### ISSUE TITLE
Python module not loading when running YARN Application

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#1001]
So I'm trying to run the k-means example [k-means.txt](https://github.com/radical-cybertools/radical.pilot/files/226746/k-means.txt), and I cannot get the CUs to execute properly when using YARN. When I check the Ystderr, I get an error that says 

` from sklearn.metrics.pairwise import euclidean_distances
ImportError: No module named sklearn.metrics.pairwise
`

I thought that loading the proper python executable would take care of the dependency, but it is not doing so for some reason. I always get this error when I try to load the proper python module, and it causes the pilot and all CUs to fail.

**Comment by iparask** [comment]
Nikhil, can you give a try to branch fix/yarn_preexec_1001?

**Comment by Nikhil-Shenoy** [comment]
Thanks Ioannis! This is the response we agreed on:

When running with resource = 'xsede.stampede_yarn':

cud.executable = 'python'
cud.arguments = ["-c", 'import sklearn; print sklearn.__version__']
cud.pre_exec = ["module purge", "module load TACC", "module load intel/15.0.2", "module load python/2.7.9"]

This is in response to the error that the script wasn't loading "sklearn.pairwise.something" properly

**Comment by iparask** [comment]
The ticket will stay open until PR #1003 is accepted.
