### ISSUE TITLE
Inform the user about spark cluster configuration

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1004]
This is a feature request. We would like to provide information to the user about the Spark cluster information, like Master Node IP, allowing the user to monitor the execution of Spark jobs or the Status of the Spark cluster.

**Comment by iparask** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/feature/resource_cfg_to_agent_spark/src/radical/pilot/agent/lm/spark.py#L141

The Lines!

**Comment by georgeha** [comment]
Added spark's master url in resource_detail of pilot. See [here](https://github.com/radical-cybertools/radical.pilot/commit/c260de029098ecaae362fc876726707413008a7b).

@iparask  should I close this issue?

**Comment by iparask** [comment]
Let me and AndreL test it and I will close it.

**Comment by iparask** [comment]
It works for me

@drelu, can you confirm if it works or not?

**Comment by andre-merzky** [comment]
This is considered resolved.
