### ISSUE TITLE
Merge Spark Branches

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1005]
Hello George,

do you think that branches ```feature/resource_cfg_to_agent_spark``` and ```feature/spark```?

That will help maintenance and the release of the Spark feature at some point in the near future.

**Comment by iparask** [comment]
Are the branches merged? If yes feel free to close this ticket

**Comment by georgeha** [comment]
Yes. Everything is merged in  feature/spark branch.

On Fri, Apr 29, 2016 at 8:51 PM, Ioannis Paraskevakos <
notifications@github.com> wrote:

> Are the branches merged? If yes feel free to close this ticket
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/radical-cybertools/radical.pilot/issues/1005#issuecomment-215828877>
>



-- 
Γιώργος Χαντζηαλεξίου

**Comment by andre-merzky** [comment]
Can you remove the old branches then, please?  I'd rather see you doing it, better then me screweing up and deleting the wrong ones :P   Thanks!

**Comment by georgeha** [comment]
Yes, I deleted them and I kept only feature/spark.

**Comment by andre-merzky** [comment]
feature/resource_cfg_to_agent still exists - can that go away then?

**Comment by georgeha** [comment]
oh I see. For some reason I could not see it on the website and I thought it was deleted properly. I think now it is okay

**Comment by andre-merzky** [comment]
thanks! :)
