### ISSUE TITLE
Constantly Check log files

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1024]
I need to continuously check spark's log files, because they keep updating while spark is running. Is there any component that is keep executing so I can put my code there?

Thanks,
G.

**Comment by iparask** [comment]
Check this:

http://stackoverflow.com/questions/12523044/how-can-i-tail-a-log-file-in-python

**Comment by georgeha** [comment]
select.register and select.poll do not exist in mac os

**Comment by andre-merzky** [comment]
Those are python calls, and exist independent from the OS.  If you look for something to watch the file in a shell, you can use `tail -f filename`.

**Comment by georgeha** [comment]
Is this non-blocking ? If I put code to continuously check spark logs  after  [this](https://github.com/radical-cybertools/radical.pilot/blob/feature/resource_cfg_to_agent_spark/src/radical/pilot/agent/lm/spark.py#L163) line will it work?

**Comment by andre-merzky** [comment]
This line is only called once.  Since the read via select.poll is non-blocking, you will read at most once in that case.

**Comment by georgeha** [comment]
select.poll is not implemented for mac os

**Comment by andre-merzky** [comment]
Why do you think that?  Did that give an error?  select is a POSIX call, MacOS is posix compliant, I would be suprised if that does not exist...

**Comment by georgeha** [comment]
https://docs.python.org/2/library/select.html#select.poll 
Look it says that is not supported for all operating systems. I

**Comment by iparask** [comment]
George, why do you want to check log files continuously?

You can check once if the Cluster is spawned correctly ( like [this](https://github.com/radical-cybertools/radical.pilot/blob/feature/yarn/src/radical/pilot/agent/lm/yarn.py#L247) ) and then if a CU fails because the cluster is down, i.e. the Master, you can raise an exception and kill the execution worker.

**Comment by andre-merzky** [comment]
> https://docs.python.org/2/library/select.html#select.poll  Look it says that is not supported for all operating systems.

Yeah, I would expect that non-POSIX systems like Windows don't support it.  Why do you think that MacOS does not?

**Comment by andre-merzky** [comment]
Ok, I checked - it seems select.poll is disabled in the default python build on MacOS, but actually works if you build python yourself.  Yet another MacOS-WTF I guess... :package: 

So, then its back to Iannis question: are you sure you need non-blocking reads?  Because that implies that you need to spawn an async thread or whatever to do the reads -- but at that point you can also read synchronously in the async thread...

**Comment by georgeha** [comment]
@iparask I checked that but it doesn't actually catch the Error. To give you an example, I defined wrong master address and I tried to start the cluster, the way you recommended.

```
 start_spark = sb.check_output([spark_home + '/sbin/start-all.sh'])
>>> start_spark
'starting org.apache.spark.deploy.master.Master, logging to /home/user/spark-pre-build/spark-1.4.1-bin-hadoop2.6/sbin/../logs/spark-user-org.apache.spark.deploy.master.Master-1-snf-463763.out\nlocalhost: starting org.apache.spark.deploy.worker.Worker, logging to /home/user/spark-pre-build/spark-1.4.1-bin-hadoop2.6/sbin/../logs/spark-user-org.apache.spark.deploy.worker.Worker-1-snf-463763.out\nlocalhost: starting org.apache.spark.deploy.worker.Worker, logging to /home/user/spark-pre-build/spark-1.4.1-bin-hadoop2.6/sbin/../logs/spark-user-org.apache.spark.deploy.worker.Worker-2-snf-463763.out\n'
```

It seems that the cluster is looks like the cluster is up and running, but checking the log files...

`16/04/29 16:17:41 ERROR NettyTransport: failed to bind to /83.212.114.162:7077, shutting down Netty transport
  4 16/04/29 16:17:42 ERROR NettyTransport: failed to bind to /83.212.114.162:7078, shutting down Netty transport
  5 16/04/29 16:17:42 ERROR NettyTransport: failed to bind to /83.212.114.162:7079, shutting down Netty transport`


So, I was thinking if there is a way to keep checking the log files continuously and Raise a RuntimeError in case any is found in the log files.

**Comment by andre-merzky** [comment]
What happens if you submit a CU to a faulty cluster?  If that fails, and the error is separable from the CU workload failing, then you can raise an exception at that point and the pilot will shut down.

**Comment by georgeha** [comment]
I tried that with a wrong master ip address  on Stampede and rp catches the error, while trying to execute a CU. Do you think that's okay?

**Comment by andre-merzky** [comment]
Yes.  That is a much simpler control flow, and you have to handle that error anyway.

**Comment by andre-merzky** [comment]
I consider this as resolved.  Please reopen if any problems remain!
