### ISSUE TITLE
cu.name in .prof by default

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1030]
I would highly appreciate if cu.name would be available in rp's .prof file by default for all CUs.

**Comment by vivek-bala** [comment]
+1

**Comment by marksantcroos** [comment]
But you probably wouldn't appreciate it if the files would explode and execution took longer :)

**Comment by andre-merzky** [comment]
profiling is for taking times, and we are indeed hesitant to add information for convenience.  In fact, we probably change to a binary format at some point, and reduce the amount of information further.

The cu IDs can be mapped to CU names via the DB json entries.  I understand that this is an additional step and thus not really convenient -- but as Mark said, we are not easily trading off performance against convenience in the RP layer.
