### ISSUE TITLE
job submission problem on smic

### ISSUE THREAD

**Issue by shayanshams66** [radical-cybertools/radical.pilot#1031]
Hi all,
I am using radical pilot to submit a job on supermic, all the setting is fine and I can submit job like /bin/date or cp and etc but the program that I am using starts with the perl script but it does not need perl to be before the script name to execute what I mean is:
if I write "perl rnnotator.pl " in command line it throws error
so in order to run it I just should use script itself like "rnnotator.pl"
so I put rnnotator.pl as cud.executable
Job is submitted to scheduler queue but it fails after couple of seconds 
although I change the code to get error output from radical pilot but It only shows exit code not the error
I am using pilot version 0.40.1
I attached two output files
one when vebos=debug
one when REPORT=debug
thanks alot
Shayan
[ticket.txt](https://github.com/radical-cybertools/radical.pilot/files/273749/ticket.txt)
[ticket2.txt](https://github.com/radical-cybertools/radical.pilot/files/273748/ticket2.txt)

**Comment by marksantcroos** [comment]
Is rnnotator.pl already on supermic?

**Comment by shayanshams66** [comment]
yes it is and I can run the program with ssh

**Comment by andre-merzky** [comment]
I don't have access to supermic, so can't check, thus a couple of questions: 

* Do you need a module to get perl enabled on compute nodes?  
* What is the first line in your script?
* what is the error you see when you run `perl rnnotator.pl`?

Could you please pack the pilot sandbox under `$HOME/radical.pilot.sandbox/<session_id>-<pilot_id>/` on supermic in a tarball and send it to me by mail?

Thanks, Andre.

**Comment by shayanshams66** [comment]
Hi Andre,
Thanks for the prompt reply.
I changed the variable env so I am not getting error if I run perl rnnotator.pl now although job submission with rp still fails.
answer to your questions:
1- I am loading perl module via pre_exec
cud.pre_exec = ['module load gcc/4.9.0', 'module load perl/5.16.3/INTEL-14.0.2','module load blat/0.35/INTEL-14.0.2']
2- I didnt get your question what is first line in my perl script or rp?
3-as I said I am not getting any error after changing some env variables although rp still fails.
I can not attach the radical pilot sandbox here since it is more than 10MB so I email it to Ming
Thanks alot

**Comment by andre-merzky** [comment]
if you script now runs without explicitly calling perl, then ignore No.2.  Lets see what Ming finds...

**Comment by andre-merzky** [comment]
FWIW, you can print `cu.stdout` and `cu.stderr` for most failing CUs, maybe that gives you more insight...

**Comment by mingtaiha** [comment]
@andre-merzky, I checked out the RP sandbox which Shayan had sent me. It seems very odd that all of the agent_0.Agent<...>.log files are all 0B. It's as if the agent never gets to AgentInputStagingPending.

The agent_0.err file gives
```
2016-05-23 23:47:10,389: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.7 |Continuum Analytics, Inc.| (default, Jun 2 2014, 12:34:02) [GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]
2016-05-23 23:47:10,389: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 62446
2016-05-23 23:47:10,389: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2016-05-23 23:47:10,389: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.40.1
2016-05-23 23:47:10,391: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.7 |Continuum Analytics, Inc.| (default, Jun 2 2014, 12:34:02) [GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]
2016-05-23 23:47:10,391: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 62446
2016-05-23 23:47:10,391: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2016-05-23 23:47:10,391: radical.pilot       : MainProcess                     : MainThread     : INFO    : radical.pilot        version: 0.40.1
Exception KeyError: KeyError(47126674275328,) in <module 'threading' from '/usr/local/packages/python/2.7.7-anaconda/lib/python2.7/threading.pyc'> ignored
```

Also, the file unit.000000/STDERR recorded
```
Died at /work/sshams2/Rnnotator-3.4.0/build/lib/site_perl/5.16.3/JGI/Bio/Assem/MultipleAssembly.pm line 294.
```
which leads me to suspect it may be some problem with the code itself.

@shayanshams66, can you please look in your unit.000000 folder/rnnotator_run folder and check if your code actually runs, and what stage of the process it gets to? I see that the script gets to the pre-processing stage, but I'm not sure if that's normal for your script.

**Comment by andre-merzky** [comment]
Re log files: please re-install radical.utils from the devel branch -- there was a regression in the logging module which has recently been fixed.

But yes, it seems that the actual application fails on the perl level, that needs to be debugged in the application on supermic I think (the logging regression is not causing this).

**Comment by mingtaiha** [comment]
@shayanshams66, the radical-utils page is here in case you are looking for it
`https://github.com/radical-cybertools/radical.utils`

**Comment by shayanshams66** [comment]
Thanks Guys
I debugged my script and now its fine couple of questions though, I saw that RP keeps the directory under unit.00000 /rnnotator_run can I change the directory to be under my home directory like $HOME/rnnotator_run??
we have another super computer which uses lsf as scheduler does RP support LSF ?

**Comment by marksantcroos** [comment]
> I debugged my script and now its fine couple of questions though, I saw that RP keeps the directory under unit.00000 /rnnotator_run can I change the directory to be under my home directory like $HOME/rnnotator_run??

Ideally you confine yourself to where RP places you, to make sure there is full isolation between all tasks.

> we have another super computer which uses lsf as scheduler does RP support LSF ?

There is support for LSF, which has been used for two distinct systems, but that didn't have much exposure so far.

**Comment by shayanshams66** [comment]
Thanks
can you please elaborate more on the support for LSF, Does that mean I need to just make a config file to define lsf as scheduler or there are other changes that need to be done?

**Comment by marksantcroos** [comment]
In theory that should be enough, but it will probably require some trial and error to get it right, especially as LSF didn't receive so much attention.

All the currently provided configs are here: https://github.com/radical-cybertools/radical.pilot/tree/devel/src/radical/pilot/configs

With the most recent LSF example here: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_yale.json

**Comment by shayanshams66** [comment]
thanks alot Mark

**Comment by andre-merzky** [comment]
Closing as resolved.  Please open a new ticket in case you need support with LSF setup!
