### ISSUE TITLE
Jobs HELD on OSG

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1032]
Jobs submitted onto OSG are held, regardless of the size of the job. I found that for jobs up to size 1024, the hold reason so far is:

Hold reason: Error from glidein_542261_602348192@CRUSH-OSG-10-5-17-5: STARTER at 10.5.17.5 failed to send file(s) to <129.79.53.198:9615>: error reading from /var/lib/condor/execute/dir_542257/glide_tQmMit/execute/dir_549597/pilot.0000.log.tgz: (errno 2) No such file or directory; SHADOW failed to receive file(s) from <128.230.171.105:6894>

Jobs tend to be held around 45s-90s after Running. However, two runs have been held quite a bit after the job starts running. One job was held 03:40:23 (hh:mm:ss) after job started running. Another was held 09:22:38 into running. 

The commands used to capture the error messages of the runs:
condor_q -analyze
condor_q -better-analyze -global 

**EDIT: It should be noted that I am using the Round Robin scheduler as opposed to the Backfilling scheduler due to issues encountered in previous testing. Backfilling scheduler testing will continue after the conclusion of the Round Robin scheduler testing.

**Comment by mingtaiha** [comment]
I will continue to run experiments to see how OSG behaves. Though this is not a bug on the RP side AFAIK, I hope more prodding of OSG will give us a better understand of what is going on.

**Comment by andre-merzky** [comment]
Thanks Ming, I realized the same.  I am working on a fix which creates the expected outputs as empty files, so that the pilots will not be held.  That might take a while to get fully implemented though, so please leave the ticket open.

**Comment by mingtaiha** [comment]
Just a quick update on more notes which I have recorded.

I ran jobs of up to 2048 Cores. The job ran for 01:01:16:33 (dd:hh:mm:ss) before it was held. The hold reason was the same as the one listed above.

I also ran jobs with 2 Pilots, 4 Pilots, 8 Pilots, each with 1 unit per pilot.. Here, I noticed that there were some odd behavior. 

When the 2 pilots become active and finishes the execution of each unit, one of the pilot exits cleanly (no longer show when using condor_q) while the other pilot is held, for the same reason as before. According to the callback messages which I have recorded, however, both pilots enter the Cancelled state. Also, the terminal in which I ran the script return control of the terminal to me, which suggests that the pilots were exited correctly and that the script cleanly finished. 

A similar situation happened for 4 Pilots. 1 Pilot was cancelled cleanly but 3 Pilots were held. Each pilot entered the Cancelled state, and there was a clean return of control of the terminal.

I was unable to run 8 Pilots. I tried 3 times. For each run, there always be at least one pilot that was held for the reason given above). The number of pilots that were held varied from each try. I would put the holding rate to about ~33%

Next will be to check the log files, as I suspect that RP did not record all of the callback messages.

**Comment by marksantcroos** [comment]
> I ran jobs of up to 2048 Cores.

Can you specify a bit more what this means?

**Comment by mingtaiha** [comment]
I meant 2048 Units, my bad.

**Comment by marksantcroos** [comment]
> On 29 May 2016, at 22:35 , mingtaiha <notifications@github.com> wrote:
> I meant 2048 Units, my bad.

Thanks!

**Comment by mingtaiha** [comment]
I've noticed sometimes jobs are HELD on OSG, the bootstrapper fails. Namely the machine does not install RP correctly. Maybe either one of you have noticed this too?

**Comment by andre-merzky** [comment]
Yes, noted, and this is fixed in the new code already.  The reason for the HOLD state was that condor could not find files it is supposed to stage out -- so it waits for those to appear (I don't know how they could possibly appear after the job died, but, whatever).  We now touch all files before we even start, so that should not happen anymore...

**Comment by andre-merzky** [comment]
This is resolved now.
