### ISSUE TITLE
CUs fail on Comet

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1033]
Hello,
I am running some experiments on Comet with the feature/spark branch, without spark and some CUs fail with:
```
ssh_exchange_identification: Connection closed by remote host
```
I tried to increase the number of cores per CU to 2, but again I get the same thing. Is there a solution to that?

**Comment by marksantcroos** [comment]
Can you explore if it improves if you increase to 4 or even 8 cores per task?

**Comment by iparask** [comment]
With 4 cores per CU and 128 cores in total, that it runs. I will keep updating as I progress. I want to run it for 64, 128 and 256 concurrent CUs.

**Comment by marksantcroos** [comment]
If 4 cores gives reliable results, I would suggest to use that and thereby increase your total core count to achieve your desired cu concurrency.

**Comment by iparask** [comment]
It worked with 4 cores per CU. I stabled to something else. As soon as I figure it out I may reopen the ticket.

**Comment by andre-merzky** [comment]
Mark, is there any argument against switching to `orte-submit` as comet default?

**Comment by marksantcroos** [comment]
Mainly not being able to use pre-compiled MPI modules.

**Comment by andre-merzky** [comment]
yeah, right.  We might nevertheless want to start promoting the ORTE route, given that there is no solution for the ssh limitation, and the default use cases mostly fail... :/  Lets discuss that on the call...

**Comment by marksantcroos** [comment]
http://i.imgur.com/J2MTlcV.png

**Comment by iparask** [comment]
Should I give it a try?

**Comment by andre-merzky** [comment]
Feel free to -- but I do not know in what state the ORTE configuration is.  Please let us know how it goes!

**Comment by iparask** [comment]
The LRMS config hook failed with the following error:
```
2016-05-30 19:15:25,523: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : lrms config hook failed
Traceback (most recent call last):
  File "/home/iparask/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 151, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/home/iparask/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 152, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/home/iparask/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 46, in lrms_config_hook
    raise Exception("Couldn't find orte-dvm")
Exception: Couldn't find orte-dvm
```

**Comment by marksantcroos** [comment]
> The LRMS config hook failed with the following error:

Yes, its currently just configured for my account, thats why it is not "supported". We will be working on that over the coming period.

**Comment by andre-merzky** [comment]
What is the status of this ticket?  Mark, you wanted to document ORTE deployment...

**Comment by iparask** [comment]
Anything new?

**Comment by marksantcroos** [comment]
No, I'll let you know once it is available on Comet.

**Comment by marksantcroos** [comment]
@andre-merzky If you would like to use this for the tutorial, I can increase the priority.

**Comment by andre-merzky** [comment]
meeee? ;)  But in general I think it would be good if the examples work on all xsede machines, indeed...

**Comment by andre-merzky** [comment]
Is there a chance to get this solved in the next day or two, for the tutorial release?

**Comment by marksantcroos** [comment]
Yes

**Comment by andre-merzky** [comment]
Thanks a lot, Mark!

**Comment by marksantcroos** [comment]
This should be fixed in the tutorial branch now.

**Comment by andre-merzky** [comment]
Confirmed as fixed.
