### ISSUE TITLE
multi-node mpi units fail on Gordon 

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1034]
```
[amerzky@gordon-ln1 unit.000514]$ mpirun_rsh -np 64 -hostfile ../rp_hostfileaHdIJ7  /bin/true
/usr/bin/xauth:  error in locking authority file /home/amerzky/.Xauthority
/usr/bin/xauth:  error in locking authority file /home/amerzky/.Xauthority
/usr/bin/xauth:  error in locking authority file /home/amerzky/.Xauthority
intel/2013.1.117(49):ERROR:105: Unable to locate a modulefile for 'mkl'
intel/2013.1.117(49):ERROR:105: Unable to locate a modulefile for 'mkl'
[gordon-ln1.sdsc.edu:mpirun_rsh][connect_socket] could not connect to gcn-14-31:60727
[gordon-ln1.sdsc.edu:mpirun_rsh][wfe_thread] Internal error: transition failed

[amerzky@gordon-ln1 unit.000514]$ echo $?
1
```

It seems to me that we run out of ssh connections to the nodes: the nodes have 15 cores, and I can only get 10 connections open.  That will rule out 16 single-core units via ssh -- but I don't know if mpirun-rsh runs into the same limit or has a different problem... :/

**Comment by marksantcroos** [comment]
mpirun will use ssh underneath, and have the same limit. There is already a ticket about this on Gordon I believe.

**Comment by andre-merzky** [comment]
Do you know if mpirun_rsh keeps the ssh tunnel open?  That would allow to at least run multiple smaller mpi jobs -- otherwise that would basically mean that we can only use 10 out of 16 cores on each node on Gordon (single-core CUs are also spawned with ssh...)

**Comment by marksantcroos** [comment]
You should be able to run dual core tasks, not sure if that is related to the first part of your question.

**Comment by andre-merzky** [comment]
> You should be able to run dual core tasks

Mpirun for 2-core tasks would again use 2 ssh channels, right?  So I could run 5 of those, ie. 10 cores out of 16?

Yes, the first part relates: if mpirun releases the channels after startup, we might have enough free for more than 5 2-core tasks.  Or am I missing something?

**Comment by marksantcroos** [comment]
> Mpirun for 2-core tasks would again use 2 ssh channels, right?

I would say 1, not 2. Why do you think so?

**Comment by andre-merzky** [comment]
This is becoming confusing...  Lets rewind.

The original problem is that a single 64-core MPI task is not getting executed, and apparently it seems an ssh channel starvation, or so I think from the message.  Any idea how to interpret that?  There is no other CU active at this point.

**Comment by andre-merzky** [comment]
FWIW, while the pilot was still active, I could run a 10-core MPI task with the same nodelist, but not a 16-core mpi task, with the same error message as above.

**Comment by andre-merzky** [comment]
I consider this to be another instance of 'switch-to-ORTE-asap' ...  Closing since we don't see any actionables wrt. to the ssh starvation.
