### ISSUE TITLE
Support for submitting to shared queue on comet?

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1038]
I was wondering if it was possible to submit to the shared queue on Comet. Jobs submitted to the shared queue must use less than 1 Node (<24 cores). pilot_launcher_worker.py converts all core
request values into multiples of a node.

I know I can change the 'cores_per_node" field in the config file as a workaround. Is there are more proper way of doing this though?

**Comment by marksantcroos** [comment]
Alternatively you can also change it programmatically: http://radicalpilot.readthedocs.io/en/latest/machconf.html#customizing-resource-configurations-programatically

**Comment by mingtaiha** [comment]
That's a much cleaner way to do it. Thanks!

**Comment by mingtaiha** [comment]
I am able to choose which queue to use. I guess that's that
