### ISSUE TITLE
Update needed to getting_started_osg.py on feature/split_module_2

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1042]
With the restructuring of the code on `feature/split_module_2`, it seems that the scheduler constants are missing. Namely, `rp.SCHED_BACKFILLING` and `rp.SCHED_ROUND_ROBIN` do not work [here](https://github.com/radical-cybertools/radical.pilot/blob/feature/split_module_2/examples/getting_started_osg.py#L16). In order to specify the scheduler, I need to set `SCHED = "backfilling"` or `SCHED = "round_robin"`.

It's a minor change, so just documenting this alteration as a reference. @andre-merzky, should the constats be added back? IMO this point should be considered before a tutorial for new users.

**Comment by andre-merzky** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/feature/split_module_2/src/radical/pilot/umgr/scheduler/base.py#L16

The definitions are now under `radical.pilot.umgr.scheduler` -- which is probably somewhat cumbersome indeed... :P

**Comment by marksantcroos** [comment]
Exposing them in the __init__.py a couple of levels higher should be enough, right?

**Comment by andre-merzky** [comment]
yes

**Comment by andre-merzky** [comment]
The example has been updated.
