### ISSUE TITLE
investigate ticket templates

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1056]
Github has introduced a template for new tickets that could help people provide the right information.

**Comment by andre-merzky** [comment]
Sounds nice!  Do you have a pointer?  Could not find any info on a (very) quick search...

**Comment by marksantcroos** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates
and
https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by andre-merzky** [comment]
Thanks!

**Comment by andre-merzky** [comment]
implemented and about to be released.
