### ISSUE TITLE
time-partitioning of agent

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1057]
possibly rendered as `pilot.reconfig(pd)`

**Comment by iparask** [comment]
I am afraid that passing it as a reconfig is not very elegant way of doing it, Let me think about it and get back at you.

**Comment by iparask** [comment]
Wouldn't ```pilot.reconfig(pd)``` allow the submission of a pilot description that is completely different than the one the pilot was started with?

For example:
```
pdesc = rp.ComputePilotDescription()
pdesc.resource = "xsede.stampede"

pilot = pmgr.submit_pilots(pdesc)

pd = rp.ComputePilotDescription()
pd.resource = "xsede.comet"

pilot.reconfig(pd)
```

How about this description to allow reconfiguring only the launch method(s)?

**Comment by marksantcroos** [comment]
> Wouldn't pilot.reconfig(pd) allow the submission of a pilot description that is completely different than the one the pilot was started with?

Depends on the implementation :) I wouldnt worry about those details for now.

> How about this description to allow reconfiguring only the launch method(s)?

You could consider creating some "sub-configs" where you put the things that are re-configurable (e.g. the launch methods, but possibly more)

**Comment by andre-merzky** [comment]
`reconfig` would not create a new pilot job, but only reconfigure the agent (or restart the agent with a different config) for an *existing* pilot job.

**Comment by andre-merzky** [comment]
v2
