### ISSUE TITLE
RADICAL Pilot Overview - Suggestions

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1066]
1. The introductory paragraphs suggests that this section shows what problems RP will and will not solve. There is no mention of the problems which RP will not solve in this page.
2. The wording of the first bullet point in Section 2.1 is awkward. One suggestion is 'abstract the heterogeneity of distributed resources so user applications can interact with resources using a single API'

**Comment by andre-merzky** [comment]
outdated
