### ISSUE TITLE
ssh config usability depends on exact hostname

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1070]
Alessia hit the problem where the ssh config looks nice and shiny for `stampede.tacc.xsede.org`, but our RP configs used `stampede.tacc.utexas.edu`.  Bummer...  We might want to provide an ssh config stub of sorts?

**Comment by marksantcroos** [comment]
That, or at least a list of canonical hostnames.

**Comment by mturilli** [comment]
Should we have a command like `radical-pilot-hostnames` that parses the available resource config files returning the list of hostnames?

**Comment by andre-merzky** [comment]
The resource configs are available programmatically:
```
import radical.pilot as rp
s = rp.Session()
print s.list_resources()
```

and each resource dict can be retrieved via `session.get_resource_config(label)`.

**Comment by andre-merzky** [comment]
To clarify: I think this is simple enough to *not* dedicate an tool for it.  We might at some point consider to provide a command line toolset for the full API, that would be interesting - but I'd think that's out of scope right now.

**Comment by andre-merzky** [comment]
moved to v2.

**Comment by andre-merzky** [comment]
outdated, and not really an RP problem
