### ISSUE TITLE
virtualenv version mismatch in docs

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1072]
In section 3.4, the VE tarball url points to v1.9 whereas in the requirements in 3.1 we specify virtualenv>=1.11.

**Comment by mturilli** [comment]
Created PR  #1840 but found that other parts of the same documentation are probably badly outdated. Also, should we add a label `topic:installation`?

**Comment by andre-merzky** [comment]
I added `topic:deployment`

**Comment by andre-merzky** [comment]
merged - thanks!
