### ISSUE TITLE
radicalpilot-close-session on split_module_2

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1075]
I tried to run `radicalpilot-close-session -m export -s <session_id>` to get a JSON log file, but I encountered an error. Upon inspection of my MongoDB, I found that there is no such JSON file. I was wondering if it is possible to get a log file of the run?

**Comment by andre-merzky** [comment]
The db will not contain much in terms of logging - it basically represents the state of the session at any point in time.  When you close the session, the DB entry is deleted.  You can avoid that by using `session.close(cleanup=False)`, and then you can export the DB entry as json.

**Comment by mingtaiha** [comment]
Thanks. Message to the wanderer.
