### ISSUE TITLE
argument consistency across profiling functions

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1076]
argument is 'dburl' in https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/utils/session.py#L17-L18

argument is 'db' in https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/utils/session.py#L171

Might be better to use either db/dburl in both places.

**Comment by andre-merzky** [comment]
Well, in the first case it wants a database URL, in the second case it expects a database handle (a mongodb object instance).  One could argue that we should pass the same types -- but the names are correct I think.  In this case at least - in general, there exist quite some inconsistencies indeed :/

**Comment by vivek-bala** [comment]
Ah ok. But then can I pass the mongodb url to get_session_frames() (without env variable method) ? There is a specific argument for fetch_profiles().

**Comment by andre-merzky** [comment]
No, at the moment you can't.  Feel free to add such an argument!

**Comment by vivek-bala** [comment]
ok :)

**Comment by vivek-bala** [comment]
Is it ok if I push/merge to devel or should I leave it in a separate branch ?

**Comment by andre-merzky** [comment]
Please create a branch and pull request - thanks!

**Comment by andre-merzky** [comment]
Lets address this in the next release cycle, which is focusing on profiling / analytics anyway...

**Comment by mturilli** [comment]
@vivek-bala, @andre-merzky Is this addressed? Was a PR made and merged?

**Comment by mturilli** [comment]
Fixed
