### ISSUE TITLE
incorrect python picked up by CUs on comet 

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1083]
RP version: 0.40.4

Trying to use the python module on comet using "module load python" in the pre exec fails. The python of the RP (from the VE) is what is being picked up.

from radical-*.sh:

```
#!/bin/sh


# Change to working directory for unit
cd /home/vivek91/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017001.0016-pilot.0000/unit.000000
# Pre-exec commands
module load python
module load gdal
# Environment variables
export RP_SESSION_ID=rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017001.0016 RP_PILOT_ID=pilot.0000 RP_AGENT_ID=agent_0 RP_SPAWNER_ID=agent_0.AgentExecutingComponent.0.child RP_UNIT_ID=unit.000000
# The command to run
/home/marksant/openmpi/installed/rhc/bin/orte-submit  --hnp "3510042624.0;tcp://10.22.255.62,192.168.7.62,192.168.15.62,192.168.23.62,192.168.31.62,198.202.118.218,10.21.255.62:46491;ud://243491.20464.1" -x LD_LIBRARY_PATH -x PATH -x PYTHONPATH -np 1 -host comet-03-49 /bin/bash "-l" "-c" "which python"
RETVAL=$?
# Exit the script with the return code from the command
exit $RETVAL
```

STDOUT:

```
/home/vivek91/radical.pilot.sandbox/ve_comet/bin/python
[ORTE] Task: 0 is launched! (Job ID: [53559,1])
[ORTE] Task: 0 returned: 0 (Job ID: [53559,1])
```

**Comment by marksantcroos** [comment]
Yeah, related to all the other tickets on env. This branch doesn't include some of the "fixes" for this particular issue as it breaks basic functionality.

**Comment by iparask** [comment]
Which is this branch?

**Comment by marksantcroos** [comment]
afaik 0.40.4 == tutorial branch.

**Comment by vivek-bala** [comment]
> This branch doesn't include some of the "fixes" for this particular issue as it breaks basic functionality.

Okk. Does this mean the fix is in a different branch ? If so, I'd like to give them a try.

**Comment by marksantcroos** [comment]
The "fix" is in devel, but it breaks other things, like normal execution.
So we need a proper fix that gives CUs a clean environment, but doesn't break the agent launch itself.

**Comment by iparask** [comment]
I think this is the [reason](https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/agent/lm/orte.py#L225). 

Based on [orte-submit documentation](https://www.open-mpi.org/doc/v2.0/man1/orte-submit.1.php), I believe that the ```-x``` option copies existing environment variables to the remote nodes before executing the program.

**Comment by marksantcroos** [comment]
Please create a self-contained example as per the instructions in https://github.com/radical-cybertools/radical.pilot/tree/devel/tests/cu_env so that we can have a repeatable piece of code that we can use to help resolve this.

**Comment by vivek-bala** [comment]
Created a PR to devel. Successful on devel, fails on master.

**Comment by andre-merzky** [comment]
Vivek, can this be closed with the latest devel?

**Comment by andre-merzky** [comment]
Vivek, another ping if this can be closed with the latest env fixes?

**Comment by vivek-bala** [comment]
Oops. Sorry, I'll try the fix_1034_am branch now.

**Comment by andre-merzky** [comment]
This is considered fixed.
