### ISSUE TITLE
Submitting Creating Job using Job Description on split_module_2 branch

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1084]
I have encountered to following error when submitting jobs to SAGA (feature/osg_optimizations_run_job) using the Job Descriptions defined in [default.py](https://github.com/radical-cybertools/radical.pilot/blob/feature/split_module_2/src/radical/pilot/pmgr/launching/default.py#L467). The error is found in pmgr.launching.0.child.log (from the client side):

```
2016-07-24 23:24:19,940: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : worker <bound method Default.work of <Default(pmgr.launching.0, started)>> failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1337, in run
    self._workers[state](things)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 295, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 470, in _start_pilot_bulk
    jc.add(js.create_job(jd))
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/job/service.py", line 295, in create_job
    raise se.BadParameter._log (self._logger, msg)
BadParameter: 'JobDescription.Project' (tg-mcb090174) is not supported by adaptor saga.adaptor.shell_job (/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/job/service.py +295 (create_job)  :  raise se.BadParameter._log (self._logger, msg))
```
This error occurs in line 467, after a job.Container object has been created, when the Default Class of the PMGR is creating jobs to append to the Job Container. Though the error occurs on the SAGA level, I believe that the issue may be due to the job description created and that there may be some error in submission of the job description when trying to create a Job object.

I have attached all of the files which I can think of. This includes the client logs and profiles, SAGA debug outputs, and agent files. There are no agent logs, but I have included all agent files for the sake of completeness. The aforementioned files are attached as a zip file.

[rp.session.radical.mingtha.017006.0001.zip](https://github.com/radical-cybertools/radical.pilot/files/380512/rp.session.radical.mingtha.017006.0001.zip)

The following environment variables have been used
```
RADICAL_PILOT_PROFILE=TRUE
RADICAL_PILOT_VERBOSE=DEBUG
RADICAL_SAGA_VERBOSE=DEBUG
RADICAL_SAGA_PTY=DEBUG
SAGA_PTY_SSH_TIMEOUT=300
```

The following package__version have been used:
RP__feature/split_module_2
SAGA__feature/osg_optimizations_run_job
RU__feature-raise_on

**Comment by andre-merzky** [comment]
Ah, bugger, that makes sense...  Let me fix that...

**Comment by andre-merzky** [comment]
I pushed a fix -can you try it, please?

**Comment by mingtaiha** [comment]
I just tried the fix. I get a new error now:
```
2016-07-25 01:29:31,130: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : worker <bound method Default.work of <Default(pmgr.launching.0, started)>> failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1337, in run
    self._workers[state](things)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 295, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 466, in _start_pilot_bulk
    jc.run()
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/task.py", line 416, in run
    % (thread.exception, thread.traceback))
NoSuccess: thread exception: Service.run is not implemented for saga.SLURMJobService (container_run) (/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py +80 (wrap_function)  :  inspect.getmembers (cpi_sync_function)[15][
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/utils/threads.py", line 154, in run
    self._result    = self._call(*self._args, **self._kwargs)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 80, in wrap_function
    inspect.getmembers (cpi_sync_function)[15][1]))
NotImplemented: Service.run is not implemented for saga.SLURMJobService (container_run) (/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py +80 (wrap_func
tion)  :  inspect.getmembers (cpi_sync_function)[15][1])))
 (/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/task.py +416 (run)  :  % (thread.exception, thread.traceback)))
```

The error occurs in line 466 of [default.py](https://github.com/radical-cybertools/radical.pilot/blob/feature/split_module_2/src/radical/pilot/pmgr/launching/default.py#L466), when the function calls the job container object to run the containers in the job.

In a related note, I found that in line 406 of [task.py](https://github.com/radical-cybertools/saga-python/blob/feature/osg_optimizations_run_job/src/saga/task.py#L406), you have `task.run`. Is `run` a method or an attribute of the `Task` class. I'm asking to make sure because I see `run` defined as a method of the `Task` class, but I don't see an attribute called `run` in the `Task` class.

**Comment by andre-merzky** [comment]
Right.  So, that is good news, in the sense that the `run_job()` seems to work.

Now however the code stumbles over the bulk job submission -- which is unexpected.  The slurm adaptor indeed does not implement bulks -- but the code should fall back to non-bulk submission in that case.  I'll check why that does not kick in...

re `task.run()`: there it is: https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/task.py#L134

**Comment by mingtaiha** [comment]
re re `task.run()`, we should change task.run to task.run() then

**Comment by andre-merzky** [comment]
Ah, now I see what you mean with the run!  Well, let me give you a code snippet - maybe it helps you figure out what is happening.  If not let me know, and I'll explain! :)

```python
# ---------------------------------------------
class Animal(object):
  
  def __init__(self, msg):
    self._msg = msg

  def say(self):
    print self._msg
# ---------------------------------------------

dog = Animal('woof')
dog.bark = dog.say

cat = Animal('Rrrrrrrr')
cat.purr = cat.say

# ---------------------------------------------
dog.bark()
cat.purr()
```

**Comment by mingtaiha** [comment]
So, `cat.purr()` points to `cat.say()` and they both call `Rrrr`,  similar for `dog`. But the objects `cat`, `dog` still call the function as a method, and the parentheses are dropped during assignment.

Going back to `task.run`, is there an assignment occurring which I am not seeing?

**Comment by andre-merzky** [comment]
Yes, indeed.  `cat.say` is a function pointer -- it points to a member function of the class.  Omitting the brackets will avoid calling it when doing so, and the actual function can be passed around and reassigned.  That works in many languages -- but is specifically simple in Python.

The version you encountered was: `t = ru.Thread.Run(task.run)`.  This is defined here:

https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/threads.py#L131

It is a shortcut for the following sequence:

```
t = ru.Thread()
t.run = cat.purr
t.start()
```

which will, upon calling `t.start()`, create a new thread and run the given function pointer in that thread (see lines 121 and 150 in the same file).

**Comment by mingtaiha** [comment]
Seeing as how I can currently run jobs on OSG using the `experiment/aimes`, derived from the `split_module_2` branch, I think we can call this closed?

**Comment by andre-merzky** [comment]
ack, thanks!
