### ISSUE TITLE
gromacs on comet barfs

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1085]
The following is submitted by Srinivas on the mailing list.
RP version 0.40.1

I've been trying to run a GROMACS simulation on SDSC Comet for quite a while. However I keep getting the following error:

```
"PMI2 initialized but returned bad values for size and rank.
This is symptomatic of either a failure to use the
"--mpi=pmi2" flag in SLURM, or a borked PMI2 installation.
If running under SLURM, try adding "-mpi=pmi2" to your
srun command line. If that doesn't work, or if you are
not running under SLURM, try removing or renaming the
pmi2.h header file so PMI2 support will not automatically
be built, reconfigure and build OMPI, and then try again
with only PMI1 support enabled."

"PMI2 failed to initialize, returning an error code of 14.
We cannot use PMI2 at this time, and your job will
likely abort."

```

I have encountered this error before, and solved it by unloading the mvapich2 module. However, even with the 'module unload mvapich2_ib' in the cudesc.pre_exec options (shown below) I get the same error. 

My compute unit description is as follows:

```
            # -------- BEGIN USER DEFINED CU DESCRIPTION --------- #
            cudesc = rp.ComputeUnitDescription()
            cudesc.environment = {'CU_NO': i}
            cudesc.executable  = "/bin/bash"  #everything to excutable
            cudesc.pre_exec = ['module unload mvapich2_ib','module load gromacs/5.1.2','source /opt/gromacs/bin/GMXRC.bash','/opt/gromacs/bin/gmx_mpi grompp -f dynamic.mdp -c init85-20.gro -o min.tpr -p 85-20.top']
            cudesc.arguments   = ['-l','-c',"/opt/gromacs/bin/gmx_mpi mdrun -s min.tpr -v -deffnm npt"]
            cudesc.input_staging = ['FRF.itp','dynamic.mdp','FF.itp','martini_v2.2.itp','85-20.top','init85-20.gro'] 
            #cudesc.output_staging = ['yeah,nope'] # file you want it back once job finishes
            cudesc.cores = 2
            cudesc.mpi = True
            # -------- END USER DEFINED CU DESCRIPTION --------- #

            cudesc_list.append(cudesc)
```

Any assistance would be greatly appreciated. If further details are required from me, please let me know.

Thank you very much.

**Comment by marksantcroos** [comment]
Two immediate comments.

- We can probably get rid of this error with some effort.
- That effort will on relatively short term be lost, as we will require a re-compiled gromacs soon.

To be continued.

**Comment by marksantcroos** [comment]
Please create a self-contained example as per the instructions in https://github.com/radical-cybertools/radical.pilot/tree/devel/tests/cu_env so that we can have a repeatable piece of code that we can use to help resolve this.

**Comment by andre-merzky** [comment]
Did this ticket have any resolution?

**Comment by andre-merzky** [comment]
Srinivas - is there any action required on this ticket?

**Comment by mingtaiha** [comment]
I see this problem, when trying to resolve #1434

**Comment by SrinivasMushnoori** [comment]
@andre-merzky My apologies, I missed this. I still see this problem. Briefly, there was semi-resolution on it since I recompiled GROMACS using openMPI, and it appeared to work, but it appears to instantiate GROMACS multiple times, i.e. every gromacs iteration appears to happen multiple times. I was in the process of doing more testing when I got sidetracked and this slipped my mind.  I'll self assign this and take it up again and update you tonight.

**Comment by andre-merzky** [comment]
No need to apologize!  Thanks for the update, let me know if you think I can help...

**Comment by mingtaiha** [comment]
Here's the script.

```
#!/usr/bin/env bash

module purge
module load gnutools/2.69
module load intel/2013_sp1.2.144
module load mvapich2_ib/2.1
module load gromacs/5.1.2
module list
gmx_mpi grompp -f /home/mingtha/bin/grompp_1000000.mdp -c /home/mingtha/bin/input.gro -p /home/mingtha/bin/topol.top -o out.tpr 2>> grompp_out_1000000
gmx_mpi mdrun -ntomp 1 -s out.tpr -c out.gro 2>> mdrun_out_1000000
```

**Comment by SrinivasMushnoori** [comment]
@mingtaiha Hey, and the CU Description from your RP script? I'm going to need to take a look at both because I need to know what I'm doing differently, etc. Thanks!

**Comment by mturilli** [comment]
@SrinivasMushnoori Can this be safely closed?

**Comment by SrinivasMushnoori** [comment]
Yes, I believe so. I think this was resolved around December 2017. Will reopen if necessary, we can close for now.
