### ISSUE TITLE
UMGR using Backfilling Scheduler does not schedule CUs to agent (experiment/aimes)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1096]
I've been trying to submit jobs to OSG using the experiment/aimes branch. The Agent can execute CUs when the Unit Manager uses the Round Robin scheduler, but not when the Unit Manager uses the Backfilling scheduler. It leads me to suspect that Backfilling Scheduler is not scheduling CUs to the pilot agents.

I was unable to find any Error messages or Traceback messages, but here are the client logs, agent logs, and OSG login files (no logs though).

[pilot2_run.zip](https://github.com/radical-cybertools/radical.pilot/files/400521/pilot2_run.zip)

**Comment by andre-merzky** [comment]
thanks for the log, this indeed looks like a backfilling scheduler problem.  Let me try to reproduce this...

**Comment by andre-merzky** [comment]
The unit manager missed out on a pilot state update.  That is fixed now in the split branch, please merge again.

Thanks, Andre.

**Comment by marksantcroos** [comment]
Thanks for fixing. I was about to request to comment the do/don't publish a bit better, as that has bewildered me in the past, but I noticed that the code in question is now actually in sync with the comments :)

**Comment by mingtaiha** [comment]
The scheduler seems to work. Not all CUs are executed, but I think that it is because of the the OSG nodes to which the pilots are scheduled to.

Closing the ticket. Thanks for the fix
