### ISSUE TITLE
Feature Request: Having two different sets of pre_execs

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1100]
Hello. I've been running AIMES-Experience experiments on OSG using RP experiment/aimes branch. When I run on OSG, I have noticed that there may be some hosts which consistently do not run units because the Agent never bootstraps (condor-job.hpc01.panther.net is a host on which I never seem to bootstrap). Also, I am to run experiments using OSG and XSEDE HPC simultaneously. In order to stage in the proper files and set up the correct virtual environment, I need to write an if/else sequence of pre_exec commands because the instructions needed to setup to correct environment (like loading the correct modules) may be different depending machines. Though it is a workaround, it feels a bit awkward since the responsibility of a CU is to execute the assigned executable, and not to ensure that the resource environment is properly setup.

It seems to me that the Agent is better suited for this task, as the Agent must by default bootstrap on a remote resource (creating a virtualenv, installing RP, RU, SAGA). It might be better to have the Agent perform any additional bootstrapping which the user specifies (like defining another virtualenv to install the needed packages) after the default bootstrapping, possibly in the form of having an agent_bootstrap_pre_exec. This way, the CUs no longer have to specify anything to set up an environment. 

The advantage of this is that it is now possible to check whether the environment is properly set up before scheduling units to an environment. An error can be raised if the environment is not properly setup to help troubleshooting.

Perhaps this information can be used in scheduling as well. There is no point in running a CU in an environment that has not been properly configured to run that same CU. By checking whether the environment on a machine is set up for some CU to run, a scheduler can decide to schedule CUs to machines with the necessary environment.

It would also be a performance problem if the CUs had to perform the same pre_execs over and over again, instead of setting up some environment per pilot and passing it on to the CU (Thanks Andre!).

**Comment by marksantcroos** [comment]
Hi Ming,

> On 07 Aug 2016, at 1:13 , mingtaiha <notifications@github.com> wrote:
> 
> When I run on OSG, I have noticed that there may be some hosts which consistently do not run units because the Agent never bootstraps (condor-job.hpc01.panther.net is a host on which I never seem to bootstrap).

Yes, in addition to improving our bootstrapper, you will have to blacklist some sites that will never be able to run our agent.
So far I've been able to run on 19 unique sites.

> Also, I am to run experiments using OSG and XSEDE HPC simultaneously. In order to stage in the proper files and set up the correct virtual environment, I need to write an if/else sequence of pre_exec commands because the instructions needed to setup to correct environment (like loading the correct modules) may be different depending machines. Though it is a workaround, it feels a bit awkward since the responsibility of a CU is to execute the assigned executable, and not to ensure that the resource environment is properly setup.

We have a concept called kernels for (exactly) this purpose:

http://radicalpilot.readthedocs.io/en/stable/apidoc.html?highlight=kernel#ComputeUnitDescription.kernel

Although this works at the (backfilling) scheduler, and not at the agent level.

The idea is that you provide a structure like:

{
'osg': {
    'pre_exec': ['module load osg_magic'],
    'executable': '/osg/bin/helloworld'
}
'xsede': {
    'pre_exec': ['module load xsede_magic'],
    'executable': '/usr/xsede/helloworld'
}}

You get the drift.

I've been looking at the code, and I can't find the code anymore that enacts this, so Andre has to comment on this whether he removed it ...

Gr,

Mark

**Comment by andre-merzky** [comment]
The kernel support is indeed gone from the split branch at the moment.  We planned to have a discussion on the future of app-kernels at some point, and This might be a good motivation to address that at last.  I'll put it on the call agenda.

The original kernel repo is abandoned -- Vivek uses a similar mechanism *within* ENTK now.  It would probably make sense to separate that part out again, to make it available to other parts of the stack...
