### ISSUE TITLE
orte-dvm doesn't always terminate properly

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1103]
When switching to the new openmpi version (currently openmpi/rhc_static) the application closes cleanly, but the dvm stays up and actually runs for 100% cpu until the queuing system kills it.

```
> pstree -p 22245
bash(22245)-+-radical.pilot\040a(22560)-+-orte-dvm(22599)-+-aprun(22606)---{aprun}(22608)
            |                           |                 |-{orte-dvm}(22602)
            |                           |                 |-{orte-dvm}(22604)
            |                           |                 `-{orte-dvm}(22605)
            |                           |-orte-submit(22738)
            |                           `-{radical.pilot\040a}(22626)
            `-ssh(22452)
```

We can see that the `orte-submit --terminate` doesn't return, so thats probably the explanation.

```
> ps -www 22738
  PID TTY      STAT   TIME COMMAND
22738 ?        S      0:00 /u/sciteam/marksant/openmpi/installed/rhc_static/bin/orte-submit --hnp 3331194880.0;tcp://10.128.99.187:46686 --terminate
```

Will look into this later.

**Comment by andre-merzky** [comment]
mark, can you update the status please?

**Comment by andre-merzky** [comment]
We don't seem to hit this with the OMPI tag we are using.  I would consider this an OMPI ticket, as I don't see anything we can do on our side here.  Please reopen if you think otherwise!
