### ISSUE TITLE
transplant/merge exercises from/to wiki to/from rtd

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1104]
Somehow do this post tutorial.

**Comment by andre-merzky** [comment]
Mark, can you remind me what needs to be done here?

**Comment by marksantcroos** [comment]
Transplant the changes we made for the tutorial into the main documentation.

**Comment by mturilli** [comment]
@andre-merzky do you know what/where is the tutorial?

**Comment by andre-merzky** [comment]
No :(
