### ISSUE TITLE
Connection closed by remote host on Comet

### ISSUE THREAD

**Issue by statho** [radical-cybertools/radical.pilot#1105]
I am running experiments on Comet and some of my CUs fail giving this error:
 
[Callback]: unit unit.000034 on pilot.0000: Failed.
stderr: ssh_exchange_identification: Connection closed by remote host

Any ideas why?
Thank you!

**Comment by andre-merzky** [comment]
This should have changed in the last RP release, which switched from SSH to ORTE based CU startup.  Can you please check what RP version you are using, and upgrade if that is not 0.42?  Thanks!

**Comment by statho** [comment]
I was using 0.40.3. I'll update it.
Thanks Andre!
