### ISSUE TITLE
FR: Create flag for RP directives to skip files not found on source

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1106]
Currently, if a file is not found in the source leads to an error. It would be good to have a flag which allows it to not prompt an error (and terminate) but gracefully skip (with a warning).

**Comment by marksantcroos** [comment]
That should be relatively easy I think. We can add a `NON_FATAL` flag to the staging directive and let the code continue if the transfer fails of a non-fatal staging directive.

**Comment by andre-merzky** [comment]
maybe rather use `skip_missing`?  Then we can (a) optimize, and (b) still raise on other errors (timeout, connection break etc) which the user would have otherwise to distinguish herself.

**Comment by marksantcroos** [comment]
There is something to say for your suggestion, although in reality its not always possible to distinguish a missing file from a connection error.

Can you describe the use case so that we can make an informed decision?

**Comment by andre-merzky** [comment]
The pilot is very well able to check the existence of files, and there is little overhead:

  * the pilot interprets some staging_output directives anyway, so there is little overhead in checking the respective ones and confirm file existence
  * the pilot also pushes a full unit update to UMGR after staging -- file existence information can well be part of that push, with little overhead (some bools).

In fact, that would also be an optimization in the normal case, as we don't even need to start remote checks or transfers for non-existing files, and can fail units earlier, before attempting to stage other files.  Assume 10 output files, the last one is missing: the agent can fail that unit immediately after the existence check (if `skip_missing == False`).

**Comment by marksantcroos** [comment]
So you only want this for missing output? You didn't specify that earlier.

**Comment by andre-merzky** [comment]
From the title: `... to skip files not found on source` ;)

**Comment by marksantcroos** [comment]
I saw that, thats why I was surprised by your agent focus.

**Comment by vivek-bala** [comment]
Example usecase: First 100 simulation tasks start executing. After time T, 1 analysis task is submitted for execution. The analysis task attempts to stage in a checkpoint file from all these 100 simulation tasks (intermediate data, so the simulation tasks are not yet DONE). The analysis task will operate on as many as checkpoint files as it can (so it doesn't HAVE to wait for all 100). So if only 40 simulation tasks have reached the state which produces the checkpoint file, analysis will stage in these 40 checkpoint files and operate on them (although it would "poll" all simulation tasks for the checkpoint file).

This would currently fail because the remaining 60 tasks will not have the checkpoint file and attempts to stage-in will prompt an error. Hence we need a ```skip_missing``` or ```NON_FATAL``` flag.

Does that help ?

**Comment by marksantcroos** [comment]
Thanks Vivek, I think that can be done relatively easy. Let me cough something up.

**Comment by vivek-bala** [comment]
Thanks Mark. Could you add/merge the feature to the partition scheduler branch as I am using that one for my experiments ?

**Comment by marksantcroos** [comment]
> Thanks Mark. Could you add/merge the feature to the partition scheduler branch as I am using that one for my experiments ?

Sure, that is no problem.

**Comment by marksantcroos** [comment]
Some more question on your use case:
- You are assuming this all runs on the same resource?
- And the checkpoint files live outside of the simulation CU sandbox on some pre-defined shared location?
- Do you link or copy the inputs of the analysis CUs?

**Comment by vivek-bala** [comment]
> You are assuming this all runs on the same resource?
Yes

> And the checkpoint files live outside of the simulation CU sandbox on some pre-defined shared location?
No, they are created inside the simulation CUs. The location is not pre-defined, I get the path of the CUs and refer from there.

> Do you link or copy the inputs of the analysis CUs?
Yes, the analysis works on the above data. I copy/link as input in the analysis CU using the RP directives.

Some more info on the usecase:

Basically, I have a (async) monitoring/analysis task that starts executing on some cores (on the same resource). This monitoring task has to stage in the checkpoint file from the simulation tasks. If the checkpoint file is available it is staged, if not it needs to be skipped. The monitoring task then works on whatever checkpoint files it has obtained.

**Comment by marksantcroos** [comment]
Please try `feature/non-fatal-missing` branch.

When you use a staging directive like the following, local missing source files will not fail the cu.
```
sd_missing = {
     'source': '/tmp/missing_input.dat',
     'action': rp.COPY,
     'flags': [rp.NON_FATAL]
}
```    

p.s. In case you want to mix this with the partitioning branch, temporarily create a new branch, and merge this one into it. Then we keep the branches clean, but you can still test the combination of the branches.

**Comment by vivek-bala** [comment]
Sure, testing now. Just to be sure, is it ```'flags': [rp.NON_FATAL]``` or ```'flags': rp.NON_FATAL``` ?

**Comment by vivek-bala** [comment]
I tried both, it failed with missing file error.

```
2016-08-23 10:28:51,625: radical.pilot       : MainProcess                     : InputFileTransferWorker-1: ERROR   : copy (file://localhost/home/vivek/Research/repos/radical.pilot/examples/input.data -> file://localhost/home/vivek/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017036.0023-pilot.0000//unit.000001/input.data) failed (1): (out: cp: cannot stat '/home/vivek/Research/repos/radical.pilot/examples/input.data': No such file or directory
) (err: None) (/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +532 (copy)  :  % (src, tgt, ret, out, err)))
Traceback (most recent call last):
  File "/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/radical/pilot/controller/input_file_transfer_worker.py", line 186, in run
    saga_dir.copy(input_file_url, target, flags=copy_flags)
  File "/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/namespace/directory.py", line 353, in copy
    if url_2  :  return self._adaptor.copy (url_1, url_2, flags, ttype=ttype)
  File "/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 532, in copy
    % (src, tgt, ret, out, err))
NoSuccess: copy (file://localhost/home/vivek/Research/repos/radical.pilot/examples/input.data -> file://localhost/home/vivek/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017036.0023-pilot.0000//unit.000001/input.data) failed (1): (out: cp: cannot stat '/home/vivek/Research/repos/radical.pilot/examples/input.data': No such file or directory
) (err: None) (/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +532 (copy)  :  % (src, tgt, ret, out, err)))
2016-08-23 10:28:51,644: radical.pilot       : MainProcess                     : InputFileTransferWorker-1: ERROR   : {'timestamp': 1471962531.625486, 'message': "Input transfer failed: input staging for unit.000001 failed: copy (file://localhost/home/vivek/Research/repos/radical.pilot/examples/input.data -> file://localhost/home/vivek/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017036.0023-pilot.0000//unit.000001/input.data) failed (1): (out: cp: cannot stat '/home/vivek/Research/repos/radical.pilot/examples/input.data': No such file or directory\n) (err: None) (/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +532 (copy)  :  % (src, tgt, ret, out, err)))"}
Traceback (most recent call last):
  File "/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/radical/pilot/controller/input_file_transfer_worker.py", line 190, in run
    % (compute_unit_id, e))
Exception: input staging for unit.000001 failed: copy (file://localhost/home/vivek/Research/repos/radical.pilot/examples/input.data -> file://localhost/home/vivek/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017036.0023-pilot.0000//unit.000001/input.data) failed (1): (out: cp: cannot stat '/home/vivek/Research/repos/radical.pilot/examples/input.data': No such file or directory
) (err: None) (/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +532 (copy)  :  % (src, tgt, ret, out, err)))
Exception in thread InputFileTransferWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/radical/pilot/controller/input_file_transfer_worker.py", line 190, in run
    % (compute_unit_id, e))
Exception: input staging for unit.000001 failed: copy (file://localhost/home/vivek/Research/repos/radical.pilot/examples/input.data -> file://localhost/home/vivek/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.017036.0023-pilot.0000//unit.000001/input.data) failed (1): (out: cp: cannot stat '/home/vivek/Research/repos/radical.pilot/examples/input.data': No such file or directory
) (err: None) (/home/vivek/Research/repos/radical.pilot/myenv/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +532 (copy)  :  % (src, tgt, ret, out, err)))
```

Also, it doesn't schedule the CU I believe since I don't since the particular unit folder in the sandbox.

**Comment by vivek-bala** [comment]
CU desc for input staging is as follows:

```
temp = {
                        'source': 'input.data',
                        'target': 'input.data',
                        'flags': [rp.NON_FATAL]
                    }
cud.input_staging  = temp
```

**Comment by marksantcroos** [comment]
> Sure, testing now. Just to be sure, is it 'flags': [rp.NON_FATAL] or 'flags': rp.NON_FATAL ?

It should be a list.

**Comment by marksantcroos** [comment]
> CU desc for input staging is as follows:

You didn't specify the action as per my example, and the default is `rp.TRANSFER`.

**Comment by andre-merzky** [comment]
See discussion on PR #1109 -- this ticket is kept open as feature request to implement the other cases for the same flag.

**Comment by mturilli** [comment]
@andre-merzky do you still want to implement the 'other cases for the same flag'?

**Comment by andre-merzky** [comment]
> want

No :-)  Lets close and re-open if the need arises.
