### ISSUE TITLE
Wrangler example configuration

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1107]
Hello,

Wrangler's entry in the [config.json](https://github.com/radical-cybertools/radical.pilot/blob/master/examples/config.json#L80) is not complete. Should I use ssh or gsissh? I will fill it for my tests.

**Comment by andre-merzky** [comment]
If the setting is `null`, then RP should use the default setting from the resource config, i.e. the first entry in  https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/configs/resource_xsede.json#L96, which would be ssh.  Is that failing for you?

**Comment by iparask** [comment]
It failed because it was missing the cores, not the schema. I will update it for the tests. Should I commit the config.json?

**Comment by andre-merzky** [comment]
Yes, please.
