### ISSUE TITLE
Waiting for CUs to reach a state to extract their working directory

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1111]
Usecase: I need to get the working directories of a set of CUs as soon as they are submitted. My understanding (thanks Mark) is that the units are guaranteed to have working directories when they reach ```AGENT_STAGING_INPUT``` state.

I am trying to get an RP example working for the above usecase.

Script: https://gist.github.com/vivek-bala/cdb5d6815285ae1573d8bcb706c29d91 (modification of 07_shared_unit_data.py)

It seems to be when I use ```state=rp.AGENT_STAGING_INPUT_PENDING``` to wait. But if I change it to ```state=rp.AGENT_STAGING_INPUT```,  the script doesn't seem to terminate at all (even though the CUs even reach DONE).

(even with state=rp.AGENT_STAGING_INPUT_PENDING, my issue in entk is still reproducible. But I will open that issue once this is resolved).

**Comment by marksantcroos** [comment]
Thanks, I'll try to reproduce.

> It seems to be when I use state=rp.AGENT_STAGING_INPUT_PENDING to wait. But if I change it to state=rp.AGENT_STAGING_INPUT, the script doesn't seem to terminate at all (even though the CUs even reach DONE).

Can you clarify this please? I think a word is missing in the first part or so.

**Comment by vivek-bala** [comment]
> Can you clarify this please? I think a word is missing in the first part or so.

Oops. It seems to **be successful** when I use state=rp.AGENT_STAGING_INPUT_PENDING to wait.

**Comment by vivek-bala** [comment]
Nevermind, this issue is resolved. The error was from a different section of the code and not from ```wait_units()```. Sorry for the noise.

Although, wait_units only worked with ```state=rp.AGENT_STAGING_INPUT_PENDING``` and not ```state=rp.AGENT_STAGING_INPUT```. This still persists. Also, I tried to view the states the CU goes into via the callbacks and I didn't see the states between ```Scheduling``` and ```AgentStagingInputPending```.

**Comment by vivek-bala** [comment]
Will close since the original issue is resolved. Can open another issue for wait_units not responding to other states. Let me know.

**Comment by andre-merzky** [comment]
There are currently race conditions wrt. state updates and events, at least in the client part of the code.  Those should be resolved in the split_module branch.  If things are workable for you at this point, I would not mind keeping this ticket closed and check again once that branch is used.

**Comment by vivek-bala** [comment]
> Those should be resolved in the split_module branch.

Does this refer to both 1) missing callbacks for some states and 2) ```umgr.wait_units()``` not responding to other states ?

>  If things are workable for you at this point, I would not mind keeping this ticket closed and check again once that branch is used.

Yup, that sounds good.

**Comment by andre-merzky** [comment]
> Does this refer to both 1) missing callbacks for some states and 2) umgr.wait_units() not responding to other states ?

Definitely to (1), but presumably also to (2).

Thanks, Andre.
