### ISSUE TITLE
Task cancelation procedure

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1112]
Usecase: Based on some condition, cancel executing tasks.

Example script: https://gist.github.com/vivek-bala/6269423c4c84adf4663c4b44c3f787cd

In the above script, I wait for all the CUs to go to ALLOCATING state and then attempt to cancel them. But the CU actually seems to reach DONE (from the verbose log) and the script does not terminate even though I am waiting only for the remaining tasks to finish.

Note: Allocating specifically because otherwise (without waiting for a state) the umgr reported that it does not know the state (https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_unit.py#L511).

**Comment by marksantcroos** [comment]
Here you probably also run into the sore state of state management.

What happens if you make the sleep longer and wait for EXECUTING?

**Comment by vivek-bala** [comment]
No that doesn't help either.

Output: https://gist.github.com/vivek-bala/5d94c63cce91a6c3a8567f3c0531ee63
Script: https://gist.github.com/vivek-bala/3f61b1a55d9c8889e47e310c2d892bf3

Note: This is the same error I get via EnTK.

**Comment by marksantcroos** [comment]
Can you try the fix in fix/cu_session branch?

**Comment by vivek-bala** [comment]
Yup, that worked for the example ! I'll try for my usecase now.

Is it ok to create a new branch with fix/cu_session + partition_scheduler + non-fatal-missing ?

**Comment by marksantcroos** [comment]
> Is it ok to create a new branch with fix/cu_session + partition_scheduler + non-fatal-missing ?

Yes, you can merge this new branch into the temp branch you already had made.

**Comment by marksantcroos** [comment]
> non-fatal-missing

Note that this has been merged to devel already.

**Comment by marksantcroos** [comment]
Can I create a PR for this or does it require more?

**Comment by vivek-bala** [comment]
Yes, you can. This worked for me.
