### ISSUE TITLE
BF scheduler needs to fail units for failing pilots

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1114]
Ref session from Matteo: `rp.session.radical.mturilli.017052.0002/pilot.0001`

**Comment by mturilli** [comment]
This was a big problem but are we ever going to use BF again?

**Comment by andre-merzky** [comment]
This actually should be fixed by now - we should check and confirm.  I expect that the BF scheduler will get used in any multi-pilot use case.  Now, if we ever see many of those I don't know... :/

**Comment by mturilli** [comment]
Good candidate for unit tests/integration test?
