### ISSUE TITLE
meta-issue: termination

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1130]
process and thread termination in RP is not clean (to put it mildly).  This is considered a 'known issue' by now, and we are closing a number of scattered tickets which ultimately are all termination related.

**Comment by ibethune** [comment]
Nearly there :)   Waiting for #1313 to be merged.

**Comment by andre-merzky** [comment]
The termination work is merged now and seems to hold up so far, thus closing.
