### ISSUE TITLE
Working directory for CUs

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1138]
I believe at some point this feature existed (might have been BJ!) but has been removed now. This feature would help in restarting/resubmitting failed units (both in terms of data movement and logging wds).

Opening this one for discussion.

**Comment by andre-merzky** [comment]
I would support this request, as long as the dir remains relative to the pilot sandbox.  It puts one additional constraint on the agent, which is a shared filesystem (units which end up on different compute nodes but have the same workdir requested would otherwise not see each others data.  That is (a) rare, AFAICS, and (b) can be compensated by placing such units on the same node.

But yes, that feature existed and was removed.  Mark might better remember the rationale behind the removal, as I think that was related to data management.

**Comment by andre-merzky** [comment]
Mark, quick ping that we discussed this on the call, but don't want to move forward without your input.

**Comment by marksantcroos** [comment]
@vivek-bala What is `wds`?

In general, specifying the working directory for the CU breaks the abstraction.

I think that the use case doesn't demand sharing the working directory, thats just one possible way to do it, and not the best.

Ultimately this comes down to data management.

If we would support this, this would conflict with RPs possibilities for optimisation, and we already know for a fact that moving the CU directory around for performance reasons is nearby on the radar.

(Not even discussing scenarios like concurrent CUs sharing the same WD overwriting each others files, cleaning up, etc.)

**Comment by andre-merzky** [comment]
> In general, specifying the working directory for the CU breaks the abstraction.

Can you clarify in what way?

> I think that the use case doesn't demand sharing the working directory, that's just one possible way to do it, and not the best.

Yeah, very likely not the only way.  But in what specific way do you think it is not the best?

One obvious way is to add link directives to the the second unit.  But that makes the application more cumbersome (it needs to actually track the file location for all units).  Or you can stage and link all data to/from the pilot staging area, which is also messy for large numbers of units, isn't it?

> Ultimately this comes down to data management.

yes :)

> If we would support this, this would conflict with RPs possibilities for optimisation, and we already know for a fact that moving the CU directory around for performance reasons is nearby on the radar.

We don't optimize on that part, yet, and its not clear when we will start doing so.  Also, it is easy to document that the use of a CU sandbox disables those optimizations.

> (Not even discussing scenarios like concurrent CUs sharing the same WD overwriting each others files, cleaning up, etc.)

From the perspective of tracking unit stdout/stderr and RP level tmp files, I don't think this is a problem, really.  The management of application files is certainly a user responsibility -- but that is the case either way, also if we link, for example.

My motivation for going into an argument in the first place really is: this is easy to implement, I think it is intuitive to the end user, and a user can *always* brute-force the semantics by `mkdir ../work && cd ../work` in the `pre_exec`, which would certainly be worse.  I see your point about optimization -- but I don't see why we can't have both (even if not at the same time).

**Comment by marksantcroos** [comment]
> In general, specifying the working directory for the CU breaks the abstraction.
> Can you clarify in what way?

I know you scoped it to relative paths already, but that was not in the original request.
That softens the pain a bit.

In general, there is no promise on the notion of a working directory from the API. Like you said yourself already before, it means the application now needs to ensure that the units land on a resource that can actually access that shared cu directory. There aren't (explicit) controls in the API for that.

> I think that the use case doesn't demand sharing the working directory, that's just one possible way to do it, and not the best.
> Yeah, very likely not the only way. But in what specific way do you think it is not the best?
> 
> One obvious way is to add link directives to the the second unit. But that makes the application more cumbersome (it needs to actually track the file location for all units). Or you can stage and link all data to/from the pilot staging area, which is also messy for large numbers of units, isn't it?

Right. I think it would be better, as it would be explicit, and not implicit. Makes it possible to optimize, allows for provenance, etc.

> Ultimately this comes down to data management.
> yes :)

Glad we agree on that part.
>
> If we would support this, this would conflict with RPs possibilities for optimisation, and we already know for a fact that moving the CU directory around for performance reasons is nearby on the radar.
> We don't optimize on that part, yet, and its not clear when we will start doing so. Also, it is easy to document that the use of a CU sandbox disables those optimizations.

There is already a request from Vivek (to me) that implies moving the CWD to a compute's node temporary storage for performance reasons. Thats what I consider my next development iteration.

> (Not even discussing scenarios like concurrent CUs sharing the same WD overwriting each others files, cleaning up, etc.)
> From the perspective of tracking unit stdout/stderr and RP level tmp files, I don't think this is a problem, really. The management of application files is certainly a user responsibility -- but that is the case either way, also if we link, for example.

STDOUT/STDERR are not the users responsibility. And then there are the temporary files used by ORTE for example.

> My motivation for going into an argument in the first place really is: this is easy to implement, I think it is intuitive to the end user, and a user can always brute-force the semantics by mkdir ../work && cd ../work in the pre_exec, which would certainly be worse. I see your point about optimization -- but I don't see why we can't have both (even if not at the same time).

Ack, I don't disagree that it can't be done, or even shouldn't be done, but you asked me what my thoughts are :)

**Comment by andre-merzky** [comment]
> In general, there is no promise on the notion of a working directory from the API. Like you said yourself already before, it means the application now needs to ensure that the units land on a resource that can actually access that shared cu directory. There aren't (explicit) controls in the API for that.

ack


>> One obvious way is to add link directives to the the second unit. But that makes the application more cumbersome (it needs to actually track the file location for all units). Or you can stage and link all data to/from the pilot staging area, which is also messy for large numbers of units, isn't it?
> Right. I think it would be better, as it would be explicit, and not implicit. Makes it possible to optimize, allows for provenance, etc.

We both seem to say, in different ways: 'better' is what the user thinks is better.


>> My motivation for going into an argument in the first place really is: this is easy to implement, I think it is intuitive to the end user, and a user can always brute-force the semantics by mkdir ../work && cd ../work in the pre_exec, which would certainly be worse. I see your point about optimization -- but I don't see why we can't have both (even if not at the same time).

> Ack, I don't disagree that it can't be done, or even shouldn't be done, but you asked me what my thoughts are :)

Yes, and thanks! :)  So, would you oppose an implementation, with the following premises:

* we make it very clear that it might disable optimizations, and might conflict with RP data management
* all conflict resolutions on CU file I/O is application responsibility
* workdirs must be relative to pilot sandbox
* no guarantee is made for non-shared file systems

Vivek, would those constraints be acceptable to you?  And you can't say 'yes' now and ask for those things later, mind ;)

**Comment by marksantcroos** [comment]
> Yes, and thanks! :) So, would you oppose an implementation, with the following premises:

No, with the possible addition that its not part of the API and can be retracted in the future.

**Comment by andre-merzky** [comment]
Ok, that sounds like a fair way forward.  Thanks!

**Comment by vivek-bala** [comment]
4/4 yes. But depending on how much optimization is achieved (/is required by the user application), it might then not be used too much. From an entk point of view, I think I should do the same = notify the user of possible optimizations (or lack there of) and let the user decide (as opposed to making such decisions in entk), would you agree ?

> Vivek, would those constraints be acceptable to you? And you can't say 'yes' now and ask for those things later, mind ;)

Yes, but ( ;) )if the current/planned optimizations are significant and will not be compatible with this effort, I will let you decide/advise if its worth the effort in implementing this, since I am the only one asking for this now. As Mark mentioned before, this would be just one way of implementing.

**Comment by andre-merzky** [comment]
I think it is straight forward to implement for the current launch methods and executors - but I can't speak for orte / liborte.  Let me give it a try in a separate branch, and lets Mark look over it afterwards again, ok?

As for the optimizations: once those kick in, having a tradeoff between convenience and performance seems very acceptable to me...

**Comment by vivek-bala** [comment]
+1

**Comment by marksantcroos** [comment]
> From an entk point of view, I think I should do the same = notify the user of possible optimizations (or lack there of) and let the user decide (as opposed to making such decisions in entk), would you agree ?

From my understanding of entk I would expect you don't expose those details.

**Comment by marksantcroos** [comment]
> I think it is straight forward to implement for the current launch methods and executors - but I can't speak for orte / liborte. Let me give it a try in a separate branch, and lets Mark look over it afterwards again, ok?

Ack, I would expect most work is for Vivek to make (proper) use of it, not so much from RP perspective.

**Comment by vivek-bala** [comment]
> From my understanding of entk I would expect you don't expose those details.

That is indeed true. And the EnTK user's requirement will be performance, since the convenience part would be hidden in/is for EnTK. But for both short term use by EnTK and long term use for RP users, this feature might be useful.

**Comment by mturilli** [comment]
@andre-merzky "Let me give it a try in a separate branch". Was this done? Is this still current?

**Comment by andre-merzky** [comment]
This is implemented in #1581

**Comment by andre-merzky** [comment]
implemented.
