### ISSUE TITLE
No module name utils

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1141]
I followed the testing protocol to install RP. I wasn't able to install using the following command:
`pip install -e 'git+https://github.com/radical-cybertools/radical.pilot.git@v0.44.RC1#egg=radical.pilot'`

When I checked out the devel branch, I rand `pip install .` and the installation was successful. However, when I run `radicalpilot-version` I get the following error:

```
Traceback (most recent call last):
  File "00_getting_started.py", line 12, in <module>
    import radical.pilot as rp
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/__init__.py", line 11, in <module>
    from .scheduler  import *
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 4, in <module>
    import radical.utils as ru
ImportError: No module named 
```

**Comment by andre-merzky** [comment]
Hmmm...

would you mind starting from scratch, and then after you see that error above, send me your command line history?  (there is a `history` command which prints the, well, history).  

Thanks!

**Comment by vivek-bala** [comment]
Hey Ming,

I got the same when using the "pip instal  git+https://.." command. I
cloned the repo, checked out the tag and installed using "pip install ."
and that worked.

- Vivek

**Comment by vivek-bala** [comment]
Oops, guess you figured it out. Didn't read the full message.

**Comment by mingtaiha** [comment]
Sorry for the extended afk. I tried the installation with the new instructions and everything seems to work fine now.

**Comment by andre-merzky** [comment]
Yep, it seems that pip (or setuptools or whatever) behaves differently, depending on where the module sources come from.  I do not intent to figure out why that happens, really, so I hope you don't mind if I just close this ticket.

The instructions on the test protocol have been adjusted accordingly.
