### ISSUE TITLE
staging input fails on stampede 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1146]
login3.stampede(16)$ cat STDERR 
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by vivek-bala** [comment]
Is this the content in STDERR of the compute unit ?

**Comment by vivek-bala** [comment]
This seems like an old error. Can you try the following **on stampede**: Copy the contents of the id_rsa.pub file (on stampede) and paste it in the authorized_keys file (on stampede).

**Comment by jdakka** [comment]
ok

**Comment by andre-merzky** [comment]
Jumana, this can also be closed I think?
