### ISSUE TITLE
Select scheduler fails on stampede

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1147]
login3.stampede(28)$ cat STDERR 
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by vivek-bala** [comment]
Possibly similar cause as #1146

**Comment by jdakka** [comment]
same issue for both 
yes the STDERR output is from the compute unit

**Comment by andre-merzky** [comment]
Jumana, can this be closed then?

**Comment by ibethune** [comment]
Closing, as no response.
