### ISSUE TITLE
rp 0.44rc1: example 07_shared_unit_data fails with authentication error

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1148]
Verbose log: https://gist.github.com/vivek-bala/2d06c30094cc4f506cbc0c2754621c8a
Pilot folder: [rp.session.radical.vivek.017098.0018-pilot.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/548840/rp.session.radical.vivek.017098.0018-pilot.0000.zip)

The only change I have made in the script is to add the following to the session:
```
c = rp.Context('ssh')
c.user_id = 'vivek91'
session.add_context(c)
```

I have added it for the remaining 9 example scripts as well and I don't see any issue in them. I added the context because rp scripts were not picking up the setting in ~/.ssh/config (but the settings work as I checked them on cmd line) - I can open another issue for this if required.

**Comment by andre-merzky** [comment]
Hey Vivek, 

thanks for the report!  I can see what goes wrong on the SAGA layer -- but unforunately don't see 'why'.  Alas, I also can't reproduce it, running the same setup against comet.  What is your target host?

**Comment by andre-merzky** [comment]
Sorry, stupid question - the logs say its also comet :P

Not sure what to do exactly.  Can you please set `RADICAL_SAGA_VERBOSE=DEBUG` and run again?
If that fails, I'll prepare a separate branch for testing.

Meanwhile, you may want to add the username to `~/.ssh//config` to continue with testing.  Thanks!

**Comment by vivek-bala** [comment]
Hey Andre.. 

> Not sure what to do exactly. Can you please set RADICAL_SAGA_VERBOSE=DEBUG and run again?If that fails, I'll prepare a separate branch for testing.

The verbose log from initial comment is with ```RADICAL_SAGA_VERBOSE=DEBUG```. Do you want me to run again or is the verbosity low/unexpected ? Not sure I understood.

> Meanwhile, you may want to add the username to ~/.ssh//config to continue with testing. Thanks!

My config file reads as follows:

```
Host xsede.comet
    Hostname comet.sdsc.xsede.org
    User vivek91
```

If I run ```ssh xsede.comet``` it works, but is not being picked up by RP. Am I missing some more parameters in config ?

**Comment by andre-merzky** [comment]
> The verbose log from initial comment is with RADICAL_SAGA_VERBOSE=DEBUG. Do you want me to run again or is the verbosity low/unexpected ? Not sure I understood.

I was staring too long at it it seems :P  Sorry...

> My config file reads as follows [...]

So, why do you specify the context in the first place?  Is that config setting not picked up?

**Comment by vivek-bala** [comment]
> So, why do you specify the context in the first place? Is that config setting not picked up?

Yes, I initially tried the scripts without the context. But the settings from the config file don't seem to be picked up. In order to finish the testing, I added the context in all the scripts.

**Comment by andre-merzky** [comment]
Hmm, one thing (ssh config ignored) is as strange as the other... (RP using different sessions) :/

**Comment by vivek-bala** [comment]
```
2016-10-24 21:53:01,042: radical.saga.api : MainProcess : MainThread : INFO : ignore ssh key at /home/vivek/.ssh/config (no public key: /home/vivek/.ssh/config.pub)
```

**Comment by andre-merzky** [comment]
yeah, that is fine -- the config file is not a public key after all :D  that is SAGA ignoring that file.  SSH should still pick up the settings...
Would you mind running once more w/o the context settings and sending the results?
Please, before you do so, remove `/tmp/saga_ssh_vivek*` (let me know if nothing is there to remove, please)

**Comment by vivek-bala** [comment]
Did find a file in ```/tmp/saga_ssh_vivek*```, removed it. 

Removed the context in 00_getting_started.py and ran it again. Fails with https://gist.github.com/vivek-bala/5441064e19bfb3f703fc70acb3102827

**Comment by vivek-bala** [comment]
The authentication error got fixed by adding comet.sdsc.xsede.org as key to the config file. After removing ```/tmp/saga_ssh_vivek*```, not able to reproduce this transfer failure.
