### ISSUE TITLE
09_MPI Doesn't work on Stampede

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1149]
MPI module is not loading...

STDOUT 

login1.stampede(8)$ ls
helloworld_mpi.py  radical_pilot_cu_launch_script.sh  STDERR  STDOUT
login1.stampede(9)$ vi STDOUT
login1.stampede(10)$ vi STDERR

Resetting modules to system default
Traceback (most recent call last):
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: No module named mpi4py
ImportError: No module named mpi4py
[c557-801.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 59253) exited with status 1
[c557-801.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 1, pid: 59254) exited with status 1
~

**Comment by marksantcroos** [comment]
You can ignore this.
