### ISSUE TITLE
Changes needed in config.json

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1151]
When running the example scripts for testing, I had to go into the config file to change the project id to `TG-MCB0901741`, and the access schema to `ssh`. This should be updated for future testing.

**Comment by andre-merzky** [comment]
`TG-MCB090174`, right?  Either way, that already shows the problem, this might not be the same for everyone.  I for example can't use ssh to supermic, only gsissh works.  So some tuning of the config will have to be acceptable.  We will make sure that the config is usable out of the box for tutorials and such, where we know allocation numbers etc. in advance.

**Comment by mingtaiha** [comment]
Right, `TG-MCB090174`. Just pointing this out in case another person will test on Supermic.
