### ISSUE TITLE
Agent side file staging is SRM specific 

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1159]
the SRM restriction should be lifted.

**Comment by mturilli** [comment]
Is this still current?

**Comment by andre-merzky** [comment]
The SRM specific code paths have been deactivated - the downside is that we don't have any remote staging capability in the agent at the moment (only the client side can initiate remote staging).

**Comment by mturilli** [comment]
Closed if this capability is needed we will open a new ticket
