### ISSUE TITLE
orte_cffi

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1163]
`orte_cffi` was added as requirement to the agent.  I just tried to install that module into a fresh env, but that seems to fail in my setup:

```
merzky@thinkie:/tmp $ source ve/bin/activate
(ve) merzky@thinkie:/tmp $ pip install orte_cffi
Collecting orte_cffi
  Downloading orte-cffi-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>

    compilation terminated.
```

Could you please clarify what is needed in the VE or system setup for this to work?  Should this requirement depend on the agent configuration?

**Comment by marksantcroos** [comment]
Only in the ortelib branch, or did I screw up?

**Comment by andre-merzky** [comment]
Right, only in ortelib.  But that is about to be merged, right? :)

**Comment by andre-merzky** [comment]
So, apparently that requires `libffi-dev` (linux), which seems not to be installed by default.  That means we likely have to provide it on machines where we want to use liborte, right?  But that also means we need to make this dependency optional.

After installing, I still stumble over:

```
raise Exception('Path "%s" is not an existing directory' % pkgdir)
    Exception: Path "/usr/lib/openmpi/lib/pkgconfig" is not an existing directory
```

which is probably not surprising.  After installing `libopenmpi-dev`, it fails though again with:

```
      File "src/orte-cffi/build.py", line 64, in pkgconfig
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
```

Is that due to a version mismatch, maybe?  But then again, I would not install the RP specific branch in /usr/local...  Any advice?

**Comment by marksantcroos** [comment]
> So, apparently that requires libffi-dev (linux), which seems not to be installed by default.

Depends on the distribution probably.

> That means we likely have to provide it on machines where we want to use liborte, right?

So far I had to request the installation on one of the resources that I used.

> After installing libopenmpi-dev

What version did that install?

> But that also means we need to make this dependency optional.

Yes, agreed, that was the plan all along as it is too specific currently.

> But then again, I would not install the RP specific branch in /usr/local... Any advice?

I don't understand this concern. As on all target resources we have to provide an openmpi installation already.

**Comment by andre-merzky** [comment]
I am not exactly sure if my point makes sense in the first place, apologies.  Will close until I get some more exposure to ORTE deployment.  Thanks!
