### ISSUE TITLE
**import theano failure

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1164]
```
/work/04265/tg835642/radical.pilot.sandbox/rp.session.radical.jdakka.017124.0006-pilot.0001/unit.000000/radical_pilot_cu_launch_script.sh: line 18: pip: command not found
Traceback (most recent call last):
  File "eeg_cnn_lib.py", line 10, in <module>
    import theano
ImportError: No module named theano
```
theano is already installed on stampede

**Comment by vivek-bala** [comment]
What's your executable and pre exec for this cu ?

**Comment by jdakka** [comment]
executable is python 
I removed pre-exec

**Comment by jdakka** [comment]
stderr: Warning: Permanently added 'c524-503,129.114.85.117' (RSA) to the list of known hosts.
Resetting modules to system default
Traceback (most recent call last):
  File "eeg_cnn_lib.py", line 10, in <module>
    import theano
ImportError: No module named theano

**Comment by vivek-bala** [comment]
How do you source your VE where you installed theano ? If you don't already do it in your bashrc on stampede. This needs to go in your pre_exec.

**Comment by jdakka** [comment]
(ve_stampede)c558-004.stampede(12)$ pip install --upgrade --user theano
Requirement already up-to-date: theano in /opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages
Requirement already up-to-date: numpy>=1.7.1 in /home1/04265/tg835642/.local/lib/python2.7/site-packages (from theano)
Requirement already up-to-date: scipy>=0.11 in /home1/04265/tg835642/.local/lib/python2.7/site-packages (from theano)
Requirement already up-to-date: six>=1.9.0 in /opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages (from theano)

(ve_stampede)c558-004.stampede(13)$ python
Python 2.7.12 (default, Sep  2 2016, 11:30:35) 
[GCC Intel(R) C++ gcc 4.4 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
>>>

**Comment by andre-merzky** [comment]
You are using some `ve_stampede` -- is that the same virtualenv as created by radical.pilot, in `$HOME/radical.pilot.sandbox/ve_stampede`?  If so, I would advise against that.  First, that virtualenv is not shared with the ComputeUnits, which explains your error.  But more importantly, that virtualenv can be re-created and updated by a starting pilot with no prior warning, which would result in unpredictable behavior.  Last, manual change in that virtualenv can cause failures in the pilot.

You may want to create a separate virtualenv on any of the shared filesystems on Stampede, and install theano:

```
$ virtualenv $HOME/ve_theano
$ source $HOME/ve_theano/bin/activate
(ve_theano) $ pip install theano
```

and then let your compute units use that virtualenv:

```
cud = rp.ComputeUnitdescription()
cud.pre_exec = ['source $HOME/ve_theano/bin/activate']
cud.executable = 'python'
cud.arguments = ['-c', 'import theano']
```

Best, Andre.

**Comment by itomaldonado** [comment]
Just want to add that we had to do "module load python" before we could run the script:

`cud.pre_exec = ['module load python', 'source $HOME/ve_theano/bin/activate']`

**Comment by andre-merzky** [comment]
Right, that makes sense of course.  Thanks for adding that note!
