### ISSUE TITLE
Gromacs command fails on Titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1165]
Cu shell script:

```
#!/bin/sh


# Change to working directory for unit
cd /lustre/atlas2/csc108/scratch/mturilli1/radical.pilot.sandbox/rp.session.titan-ext3.mturilli1.017127.0009-pilot.0000/unit.000100
# Environment variables
export RP_SESSION_ID=rp.session.titan-ext3.mturilli1.017127.0009
export RP_PILOT_ID=pilot.0000
export RP_AGENT_ID=agent_1
export RP_SPAWNER_ID=agent_1.AgentExecutingComponent.0.child
export RP_UNIT_ID=unit.000100

# Pre-exec commands
module load gromacs
# The command to run
/lustre/atlas/world-shared/bip103/openmpi/static-nodebug/bin/orterun  --hnp "1274544128.0;tcp://10.128.0.96,160.91.205.241:48044"  -np 1 -host 2443 grompp_mpi "-f" "grompp.mdp" "-c" "input.gro" "-p" "topol.top"
RETVAL=$?
# Exit the script with the return code from the command
exit $RETVAL
```

STDOUT:

```
------------------------------------------------------------
A process or daemon was unable to complete a TCP connection
to another process:
  Local host:    nid02453
  Remote host:   160.91.205.241
This is usually caused by a firewall on the remote host. Please
check that any firewall (e.g., iptables) has been disabled and
try again.
------------------------------------------------------------

```

STDERR: Empty

Let me know how I can help debug.

**Comment by vivek-bala** [comment]
I followed ```https://www.olcf.ornl.gov/kb_articles/software-gromacs/?softwaretype=kb_software_scientific_applications``` to run the gromacs command on the compute node.

From the above link: **"The gmx_mpi binary must run on the compute nodes via aprun"**

The following two worked:
```
aprun -n 1 grompp_mpi "-f" "grompp.mdp" "-c" "input.gro" "-p" "topol.top"
```

```
aprun -n 1 gmx_mpi grompp "-f" "grompp.mdp" "-c" "input.gro" "-p" "topol.top"
```

**Comment by vivek-bala** [comment]
I think this is ok. Since anyway we have to compile gromacs against the RP openmpi. I can work on that. But the current rp openmpi is within the atlas project. Not sure if compiling gromacs against this RP in the atlas project is ok (?)

**Comment by andre-merzky** [comment]
Let me know if you need another RP-OMPI installation.  I should be able to provide that.

**Comment by andre-merzky** [comment]
We will pick this up for re-testing once #1323 is investigated.

**Comment by andre-merzky** [comment]
#1323 is now rerouted to #1332

**Comment by AA919** [comment]
During these days open-mpi changed several times thus the wiki page might not be updated to the latest version. I think that this is the only problem

**Comment by andre-merzky** [comment]
Yeah, I was working on that.  the  current version (`module load openmpi/2017_05_04_539f71d`) should be there for a while.  Let me put that into devel, actually...

**Comment by andre-merzky** [comment]
done

**Comment by andre-merzky** [comment]
Alessio seems to have a functional Gromacs by now.  @vivek-bala, @AA919 : can you please sync to check if there is any action still needed on this ticket?

**Comment by AA919** [comment]
I have updated the wiki with the ''new'' version of Open MPI module.  I have also put a version of Gromacs on /lustre/atlas/world-shared/csc230/ that is compiled against Open MPI.
It should work smoothly. Let me know.

**Comment by andre-merzky** [comment]
thanks!

**Comment by ibethune** [comment]
@vivek-bala please confirm ASAP if any further action is required here, or if the binary @AA919 installed is working for you.

**Comment by andre-merzky** [comment]
ping @vivek-bala

**Comment by vivek-bala** [comment]
This issue is resolved. Sorry for the delay.

**Comment by andre-merzky** [comment]
No worries - thanks for the update!
