### ISSUE TITLE
Schedulers question

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1167]
Hello,

I just wanted to ask if there is a scheduler that prefers to schedule units to an empty node rather than a node that has even a CU? Also, is there a scheduler that schedules units to cores randomly?

Thank you

**Comment by andre-merzky** [comment]
No, and no.  A basic assumption of RP is that you don't leave cores or nodes idling, and that you want to fill them as quickly as possible.  With that in mind, any performance boost you would obtain from a CU being alone on a node would quickly evaporate, as the next CU is *supposed* to arrive shortly anyway.  Further, we want to make sure we can actually fill the nodes optimally.  Assume a random set of 1 and 7 core CUs on a cluster with 8 core nodes: a random placement of 2 single core CUs on the same node would immediately inhibit (or at least pessimize) a 7-core CU on that node.

I guess I can see why that is interesting in terms of scheduling research - but that is not the core focus or RP IMHO.  

Sooo, having said that: one can of course implement such schedulers.  What is the rationale behind the question?

**Comment by iparask** [comment]
I am running some Input intensive experiments and I was wondering if, at least for some time, there would be any benefit from having the CUs as much as possible alone in a node, without having to request more cores for a CU that will not use them.

**Comment by andre-merzky** [comment]
but, as said, the scheduler would (ideally at least) fill the node with other CUs anyway?

**Comment by iparask** [comment]
I got that. The previous answer was the rationale behind my question.

Thank you!

**Comment by andre-merzky** [comment]
Got it, ack...
