### ISSUE TITLE
RP  on LRZ

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.pilot#1169]
I am about to embark upon trying to run some simulations on LRZ which is contributing to an EU project called ComPat. As you may know Radical/SAGA has been included as part of the so-called ComPat stack.

Up until now we have been using custom scripts developed with the LRZ helpdesk to employ Redis to run multiple small jobs within a single job allocation. I would like to make this more robust and transferable and Radical/SAGA seems a good way to do this.

My question is whether you have tested your tools on this system? Having glanced through the documentation my feeling is that I need to setup a MongoDB server somewhere. Is this correct? If so do you know of any limitations that apply specifically to LRZ as to where this must be hosted?

Cheers
Dave

**Comment by dww100** [comment]
Just FYI everybody - this was my query which I emailed to Shantenu earlier. Thanks in advance for any help you can provide.

**Comment by marksantcroos** [comment]
Hi Dave,

Which system(s) at LRZ are you interesting in having supported?

We have supported SuperMUC in the past, but currently we don't have active users there and support likely needs to be revived. LRZ was particularly strict in network access so that is one practical hurdle that might need to be overcome again.

Regards,

Mark

**Comment by dww100** [comment]
Hi Mark,

It is indeed SuperMUC which I'm looking to use. My previous experience with their network access was what prompted my questions about where to run the MongoDB server.

For context - the ComPat project is looking to eventually be using three separate sites including SuperMUC and machines at PSNC in Poland and STFC in the UK. I'm starting with SuperMUC as a) I have access already and b) I thought there was some experience your end with the system.

Cheers
Dave

**Comment by marksantcroos** [comment]
@andre-merzky You still have access to LRZ? I seem to have lost mine ...

**Comment by shantenujha** [comment]
Please let me know if I should write to  contacts at LRZ  for any form of help to move this forward.

**Comment by andre-merzky** [comment]
It seems that I lost my account as well (which is not surprising I guess).  The last time we did indeed need to install a custom, static version of RP, IIRC, to handle the firewall and python issues, and I assume that this would still be the case.   So access to supermuc would probably be helpful to move this forward...

**Comment by dww100** [comment]
There is effort available in the ComPat project for someone at LRZ to work on getting this sort of thing up and running. Should I people in touch with one another to facilitate getting accounts and then things up and running?

**Comment by marksantcroos** [comment]
To close the loop here, we had discussed this in our group just before your message came in. We had concluded that Shantenu would follow-up with you and LRZ to get our accounts re-established.
