### ISSUE TITLE
cu.working_directory in split_module branch

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1170]
In the sm branch `cu.working_directory` property is an alias for `sandbox`.
Example 01_unit_details.py uses working directory from the exposed dict, and there the alias doesn't exist.

We could of course add it there too, but why was it renamed in the first place? Are the semantics different?

**Comment by ibethune** [comment]
So this is now tripping up the automated tester, so needs to be fixed in this releae cycle.
s

**Comment by itomaldonado** [comment]
oh, I did not know we had this one, I guess I should have searched. Yes it is not Jenkins, this has been happening on all PR tests.

**Comment by andre-merzky** [comment]
This should be addressed in the `fix/example_01` branch, will open a PR.

**Comment by andre-merzky** [comment]
This is fixed now.
