### ISSUE TITLE
Failing units on TITAN

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1173]
When a large number of CUs is submitted all together, the major part of them fail.
Resubmit them immediately after the failure does not solve the problem and in the end the pilot hits the walltime.
I did a stupid test to reproduce the problem. It consists in submitting a fixed number of CUs that run "/bin/data" so they can fail immediately.
The resubmission corrects the error, collects the CUs and send them again on the pilot in small bulks. 
When the number of CUs is small (~100/200) the procedure finishes propertly. The number of CUs is large (> 1000) the procedure continues to resubmit units because many of the CUs that have been resubmitted fail as well.

An additional problem that I have noticed is that the standard output is not always present in STDOUT.

**Comment by marksantcroos** [comment]
Just a heads-up that I'm working on this.

Note that resubmission only makes it worse :)
Note also that the units don't "fail", they don't start at all, thats why you see no STDOUT.

Remember that we debugged this already and you should see some popen resource errors in the agent logs.

**Comment by marksantcroos** [comment]
Can you please give the `feature/ortelib` branch a try. Use `ornl.titan_lib` as the target resource.
Please clean out the `ve_titan` in the sandbox directory so that it can create a fresh one.

Note that the environment handling of `orte_lib` is different than for `orte`, so complex units (e.g. atlas) likely won't run (yet).

Regardless this should get you going to achieve higher throughput, and we can work in parallel to make the environment work too, so that you can run atlas too.

**Comment by AA919** [comment]
I tried to submit 3000 CUs on 64 cores and it returns a "Quota exceeded" 
error.
There are no agent log files in the sandbox.


Traceback (most recent call last):
   File "testCollectiveResub.py", line 98, in <module>
     umgr.submit_units(cuds)
   File 
"/ccs/home/aleang9/ve-ortelib/lib/python2.7/site-packages/radical/pilot/unit_manager.py", 
line 457, in submit_units
     self._worker.publish_compute_units (units=units)
   File 
"/ccs/home/aleang9/ve-ortelib/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", 
line 448, in publish_compute_units
     unit_log=[])
   File 
"/ccs/home/aleang9/ve-ortelib/lib/python2.7/site-packages/radical/pilot/db/database.py", 
line 778, in insert_compute_units
     unit_uids = self._w.insert(unit_docs)
   File 
"/ccs/home/aleang9/ve-ortelib/lib/python2.7/site-packages/pymongo/collection.py", 
line 410, in insert
     _check_write_command_response(results)
   File 
"/ccs/home/aleang9/ve-ortelib/lib/python2.7/site-packages/pymongo/helpers.py", 
line 209, in _check_write_command_response
     raise OperationFailure(error.get("errmsg"), error.get("code"), error)
pymongo.errors.OperationFailure: quota exceeded

**Comment by marksantcroos** [comment]
Did you fill up your mongodb?

**Comment by marksantcroos** [comment]
Which one are you using?

**Comment by AA919** [comment]
This one:

mongodb://rp:rp@ds015335.mlab.com:15335/rp

**Comment by marksantcroos** [comment]
If there is nothing you want to preserve in there, you can use the following to wipe it:
```
mongo -u rp -p rp ds015335.mlab.com:15335/rp --eval "db.getCollectionNames().forEach(function(n){if(n.match(/rp.session/)){db[n].drop();}});"
```

**Comment by AA919** [comment]
Does this procedure delete also the data of other users?

Should I put my username on TITAN somewhere?

Ale

**Comment by marksantcroos** [comment]
Ah, I assumed this was your own db.
Try this and cross your fingers ;-)
```
mongo -u rp -p rp ds015335.mlab.com:15335/rp --eval "db.getCollectionNames().forEach(function(n){if(n.match(/rp.session.*aleang9.*/)){db[n].drop();}});"
```

**Comment by AA919** [comment]
Apparently I have no credential to do it.

Who is the admin of this db?

Ale

**Comment by marksantcroos** [comment]
@andre-merzky probably

**Comment by andre-merzky** [comment]
indeed :)  I cleaned it out.

**Comment by AA919** [comment]
Hi Mark,

I have sent 5000 ``must fail'' CUs.  RP was able to launch all of them 
and allow me to resubmit them.

Summarizing, it seems to work.

I lost some CUs in the process. I will investigate this further but I 
think that this is a flaw of my resubmission mechanism.

Now I will increase the number of cores to see if this might be a 
problem. This will require some time (I guess 3/5 hours).

Thanks,

Ale

**Comment by marksantcroos** [comment]
> Summarizing, it seems to work.

Ok, good.

> I lost some CUs in the process. I will investigate this further but I
> think that this is a flaw of my resubmission mechanism.

Ok, I noticed that its not rock solid though, also some saw cu's that didn't return and therefore slowly eating available cores.
Looking into that.

**Comment by shantenujha** [comment]
What is the status here? All work on titan seems to have to come to halt.

**Comment by marksantcroos** [comment]
At least one of the contributors to failing units got fixed over the weekend (https://github.com/open-mpi/ompi/issues/2691).

I still see some more that I'm currently investigating.

What do you mean with all work coming to a halt?

**Comment by marksantcroos** [comment]
@AA919 Can you give it another try please? I was able to run 10k units on a 100 node pilot.

**Comment by AA919** [comment]
Should I do a pull?

AA

**Comment by marksantcroos** [comment]
No RP changes required.

**Comment by AA919** [comment]
Sent. We will see what happens.

With bin/date I started having problems at 2048 cores but there were 
much less CUs.

AA

**Comment by AA919** [comment]
It completed 9424 CUs and then hit the walltime waiting for the rest.

Or at least this is what I was able to find by using the command "cat 
agent_1.out |grep "returned: 0"| wc -l ".

Ale

**Comment by marksantcroos** [comment]
Ok, I assume that is good?

**Comment by andre-merzky** [comment]
The next step would be to use more cores, and extend the pilot runtime?

Mark: what has changed on the ORTE layer?

**Comment by marksantcroos** [comment]
I disabled a subsystem while we are debugging and fixing the issue.

**Comment by AA919** [comment]
Yes, it is but, in my opinion, the problem is that the number of CUs 
decreases while increasing the size of the pilot and, at a certain 
point, the pilot hangs there.

With the same walltime and only 64 cores I was able to run more CUs 
(~12K if I remember correctly).

Have a good day,

Ale

**Comment by andre-merzky** [comment]
Alessio, can you please provide Mark with some guidelines on how to reproduce this?  What is the script you are running, what is the expected result, what do you see.

Thanks!

**Comment by AA919** [comment]
I took the simplest RP example and I increased the number of CUs.

I re-doing the test right now. To be sure.

Ale

**Comment by AA919** [comment]
Ok it might me less than 12K, I am receiving this message:


RADICAL-Pilot was unable to launch the specified application as it 
encountered an error:

Error: system limit exceeded on number of processes that can be started
Node: 2259

when attempting to start process rank 0.

This can be resolved by either asking the system administrator for that 
node to
increase the system limit, or by rearranging your processes to place 
fewer of them
on that node.

**Comment by marksantcroos** [comment]
Which branch are you using now?

**Comment by AA919** [comment]
feature/ortelib

**Comment by andre-merzky** [comment]
@AA919 and which resource tag?  `ornl.titan` or `ornl.titan_lib`?
@marksantcroos is there a difference to `feature/split_module_2` (in this context)?  Can you reproduce this?

**Comment by AA919** [comment]
ornl.titan_lib

**Comment by andre-merzky** [comment]
Alessio, can you please give the following stack a try:

$ radical-stack
python            : 2.7.9
virtualenv        : /autofs/nccs-svm1_home1/merzky1/ve_split
radical.utils     : v0.44-13-ge86642c@devel
saga-python       : v0.44-124-gc1dbe1d@feature-torque_bulk
radical.pilot     : v0.44.RC1-651-gd514e48@feature-split_module_2

Thanks

**Comment by marksantcroos** [comment]
In addition to Andre's request: I pushed one more fix.
Repeatedly submitted 10k units to 100 and 10 node pilots and don't get errors any more.

**Comment by AA919** [comment]
I am trying right now.

Ale

**Comment by AA919** [comment]
Hi Andre,

Do you want me to use your virtualenv?

Or do you want me to generate a new one?

Ale

**Comment by AA919** [comment]
I am using Andre's virtualenv and all my units are failing.

I am waiting for the end of the execution to determine if it is just a 
client side problem or not.


Ale

**Comment by AA919** [comment]
I am using Andre's virtualenv and all my units are failing.

I am waiting for the end of the execution to determine if it is just a 
client side problem or not.


Ale

**Comment by AA919** [comment]
It works by using this virtualenv: /autofs/nccs-svm1_home1/merzky1/ve_split

But I am not able to generate a working virtualenv in my home.

Are the branches correct?

Ale

**Comment by marksantcroos** [comment]
So now that it works again (offline), do you see the failing units?

**Comment by andre-merzky** [comment]
What was the problem?

**Comment by AA919** [comment]
Hi,

I am still in queue.

Ale

**Comment by AA919** [comment]
Sorry,

I sent the last message with a missing part.

The test that I sent yesterday did not go through. Do not know why, but 
I think was a problem of my session not with RP.

I have sent another test this morning and I am still waiting.

Ale

**Comment by AA919** [comment]
Computation was ok.

Have you noticed a funny behaviour on TITAN during the last days?

I have experienced at least three rebooting of head nodes and now I am 
not able to modify pre-existent files (E667: Fsync failed)

Is it just me or you have the same problem?

Ale

**Comment by andre-merzky** [comment]
> Computation was ok.

Great!

FWIW, it seems we have a new failure mode: the agent sometimes seems to miss a specific message on startup, and then is not able to finish bootstrapping.  I have only seen that on large pilots at this point (>200 nodes), Mark may have stumbled over this on small pilots.  So, please let us know if you seem to have pilots failing early!

Alessio, if you have a working setup for now, I would suggest closing this ticket, and open new ones as needed.

> Have you noticed a funny behaviour on TITAN during the last days?
> I have experienced at least three rebooting of head nodes and now I am
> not able to modify pre-existent files (E667: Fsync failed)
> Is it just me or you have the same problem?

Maybe related, maybe not: I sometimes see files *disappearing*.  Like, I install `radical.utils` in a VE, and have a successful run, and on the next run some files in the VE are missing and python can't find the `radical.utils` module anymore.  I did not bother tracking this down, but it happened repeatedly.  File system caching issues would explain that actually...

**Comment by AA919** [comment]
On 21/01/2017 11:14, Andre Merzky wrote:
>
>     Computation was ok.
>
> Great!
>
> FWIW, it seems we have a new failure mode: the agent sometimes seems 
> to miss a specific message on startup, and then is not able to finish 
> bootstrapping. I have only seen that on large pilots at this point 
> (>200 nodes), Mark may have stumbled over this on small pilots. So, 
> please let us know if you seem to have pilots failing early!
>
> Alessio, if you have a working setup for now, I would suggest closing 
> this ticket, and open new ones as needed.
>
More than ok for me. Just a clarification? what is the current limit in 
terms of node when a single core per cu is used?
>
>     Have you noticed a funny behaviour on TITAN during the last days?
>     I have experienced at least three rebooting of head nodes and now I am
>     not able to modify pre-existent files (E667: Fsync failed)
>     Is it just me or you have the same problem?
>
> Maybe related, maybe not: I sometimes see files /disappearing/. Like, 
> I install |radical.utils| in a VE, and have a successful run, and on 
> the next run some files in the VE are missing and python can't find 
> the |radical.utils| module anymore. I did not bother tracking this 
> down, but it happened repeatedly. File system caching issues would 
> explain that actually...
>
Happened to me too. I thought I was getting crazy (which might be true 
anyway).
Ale

**Comment by andre-merzky** [comment]
> More than ok for me. Just a clarification? what is the current limit in
> terms of node when a single core per cu is used?

Good question!

IIUC, we do have a hard limit of 64k  CUs right now.  Mark may be able to clarify  if that is a limit on concurrent CUs or on CUs in total.

We seem to have a problem with large DB updates: pushing bulks of 10k units to the DB seems to regularly fail.  Non-bulk pushes seem ok - but for large pilots, our auto-bulking algorithm can still collect large bulks of data, triggering the problem.  I don't have a hard number on the limit, yet, and am working on a fix.

As mentioned, I see agent startup problems on large pilots - but I don't know a specific number when that happens, and am not even sure it is indeed size related.

I am not aware of other hard limits at the moment.  @marksantcroos, any comments?


> Happened to me too. I thought I was getting crazy (which might be true
> anyway).

:-P

**Comment by AA919** [comment]
Thanks I will do some tests too. See how they will go.

Ale
