### ISSUE TITLE
Ask for 16 cores on TITAN generates an error

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1174]
Hi,
RP returns an error anytime that I ask for 16 cores (equivalent to one node). I am using the latest commit on devel. The error can be reproduced by using RP example 00 and changing config.json in such a way that 16 cores are asked instead of 64.

Cheers

**Comment by marksantcroos** [comment]
What is the error?

In general it depends on the agent configuration if it is possible to ask for just one node, as the configuration might reserve a node for the agent itself.

**Comment by AA919** [comment]
The error is this one:
 /2017-01-02 17:44:01,884: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
2017-01-02 17:44:01,884: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 235, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1

Ok. Do I have always ask for one node more than I need?

Thanks,

Alessio

**Comment by andre-merzky** [comment]
That is the error on the client side, which basically is a reaction on the pilot failing.  The agent logs will contain some additional error message (`grep ERROR *.log`).

Yes, on Cray you basically have to ask for one additional node (by default).  Look at the `target` flags in the cray agent config at  https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/agent_cray.json : the first subagent `agent_0` with `target="local"` will run on the MOM node - but we have to put the CU executor on a compute node, thus we have a subagent `agent_1` on `target="node"`, and that node then cannot be used for CUs anymore.

**Comment by marksantcroos** [comment]
We toyed around with agent configs on Titan for Alessio so I'm not sure which one he is using now.

**Comment by andre-merzky** [comment]
Ah, ok, got it...

**Comment by AA919** [comment]
I think that you are both right. I had the very same problem some months ago but then it disappeared while I was working with Mark. Yesterday I did a push from scratch and the problem returned.
Thanks for the help. If we know what it is is not an issue and we can close the ticket.
