### ISSUE TITLE
global staging area

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1180]
to share data between different pilot sandboxes.  Location should be user specified (to allow for non-scratch storage).  This is an INCITE request

**Comment by andre-merzky** [comment]
Example: on titan, data should be staged to more persistent storage than `/scratch`.

**Comment by jhprinz** [comment]
I would prefer to have something like different file prefixes to access files
- `staging://`: points to files in the staging area `staging_area/`
- ``: points to files on the work unit `unit.[xxxxxx]/` folder 
- `file://`: points to files in the current working directory of the application on the host machine. see `os.getcwd()` to

new would/could be
- `shared://` point to the shared fs main folder. I think this is stored in `default_remote_workdir`
- `sandbox://` point to the main `radical.pilot.sandbox` folder usually in `default_remote_workdir/radical.pilot.sandbox/`

I can easily do copy and link in the pre_exec stage. But it seems cleaner to me, when I could add these in the `input/output_staging` phase.

Perhaps one might even have the possibilty to add user-defined prefixes. All this really is, is a string replace of `xyz://` with a file location. So I might wanna do this
```py
umgr.add_staging_prefix('shared', 'some/place/to/shared/')
umgr.add_staging_prefix('trajectories', 'some/place/to/put/trajectories')
```

**Comment by andre-merzky** [comment]
I also considered different prefixes - but neither `shared` nor `sandbox` seems useful (if I may be so blunt): `shared` between what?  And we have pilot- and unit-sandboxes...

If I may offer an alternative:

* `resource`: shared between all pilots (for that user) on the target resource
* `pilot`: shared for all units under the same pilot (ie. the pilot sandbox)
* `unit`: local to the unit
* `client`: local to the client host

All other URLs (`ftp://...`) would then be interpreted as absolute URLs and we don't care about sharing properties.

**Comment by jhprinz** [comment]
I think you made a good point and your suggestions sound good to me.

**Comment by andre-merzky** [comment]
The above staging scheme is now implemented.
