### ISSUE TITLE
[FEATURE] Running RP from within an Jupyter/IPython notebook

### ISSUE THREAD

**Issue by jhprinz** [radical-cybertools/radical.pilot#1182]
Not sure if this is the right place to put this,  but I managed to run RP from within an IPython notebook. I remember that there were some problems to run RP with conda and not inside a virtualenv environment. 

So this is more a note for the possibility of interactive sessions and could have interesting applications to monitor the progress from within a notebook.

I guess comments or ideas are welcome.

**Comment by andre-merzky** [comment]
Yeah, happy to comment on this.  

We have been using notebooks in the past, and got mixed results.  The main source of problem seems to be that *order of execution* is variable in notebooks: you can run `cell 1`, `cell 2`, `cell 3`, and then `cell 2` again -- and iPython will, by clever caching of intermediate state of the script, try to support that efficiently.

RP on the other hand is a distributed system with state in different components of which iPython knows nothing about - and having part of the frontend state cached, and having API calls executed out of order, can easily throw it off the track.

So please do make sure to, for example, confirm that all pilots started in a notebook are indeed terminated at the end, etc.

**Comment by jhprinz** [comment]
I was not aware of the caching. But that is indeed a potential problem. So far I am using only more or less a linear approach with potential rerun of a cell that failed. It is helpful for testing. I would consider this closed for now. Since I also do not see the current use in production and everyone is free to use it for testing on their own of course.
