### ISSUE TITLE
[FEATURE REQUEST] Allow staging/linking of directories

### ISSUE THREAD

**Issue by jhprinz** [radical-cybertools/radical.pilot#1183]
I am using the linking of files from the staging area to simplify the access on the working unit. It would be nice, if this could be extended to folders as well. From my perspective the change would be minimal
and (at least for my purpose) soft links are fine.

```python
{
    'source': 'staging:///alanine/',
    'target': 'trajectories/'
    'action': rp.LINK
}
```
It might also me enough to request a link to the folder `staging_area` directly with a fixed name.

**Comment by andre-merzky** [comment]
I think this would be a duplicate of #936?

**Comment by jhprinz** [comment]
Yes, will close this one then and continue in #936.
