### ISSUE TITLE
Runtime Error: Job does not match any pilot (experiment/aimes)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1191]
Hello, I've been using the experiment/aimes stack to submit jobs Supermic. I was able to submit a job requesting 16 cores (1 task per core). I saw that the job was running on Supermic with the Job ID [203396]. However, RP catches the following exception and means that RP was unable to find the job based on its ID despite having the correct ID.

The error was found in pmgr.launching.0.child.log
```
2017-01-19 18:27:39,758: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 298, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 505, in _start_pilot_bulk
    % (j.name, j.id))                                                                                                                                                                                       
RuntimeError: job does not match any pilot: None : [torque+gsissh://supermic.cct-lsu.xsede.org]-[203396]
```

**Comment by andre-merzky** [comment]
All branches which are based on the `feature/module_split_2` branch, which includes `experiment/aimes`, need support for `job.name` on the SAGA layer.  That seems to be missing from the SAGA version you are using.  You may also want to use `experiment/aimes` on the SAGA layer (or pull if you are on it already).  On the utils layer, `devel` should work ok.

note that Supermic is not tested with that branch, and I am unsure if the agent config is up to par.  Please let me know if you stumble over further problems!

**Comment by mingtaiha** [comment]
I am already using the experiment/aimes stack for RP, RU and SAGA

**Comment by andre-merzky** [comment]
Supermic works ok now in the released version, at least in the context of this ticket.
