### ISSUE TITLE
Wrong parsing of `file:///` in compute unit file staging

### ISSUE THREAD

**Issue by jhprinz** [radical-cybertools/radical.pilot#1192]
I found a potential bug or rather unindented inconsistency. When I use the prefix `file://` during `pilot.stage_in` for the `source` I can refer to files on the application side. When I try the same for `input_staging` (and possibly) `output_staging` then it does not recognise the prefix and prepends the current working directory. so
```
{
    'source' : 'file://[my_path]/my_file',
}
```
gets parsed as this file which does not exist
```
[path_to_cwd]/file:/[my_path]/my_file`
```

A simple workaround is to omit the prefix `file://` in these cases so it is not really a problem. I just guess that this is not intended.

**Comment by andre-merzky** [comment]
Just to be sure we are not missing something:  the above should be

```
{
    'source' : 'file:///[my_path]/my_file',
}
```

(3 slashes) because it would otherwise be an incorrect URL, right?  But I think your original issue in the markovchain repo hat that right...

**Comment by jhprinz** [comment]
Yes, exactly. At least this is how I understood it:

```
file:///path/to/my/folder/file.ext
```

does not work. Where this is comprised of `file://` + `/path/to/my/folder/file.ext` correct?

**Comment by jhprinz** [comment]
I tested the exact same `dict` for `pilot.stage_in` and `cu.input_staging` and it worked for the pilot but not for the cu. This is what got me wondering.

**Comment by andre-merzky** [comment]
got it, thanks!

**Comment by andre-merzky** [comment]
The staging ops have been changed in the last release - this needs to be checked again, and should now be easy to fix (tm)

**Comment by mturilli** [comment]
@andre-merzky Is this fixed?

**Comment by andre-merzky** [comment]
I don't know, needs checking :-/

**Comment by andre-merzky** [comment]
see also radical-cybertools/saga-python/issues/483

**Comment by andre-merzky** [comment]
outdated,
