### ISSUE TITLE
agent scheduler performance 

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1195]
microbenchmarks showed that this is not great (iterating the data structure, coarse-grained locking).  The bitarray scheduler in RU could be used to remove that bottleneck.

**Comment by andre-merzky** [comment]
Needs to be re-evaluated with the gpu branches, as the schedulers have seen major changes there.

**Comment by mturilli** [comment]
Would this be in the scope of RP paper? Both in terms of currently planned micro-benchmarks or new ones?

**Comment by andre-merzky** [comment]
Some work on the scheduler has been done by now,  in the context of GPU scheduling.  This is supposed to have resolved *some* performance issues, and the RP paper micro benchmarks should show that.  The remaining issues are likely only solvable by moving to C, via the mentioned bitarray scheduler (or some variant of that).

The RP paper could either use the current state, and point toward future work, or could use the GPU scheduler, and point to future work.  The latter would be more useful for us, as we learn something new, but would then use a slightly different stack again than we used for the other experiments.

Switching to the bitarray scheduler would be too time distracting I think (wrt. time) - we don't even have that in our roadmap, yet :/
