### ISSUE TITLE
Resource temporarily unavailable (bundled/zeromq/src/thread.cpp:106)

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1199]
Next time you encounter `Resource temporarily unavailable (bundled/zeromq/src/thread.cpp:106)` in `agent_0.err`, check your stacksize.

I ran into this on a system that had an extremely high stacksize set. After lowering that in pre_bootstrap_1 it works fine.

**Comment by andre-merzky** [comment]
Interesting...  This should 'only' be virtual memory though, until the stack is getting filled with some significant amount of data.  So you were even running out of virtual memory on that machine?  I wonder if that is what happened on Titan, too.  What was your observed stack size?

FWIW, I would think its safe to limit the stack size on the agent side by default.  I'll leave this ticket open for now,  will look into it (at some point).

Thanks!

**Comment by marksantcroos** [comment]
> What was your observed stack size?

500MB

**Comment by andre-merzky** [comment]
oh, ouch...  That kinda explains it... :-P

**Comment by mturilli** [comment]
@andre-merzky was this addressed?

**Comment by andre-merzky** [comment]
We now set the stack size on affected machines, so we don't run into that anymore.
