### ISSUE TITLE
When lrms_config_hook called?

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1202]
Should the LRMS config hook be called after LRMS has been configured?

Doesn't this cancel the purpose of the hook?

**Comment by iparask** [comment]
Wrong question

**Comment by marksantcroos** [comment]
Can you be more specific? It serves it purpose now.

**Comment by marksantcroos** [comment]
Ok.

**Comment by iparask** [comment]
I thought that the way the LRMS config hook was called had changed. I made a mistake there, invalidating my own question
