### ISSUE TITLE
DB unit insert chokes on too many units

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1205]
This was reported by @marksantcroos on titan, but is expected to be a general limit: if too many units (>16k) are submitted in a single bulk, the mongodb `insert` call will choke.

**Comment by andre-merzky** [comment]
@marksantcroos, this should be addressed in the branch `feature/bulk_size_limit`.  Could you give it a spin, please, and report back?

**Comment by marksantcroos** [comment]
Thanks, will have a go at it.

**Comment by andre-merzky** [comment]
Did you have a chance to look at it?

**Comment by marksantcroos** [comment]
Not yet, as I don't want to do a quick check, but rather a real check. It's on my todo list.

**Comment by andre-merzky** [comment]
ack, thanks

**Comment by marksantcroos** [comment]
Seems to work ;)
