### ISSUE TITLE
Consistency in env variable values

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1208]
RADICAL_PILOT_VERBOSE accepts both info and INFO. RADICAL_PILOT_AGENT_VERBOSE however accepts only INFO (fails with info).

Not critical, but I guess a easy fix.

**Comment by andre-merzky** [comment]
Ah, thanks - that is an easy fix indeed! :)  I though wonder if we should get rid of `RADICAL_PILOT_AGENT_VERBOSE` altogether, we have too many env vars anyway.  Any opinion on that?

**Comment by marksantcroos** [comment]
Please keep them both as far as I am concerned. They serve different purposes.

**Comment by vivek-bala** [comment]
As long as the alternative is an equivalent/ union of verbose on client+remote, I think I'll agree.
