### ISSUE TITLE
MPI CUs fail on localhost - mpi4py not installed

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1210]
The ./09_mpi_units.py fails for me.  I installed mpi4py from pip inside my virtualenv, and I can manually run the CUs e.g.:

```
(0.45-test-env2) Iains-MacBook-Pro:examples ibethune$ /opt/local/bin/mpiexec -n 2 -host localhost python ~/radical.pilot.sandbox/rp.session.Iains-MacBook-Pro.local.ibethune.017210.0017-pilot.0000/unit.000127/helloworld_mpi.py 
1/2/Iains-MacBook-Pro
2/2/Iains-MacBook-Pro
```

Yet, when run through RP, I get errors that mpi4py was not found:

```
(0.45-test-env2) Iains-MacBook-Pro:examples ibethune$ cat ~/radical.pilot.sandbox/rp.session.Iains-MacBook-Pro.local.ibethune.017210.0017-pilot.0000/unit.000127/STDERR 
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: ImportError: No module named mpi4py
No module named mpi4py
```

I don't know if I should have installed mpi4py *before* I first ran RP and the ve_localhost was created.  Even if I nuke ve_localhost and it gets recreated when the pilot bootstraps, I still get the same errors. How do I add packages to the python env that RP executes CUs in?  I can imagine this is a real use-case (although I don't consider it to be blocking for the release since it's clearly related to my local python setup rather than anything more fundamental).

**Comment by vivek-bala** [comment]
Hey Iain,

Neither the client VE nor the VE in the sandbox are invoked within a CU and hence the error. You will have to install the module in the system/user space and not in the VE.

Not sure what the mac equivalent is but ```pip install mpi4py --user``` should install it in the user space.

**Comment by marksantcroos** [comment]
What I would suggest is to actually remove test09, or at least make clear in the documentation/output that it is expected to work less out of the box than the other tests.

**Comment by andre-merzky** [comment]
Ack on all: we should better document what this example expects on the target resource, and we might want to remove it from the localhost tests...

**Comment by ibethune** [comment]
OK, so this is working now I have mpi4py installed in my system python environment.  I think it's useful to keep it in the examples suite (after all, running MPI CUs is a common use case).  Let's use this issue to fix the documentation here https://radicalpilot.readthedocs.io/en/latest/user_guide/09_mpi_units.html re: the requirement to have mpi4py in the execution host's python env (not in the VE used for launching RP)

**Comment by andre-merzky** [comment]
Fair enough.  Note that on any target clusters, mpirun or similar startup mechanisms are readily available in most cases, and the resource configs ensure that the right mechanism is picked in those cases - its only localhost, ie. personal laptops etc, which are unlikely to run MPI apps out of the box...

**Comment by ibethune** [comment]
Close as a duplicate of #1239
