### ISSUE TITLE
Localhost Anaconda execution fails

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1211]
As reported by George:
RADICAL Stack:

```
(test_ve)georgeha@js-17-215:~/radical.pilot.sandbox/rp.session.js-17-215.jetstream-cloud.org.georgeha.017210.0007-pilot.0000$ radical-stack
python : 2.7.6
virtualenv : /home/georgeha/test_ve
radical.utils : v0.45.RC1@detached-v0.45.RC1
saga-python : v0.45.RC1@detached-v0.45.RC1
```
[Archive.zip](https://github.com/radical-cybertools/radical.pilot/files/772364/Archive.zip)

George please report RP's version also.

**Comment by iparask** [comment]
George, 

can you test it please?

**Comment by georgeha** [comment]
Hi Giannis,

I run a couple of examples and it works.

**Comment by iparask** [comment]
Based on PR #1219, the fix has been merged in devel. Thus, I consider the ticket resolved.
