### ISSUE TITLE
Data staging not implemented for OSG

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1221]
```
$ radical-stack 
python            : 2.7.10
virtualenv        : /Users/mturilli/ve
radical.utils     : v0.45.RC1@HEAD-detached-at-v0.45.RC1
saga-python       : v0.45.RC1@HEAD-detached-at-v0.45.RC1
radical.pilot     : v0.45.RC1@HEAD-detached-at-v0.45.RC1

$ ./05_unit_input_data.py osg.xsede-virt-clust
[...]
wait for 128 unit(s)
        -----------------------------------------------------------------------|
        ---------------------------------------------------------             ok

  * unit.000000: Fail, exit:   1, out: 
  * unit.000001: Fail, exit:   1, out: 
  * unit.000002: Fail, exit:   1, out: 
[...]
```

**Comment by andre-merzky** [comment]
Yes, this is indeed true.  I am gonna close this as 'will not implement' though: at least for the time being, we don't really see a viable way to stage data from localhost to a OSG execution node, which is the staging mode this example uses.  Lets leave OSG data staging to the split branch and to the proper pilotdata implementation.

Thanks Matteo!

**Comment by mturilli** [comment]
I would keep it open as a feature request. Without data staging most of the 'real' uses of OSG are unfeasible.

```
$ ./06_unit_output_data.py osg.xsede-virt-clust                                                                                                  [...]
wait for 128 unit(s)
        -----------------------------------------------------------------------|
        ---------------------------------------------------------             ok

  * unit.000000: Fail, exit:   1, out: 
  * unit.000001: Fail, exit:   1, out: 
  * unit.000002: Fail, exit:   1, out: 
```

**Comment by mturilli** [comment]
```
$ ./07_shared_unit_data.py osg.xsede-virt-clust                                                                                                           
[...]
wait for 128 unit(s)
        -----------------------------------------------------------------------|
        ---------------------------------------------------------             ok

  * unit.000000: Fail, exit: None, out: 
  * unit.000001: Fail, exit: None, out: 
  * unit.000002: Fail, exit: None, out: 
```

**Comment by andre-merzky** [comment]
> I would keep it open as a feature request. Without data staging most of the 'real' uses of OSG are unfeasible

Yeah, fair enough, I put it on the backburner though.

To summarize the state of affairs (Mark, please correct): 

Staging from the client side to a unit will likely need to be a two-hop transfer, as we usually can't access the compute nodes from outside.  Having said that, the pilot agent should already be able to pull  data for the unit from 3rd party hosts, at least for SRM based data sources.  The plan is to extent this to other types of data sources.

Also, we could in principle implements indirect staging via the submission host -- but I am not sure how reliable that will be, as not all compute nodes can be ssh-accessed even from the submission host.

**Comment by marksantcroos** [comment]
> Staging from the client side to a unit will likely need to be a two-hop transfer, as we usually can't access the compute nodes from outside.

You can remove `likely`.

> Having said that, the pilot agent should already be able to pull data for the unit from 3rd party hosts, at least for SRM based data sources. The plan is to extent this to other types of data sources.

Right. So functionally you can do it with the current staging implementation, but you need to do the indirection explicitly, i.e. push data to intermediate storage, and use that url as input for the cu.

> Also, we could in principle implements indirect staging via the submission host -- but I am not sure how reliable that will be, as not all compute nodes can be ssh-accessed even from the submission host.

The only real solution is pull from the compute node. So you could use the submission host just as any other intermediate step for the staging, but the worker node really need to pull.

There are some mechanisms in various stages of maturity (e.g. parrot / stash) that work with providing a shared "filesystem" on the compute node, but you would still need to get the data from your laptop into that.

Pilot-Data practically does the same, but manages the indirection for you.

**Comment by mturilli** [comment]
Should we put together an example of 'managing the indirection'?

**Comment by marksantcroos** [comment]
Although ultimately a good idea, it is involved, especially if it would be based on SRM.
