### ISSUE TITLE
MPI submissions not handled for OSG

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1223]
```
$ radical-stack 
python            : 2.7.10
virtualenv        : /Users/mturilli/ve
radical.utils     : v0.45.RC1@HEAD-detached-at-v0.45.RC1
saga-python       : v0.45.RC1@HEAD-detached-at-v0.45.RC1
radical.pilot     : v0.45.RC1@HEAD-detached-at-v0.45.RC1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

$ ./09_mpi_units.py osg.xsede-virt-clust                                                                                                                  

================================================================================
 Getting Started (RP version v0.45.RC1)                                         
================================================================================

/home/mturilli/ve/local/lib/python2.7/site-packages/libcloud/utils/py3.py:71: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
new session: [rp.session.radical.mturilli.017212.0002]                         \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [osg.xsede-virt-clust:1]                             ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        ........................................................              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        ***********************************************************************|
        *********************************************************             ok

caught Exception: 'NoneType' object has no attribute 'split'

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.radical.mturilli.017212.0002                        \
close pilot manager                                                            \
wait for 1 pilot(s) +                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 1107.5s                                                     ok
Traceback (most recent call last):
  File "./09_mpi_units.py", line 117, in <module>
    ','.join(unit.stdout.split('\n'))))
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by andre-merzky** [comment]
> `/home/mturilli/ve/local/lib/python2.7/site-packages/libcloud/utils/py3.py:71: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")`

This is a strange one -- happy to ignore this and blame python module dependencies or versions...

On point though: MPI won't work in OSG I guess, but the units should show `-` (FAILED) instead of `*` (CANCELED)...  Could it be that the pilot failed for some other reason,  like getting evicted?  If you don't mind, I'll have a look at the pilot sandbox.

**Comment by marksantcroos** [comment]
> /home/mturilli/ve/local/lib/python2.7/site-packages/libcloud/utils/py3.py:71: UserWarning: Missing backports.ssl_match_hostname package warnings.warn("Missing backports.ssl_match_hostname package")
> This is a strange one -- happy to ignore this and blame python module dependencies or versions...

Nah, see that all the time. But that is indeed not an RP issue.

**Comment by ibethune** [comment]
Is this a regression, or just missing functionality?  If the latter, I suggest we defer to the next release.

**Comment by mturilli** [comment]
We are not supposed to run MPI jobs on OSG -- it is not designed for that, at least the portion of OSG we (can) use. We should handle the failure gracefully though, and AFAIH that is what it is missing in RP. If we deem OSG experimental or unsupported I see no problem with deferring this issue to the next release.

**Comment by ibethune** [comment]
OK, so since we will need a 0.45RC2 in any case, I suggest that whether this is fixed or not depends on if the fix would be localised and low-risk (to other configs) - then 0.45, otherwise we defer it.

**Comment by andre-merzky** [comment]
There are a couple of issues here:

  - the RP backfillinf scheduler actually checks if a unit fits onto a pilot - it would have declined an multicore MPI unit.  The examples use the round-robin scheduler by default, which is less clever.  We could add a similar check there.  Conceptually not difficult, but not trivial either (what to do with units which don't fit on any pilot?)
  - the examples are simple in their unit checks: the error you see (`no split() on None`) is just the example code being stupid, not RP doing things wrong, really (failed unit don't have stdout)
  - OSG cannot run MPI: single core MPI units actually should go into FAILED, we may want to confirm this is the case.
