### ISSUE TITLE
RP 0.45.RC1 with GROMACS on Comet fails

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1227]
GROMACS fails on Comet when run via RP.
grompp (gromacs pre-processor) actually executes correctly. 
However, mdrun_mpi fails with the following message in the STDERR file ( identical to Ticket #1218 ): 

```
"/home/marksant/openmpi/installed/rhc/bin/orterun: Error: unknown option "--hnp"
Type '/home/marksant/openmpi/installed/rhc/bin/orterun --help' for usage."
```

Upon opening the STDOUT file, the following message is seen:

```
"PMI2 initialized but returned bad values for size and rank.
This is symptomatic of either a failure to use the
"--mpi=pmi2" flag in SLURM, or a borked PMI2 installation.
If running under SLURM, try adding "-mpi=pmi2" to your
srun command line. If that doesn't work, or if you are
not running under SLURM, try removing or renaming the
pmi2.h header file so PMI2 support will not automatically
be built, reconfigure and build OMPI, and then try again
with only PMI1 support enabled."
```

For reference: this (or a similar) issue has been reported previously for an older version of RP (0.40.1) in ticket #1085

**Comment by marksantcroos** [comment]
For GROMACS (MPI) usage with ORTE, we need a GROMACS compiled against OpenMPI.

**Comment by andre-merzky** [comment]
An suitable ORTE installation is in place at `/home/amerzky/ompi/installed/2017_02_15/`.  Note that this is not really tested yet - I can't get my tests through the queue on Comet it seems... :/

**Comment by vivek-bala** [comment]
I couldn't get any job through the 'compute' queue for over a day. You might want to try the 'debug' queue (2 nodes max).

**Comment by andre-merzky** [comment]
Ah, cool - debug queue indeed works!  the ompi installation seems good, I'll open a PR.

**Comment by andre-merzky** [comment]
@SrinivasMushnoori : can you please give Gromacs another try with the new ompi installation?  Thanks!

**Comment by SrinivasMushnoori** [comment]
Yes, most certainly: I'm working on it.

**Comment by andre-merzky** [comment]
The PR is #1228

**Comment by ibethune** [comment]
@SrinivasMushnoori Have you been able to retest this with 0.45.RC2 yet?

**Comment by SrinivasMushnoori** [comment]
@ibethune I did with an OpenMPI compilation on RC1 and it did work. On RC2, unfortunately I haven't, since I've been busy with a conference. I'm returning later in the evening today, and will have the tests done.

**Comment by SrinivasMushnoori** [comment]
Hi, I'm happy to confirm that RC2 along with an OpenMPI build of GROMACS solves this issue.
Should this ticket be closed now, or would you like me to probe further?

**Comment by andre-merzky** [comment]
Good enough for me, please do close.  Please do update the testing spreadsheet if you get the opportunity.  Thanks!

**Comment by SrinivasMushnoori** [comment]
Closing issue.
