### ISSUE TITLE
RP devel failure on titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1233]
Stack:

```
> radical-stack 
python            : 2.7.9
virtualenv        : /autofs/nccs-svm1_home1/vivekb/ves/seis_env
radical.utils     : v0.45.RC1@devel
saga-python       : v0.45.RC1-4-g6cfe308@devel
radical.pilot     : v0.45.RC1-7-gfbed0d1@devel
```

I have attached the entire sandbox.
[rp.session.titan-ext7.vivekb.017213.0002-pilot.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/783728/rp.session.titan-ext7.vivekb.017213.0002-pilot.0000.zip)

The error seems to be in  ```agent_0.out```. Tail of the file (starting from the error): https://gist.github.com/vivek-bala/0ebf33e4198331e00a8e072293446fda

Let me know how I can debug. 

Also if there is any another rp version that is stable for O(10) tasks on titan for now, please let me know.

**Comment by andre-merzky** [comment]
I am sorry Vivek, I will have to ask you to simply try again: all the traces indicate that the agent got a SIGTERM. At the point where bootstrapping stops, there is not much up which can issue that signal, so I assume it comes (indirectly) from the client side or the batch system. There is also the option that not all logfile were flushed to disk in time -- but then its hard to say anything definitive either :/

What test have you been running? Did you see this take suspiciously long (like, longer than the 40min runtime)? Did the error occur multiple times?

Thanks!

**Comment by vivek-bala** [comment]
> What test have you been running? 

I am trying to get a set of earthquake simulations running. This is the work with the princeton folks.

> Did you see this take suspiciously long (like, longer than the 40min runtime)? 

Yes

I'll test it a couple of times more to verify.

**Comment by andre-merzky** [comment]
>> Did you see this take suspiciously long (like, longer than the 40min runtime)?
> Yes

Ah, interesting.  There are only a few timestamps recorded at that early bootstrapping stage, so its hard to see what's up with that - but 40min. hanging somewhere would explain the `SIGTERM`... 
 
> I'll test it a couple of times more to verify.

Thanks Vivek!

**Comment by ibethune** [comment]
Vivek, have you been able to reproduce this (or not?)

**Comment by ibethune** [comment]
@vivek-bala any update on if you have been able to successfully run on Titan, or are you still hitting this issue?

**Comment by vivek-bala** [comment]
I don't face this issue anymore. Please consider it resolved.
