### ISSUE TITLE
ortelib launcher needs to support pre- and post-exec

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1234]
This is needed by entk

**Comment by ibethune** [comment]
@vivek-bala can you let us know if you are really needing ORTElib for performance reasons for your current  / near-future experiments, or if ORTE is good enough?

**Comment by vivek-bala** [comment]
I think ORTE is enough for my upcoming development and experiments (in the earth science project). 

Just to keep it in the loop and help plan, I think the Incite project would be the one that will have an earlier demand for ORTElib. The project hasn't moved to Titan yet but will soon do I suppose (1-2 months). HtH.
