### ISSUE TITLE
Unable to run 09_mpi_units.py, v0.45.RC2

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1239]
On Gordon, Comet, Stampede I get the following errors:
```
Exception KeyError: KeyError(47584561155520,) in <module 'threading' from '/opt/python/lib/python2.7/threading.py'> ignored
```

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
    from mpi4py import MPI
ImportError: No module named mpi4py
[gcn-7-64.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 42544) exited with status 1
[gcn-7-64.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 1, pid: 42546) exited with status 1
```

**Comment by ibethune** [comment]
@andre-merzky you were able to run the examples on Stampede, which suggests there should be a Python environment with a working mpi4py installed (at least there, if not on Comet or Gordon).  Did you do something different to Ming?

@mingtaiha can you please add the output of ```radical-stack``` to tickets, so we know exactly what stack you are running?

**Comment by mingtaiha** [comment]
Sure, sorry for not adding the stack. Here you go:

```
(ve)[mingtha@workflow rp]$ radical-stack 
python            : 2.7.5
virtualenv        : /home/mingtha/ve
radical.utils     : v0.45.RC2@detached-v0.45.RC2
saga-python       : v0.45.RC2@detached-v0.45.RC2
radical.pilot     : v0.45.RC2@detached-v0.45.RC2
```

**Comment by andre-merzky** [comment]
Now that you mention it, 09 succeeding on stampede *is* surprising :)  Let me check how that worked out (will take a while since stampede is in maintenance)

**Comment by andre-merzky** [comment]
Me reporting success for MPI on stampede was a mistake.

**Comment by ibethune** [comment]
If all the other tests  (apart from 09_mpi... ) are running OK, then we can leave this for the next release.

**Comment by ibethune** [comment]
Suggest we fix deployment on at least one of these target machines for the next release.

**Comment by ibethune** [comment]
Will update the deployment on stampede to include mpi4py so we can run those tests.

**Comment by ibethune** [comment]
@andre-merzky, will you have time to add mpi4py to the stampede environment?

**Comment by andre-merzky** [comment]
Yes, I should be able to do so.

**Comment by andre-merzky** [comment]
Lucky me - stampede has mpi4py in the default python tree now :D
