### ISSUE TITLE
What happens if pre_exec fails?

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1240]
Hello,

I think that if pre_exec fails in a CU the execution of the CU will continue. Am I correct? 

If yes, shouldn't the CU fails since one condition for its execution is not met?

In all of these, I am assuming that the executable will run correctly, whether the pre_exec conditions are met or not.

Thank you
Giannis

**Comment by marksantcroos** [comment]
Ideally the pre_exec isn't much more than some environment variable setting.
In reality it might be a bit more, and there you have a valid point.

**Comment by iparask** [comment]
Is it the same if post_exec fails? I mean, if the executable succeeds and the post_exec fails, will the CU fail?

**Comment by marksantcroos** [comment]
Yeah, I think the same behavior applies.

**Comment by ibethune** [comment]
@iparask can you test the branch fix/issue_1240 if you have a use case relating to this question?  If not, I guess we review the PR and merge...

**Comment by iparask** [comment]
@andre-merzky, I tried the PR but it does not launch even the agent. Initially, I though it was the resource label I used. I found that ```xsede.stampede``` exists in the examples config, but not in the pilot's resource config file. I added ```_ssh``` and still it did not launch the agent. I also tried ```xsede.stampede_ortelib```, but again it did not launch the agent.

I cannot still navigate the log files easily, so can you point me where I should look what went wrong?

**Comment by andre-merzky** [comment]
That is unexpected - none of the code changes are related to the pilot startup, and the code paths should only get triggered after the pilot becomes active.

For the logfiles: in the directory where your run your application script, you should find a new subdir with the session ID, containing all logs and profiles.  Usually a `grep ERROR *.log` in that directory gives you a good starting point.  Agent submission problems are likely recorded in `pmgr.launching.0.child.log`.  One the pilot bootstraps, you should find a subdir with the same name in `$HOME/radical.pilot.sandbox/` (or similar, depending on the target resource's shared FS setup), which then contains the logs and profiles for the pilot agent -- but I think you know about that part already, right?  So, the client side now follows the same scheme.

**Comment by iparask** [comment]
:) I know the agent part, but not the client part yet! Here is the error:

```
pmgr.0000.log:2017-05-27 19:58:41,154: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : [Callback]: pilot 'pilot.0000' failed
pmgr.0000.log:2017-05-27 19:58:41,154: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : abort: RuntimeError('pilot pilot.0000 failed - fatal!',)
pmgr.launching.0.child.log:2017-05-27 19:58:40,985: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
pmgr.launching.0.child.log:2017-05-27 19:58:43,114: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: ERROR   : abort: KeyError('pilot.0000',)
update.0.log:2017-05-27 19:58:44,006: update.0            : update.0                        : MainThread     : ERROR   : term msg error not sent: error(32, 'Broken pipe')
```

Any ideas what caused it?

**Comment by andre-merzky** [comment]
Ah, cool :)  Either way, check the exception message after the `bulk launch failed` for the cause of your problem...

Thanks!

**Comment by iparask** [comment]
This is what pointed to SAGA version:
```
2017-05-27 19:58:40,985: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 323, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 513, in _start_pilot_bulk
    jc.run()
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/saga/task.py", line 400, in run
    threads.append (ru.Thread.Run (m_handle, tasks))
AttributeError: type object 'Thread' has no attribute 'Run'
```

**Comment by andre-merzky** [comment]
Indeed - that is a mismatch between SAGA and Utils versions.

**Comment by iparask** [comment]
I am closing this ticket since it is satisfied by its respective PR
