### ISSUE TITLE
Create databases 'on the fly'

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1242]
We have a requirement from one of our collaborators to be able to create databases 'on the fly' given the URL to an existing mongodb instance. See https://github.com/radical-collaboration/GB-SC18/issues/2.

I was checking if this was already supported in RP by doing the following:

```
session = rp.Session(database_url='mongodb://rp:rp@ds015335.mlab.com:15335/', database_name = 'test_newdb')
```
but this fails with:
```
radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'mongodb://rp:rp@ds015335.mlab.com:15335/test_newdb' incorrect?): command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('autoAuthorize', 1), ('payload', Binary('n,,n=rp,r=ODg3NjU3Nzg4NjI0', 0))]) on namespace test_newdb.$cmd failed: Authentication failed
```

It might be that it is supported but I'm specifying the parameters incorrectly, do let me know in this case.

But if this feature is not supported, I suppose something like the following should suffice(?):

```
from pymongo import Connection
connection = Connection('mongodb://rp:rp@ds015335.mlab.com','15335')
db = connection['test_newdb']
```

Although this can be done in entk and passed to RP, I think the appropriate place to do this might be RP itself. Thoughts?

**Comment by marksantcroos** [comment]
I would be very hesitant to put this into RP. 
The management of users and databases is really outside of the scope of RP.
(That even goes for ENTK probably)

**Comment by vivek-bala** [comment]
I agree. I haven't really thought about the can of worms that this feature might open. I think this issue is triggered by the fact that it is mentioned in the documentation (http://radicalpilot.readthedocs.io/en/latest/installation.html#mongodb-service):

```
The dbname component in the database url can be any valid MongoDB database name (ie. it musy not contain dots). RP will create that DB on the fly.
```

If we choose/decide not to support this, then we might want to remove that statement. Since according to the documentation, it is a feature that is currently supported (leading to issue https://github.com/radical-collaboration/GB-SC18/issues/2).

**Comment by marksantcroos** [comment]
Agreed on improvement of documentation.

**Comment by andre-merzky** [comment]
The term `database` is incorrectly used here I think.  RP will create a new *collection* in an existing database to store session documents, and we usually call that 'the session DB'.  We should be more careful with wording here, and indeed fix the documentation.

**Comment by ibethune** [comment]
Not necessary to fix before the release, I think.

**Comment by vivek-bala** [comment]
So, I take it there is consensus that creating a database 'on the fly' is not something that will/can be supported? I would like to report back in the original ticket.

**Comment by andre-merzky** [comment]
indeed, as the user and security configuration cannot sensibly be automated.

**Comment by andre-merzky** [comment]
Vivek, can you do that, please?

**Comment by vivek-bala** [comment]
Thanks, just did that. I'll leave this open as it is now a documentation issue.

**Comment by ibethune** [comment]
@vivek-bala please can you check that the doc update in PR #1325 covers the case you asked about, then once it's merged we'll close this.
