### ISSUE TITLE
Message warning about missing backports.ssl_match_hostname package

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1244]
```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/mturilli/ve
radical.utils     : v0.45.RC2@HEAD-detached-at-v0.45.RC2
saga-python       : v0.45.RC2@HEAD-detached-at-v0.45.RC2
radical.pilot     : v0.45.RC2@HEAD-detached-at-v0.45.RC2

rp/examples$ ./* *
/home/mturilli/ve/local/lib/python2.7/site-packages/libcloud/utils/py3.py:71: UserWarning: Missing backports.ssl_match_hostname package
```

**Comment by marksantcroos** [comment]
```pip install backports.ssl_match_hostname``` resolves it, but unclear whether its a good idea to add that to the dependency chain.

**Comment by andre-merzky** [comment]
yeah, this started to pop up recently - I am also unsure about the implications of adding that module as dependency.

We could also go the other way though: RS' libcloud resource adaptor is rarely used at the moment, and we could make it an *optional* dependency - which also would reduce RP pilot bootstrapping time.  Using that adaptor would though then require to install RS via: 

```
pip install 'saga-python[libcloud]'
```

I would prefer that approach - introducing this mechanism would allow us to keep the default stack installation lean.
```

**Comment by marksantcroos** [comment]
I'm surprised you didn't see it before. I think I've seen it since I started using the radical vm.

**Comment by mturilli** [comment]
Assuming very clear documentation, I would agree on keeping the installation lean
