### ISSUE TITLE
OSG: fails to cancel all running pilots once all units are done

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1246]
```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/mturilli/ve/AIMES-EXPERIENCE
radical.utils     : v0.44.RC1-11-ge108e90@experiment-aimes
saga-python       : v0.44-137-g98a692ed@experiment-aimes
radical.pilot     : v0.40.1-243-g52f0a6ce@experiment-aimes
```
Happens often, last session with this problem:
```
rp.session.radical.mturilli.017223.0002
```
RP exits normally if I manually clean the queue from the remaining pilots.

**Comment by andre-merzky** [comment]
I consider that not relevant to 0.45,  since we don't support the 'many pilots' use case there anyway, but its relevant in the 0.46 context which introduces it.

**Comment by andre-merzky** [comment]
This should be checked against the termination branch.

**Comment by ibethune** [comment]
@mturilli please test when you have the termination branches running to OSG.

**Comment by ibethune** [comment]
This is stuck behind #1241, I think.

**Comment by ibethune** [comment]
Now that #1241 is resolved (I assume from the comments that if you run with a valid project ID then you are able to run jobs), is this one still an issue?

**Comment by mturilli** [comment]
Sadly yes but I need a couple of more tests to see whether the failure I saw depended on RP.

**Comment by andre-merzky** [comment]
Matteo, should we move this one to the next release?

**Comment by andre-merzky** [comment]
did so...

**Comment by mturilli** [comment]
Thanks. Currently, OSG support seems to be low priority. I may have to run some more experiments to collect data about corner cases. In that case, I will update the ticket.
