### ISSUE TITLE
Documentation of RP config file

### ISSUE THREAD

**Issue by nsplattner** [radical-cybertools/radical.pilot#1261]
For storage of mass data its important to have a config file or config options of RP easily accessible. Currently this is not well documented.
(see https://github.com/markovmodel/adaptive-sampling/issues/67 for details)

**Comment by marksantcroos** [comment]
FYI, the repo that you refer to is private.

**Comment by nsplattner** [comment]
I'm aware of that and I'm not the owner. I opened this issue here upon request of common contributors. Please ask @andre-merzky for details.

**Comment by andre-merzky** [comment]
oops, my mistake.  But the point mostly is that editing config files in the installation is not really practical for end users, which is why we have the config overloading mechanism in the first place.  Unless that is documented though its not really usable either...

**Comment by mturilli** [comment]
@andre-merzky was this documented? Should we add a label `topic:configuration`?

**Comment by andre-merzky** [comment]
A topic for configuration  might make sense.  The issue is not addressed, yet.  The code will change in the upcoming release, but the  state of documentation did not improve.

**Comment by andre-merzky** [comment]
Moved to v2.

**Comment by andre-merzky** [comment]
outdated
