### ISSUE TITLE
Pilot does not enter the queue if the wall-time is 6hr

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1262]
Hi,
I tried to submit pilot with a wall-time of 6 hours on TITAN's batch queue. Everything seems to work fine but if I look the queue with qstat I am not able to see my jobs.
No error is shown, RP seems to wait for the execution of the pilot even if the pilot is not there.
In the sandbox, I found this:
```pilot pmgr.0000.log:2017-03-04 23:16:46,505: pmgr.0000           : MainProcess                     : pmgr.0000.ctrl.watcher: ERROR   : pmgr.launching.queue.bridge died - shutting down
pmgr.launching.0.child.log:2017-03-04 23:14:29,605: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
```
I do not know if this might be the problem.

Cheers,

Alessio

P.s. Note that I tried to submit a pilot with a smaller wall-time with the same code and everything worked as it should.

**Comment by marksantcroos** [comment]
What branches are you using?

Any more useful information in the logs?

What queue are you submitting to?

**Comment by andre-merzky** [comment]
`bulk launch failed`

This very likely is the problem.  Just before that message, you likely should see either a stack trace or an error message from the batch system in the logfile - can you paste that (completely), or send the complete `pmgr.launching.0.child.log`, please?

**Comment by AA919** [comment]
This is on me. I visualized a wall-time but I asked for another (which was more than the limit).
I do not know why RP does not fail as it did in the past though.

Sorry for the bothering,

Alessio

**Comment by marksantcroos** [comment]
Thanks for getting back. Still the error mode should have been different.

**Comment by andre-merzky** [comment]
Yes, indeed - this is alas (AFAICS) one of the known termination problems...
