### ISSUE TITLE
radicalpilot-fetch-profiles creates two nested sid directories

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1278]
```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/mturilli/ve/AIMES-EXPERIENCE-XSEDE
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-9-gf9b04d83@devel
radical.pilot     : split-27-g8e6be2ba@devel
```
```
$ cd /tmp/profiles
$ radicalpilot-fetch-profiles -c /home/mturilli/experiments/AIMES-Experience/XSEDE/bin rp.session.one.mturilli.017238.0010
$ ls rp.session.one.mturilli.017238.0010
rp.session.one.mturilli.017238.0010  rp.session.one.mturilli.017238.0010.json
$ ls rp.session.one.mturilli.017238.0010/rp.session.one.mturilli.017238.0010
pilot.0000                   pmgr.launching.0.prof                     umgr.scheduling.0.child.prof     umgr.staging.input.0.prof         update.0.child.prof
pmgr.0000.prof               rp.session.one.mturilli.017238.0010.prof  umgr.scheduling.0.prof           umgr.staging.output.0.child.prof  update.0.prof
pmgr.launching.0.child.prof  umgr.0000.prof                            umgr.staging.input.0.child.prof  umgr.staging.output.0.prof
```
Note that this does not happen with sessions run on OSG!

**Comment by andre-merzky** [comment]
Hmm, funny, but that should indeed not happen...

**Comment by ibethune** [comment]
Can we confirm this is a regression vs previous releases, or has it never worked correctly?  If it's not a trivial fix I would suggest pushing out to a future release.

**Comment by andre-merzky** [comment]
I am not sure if it is a regression.  I would leave it to Matteo's judgement if this is urgent to fix, as he is the one suffering.

I **guess** this is a semantic discrepancy on data staging in the SAGA layer, where adaptors seems to behave differently.  Probably not hard to fix, but possible a little tedious to find.

**Comment by mturilli** [comment]
It is an annoyance, not a bug that stops me from doing my experiments.

**Comment by ibethune** [comment]
I'm inclined to defer this, rather than cramming more work into the current milestone.
