### ISSUE TITLE
Instructions on how to compile applications against custom RP's OpenMPI installation on Blue Waters and other machines

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1283]
I needed this in the context of Blue Waters. On that machine ORTE is using custom OpenMPI installation and if you compile your application using instructions provided by cluster admins, it will not run. I don't think simply knowing the path to MPI execs is sufficient, since some applications require to use the same programming environments and compilers which were used for OpenMPI. 

In one sentence: Please provide instructions on how users should compile their applications.

**Comment by andre-merzky** [comment]
Hey Antons, 

this basically means that our custom openmpi module should be loaded instead of the system one.  That provides the development headers and libraries to compile and link against.

Well, at least this is what I assume.  If that fails for you for some reason, please let us know, and we'll should likely be able to fix the module setup!

best, Andre.

**Comment by antonst** [comment]
Hi Andre,

Thanks. What is the name of the module I have to load?

**Comment by andre-merzky** [comment]
I am not exactly sure about the state of affairs on BW specifically, but basically you would run the same commands as specific in `pre_bootstrap_1` in the resource config, like here: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_ncsa.json#L49.  That should make the custom openmpi module available in the env, and provide the correct includes and libs for building MPI applications.

**Comment by andre-merzky** [comment]
A note has been added to the documentation.  We do not provide specific instructions for each resource and configuration, but instead point out when recompilation is needed, and ask to ping the mailing list if support is needed.
