### ISSUE TITLE
config management does not scale well

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1287]
Like, we have 5 config keys for stampede - and any additional options for python version or anaconda are orthogonal, and always require a new complete config entry.  This should be made composable, maybe along the lines we use for the `schema` entries.

FWIW, this is related to (but different from) #1261.

**Comment by mturilli** [comment]
@andre-merzky was this addressed by the following changes in RP configuration?

**Comment by andre-merzky** [comment]
This will be addressed in v.2 which uses a composable configuration scheme where stampede configs are independent of, say, configuration settings for agent layout and launch methods.

**Comment by andre-merzky** [comment]
outdated and fixed
