### ISSUE TITLE
tag core IDs

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1289]
We want to identify how long a core remains idle after a CU finished, in the context of scheduling overhead.  That would basically be the time from when the scheduler learns about the core being freed, to the point where that specific core got assigned to the next units.

We do profile both free and alloc of cores, but we do not identify which core gets freed/allocced.  This ticket is asking to add that information.

**Comment by mturilli** [comment]
@andre-merzky any progress?

**Comment by andre-merzky** [comment]
Yes, this information can now derived from the session information, and RA can use that information already.  Thanks, can be closed.
