### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1291]
I set up a virtualenv on my Mac using the current devel stack:

```
(rp-devel-env) Iains-MacBook-Pro:rp-devel-env ibethune$ radical-stack 
python            : 2.7.13
virtualenv        : /Users/ibethune/Desktop/rp-devel-env
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-11-g807713c6@devel
radical.pilot     : split-28-gae1602f6@devel
```

Running the first example script (even to localhost), results in the following error:

```
(rp-devel-env) Iains-MacBook-Pro:examples ibethune$ ./00_getting_started.py
new session: [rp.session.Iains-MacBook-Pro.local.ibethune.017249.0006]         \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
create unit managerToo many open files (bundled/zeromq/src/kqueue.cpp:61)
Abort trap: 6
```

I was able to work around this by upping my ulimit on open files (which defaults to 256) to 2000 (just a guess).  Looks like some behaviour has changed since 0.45 and either we should try to check if the ulimit is enough (or if we have permission) increase it?

**Comment by itomaldonado** [comment]
I can confirm this as well, I started having the same issue with the current version.
```
(venv) itoMac:~/git/radical.pilot radical-stack 
python            : 2.7.12
virtualenv        : /Users/itomaldonado/git/radical.pilot/venv
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-11-g807713c6@devel
radical.pilot     : split-28-gae1602f6@devel
```

I had to do the `ulimit` workaround by putting it in my `~/.bash_profile` for now.

**Comment by itomaldonado** [comment]
I believe this may be related to #1122?

**Comment by andre-merzky** [comment]
Yes, that is indeed the same as #1122.  We agreed back then that this is a documentation issue.  I am not yet sure if there is an easy way to avoid this, as we open many logging and profiling handles in total... :/

**Comment by ibethune** [comment]
Well since this is tripping over multiple people now, we should fix the documentation in this release cycle.  Andre, can be be definitive about how many concurrent open files we need to allow?

**Comment by andre-merzky** [comment]
I need to measure this.  We probably can also do an estimate and add some safety.  Either way, I will provide and document a number.

**Comment by ibethune** [comment]
I think, in addition to documenting, if we know there is a lower limit, and we can check on startup (i.e. well before the pilot starts on a remote resource) we should exit with a helpful error message, rather than failing later on with a hard error.

**Comment by andre-merzky** [comment]
In `fix/macos`, we now increase the open file limit when a session gets created, and also when the bootstrapper starts (for the agent limits), so I hope this is resolved.  Please let me know if you think that warrants a mention in the documentation anyway.

FWIW, `fix/macos` needs RU branch `feature/poll`.

**Comment by ibethune** [comment]
OK, this is working for me, so I think we are good, and no doc update is needed.
