### ISSUE TITLE
Is there backward compatibility?

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1292]
Hello guys,

I am trying to run some scripts of mine which are using attributes like Session Name, specific schedulers like DIRECT_SUBMISSION, probe the cu states and write CSV files, with the devel branch. The reason I am using devel, is that it has the Comet fix and I will probably be able to scale my experiments there.

What I found out is that my scripts fail, because of changes that either I did not track or were not communicated very well.

Is there any documentation of all the changes between v0.45 of RP and Devel? I would like to be able to do CTRL+F and search to find the differences.

Example:
```
v0.45 Unit States:
# -----------------------------------------------------------------------------
# ComputeUnit States
UNSCHEDULED                  = 'Unscheduled'
PENDING_INPUT_STAGING        = 'PendingInputStaging'
STAGING_INPUT                = 'StagingInput'
AGENT_STAGING_INPUT_PENDING  = 'AgentStagingInputPending'
AGENT_STAGING_INPUT          = 'AgentStagingInput'
PENDING_EXECUTION            = 'PendingExecution'
SCHEDULING                   = 'Scheduling'
ALLOCATING_PENDING           = 'AllocatingPending'
ALLOCATING                   = 'Allocating'
EXECUTING_PENDING            = 'ExecutingPending'
EXECUTING                    = 'Executing'
AGENT_EXECUTING              = 'Executing'
AGENT_STAGING_OUTPUT_PENDING = 'AgentStagingOutputPending'
AGENT_STAGING_OUTPUT         = 'AgentStagingOutput'
PENDING_OUTPUT_STAGING       = 'PendingOutputStaging'
STAGING_OUTPUT               = 'StagingOutput'
```

```
Devel Unit States:
# ------------------------------------------------------------------------------
# 
# unit states
#
UMGR_SCHEDULING_PENDING      = 'UMGR_SCHEDULING_PENDING'
UMGR_SCHEDULING              = 'UMGR_SCHEDULING'
UMGR_STAGING_INPUT_PENDING   = 'UMGR_STAGING_INPUT_PENDING'
UMGR_STAGING_INPUT           = 'UMGR_STAGING_INPUT'
AGENT_STAGING_INPUT_PENDING  = 'AGENT_STAGING_INPUT_PENDING'
AGENT_STAGING_INPUT          = 'AGENT_STAGING_INPUT'
AGENT_SCHEDULING_PENDING     = 'AGENT_SCHEDULING_PENDING'
AGENT_SCHEDULING             = 'AGENT_SCHEDULING'
AGENT_EXECUTING_PENDING      = 'AGENT_EXECUTING_PENDING'
AGENT_EXECUTING              = 'AGENT_EXECUTING'
AGENT_STAGING_OUTPUT_PENDING = 'AGENT_STAGING_OUTPUT_PENDING'
AGENT_STAGING_OUTPUT         = 'AGENT_STAGING_OUTPUT'
UMGR_STAGING_OUTPUT_PENDING  = 'UMGR_STAGING_OUTPUT_PENDING'
UMGR_STAGING_OUTPUT          = 'UMGR_STAGING_OUTPUT'
```

Example 2: Session Name does not exist any more
Thank you,
Giannis

**Comment by ibethune** [comment]
This would be a good topic to discuss in the development meeting, unfortunately @andre-merzky can't make it today.  Is there some documentation on the updates to the states that I can point people to?

**Comment by marksantcroos** [comment]
There are a couple of issues I raised when I started to use the split branch, where some of them involve API changes. You might want to gather those too.

**Comment by ibethune** [comment]
@marksantcroos can you list the relevant issue numbers?  We did go back through open tickets, but if we missed some that weren't assigned to the 0.46 milestone please let me know.

**Comment by andre-merzky** [comment]
Other incompatibilities are:

  * naming of scheduler constants
  * `database_url` -> `dburl`

**Comment by ibethune** [comment]
The correspondance between the states should be documented here: https://github.com/radical-cybertools/radical.pilot/wiki/State-Model-Evolution.  Hopefully that is enough for @iparask to get his scripts working.

The ticket should then be used to track documentaiton of the API changes in 0.46

**Comment by andre-merzky** [comment]
Here is another backward compatibility thing which adds deprecation:

The file staging used to support the schema `staging://`, which referred to the `staging_area` subdir in the pilot sandbox.  This is now replaced by `pilot://`, and other schemas have been introduced, too, with the following meaning

* `client://`: the application PWD
* `resource://`: `staging_area` subdir in the global RP sandbox on the target resource, usually `$HOME/radical.pilot.sandbox/staging_area`
* `pilot://`: see above, the `staging_area` subdir in the pilot sandbox
* `unit://`: the unit sandbox

`staging://` is still supported, but will trigger a deprecation warning on stderr.
