### ISSUE TITLE
Error on termination: KeyError: 'working_directory'

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1295]
The Jenkins test of branch fix/issue_1276 failed at the end of the 01_unit_details.py script.  See https://jenkins.radical-project.org/job/radical.pilot.devel.test.pr/26/console for full output.

@itomaldonado can you check to see if this is an issue todo with the Jenkins setup itself?
Assuming, not please assign to @andre-merzky

**Comment by marksantcroos** [comment]
Are you going to duplicate all of my tickets? ;-) https://github.com/radical-cybertools/radical.pilot/issues/1170

**Comment by ibethune** [comment]
Thanks Mark, I even searched before opening this one but didn't find the original!  Closing as duplicate.
