### ISSUE TITLE
Remove default configurations and always append _launch_method

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1299]
As discussed at the devel meeting, we need to move away from having default configs which change launch_method, but rather expose the choice that the user needs to make.

**Comment by mturilli** [comment]
If this is not going to be prioritized, can we have a transitory unification of the launch_method options? Something like:
```
xsede.comet_ssh
xsede.comet_orte
xsede.comet_ortelib

xsede.stampede_ssh
xsede.stampede_orte
xsede.stampede_ortelib

xsede.supermic_ssh
xsede.supermic_orte
xsede.supermic_ortelib
...
```
I am not sure how easy/rapid/painless is to do this.

**Comment by ibethune** [comment]
Hi Matteo, yes this is exactly what I had in mind.  I would think it is a straightforward renaming, and restoring the SSH config where this has been replaced by an orte/ortelib default.

**Comment by andre-merzky** [comment]
Ack, renaming is indeed straight-forward, but note that it will not always result in the ability to choose the same suffix on all machines.  Like, `*_orte` will not always be available, some machines use `rsh` instead of `ssh`, etc.  But that, as discussed, cannot be solved quickly, so the rename is probably good enough as a quick stopgap solution.

**Comment by marksantcroos** [comment]
So we loose a "default" then?

My $0.02: I would invest my time towards consolidation of using one method per resource.

**Comment by andre-merzky** [comment]
I am sure that is very valid towards our external users - they should, on a first approach, not have to choose options which are difficult to choose from.

Consolidation will however only really begin to make sense once we have pre- and post-exec for orte/ortelib - until then we have to pick between feature and performance/scalability.

**Comment by marksantcroos** [comment]
Note that I have nothing against consistent suffices, as far as possible.

We have the ability to create aliases, right? So we could create all the entries with suffices and then create an alias without prefix that serves as a default.

**Comment by andre-merzky** [comment]
Hmm, indeed, we could use aliases to define experiment specific sets, like

```
  alias xsede.stampede_aimes xsede.stampede_ssh
  alias xsede.comet_aimes xsede.comet_ortelib
```

or whatever, didn't think of that.  For those we don't know, we introduced aliases to allow for some backward compatibility when we changed our resource labe scheme a looong time back: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_aliases.json

We still can have more consistent suffixes of course...

**Comment by ibethune** [comment]
I will close after the merge
