### ISSUE TITLE
`resource_details` missing in split termination branch

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1302]
```
stderr: Traceback (most recent call last):
  File "StreamingProducer.py", line 2, in <module>
    import numpy as np
ImportError: No module named numpy
```

I am trying to use numpy on stampede but the system can't detect it. 

```
(streaming)georgeha@js-17-215:~/repos/midas/streaming/StreamingKMeans$ radical-stack
python            : 2.7.6
virtualenv        : /home/georgeha/ves/streaming
radical.utils     : 0.45
saga-python       : 0.45.1
radical.pilot     : feature-streaming-pre_split-1-g78904ea@feature-streaming
```

**Comment by andre-merzky** [comment]
Can you please send a unit description?

**Comment by vivek-bala** [comment]
Which python are using in the CU?

**Comment by georgeha** [comment]
``` 
cudesc = rp.ComputeUnitDescription()
150         cudesc.pre_exec = ['module load python']  // I tried with and without this command
151         cudesc.executable = 'python'
152         cudesc.arguments = ['StreamingProducer.py',broker]                                                     
153         cudesc.input_staging = ['StreamingProducer.py']
154         cudesc.cores = 4
```

I am using python/2.7.12

**Comment by vivek-bala** [comment]
Can you replace the pre_exec with the following: ```cudesc.pre_exec = ['module list','module load python', 'module list', 'which python']``` and paste the output here (both stdout, stderr).

**Comment by iparask** [comment]
George, please also paste the resource configuration you are using. There is a possibility that either you do not have the fix for ticket #1043 or you the resource configuration is not fully correct

**Comment by georgeha** [comment]
stdout:
```
stderr: 
Currently Loaded Modules:
  1) xalt/0.6   3) intel/15.0.2   5) python/2.7.12
  2) TACC       4) mvapich2/2.1   6) jdk64/1.8.0

 


Currently Loaded Modules:
  1) xalt/0.6   3) intel/15.0.2   5) jdk64/1.8.0
  2) TACC       4) mvapich2/2.1   6) python/2.7.12

 

Traceback (most recent call last):
  File "StreamingProducer.py", line 2, in <module>
    import numpy as np
ImportError: No module named bumpy
```
STDOUT: /opt/apps/intel15/python/2.7.12/bin/python

I am using streaming repo which  I created it in Autumn, so I don't know if recent fixes are included

**Comment by andre-merzky** [comment]
```
No module named bumpy
```

Is this a typo?

**Comment by iparask** [comment]
Which python is used by Kafka? Are you sure it is using the one you are reporting? Can it be like PySpark which uses what ever python is used to launch it?

**Comment by georgeha** [comment]
Somehow I did that while copying-pasting. The correct output is numpy

**Comment by andre-merzky** [comment]
With current devel and `examples/00_getting_started.py` changed to contain:

```py
            cud = rp.ComputeUnitDescription()
            cud.pre_exec   = ['module load python',
                              'which python']
            cud.executable = 'python'
            cud.arguments  = ['-c', 'import numpy as np; print np.__file__']
```

I get the expected stdout/stderr:

```
Resetting modules to system default

/opt/apps/intel15/python/2.7.12/bin/python
/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/__init__.py
```

when running against `xsede.stampede`.  Can you please verify that this works for you?  From there we can try to see what differs from your problematic run...

**Comment by georgeha** [comment]
This is my 
stdout:

```
/usr/bin/python
/usr/lib64/python2.6/site-packages/numpy/__init__.pyc
```
I got nothing in stderr

**Comment by andre-merzky** [comment]
With the same pre_exec, and the same resource label?

**Comment by georgeha** [comment]
Ok, we are at the same page Andre. I got the same output with you. I hadn't pulled the latest version.

**Comment by andre-merzky** [comment]
Ah, ok.  Can you use that latest version, or do you need to stick to an older one and need a fix there?  If you can use it, I guess the ticket can be closed?

**Comment by georgeha** [comment]
I pulled the changes from devel to streaming branch and now nothing works for me. I get errors even for the scheduler

**Comment by georgeha** [comment]
Hi Andre. Can we apply [these](https://github.com/radical-cybertools/radical.pilot/issues/1305) fixes to streaming branch too?

**Comment by andre-merzky** [comment]
Those fixes are in devel now, so you should be able to get the respective commits when merging from devel again.  Or is that not sensible for some reason?  

BTW, as said on the call: I'd be happy to do that merge for you, but it would be great to get a test script to verify the result of the merge...

**Comment by georgeha** [comment]
Thanks andre. [Here](https://github.com/radical-cybertools/midas/tree/master/streaming/streaming_startup) are the test script that you can use. I tried to merge but i still can't run the scripts.

**Comment by georgeha** [comment]
Andre is there any update here?

**Comment by andre-merzky** [comment]
Hey @georgeha - I finally looked into it.  Alas, it seems like the pilot is hitting a deployment snafu: it complains about `wget http://mirror.cc.columbia.edu/pub/software/apache/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz` failing, and indeed that seems to fail with a permission denied.  Any idea whats up here?

Thanks, Andre.

**Comment by georgeha** [comment]
@andre-merzky  you can replace it with that: `http://apache.claz.org/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz` it is the same version but from a working mirror.

**Comment by georgeha** [comment]
Hi @andre-merzky  did you manage to take a look at it? I need to run some experiments using this branch. Thanks

**Comment by andre-merzky** [comment]
Hmm, apart from the usual termination problems and the fact that your `pi.py` thinks that `Pi is roughly 3.138312`, all seems to work well for me.  I needed some small changes in `submit_bot.py` though (https://gist.github.com/andre-merzky/bd0ea7f15a64fa9589d0a048662203a9).

Here is what I did:

```sh
$ cd /tmp/
$ virtualenv ve
$ source ve/bin/activate
$ pip install radical.utils saga-python

$ git clone git@github.com:radical-cybertools/radical.pilot.git
$ cd radical.pilot
$ git checkout feature/streaming
$ pip install .
$ cd ..

$ wget https://raw.githubusercontent.com/radical-cybertools/midas/master/streaming/streaming_startup/pi.py
$ wget https://raw.githubusercontent.com/radical-cybertools/midas/master/streaming/streaming_startup/submit_bot.py
$ vi submit_bot.py
$ python submit_bot.py 
```

**Comment by andre-merzky** [comment]
@georgeha: can you please try the above steps?

**Comment by georgeha** [comment]
Hi @andre-merzky,

I tried that and the example is working, but the 
```
info = info['resource_details']['lm_detail'] 
```
doesn't work. And it is important for streaming because in this dictionary I put all the important urls that kafla connects.

**Comment by andre-merzky** [comment]
Ah, but that is a different issue then :)  Will check...

**Comment by andre-merzky** [comment]
This should work again per 7d7c385a2c23c158149e252990432ff3c25a6898 - but I only tested with the fork launcher.  Can you please give it a try with Kafka / Spark?  Thanks!

**Comment by georgeha** [comment]
Hi andre,

```
{'uid': 'pilot.0000', 'pmgr': 'pmgr.0000', 'stdout': None, 'session': 'rp.session.one.george.017279.0004', 'description': {'project': 'TG-MCB090174', 'resource': 'xsede.stampede_streaming', 'exit_on_error': False, 'candidate_hosts': None, 'queue': 'development', 'sandbox': None, 'cleanup': False, 'access_schema': 'gsissh', 'memory': None, 'cores': 32, 'runtime': 8}, 'resource_details': None, 'resource': 'xsede.stampede_streaming', 'log': None, 'state': u'PMGR_ACTIVE', 'sandbox': u'gsisftp://stampede.tacc.utexas.edu:2222/work/03662/tg829618/radical.pilot.sandbox/rp.session.one.george.017279.0004/pilot.0000/', 'stderr': None, 'type': 'pilot'}
```
I  still don't see any value in resource_details, in feature/streaming branch.

**Comment by andre-merzky** [comment]
I added that commit to the feature/streaming branch now - would you be so kind to give it another try, please?  Thanks!

**Comment by georgeha** [comment]
Yes it works now. Thank you very much!

**Comment by georgeha** [comment]
Should I close the ticket now?

**Comment by andre-merzky** [comment]
Yes, please do :)
