### ISSUE TITLE
Default python configuration with Anaconda

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1304]
As promised on Friday morning, this is the bootstrap_1.out from a run Vivek did on Supermic:

[bootstrap_1.out.zip](https://github.com/radical-cybertools/radical.pilot/files/888737/bootstrap_1.out.zip)

**Comment by ibethune** [comment]
Can you comment on if this is a regression in 0.46, request for new functionality, or what?

**Comment by andre-merzky** [comment]
It is a **pro**gression! We don't understand yet how, thus the ticket, but it is not urgent to look into.

**Comment by andre-merzky** [comment]
Hmm, this log actually looks clean enough.  I would suggest we accept that the default config *can* sometimes work with an anaconda Python installation - but I would not document (and thus not support) this setup.  

Any objection?

**Comment by iparask** [comment]
So, I found out why it works. The python module loaded, while the Pilot is bootstrapped, is very old and support the virtualenv command. If the module change to something newer, then the python distribution flag has to change to anaconda

**Comment by andre-merzky** [comment]
Funny...  Thanks for the follow-up - better to not rely on magic...  Do you see any need to update the python module though for supermic?  Otherwise we can just leave things as they are, and pick it up again once the system configs change...

**Comment by andre-merzky** [comment]
We consider this a feature, not a bug, and close the ticket.
