### ISSUE TITLE
doc matrix

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1311]
document resource configurations

**Comment by ibethune** [comment]
@mturilli can you let me know if you have the bandwidth to do this in the next week?

**Comment by mturilli** [comment]
Yes, I should be able to do that.

**Comment by ibethune** [comment]
@mturilli just to check if this is still on your radar?

**Comment by andre-merzky** [comment]
Matteo, is this still something you think we should do (for this release)?
