### ISSUE TITLE
agent executor dies on titan with core dump

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1314]
In a run with 70k units on a 1024 core pilot the agent dies after ~5000 units.

In agent_1.log I see:
```
2017-04-12 06:43:23,633: agent_1             : MainProcess                     : agent_1.ctrl.watcher: ERROR   : agent.executing.0 died - shutting down
```

I get a core file and the stack looks like:
```
$ gdb python core
(gdb) bt
#0  0x00002aaaabe8235b in memcpy () from /lib64/libc.so.6
#1  0x00002aaab24df940 in zmq::encoder_base_t<zmq::v2_encoder_t>::encode (this=0xb6a0b0, data_=0x2aaabc51b178, size_=<optimized out>) at bundled/zeromq/src/encoder.hpp:123
#2  0x00002aaab24e165b in zmq::stream_engine_t::out_event (this=0xb7edc0) at bundled/zeromq/src/stream_engine.cpp:365
#3  0x00002aaab24e6c7c in zmq::io_thread_t::in_event (this=0xa5afd0) at bundled/zeromq/src/io_thread.cpp:83
#4  0x00002aaab24e7fae in zmq::epoll_t::loop (this=0xb68aa0) at bundled/zeromq/src/epoll.cpp:176
#5  0x00002aaab24e6440 in thread_routine (arg_=0xb68b20) at bundled/zeromq/src/thread.cpp:96
#6  0x00002aaaab563806 in start_thread () from /lib64/libpthread.so.0
#7  0x00002aaaabed99bd in clone () from /lib64/libc.so.6
#8  0x0000000000000000 in ?? ()
```

What I noticed is that I didn't get any updates on the client, as if the agent is queuing up status updates or so.

For record keeping: rp.session.titan-ext7.marksant1.017268.0004

**Comment by andre-merzky** [comment]
I am *really* glad we are not running out of limits :package: 

Does that happen every time?  Do you happen to have an indication on memory usage, and total number of threads?  Likely not, but I wanted to ask.

What specifically does 'after 5000 units' mean - 5000 finished, or arriving in the agent?

**Comment by ibethune** [comment]
Should fixing this be in-scope for 0.46.  Bearing in mind (IMO) we don't have any documented limits, I would say yes if ( this is a regression vs an earlier release || this is blocking issue for Mark) else defer for consideration in next release.

**Comment by andre-merzky** [comment]
￼￼I would like to argue that fixing coredumps in lower layers are out of scope.  Once this is reproducible, or at least better understood, we should open a ticket toward libzmq, pyzmq, Python, or whatever appears to be the most likely culprit.

**Comment by ibethune** [comment]
Right, let's do that.

**Comment by andre-merzky** [comment]
Mark, is this still a concern on your end?
