### ISSUE TITLE
Atlas workload does not work anymore on split branch

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1323]
Hi,
I noticed that Altas workload does not work anymore on split branch. It seems the error that we have with the previous versions of ORTE. CUs start but go so slow that the pilot hits the walltime.

I tried the commit tagged as "titan". Thus, this is something related to the latest commits.
The sandbox is attached.
[sandbox.zip](https://github.com/radical-cybertools/radical.pilot/files/945651/sandbox.zip)

**Comment by andre-merzky** [comment]
closing in favor of #1332
