### ISSUE TITLE
documentation Update

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1325]
We need to update the documentation of radical pilot.

**Comment by andre-merzky** [comment]
@georgeha : which I easily can agree to the general observation - can you be more specific on what specifically prompted this ticket?  Thanks.

**Comment by georgeha** [comment]
Hi, the main reason of that ticket is to track the changes of radical's pilot API.

**Comment by andre-merzky** [comment]
If you don't mind, I'll close this as duplicate of #1292 then - but please let me know if I missed anything!
