### ISSUE TITLE
mandatory_args code handling has disappeared

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1327]
As far as I can see, the code to deal with the `mandatory_args` entry has disappeared.
So we either need to re-add that (see https://github.com/radical-cybertools/radical.pilot/commit/6c9409381e3daf6f01cd20b4e86d74883a37081d) or remove all the entries from the config files.

**Comment by andre-merzky** [comment]
Oops - good catch, thanks!

**Comment by ibethune** [comment]
@marksantcroos please review #1329 and then this can be closed following merge.
