### ISSUE TITLE
minimum memory requirement in resource description

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1328]
I have a resource where I need to increase the requested memory to get the pilot even started.

Currently I can specify this in the pilot job description, but it would make sense to encode that resource knowledge directly into the resource description, as it is always needed.

Any reasons not to do this?

**Comment by andre-merzky** [comment]
Agree, it *should* be in the resource description.  The easiest and most flexible way might be to allow for stubs of SAGA level job descriptions to be included in the resource configs.  That is also easy to abuse I guess - but we can address this once this gets out of hand...

How urgent is this for you?

**Comment by marksantcroos** [comment]
Ok. And its not urgent.
