### ISSUE TITLE
RP version on Documentation

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1335]
Shouldn't the installation inform the users that they can install RP on Anaconda python as well?

Also the installation section says that the version of RP is 0.32

**Comment by iparask** [comment]
In addition this [example section](https://radicalpilot.readthedocs.io/en/latest/user_guide/00_getting_started.html#running-the-example) says that the RP version is 0.36.RC1

**Comment by iparask** [comment]
Actually, the versions of RP that are in the documentation:

* 0.32
* 0.36
* 0.36.RC1
* 0.37

**Comment by andre-merzky** [comment]
Ack - but I don't think its worthwhile doing new screenshots / screengrabs for each version, which otherwise look the same.  Also, we at some point (during install) mention that the exact version info depends on, well, the version used.  I think we should leave that...

**Comment by andre-merzky** [comment]
I added infos on anaconda.

**Comment by andre-merzky** [comment]
I think this one can be closed - anaconda is documented now, and I am in favor of keeping the version tags as they are.

**Comment by ibethune** [comment]
Agreed.
