### ISSUE TITLE
Scheduler Selection

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1337]
The example [select scheduler](https://radicalpilot.readthedocs.io/en/latest/user_guide/04_scheduler_selection.html#selecting-a-unit-scheduler) speaks of three schedulers, when the [unit scheduler section](https://radicalpilot.readthedocs.io/en/latest/schedulers.html) discusses two

**Comment by andre-merzky** [comment]
clean up - thanks
