### ISSUE TITLE
Gromacs limited to 1024 CUs on 64 nodes of Titan

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1347]
Split off from #1332 (originally reported by @AA919):

> I was not able to complete 2048 single threaded CUs by using 128 nodes.

**Comment by vivek-bala** [comment]
I don't think this is any issue anymore since I have gone beyond 1K tasks. Is it specific to 1K tasks, 64 nodes or some other configuration? @andre-merzky @mturilli

**Comment by andre-merzky** [comment]
Yes, this was resolved.  Thanks.
