### ISSUE TITLE
Blue Waters - RP must support GPU 

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.pilot#1350]
1. BW do not distinguish (any more) between XK7 and XE nodes (ie GPU vs non-GPU) from a queuing point of view. Thus, all are allowed access to GPU.

2. PVC and John Chodera's team would like to use GPU nodes as part of the cancer project.

3. Likely start date of allocation July 01.

**Comment by ibethune** [comment]
Thanks @shantenujha, a couple of questions:

1) Can you point to some documentation about this change - as far as I can read from the BW documentation, they still have "xe", "xk" and "x" exposed in the queuing system, with the default being "xe".  So while GPU and non-GPU jobs go into the same queue, it is still up to the user (or middleware) to construct a job script which requests the appropriate number of GPU nodes.  Or perhaps I misunderstood your point?

2) Will they be using RP directly, or does this also implicate EnTK?  Who in RADICAL has the best handle on their requirements from a technical standpoint?

**Comment by shantenujha** [comment]
1. Yes, its up to the user to determine / construct a job script with requests the number of GPU nodes. It may have always been like this, but there was apparently a check at job start up for allocation/authentication on GPU. This has now been removed, as I was told.

2. EnTK mostly, but there might be the odd chance that RP directly be used. 

3.  Antons had played around with GPUs on BW.. Andre might recall the status.

**Comment by vivek-bala** [comment]
I think this is pretty old. Closing this our projects on BW are ending/have ended.
