### ISSUE TITLE
Unable to install packages when bootstrapping Bridges

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1353]
I've been writing a config to extend RP to support execution on Bridges. I've been having some network connectivity issues, which prevents the bootstrapper from installing many of the packages. Below is what the error looks like.

It was able to install SAGA, RP, RU, but was unable to install their dependencies. It was also unable to curl `virtualenv1.9`, but it was still able to create a venv because of the python module

 
[bootstrap_1.out.txt](https://github.com/radical-cybertools/radical.pilot/files/1033068/bootstrap_1.out.txt)

```
Collecting msgpack-python
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b9135366a50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/msgpack-python/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b9135366bd0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/msgpack-python/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b9135366d50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/msgpack-python/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b9135366ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/msgpack-python/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b913573c090>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/msgpack-python/
  Could not find a version that satisfies the requirement msgpack-python (from versions: )
```

My `radical-stack`:
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.rp_add_res_cfg

  radical.pilot        : split-71-gfdd36239@feature-bridges_cfg
  radical.utils        : v0.45-45-gce49d06@feature-managed_process
  saga                 : split-18-gc074c761@devel
```

**Comment by mingtaiha** [comment]
@andre-merzky. I saw some activity on ticket #980 for Bridges support. Were you able to set up a config that allows the agent bootstrapper to install the python packages?

**Comment by mingtaiha** [comment]
@itomaldonado, did the run on Bridges finish?

**Comment by andre-merzky** [comment]
Hey Ming, 

I finally got around to look into bridges again, and it seems to work ok now.  Can you give the following combo a spin, please, and let me know how it looks for you?  You may have to remove the `ve_bridges` dir in your sandbox on bridges - not sure (there was a module snafu which may have screwed it up - or not...)

```
RU: devel
RS: fix/bridges
RP: feature/bridges
```

**Comment by mingtaiha** [comment]
Sure thing. I'll keep you posted

**Comment by mingtaiha** [comment]
I got it to work on the RP getting_started example. I am going to test that example but with 1024 CUs to see how that goes. I will then do the rest of the examples for the testing for coming release as a bonus ;)

**Comment by mingtaiha** [comment]
The getting_started example works fine with 1024 CUs (`/bin/date`)

**Comment by mingtaiha** [comment]
All but the MPI example script worked.

**Comment by andre-merzky** [comment]
Great - thanks for checking!
