### ISSUE TITLE
Jetstream Support

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1354]
Many of the XSEDE machines that we know and love are being decommissioned, and we have few machines available to us (and still fewer have acceptable queue time).

EDIT: This would also require development from SAGA as Jetstream is an XSEDE cloud resource and has no batch queue.

**Comment by andre-merzky** [comment]
out of scope for the time being...

**Comment by vivek-bala** [comment]
Leaving this open to address till priority becomes higher

**Comment by mturilli** [comment]
I would move it to v2

**Comment by andre-merzky** [comment]
ack

**Comment by andre-merzky** [comment]
outdated
