### ISSUE TITLE
Question: aprun vs openmpi mode on Titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1359]
I have a question on when aprun and openmpi modes can be used on Titan. 

My scale requirements are as follows: upto 4K tasks, 1 node/task
I have multiple tools that use hdf5-parallel, netcdf-parallel, mpi and I would ideally like to avoid the overhead of compiling them against the openmpi that RP uses. 

Since my tasks are always going to use the entire node, is it advisable to use aprun (since I can skip the compilation overhead)?

**Comment by andre-merzky** [comment]
The number of aprun processes per job is limited on titan, to about 100, so you will not be able to reach 4k tasks with aprun I'm afraid.

**Comment by vivek-bala** [comment]
Ah ok. Maybe I can use it for initial testing for <100 tasks in that case.

**Comment by ibethune** [comment]
Hi @vivek-bala, if the question is answered, please close.

**Comment by vivek-bala** [comment]
Thanks for the clarification.
