### ISSUE TITLE
final pilot transition state not always profiled

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1362]
See radical-cybertools/radical.analytics/issues/37 for details and stack information.  This is a regression, thus adding to the current release milestone.

**Comment by andre-merzky** [comment]
At this point I am willing to take this out of the MS again: while the problem persists, we do have the ability tpo work around this and to use the profiles in analytics, via an additional post-processing step.

**Comment by mturilli** [comment]
The script `pilot_final.sh` at https://github.com/radical-experiments/rp-paper/tree/master/analysis/bin/pilot_final.sh seems to be failing to fix session `rp.session.titan-ext6.aleang9.017304.0002` at https://github.com/radical-experiments/rp-paper/blob/master/analysis/data/use_case_id_5_gromacs/exp1.tar.bz2.

The script passes the session:

```
$ echo rp.session.*/pmgr.0000.prof | xargs -n 1 ../../../bin/pilot_final.sh
rp.session.titan-ext6.aleang9.017303.0014/pmgr.0000.prof: ok
rp.session.titan-ext6.aleang9.017303.0015/pmgr.0000.prof: ok
rp.session.titan-ext6.aleang9.017304.0000/pmgr.0000.prof: ok
rp.session.titan-ext6.aleang9.017304.0001/pmgr.0000.prof: ok
rp.session.titan-ext6.aleang9.017304.0002/pmgr.0000.prof: ok
rp.session.titan-ext6.aleang9.017304.0003/pmgr.0000.prof: ok
rp.session.titan-ext6.aleang9.017304.0005/pmgr.0000.prof: ok
```

but when wrangling with `wranglermp.py -d ../data/use_case_id_5_gromacs/ -t exp -s rp.session.titan-ext6.aleang9.017304.0002` (code at: https://github.com/radical-experiments/rp-paper/blob/master/analysis/bin/wranglermp.py):
```
exp1 -- rp.session.titan-ext6.aleang9.017304.0002 -- Loading session:


exp1 --- rp.session.titan-ext6.aleang9.017304.0002Traceback (most recent call last):
  File "./wranglermp.py", line 770, in <module>
    wrangle_session(sdir, sid)
  File "./wranglermp.py", line 655, in wrangle_session
    sdm, pdm, udm, pilots, units, sts)
  File "./wranglermp.py", line 531, in load_session
    s[duration].append(sra_units.duration(udm[duration]))
  File "/Users/mturilli/Virtualenvs/RADICAL-ANALYTICS/lib/python2.7/site-packages/radical/analytics/session.py", line 536, in duration
    ranges = self.ranges(state, event, time)
  File "/Users/mturilli/Virtualenvs/RADICAL-ANALYTICS/lib/python2.7/site-packages/radical/analytics/session.py", line 493, in ranges
    raise ValueError('no duration defined for given constraints')
ValueError: no duration defined for given constraints
```

This applies also to `exp3/rp.session.titan-ext2.aleang9.017310.0018`

Stack:
```
$ radical-stack 

  python               : 2.7.10
  pythonpath           : 
  virtualenv           : /Users/mturilli/Virtualenvs/RADICAL-ANALYTICS

  radical.analytics    : v0.45.2@devel
  radical.pilot        : split-74-g10acb0d3@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : v0.45.1@master
```

**Comment by andre-merzky** [comment]
This should be addressed for the next release - but I think that the original problem (recording the final state transition) should be fixed at this point, unless the session fails catastrophically, which makes the profiles unusable anyway.

Lets observe this for the next batch of experiments...

**Comment by itomaldonado** [comment]
Want to write to this, as for what I can see this is because the profiles are being truncated.

This is currently a problem on how sub-processes are being closed, thus a fix needs to happen at the `radical.utils` layer.

This issue should be fixed by radical-cybertools/radical.utils#120

**Comment by andre-merzky** [comment]
This was a somewhat different issue: the pilot final state was supposedly profiled in agent_0's `finalize_parent()`, but agent_0 got killed too quickly by the bootstrapper so that the  finalize did not manage to get through.  We now wait more gracefully in the bootstrapper, so that does not happen anymore.
This might have additionally been impacted by the flushing problem of course.

**Comment by itomaldonado** [comment]
Good to know, I think I should have been a bit more precise in saying that this problem *might* have *also* been related.

**Comment by andre-merzky** [comment]
No worries!  I actually appreciate that you look through the tickets and look for those which might be related! :)

**Comment by vivek-bala** [comment]
Not looked into the pilot final state much. Was this issue resolved? @andre-merzky

**Comment by andre-merzky** [comment]
Yes, this is resolved: there are some fallbacks in the pilot to record the correct state, and the pilot manager jumps in when those don't apply.
