### ISSUE TITLE
resource ve is not updated on new dependencies 

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1363]
rp agent now depends on msgpack - but an existing `ve_<resource>` is accepted as functional if it loads, and new dependencies are not installed.  The bootstrapper will then fail when testing for the dependency.   This is a regression unfortunately.  Well, not really maybe, it behaved this way for quite some time - but the release will trigger this problem all over the place now.

**Comment by marksantcroos** [comment]
Right, this is not new. At some point when we had major changes we instructed people to wipe the ve in the release notes.
