### ISSUE TITLE
Question about the performance variation of the executor

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1375]
(Sorry if the question is vague. Please let me know if I can make myself more clear.)

I have running many instances (CUs) of the same Synapse emulation on different machines (SuperMIC, Bridges, Comet) to measure the Tx. I have found that on some machines (especially SuperMIC), the fluctuations in Tx can vary a lot (~60%), more than what has been measured in the literature (~30%).

I was wondering if there was any data which shows how the agent performs when executing a task (e.g. overheads incurred, how much the Tx of a CU fluctuates?)

EDIT: I am using the following `radical-stack` when running these Synapse emulations
```
/exp/model_confirm$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.pilot        : 0.46-split-84-g1219765a@devel
  radical.utils        : 0.46-v0.45-49-g38f6ee3@devel
  saga                 : 0.46-split-19-g11be22af@devel
```

**Comment by andre-merzky** [comment]
Hi Ming - the question is clear, and is also interesting :)  A couple of comments / thoughts:

One needs to make sure to separate different variances: `synapse`, `system`, and `RP`.   Out of those three, system is hardest to separate, but you should be able to measure the  `synapse + system` and `RP + system` just fine: the first by running a fixed synapse workload on the system w/o RP, the second by running an empty CU (`/bin/true`) with RP.

Also, the overhead or RP is recorded with profiler events.  For one approach on how to analyse those profiles, have a look at [this analytics example](https://github.com/radical-cybertools/radical.analytics/blob/feature/events/examples/06_events.py#L57).  Note though that our [event model](https://github.com/radical-cybertools/radical.pilot/blob/feature/events/docs/source/events.md) is only  fully implemented in the `feature/events` branch - but that will be the target of the next release.

Is that helpful?
