### ISSUE TITLE
RP fails on Titan 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1376]
I ran a test example using 1 pilot, 16 cores on Titan-ortelib (RP version 0.46)
I get the following errors: 

```================================================================================
 Getting Started (RP version 0.46)                                              
================================================================================

new session: [rp.session.titan-ext7.jdakka.017339.0001]                        \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]Traceback (most recent call last):
  File "pilot.py", line 38, in <module>
    session = rp.Session()
  File "/lustre/atlas2/csc230/proj-shared/mskcc/rp_experiments/venv/lib/python2.7/site-packages/radical/pilot/session.py", line 257, in __init__
    self._components = ruc.start_components(self._cfg, self, self._log)
  File "/lustre/atlas2/csc230/proj-shared/mskcc/rp_experiments/venv/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 252, in start_components
    comp.start()
  File "/lustre/atlas2/csc230/proj-shared/mskcc/rp_experiments/venv/lib/python2.7/site-packages/radical/utils/process.py", line 462, in start
    timeout))
RuntimeError: unexpected child message (alive) [5.0]
```

And from root message: 

```
PBS Job Id: 3458802
Job Name:   pilot.0000
Exec host:  2342/0-15
An error has occurred processing your job, see below.
request to copy stageout files failed on node '2342' for job 3458802

Unable to copy file /autofs/nccs-svm1_home1/jdakka/3458802.OU to /lustre/atlas/scratch/jdakka/csc230/radical.pilot.sandbox/rp.session.titan-ext4.jdakka.017339.0000/pilot.0000/bootstrap_1.out, error 1
*** error from copy
/bin/cp: cannot stat `/autofs/nccs-svm1_home1/jdakka/3458802.OU': No such file or directory
*** end error output

Unlink of stage out file /autofs/nccs-svm1_home1/jdakka/3458802.ER failed
```

**Comment by AA919** [comment]
I have the same problem. I tried to run experiments but the folders of the units are not copied on Lustre. I also tried to delete pilot's virtualenv but RP is not able to create a new one. Yesterday Titan had a downtime, probably they updated the system and the update is bothering RP.

**Comment by vivek-bala** [comment]
This might not be the root cause of the problem. But I think you need a minimum of 2 nodes (=32 cores on Titan) if you are using orterun/ortelib.

**Comment by AA919** [comment]
Yes but I asked for the extra node and the problem is still there.

**Comment by jdakka** [comment]
Ran Ortelib with 32 cores...same stalling issue as @AA919

**Comment by andre-merzky** [comment]
Yeah, RP fails for me, too, earlier even - we seem to hit a Python/Pip compatibility problem again :/

**Comment by andre-merzky** [comment]
titan FS behaves very inconsistent right now, and I can't get debug runs started.  Sorry, but this has to wait a little longer :/

**Comment by andre-merzky** [comment]
Sooo, the virtualenv version we use in the pilot bootstrapper does not cooperate with Titan's python setup anymore.  More specifically, the specific combination of python, virtenv and easy_install packaged in virtenv and used to install pip fails, due to a mismatch in setuptools.  I don't think we can fix this in our stack, and I don't think we can ask Titan support, as we use our own virtenv version, and they'll not going to support that.

So, we'll have to touch the bootstrapper and fall back to the native titan virtenv/pip combo.  Now, we did not choose our own virtenv version for no reason, and we may have to check what other problems will pop up again - or maybe not. 

Either way, I guess I am just saying: stay tuned, this will take a while... :/

**Comment by andre-merzky** [comment]
#1378 fixes a part of the problem.  For this to kick in, you will have to remove the pilot VE on titan.  Alas, more work is needed - the system upgrade also screwed with pyzmq deployment, which is now unusable, so this ticket remains open.

**Comment by andre-merzky** [comment]
https://github.com/zeromq/pyzmq/issues/946

This seems unresolved on pyzmq wheel level.  I guess we will have to install/compile/maintain zmq to resolve this.

**Comment by marksantcroos** [comment]
You are chasing a ghost in your test probably ... try with `export LD_PRELOAD=/lib64/librt.so.1`.

**Comment by andre-merzky** [comment]
Nah, that is set....

...

**Comment by marksantcroos** [comment]
Given that you reply by mail I'm assuming you didn't try? :)

**Comment by andre-merzky** [comment]
I am on my phone - but I explicitly checked for that setting already....

...

**Comment by marksantcroos** [comment]
I can reproduce your error if I unset LD_PRELOAD.

**Comment by andre-merzky** [comment]
```
merzky1@titan-ext1:~/sandbox $ env | grep PREL
LD_PRELOAD=/lib64/librt.so.1

merzky1@titan-ext1:~/sandbox $ module list 2>&1 | grep python
 26) python/2.7.9
 27) python_setuptools/21.0
 28) python_pip/8.1.2
 29) python_virtualenv/12.0.7

merzky1@titan-ext1:~/sandbox $ virtualenv ve_test 2>&1 > /dev/null
merzky1@titan-ext1:~/sandbox $ source ve_test/bin/activate

(ve_test)merzky1@titan-ext1:~/sandbox $ which python pip
/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/bin/python
/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/bin/pip

(ve_test)merzky1@titan-ext1:~/sandbox $ pip install pyzmq                                                                                                                                                         
Collecting pyzmq
  Using cached pyzmq-16.0.2.tar.gz
Installing collected packages: pyzmq
  Running setup.py install for pyzmq ... done
Successfully installed pyzmq-16.0.2
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(ve_test)merzky1@titan-ext1:~/sandbox $ python -c 'import zmq'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve_test/lib/python2.7/site-packages/zmq/backend/cython/error.so: undefined symbol: zmq_strerror

(ve_test)merzky1@titan-ext1:~/sandbox $ env | grep PREL
LD_PRELOAD=/lib64/librt.so.1
```

Am I reading your comment correctly that you still can run stuff on titan?  Or, in other words, were you unable to reproduce *without* LD_PRELOAD?

**Comment by andre-merzky** [comment]
It turned out that some update in either pip or pyzmq lead to a different env being used when installing pip.  I decided not to track this down any further, but instead created a static VE on titan which uses a custom pyzmq installation and is functional for our purposes.  The respective config changes are updated in the `fix/titan_pip` branch - I would appreciate if somebody could  confirm this works for not just me (permissions, env etc), and then can merge this to devel.

**Comment by vivek-bala** [comment]
I didn't check if I can reproduce the initial issue but I tried the fix/titan_pip branch and my scripts run and terminate successfully currently. Note that this only tests the aprun mode.

**Comment by andre-merzky** [comment]
Thanks for the feedback, Vivek.  I'll be merging it now - devel for sure is broken on titan, so we can't make it worse ;)

**Comment by AA919** [comment]
That's the spirit :)
