### ISSUE TITLE
Feature request: Agent: monitoring I/O and CPU of working node

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1385]
On grid systems, PanDA Pilot implements a monitoring probe that collect statistics on I/O and CPU of the node on which the payload is executed. We should study their solution and see what it would take to implement something similar in our RP Agent.

**Comment by vivek-bala** [comment]
I think this FR has come up in multiple contexts (e.g. memory aware scheduler). Leaving this open with low priority.

**Comment by mturilli** [comment]
Probably best to move it to v2

**Comment by andre-merzky** [comment]
Reopen when we have an explicit use case
