### ISSUE TITLE
Update Child Error when running example 00_getting_started.py

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1390]
I get the following error when running `00_getting_started.py`. I only got this error the first time I ran the command and have not encountered this error again.

```
(ve.rc1)[mingtha@workflow examples]$ python 00_getting_started.py xsede.comet
new session: [rp.session.workflow.iu.xsede.org.mingtha.017371.0000]            \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]Traceback (most recent call last):
  File "00_getting_started.py", line 36, in <module>
    session = rp.Session()
  File "/home/mingtha/ve.rc1/lib/python2.7/site-packages/radical/pilot/session.py", line 272, in __init__
    self._components = ruc.start_components(self._cfg, self, self._log)
  File "/home/mingtha/ve.rc1/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 252, in start_components
    comp.start()
  File "/home/mingtha/ve.rc1/lib/python2.7/site-packages/radical/utils/process.py", line 479, in start
    (self._ru_childname, msg))
RuntimeError: child update.0.child failed to come up [s]
```

My `radical-stack`:
```
  python               : 2.7.5
  pythonpath           : /usr/lib64/python2.7/site-packages/openmpi
  virtualenv           : /home/mingtha/ve.rc1

  radical.analytics    : v0.45.2-2-g476254a@devel
  radical.pilot        : 0.46-v0.46.RC1@detached-v0.46.RC1
  radical.utils        : 0.46-v0.46.RC1@detached-v0.46.RC1
  saga                 : 0.46-v0.46.RC1@detached-v0.46.RC1
```

**Comment by andre-merzky** [comment]
Thanks - I'll check if this should be an exception in the first place (instead of a warning in the logs).

**Comment by andre-merzky** [comment]
Ming, do you happen to have the client side logs for this failed run available?  Thanks, Andre

**Comment by mingtaiha** [comment]
There are no client side logs. This problem seems to appear when I run two RP sessions one after the other. It might have to do with process teardowns?

**Comment by andre-merzky** [comment]
Two sessions in the same process, or in different processes?  But more important actually: why are there no client side log files?  Do you have `RADICAL_PILOT_VERBOSE=DEBUG` set?

**Comment by mingtaiha** [comment]
No, I did not have `RADICAL_PILOT_VERBOSE=DEBUG` set

**Comment by andre-merzky** [comment]
Got it.  So, please do set it, and also `RADICAL_PILOT_AGENT_VERBOSE=DEBUG`, remove the sandbox, and give it another try.  Thanks!

**Comment by mingtaiha** [comment]
This is awkward, I'm having trouble reproducing this error now :(

**Comment by andre-merzky** [comment]
Good for me :-D

**Comment by andre-merzky** [comment]
Ming, what are we going to do about this one?  Did it resurface?

**Comment by andre-merzky** [comment]
ping

**Comment by mingtaiha** [comment]
DAE anyone see this problem? I have not encountered this since. We can close this for now (????). What do you think @andre-merzky

**Comment by andre-merzky** [comment]
I have not seen process spawning problems for quote some time now - happy to close and to re-open if it reappears.

Thanks for the follow-up!

**Comment by mingtaiha** [comment]
Fine by me. Closing
