### ISSUE TITLE
Better documentation of format of data returned by get_session_profile() and get_session_description()

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1391]
Better documentation of format of data that is returned by get_session_profile() and get_session_description(). This will help in integration of analytics with utils in EnTK.

**Comment by vivek-bala** [comment]
Specifically, what needs to be the value profile, accuracy, hostmap and description in the following lines: https://github.com/radical-cybertools/radical.analytics/blob/devel/src/radical/analytics/session.py#L39-L41.

Creating utilities in EnTK to return data in the same format should let us use analytics directly for profiles generated by EnTK as well.

Also to note there is no JSON file created in EnTK. Some comments about how to handle that will be helpful.

**Comment by vivek-bala** [comment]
I don't think we have any documentation regarding the two. For EnTK, I had to look at RP output, manually parse and create the same data structure. I don't think there is anyway around the manual step but documentation would be helpful.

But not sure if this applies to any other tool.

**Comment by andre-merzky** [comment]
internal data only.
