### ISSUE TITLE
Examples config file is not updated

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1393]
There is no ```xsede.supermic``` . It should be ```xsede.supermic_ssh```. I am not sure if the rest of the labels are correct

**Comment by andre-merzky** [comment]
Hmm, an alias for this should exist -- see [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_aliases.json#L32).  Can you please post the debug log from the client side?  Thanks!

**Comment by andre-merzky** [comment]
I misread the report - you mean the *example* config, where the *resource* config aliases don't apply!  Gotcha, thanks.

**Comment by iparask** [comment]
Yes! The example config! You are welcome!

**Comment by andre-merzky** [comment]
Fixed - thanks
