### ISSUE TITLE
Hadoop link is outdated

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1395]
The link that is used to download Hadoop is outdated. It needs to be updated.

Giannis

**Comment by iparask** [comment]
Additional bugs:

1.  Dropbox changed the public folders to private and YARN app link needs to be updated.
2.  CU states have changed and they need to be corrected. 
3. Deprecated code should be removed

Unless all bugs are removed this ticket will not close

**Comment by iparask** [comment]
New error:

```
2017-07-25 16:45:45,377: agent.executing.0   : MainProcess                     : MainThread     : WARNING : recv timed out
2017-07-25 16:45:45,378: agent.executing.0   : MainProcess                     : MainThread     : ERROR   : initialization failed (child agent.executing.0.child failed to come up [s])
Traceback (most recent call last):
  File "/work/03170/tg824689/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017372.0009/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 479, in start
    (self._ru_childname, msg))
RuntimeError: child agent.executing.0.child failed to come up [s]
2017-07-25 16:45:45,494: agent.executing.0   : MainProcess                     : MainThread     : INFO    : stop agent.executing.0 (77075 : 78404 : MainThread) [radical.utils.process.ABDS.start]
2017-07-25 16:45:45,494: agent.executing.0   : MainProcess                     : MainThread     : INFO    : parent stops child
```
Andre, any ideas? I am not sure I know how to fix it

**Comment by andre-merzky** [comment]
you'll have to check `agent.executing.0.child.log` to see why that proc did not bootstrap correctly.  Let me know if that doesn't help!

**Comment by iparask** [comment]
There are no errors in that log file. ```agent_0.log``` has a message : : ERROR   : bridge / component startup incomplete: from the mainthread. 

In addition, the last log, that are based for YARN, is the [one](https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1395/src/radical/pilot/agent/lm/yarn.py#L315) before the YARN app starts to download. The download is finishing, but I do not see anywhere the message [after](https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1395/src/radical/pilot/agent/lm/yarn.py#L319) it.

**Comment by andre-merzky** [comment]
That likely means that the `wget` command hangs.  You won't see an error in that case indeed - the parent will just assume that the component did not come up properly, and thus complain and terminate.

I assume you will have to redirect  stdout/stderr of the wget to trace this down.  If that indeed takes too long due to the data size, we have to either increase the timeouts, or need to move the wget initialization elsewhere (e.g. into the first invokation of `work()`, which is not timed out).

**Comment by iparask** [comment]
wget needs about 8 seconds on Stampede to finish. As it is understandable, this value is not guaranteed due to resource connectivity and Dropbox availability.

I would suggest to move it in the LRMS config hook, along with the hadoop download. This way the config method will only discover YARN's path and will be okay. Is that okay with you?

**Comment by iparask** [comment]
I want to keep the ticket open for a while longer.  Can we also keep the branch?

**Comment by andre-merzky** [comment]
Sure, absolutely!  I habitually deleted the branch after merging the PR - but it is restored now.  Please consider it owned by you now.

Cheers, Andre.

**Comment by iparask** [comment]
Thank you very much Andre!

**Comment by vivek-bala** [comment]
@iparask do you still want to keep this ticket open?

**Comment by andre-merzky** [comment]
outdated
