### ISSUE TITLE
Spark bug fixes

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1399]
- update spark variable from  SPARK_MASTER_IP to SPARK_MASTER_HOST based on the new version
- remove spark tar file.

**Comment by andre-merzky** [comment]
@georgeha, are there any actions remaining here, or was this addressed by your pull request?

**Comment by iparask** [comment]
@andre-merzky , the first bullet is done, I do not think the second is though. There is no change at the config hook.
