### ISSUE TITLE
MPI units fail on wrangler

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1401]
MPI units fail on wrangler:

unit.* output
```
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
[c252-135.wrangler.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 1, pid: 31238) exited with status 1
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
[c252-135.wrangler.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 31236) exited with status 1
```

radical-stack:
```
 python               : 2.7.6
  pythonpath           : 
  virtualenv           : /home/georgeha/testing_dir/ve.rc1

  radical.pilot        : 0.46-v0.46.RC1@fix-issue_1396
  radical.utils        : 0.46-v0.45-49-g38f6ee3@devel
  saga                 : 0.46-split-19-g11be22a@devel
```

**Comment by andre-merzky** [comment]
Yeah, its still true that the MPI test will fail on most resources unless additional configurations or installations are done.  Matteo and I have the standing todo item to come up with a more sane and portable MPI test - but we are not there, yet...

I'll keep this ticket open for that purpose (I don't think we have a ticket for that topic yet).

**Comment by andre-merzky** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/feature/gpu/examples/09_mpi_units.sh now contains a generic MPI / OpenMP test which does not depend on `mpi4py` anymore.  I doubt this will  make it into the `0.46` release though, as it is somewhat tied to the `feature/gpu` branch.

**Comment by andre-merzky** [comment]
I am closing this one as a 'known issue' - we'll address the problem in the context of the gpu branch, as mentioned above.
