### ISSUE TITLE
zeromq issues on Comet

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1403]
00_getting_started.py returns error: 

```
(ve.rc1) [jdakka@comet-ln2 examples]$ python 00_getting_started.py 
new session: [rp.session.comet-ln2.sdsc.edu.jdakka.017377.0002]                \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]Resource temporarily unavailable (bundled/zeromq/src/thread.cpp:106)
Traceback (most recent call last):
  File "00_getting_started.py", line 36, in <module>
    session = rp.Session()
  File "/home/jdakka/.local/lib/python2.7/site-packages/ve.rc1/lib/python2.7/site-packages/radical/pilot/session.py", line 272, in __init__
    self._components = ruc.start_components(self._cfg, self, self._log)
  File "/home/jdakka/.local/lib/python2.7/site-packages/ve.rc1/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 252, in start_components
    comp.start()
  File "/home/jdakka/.local/lib/python2.7/site-packages/ve.rc1/lib/python2.7/site-packages/radical/utils/process.py", line 479, in start
    (self._ru_childname, msg))
RuntimeError: child update.0.child failed to come up [s]
```

[comet_testing.zip](https://github.com/radical-cybertools/radical.pilot/files/1186056/comet_testing.zip)

**Comment by andre-merzky** [comment]
Jumana, are you running on MacOS by any chance?  If so, please do try to increase ulimits for open files (`ulimit -n 512` I believe) - this looks like a duplication of #1122.

**Comment by jdakka** [comment]
@andre-merzky not running on Mac, directly on Comet

**Comment by andre-merzky** [comment]
Thanks Jumana - let me try to reproduce this on comet.

**Comment by vivek-bala** [comment]
Hey @jdakka , are you running from the login node? If so, just wanted to let you know that the general recommendation is not to use the login node as the client. Since the RP client can possibly get heavy which the sys admins might not like. You don't want to become a part of the people-who-have-been-banned-on-xsede-machines group :). Ignore this if you have a specific reason for running on the login node.

**Comment by jdakka** [comment]
fixed...silly mistake on my end

**Comment by andre-merzky** [comment]
Now I am curious!  What was it?
