### ISSUE TITLE
09_mpi_units.py fails on Comet

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1405]
The problem seems like we couldn't import the right MPI modules. There were no other errors in the log,
only the following in the `STDERR` files in the folders of each unit on resource (specifically in the session folder in the sandbox)
```
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
    from mpi4py import MPI
ImportError: No module named mpi4py
```

**Comment by andre-merzky** [comment]
We will have a better MPI test for the next release - for this release, please to ignore that one...

Thanks, Andre.
