### ISSUE TITLE
fold example config into resource config

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1410]
by now, we have 42 config entries, so one for basically each resource config.  We should add example and test configurations directly to the resource config.

**Comment by vivek-bala** [comment]
Not sure what changes are being discussed/planned here. Is this implemented? Can you add some more info regarding the feature please?

**Comment by andre-merzky** [comment]
Each resource config should have a subsection containing the settings from `examples/config.json`.
