### ISSUE TITLE
Examples 7 and 8 give the following message: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1413]
```
Traceback (most recent call last):
  File "07_shared_unit_data.py", line 125, in <module>
    unit.exit_code, unit.stdout.strip()[:35]))
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by andre-merzky** [comment]
Can you please attach the logfiles (from both the client side and the target host)?  Thanks!

**Comment by SrinivasMushnoori** [comment]
/md1/scm177/RADICALSTACK0.46RP2/src/rp/examples/Logfiles.tar

I do not see any host side log files, strangely. Unsure if I'm looking in the wrong place.

**Comment by SrinivasMushnoori** [comment]
Client side:
[Logfiles.zip](https://github.com/radical-cybertools/radical.pilot/files/1219242/Logfiles.zip)


There appear to be no logs on the host side.

**Comment by andre-merzky** [comment]
Thanks Srinivas - but alas the archive is missing the remote logfiles.  Apparently the pilot failed, so we have to dig there to see why that happened...

**Comment by vivek-bala** [comment]
@SrinivasMushnoori I am closing this issue. It seems pretty old and probably not being faced anymore. Please do reopen if that is not the case.

**Comment by andre-merzky** [comment]
This is still broken: examples behave badly when the pilot fails or when units fail, in the sense that they raise errors which have nothing to do with the original problem.

**Comment by andre-merzky** [comment]
outdated
