### ISSUE TITLE
cleanup needs checking

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1414]
#1407 mentioned that `cleanup` does not work as expected.  I assume the cleanup flags require some consolidation in general tbh.

**Comment by vivek-bala** [comment]
@andre-merzky has there been work on the cleanup? I don't use it much so not sure.

**Comment by andre-merzky** [comment]
No, this is still broken.

**Comment by andre-merzky** [comment]
outdated
