### ISSUE TITLE
Radical Pilot fails

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1417]
I am using the devel stack:
```
radical-stack 
  python               : 2.7.13
  pythonpath           : 
  virtualenv           : /home/johnrobot/myenv
  radical.pilot        : 0.46.1
  radical.utils        : 0.46.2
  saga                 : 0.46.1
```
Here's the tail of bootstrap_1.out:
```
purge install source at radical.pilot-0.47-v0.46-3-g0f79ca8-devel/
verify python viability: /home/johnrobot/myenv/bin/python ... ok
verify module viability: saga            ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named saga
 failed
python installation cannot load module saga - abort
```
Pilot folder attached.
[rp.session.johnrobot-HP-ENVY-TS-17-Notebook-PC.johnrobot.017406.0006.zip](https://github.com/radical-cybertools/radical.pilot/files/1255014/rp.session.johnrobot-HP-ENVY-TS-17-Notebook-PC.johnrobot.017406.0006.zip)

**Comment by andre-merzky** [comment]
Hi, 

the only thing suspicious is the following:  the pilot uses Python from within a user virtualenv for bootstrapping:

```
VIRTENV : /home/johnrobot/radical.pilot.sandbox/ve.local.localhost.0.47
VIRTENV : /home/johnrobot/radical.pilot.sandbox/ve.local.localhost.0.47 (normalized)
PYTHON: /home/johnrobot/myenv/bin/python
PIP   : /home/johnrobot/myenv/bin/pip
```

My assumption would be that this virtualenv is sourced in the user's bashrc (or similar)?  What then basically happens is that we create a virtualenv from within a virtualenv, but then use the pip from the *original* virtualenv to install our modules.  That install seems to work ok, but the modules are not tu be found once the pilot wants to start up.  

Would you mind removing that user virtualenv from the picture, and try again?  Please to remove  /home/johnrobot/radical.pilot.sandbox/ve.local.localhost.0.47 before doing so, to start from a clean slate.

Thanks, Andre.

**Comment by jrossyra** [comment]
Everything works ok from here, Thanks!

**Comment by andre-merzky** [comment]
Great :)
