### ISSUE TITLE
Pymongo 3 compatibility

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1418]
Would like to explore the compatibility of `radical.pilot` and pymongo 3. 

There are several updates to the API from pymongo 2 to pymongo 3, mostly are backwards compatible, but there are several deprecations and some actually generate errors.

We encountered an error similar to what is shown here: https://github.com/django-nonrel/mongodb-engine/issues/207

**Comment by mingtaiha** [comment]
lmk when you are going through it? I would like to learn more about how RP and Mongo interacts if that's kk with you

**Comment by itomaldonado** [comment]
I wanted to add this, documentation directly from pymongo:

https://api.mongodb.com/python/current/migrate-to-pymongo3.html

**Comment by andre-merzky** [comment]
This is merged in devel now and about to be released.
