### ISSUE TITLE
Function to provide list of supported resource names

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1419]
Is there a function to expose the supported resource names? Such as `rp.supported_resources()` --> ['ornl.titan', 'uiuc.bluewaters', etc]

**Comment by andre-merzky** [comment]
No, but that would be easy to add.  That would likely be a call on the Session object, as the information is readily available there:

```
s = rp.Session()
print s.supported_resources()
```

or whatever the API.  I'll take this as a feature request.

**Comment by jrossyra** [comment]
Ok super! for now, I have something like 
```
resource_names = set([k.split('_')[0] for k in s._resource_aliases.keys()])
```
I noticed that `_resource_configs` seems to be a superset of `resource_aliases` probably due to the purpose of aliasing. Is the configs going to give the most comprehensive list of resource names of all the available attributes?

**Comment by andre-merzky** [comment]
The aliases are indeed only a subset of valid resource labels - it seems that you guessed that those are convenient or backward-compatible names for actual resource config entries. 

Your snippet will give you a list of resources indeed - but you will need to use a complete label in a pilot description, including the `_xyz` part, at least at this point in time.  But I guess you figured that out already :)

**Comment by andre-merzky** [comment]
This is implemented as `session.list_resources()` now, in PR #1422.  I am not sure in what release that will go though.  Let me know if the method name is acceptable for you.  Also, that call will not return aliases - those are mostly used for deprecated names etc.  Is that ok?

**Comment by jrossyra** [comment]
It is. I just want to check that a user-typed resource name has some corresponding configuration defined in rp. I'll keep my eye out for when its available. Thanks again!

**Comment by vivek-bala** [comment]
I think PR 1422 has been since merged and released. Closing.
