### ISSUE TITLE
ve-in-ve  breaks agent bootstrapping

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1420]
See #1417.  I am not sure there is an easy fix - but it needs documenting, possibly as an FAQ or troubleshooting entry.

**Comment by vivek-bala** [comment]
Ve-ception? :) I think we have general instructions on creating VEs, I don't think we should be adding documentation in RTD for this issue. @andre-merzky what do you think?

**Comment by andre-merzky** [comment]
.Agree,
