### ISSUE TITLE
CUs don't reach DONE state with RP devel

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1423]
I tried the 01_unit_details.py example using RP devel. See stack below:

```
$ radical-stack 

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/ves/admd

  radical.pilot        : 0.47-v0.46-3-g0f79ca8@devel
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-2-ga48f5f0@devel

```

None of the units reach RP.DONE and the last stage that they reach is UMGR_STAGING_OUTPUT_PENDING.

**Comment by andre-merzky** [comment]
This works for me (tm).  Could you please send the client and agent logfiles?

**Comment by vivek-bala** [comment]
I don't get this error with the default pymongo that RP installs. I can reproduce it with the latest pymongo (3.5.1). Pymongo 3.5.1 is required by one of collaborators for their software package and hence the requirement. @itomaldonado Do you agree with the 3.5.1 requirement?

Attached client and agent logs.

[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017407.0015.zip](https://github.com/radical-cybertools/radical.pilot/files/1260307/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017407.0015.zip)

[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017407.0015.zip](https://github.com/radical-cybertools/radical.pilot/files/1260309/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017407.0015.zip)

**Comment by andre-merzky** [comment]
Ah.  Then please see #1418.  Manuel, do you have any input?  Thanks!

**Comment by itomaldonado** [comment]
Hey, I believe that their requirement is at least 3.0+ because they use (as I do in my code) the function `collection_obj.insert_one(some_obj)`. That family of methods (`.*_one()`) was introduces with pymongo3.0+ so it is definitely a requirement for them.

As far as @1418 goes, I think that this may be related to it, we found some weird issues with RP and pymongo3.5.1 (which could be generalized to upgrading pymongo from 2.8 to 3.0+).

**Comment by mingtaiha** [comment]
I also encounter this for my experiments.

**Comment by andre-merzky** [comment]
Well, we do not officially support pymongo3.0 yet, and I am hesitant to add that to the current (analytics-focused) release schedule, unless this is stopping work for some users (ie. you), and you don't have the option to use a different MongoDB in that setup?

**Comment by mingtaiha** [comment]
Sorry for the mixup. I am running pymongo2.8.

**Comment by andre-merzky** [comment]
Oh, so its a different issue then?  Please do open a new    ticket, please, and attach the logs, will you?  Thanks, Ming!

**Comment by vivek-bala** [comment]
I think this issue was related to the pymongo versions. This was resolved.
