### ISSUE TITLE
how to disable the cursor while waiting for units

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.pilot#1427]
When running UnitManager.wait_units() is shows a cursor, which some people don't like. Is there an option to remove this cursor (remove only this cursor, nothing else)?

**Comment by andre-merzky** [comment]
Unfortunately, the cursor (I assume you mean the animation thing) is part of the reporter output - you can only enable/disable the reporter output altogether, not that animation specifically.  How much of an issue is this?

**Comment by euhruska** [comment]
Disabling the report might be a partial solution, but I have outcommented the LogReporter (in examples.07_shared_unit_data.py) and that doesn't remove the animation thing. How would I disable the any output to stdout? In jupyter notebook instead of the animation it fills pages with symbols, so it's annoying.

**Comment by vivek-bala** [comment]
I don't think we have the rotating line which caused this issue anymore. @andre-merzky let me know if I am incorrect.

**Comment by andre-merzky** [comment]
We still have this, and it still cannot be disabled individually.

**Comment by vivek-bala** [comment]
Should I leave this ticket open this for an FR? @iparask do you have any suggestions on running RP via notebooks?

**Comment by andre-merzky** [comment]
implemented

**Comment by euhruska** [comment]
Thanks
