### ISSUE TITLE
Question about loading modules when agent uses ORTE

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1434]
I have been trying to run a Gromacs simulation on Comet where the agent uses ORTE. However, I have not been able to load the Gromacs modules that I need. Does using ORTE require that I load the modules differently?

**Comment by andre-merzky** [comment]
To run MPI applications under ORTE (both `comet_orte` and `comet_ortelib`) you will need to use an application binary which is compiled against the specific ORTE version we use to start the application -- otherwise the MPI bootstrapping will fail.  My assumption would be that this is your problem?  If that does not match the error you see, can you please send more specifics on the actual error?

Thanks!

**Comment by mingtaiha** [comment]
I checked the logs myself, but there doesn't seem to be any errors aside from the ones caused by a hard cancel or the like. How does one compile Gromacs with ORTE?

**Comment by andre-merzky** [comment]
If there are no errors, why do you think it failed? :D  I would guess the unit goes to `FAILED`?  Please check the unit stdout / stderr in this case.

@vivek-bala  may have some advice on compiling gromacs against ORTE.  You should find the ORTE module information [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L621).

Let me know how it goes!

**Comment by mingtaiha** [comment]
It failed because I tried loading the Gromacs modules, but when the unit tries to run the command that I specified, it fails does not recognize the command. Specifically, I try to run `gmx_mpi` but I get the error that the command is not recognized. I know for sure that if the Gromacs module is loaded this command will run since I have executed this command with using RP and ORTE

**Comment by andre-merzky** [comment]
Ah, I see - I was on the wrong track here, should have been more careful.  ORTE and ORTELIB are not supporting pre_exec - are you loading the module there?  Please have a look at the discussion in #1190, is that the same?

**Comment by mingtaiha** [comment]
This seems to be my problem. Is `/bin/sh` still a viable workaround

**Comment by andre-merzky** [comment]
I am not sure how much the `sh` based startup would interfere with the MPI bootstrapper... - worth a try?

**Comment by mingtaiha** [comment]
Rather than using the `pre_exec`, I put the `module load` and the Gromacs commands into one script. This seemed to solve the problem. However, I saw the error seen in #1085. I tried unloading the module `mvapich_ib` as recommended but I get the same error.

**Comment by SrinivasMushnoori** [comment]
@mingtaiha yes I still see this problem. 
Mind sharing the workaround?
I semi-solved this problem by recompiling GROMACS using OpenMPI. But that makes GROMACS run incorrectly. For some reason, it appears to instantiate multiple time inside the same CU. 

I've taken up #1085 and will update that tonight.

**Comment by mingtaiha** [comment]
I made a wrapper script with two commands. I put the `module load` command before the Gromacs command in a wrapper script. Then I have the CUs run the wrapper script.

**Comment by SrinivasMushnoori** [comment]
@mingtaiha interesting. I'm assuming the two commands you put into the wrapper script are:

gmx_mpi grompp .......

gmx_mpi mdrun ........

Correct?
Would you mind copy/pasting the CU description that you used to submit this?
Thanks a bunch.

**Comment by vivek-bala** [comment]
Closing as we no longer support ORTE and this ticket is pretty old.
