### ISSUE TITLE
Jenkins cleanup

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1436]
Backup and cleanup old Jenkins jobs.

**Comment by vivek-bala** [comment]
@andre-merzky @mturilli Any idea if the backup was created? Can you comment where the backup is stored?

**Comment by andre-merzky** [comment]
No idea, sorry...

**Comment by vivek-bala** [comment]
Any suggestion on how we can proceed with jenkins related issues?

**Comment by mturilli** [comment]
@vivek-bala in general, I think the approach to jenkins and integration testing is well understood. To summarize: 
1. every time we do not test RP on a supported machine, one of our users does it for us. 
2. this creates endless problems for the users that has to go through one or more debugging session with tens of iterative reruns, often at scale and often under the pressure of some deadline
3. this throws us into an continuous state of emergency, made particularly bad by chronic understaffing and overcommitment of the existing staff/students. 
4. most often, the user stop using RP if s(he) can and we drop the issue altogether going back to the next commitment.
5. based on this, we should all conclude that spending time and effort on testing is an absolute priority. 

Unfortunately, the actual approach stops at point 4: Jenkins-related tickets are at least 1.5 years old and clearly deprioritized to the point that we do not even remember about them anymore.

For the specific topic of this tickets: the backup, if it exists, should be on one.radical.

**Comment by itomaldonado** [comment]
@vivek-bala this issue was nevwr done (by me) so no jobs were ever deleted, thus backups weren’t necessary.

**Comment by itomaldonado** [comment]
I started cleaning jobs I created (when I left some are still around) but I never deletd jobs created by other people. Because we were not at a point (back then) where Jenkins was used properly so there was no point in cleaning/removing old jobs.

**Comment by andre-merzky** [comment]
Thanks @itomaldonado :-D  And greetings, to wherever you are right now!

**Comment by andre-merzky** [comment]
outdated
