### ISSUE TITLE
Create test for master that runs all the examples locally

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1438]

**Comment by mturilli** [comment]
Only if #1439 is voted down.

**Comment by vivek-bala** [comment]
Lots of discussion on 1439, do the jenkins tests run the examples locally? @andre-merzky @mturilli

**Comment by andre-merzky** [comment]
I am not sure if Jenkins is still functional / active.

**Comment by vivek-bala** [comment]
What are the plans regarding the jenkins tests? There are a lot of tickets regarding jenkins tests, backups, extensions, etc. Any suggestions on whether I should leave them open or close them and start testing discussion from scratch?

**Comment by andre-merzky** [comment]
I don't have a good answer.  We still lack decent remote integration testing very badly.

**Comment by mturilli** [comment]
See #1436

**Comment by andre-merzky** [comment]
outdated
