### ISSUE TITLE
Test all the tests for hotfixes

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1440]
Catch all the tests incrementally based on naming convention.

**Comment by andre-merzky** [comment]
I am not sure what the above means.  Does that refer to the branch naming, to get all hotfix branches tested?

**Comment by itomaldonado** [comment]
Andre, I think this (for now) may be a reminder or something?

He means that we should keep (and modify if needed) the naming convention we have for test cases that have been created to tackle any issue. for example we currently follow: `issue_1234.py`. This is a good convention. 

We should make sure that we have a folder where we keep all of those for now so as we move into using unittest we can migrate them to Test Cases easily and there is very little to change from the automated testing framework perspective.

**Comment by itomaldonado** [comment]
Also, this is for *me* to add those tests following the naming convention into our Jenkins.

**Comment by vivek-bala** [comment]
I'm not sure if all tests were added and what the current status/plan for the jenkins tests are. @andre-merzky any idea?

**Comment by andre-merzky** [comment]
I don't know either.

**Comment by andre-merzky** [comment]
outdated
