### ISSUE TITLE
"Where do I find the output of my (RP) job?"

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.pilot#1443]
https://github.com/radical-collaboration/CyberManufacturing/pull/8#issuecomment-327875302

**Comment by iparask** [comment]
Depends whether or not a Unit stages out data to the client. Generally, all the ouput from units as well as the pilot exist in the pilot sandbox. 

The sandbox can be found in the remote resource under the folder ```radical.pilot.sandbox/<session_name>```. ```<session_name>``` is the name of the RP session as it is reported when executing an RP script

**Comment by vivek-bala** [comment]
This refers to a merged PR. Assuming this info has been provided. Closing.
