### ISSUE TITLE
Allow explicit configuration of username and SSH Key for ssh sessions

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1445]
This is more of a QoL improvement. Always using the defaults on the machine for 'SSH' isn't a good idea. We should allow the user to enter a 'username' and/or 'ssh key' information (file location, like the `-i` flag) explicitly/programmatically.

This will make testing easier since the SSH keys will be on random files each time.

This **may** actually spawn a related issue in Saga.

**Comment by vivek-bala** [comment]
@andre-merzky I believe we already have the feature right? We can specify usernames. We also document/suggest to keep the settings in a SSH config file.

**Comment by andre-merzky** [comment]
Yes.  But either way, the documentation now recommends to use an ssh config for this.
