### ISSUE TITLE
profile profiler and logger

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1451]
at reasonable scale (16k+ units at scale, 1hr runs).

**Comment by vivek-bala** [comment]
@andre-merzky do we have any numbers for this? We may want to put this in a wiki or in the RTD as it may be useful to multiple people/projects.

**Comment by andre-merzky** [comment]
I don't think we have decent numbers.  Publications mostly do some hand waving `bla bla orders of magnitude bla bla`, which is not great.  I mean, I am sure the overhead is *indeed* small, but...

**Comment by mturilli** [comment]
This has value and we should probably do what is needed. As I am running experiments, I could have 1 more run without the profiler and logger and compare TTC. Only issue, will I be able to independently determine queue time?

**Comment by andre-merzky** [comment]
The batch system may provide some information about the queue time - but I would suggest to manually add a `print(time.time())` [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L824) and `date '+%s'` [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L824).

**Comment by mturilli** [comment]
Related to https://github.com/radical-cybertools/radical.pilot/discussions/2408

**Comment by andre-merzky** [comment]
Profiler has a throughput of about 500k events per second, the logger about 150k lines per second.  That is currently larger than what we need by about 2 orders of magnitude.
