### ISSUE TITLE
RP uses hyperthreading during mpi execution

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1462]
I am running a MPI application on Stampede2 using ibrun. Stampede2 has 68 cores and 4 threads per core.
When I define a CU with more than 68 cores, RP thinks there are 272 cores per node and puts the CU to run in one node utilizing hyper threading.

We should introduce a way to avoid hyperthreading.

**Comment by andre-merzky** [comment]
This will be addressed in the GPU branch.  At this point, RP relies on the batch system information which reports `68*4` process slots.  In the GPU branch, we can define the number of cores and threads per node.  I'll keep the ticket open until this is merged.

Iannis, do you have the option to switch to the GPU branches for this line of experiments?
Also, I am fairly sure this is indeed the intended way to use the nodes on stampede-2, isn't it?  What is the actual reason to avoid hyperthreading?

**Comment by andre-merzky** [comment]
After discussing this, we may want to consider adding a `cud.hyperthreading=True` flag to the CU description.

**Comment by vivek-bala** [comment]
Closing as the CU description has been discussed and changed since then.
