### ISSUE TITLE
AMBER on Comet fails inside RP

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1466]
The pilot is submitted (apparently) correctly, the executable is called (apparently) correctly, but then the CU fails because it is unable to locate some libraries. The simulations runs just fine standalone, i.e. outside of RP.

```
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
/opt/amber/bin/pmemd.MPI: error while loading shared libraries: libnetcdff.so.6: cannot open shared object file: No such file or directory
```

Unsure how to solve this. CU Description is as follows:

            # -------- BEGIN USER DEFINED CU DESCRIPTION --------- #

            cudesc = rp.ComputeUnitDescription()
            cudesc.environment = {'CU_NO': i}
            cudesc.executable  = "/opt/amber/bin/pmemd.MPI"
            cudesc.pre_exec = ['module load amber']
            cudesc.arguments   = ['-O',  '-i', 'mdin', '-o', 'mdout', '-p', 'prmtop', '-c', 'inpcrd','-inf', 'info.mdinfo']
            cudesc.input_staging = ['mdin','prmtop','inpcrd']
            #cudesc.output_staging = ['outfile']
            cudesc.cores = CU_CORES
            cudesc.mpi = True
            # -------- END USER DEFINED CU DESCRIPTION --------- #

**Comment by andre-merzky** [comment]
I assume you have to load some module or the other in order to get the application to work properly standalone?  If so, then you will likely need the same modules loaded in the CU environment.  You likely will want to put the `module load` command into the unit's `pre_exec` field, like shows [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/10_pre_and_post_exec.py#L91).

You are running on comet - note that pre- and post exec are not supported for the ORTE and ORTELIB configurations on comet - the ssh configuration should be able to handle this setup.

**Comment by SrinivasMushnoori** [comment]
While running it standalone, all I have to do is "module load amber" and that is already a part of my pre-exec.

Unsure how to invoke ssh configuration, as opposed to ORTE?

Thanks, Andre.

**Comment by andre-merzky** [comment]
Can you please send the following:

 - the output of the `radical-stack` command
 - your pilot description
 - your unit description

Thanks!

**Comment by SrinivasMushnoori** [comment]
radical-stack:

(RP_0.46_env) scm177@two:~/RP_Experiments/AMBER_RP_Tests$ radical-stack

  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/RP_0.46_env

  radical.analytics    : v0.45.2-7-g6862da3@devel
  radical.pilot        : 0.46.2
  radical.utils        : 0.46.2
  saga                 : 0.46.1


Pilot Description:

 RESOURCE_LABEL = 'xsede.comet'
    PILOT_CORES = 144
    BAG_SIZE = 1024 # The number of units
    CU_CORES = 72 # The cores each CU will take.
    QUEUE = "compute"
    # we use a reporter class for nicer output
    report = ru.LogReporter(name='radical.pilot')
    report.title('Getting Started (RP version %s)' % rp.version)

    # Create a new session. No need to try/except this: if session creation
    # fails, there is not much we can do anyways...
    session = rp.Session()

  try:
        pdesc = rp.ComputePilotDescription ()
        pdesc.resource = RESOURCE_LABEL  # this is a "label", not a hostname
        pdesc.cores    =  PILOT_CORES
        pdesc.runtime  = 1440    # minutes
        pdesc.cleanup  = False  # clean pilot sandbox and database entries
        pdesc.queue = QUEUE
        pdesc.access_schema = "gsissh" #For Blue Waters/Stampede
        pdesc.project = "TG-MCB090174" #account/allocation



CU description:

            # -------- BEGIN USER DEFINED CU DESCRIPTION --------- #

            cudesc = rp.ComputeUnitDescription()
            cudesc.environment = {'CU_NO': i}
            cudesc.executable  = "/opt/amber/bin/pmemd.MPI"
            cudesc.pre_exec = ['module load amber', 'export LD_LIBRARY_PATH=/opt/netcdf/4.3.2/intel/mvapich2_ib/lib']
            cudesc.arguments   = ['-O',  '-i', 'mdin', '-o', 'mdout', '-p', 'prmtop', '-c', 'inpcrd','-inf', 'info.mdinfo']
            cudesc.input_staging = ['mdin','prmtop','inpcrd']
            #cudesc.output_staging = ['outfile']
            cudesc.cores = CU_CORES
            cudesc.mpi = True
            # -------- END USER DEFINED CU DESCRIPTION --------- #

**Comment by andre-merzky** [comment]
Thanks!  BTW: you can specify code sections in github by using triple-backticks.

Can you please try the resource target `xsede.comet_ssh`?  Thanks!

**Comment by SrinivasMushnoori** [comment]
Ah, thanks Andre.

xsede.comet_ssh causes this:

```
mpirun_rsh: error while loading shared libraries: liblimic2.so.0: cannot open shared object file: No such file or directory

```

**Comment by andre-merzky** [comment]
Hmm, this is interesting - now we have a bug... :P  Can you please send me a tarball of the pilot sandbox?  Thanks!

**Comment by SrinivasMushnoori** [comment]
@andre-merzky So it took me a while to get back to this, and the sandbox is rather large. I've compressed the Agent side RP session and the VE directory on Comet and compressed them into a single tar, but even that's kind of big. 

Google drive link: https://drive.google.com/file/d/0B9F6J4ZfMhheQ0VBRXJ5c0Fia0U/view?usp=sharing

I hope this is what you need?

**Comment by andre-merzky** [comment]
Srinivas, do you need to use 0.46.2, or can you upgrade to devel?  That won't work either, but I'd rather fix that in devel than in the previous releases...

**Comment by SrinivasMushnoori** [comment]
Makes sense. Let me do that and upload the new tarball...
Be back in a bit.

**Comment by andre-merzky** [comment]
No need for a new tarball, I actually see whats up...  Just need confirmation that a fix on devel is useful for you... :)

**Comment by SrinivasMushnoori** [comment]
Ah I see. Yes certainly. I'll be useful to me. Thanks!

**Comment by SrinivasMushnoori** [comment]
After moving to the fix/issue_1466 branch,

STDERR:  

```mpirun_rsh: error while loading shared libraries: liblimic2.so.0: cannot open shared object file: No such file or directory```

STDOUT is blank

radical_pilot_launch_script.sh:

```
#!/bin/sh


# Environment variables
export RP_SESSION_ID="rp.session.two.scm177.017444.0002"
export RP_PILOT_ID="pilot.0000"
export RP_AGENT_ID="agent_0"
export RP_SPAWNER_ID="agent.executing.0.child"
export RP_UNIT_ID="unit.000000"
export RP_GTOD="/home/mushnoor/radical.pilot.sandbox/rp.session.two.scm177.017444.0002/pilot.0000/gtod"
export RP_PROF="/home/mushnoor/radical.pilot.sandbox/rp.session.two.scm177.017444.0002/pilot.0000/unit.000000/PROF"
export RP_TMP="/scratch/$USER/$SLURM_JOBID"
export "CU_NO=0"


touch $RP_PROF

# Change to unit sandbox
cd /home/mushnoor/radical.pilot.sandbox/rp.session.two.scm177.017444.0002/pilot.0000/unit.000000

# Pre-exec commands
module load amber ||  (echo "pre_exec failed"; false) || exit
export LD_LIBRARY_PATH=/opt/netcdf/4.3.2/intel/mvapich2_ib/lib ||  (echo "pre_exec failed"; false) || exit

# The command to run
mpirun_rsh -np 24 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-\
14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01 comet-14-01   ="$ \
"  /opt/amber/bin/pmemd.MPI "-O" "-i" "mdin" "-o" "mdout" "-p" "prmtop" "-c" "inpcrd" "-inf" "info.mdinfo"
RETVAL=$?

# Exit the script with the return code from the command
exit $RETVAL

```

**Comment by SrinivasMushnoori** [comment]
@andre-merzky Hi Andre, quick reminder: is this issue still on the map?

**Comment by andre-merzky** [comment]
I am actually working on it right now :)  Stumbled over an unrelated problem while testing though... :/  Nothing is ever easy...  Either way, will send an update later today.

**Comment by SrinivasMushnoori** [comment]
Thanks!

**Comment by andre-merzky** [comment]
Srinivas, could you please give that branch another try?  You will also need to update `radical.utils`, but there you can use the devel branch.

**Comment by SrinivasMushnoori** [comment]
Hi @andre-merzky , 

I'm only just getting around to this, I need a bit of clarification:
I use the devel branch of ```radical.utils``` and the ```fix/issue_1466``` branch on RP, correct?

**Comment by SrinivasMushnoori** [comment]
Hi Andre

Same issue.

```STDERR``` contents are as follows

```

mpirun_rsh: error while loading shared libraries: liblimic2.so.0: cannot open shared object file: No such file or directory


```


```STDOUT``` is blank.

radical stack is:

```

(RP_0.46_env) scm177@two:~/RP_Experiments/AMBER_RP_Tests$ radical-stack

  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/RP_0.46_env

  radical.analytics    : v0.45.2-7-g6862da3@devel
  radical.pilot        : 0.47-v0.46.2-18-g5c61694f@fix-issue_1466
  radical.utils        : 0.47-v0.46-18-g003a153@devel
  saga                 : 0.46.1


```

**Comment by andre-merzky** [comment]
Thanks Srinivas - let me try to reproduce this problem.

**Comment by andre-merzky** [comment]
Srinivas, please give the following stack a try:

```
  radical.pilot        : 0.47-v0.46.2-180-g4c0a6c10@rc-v0.46.3
  radical.utils        : 0.47-v0.46-73-gd580ab1@rc-v0.46.3
  saga                 : 0.47-v0.46-32-ga2f9dedc@rc-v0.46.3
```

This should be the HEAD of the `rc/v0.46.3` branches for all three layers.  Apparently, the configuration changed on comet, and we had to switch from `mpirun_rsh` to `ibrun`, but that now gets amber started as expected.

**Comment by SrinivasMushnoori** [comment]
@andre-merzky 

This works, can confirm! :)

**Comment by andre-merzky** [comment]
Ah, finally! :)  Thanks for your patience!
