### ISSUE TITLE
zmqError in 0.46.2

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1470]
```
georgeha.017442.0024$ grep ERROR *.log
pmgr.0000.log:2017-10-03 11:01:07,858: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : abort: ZMQError('Socket operation on non-socket')
pmgr.launching.0.child.log:2017-10-03 11:01:05,779: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
umgr.0000.log:2017-10-03 11:01:07,558: umgr.0000           : MainProcess                     : umgr.0000.subscriber._state_sub_cb: ERROR   : abort: ZMQError('Socket operation on non-socket')
```
radical-stack:

```

  python               : 2.7.6
  pythonpath           : 
  virtualenv           : /home/georgeha/ves/ve

  radical.pilot        : 0.46.2
  radical.utils        : 0.46.2
  saga                 : 0.46.1

```

**Comment by georgeha** [comment]
```
Traceback (most recent call last):
190   File "/home/georgeha/ves/ve/local/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
191     if not self.work_cb():
192   File "/home/georgeha/ves/ve/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1088, in
193     topic, msg = self._q.get_nowait(500)  # timout in ms
194   File "/home/georgeha/ves/ve/local/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 352, in get_
195     if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
196   File "/home/georgeha/ves/ve/local/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 50, in _unin
197     return f(*args, **kwargs)
198   File "/home/georgeha/ves/ve/local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 558, in poll
199     evts = dict(p.poll(timeout))
200   File "/home/georgeha/ves/ve/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
201     return zmq_poll(self.sockets, timeout=timeout)
202   File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c
203   File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c
204   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_po
205     raise ZMQError(errno)
206 ZMQError: Socket operation on non-socket      
```

**Comment by vivek-bala** [comment]
I think these messages come up during termination. These might not be the reason for any failure. Do you see a failure in your script execution? Can you attach all the client and agent logs please.

**Comment by georgeha** [comment]
at the target machine the ve_wrangler is not even created.

I'm attaching the client
[update.0.log](https://github.com/radical-cybertools/radical.pilot/files/1353097/update.0.log)
[umgr.unschedule.pubsub.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353096/umgr.unschedule.pubsub.bridge.0000.log)
[update.0.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353095/update.0.child.log)
[umgr.staging.output.queue.input.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353098/umgr.staging.output.queue.input.0000.log)
[umgr.staging.output.queue.output.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353101/umgr.staging.output.queue.output.0000.log)
[umgr.unschedule.pubsub.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353118/umgr.unschedule.pubsub.bridge.0000.child.log)
[umgr.staging.output.0.log](https://github.com/radical-cybertools/radical.pilot/files/1353104/umgr.staging.output.0.log)
[umgr.staging.output.queue.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353099/umgr.staging.output.queue.bridge.0000.child.log)
[umgr.staging.output.queue.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353100/umgr.staging.output.queue.bridge.0000.log)
[umgr.staging.input.queue.output.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353102/umgr.staging.input.queue.output.0000.log)
[umgr.staging.output.0.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353103/umgr.staging.output.0.child.log)
[umgr.staging.input.queue.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353107/umgr.staging.input.queue.bridge.0000.child.log)
[umgr.staging.input.queue.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353113/umgr.staging.input.queue.bridge.0000.log)
[umgr.staging.input.queue.input.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353105/umgr.staging.input.queue.input.0000.log)
[umgr.staging.input.0.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353106/umgr.staging.input.0.child.log)
[umgr.staging.input.0.log](https://github.com/radical-cybertools/radical.pilot/files/1353111/umgr.staging.input.0.log)
[umgr.scheduling.queue.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353110/umgr.scheduling.queue.bridge.0000.log)
[umgr.scheduling.queue.input.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353109/umgr.scheduling.queue.input.0000.log)
[umgr.scheduling.queue.output.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353108/umgr.scheduling.queue.output.0000.log)
[umgr.scheduling.0.log](https://github.com/radical-cybertools/radical.pilot/files/1353112/umgr.scheduling.0.log)
[umgr.scheduling.queue.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353114/umgr.scheduling.queue.bridge.0000.child.log)
[umgr.reschedule.pubsub.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353131/umgr.reschedule.pubsub.bridge.0000.log)
[umgr.scheduling.0.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353115/umgr.scheduling.0.child.log)
[state.pubsub.sub.0001.log](https://github.com/radical-cybertools/radical.pilot/files/1353116/state.pubsub.sub.0001.log)
[umgr.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353121/umgr.0000.log)
[umgr.reschedule.pubsub.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353117/umgr.reschedule.pubsub.bridge.0000.child.log)
[state.pubsub.pub.0005.log](https://github.com/radical-cybertools/radical.pilot/files/1353119/state.pubsub.pub.0005.log)
[state.pubsub.pub.0006.log](https://github.com/radical-cybertools/radical.pilot/files/1353120/state.pubsub.pub.0006.log)
[state.pubsub.sub.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353129/state.pubsub.sub.0000.log)
[state.pubsub.pub.0001.log](https://github.com/radical-cybertools/radical.pilot/files/1353124/state.pubsub.pub.0001.log)
[state.pubsub.pub.0002.log](https://github.com/radical-cybertools/radical.pilot/files/1353122/state.pubsub.pub.0002.log)
[state.pubsub.pub.0003.log](https://github.com/radical-cybertools/radical.pilot/files/1353123/state.pubsub.pub.0003.log)
[state.pubsub.pub.0004.log](https://github.com/radical-cybertools/radical.pilot/files/1353125/state.pubsub.pub.0004.log)
[state.pubsub.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353126/state.pubsub.bridge.0000.child.log)
[state.pubsub.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353127/state.pubsub.bridge.0000.log)
[state.pubsub.pub.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353128/state.pubsub.pub.0000.log)
[pmgr.launching.queue.input.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353130/pmgr.launching.queue.input.0000.log)
[pmgr.launching.queue.output.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353146/pmgr.launching.queue.output.0000.log)
[rp.session.js-17-20.jetstream-cloud.org.georgeha.017442.0031.log](https://github.com/radical-cybertools/radical.pilot/files/1353132/rp.session.js-17-20.jetstream-cloud.org.georgeha.017442.0031.log)
[pmgr.launching.0.log](https://github.com/radical-cybertools/radical.pilot/files/1353135/pmgr.launching.0.log)
[pmgr.launching.queue.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353133/pmgr.launching.queue.bridge.0000.child.log)
[pmgr.launching.queue.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353134/pmgr.launching.queue.bridge.0000.log)
[pmgr.launching.0.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353137/pmgr.launching.0.child.log)
[log.pubsub.pub.0005.log](https://github.com/radical-cybertools/radical.pilot/files/1353140/log.pubsub.pub.0005.log)
[log.pubsub.pub.0006.log](https://github.com/radical-cybertools/radical.pilot/files/1353136/log.pubsub.pub.0006.log)
[pmgr.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353138/pmgr.0000.log)
[log.pubsub.pub.0002.log](https://github.com/radical-cybertools/radical.pilot/files/1353142/log.pubsub.pub.0002.log)
[log.pubsub.pub.0003.log](https://github.com/radical-cybertools/radical.pilot/files/1353155/log.pubsub.pub.0003.log)
[log.pubsub.pub.0004.log](https://github.com/radical-cybertools/radical.pilot/files/1353139/log.pubsub.pub.0004.log)
[log.pubsub.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353141/log.pubsub.bridge.0000.log)
[log.pubsub.pub.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353144/log.pubsub.pub.0000.log)
[log.pubsub.pub.0001.log](https://github.com/radical-cybertools/radical.pilot/files/1353151/log.pubsub.pub.0001.log)
[control.pubsub.pub.0006.log](https://github.com/radical-cybertools/radical.pilot/files/1353143/control.pubsub.pub.0006.log)
[control.pubsub.sub.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353148/control.pubsub.sub.0000.log)
[control.pubsub.sub.0001.log](https://github.com/radical-cybertools/radical.pilot/files/1353145/control.pubsub.sub.0001.log)
[log.pubsub.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353158/log.pubsub.bridge.0000.child.log)
[control.pubsub.pub.0003.log](https://github.com/radical-cybertools/radical.pilot/files/1353147/control.pubsub.pub.0003.log)
[control.pubsub.pub.0004.log](https://github.com/radical-cybertools/radical.pilot/files/1353149/control.pubsub.pub.0004.log)
[control.pubsub.pub.0005.log](https://github.com/radical-cybertools/radical.pilot/files/1353150/control.pubsub.pub.0005.log)
[control.pubsub.pub.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353152/control.pubsub.pub.0000.log)
[control.pubsub.pub.0001.log](https://github.com/radical-cybertools/radical.pilot/files/1353153/control.pubsub.pub.0001.log)
[control.pubsub.pub.0002.log](https://github.com/radical-cybertools/radical.pilot/files/1353154/control.pubsub.pub.0002.log)
[control.pubsub.bridge.0000.child.log](https://github.com/radical-cybertools/radical.pilot/files/1353156/control.pubsub.bridge.0000.child.log)
[control.pubsub.bridge.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1353157/control.pubsub.bridge.0000.log)

**Comment by georgeha** [comment]
that might me related too:
```
host bootstrap failed - no pid (PID: 1398
rm: cannot remove ‘.saga/adaptors/shell_job/.nfs000000000b3d152200000266’: Device or resource busy
rm: cannot remove ‘.saga/adaptors/shell_job/.nfs000000000b3d151d000006ed’: Device or resource busy
rm: cannot remove ‘.saga/adaptors/shell_job/51436.0/.nfs000000000b4141cb000006eb’: Device or resource busy
rm: cannot remove ‘.saga/adaptors/shell_job/51436.0/.nfs000000000b4141cc000006ec’: Device or resource busy
rm: cannot remove ‘.saga/adaptors/shell_job/51436.0/.nfs000000000b4141d1000006ea’: Device or resource busy
rm: cannot remove ‘.saga/adaptors/shell_job/51436.0/.nfs000000000b4141d2000006e9’: Device or resource busy
)
```
Should I kill a process to stop that?

**Comment by itomaldonado** [comment]
do you have any `.err` files? specifically `pmgr.0000.err`

**Comment by vivek-bala** [comment]
> host bootstrap failed - no pid (PID: 1398
rm: cannot remove ‘.saga/adaptors/shell_job/.nfs000000000b3d152200000266’: Device or resource busy

Can you delete the ```.saga``` folder try again?

Also when you are attaching a large number of files, please zip/tar the files and attach the compressed file to the ticket. If its a single file, you can consider even pasting the contents in a gist file and attaching a link to the gist in the ticket.

**Comment by georgeha** [comment]
[client.zip](https://github.com/radical-cybertools/radical.pilot/files/1353184/client.zip)
I uploaded everything again in the zip file.

I tried that one:
```
rm -rf ~/.saga/
rm: cannot remove ‘/home/03662/tg829618/.saga/adaptors/shell_job/.nfs000000000b3d152200000266’: Device or resource busy
```
the problem is that if another process is using a file, I can't delete it like that.

**Comment by georgeha** [comment]
I found it. I saw the content of the file and then I used this command to find the correct process.

```
ps -ef | grep username
```

**Comment by andre-merzky** [comment]
Great!

BTW, if you don't mind, please upload a tarball of the logfiles the next time - that makes it much simpler to download all of them...  Thanks! :)
