### ISSUE TITLE
FIXME solution idea - file continuous.py - line 281 - More detailed "completion message" from completing CU so RP will know which resources became free without looking through the list

### ISSUE THREAD

**Issue by FranklinBetten** [radical-cybertools/radical.pilot#1475]
Link to file / line of interest
https://github.com/radical-cybertools/radical.pilot/blob/feature/gpu/src/radical/pilot/agent/scheduler/continuous.py#L281 

At the RCT meeting today I became aware of performance issues in line 281 of continuous.py. The for loop that checks for which nodes are free appeared to be a large performance bottleneck. It sounded like currently the program iterates through the list of nodes to check which ones are free so it can figure out where to allocate the next CU after one CU finishes its workload.

I was thinking to solve this problem we could have the CU that  finishes send some extra information with the message it passes that declares to RP it has finished computing. If the CU also sends out which node it was running on, the number of cores, etc, when it passes its "completion message", then there will be no need to search for an "available" node (since RP will know from the message it received which resource became free). Instead of looking through a list of nodes RP will know exactly where to allocate the next CU that needs to run since it know on which resource the last CU finished running.

**Comment by andre-merzky** [comment]
Thanks Franklin!  Information like that are actually available at this point, see here: https://github.com/radical-cybertools/radical.pilot/blob/feature/gpu/src/radical/pilot/agent/scheduler/base.py#L447
The `slots` structure passed to the `self._release_slots()` method is exactly the one we attached to the unit while scheduling.  So we know what cores were freed, on what node!

The caveat is the following: the agent scheduler cannot assume that the next unit has the same requirements - it might need more or less cores / gpus / thread, mit or might not be an MPI unit, etc.  So it is not at all clear that it fits exactly the set of cores just freed by the finishing unit.  How would you account for that?

**Comment by vivek-bala** [comment]
Thanks for the idea/discussion folks! Closing the ticket.
