### ISSUE TITLE
Need to update pre_bootstrap pre_exec for SuperMIC to load correct version of Python

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1478]
I tried running on SuperMIC using the `rc/0.46.3` branch but I got the following error in the `bootstrap_1.out` :
```
/worka/work/mha/radical.pilot.sandbox/ve.xsede.supermic.0.47/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

Turns out the problem is that RP runs `module load python` in order to load Python 2.7. On SuperMIC, it seems that running `module load python` loads a different version of Python, namely `python/3.6.2-anaconda-tensorflow`.

The fix to this is to specify exactly the module of Python to load [here](https://github.com/radical-cybertools/radical.pilot/blob/rc/v0.46.3/src/radical/pilot/configs/resource_xsede.json) so that we load a module of Python 2.7, and delete the current virtual environment on from the sandbox. I have tested this fix for the module `python/2.7.7/GCC-4.9.0` and it works for me, but I am using an older commit of the branch. There are also other modules of Python, but I think this module should be fine (or also up for discussion).

EDIT: `module load python` is also a pre_bootstrap command in `devel` branch. Is there a neat way to apply all the changes to all the branches?

EDIT2: Formatting

**Comment by andre-merzky** [comment]
that sounds reasonable, Ming.  Would you mind opening a pull request? :-D  Thanks!

**Comment by vivek-bala** [comment]
I believe https://github.com/radical-cybertools/radical.pilot/pull/1479 addresses this issue. Closing.
