### ISSUE TITLE
Pilot fails with "could not import netifaces" in bootstrap_1.out

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1481]
Clientside and agentside files attached. 

[agent_rp.session.mcewan.engr.rutgers.edu.scm177.017465.0008.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1419430/agent_rp.session.mcewan.engr.rutgers.edu.scm177.017465.0008.tar.gz)

[client_rp.session.mcewan.engr.rutgers.edu.scm177.017465.0008.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1419436/client_rp.session.mcewan.engr.rutgers.edu.scm177.017465.0008.tar.gz)

Thanks!

**Comment by andre-merzky** [comment]
The virtualenv seems incomplete.   Can you please remove `/home/scm177/radical.pilot.sandbox/ve.local.localhost.0.47` and try again?

**Comment by vivek-bala** [comment]
Hey @SrinivasMushnoori , any updates here? Do you see this issue any more?

**Comment by SrinivasMushnoori** [comment]
Hi folks, I do not believe I see this issue right now. If I face this again we can always reopen. Closing.
