### ISSUE TITLE
RP profiles missing

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1483]
running following stack: 

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/jdakka/UCL/gpu_branch_env/venv

  radical.pilot        : 0.47-v0.46.2-93-g379bd68d@feature-gpu
  radical.utils        : 0.47-v0.46-18-g003a153@devel
  saga                 : 0.47-v0.46-23-g21cb4e9d@feature-gpu
```
I experience cut-off in the RP profiles after running radicalpilot-fetch-profiles: 

```
control.pubsub.bridge.0000.child.log        pmgr.launching.queue.output.0000.log
control.pubsub.bridge.0000.log              rp.session.two.jdakka.017465.0000
control.pubsub.pub.0000.log                 rp.session.two.jdakka.017465.0000.log
control.pubsub.pub.0001.log                 rp.session.two.jdakka.017465.0000.prof
control.pubsub.pub.0002.log                 state.pubsub.bridge.0000.child.log
control.pubsub.sub.0000.log                 state.pubsub.bridge.0000.log
control.pubsub.sub.0001.log                 state.pubsub.pub.0000.log
log.pubsub.bridge.0000.child.log            state.pubsub.pub.0001.log
log.pubsub.bridge.0000.log                  state.pubsub.pub.0002.log
log.pubsub.pub.0000.log                     state.pubsub.sub.0000.log
log.pubsub.pub.0001.log                     umgr.scheduling.0.child.err
log.pubsub.pub.0002.log                     umgr.scheduling.0.child.out
pmgr.0000.log                               umgr.staging.input.0.child.err
pmgr.0000.prof                              umgr.staging.input.0.child.out
pmgr.launching.0.child.err                  umgr.staging.output.0.child.err
pmgr.launching.0.child.log                  umgr.staging.output.0.child.out
pmgr.launching.0.child.out                  update.0.child.err
pmgr.launching.0.child.prof                 update.0.child.log
pmgr.launching.0.log                        update.0.child.out
pmgr.launching.0.prof                       update.0.child.prof
pmgr.launching.queue.bridge.0000.child.log  update.0.log
pmgr.launching.queue.bridge.0000.log        update.0.prof
pmgr.launching.queue.input.0000.log
```

Will use the release candidate instead as suggested by Matteo et al.

**Comment by andre-merzky** [comment]
we now have a merge between GPU and RC branches, in `experiment/jdakka` (for RU, RS, RP).  This presumable resolves this issue, awaiting feedback from @vivek-bala and @jdakka .

**Comment by jdakka** [comment]
I tested out this branch a while back but since we have reverted back to the RC branch for the multiple MPI application constraint imposed by BW. Now I'm testing it out again, just with vanilla gpu-stack and I noticed that while all my profiles were created some of them are empty. I pulled the latest on rp feature/gpu and ru devel to test again. I'll update this ticket for what happens shortly.

As for the experiment/jdakka merge I got a resource submission failure on the appmanger in EnTK. Attached are the client/agent files. 
[rp.session.two.jdakka.017493.0002.zip](https://github.com/radical-cybertools/radical.pilot/files/1497854/rp.session.two.jdakka.017493.0002.zip)
[8_replicas.zip](https://github.com/radical-cybertools/radical.pilot/files/1497855/8_replicas.zip)

**Comment by jdakka** [comment]
Looks like the profiles are still missing using `features/gpu` (RE,RP,RS) with `devel` on RU. I get error  `row invalid` from the bootstrap.prof. 

The screenshot shows the truncated profiles in the `/pilot.0000` (significantly less than profiles provided using rc branch)
<img width="784" alt="screen shot 2017-11-22 at 9 39 00 pm" src="https://user-images.githubusercontent.com/17818114/33157172-189b64a6-cfce-11e7-85d3-1f9ecd0b90bc.png">

**Comment by jdakka** [comment]
the components in the header of the bootstrap.prof file are as follows:

```
#time,name,uid,state,event,msg
0.0072,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,bootstrap_1_start,
...
```

However the profiler.py file in RU shows the the arrangements in the following order:

```
TIME         = 0  # time of event (float, seconds since epoch)  mandatory
EVENT        = 1  # event ID (string)                           mandatory
COMP         = 2  # component which recorded the event          mandatory
TID          = 3  # uid of thread involved                      optional
UID          = 4  # uid of entity involved                      optional
STATE        = 5  # state of entity involved                    optional
MSG          = 6  # message describing the event                optional
ENTITY       = 7  # type of entity involved                     optional
PROF_KEY_MAX = 8  # iteration helper: `for _ in range(PROF_KEY_MAX):
```

It's expecting COMP instead of UID 

As a results the full error I get is 

```
row invalid [./replicas_8_trial_3/rp.session.two.jdakka.017493.0000/pilot.0000/bootstrap_1.prof]: ['0.0072', 'bootstrap_1', 'pilot.0000', 'PMGR_ACTIVE_PENDING', 'bootstrap_1_start', '']
```

**Comment by jdakka** [comment]
one last comment :) 

In case you need to try the notebook for yourself (and also see what the profiles look like) 

https://github.com/radical-experiments/htbac-experiments/tree/master/esmacs_entk06/entk-6-barrier-gpu

**Comment by andre-merzky** [comment]
Hmm, the list of profiles looks good actually.  Which ones are missing in your opinion?

As for the `row invalid` error: please set `RADICAL_ANALYTICS_LEGACY_PROFILES=TRUE` in your environment and try again to read them.  That should provide backward compatibility.  Hmm, maybe I should make that setting a default...

Sorry for the incorrect header of the profiles - that was fixed meanwhile.

**Comment by jdakka** [comment]
I get an error further down:
```
/Users/JumanaDakka/environments/venv_gpu/lib/python2.7/site-packages/radical/utils/profile.py in read_profiles(profiles, sid, efilter)
    370                             print "here are the rows"
    371                             print row
--> 372                             comp, tid = row[1].split(':', 1)
    373                             new_row = [None] * PROF_KEY_MAX
    374                             new_row[TIME        ] = row[0]
```
I had it print the first row output:
`[0.0072, 'bootstrap_1', 'pilot.0000', 'PMGR_ACTIVE_PENDING', 'bootstrap_1_start', '', None, 'bootstrap_1_start']`
Are you sure you meant do to `comp, tid = row[1].split(':', 1)` instead of `row[1].split('_', 1)` ? That is if the headers of comp and tid are indeed supposed to be `bootstrap_1`

**Comment by jdakka** [comment]
Actually even with my fix it ran but didn't return the rp_dur or exec_dur. I think in the legacy version of that element had a ":"

**Comment by andre-merzky** [comment]
Hey Jumana, 

sorry for the late reply!  Is this still an issue?  In the other ticket, you seem to be able to get the data now?

**Comment by jdakka** [comment]
@andre-merzky Vivek pushed a new branch for me to test out for profiles. I'll keep you posted

**Comment by andre-merzky** [comment]
Hi @jdakka - I think this is the ticket you referred to during the call.  I am not sure if any action is expected on my end right now, could you help me out and clarify, please?

**Comment by jdakka** [comment]
Hi Andre, 

I have the complete set of profiles but some rp.states are missing. 
specifically I cannot access`rp.PMGR_ACTIVE`. The durations return 0. I've had to resort to using `rp.UMGR_SCHEDULING_PENDING`

**Comment by andre-merzky** [comment]
Hmm, the state transition is recorded all right:

```
agent_0.prof:1512981825.0028,advance,agent_0,MainThread,pilot.0000,PMGR_ACTIVE,
```

Are you still on that stack from the top, and working in the same notebook?  If not, can you please update the stack and send a notebook or script, and I'll try to reproduce this.  Thanks!

**Comment by jdakka** [comment]
I noticed that none of the pilot manager states are working:

`rp_dur = pilots.duration([rp.PMGR_ACTIVE, rp.DONE])`

```
PMGR_ACTIVE = 'PMGR_ACTIVE'
PMGR_ACTIVE_PENDING = 'PMGR_ACTIVE_PENDING'
PMGR_LAUNCHING = 'PMGR_LAUNCHING'
PMGR_LAUNCHING_PENDING = 'PMGR_LAUNCHING_PENDING'
```
They all return 0.

**Comment by vivek-bala** [comment]
I can confirm the same with the devel stack as well as

```
$ radical-stack

  python               : 2.7.13
  pythonpath           : 
  virtualenv           : 

  radical.analytics    : v0.45.2-7-g6862da3@devel
  radical.pilot        : 0.47-v0.46.2-15-g62a193b@HEAD-detached-at-62a193b
  radical.utils        : 0.47-v0.46.2-6-gc515db1@HEAD-detached-at-c515db1
  saga                 : 0.47-v0.46-5-g74fc381@HEAD-detached-at-74fc381
```

**Comment by andre-merzky** [comment]
> rp_dur = pilots.duration([rp.PMGR_ACTIVE, rp.DONE])

Does the pilot end in `DONE` state?  In general, you may want to use either of these (the 2 lines are equivalent):
```
rp_dur = pilots.duration([rp.PMGR_ACTIVE, rp.FINAL])
rp_dur = pilots.duration([rp.PMGR_ACTIVE, [rp.DONE, rp.FAILED, rp.CANCELED]])
```

**Comment by andre-merzky** [comment]
```
 thinkie  merzky  …/radical.analytics.devel/4_instances/rp.session.two.jdakka.017511.0001  [devel *] $ cat *prof | sort -n | grep pilot.0000 | grep advance | tail -n 1
1512992343.4660,advance,pmgr.0000,pmgr.0000.idler._state_pull_cb,pilot.0000,CANCELED,
```

So, `CANCELED` it is I think?

**Comment by vivek-bala** [comment]
I'm closing this ticket as it is pretty old. We haven't faced any issue of this type recently. Also now, we check for all final states of the Pilot in EnTK.
