### ISSUE TITLE
shield the executor mkdir

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1485]

**Comment by vivek-bala** [comment]
Hey @andre-merzky are you referring to [this](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/executing/popen.py#L233). Can you add some more info on why and from what it has to be shielded?

**Comment by andre-merzky** [comment]
Ah, this is actually [implemented by now](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/utils/misc.py#L55).  The reason was that the sandbox might exist is data were staged for the unit previously.
