### ISSUE TITLE
truncation of profiles in GPU branch

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1487]
needs cherry-picks from RC.

**Comment by andre-merzky** [comment]
we now have a merge between GPU and RC branches, in `experiment/jdakka` (for RU, RS, RP).  This presumable resolves this issue, awaiting feedback from @vivek-bala and @jdakka .

**Comment by vivek-bala** [comment]
Apologies for not updating the ticket. But I can confirm this is no longer an issue for me. I haven't seen any truncated profiles. @jdakka do you see this issue anymore?
