### ISSUE TITLE
Request for Comments - Node representation

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1493]
I suggest we discuss the possibility and viability of changing the representation of Nodes (cores, GPUs, availability, etc...) from a map/dict to an actual python object.

So this will change the current node list:
```
nodelist = [{name : 'node_1', cores: [##--------------], gpus : [#-]},
                {name : 'node_2', cores: {----------------], gpus : [--]},
                ...
               ]
```

to something along the lines of:

```
nodelist = [nodeObj1, nodeObj2, ... ,nodeObjn]
```

The current representation could be translated into a class quite easily, as in, the same core/gpu map etc. but with this application we have several pros/cons.

Pros:
* Simplified handling of the nodes: every time we have to write something that interacts with the node (e.g. scheduling) the developer does not need to know about the internals of the map exactly, it can just say `node.core_free_count()` instead of the current approach which is, every time you need the free count you have to do a for-loop or use the `.count()` method.
* Centralized way of node operations: we can centralize all of the node's operations in one place, this way we don't worry about how one component checks for free nodes versus another. Also means any changes we do there will be automatically used by all components
  * An example of this would be that the counts could be kept as instance variables (increased/decreased each time alloc/dealloc is called) so we don't have to run a for-loop or call `.count()` each time we need the list of free cores/gpus.
* We can use this as a base for a class that represent your resources (which would replace the actual "nodelist" for improvements there, maybe on how we represent that list and how we search for free cores/gpus faster/more efficiently (maybe using heaps, or circular buffers or something...).

Cons:
* sure, lots of re-writing...
* arguably, more rigid than using a plain dictionary (generality)
* keeping in memory list of objects versus plain dictionaries
* overhead of object/method invocation may need to be research to see if it is better/worth the effort over what we have.
* (can't think of anything right now....)

**Comment by andre-merzky** [comment]
I like that RFC!  Well, I also disagree, but I like it :-D  I'll reply in detail later.

**Comment by andre-merzky** [comment]
'later' I said, and 'later' it is ;-)  - but I'll keep this short.   What I would like to do is to move the scheduling algorithm to C.  It is a bottleneck, and adding objects won't help.  If anything, we should move to sets, as those are faster in Python.

I agree on *all* the readability and clarity points - but I think that in terms of scale we are beyond that point.  If we have a decent C scheduler implementation, I would like to take up your RFC and add a decent API along those lines on top of it.

Have a look at this: https://github.com/radical-cybertools/radical.utils/blob/feature/scheduler/bin/radical-utils-scheduler.py. That branch of RU contains an interface to a bitarray implementation in Python and puts a scheduler on top of it.   I did not have the time to move this forward, but that's something I'd like to see taken up at some point, and to be equipped with a decent API, to be used in both the UMGR and the Agent scheduler...

**Comment by vivek-bala** [comment]
I think we have managed to agree and change the node representation in our scheduler. Closing this ticket. @andre-merzky not sure if it changes anything, but the URL to the bit array scheduler is broken (maybe it got merged),

**Comment by andre-merzky** [comment]
Yes, it did get merged. Thanks.
