### ISSUE TITLE
Ibrun does not return exit code?!

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1496]
Hello Andre,

I noticed the following happening. When I run a MPI program with ibrun on Stampede2 I see the following:

Success:
```
TACC:  MPI job exited with code: 1
TACC:  Shutdown complete. Exiting.
c455-041[knl](18)$ RETVAL=$?
c455-041[knl](19)$
```
Failure:
```
TACC:  MPI job exited with code: 1
TACC:  Shutdown complete. Exiting.
c455-041[knl](22)$ RETVAL=$?
c455-041[knl](23)$
```

I am not sure if RP is then able to get the correct exit code. Any ideas how to fix this? I will continue looking.

**Comment by andre-merzky** [comment]
Hmm, interesting, that works ok on stampede_1:

```
c557-904.stampede(1)$ ibrun -n 1 fail
TACC: Starting up job 8712327
TACC: Setting up parallel environment for MVAPICH2+mpispawn.
ERROR: The -n option to ibrun was set but -o was not.
TACC: MPI job exited with code: 1
c557-904.stampede(2)$ echo $?
1
```

I think this should be an XSEDE ticket.  Would you mind opening one?
Thanks!

**Comment by iparask** [comment]
Wait I missed doing echo $RETVAL?!

**Comment by andre-merzky** [comment]
Hahaha...  :)

**Comment by iparask** [comment]
My mistake. It works...... Apparently the application I am running had a bug and did not return something upon completion
