### ISSUE TITLE
mpiexec args differ between hydra and ompi

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1498]
`--hosts` vs. `-H`

**Comment by mturilli** [comment]
We may want to close this ticket and we will open a new one when we will start to officially work on Frontera. @andre-merzky?

**Comment by andre-merzky** [comment]
This is not related to the DVM based launchers, but rather to the `mpiexec` launch method.  mpiexec is provided by both OpenMPI and MPICH, but their argument specs differ.  We have a similar switch already in place for env settings (see [here](https://github.com/radical-cybertools/radical.pilot/blob/feature/summit/src/radical/pilot/agent/lm/mpiexec.py#L57)), but that needs to be extended to the host specs.

**Comment by vivek-bala** [comment]
Okay, will leave this ticket open in that case.

**Comment by mturilli** [comment]
I think we just hit this issue again few days ago. Apart being aware of the differences, I see little else we can do about it.
