### ISSUE TITLE
aprun defaults to 1 core for nonMPI applications on Blue Waters

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1500]
I'm running a nonMPI  EnTK script on blue waters where I allocate 32 cores for my NAMD executables. 

on the agent/launch method in the VE, there seems to be a problem with the way nonMPI pes are allocated:

```def construct_command(self, cu, launch_script_hop):

        opaque_slots = cu['opaque_slots']
        cud          = cu['description']
        task_exec    = cud['executable']
        task_cores   = cud['cores']
        task_mpi     = cud['mpi']
        task_args    = cud.get('arguments') or []
        task_argstr  = self._create_arg_string(task_args)

        if task_argstr:
            task_command = "%s %s" % (task_exec, task_argstr)
        else:
            task_command = task_exec

        if task_mpi:
            pes = task_cores
        else:
            pes = 1

        node_set = set()
        for slot in opaque_slots['task_slots']:
            node_set.add(slot.split(':')[0])
        node_list = ','.join(list(node_set))

        aprun_command = "%s -L %s -n %d %s" \
                      % (self.launch_command, node_list, pes, task_command)

        return aprun_command, None
```

This is inline with command to run from the unit folder:

`/opt/xalt/0.7.6/sles11.3/bin/aprun -L 3944 -n 1 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-ugni-smp-BlueWaters-memopt/namd2 "2j6m-a698g/mineq_confs/eq0.conf" 
RETVAL=$?`

Is there a way to pass the cores from the EnTK attribute down to the aprun RP layer?

**Comment by andre-merzky** [comment]
This should actually be fixed in the GPU branch already.  Is that an option for you?

**Comment by jdakka** [comment]
I tested it with the gpu stack. I had a minor hiccup (but no trace of the error) where I didn't set the processes correctly for the last NAMD executable so I didn't get a full run to examine the profiles issue we faced in "RP profiles are missing on BW" ticket (which I can no longer find). I'll update you once I get a full run.

**Comment by andre-merzky** [comment]
Any updates? :-)

**Comment by jdakka** [comment]
I used the GPU branch solely because I used a non-MPI version of NAMD and had core pin using the GPU stack. However I was able to retrieve an MPI version of NAMD on Blue Waters and reverted back to the RC/master stack. 

I will update this ticket because most likely once I begin to use NAMD on Titan (which will require core pinning). Once I have a completed run I can test with RP-Analytics.

**Comment by iparask** [comment]
@jdakka, is this issue still affecting your experiments?

**Comment by iparask** [comment]
Bluewaters is getting decommissioned. I'm closing this issue after discussing it with @jdakka
