### ISSUE TITLE
wait_units does not return

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1501]
I am using:

```
umgr.wait_units(uids=[dem_unit.uid],state=[rp.AGENT_SCHEDULING_PENDING])
```

and it does not return when the unit reaches this state.

My stack is:
```
python               : 2.7.14
  pythonpath           :
  virtualenv           : Cyber

 radical.pilot        : 0.47-v0.46.2-186-g2648ca47@experiment-cybermanufacturing
  radical.utils        : 0.47-v0.46-77-ga7b4e00@rc-v0.46.3
  saga                 : 0.47-v0.46-32-ga2f9dedc@rc-v0.46.3
```

**Comment by andre-merzky** [comment]
Hmm, can you please attach set of logfiles, from both agent and client side?

**Comment by iparask** [comment]
Anything specific?

**Comment by andre-merzky** [comment]
No, since I don't know where the notification for the state change gets lost.  So, preferably all of them (and preferably in an otherwise small run, if you have that)

**Comment by iparask** [comment]
[pilot_logs.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1489348/pilot_logs.tar.gz)

[client_logs.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1489349/client_logs.tar.gz)

**Comment by iparask** [comment]
Fixed in the fix/issue_1501 branch. Closing
