### ISSUE TITLE
RC v0.47 Jenkins Test Fails -- example 07_shared_unit_data.py never completes

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1503]
The jenkins job linked below ran for over 8 days. It got stuck on the `07_shared_unit_data.py` example without a discernible error. Will post log files soon.

Jenkins Link: https://jenkins.radical-project.org/job/radical.pilot.devel.test.adhoc/5/

**Comment by andre-merzky** [comment]
This one got stuck because of #1495 - I'll address this for the release.

**Comment by andre-merzky** [comment]
This is resolved now, and will go into the next release (`v0.47`)
