### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1505]
Would it be possible to do the following?

- Input from localhost:

- A large file or array which contains a very big list/array

- Partition the array and stage it to memory
- Each CU will be able to access a partition based on  criteria

**Comment by andre-merzky** [comment]
Ah, apologies, I missed that ticket!!

**Comment by andre-merzky** [comment]
thanks again George - I am angry at myself for missing it... :/  As discussed, its out of scope for the time being.  Fascinating topic for sure, but too complex to tackle in our class setting... :/  Closing thus for now.
