### ISSUE TITLE
Question about scheduling

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1506]
- Wrangler has 24 physical cores and each core has 2 logical cores. If
- I have a program with 8 compute Units . 
Can I make sure that the units, since they are less than 24, are scheduled only on physical cores?

**Comment by andre-merzky** [comment]
RP does in general not distinguish between logical and physical cores.  In fact, the system does neither, ie. the cores as presented by the system are all equivalent, ie. it only exposes the logical cores.  But indeed, if one starts only 24 processes per node, the system load balancer is likely to place on process per physical core.

For the released version of RP, that can be achieved by creating a resource configuration which sets `cores_per_node=24` - then the agent scheduler will treat the nodes as 24-core nodes, and will only place 3 of your CUs onto them at any time.  In the GPU branches this still works, but you can also set `cpu_threads=2` in the unit description, meaning that each process gets two cores assigned, presumable for threading, but if those threads don't get spawned they'll idle.

**Comment by georgeha** [comment]
Thank you very much Andre. Make sense!
