### ISSUE TITLE
Units are not canceled when cancel is being sent

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1510]
I am opening this because of this [ticket](https://github.com/radical-collaboration/CyberManufacturing/issues/43)

**Comment by iparask** [comment]
The unit get registered for cancelation:
```
iparask@DESKTOP-R64I4QR:/mnt/c/Users/neinon21/Desktop/New folder/client$ grep 'register for cancellation' *.log
pmgr.0000.launching.0.child.log:2017-12-03 14:31:46,551: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : pmgr.0000.launching.0.child.subscriber._cancel_monitor_cb: DEBUG   : register for cancellation: ['unit.000000']
umgr.0000.scheduling.0.child.log:2017-12-03 14:31:46,552: umgr.0000.scheduling.0.child: umgr.0000.scheduling.0          : umgr.0000.scheduling.0.child.subscriber._cancel_monitor_cb: DEBUG   : register for cancellation: ['unit.000000']
umgr.0000.staging.input.0.child.log:2017-12-03 14:31:46,552: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : umgr.0000.staging.input.0.child.subscriber._cancel_monitor_cb: DEBUG   : register for cancellation: ['unit.000000']
umgr.0000.staging.output.0.child.log:2017-12-03 14:31:46,551: umgr.0000.staging.output.0.child: umgr.0000.staging.output.0      : umgr.0000.staging.output.0.child.subscriber._cancel_monitor_cb: DEBUG   : register for cancellation: ['unit.000000']
update.0.child.log:2017-12-03 14:31:46,552: update.0.child      : update.0                        : update.0.child.subscriber._cancel_monitor_cb: DEBUG   : register for cancellation: ['unit.000000']
```

**Comment by iparask** [comment]
Here is a difference which I find important between canceling a pilot and canceling a unit. When a pilot is being canceled a message that got to the DB is being send through the [pilot_command](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/db/database.py#L230) method if the `database` class. A `cancel_pilots` command is being recorded in the DB and `agent_0` sees it as:
```
agent_0.log:2017-12-03 17:17:05,761: agent_0             : MainProcess                     : agent_0.idler._agent_command_cb: DEBUG   : Giannis: {u'cmd': u'cancel_pilot', u'arg': []}, retdoc {u'cmd': [{u'cmd': u'cancel_pilot', u'arg': []}], u'_id': u'pilot.0000'}
```
when [_check_commannds](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/agent_0.py#L409) is executed. 

When a unit cancel is requested the unit manager push a message in the [control pubsub](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/unit_manager.py#L976), but I am not sure where the DB is being updated. In addition, `agent_0` pushes the message of a unit cancelation is being requested ([code](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/agent_0.py#L453)).

I suggest a similar solution for the unit cancelation as it is for pilot cancelation

**Comment by iparask** [comment]
Okay! The agent gets the message:
```
Ioannis’s Mac pilot.0000$ grep 'cancel unit' *.log
agent_0.executing.0.child.log:2017-12-03 18:00:20,602: agent_0.executing.0.child: agent_0.executing.0             : agent_0.executing.0.child.subscriber.command_cb: INFO    : cancel unit command ({'uids': ['unit.000000']})
agent_0.log:2017-12-03 18:00:20,592: agent_0             : MainProcess                     : agent_0.idler._agent_command_cb: INFO    : cancel unit cmd
```

**Comment by iparask** [comment]
```
Ioannis’s Mac pilot.0000$ grep 'cancel unit command' *.log
agent_0.executing.0.child.log:2017-12-03 19:29:33,251: agent_0.executing.0.child: agent_0.executing.0             : agent_0.executing.0.child.subscriber.command_cb: INFO    : cancel unit command ({'uids': ['unit.000000']})
Ioannis’s Mac pilot.0000$ grep 'cancel_units' *.log
agent_0.executing.0.child.log:2017-12-03 19:29:33,251: agent_0.executing.0.child: agent_0.executing.0             : agent_0.executing.0.child.subscriber._cancel_monitor_cb: DEBUG   : command ignored: cancel_units
agent_0.executing.0.child.log:2017-12-03 19:29:33,251: agent_0.executing.0.child: agent_0.executing.0             : agent_0.executing.0.child.subscriber.command_cb: INFO    : command_cb [control_pubsub]: {'cmd': 'cancel_units', 'arg': {'uids': ['unit.000000']}}
agent_0.scheduling.0.child.log:2017-12-03 19:29:33,251: agent_0.scheduling.0.child: agent_0.scheduling.0            : agent_0.scheduling.0.child.subscriber._cancel_monitor_cb: DEBUG   : command ignored: cancel_units
agent_0.staging.input.0.child.log:2017-12-03 19:29:33,251: agent_0.staging.input.0.child: agent_0.staging.input.0         : agent_0.staging.input.0.child.subscriber._cancel_monitor_cb: DEBUG   : command ignored: cancel_units
agent_0.staging.output.0.child.log:2017-12-03 19:29:33,251: agent_0.staging.output.0.child: agent_0.staging.output.0        : agent_0.staging.output.0.child.subscriber._cancel_monitor_cb: DEBUG   : command ignored: cancel_units
update.0.child.log:2017-12-03 19:29:33,251: update.0.child      : update.0                        : update.0.child.subscriber._cancel_monitor_cb: DEBUG   : command ignored: cancel_units
```
Is everything happening correctly?

**Comment by iparask** [comment]
Apparently, this is not an easy one. 

Andre's fix does indeed kill the process that is used to run the CU and thank you for taking care of it so fast! So, I consider the fix correct. 

Although, when a unit is in the `AGENT_EXECUTING` state a process is being launched based on the launch method we use to execute the actual workload. As a result, if a unit gets a cancellation command while executing, RP will terminate the process used to launch it, inform the scheduler that the cores are free, but the CU executable may not be canceled. During my discussion with Andre yesterday he told me that it is the application's responsibility to do what it wants when a `SIGKILL` is received. My question is how can I verify that it actually reached the launch method command and as a result the executable?

**Comment by andre-merzky** [comment]
That is tricky indeed.  I should be more precise also: we have to look at the combination of the launch command and the spawner.  The spawner in this case is `popen`, which is creating a subprocess.  That subprocess is defined by the launch method, and will in general be in a shell script - that shell script is what gets the signal.  The popen spawner actually does not attempt to kill the children of that script, which is likely the actual launch method.

We probably should change that to kill not only the shell script, but the process group of the shell - which then would also include the child processes.  I don't think the multiprocessing `popen` supports that - but `os.kill()` should, I'll check.

**Comment by andre-merzky** [comment]
I pushed a change to the PR - @iparask, can you give this a try please?

**Comment by iparask** [comment]
Yes sir!!! I added that for discussion! Thank you for taking care of it!

**Comment by iparask** [comment]
Closer, but not full solution. I tried it with the launch methods `FORK`, `SSH` and `MPIEXEC. Sending `SIGTERM` to the process group for `FORK` and `MPIEXEC` worked. This was not the case for `SSH`.

**Comment by andre-merzky** [comment]
Hmm, interesting.  I am actually not sure how ssh would handle that, not sure if that is well defined / documented.  

Unless you desperately need that for ssh, I would prefer not to work on this one right now though.  So, do you need that for the publication deadline? :)

**Comment by iparask** [comment]
No, I do not need it. That is why the labels are feature and optimization and not bug! I think that what fix/issue_1510 branch has right now, is okay for most cases.

I agree that `ssh` is a corner case. If I come up with something I will post it here! Thank you!

**Comment by andre-merzky** [comment]
Thanks!

**Comment by iparask** [comment]
I am back! I created a small python script that does:
```
import subprocess
import os
import time
import signal
stdoutF = open('stdout','w')
stderrF = open('stderr','w')
cu = dict()
cu['proc'] = subprocess.Popen(args='./unit.000000.sh',stdout=stdoutF,stderr=stderrF)
print cu['proc'].pid
time.sleep(120)
os.killpg(cu['proc'].pid,signal.SIGTERM)
print "Killed"
```

The important part of `unit.000000` is `/usr/local/bin/ibrun -n 64 -o 0 tacc_affinity lmp_micstam "-in" in.*`

When I run it at the end I get:
```
c455-033[knl](1013)$ python killing.py
227157
Traceback (most recent call last):
  File "killing.py", line 11, in <module>
    os.killpg(cu['proc'].pid,signal.SIGTERM)
OSError: [Errno 3] No such process
```

but `ps faux; grep unit.000000; ps faux | grep lmp_micstam`, I am getting:
```
tg824689 227833  0.0  0.0 116928  1068 pts/0    S+   18:15   0:00              \_ grep --color=auto unit.000000
tg824689 227157  0.0  0.0 117660  1800 ?        S    18:02   0:00 /bin/sh ./unit.000000.sh
tg824689 227835  0.0  0.0 116928  1056 pts/0    S+   18:15   0:00              \_ grep --color=auto lmp_micstam
tg824689 227188  0.0  0.0 117536  1804 ?        S    18:02   0:00  \_ /bin/bash /usr/local/bin/ibrun -n 64 -o 0 tacc_affinity lmp_micstam -in in.2_sim_new
tg824689 227248  0.0  0.0  22200  1668 ?        S    18:02   0:00      \_ /opt/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin/mpiexec.hydra -np 64 -machinefile /home1/03170/tg824689/.slurm/job.514477.hostlist.3a10FGxs /usr/local/bin/tacc_affinity lmp_micstam -in in.2_sim_new
tg824689 227253  0.0  0.0 117532  1696 ?        S    18:02   0:00              \_ /bin/bash /usr/local/bin/tacc_affinity lmp_micstam -in in.2_sim_new
tg824689 227610 99.7  0.1 1047048 118944 ?      Rl   18:02  12:31              |   \_ lmp_micstam -in in.2_sim_new
```

**Comment by iparask** [comment]
So the answer TACC gave me is that this way we are not getting the process group and thus we cannot correctly kill the processes. They proposed something like:

```
c455-072[knl](1007)$ ps xao uname,pid,ppid,pgid,sid,comm | grep sh
root       1621      2      0      0 kdmflush
root       2600      2      0      0 kdmflush
root       2603      2      0      0 kdmflush
root       2798      2      0      0 ipoib_flush
root       3022      1   3022   3022 sshd
root      71649   3022  71649  71649 sshd
tg824689  71680  71649  71649  71649 sshd
root      71681   3022  71681  71681 sshd
tg824689  71685  71680  71685  71685 bash
tg824689  71759  71681  71681  71681 sshd
tg824689  71762  71759  71762  71762 bash
root      71868   3022  71868  71868 sshd
tg824689  71870  71868  71868  71868 sshd
tg824689  71871  71870  71871  71871 bash
tg824689  73410  73396  73396  71685 unit.000000.sh
c455-072[knl](1008)$ kill -9 -73396
```

The problem with this solution, although it works, is that it kills the python interpreter as well. This will result in killing the component process.

I replicated the issue on comet as well. That being said we need to think of another way of canceling units.

**Comment by andre-merzky** [comment]
thanks Iannis.  Would you mind pasting the support reply verbatim? This is a point where I actually would want to argue with them...

**Comment by iparask** [comment]
Here it is:
```
Correspondence added by mclay 
You are not getting the right number for the group process id.

Try:

ps xao uname,pid,ppid,pgid,sid,comm | head

You want the pgid not ppid.

I hope this helps,
Robert.
```

**Comment by andre-merzky** [comment]
This is fixed in devel and about to be released.
