### ISSUE TITLE
Agent Input Staging Proposal

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1512]
Right now each actionable, e.i. each staging directive, is treated independently from any other. Although, it is usual practice to move multiple data from one unit to another. Treating each data movement as something separate instruction, thus doing multiple file movements at the same time resulting to multiple hits on the FS resulting sometimes in varying latencies.

I propose that an on-the-fly analysis on actionables. When multiple action require to move data from the same source to the same target, it can happen as a single instruction. Also to avoid the case where multiple small files are moved around, we can see whether or not creating an uncompressed tarball before any move or copy would make sense.

**Comment by iparask** [comment]
In addition, we can introduce magic characters in the source and target of the staging directive, like `*`, allowing the user to define staging of multiple files with some level of similarity to define only one staging directive.

**Comment by andre-merzky** [comment]
See #1513 as related issue.

Its probably not trivial to analyze staging directives and to bulk them on the fly - but I agree with the premise that many hits on a shared FS are costly.  I would propose to first measure the effect (out of band, in a shell script or so) on a known slow shared FS (like BlueWaters).

For the magic expansion, I would strongly suggest to stick with the shell conventions, and if possible to reuse Python's `glob` module.

**Comment by iparask** [comment]
Is `*` in file names a shell convention?

**Comment by andre-merzky** [comment]
> Is * in file names a shell convention?

Better: its defined by [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_13)

**Comment by itomaldonado** [comment]
Also, in Python we can use:

https://docs.python.org/2/library/glob.html#glob.glob

**Comment by andre-merzky** [comment]
Iannis, the glob part is somewhat orthogonal to the bulk transfer (via tarballs), so I'd say you should leave it out for the moment, and only focus on one of them.  I'll leave it to you both to judge if the on-the-fly analysis is useful in this context, or if you want to simply always tar on a certain number of staging directives per unit.  Or if you want to optimize across units.

Since this is essentially an optimization, a big part of your initial work will be to *measure* (not guess) what you want to optimize, and if the chosen approach is promising to improve performance.  Please do take that serious: I am not very open to see code complexity increase without documented benefits.

The ticket talks about the agent staging component and optimization of shared FS access.  Please consider (ie. measure) if that optimization would not be more useful on the remote transfer.  But I'll leave this to you to pick either the UMGR or the Agent components as implementation target.

**Comment by SrinivasMushnoori** [comment]
Hi Andre

The plan is as follows:
1) We change the `_handle_unit` method of the `agent/staging_input/default` class. 
2) We will use Python's tarfile [module](https://docs.python.org/2/library/tarfile.html)  to create the tarballs.
3) The algorithm is as follows: for every actionable that has the _same target directory,_ and the action is _either copy or move,_ we create a new list with all file names in the source directory of the unit, and those will be added to a tarball.  Now we create a new actionable for the tarball: _copy._ Next we remove all previous actionables for the files in the tarball from the list. Once the copy to the target directory is complete, untar the tarball and remove tarballs from source and destination, as well as any file that was tagged to be moved.
For transfers, assuming that the target is always the CU sandbox, all files that are tagged for transfer are tarred and moved through SAGA as a tarball. On the agent side, if there is a transfer actionable, we check if the transfer tarball exists. If it does, it is untarred.  The remainder of the algorithm is the same as above.

The agent staging component part of this ticket should be complete (i.e. implemented and tested) in the assigned time. We do not yet know what to expect for the remote staging: we do not know if the proposed solution is acceptable.  

-Srinivas and Giannis

**Comment by andre-merzky** [comment]
Hey Srinivas, thanks for the writeup!  Two questions:

- why do you limit the tar content to files which end up in the same directory?  tar is well able to pack files from multiple directories, and you get the `mkdir` for free on untar :)
- how do you untar?  The python tar module will only work for the local file system...

Well, and a note:
> ...assuming that the target is always the CU sandbox...
That is quite an assumption, isn't it?  Fortunately you can test it ;)

**Comment by iparask** [comment]
>- why do you limit the tar content to files which end up in the same directory?  tar is well able to pack files from multiple directories, and you get the `mkdir` for free on untar :)

I see. The idea is to change and remove some of the iterations this [loop](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/umgr/staging_input/default.py#L328). Let us discuss this a bit further.

>- how do you untar?  The python tar module will only work for the local file system...

Always untar at the agent side. There is a trade off that we should think. There should be a limit to the size of files that are included in the tar ball. I do not think trying to create a tarball of files GBs in size and moving that will benefit anyone. 

>>...assuming that the target is always the CU sandbox...

>That is quite an assumption, isn't it? Fortunately you can test it ;)

I do not think that using a CU input staging directive to stage data anywhere else is a good usage of the abstraction. This essentially means that the target in unit input staging should be `client:///`. Yes, a check might be needed, but in my opinion that should have already been there. The same assumption would be a very wrong assumption if we were discussing output staging.

**Comment by andre-merzky** [comment]
> Always untar at the agent side.

So, you intent to tar and transfer from the umgr stager, and to untar in the agent staging component?  How do you trigger that?

> I do not think trying to create a tarball of files GBs in size and moving that will benefit anyone.

Yeah, 256k should be enough for anybody... (I hope you recognize that quote, otherwise its not funny ;) )

> I do not think that using a CU input staging directive to stage data anywhere else is a good usage of the abstraction.

What we think about such a usage is somewhat beside the point - the semantics of the staging components is to execute whatever staging directive is thrown at them...

**Comment by iparask** [comment]
Initially, we add units that `rpc.TRANSFER` in the units with actionables. When that unit is being handled in [this statement](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/staging_input/default.py#L78) will be true. We check the tgt schema and we trigger it.

>Yeah, 256k should be enough for anybody... (I hope you recognize that quote, otherwise its not funny ;) )

Bill Gates! (I do not know my history, but Google does! :))

Okay for the third point.

**Comment by iparask** [comment]
The plan is as follows:

 1. Identify where transfer happens between client and agent
 2. Create a script that replicates RP's transfer.
 3. Run that script for different number of files (1 up to 2K) and different sizes( 512K up to 2MBs) and measure times.
 4. Do the same with tar and transferring.
 5. The last variable will be the network. We will this test using RADICAL VM 2 and a personal laptop connected to a wireless network like RU wireless. 
 6. Report our findings on Tuesday.

**Comment by andre-merzky** [comment]
That sounds reasonable to me, and I appreciate that the numbers are supported by a use case.  If you don't mind, can you please add `0 bytes` to the list of file sizes, ie. empty  files?  That should give you the contribution from all elements *but* the actual transfer.

**Comment by iparask** [comment]
1. Add a new action named `TARBALL`to the staging directives
2. Tarball name will `unit[uid]`
3. Make sure that lines 155-158 on the `Agent Staging Input Component` `default` class is needed.
4. Met with Manuel about testing protocols
5. Get testing link from Manuel
6.

**Comment by SrinivasMushnoori** [comment]
Update on test for tarball method on umgr side:
Test fails with
```
test_tarball (__main__.TestStagingInputComponent) ... ERROR

======================================================================
ERROR: test_tarball (__main__.TestStagingInputComponent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/RP_Master/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "test_tarball_umgr.py", line 133, in test_tarball
    component._handle_unit(self.unit, actionables)
  File "/home/scm177/VirtualEnvs/RP_Master/local/lib/python2.7/site-packages/radical/pilot/umgr/staging_input/default.py", line 319, in _handle_unit
    if key not in self._fs_cache:
AttributeError: 'Default' object has no attribute '_fs_cache'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
```
Test is at:
https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1512/tests/test_tarball_umgr.py

Test may need some cleaning up.

**Comment by SrinivasMushnoori** [comment]
Hi, we seem to have caught a bug in the Umgr side of the test: 

```
======================================================================
ERROR: test_tarball (__main__.TestStagingInputComponent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/RP_Master/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "test_tarball_umgr.py", line 136, in test_tarball
    component._handle_unit(self.unit, actionables)
  File "/home/scm177/VirtualEnvs/RP_Master/local/lib/python2.7/site-packages/radical/pilot/umgr/staging_input/default.py", line 371, in _handle_unit
    unit['description']['input_staging'].remove(sd)
KeyError: 'description'

----------------------------------------------------------------------
Ran 1 test in 0.394s

FAILED (errors=1)
```

Test is [here](https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1512/tests/test_tarball_umgr.py)

**Comment by iparask** [comment]
Yes, I found the reason. `UMGR` `_handle_unit` also expects the actionable to be in the unit description. I added that and made some changes in the test. The changes include:

 1. mocking the `os.remove` method so that it is not deleted as soon as the tarball is sent away. 
 2. checking if the tarball exists in the client folder.
 3. remove the tarball after assertion.

The test creates directories for pilot's and unit's sandboxes. Are these needed or are they left there from the agent side test?

**Comment by SrinivasMushnoori** [comment]
Yes they are from the agent side test. They should be removed, but before I do I want to check for sure if I'm accidentally using any of them in the umgr side test (I should not be).

**Comment by SrinivasMushnoori** [comment]
We need to also test the Agent side on at least one remote resource.

**Comment by andre-merzky** [comment]
This has been merged - thanks all!
