### ISSUE TITLE
Support the use of copying folders in agent input staging

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1513]
Can we replace the line:

```
 if   action == rpc.COPY: shutil.copyfile(src.path, tgt.path)
```

to the line:
```
 if   action == rpc.COPY: 
    try:
        shutil.copytree(src.path, tgt.path)
    except OSError as exc: # python >2.5
        if exc.errno == errno.ENOTDIR:
            shutil.copy(src.path, tgt.path)
        else: raise
```

This should handle both copy directories and individual files.

File/Line:

https://github.com/radical-cybertools/radical.pilot/blob/fb1120a4c858c67fd922c5e3541efecba41a8ffe/src/radical/pilot/agent/staging_input/default.py#L183

**Comment by jdakka** [comment]
Adding to this: 
`rpc.TRANSFER` to send files AND folders between remote machines.

**Comment by andre-merzky** [comment]
@itomaldonado : I agree with the gist of it - but I think exceptions should be used for exceptional (and usual erroneous) circumstances, not as part of the normal workflow (even though Python's philosophy somewhat encourages the latter).  So can we we either use a flag, or check the path with `os.path.isdir()`?  FWIW, flags are defined [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/constants.py#L60), and I would not mind adding a recursive flag to the default.

**Comment by andre-merzky** [comment]
@jdakka : also ack.  recursive data transfer is something where optimization is very useful, as this is always costly.  In other places in the code we create temporary tarballs to stage multiple data, and then unpack them on the target host (see [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L543).  We could consider generalizing this, or think of a different approach.  Or of course we could leave this to later and right now only care about the feature - but I wanted to mention it...

**Comment by itomaldonado** [comment]
@andre-merzky although I understand your point, I believe in this scenario Python's philosophy still stands. Checking the file with `os.path.isdir()` before calling the correct copy command *may* (in weird edge cases) cause issues. So an EAFP approach here makes sense.

Here is an example (for a slightly different problem although similar mechanism): https://docs.python.org/2/library/os.html#files-and-directories

**Comment by andre-merzky** [comment]
hehe - you guys will have fun discussing this :-P

**Comment by andre-merzky** [comment]
@jdakka : please move your proposal into a separate ticket, and assign yourself and Ming to it.  Thanks! :)

**Comment by jdakka** [comment]
created new [ticket](https://github.com/radical-cybertools/radical.pilot/issues/1514)

**Comment by andre-merzky** [comment]
This has been merged - thanks all!
