### ISSUE TITLE
Support recursive copy/transfer between remote machines

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1514]
@mingtaiha you've been summoned.

**Comment by jdakka** [comment]
3 ways of addressing transfer of folders:

1) `RP` layer: we modify the [`complete_url`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/staging_directives.py#L123) function. We pass the path and if it is a folder, perform `os.walk` to retrieve a list of files inside that folder. From, there we return `purl` as a `list()`. This will address the staging of folders in both StagingInput and StagingOutput components. But we are not sure if this function is being used elsewhere and would break that component.  

2) Another idea at `RP` layer if the above does not apply is to have the `os.walk()` inside the `_handle_units()` of the `ASIC` and `ASOC`. This would keep them local to these components and not affect any other components.

3) At the `saga` layer: we propose to change [`copy`](https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/namespace/directory.py#L329) with `os.walk` of `url_1` if it points to a folder. We create a `list()` of path names that point to the files in the folder. From there, we iterate through that list and [lines](https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/namespace/directory.py#L352-L354) would be iterated for each of those files.

**Comment by jdakka** [comment]
In SAGA, we are invoking the `RECURSIVE copy` flag and transferring a directory from local to `supermic`. However we notice that in `umgr.staging_input` the `recursive -r` command is not invoked as it should in this section of the [SAGA code](https://github.com/radical-cybertools/saga-python/blob/e68f3706fbe40531793f8a4c97934e6d2a39af9c/src/saga/adaptors/shell/shell_file.py#L515-L520). We checked to make sure that we are indeed invoking this `if` condition.

**Comment by georgeha** [comment]
We also checked from localhost -> localhost

**Comment by vivek-bala** [comment]
@georgeha to take a crack at creating a simple example using saga to reproduce the issue.

**Comment by vivek-bala** [comment]
We have added the component level test for USIC and integration tests for testing input data staging of files and folders.

@andre-merzky I do have a question regarding permissions in saga. I am reading from the rp config files [here](https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1514/tests/test_issue_1514/test_usic.py#L23-L24). So when it tries to create a folder in [line 55](https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1514/tests/test_issue_1514/test_usic.py#L55), I get a permission denied error (even on localhost). 

Error:
```
@SYNC_CALL
    def make_dir (self, tgt_in, flags):
    
        self._is_valid ()
    
        cwdurl = saga.Url (self.url) # deep copy
        tgt    = saga.Url (tgt_in)   # deep copy
    
        if  flags & saga.filesystem.EXCLUSIVE :
            # FIXME: this creates a race condition between testing for exclusive
            # mkdir and creating the dir.
            ret, out, _ = self._command (" test -d '%s' " % tgt.path)
    
            if  ret != 0 :
                raise saga.AlreadyExists ("make_dir target (%s) exists (%s)" \
                    % (tgt_in, out))
    
    
        options = ""
    
        if  flags & saga.filesystem.CREATE_PARENTS :
            ret, out, _ = self._command (" mkdir -p '%s'" % tgt.path, make_location=True)
        else :
            ret, out, _ = self._command (" mkdir '%s'" % tgt.path)
    
        if  ret != 0 :
>           raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out))
E           NoSuccess: make_dir ($HOME/radical.pilot.sandbox/rp.session.testing.local.0000/pilot.0000/staging_area) failed: mkdir: cannot create directory ‘$HOME’: Permission denied
E            (/home/vivek/Research/ves/test-issue-1514/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +768 (make_dir)  :  raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out)))
```

Not sure what I am missing, any flag? I tried with ```/tmp``` instead of ```$HOME``` on localhost which worked fine. Let me know.

Note: Some reorganization of all the tests is required. Should we come up with a folder structure for each test? If its already there, let us know please. Thanks

**Comment by andre-merzky** [comment]
I would think that `$HOME` is not getting expanded here.  Can you find out where the `$HOME` creeps in?

**Comment by vivek-bala** [comment]
The $HOME comes from the RP resource config file. I want to test against the same directory ("default_remote_workdir") as RP would plus we don't have to maintain different config files. I thought the environment variables are resolved in SAGA and not in RP? Is it possible to do that in SAGA?

**Comment by jdakka** [comment]
Included RP integration testing

**Comment by andre-merzky** [comment]
This has been merged - thanks all!
