### ISSUE TITLE
Execution disrupted due to import failure in virtualenv

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1520]
I am trying to have a python script execute using the titan_aprun configuration. It has started consistently, however the execution is halted in the compute unit. A virtualenv with the packages I try to use in the python script load in the unit script successfully. Looking at the stdout and stderr, and some of the other logs, I haven't been able to spot an indication of the failure point in these. 

I have tried to have the script print help("modules") just to see everything listed (as I can verify manually in the interpreter), however the execution stops here if I try this. The failing cu performs is performing a task that imports the adaptivemd package, so I have moved this import to previously working tasks that did not import the package. This causes a failure, so it just looks like there is a failure to import the package when the virtualenv is loaded in the cu vs. outside the cu. Like I mentioned, I haven't found any errors that are printed to troubleshoot this further. Is there any way to find out why it is not importing? Its unit 10 in the uploaded agent logs. Units 1-9 in this test executed as expected. 
[rp.session.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1557315/rp.session.tar.gz)
[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1557395/rp.agent.tar.gz)

**Comment by vivek-bala** [comment]
STDOUT
```
Import os
Import sys
/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/bin/python
['/lustre/atlas1/bip149/scratch/jrossyra/radical.pilot.sandbox/rp.session.titan-ext3.jrossyra.017513.0009/pilot.0000/unit.000010', '/lustre/atlas1/bip149/scratch/jrossyra/radical.pilot.sandbox/rp.session.titan-ext3.jrossyra.017513.0009/pilot.0000/staging_area', '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/globus_sdk-0.2.6-py2.7.egg', '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/requests-2.11.1-py2.7.egg', '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages', '/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages', '/sw/xk6/xalt/0.7.5/site', '/sw/xk6/xalt/0.7.5/libexec', '/opt/cray/sdb/1.1-1.0502.63652.4.27.gem/lib64/py', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python27.zip', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python2.7', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python2.7/plat-linux2', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python2.7/lib-tk', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python2.7/lib-old', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python2.7/lib-dynload', '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7', '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/plat-linux2', '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/lib-tk', '/lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv/lib/python2.7/site-packages', '/opt/cray/sdb/1.1-1.0502.63652.4.27.gem/lib64/py']
Imported importlib

Please wait a moment while I gather a list of all available modules...

Application 16448903 exit signals: Killed
Application 16448903 resources: utime ~2s, stime ~3s, Rss ~70984, inblocks ~37816, outblocks ~1668
```

Seems like it takes a while to run ```from adaptivemd.mongodb import ObjectJSON```? Can you import this module if you simply login to titan? How long does that take?

**Comment by jrossyra** [comment]
If I import in the interpreter or via aprun in interactive jobs it only takes a few seconds. The timestamps on the files show only about a minute went by between the unit files being created and the termination, but the job should have had about 15 minutes of walltime left.

**Comment by jrossyra** [comment]
Here are the logs for an execution where I have included the debug environment variables: 
`export RADICAL_SAGA_PTY_VERBOSE="DEBUG"`
`export RADICAL_VERBOSE="DEBUG"`

[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1635799/rp.agent.tar.gz)
[rp.client.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1635800/rp.client.tar.gz)

I also ran `radical-stack` to get the version information for what I'm working with.

```
(admdrpenv) [jrossyra@titan-ext2 /lustre/atlas/proj-shared/bip149/admdrp/runs/runs/test01]$ radical-stack
2018-01-16 10:37:07,393: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-01-16 10:37:07,393: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 12903
2018-01-16 10:37:07,393: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2018-01-16 10:37:07,393: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.47-v0.46-33-g3c75f23@devel
2018-01-16 10:37:07,436: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-01-16 10:37:07,436: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 12903
2018-01-16 10:37:07,436: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread

  python               : 2.7.9
  pythonpath           : /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas/proj-shared/bip149/jrossyra/admdrpenv

  radical.pilot        : 0.47.1
  radical.utils        : 0.47-v0.47-2-g8b9d4ec@devel
  saga                 : 0.47-v0.46-33-g3c75f23@devel

```

**Comment by andre-merzky** [comment]
Thanks for the logfiles, that helps!  It seems like RP is using pymongo version 3.x here.  Alas, the API has changed since 2.x, and at the moment we only support the older API.  Can you please downgrade pymongo via:

```
pip uninstall -y pymongo
pip install pymongo==2.8
```

Thanks, Andre.

**Comment by andre-merzky** [comment]
@jrossyra : Hey John, is that still something we should look into?

**Comment by jrossyra** [comment]
I think that @itomaldonado and I will give it an additional round of testing and inspection on the [[https://github.com/radical-cybertools/radical.pilot/tree/issue/1418]] branch, so I can report back when we have made the next run.

**Comment by andre-merzky** [comment]
Thanks for the updates!

**Comment by jrossyra** [comment]
Using the ORTE branch with all the changes in `projects/adaptivemd` fixed this.
