### ISSUE TITLE
silence profiler partially

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1521]
right now its all on / all off, but then we don't get even basic measure

**Comment by iparask** [comment]
This is a two year old feature request. I think this will be nice to have for version 2, but I do not think it is critical at least for now.

**Comment by andre-merzky** [comment]
Agree.  if anybody ever ends up with multi-GB profiles, we can pick this up again.  I don't think that will ever happen though, right @iparask  ;-)

**Comment by mturilli** [comment]
I think this is still relevant and probably even more so now that we routinely run very large workloads/pilots. Should we put it on the development roadmap?

**Comment by andre-merzky** [comment]
All components have a profiler and logger created in the component base class, and are distingushed by the component names. For example, the component `agent_scheduler` has the config env variables:
```
RADICAL_PILOT_AGENT_SCHEDULER_LOG_LVL
RADICAL_PILOT_AGENT_SCHEDULER_LOG_TGT
RADICAL_PILOT_AGENT_SCHEDULER_PROFILE
```
(also `RADICAL_PILOT_AGENT_SCHEDULER_REPORTER` btw, but only the API layer uses the reporter right now).

**Comment by mturilli** [comment]
Related to https://github.com/radical-cybertools/radical.pilot/discussions/2408

**Comment by andre-merzky** [comment]
Closing as outdated and partially implemented (see above)
