### ISSUE TITLE
ORTE fails on Wrangler

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1524]
I am getting this error:

```
agent_0.log:2017-12-19 19:16:24,671: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [c251-101.wrangler.tacc.utexas.edu:86616] [[43275,0],0] ORTE_ERROR_LOG: Bad parameter in file /home/03170/tg824689/ompi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
```

The units finish correctly.

**Comment by andre-merzky** [comment]
Unfortunately, we do observe ORTE DVM errors from time to time.  Unless this can be reliably reproduced, I don't think there is much we can do about it at this point...  So, can it?

**Comment by iparask** [comment]
Yes, it is reproducible on Wrangler.

**Comment by iparask** [comment]
And apparently, it does not like hyperthreading. I think it is time to start thinking updating the confs with the correct cores per node.
