### ISSUE TITLE
v0.47 does not create exec_start and exec_stop events for every run

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1526]
Some initial information can be found [here](https://github.com/radical-cybertools/radical.analytics/issues/37). In addition I have the same issue with runs also on Wrangler not only Comet.

As I understand it these events show the starting and ending point of a unit's execution. I believe that these events should always be there for every unit.

How can we debug this? It is very important that I know the execution time of each unit.

**Comment by andre-merzky** [comment]
This turned out to be a download problem, not a profiling problem (fortunately...)
