### ISSUE TITLE
GPU example is failing with permission issue

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1530]
The GPU example under radical.pilot/examples/misc is failing due to permission issue:
```
/bin/sh: /lustre/atlas/scratch/merzky1/csc230/radical.pilot.sandbox/09_mpi_units.sh: Permission denied
```

Not critical obviously, just want to keep it tracked.

**Comment by andre-merzky** [comment]
This example should  probably be folded into `examples/09_mpi_units.py` which stages the test script on the fly...

**Comment by iparask** [comment]
`09_mpi_units.sh` is moved in the examples folder. This is not relevant anymore. I'm closing this issue.
