### ISSUE TITLE
Unit stuck at UMGR output staging pending 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1531]
Opening ticket for HTBAC: 
Stack (running on the granddaddy Blue Waters): 

```
radical.pilot        : 0.47-v0.46.2-196-ga4819118@devel
radical.utils        : 0.47-v0.47-2-g8b9d4ec@devel
saga                 : 0.47-v0.46-33-g3c75f23a@devel
entk (experiments/jdakka-resubmission)
```
Last units (150/151) moves to ```umgr.0000.staging.input.0.child.log:2018-01-15 11:17:52,111: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : DEBUG   : drop  unit.000151 [AGENT_STAGING_INPUT_PENDING]``` but does not continue past this stage. 

Client files are attached.

[adaptive_run_improper_termination.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1640384/adaptive_run_improper_termination.tgz.zip)

Remote path: 

`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017546.0003/pilot.0000`

Eventually I had to improperly terminate the run because the unit was getting stuck. On the client side the`DEBUG` mode is set for `EnTK`. You can trace the activity in debug.log

**Comment by jdakka** [comment]
Running another run to verify (was stuck in queue for > 48 hours). It's at hour 8 currently, even though the application finished. I set the wall-time to 12 hours.

**Comment by jdakka** [comment]
Hey Andre, sorry was out of office. Yes I can confirm that this happens for EnTK applications that implement adaptivity i.e. we keep the pilot alive but resubmit a new workflow. 
[data_run_hanging.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1652333/data_run_hanging.tgz.zip)

Here is an additional run that finished but also didn't terminate properly.

**Comment by jdakka** [comment]
[data_run_hanging.zip](https://github.com/radical-cybertools/radical.pilot/files/1656189/data_run_hanging.zip)
recompressing in case this doesn't open

**Comment by andre-merzky** [comment]
Jumana - do you happen to have the json file, too?

@vivek-bala: the pilot dies, the respective callback is called.  Can I see somewhere in the entk log if and how reacts on the  pilot's termination?

**Comment by vivek-bala** [comment]
Hmmm. Upon pilot termination, are the units marked FAILED or CANCELED? The callback in EnTK waits for tasks to reach DONE or FAILED.

**Comment by andre-merzky** [comment]
For this specific run, all units are DONE:
```
$ grep advance *prof | grep unit | grep -e FAILED -e DONE -e CANCELED | cut -f 6 -d ,  | sort | uniq -c
     91 DONE
```

**Comment by vivek-bala** [comment]
There are 92 units in total IIUC. You can see unit.00000 to unit.000091 in the [sandbox](/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017549.0005/pilot.0000/).

```
$ grep advance *prof | grep unit | grep -e FAILED -e DONE -e CANCELED -e UMGR_STAGING_OUTPUT | cut -f 6 -d ,  | sort | uniq -c
     91 DONE
     92 UMGR_STAGING_OUTPUT
```

So the last unit doesn't reach DONE or FAILED or CANCELED. EnTK waits for the 92nd unit to reach DONE or FAILED.

**Comment by vivek-bala** [comment]
Upon pilot termination, the state of the unit should reach either DONE or FAILED or CANCELED. Right?

**Comment by andre-merzky** [comment]
Yes,we do not yet attempt to resubmit to a different pilot - so once they passed UMGR_STAGING, they will get finalized once the pilot is gone.  Units should go into CANCELED if they are  not in any other final state at that point.

**Comment by andre-merzky** [comment]
Actually... - let me check if that code path is really active - I'll ping back...

**Comment by iparask** [comment]
@andre-merzky, any news on this?

**Comment by andre-merzky** [comment]
I think it's fair to assume  that this is [not implemented](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/umgr/scheduler/round_robin.py#L68)

**Comment by mturilli** [comment]
This seems relevant and we may want to check whether it might explain some of the terminating behavior we recently observed.

**Comment by mturilli** [comment]
@lee212 do you think this would be worth a test to determine whether it still affects EnTK?
