### ISSUE TITLE
gpu example on titan

### ISSUE THREAD

**Issue by mpbl** [radical-cybertools/radical.pilot#1532]
Hi, 

I am running into an issue for the  https://github.com/radical-cybertools/radical.pilot/blob/feature/gpu/examples/misc/gpu_pilot.py example on the feature/gpu branch.

[gpu_example_titan_log.zip](https://github.com/radical-cybertools/radical.pilot/files/1640425/gpu_example_titan_log.zip)

Attached are the client-side logs. No agent logs have been outputted.

Any idea of why I'm running into this issue?

Best,
Matthieu

**Comment by andre-merzky** [comment]
The error is in  logged in `pmgr.0000.launching.0.child.log`:

```
2018-01-17 14:52:51,986: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/ccs/home/mpbl/miniconda2/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 487, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/ccs/home/mpbl/miniconda2/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 602, in _start_pilot_bulk
    out = sp.check_output(["/bin/sh", "-c", cmd], stderr=sp.STDOUT)
  File "/ccs/home/mpbl/miniconda2/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/bin/sh', '-c', 'cd /tmp/rp_agent_tar_dir6aeE7V && tar zchf /tmp/rp_agent_tar_dir6aeE7V/rp.session.titan-ext7.mpbl.017548.0004.pmgr.0000.launching.0.child.tgz *']' returned non-zero exit status 2
```

Alas, the logfiles don't log the error message from that command (I'll fix that), so I am not sure what's up there.  Would you mind doing a retry?  I don't think this is related to the GPU branch itself...

**Comment by andre-merzky** [comment]
Please  update RP from the `feature/gpu` branch: the command should should get logged now.  Thanks!

**Comment by mpbl** [comment]
Hi, Andre,

Many thanks for your help! Here are the new logs:
[gpu_example_titan_log.zip](https://github.com/radical-cybertools/radical.pilot/files/1640772/gpu_example_titan_log.zip)

This comes from the ```python gpu_pilot.py ornl.titan_aprun``` command. I forgot to specify the resource name the last time.

Matthieu

**Comment by mpbl** [comment]
Hi, Andre,

I was a bit disappointed by Vivek being able to run and not me. I re-created a fresh environment and... it's running and produces the agent log. 

Sorry for the noise, I'll close the issue; and thanks again for looking into this.

Matthieu

**Comment by andre-merzky** [comment]
No worries - I am glad it was not more serious! :-)
