### ISSUE TITLE
Functionality/to open discussion for office hours (friday): Partial ordering of tasks 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1535]
This is in reference to the Ensemble of Pipelines pattern in EnTK. In the event that we submit multiple `pipelines` in EnTK, we notice an inconsistency in the execution order and the submission order. EnTK submits tasks in a particular order that is in agreement with the synchronization barriers handled by the `stage(s)` component. However when these ordered tasks are submitted to RP (which translates the `Tasks` to CUs in a `set()`), we lose the initial ordering of tasks. In turn certain pipelines compete for resources and finish well before other pipelines even begin to execute.

**Comment by jdakka** [comment]
@andre-merzky I've created an HTBAC script to test this feature, using `devel` in `RS/RU` and `devel` in `EnTK`.

**Comment by andre-merzky** [comment]
Sooo, does it work? :-)

**Comment by jdakka** [comment]
It works apart from a hanging `rabbitmq`

[rabbit_mq_hangup.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1717076/rabbit_mq_hangup.tgz.zip)

**Comment by andre-merzky** [comment]
So,  if that behaves as expected, and the remaining problems are confined to  RabbitMQ, ie. to the EnTK layer, can the fifo scheduler then be merged, or is there additional work needed (in RP) to serve this use case?

**Comment by jdakka** [comment]
@vivek-bala @andre-merzky I indeed verify that I can run two concurrent EnTK pipelines and the performance is as expected using feature/FIFO

**Comment by iparask** [comment]
This is resolved!
