### ISSUE TITLE
Create branch to contain AdaptiveMD fixes

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1545]
@itomaldonado @mturilli Since there are a few issues that need to be fixed simultaneously for executing AdaptiveMD workflows via radical pilot, I just wanted to suggest that we have a branch dedicated to these changes. I wanted to mention that the branches `fix/issue_1538` and `issue/1418` (I think based from the most current orte branch) contain the relevant changes we've worked on.

**Comment by jrossyra** [comment]
I just wanted to ping on this again and check if you think this is a good idea to consolidate all the fixes we end up doing for AdaptiveMD, and what the time frame would be for merging these branches. I also wanted to mention we are currently held up by #1538 , so this branch could contain any further fixes for that issue.

**Comment by itomaldonado** [comment]
As discussed, I created the branch `project/adaptivemd` on radical.utls, saga-python and radical.pilot.

I have already merged the `issue/1418` changes so it is ready for testing!

Please let me know @jrossyra

**Comment by jrossyra** [comment]
Branch is made, though we have troubleshooting to do #1565
