### ISSUE TITLE
document `complete_url()` method

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1548]

**Comment by iparask** [comment]
@andre-merzky , which RP component is this method from? Also, if you have already documented it, it can be closed!

**Comment by andre-merzky** [comment]
It is defined [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/staging_directives.py#L134).  The code is documented, but it does not appear in the developer documentation.  Should it?

**Comment by iparask** [comment]
No, I do not think so. The doctoring should be enough if there is a developer that requires it at some point we can move it in the documentation.
