### ISSUE TITLE
Get RP running on NCAR Cheyenne

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1551]
Our collaborators want to run their applications on Cheyenne. See ticket https://github.com/radical-collaboration/hpc-workflows/issues/28.

A config file has been added for cheyenne under resource_ncar.json in the feature/cheyenne branch. Pending instructions to create a static VE on cheyenne (if required), need to confirm with Andre.

**Comment by vivek-bala** [comment]
We have a list of notes and questions at https://docs.google.com/document/d/1p4DbM2ABxqv308C1mi8mYNzEe7iWMxLFTrJ9cwJsdew/edit?usp=sharing. If everyone is okay with the list of questions, we can send it over to cheyenne sys admins/ user support.

**Comment by mturilli** [comment]
Edited and ready to go for me.

**Comment by vivek-bala** [comment]
As a first, requires the following:

* Tunneling through the head node on Cheyenne
* New launch method https://github.com/radical-cybertools/radical.pilot/issues/1552

**Comment by vivek-bala** [comment]
Also, I sent the confirmation that we are using the head node as a starting point. They recommended again checking the memory usage and comparing with allowed memory usage as detailed at https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/checking-memory-use

**Comment by vivek-bala** [comment]
Confirmed: No system limitation on number of concurrent mpirun or mpiexec_mpt  jobs

**Comment by vivek-bala** [comment]
Blocked by #1552

**Comment by mturilli** [comment]
Ping

**Comment by iparask** [comment]
@vivek-bala is this still blocking your collaborators?

**Comment by mturilli** [comment]
Done.
