### ISSUE TITLE
Need support for mpiexec_mpt dplace launch method

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1552]
mpiexec_mpt dplace is the launch method on NCAR Cheyenne

Example PBS script: https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs

This issue is blocking #1551

**Comment by mturilli** [comment]
Possibly also useful: https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs/omplace-and-dplace

**Comment by andre-merzky** [comment]
That page is a nice find, thank you!  And yes, using `omplace` seems like the right thing to do in this case.

side note: right now, we create a new launch method for each placement command combination, so we have a new LM for `mpirun+dplace`, `mpirun_mpt+dplace`, 'mpiexec+dplace`, `mpirun+omplace` etc etc.  That is ugly, and should be replaced by a more generic LM which can be configured by mpi flavor and placement script flavor.  But since all flavors are slightly (or sometimes not so slightly) different  in syntax and semantics, its not a trivial exercise either...  Cheyenne support with its different options might be a good place to get this topic back on the table?  Well, maybe not,  given the timelines...

**Comment by mturilli** [comment]
I would separate three issues:
- Supporting the first API launching method on Cheyenne: which one? (priority: critical)
- Supporting further launching methods for Cheyenne if needed by the use case(s) (priority: normal)
- Developing new configuration system for launching methods (priority: low)

**Comment by andre-merzky** [comment]
The launch method support has been added in the `feature/cheyenne` branch, and also a resource config entry.  What is missing is the location of a static virtualenv which we likely have to create there.  Vivek, will you take care of this?  The script at `https://raw.githubusercontent.com/radical-cybertools/radical.pilot/e849fcf33b3b7d6b50976507d60e4613b1002fbe/bin/radicalpilot-create-static-ve` should do the trick.

**Comment by vivek-bala** [comment]
Yes, I'll try it out and get back to you.

**Comment by vivek-bala** [comment]
I updated the branch with some fixes. I tried the 01_unit_details.py example. I got the following error: https://gist.github.com/vivek-bala/edb3d085595f663f063bb8424c86dd79.

There unit folders created in the sandbox but no log files.
```
vivekb@cheyenne2:/glade/scratch/vivekb/radical.pilot.sandbox> cd rp.session.cheyenne1.vivekb.017575.0011/
vivekb@cheyenne2:/glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011> ls
bootstrap_1.sh	pilot.0000						     radical.utils-0.47.tar.gz						      rp.session.cheyenne1.vivekb.017575.0011.umgr.0000.staging.input.0.child.tgz
cacert.pem.gz	radical.pilot-0.47-0.47-18-gae23b6f-feature-cheyenne.tar.gz  rp.session.cheyenne1.vivekb.017575.0011.pmgr.0000.launching.0.child.tgz  saga-python-0.47-v0.46-39-g1f94a36-feature-cheyenne.tar.gz
vivekb@cheyenne2:/glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011> cd pilot.0000/
vivekb@cheyenne2:/glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/pilot.0000> ls
agent_0.cfg	    unit.000006  unit.000014  unit.000022  unit.000030	unit.000038  unit.000046  unit.000054  unit.000062  unit.000070  unit.000078  unit.000086  unit.000094	unit.000102  unit.000110  unit.000118  unit.000126
pilot.0000.log.tgz  unit.000007  unit.000015  unit.000023  unit.000031	unit.000039  unit.000047  unit.000055  unit.000063  unit.000071  unit.000079  unit.000087  unit.000095	unit.000103  unit.000111  unit.000119  unit.000127
unit.000000	    unit.000008  unit.000016  unit.000024  unit.000032	unit.000040  unit.000048  unit.000056  unit.000064  unit.000072  unit.000080  unit.000088  unit.000096	unit.000104  unit.000112  unit.000120
unit.000001	    unit.000009  unit.000017  unit.000025  unit.000033	unit.000041  unit.000049  unit.000057  unit.000065  unit.000073  unit.000081  unit.000089  unit.000097	unit.000105  unit.000113  unit.000121
unit.000002	    unit.000010  unit.000018  unit.000026  unit.000034	unit.000042  unit.000050  unit.000058  unit.000066  unit.000074  unit.000082  unit.000090  unit.000098	unit.000106  unit.000114  unit.000122
unit.000003	    unit.000011  unit.000019  unit.000027  unit.000035	unit.000043  unit.000051  unit.000059  unit.000067  unit.000075  unit.000083  unit.000091  unit.000099	unit.000107  unit.000115  unit.000123
unit.000004	    unit.000012  unit.000020  unit.000028  unit.000036	unit.000044  unit.000052  unit.000060  unit.000068  unit.000076  unit.000084  unit.000092  unit.000100	unit.000108  unit.000116  unit.000124
unit.000005	    unit.000013  unit.000021  unit.000029  unit.000037	unit.000045  unit.000053  unit.000061  unit.000069  unit.000077  unit.000085  unit.000093  unit.000101	unit.000109  unit.000117  unit.000125
```

Let me know how we can debug further.

**Comment by andre-merzky** [comment]
Also, please try another run with only 8 units.  That should work around the error above (which needs fixing though), so that we can see how the rest of the stack holds up right now.

**Comment by vivek-bala** [comment]
Attached (tar converted to zip)
[rp.session.cheyenne1.vivekb.017575.0011.umgr.0000.staging.input.0.child.zip](https://github.com/radical-cybertools/radical.pilot/files/1724564/rp.session.cheyenne1.vivekb.017575.0011.umgr.0000.staging.input.0.child.zip)


Running the commands:

```
vivekb@cheyenne6:~> export TARBALL="/glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/rp.session.cheyenne1.vivekb.017575.0011.umgr.0000.staging.input.0.child.tgz"
vivekb@cheyenne6:~> tar --version
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
Written by John Gilmore and Jay Fenlason.
vivekb@cheyenne6:~> tar zmxvf $TARBALL  -C /
glade/
...
[shortened]
glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/pilot.0000/unit.000035/
glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/pilot.0000/unit.000095/
glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/pilot.0000/unit.000011/
tar: glade/scratch: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
```

```
vivekb@cheyenne6:~> tar zxvf $TARBALL  -C /
glade/
...
[shortened]
glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/pilot.0000/unit.000095/
glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne1.vivekb.017575.0011/pilot.0000/unit.000011/
tar: glade/scratch: Cannot utime: Operation not permitted
tar: glade/scratch: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: glade: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
```


Will run it with 8 units but not sure how that will resolve the permission issue though.

**Comment by vivek-bala** [comment]
With 8 units, the logs look different (?!): https://gist.github.com/vivek-bala/e5540c4d8337d207680aa4e4295af619

Also the unit folders are not created. See session sandbox structure:
```
vivekb@cheyenne3:/glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne6.vivekb.017576.0001> ls -l
total 3072
-rwxr-xr-x 1 vivekb ncar   62637 Feb 14 08:36 bootstrap_1.sh
-rw-r--r-- 1 vivekb ncar  140031 Feb 14 08:36 cacert.pem.gz
drwxr-xr-x 2 vivekb ncar    4096 Feb 14 08:36 pilot.0000
-rw-r--r-- 1 vivekb ncar  438575 Feb 14 08:36 radical.pilot-0.47-0.47-18-gae23b6f-feature-cheyenne.tar.gz
-rw-r--r-- 1 vivekb ncar  142405 Feb 14 08:36 radical.utils-0.47.tar.gz
-rw-r--r-- 1 vivekb ncar 1187134 Feb 14 08:36 rp.session.cheyenne6.vivekb.017576.0001.pmgr.0000.launching.0.child.tgz
-rw-r--r-- 1 vivekb ncar  445498 Feb 14 08:36 saga-python-0.47-v0.46-39-g1f94a36-feature-cheyenne.tar.gz
vivekb@cheyenne3:/glade/scratch/vivekb/radical.pilot.sandbox/rp.session.cheyenne6.vivekb.017576.0001> ls -l pilot.0000/
total 256
-rw------- 1 vivekb ncar 4556 Feb 14 08:36 agent_0.cfg
-rw-r--r-- 1 vivekb ncar    0 Feb 14 08:36 pilot.0000.log.tgz
```

**Comment by andre-merzky** [comment]
Using 8 units will not trigger the unit sandbox create optimization, which is what tripped you earlier.

Alas, the gist you linked is insufficient to say whats up in this configuration - please attach client and agent sandbox.  Also, please do try to run the untar manually, to understand whats up with that - we'll need that for larger number of CUs...

**Comment by andre-merzky** [comment]
Sorry - I missed that you added the tar test above!  Am I reading this right that the unit sandboxes all get extracted before the error pops up?  If so, then a quick workaround is to ignore the error (there is nothing else in the tarball than the sandboxes).   The clean fix is likely to keep the paths relative to the pilot sandbox in the first place, that will take a little more time.

So please stick with 8 units for the time being.

I'll have to read up on tar and posix to check if its worth opening a system ticket.

**Comment by vivek-bala** [comment]
The tar attempts I made above are with 128 units. With 8 units, I don't have that tarball any more. See the agent and client sandboxes.

[rp.session.cheyenne6.vivekb.017576.0001.agent.zip](https://github.com/radical-cybertools/radical.pilot/files/1724833/rp.session.cheyenne6.vivekb.017576.0001.agent.zip)
[rp.session.cheyenne6.vivekb.017576.0001.client.zip](https://github.com/radical-cybertools/radical.pilot/files/1724834/rp.session.cheyenne6.vivekb.017576.0001.client.zip)


Note the error in the pmgr launcher:
```
2018-02-14 08:36:52,265: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 487, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 672, in _start_pilot_bulk
    js = rs.job.Service(js_ep, session=self._session)
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/base.py", line 104, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 543, in init_instance
    self.initialize()
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 601, in initialize
    log_error_and_raise(message, saga.NoSuccess, self._logger)
  File "/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 116, in log_error_and_raise
    raise exception(message)
NoSuccess: Error running pbsnodes:  (/glade/u/home/vivekb/ves/test-rp/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py +116 (log_error_and_raise)  :  raise exception(message))
```

**Comment by vivek-bala** [comment]
The error seems to come from the SAGA layer but the SAGA verbose messages didn't particularly point to anything (referring to the same logs as above - https://gist.github.com/vivek-bala/e5540c4d8337d207680aa4e4295af619).

**Comment by mturilli** [comment]
For the tar issue, try seeing: https://superuser.com/questions/699225/avoid-errors-from-tar-failing-to-restore-directory-permissions

**Comment by andre-merzky** [comment]
Yeah, `--no-overwrite-dir` would solve this - but its not posix, and I'll try to stick to that where possible.  But you are also right that the perm collision with the parent dirs creates the issue.  Its too tedious to tune that juuuuust right - I'll switch to the relative paths... 
Thanks! :-)

**Comment by andre-merzky** [comment]
I think I have no access to Cheyenne, yet - is that something which could be arranged w/o too much overhead?  That would speed up testing and development a lot.  For example, I need to search the system for a tool equivalent to `pbsnodes`, so that the SAGA adaptor can learn about the node layout, and also would like to run some interactive tests with `mpirun_mpt dplace` to check out combinations of the command line flags...

**Comment by andre-merzky** [comment]
This is implemented
