### ISSUE TITLE
GPU stack incompatibility

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1556]
[client_files.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1699402/client_files.tgz.zip)
[rp.session.titan-ext4.jdakka.017568.0001.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1699403/rp.session.titan-ext4.jdakka.017568.0001.tgz.zip)

Running an HTBAC script on Titan using the `feature/gpu` RP branch 

The bootstrapper gives an error on compatibility issues specifically for `radical.utils` branch:

```
rm: cannot remove `./radical.pilot-0.47-0.47-118-gf66e2f6-feature-gpu.tar.gz': No such file or directory
ERROR: local RP install needs sdist based install (not 'radical.utils-0.47-v0.47-4-gcca43d5-devel/')
```

* radical-stack: 
```
python               : 2.7.9
pythonpath           : /sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
virtualenv           : /autofs/nccs-svm1_home1/jdakka/htbac/venv

radical.pilot        : 0.47-0.47-118-gf66e2f6@feature-gpu
radical.utils        : 0.47-v0.47-4-gcca43d5@devel
saga                 : 0.47-v0.46-53-gb342c0c@feature-gpu
```

**Comment by jdakka** [comment]
I tried with the `master` branch instead. I see units are created but I get another error: 
`Request invalid for state of job MSG=invalid state for job - COMPLETE 3866273.titan-moab.ccs.ornl.gov`
[master_bad_data.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1715133/master_bad_data.tgz.zip)
[rp.session.titan-ext5.jdakka.017572.0004.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1715134/rp.session.titan-ext5.jdakka.017572.0004.tgz.zip)

**Comment by shantenujha** [comment]
@jdakka, @vivek-bala Isn't there an advertised (= recommended) version of EnTK that works on Titan, so that users of EnTK don't have to worry about "abstractions" below EnTK viz., RP version?

**Comment by andre-merzky** [comment]
This is likely the same problem as #1529 - I am still not sure what triggered this, likely an environment change on Titan...

**Comment by jdakka** [comment]
@shantenujha I capture the "right" stack with `--dependency links` when the user installs via pip. I did this for Blue Waters, we're are still trying to find the "right" stack on `Titan`.

**Comment by vivek-bala** [comment]
@shantenujha In both EnTK and RP, we had a gpu and non-gpu version. The errors over the last few days seem to suggest that both are failing and likely fix would be lower down in the stack. Note that the ompi dist seems to have been changed (since it got purged - #1529).

**Comment by shantenujha** [comment]
@all requesting a status update as this has brought UCL's work on Titan to a halt.

**Comment by jdakka** [comment]
We have a working stack with RCT `devel` that can execute ESMACS protocols using `cpu/gpu` hybrid execution.
