### ISSUE TITLE
`SKIP_FAILED` is defined, but not implemented

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1557]
it should go, or at least not be set by default.

**Comment by vivek-bala** [comment]
I remember this old issue #1106. The idea behind it was to ignore data staging that fails and continue with unit execution. But the flag created for this was 'NONFATAL'. Maybe there is some overlap between the two? I am not sure what 'SKIP_FAILED' is meant to do.

**Comment by andre-merzky** [comment]
Yeah, its likely related to that ticket - but as said, I don't see that flag being evaluated anywhere right now.  Is this still a valid use case?

**Comment by vivek-bala** [comment]
I haven't use 'skip_failed', so not sure. I have used 'nonfatal' in the past and consider it useful, so would recommend keeping 'nonfatal'.

**Comment by andre-merzky** [comment]
I don't see that flag evaluated anywhere either - I doubt it works... :/

**Comment by iparask** [comment]
@andre-merzky, @vivek-bala Is this use case still valid?

**Comment by vivek-bala** [comment]
I don't think so, no.

**Comment by iparask** [comment]
I'm closing as not needed any more.

**Comment by andre-merzky** [comment]
If it is not needed, the flag and its documentation should be removed...
