### ISSUE TITLE
pilot sandbox is incorrect on titan

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1559]
See @jdakka's logs in #1529 .

Jumana, can you please run again with:

```
export RADICAL_SAGA_PTY_VERBOSE=DEBUG
export RADICAL_SAGA_PTY_LOG_TGT=pty.log
```

and attach the  *client* sandbox and the resulting pty.log?  Thanks!

**Comment by jdakka** [comment]
Running `01_unit_details.py`
[example_01.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1722041/example_01.tgz.zip)

**Comment by andre-merzky** [comment]
Wait, you are using the resource label `local.localhost` here I think - that should be `ornl.titan_orte` I think?

**Comment by jdakka** [comment]
Apologies, ran the same example with `titan.orte`
[example_01_titan_orte.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1731824/example_01_titan_orte.tgz.zip)

**Comment by andre-merzky** [comment]
Thanks Jumana!   I know I asked only for the client logs - but can you please add the agent logs, too, after all?  Thank you!

**Comment by jdakka** [comment]
Agent logs!
[rp.session.titan-ext2.jdakka.017578.0001.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1737417/rp.session.titan-ext2.jdakka.017578.0001.tgz.zip)

**Comment by andre-merzky** [comment]
This is a duplicate of #1568 - Jumana, can we keep one of these tickets closed, please? :-)

**Comment by jdakka** [comment]
Now it makes sense! We can close this one then!
