### ISSUE TITLE
compute unit property unit_sandbox does not return ru.Url()

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1563]
It currently returns a string and not a Url object

https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_unit.py#L368

**Comment by andre-merzky** [comment]
Hmpf, this needs discussion of types in the API in general, as the API is inconsistent here: pilot sandbox is defined as string,  unit sandbox as Url :/

**Comment by vivek-bala** [comment]
I agree. Another one: unit.sandbox and unit.unit_sandbox. Both return the same string currently.

**Comment by iparask** [comment]
It now returns a `ru.Url`. This is resolved.
