### ISSUE TITLE
STDOUT/STDERR not available in agent sandbox

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1564]
I am trying to look up the `aprun` noise and application timestamps that are printed in the logs of the `STDOUT/STDERR` files. However I noticed that those files are missing from my `unit.00*` folders. 

Can you take a look and explain why this occurs? This experiment used the `master` branch of `RP` on Blue Waters: 

`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017530.0028/pilot.0000`

**Comment by andre-merzky** [comment]
Hmm, there are no logfiles in the pilot sandbox either.  I am not sure what's up with that session, sorry :(

**Comment by mturilli** [comment]
Can we put together a test so to be sure these files are created? Ideally, this would test both profile creation (when enabled) and STD* creation?

**Comment by andre-merzky** [comment]
Jumana, can you please check for `ERROR` entries in the client side logs?

**Comment by mturilli** [comment]
Is this ticket still current? @jdakka did you see this issue with your latest runs?

**Comment by jdakka** [comment]
I checked my latest runs on BW, the runs all contain `STDOUT/STDERR` logs in all units.
