### ISSUE TITLE
Agent cannot find VE on Titan

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1568]
Running an HTBAC workload. Error in `bootstrap_1.out` 

`tar (child): ./radical.utils-0.47-v0.47-3-g18dab2b-master.tar.gz: Cannot open: No such file or directory`

Agent logs: 

[rp.session.titan-ext7.jdakka.017585.0002.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1753470/rp.session.titan-ext7.jdakka.017585.0002.tgz.zip)

Stack: 

```
virtualenv           : /lustre/atlas2/chm126/scratch/jdakka/venv

  radical.pilot        : 0.47-0.47@master
  radical.utils        : 0.47.1
  saga                 : 0.47-v0.46-34-g0f186f66@master
```

**Comment by andre-merzky** [comment]
This is a duplicate of #1556.

**Comment by jdakka** [comment]
The `bootstrap.out` file sets PWD as `PWD=/lustre/atlas/scratch/jdakka/chm126` and thereby it cannot find `./radical.utils-0.47.1-v0.47.1-4-g7f65216-devel.tar.gz: Cannot open: No such file or directory`. 

FYI in MEMBERWORK I only have access to `chm126` 

Based on @itomaldonado he has access to `chm126` and `csc190`. His `bootstrap.out` PWD shows `PWD=/lustre/atlas/scratch/itoman/csc190/radical.pilot.sandbox/rp.session.titan-ext1.itoman.017588.0014/pilot.0000` 

1. Even though @itomaldonado specified project `chm126` it still rerouted the `radical.pilot.sandbox` on `csc190` 

2. Since I don't have access to another Titan allocation, can you update or check why the PWD in `chm126` is not being updated properly.

**Comment by andre-merzky** [comment]
No, its not *setting* it,  its *reporting* at that value.  I have been running a gazillion of tests (well, a few at least) to try to reproduce this, but can't yet.

Can you attach your `.bashrc`, please?

**Comment by andre-merzky** [comment]
Re Manuel's sandbox reroute: this is cause by [this line](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_ornl.json#L34) - the dir uses the first project group instead of looking at the pilot description.  This is not easy to fix really - but is also, I think, not the source of Jumana's problems.  I think...

**Comment by itomaldonado** [comment]
@andre-merzky I agree with your last message, I think these are two different issues. It was just something that came out of debugging this.

**Comment by andre-merzky** [comment]
yeah, `.profile` is also a candidate.  But I am honestly at a loss.  It only happens for Jumana so far.

**Comment by itomaldonado** [comment]
The reason I bring up the `~/.profile` is because her `~/.bashrc` seemed fine to me (of course we'll wait for her to post it...) so if that *is* the case I'd suggest she also posts the `~/.profile`.

**Comment by jdakka** [comment]
`~./bashrc`
```
cd /lustre/atlas/scratch/jdakka/chm126
export LD_PRELOAD=/lib64/librt.so.1

module unload PrgEnv-pgi
module load   PrgEnv-gnu
module load   tmux
module load   python
module load   python_pip
module load   python_virtualenv
```
I do not have a `~/.profile`setup

**Comment by vivek-bala** [comment]
Why "cd /lustre/atlas/scratch/jdakka/chm126" in the bashrc?! That will bring your cwd to that path every time a new session is opened. I will suggest to remove the module unloads/loads as well and only keep the LD_PRELOAD assignment.

**Comment by jdakka** [comment]
- Make sense! Now the bootstrapper launches successfully, even though all 16 CUs fail :/ 
- Ill capture all these dependencies in the HTBAC layer/documentation.
