### ISSUE TITLE
ORTE fails on Titan

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1572]
Tried the `getting_started.py` example with 16 CUs using `ornl.titan_orte`, without success, with error in Agent_0.err: 
`orte-info: error while loading shared libraries: libopen-rte.so.0: cannot open shared object file: No such file or directory` 

@itomaldonado alluded to a change in `libopen-rte.so.0` library on Titan

**Comment by andre-merzky** [comment]
Yes, we have a new deployment for ORTE on  Titan.  Let me merge that.  What branch are you on right now?

**Comment by jdakka** [comment]
Hi @andre-merzky 

I was using the release candidate, but let's ask @vivek-bala which RP stack is needed for EnTK on Titan.  I believe it was the `master` RP branch with `devel` for RU.

**Comment by andre-merzky** [comment]
RP devel should have that fix, master will  come up shortly.

**Comment by jdakka** [comment]
I tried using `devel` before but the problem with the `uid` is still there:

```
Traceback (most recent call last):
  File "00_getting_started.py", line 37, in <module>
    session = rp.Session()
  File "/autofs/nccs-svm1_home1/jdakka/venv/lib/python2.7/site-packages/radical/pilot/session.py", line 201, in __init__
    rs.Session.__init__(self, uid=self._uid)
TypeError: __init__() got an unexpected keyword argument 'uid'
```

**Comment by vivek-bala** [comment]
Both should work fine with EnTK. If you are using devel of RP, you have to use devel of RS and RU as well.

**Comment by jdakka** [comment]
Update: I tried again with `devel` and `master` but the `uid` issue still persists, 

I noticed another `RP` branch for `feature-orte_master` so I thought I'd try that in case it's ready/meant for the purpose of this ticket. 

```
radical.pilot        : 0.47-v0.46.2-194-gb71568c2@feature-orte_master
radical.utils        : 0.47.1-v0.47.1-4-g7f65216@devel
saga                 : 0.47-v0.46-34-g0f186f66@master
```

I figured @andre-merzky this is still in "development" because I see that the lrms issue is still there:

```
agent_0.log:2018-03-02 09:24:19,401: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms config hook failed
agent_0.log:2018-03-02 09:24:19,405: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms construction error
```

**Comment by andre-merzky** [comment]
`feature/orte_master` is a different beast altogether.  I can see why the name seems related, but it isn't, really.

**Comment by andre-merzky** [comment]
To be more clear: you will need devel for all three, RP, RS and RU.

**Comment by jdakka** [comment]
ORTE appears to be working with 256 units on Titan! Will try the HTBAC workload.

**Comment by jdakka** [comment]
On the agent side I get the following error: `/lustre/atlas/scratch/jdakka/chm126/radical.pilot.sandbox/rp.session.titan-ext5.jdakka.017594.0009/pilot.0000/unit.000000`

`STDERR` 
```
Sun Mar  4 18:42:09 2018: [PE_0]:_pmi_alps_sync:alps response not OKAY
Sun Mar  4 18:42:09 2018: [PE_0]:_pmi_init:_pmi_alps_sync failed -1
```

client logs: `/lustre/atlas/world-shared/bip149/esmacs-nilotinib/rp.session.titan-ext5.jdakka.017594.0009`

**Comment by jdakka** [comment]
If it helps here is my `~/.bashrc` 

```
export LD_PRELOAD=/lib64/librt.so.1
module load cray-mpich/7.6.3
module load PrgEnv-pgi/5.2.82
module load pmi/5.0.12 
module load python/2.7.9
module load python_pip/8.1.2
module load python_virtualenv/12.0.7
export MPICH_PTL_SEND_CREDITS=-1
export MPICH_MAX_SHORT_MSG_SIZE=8000
export MPICH_PTL_UNEX_EVENTS=80000
export MPICH_UNEX_BUFFER_SIZE=100M
module load namd/2.12

source /ccs/home/jdakka/venv/bin/activate
```
** The `export MPICH` variables are namd specific

**Comment by andre-merzky** [comment]
Please remove these:
```
module load cray-mpich/7.6.3
module load PrgEnv-pgi/5.2.82
module load pmi/5.0.12

export MPICH_PTL_SEND_CREDITS=-1
export MPICH_MAX_SHORT_MSG_SIZE=8000
export MPICH_PTL_UNEX_EVENTS=80000
export MPICH_UNEX_BUFFER_SIZE=100M
```

and add these (before the python module loads):
```
module swap PrgEnv-pgi PrgEnv-gnu
module use --append /lustre/atlas/world-shared/csc230/openmpi/modules/
module load openmpi/2018_01_16_539f71d
```

**Comment by jdakka** [comment]
I'm afraid all the `namd2` versions are compiled with MPI...
I'll find some time to work with @andre-merzky on compiling NAMD with internal OpenMP

**Comment by andre-merzky** [comment]
NAMD is compiled under `/lustre/atlas1/bip149/scratch/merzky1/namd/namd/CRAY-XE-gnu`.  You will need 
```
module load PrgEnv-gnu/5.2.82
module load tcl_tk/8.5.8
```

**Comment by jdakka** [comment]
Thanks @andre-merzky could you `chmod 770` to make that path accessible? I need it to get the namd executable...basically the last bit that ends in `.../namd2`

**Comment by andre-merzky** [comment]
Quick note that testing showed inconsistent behaior wrt. the physical system.  This is now iterated with UCL to ensure we use the right test case.

**Comment by jdakka** [comment]
[TIES system](https://github.com/radical-cybertools/htbac/tree/master/experiments/orte_ties/ties-raw)

tested this out with OpenMP in path `/lustre/atlas2/csc230/world-shared/openmpi/applications/namd/namd-openmp/CRAY-XE-gnu`

executuble: `../../../../installed/test/bin/mpirun -n 1 --bind-to none ../../namd-openmp/CRAY-XE-gnu/namd2 ++ppn 15 stmv.namd`

```
module load PrgEnv-gnu/5.2.82
module load tcl_tk/8.5.8
module unload cray-mpich
module load cmake
module load rca 
```

This worked. @kristofarkas can provide walltime results using this system on Titan and the comparable output on Blue Waters

**Comment by kristofarkas** [comment]
Results from running a raw **TIES** `namd2` on titan and blue waters for the _same_ system:

Supercomputer  | BW | TITAN |
--- | --- | --- |
Walltime (seconds) | 104 | 263 |

**Comment by vivek-bala** [comment]
@jdakka @kristofarkas You might have already planned this. But you might want to compare NAMD built against cray and NAMD built against openmpi (by Andre) for the same machine.

**Comment by kristofarkas** [comment]
@vivek-bala the namd that is compiled on Titan is for CUDA, and alchemical thermodynamic integration is not supported in the CUDA version.

**Comment by andre-merzky** [comment]
@jdakka , @kristofarkas : does that mean that you are all set for your experiments, at least for the NAMD deployment and the RP layer - is that correct?

**Comment by jdakka** [comment]
@andre-merzky we are set for using TIES w/o CUDA support on Titan using a single node --> this will be useful for testing concurrency beyond the limits of Blue Waters APRUN.

For ESMACS protocol (which serves as the production runs for UCL on Titan) we will need to use ORTE with a CUDA-compiled NAMD. (The MPI versions of NAMD currently on Titan use CUDA). Is it feasible to compile a CUDA version of NAMD?

**Comment by andre-merzky** [comment]
Hi Jumana - sorry, this crossed with the other mail thread, thanks for picking this up!

Do the CUDA runs need to span multiple nodes?  If not, then the Cray version might actually work.  If not, We need indeed to compile one.

**Comment by jdakka** [comment]
Hi @andre-merzky-- just highlighting some of our discussion/ideas from slack back online:

This is in reference to UCL's production runs for ESMACS:

* The current physical systems using the ESMACS protocol cannot be executed with the `OpenMP` compiled version of `NAMD`. The cray version on Titan (compiled with `CUDA`) works. The issue at hand is that `LP hosts cannot be reconciled with lone pairs`. According to UCL, in order to overcome this issue, they would have to rebuild all their physical systems. Therefore this is not feasible. 

* Executing the cray-compiled version of `NAMD` with `ORTE` (but running without `MPI`) produces an incompatibility between compilers (`namd` still needs `MPI`):

```
[PE_0]:_pmi_alps_sync:alps response not OKAY
[PE_0]:_pmi_init:_pmi_alps_sync failed -1
```

**Comment by jdakka** [comment]
@kristofarkas found a pre-compiled multi-core non-MPI CUDA version of NAMD. Tested with `ORTE` and it's working properly: heterogenous `cpu/gpu` execution, with the RCT `devel` stack.

UCL can go into production using RCT  

[ticket](https://github.com/radical-cybertools/htbac/issues/5#issuecomment-376869315)

**Comment by vivek-bala** [comment]
Great! As you are planning/going into production, I will suggest (i) trying to replicate the same NAMD configuration in user space or (ii) notifying ORNL/Titan(?) that you are using that for production. Basically, (i) and (ii) are to avoid/minimize any surprises during production. 
My two cents.
