### ISSUE TITLE
config   file duplication

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1573]
#1562 adds a separate config file for a test (`tests/test_issue_1514/config.json`).  We will not be able to maintain individual config files for each test.  Please come up with a different approach, like using the config files we have in the examples dir.

**Comment by vivek-bala** [comment]
Fixed and tested. Please merge the PR again. We take the config file from the examples folder.

**Comment by andre-merzky** [comment]
Well, the PR  is gone - but I'll merge the branch again.  Thanks!

**Comment by iparask** [comment]
As I understand this is resolved. I'm closing this issue
