### ISSUE TITLE
feature/FIFO branch fails with more processes on Blue Waters

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1576]
`radical-stack`
```
radical.pilot        : 0.47-0.47-16-g62a2954d@feature-fifo
radical.utils        : 0.47.1-v0.47.1-4-g7f65216@devel
saga                 : 0.47-v0.46-37-g01fbb26c@devel
```
This is a follow-up from ticket [1535](https://github.com/radical-cybertools/radical.pilot/issues/1535)
where I launched two EnTK `Pipelines()` each containing 4 `Stages()` and 1 `Task()` per `Pipeline()`. 

However when I spawn the production scale number of `Tasks` i.e. 25 per `Pipeline()`, RP completes the first set of `Tasks`, 50 total for stage_1. In stage_2 I notice that the `CUs` are created and the appropriate data is staged inside each `CU` however only 3 `Tasks()` begin/complete execution. All other `Tasks()` i.e. unit.000054-unit.000099 do not begin execution. 

From `debug.log` in the .zip it shows all the units made it to `AGENT_STAGING_INPUT_PENDING`. 

See attached client files: 
[fifo_queue_nonexecuting_units.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1776378/fifo_queue_nonexecuting_units.tgz.zip)

Agent logs:

`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017590.0002/pilot.0000`

**Comment by andre-merzky** [comment]
I am quite confused by the times I find in the agent logfiles: the agent was supposed to run for 24hrs, but the log file entries span three days.  They are also out of order in many places.  I am thus really uncertain on what happened here.

I am sorry I have to ask this, but can you please run again to get a new pilot sandbox?  If that shows the same, I'll need to look into whats up with the logging...

Thanks!

**Comment by andre-merzky** [comment]
A fix got pushed to the fifo scheduler - can you please try that?  Thanks!

PS.: sorry for the earlier message on the logfiles - I mixed something up...

**Comment by jdakka** [comment]
Testing now. FYI, the queues on BW have been quite bad in the past week. Hopefully the weekend schedule grants more mercy :)

**Comment by jdakka** [comment]
This test ran longer however the pilot ran out of wall time. Rerunning again with max wall time.

**Comment by jdakka** [comment]
FIFO queue works for 2 independent ESMACS pipelines, with each production simulation long-running CU running at 2M time steps for **54403 seconds**

**Comment by andre-merzky** [comment]
Wohoo!
