### ISSUE TITLE
Documentation: Table with all the enviroment variables of rp 

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1578]
A table with all the environment variables of radical pilot is needed (RADICAL_PILOT_VERBOSE, RADICAL_PILOT_PROFILE ..)

**Comment by iparask** [comment]
Same as #1577, it gets pushed to version 2\

**Comment by andre-merzky** [comment]
duplicated,

**Comment by mturilli** [comment]
If we create a list of variables and definitions here, I will write the related documentation page. Here a start with a coarse grep on `RADICAL_` so it will need pruning and adding:
```
VIRTENV_RADICAL_DEPS
VIRTENV_RADICAL_MODS
RADICAL_PILOT_PROFILE
RADICAL_PROFILE
RADICAL_MOD_PREFIX
RADICAL_VERBOSE
RADICAL_PILOT_VERBOSE
RADICAL_PILOT_DB_HOSTPORT
RP_BS_TUNNEL
RADICAL_UTIL_VERBOSE
RADICAL_PILOT_DBURL
RADICAL_PILOT_BARRIER
RADICAL_PILOT_DB_HOSTPORT
RADICAL_PILOT_CPROFILE_COMPONENTS
RADICAL_SAGA_SMT
RADICAL_PILOT_PRUN_VERBOSE
RADICAL_PILOT_SESSION_RECORD
RADICAL_PILOT_BULK_CB
RADICAL_PILOT_AGENT_CONFIG
RADICAL_PILOT_BACKFILLING_HWM
RADICAL_PILOT_BACKFILLING_START
RADICAL_PILOT_BACKFILLING_STOP
RADICAL_PILOT_STRICT_CANCEL
```

**Comment by andre-merzky** [comment]
Not all of them should be documented I think - some are used internally, some are for debugging, etc.  Lets discuss on the call where to make the cut?

**Comment by andre-merzky** [comment]
@mturilli : please have a look if / how Napoleon supports this.

**Comment by mturilli** [comment]
Check whether we can use https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html and add a specific tag for env variables

**Comment by mturilli** [comment]
We do not have an entry specific to envs but we could use a catch-all one? https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections

**Comment by mturilli** [comment]
@andre-merzky @mtitov if you agree we can use Napoleon+tag, I will start to work on a PR.

**Comment by andre-merzky** [comment]
> @andre-merzky @mtitov if you agree we can use Napoleon+tag, I will start to work on a PR.
I do.

**Comment by andre-merzky** [comment]
Hi @kartikmodi - the list we gave above is a bit outdated.  Here is a more up to date one.  Once we have established how this is documented in code it will (hopefully) be easier to keep that list up to date.  Note that many env vars are actually defined in `radical.utils`.

The list is in no particular order, and specifically not all env vars are expected to be used by end users.  We may want to maybe  split the list in 'user' and 'developers' related once?  Not sure if and how that would be useful.  Anyway, here it goes:

[`RADICAL_UTILS_NO_ATFORK`](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/atfork/atfork.py):  lines 66 and 104

[`RADICAL_DEFAULT_*`](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/configs/utils_default.json): 
These kick in when no other env vars are set to overwrite them.  For example, if you create a logger `ru.Logger('radical.pilot`) and `RADICAL__PILOT_LOG_LVL` is not set, then the above `RADICAL_DEFAULT_LOG_LVL` will kick in.

`RADICAL_DEBUG`: enables scattered debug facilities.  This will likely slow down and even destabilize the code and is only for developers.  
`RU_RAISE_ON_*`: related to `RADICAL_DEBUG` to trigger specific exceptions.
`RADICAL_DEBUG_HELPER`: related to `RADICAL_DEBUG`, enables a persistent debug helper class in the code and installs some signal handlers for extra debug output.
For all see [here](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/debug.py)

`RADICAL_BASE`: root dir for temporary state files, defaults to `$HOME/.radical/` - see [`get_base`](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/misc.py#L497)

Loggers: [`ru.Logger`](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/logger.py#L183) instances have a name and a name space.  The name space is used to derive env variable names for log levels and targets.  If no ns is given, the ns is derived from the name.  The variables are:
  - `<NS>_LOG_LVL` for the log level
  - `<NS>_LOG_TGT` for the log targets
Please check the docstring linked above.

Reporters: [`ru.Reporter`](`https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/report.py`) instances are very similar to `ru.Logger` instances: same schema is used for names and name spaces.  The env vars are:
  - `<NS>_REPORT`: boolean to turn on and off
  - `<NS>_REPORT_TGT`: where to report to
Have a look at the various `ru_get_env_ns` calls in the class c'tor - that file misses doc strings unfortunately :-/  `get_env_ns` is something you may want to look at (in `misc.py`).

Profilers: [`ru.Profiler](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/profile.py#L138): again similar to `Logger` and `Reporter`:
  - `<NS>_PROFILE: boolean to turn on and off profiler

[`RU_USE_PYPOLL`](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/poll.py#L12) - probably obsolete?

[`RADICAL_UTILS_NTPHOST`](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/profile.py#L86): NTP host to be used for profile syncing (default: `0.pool.ntp.org`)

[`RADICAL_PILOT_BULK_CB`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pilot_manager.py#L20): enable bulk callbacks for performance boost.  This changes the callback signature, needs better documentation.

[`RADICAL_PILOT_PRUN_VERBOSE`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/prte.py#L36): increase verbosity of prun output.  There are some more `os.environ` check in that file - none of those should ever be used by end users.

[`RP_ENABLE_OLD_DEFINES`]: enable backward compatibility for old state defines.  This should be phased out, those names have not been in use for years.

[`RADICAL_SAGA_SMT`]: sets SMT settings on some resources.  This should not be used by end users and is usually covered via resource config options.

Some env vars are used by the [`tmgr.Backfilling scheduler](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/tmgr/scheduler/backfilling.py#L14).  We don't use this much.

`RADICAL_PILOT_DBURL`: you found this one.

[`RP_PROF_DEBUG`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/utils/prof_utils.py): enable additional debug messages on profile extraction

[`RADICAL_PILOT_STRICT_CANCEL`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/task_manager.py#L1072).

[`RADICAL_SAGA_PTY_SSH_TIMEOUT`]: sets the connection timeout (in seconds, default: 10) for the SAGA PTY layer.  On connection timeouts should be set to 60 or more.

Other SAGA default envs, have a look at the files [here](https://github.com/radical-cybertools/radical.saga/tree/devel/src/radical/saga/configs), specifically `session.json` and `utils_default.json`.
