### ISSUE TITLE
Agent Scheduler Architecture (RCT Class)

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1579]
[use-case/functional/nonfunctional requirements](https://docs.google.com/document/d/1BNUJEZ_U0f2ZkISazqa2Zq9c6xVkp7zrh9r7TUtT6LY/edit?usp=sharing)

Our job is to come up with an architecture for the Agent scheduler that will allow it to be easily extensible in the information it takes into account for decision making. Until next Tuesday we need to create a requirements documentation, which will include functional and non-functional requirements as well as a use case. The only use case we have at the moment is data awareness.

**Comment by iparask** [comment]
Commit 49e7eeb has the implementation of providing the size and path of the local node filesystem to the scheduler through `LRMS`. `LRMS` is updated accordingly and @chengwill97  started writing tests.

**Comment by jdakka** [comment]
`HTBAC` use-case instructions can be found here: https://github.com/radical-cybertools/htbac/blob/master/examples/README.md

**Comment by jdakka** [comment]
HTBAC use-case has been updated to include the [tagging functionality](https://github.com/radical-cybertools/htbac/tree/tagging/examples) but running this workload requires `EnTK 0.7`. HTBAC is currently being upgraded with the new `EnTK` API. Will update ticket once testing can begin.

**Comment by iparask** [comment]
This can be closed. It refers to last year's RCT class
