### ISSUE TITLE
not all mpi LMs support hostfile, yet

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1587]
we should also add  rankfile support for threaded CUs

**Comment by iparask** [comment]
@andre-merzky, is this still valid? The issue is a bit vague.

**Comment by andre-merzky** [comment]
@vivek-bala : please label the issues.

This relates to the use of hostfiles for large MPI units, and use of rankfiles when MPI units are multithreaded.  This is needed for all MPI launch methods - but only some implement it.  So that needs consolidation - which is only partially done at this point.  Does that help?

**Comment by iparask** [comment]
Yes, it stays open then!

**Comment by mturilli** [comment]
Ongoing.

**Comment by andre-merzky** [comment]
MPI is done, also do aprun, srun...
