### ISSUE TITLE
failed units are pushed to pilot

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1592]
see #1591: units which failed input staging get correctly moved into FAILED state, but then get pushed to the pilot nevertheless.  They should not.

**Comment by iparask** [comment]
I do not think this is resolved. @andre-merzky am I right?

**Comment by andre-merzky** [comment]
I don't know, this needs checking.

**Comment by mturilli** [comment]
Ongoing.

**Comment by mturilli** [comment]
@andre-merzky @mtitov would it make sense to write a test for this? If so, should we do it?
