### ISSUE TITLE
Bulk callback: Callback for a set of compute units possible?

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1598]
Currently, the RP unit callback is fired for each state update for every unit. Tools above RP, such as EnTK, that need to communicate DONE CUs do so one CU at a time as they depend on the unit callbacks. This can be quite inefficient and I am wondering if I can aggregate multiple DONE CUs for communication. Something similar to bulk submission where a list of CUDs can be submitted together.

I understand I can implement a wait function in EnTK that waits for 'T' seconds to bulk finished CUs before communicating them to other processes/threads (sort of a workload level callback similar to unit level callback). I wanted to see if there is a recommended way of doing it.

Is there a way to fire the RP callbacks over a set of CUs?
Should we develop a workload level callback in EnTK?
Alternatives?

**Comment by vivek-bala** [comment]
Following up on our discussion yesterday. Some initial proposal:

The callback could be such that it has two parameters: number of entity updates (NE) and wait time (WT). The callback could fire upon either reaching NE or WT (WT if at least one entity is updated).

**Comment by vivek-bala** [comment]
VB to get numbers on the callback overhead and the parameters that the overhead depends on.

**Comment by andre-merzky** [comment]
I looked over the RP implementation again, and now think that bulk callbacks can be implemented with reasonable effort.  A concern is API compatibility - an optional parameter on callback registration to trigger bulks should do the trick though.

**Comment by iparask** [comment]
@andre-merzky , @vivek-bala is this still needed by EnTK? Otherwise, we should close it. Do you agree?

**Comment by andre-merzky** [comment]
Yes, this should still be implemented, as for large workloads it will provide a very significant performance boost.  It's also cheap to implement, really.

**Comment by andre-merzky** [comment]
Thinking about it: due to the implied API change, this would be agood candidate vor v2.  @vivek-bala : would you agree to that?

**Comment by vivek-bala** [comment]
Yes, I definitely agree!

**Comment by mturilli** [comment]
Seeing that now we routinely run large workloads on large pilots, should we put this on the development roadmap?

**Comment by andre-merzky** [comment]
This is implemented and released by now.  Bulk callbacks can be enabled by setting `export RADICAL_PILOT_BULK_CB=True`. 
 The [default](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/unit_manager.py#L19) is `False` for now, but I would not mind changing that.

**Comment by mturilli** [comment]
Thanks. Closing this now as `RADICAL_PILOT_BULK_CB` is already listed as needed documentation.
