### ISSUE TITLE
Insufficient resources

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1601]
I'm submitting a 1600 core job, 32 cores per task * 50 tasks, 4 stages on BW and I verified in the debug logs and the `agent_0.cfg` that I am indeed submitting the correct pilot request. However, SAGA is throwing an error about insufficient resources. I submitted on the `debug queue` but my request is well below the resource limit. 

```
radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (RUNNING:
29241.0:DONE:0
11700.0:RUNNING:
11700.0:DONE:0
59304.0:RUNNING:
59304.0:DONE:0
45551.0:RUNNING:
45551.0:DONE:0
4620.0:RUNNING:
4620.0:DONE:0
61371.0:RUNNING:
61371.0:DONE:0
Shared connection to bw.ncsa.illinois.edu closed.
```

RCT stack: 

```
radical.entk         : 0.6.1
radical.pilot        : 0.47.8 (hot fix release)
radical.utils        : 0.47.4
saga                   : 0.47.3
```

PBS script: 
```
#!/bin/bash
#PBS -N pilot.0000
#PBS -v RADICAL_PILOT_PROFILE=TRUE
#PBS -o /scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017638.0007/pilot.0000/bootstrap_1.out
#PBS -e /scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017638.0007/pilot.0000/bootstrap_1.err
#PBS -l walltime=0:30:00
#PBS -q debug
#PBS -A bamm
#PBS -l nodes=50:ppn=32
export    PBS_O_WORKDIR=/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017638.0007/pilot.0000
mkdir -p  /scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017638.0007/pilot.0000
cd        /scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017638.0007/pilot.0000
export SAGA_PPN=32
```
[client_logs.zip](https://github.com/radical-cybertools/radical.pilot/files/1920031/client_logs.zip)

Client logs are attached, agent logs are in `/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017638.0007/pilot.0000`

**Comment by andre-merzky** [comment]
Jumana, can you please log onto BW and check if you have any stray processes running, with `ps -ef --forest | grep jumana` (assuming your username is jumana in this example) - thanks!

**Comment by jdakka** [comment]
Killed the process but I get the same error as [ticket 1606](https://github.com/radical-cybertools/radical.pilot/issues/1606)...

Sounds like BW has changed the python module again.

Will try with static VE for now https://raw.githubusercontent.com/radical-cybertools/radical.pilot/feature/create_ve/bin/radicalpilot-create-static-ve

**Comment by andre-merzky** [comment]
@jdakka : ping - how did that work out?
