### ISSUE TITLE
Agent fails on Titan with libopen-rte not found error

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.pilot#1604]
Trying to run HTBAC on Titan. Two days ago it was working correctly, then starting yesterday the _same_ job failed with error in `agent_0.err`:
```
orte-info: error while loading shared libraries: libopen-rte.so.0: cannot open shared object file: No such file or directory
```

I wonder if somebody changed something in the ORTE installation on Titan recently?

Stack:
```
radical.entk         : 0.6.1-entk-0.5-309-gc2bb40b@master
radical.pilot        : 0.47.6-v0.47.6@master
radical.utils        : 0.47.4-merge-pre_gpu@master
saga                 : 0.47.3-merge-pre_gpu@master
```

Let me know what other files do you need to debug this.

Would an update on the stack fix the problems?

**Comment by kristofarkas** [comment]
Tagging @jdakka @andre-merzky

**Comment by andre-merzky** [comment]
Looks like the installation got purged.  I was under the impression that `world-shared` storage is permanent and *not* purged...  I'll check the policy, and will redeploy the same version.

**Comment by kristofarkas** [comment]
It seems like _only_ purged storage is accessible from compute nodes. Hmm.
Thanks for redeploying it!

**Comment by kristofarkas** [comment]
Unfortunate that the purge happened when my 4000 node job (finally) started executing. Haha.

**Comment by andre-merzky** [comment]
OMPI got redeployed now.

> Unfortunate that the purge happened when my 4000 node job (finally) started executing. Haha.

Oops...

**Comment by kristofarkas** [comment]
Thanks!
