### ISSUE TITLE
REPORT level messages printed even if RP verbosity is not set

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1605]
I don't have RADICAL_PILOT_VERBOSE set to any value but I see the following REPORT level messages when running any EnTK/RP script.

```
new session: [rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017640.0012]   \
database   : [mongodb://138.201.86.166:27017/ee_exp_4c]                       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .    
submit 1 unit(s)
        .  
submit 10 unit(s)
        ..........                                                            ok
wait for 1 pilot(s)
                                                                              ok
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 142.1s 
```

These messages would not make sense for someone using frameworks above RP and have no idea of RP.

**Comment by andre-merzky** [comment]
This is now implemented/fixed, @vivek-bala was asked to test and confirm

**Comment by vivek-bala** [comment]
I think the logger might be broken now. Running any example in RP prints all messages, INFO and DEBUG. Even when I don't have the verbose env variable set,

**Comment by andre-merzky** [comment]
Hmm, I don't see that.  Can you please send the output of `env | grep RADICAL`?  Thanks!

**Comment by andre-merzky** [comment]
Confirmed.

**Comment by vivek-bala** [comment]
Just an update here that setting the INFO level still invokes the REPORT in both EnTK and RP.

**Comment by andre-merzky** [comment]
Hmm, I do not observe this (for RP).  Can you send me your radical-stack, please, and also the command line you used to test RP?  Please also send the output from `env | grep RADICAL`.  Thanks!

**Comment by iparask** [comment]
This is resolved.
