### ISSUE TITLE
RP Launch failure on Titan

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1608]
My limited understand tells me this error is a failure for RP to acquire a shell for running its instance. It seems this affected both new sessions
[rp.session.juststarted.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1974903/rp.session.juststarted.tar.gz)
 and sessions that have been in the queue for a couple days
[rp.session.queuedfirst.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1974916/rp.session.queuedfirst.tar.gz)
, as these had no errors until the job started. However, I can't find an error message in the second session and I lost the screen output from killing my tmux session before copying the message I saw there.

This is suspect to me
```
ControlSocket /tmp/saga_ssh_jrossyra_titan.ccs.ornl.gov_22.ctrl already exists, disabling multiplexing
Received message too long 1701079412
Killed by signal 1.
```
because there is no such file (I'm on the same login node), nor any with `saga_....` in the tmp directory.
```
(admdrpenv) [jrossyra@titan-ext1 /lustre/atlas/proj-shared/bip149/jrossyra/admdrp/admdrp/runs/runs/trial_trial]$ lg /tmp/ | grep saga*
(admdrpenv) [jrossyra@titan-ext1 /lustre/atlas/proj-shared/bip149/jrossyra/admdrp/admdrp/runs/runs/trial_trial]$
```

**Comment by andre-merzky** [comment]
`lg /tmp/ | grep saga*` is likely not giving a useful result.  I am not sure if `lg` is a typo for `ls`, or if it is an alias for ls - but either way, `grep saga*` will expand to whatever file in your *local* directory matches that glob pattern, which is not what you want for this query.  This rather should be something like `ls /tmp/saga*` .

Having said that: the error seems to indicate that ssh is used on titan, and some race condition (possibly indeed system induced) gets triggered on ssh channel setup.  But, ssh is not needed when running from titan to titan, its sufficient to use the local access methods - which is also a little faster.  What is the resource target used in your runs?  I am not sure if EnTK is adding anything for the pilot description - @vivek-bala , any idea on the schema used?

**Comment by vivek-bala** [comment]
I don't think EnTK is being used for adaptivemd right now, it directly uses RP. John, can you specify the schema as 'fork' in the pilot description. I suppose you haven't edited anything in that part, so I am wondering why you didnt encounter this error before.

**Comment by andre-merzky** [comment]
Ah, sorry - then indeed, `schema='fork' can be directly added to the pilot description.  

> I am wondering why you didn't encounter this error before.

Well, `ssh` is supposed to work locally also.  Either the system barfed up, or John  triggered a race, or some termination problem of an earlier run left some stuff behind...

**Comment by jrossyra** [comment]
Haven't seen the issue again, thanks!
