### ISSUE TITLE
Local BW resource description issues

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.pilot#1612]
After problems with long connections to BW due to queue times, I'm trying to run locally via `ncsa.bw_local_orte`. Unfortunately the workdir set in radical.pilot for this resource is different from the gsissh ones. This dir is not accessible to me. 

Relevant line:

https://github.com/radical-cybertools/radical.pilot/blob/ec325c8900e7d17a4efda07ab6a4be74af4fe87d/src/radical/pilot/configs/resource_ncsa.json#L126

Can we change this?

**Comment by andre-merzky** [comment]
Yeah, this is clearly an error, apologies.  In what branch (or release?) do you need this fix applied right now?

**Comment by kristofarkas** [comment]
Branch master if possible. Thanks!

**Comment by kristofarkas** [comment]
Even better would be to have a `bw_local_aprun` similar to the current `bw_aprun` with `local` access schema as opposed to `gsissh`. The reason for this is because it will be running NAMD with potentially MPI, and I don't want to recompile NAMD, just use the one provided on BW that works with `aprun`.

**Comment by andre-merzky** [comment]
This has been fixed in master (thanks for the PR to @kristofarkas !), and is now released as v0.47.11.

**Comment by kristofarkas** [comment]
Okay, so after testing this the following error pops up:
```
2018-05-09 04:53:18,771: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-3       : ERROR   : Error running job via 'qsub': 
ERROR: Use of 'size=256' specification is deprecated, please use 'procs=256' instead.

qsub: Your job has been administratively rejected by the queueing system.
qsub: There may be a more detailed explanation prior to this notice.
. Commandline was: SCRIPTFILE=`mktemp -t SAGA-Python-TORQUEJobScript.XXXXXX` &&  echo "
#!/bin/bash 
#PBS -N pilot.0000 
#PBS -v RADICAL_PILOT_PROFILE=TRUE
#PBS -o /scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.h2ologin1.farkaspa.017660.0001/pilot.0000/bootstrap_1.out 
#PBS -e /scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.h2ologin1.farkaspa.017660.0001/pilot.0000/bootstrap_1.err 
#PBS -l walltime=24:0:00 
#PBS -q high 
#PBS -A bamm 
#PBS -l size=256
export    PBS_O_WORKDIR=/scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.h2ologin1.farkaspa.017660.0001/pilot.0000 
mkdir -p  /scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.h2ologin1.farkaspa.017660.0001/pilot.0000
cd        /scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.h2ologin1.farkaspa.017660.0001/pilot.0000
export SAGA_PPN=32
/bin/bash -l /scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.h2ologin1.farkaspa.017660.0001/bootstrap_0.sh  -d 'radical.utils-0.47.4-merge-pre-gpu-master.tar.gz:saga-python-0.47.3-merge-pre-gpu-master.tar.gz:radical.pilot-0.47.11-v0.47.11-master.tar.gz' -p 'pilot.0000' -s 'rp.session.h2ologin1.farkaspa.017660.0001' -m 'create' -r 'local' -b 'default' -g 'default' -v '/scratch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.11' -y '1440' -e 'module switch PrgEnv-cray PrgEnv-gnu' -e 'module load bwpy' " > $SCRIPTFILE && /opt/torque/6.0.4/bin/qsub $SCRIPTFILE && rm -f $SCRIPTFILE
```

Not sure why this happens with local execution but not when done remotely? Is this `size` vs `procs` a flag we can set somewhere? Also usually one sets this via the`#PBS -l nodes=X:ppn32:xe` not `#PBS -l procs=X`. 

Another note: couple of lines above the SAGA log says:
```
2018-05-09 04:53:18,057: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-3       : INFO    : Using Cray XT (e.g. Kraken, Jaguar) specific '#PBS -l size=xx' flags (TORQUE).
```
Could this be the real problem, as this is XE not XT?

**Comment by kristofarkas** [comment]
Ah, when running locally host name is the name of the login node (in this case `h2ologin1`) and not what SAGA is looking for. See:

https://github.com/radical-cybertools/saga-python/blob/4a14d5f5d88c6ad0a9b2661d37dd01a1725a3204/src/saga/adaptors/torque/torquejob.py#L326

**Comment by andre-merzky** [comment]
Yeah, I just saw that, too...  Let me try to get the right code path triggered for this case.

**Comment by andre-merzky** [comment]
Can you give the SAGA branch `fix/issue_1612` a try,  please?

**Comment by kristofarkas** [comment]
Yes, it's working! Thanks @andre-merzky

**Comment by andre-merzky** [comment]
Great - I'll put that into a SAGA bugfix release then.

**Comment by kristofarkas** [comment]
One more question: on Titan we realised after some debugging, that the agent itself required a node to run, in addition to nodes required by the executables. Is this the case for BW running locally too? Or was that a Titan specific problem?

**Comment by andre-merzky** [comment]
The extra node is not BW, but Cray specific - we don't use this configuration on non-Crays (at least not by default).

You'll find this configured [`agent_config = 'cray'`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_ncsa.json#L47), which points to [this](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/agent_cray.json) config file which defines a subagent on a separate node on lines 40 / 41.  The main purpose of this is to reduce the load on the MOM node, but also some Cray configurations have different limits on MOM and Compute nodes which made this configuration necessary.

**Comment by jdakka** [comment]
While @andre-merzky @kristofarkas are debugging locally on BW,  I ran a longer simulation job from radical-2 without ssh throttling issues that requested > 1000 nodes. @kristofarkas, in parallel I suggest we try your workload with my older (working) stack and I'll request additional priority with BW directly to get these runs out of the queue as fast as possible.
