### ISSUE TITLE
Long queue times result in non-starting pilots on BW

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.pilot#1615]
In short a job just simply didn't start (no errors in the logs) on BW with `gsissh` from local cluster. 

The DEBUG log (not captured) shows a heartbeat from SAGA (I think) about the job queue status (PENDING), that (the heartbeat) at some point just stops. That is the last line in the log, no errors.

Wonder if the folders will be enough to find the problem. They are here:

[rp.remote.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017651.0003.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1984692/rp.remote.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017651.0003.tar.gz)
[rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017651.0003.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1984694/rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017651.0003.tar.gz)

Tagging @andre-merzky @jdakka

**Comment by andre-merzky** [comment]
Hi @kristofarkas, I'm afraid that this is not easy to solve.  What happens in those cases usually is that an ssh tunnel dies (times out) and leaves the SAGA layer in an inconsistent state.  We don't handle such interruptions well at the moment.  When exactly those timeouts happen depends on system and user configuration settings on both the local and the remote host.

We started to work on a more resilient communication layer - but it is really uncertain when that will be in a state where it can be used.  Meanwhile, the easiest workaround is to use machines with long queue times from the login nodes.  Depending on the urgency of this issue for your project, we may want to revisit our options for a short-term fix or workaround.

**Comment by jdakka** [comment]
@andre-merzky these experiments are critical for the upcoming e-science deadline. @kristofarkas the option to run experiments from the login node on Blue Waters would suffice as the best work-around for the time being. 

Looping in issue [1612](https://github.com/radical-cybertools/radical.pilot/pull/1614#event-1616346097) for correct schema to run locally on BW.

**Comment by kristofarkas** [comment]
Closing this for now then.

**Comment by kristofarkas** [comment]
Reopening after this issue happened on Titan, where we are running locally, without a remote ssh connection. Same happens: the heartbeat from SAGA (`2018-06-01 11:49:16,968: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : INFO    : Job monitoring thread updating Job [torque://localhost]-[4055109] (old state: Pending, new state: Pending)`) stops at some point before the job starts executing.

**Comment by iparask** [comment]
@andre-merzky, I agree this is general issue for RP. Is it fair to move it to version 2 since it will separate the pilot from the client?

**Comment by andre-merzky** [comment]
It is very unlikely to get resolved before v2, so: yes, please.

**Comment by mturilli** [comment]
We know the problem and it is part of the requirements list for V2. Closing.
