### ISSUE TITLE
Memory limit reached on BW login nodes

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.pilot#1618]
Since we switched to running BW locally, larger jobs (500+ CUs) started being killed off due to the runner python script (executed from a login node) is using too much memory. 

The relevant lines from an email from BW:
> NCSA Blue Waters policy limits memory for computational processes submitted outside the batch queues.
>
>On 5/11/2018 the following process on h2ologin1 was terminated. The process was consuming 100% which is over the 25% limit for system memory usage.
>
>User:farkaspa Command:0.0 python htbac-runner.py

We are unsure which layer (HTBAC, ENTK, ...) uses too much memory. We haven't had similar issues on Titan for example, or when running BW remotely.

**Comment by kristofarkas** [comment]
I could try running a `gc.collect()` before calling `run` on the EnTK `AppManager`.

**Comment by kristofarkas** [comment]
Couldn't find any data on what the memory limit actually is on BW, but while the job is in the queue the python script uses ~100MB of memory.

**Comment by vivek-bala** [comment]
I think 100MB is probably acceptable. Can you confirm this is the cumulative of all the processes started by HTBAC, EnTK and RP. You can probably use psutil(https://psutil.readthedocs.io/en/latest/) as part of the runner script to measure the total consumption. There might be other tools but I have used psutil before and found it to be quite feature-rich.

**Comment by andre-merzky** [comment]
It might be worthwhile to open a ticket (or reply to the notification) to ask (a) for the actual limit, (b) the observed value,  and (c) *how* the value was observed (so that we can reproduce it)?

**Comment by kristofarkas** [comment]
Got back from BW:

> Kristof,
> before we go any deeper, this message is the indication that you were using login node in a way they aren't supposed to be used. Login nodes are for configuring and building your code, not for running anything nor even for debugging. Now to answer your questions:
> 1) the limit is 25% of the total system memory which is 512G
> 2) you went 116% of that which is about **150G**
> 3) we don't want you to reproduce it, the memory is measured as the total memory used by your process, that is both user and kernel space allocated to you
> There are other limits in place such as peak CPU utilization, sustained CPU utilization, total running time, etc. They are there because login nodes are shared resources and used my many users at the same time, unlike compute nodes which are dedicated to whomever is scheduled.
> If your job needs a lot of memory you should use big memory compute nodes, please refer here for details:  https://bluewaters.ncsa.illinois.edu/queues-and-scheduling-policies
> If that's not enough, your first choice is to run parallel. If you cannot run parallel and/or need over 120G per node we can dedicate one login node to you for a short time. This will only happen once and you should demonstrate that you really need it and cannot run otherwise.

It looks like something is going horrible wrong. This run is about 1000 EnTK `Task`s 1 stage, 1 pipeline.

**Comment by kristofarkas** [comment]
Added a `dummy` engine to HTBAC which is just `/bin/echo` to test the stack out. The stack is the `master` branch of every layer (RU, SAGA, RP, ENTK, HTBAC). 

The actual workload is here: https://github.com/kristofarkas/SAMPLing. I added a dummy run script called [afe-dummy.py](https://github.com/kristofarkas/SAMPLing/blob/master/afe-dummy.py) for the python script, and [dummy-run.sh](https://github.com/kristofarkas/SAMPLing/blob/master/dummy-run.sh) for the calling shell script. Please set the Mongo db url, and correct local resource in the shell and python script respectively.

**Comment by kristofarkas** [comment]
I am unsure how to test this if the local memory is less than what this is supposedly using on BW (100G).

**Comment by kristofarkas** [comment]
Output of `radical-stack` (in general I `pip install .` the master branch of every layer, as opposed to from PyPi).
```
  radical.entk         : 0.6.2-0.6.2-1-g81da461@master
  radical.pilot        : 0.47.11-v0.47.11@master
  radical.utils        : 0.47.4-merge-pre_gpu@master
  saga                 : 0.47.3-merge-pre_gpu-1-g28fa0d9d@fix-issue_1612
```

HTBAC is here https://github.com/radical-cybertools/htbac/tree/master. Just pip install the master branch, there is no PyPi installation yet.

**Comment by kristofarkas** [comment]
Just got another one of these emails. The job was in the queue for days without reaching the memory limit, then when it started running that's when the memory usage spiked.

**Comment by andre-merzky** [comment]
Thanks, let me try to reproduce this.

**Comment by andre-merzky** [comment]
I can't see anything strange when running your dummy locally - it does not seem to use an unusual amount of memory.  Was one of the mails you got about a dummy run?  If not, can you please try to submit  one of those, to see if that makes a difference?

**Comment by kristofarkas** [comment]
No, both were full jobs, in the sense that the executable was the NAMD binary (otherwise the same). I'll try that; how many nodes should I use? The jobs that failed used 1000 nodes, which might be take days to queue (but long queuing might be the problem in the first place).

**Comment by kristofarkas** [comment]
Just noticed a file called `SAGA-Python-TORQUEJobScript.D00Nog.e8615914`, not sure if this is relevant to any of this, but here is it's contents:
```
tar: scratch/sciteam: Cannot change mode to rwx------: Operation not permitted
tar: scratch: Cannot change mode to rwx------: Operation not permitted
tar: Exiting with failure status due to previous errors
```

**Comment by kristofarkas** [comment]
This is no longer an issue with newer versions of the rp stack. Closing.
