### ISSUE TITLE
Implement Agent Heartbeat

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#162]

**Comment by andre-merzky** [comment]
Agent heartbeat is implemented.  I am not sure on the semantics of its usage though, so the heartbeat is not being used right now.  I'll leave this ticket open to discuss this.

**Comment by andre-merzky** [comment]
Heartbeats are implemented and functional, on a per-module basis.  Heartbeats between pmgr and agent contradict the requirement for disconnected pilots.
