### ISSUE TITLE
Resource managers don't convert number represented as string to integer

### ISSUE THREAD

**Issue by chengwill97** [radical-cybertools/radical.pilot#1623]
Unit testing in the 'project/DA-scheduler_algo' branch done in the file 'radical.pilot/tests/test_da_scheduler/test_agent_rm_configure.py' shows that key-values such as 
"cores_per_node"              : "20"
will read the value of "cores_per_node" as u'20' instead of 20
This fails my unit tests, assuming that the value will be the int 20

Currently, I've only tested radical/pilot/rm/slurm.py

Project #1622

**Comment by andre-merzky** [comment]
I am not sure I completely understand the problem:  `cores_per_node` *should* be an integer, so the config should use `20` instead of `"20"`?

**Comment by chengwill97** [comment]
Some of the resource configurations in radical/pilot/agent/configs/resource_xsede.json such as "supermic_orte" and "supermic_ortelib" have the pair '"cores_per_node" : "20"'

So the problem is that the configuration is set incorrectly, and not that the resource managers are supposed to handle these cases?

**Comment by andre-merzky** [comment]
> Some of the resource configurations in radical/pilot/agent/configs/resource_xsede.json such as "supermic_orte" and "supermic_ortelib" have the pair '"cores_per_node" : "20"'
> 
> So the problem is that the configuration is set incorrectly, and not that the resource managers are supposed to handle these cases?

Indeed, I would consider those config errors to be wrong.

**Comment by chengwill97** [comment]
fixed the resource_xsede.json configuration to have integers without quotes

**Comment by andre-merzky** [comment]
Thanks! :-)
