### ISSUE TITLE
Documentation does not explicitly explain how to run an example

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1624]
[getting_started](https://radicalpilot.readthedocs.io/en/latest/user_guide/00_getting_started.html) does not explicitly show how to run the example on any system. In [running-the-example](https://radicalpilot.readthedocs.io/en/latest/user_guide/00_getting_started.html#running-the-example) section it just shows the output. I propose that we include a line like:

```
To execute the example please do:

python 00_getting_started.py <resource>

where <resource> is can be empty or it can be a resource label from the config file
```

and provide a link to where the config file is or make it downloadable like the example.

**Comment by mturilli** [comment]
Fixed in devel waiting for merge.
