### ISSUE TITLE
Draft initial set of RP test targets

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1625]
Specify the components to be tested
Specify the target test coverage for each component

**Comment by andre-merzky** [comment]
ping :-)

**Comment by iparask** [comment]
@vivek-bala ping

**Comment by mturilli** [comment]
I am going to close this ticket. I have added a Testing header to https://github.com/radical-cybertools/radical.pilot/wiki/Roadmap-and-Milestones and added the issue of this ticket as a requirement of the integration tests.
