### ISSUE TITLE
RP devel fails with AttributeError

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1630]
I am trying to run the 00_getting_started.py example (radical.two -> BW) and I get the following attribute error:
```
$ python 00_getting_started.py 
Traceback (most recent call last):
  File "00_getting_started.py", line 37, in <module>
    session = rp.Session()
  File "/home/vivek/ves/ve-gpu/local/lib/python2.7/site-packages/radical/pilot/session.py", line 224, in __init__
    self._log.report.info ('<<new session: ')
  File "/home/vivek/ves/ve-gpu/local/lib/python2.7/site-packages/radical/utils/logger.py", line 352, in __getattr__
    return getattr(self._logger, attr)
AttributeError: 'Logger' object has no attribute 'report'
```

I have tried it with the feature/gpu branch as well, got the same error.

I want to use a RP branch that has the GPU features to test the extasy package on BW. Let me know if there is an alternate branch I should use.

**Comment by andre-merzky** [comment]
This seems to be an inconsistency between RP and RU - can you please make sure that you use `devel` for the whole stack (RS will also complain)?  Devel has all of the GPU features merged by now.

**Comment by vivek-bala** [comment]
Thanks! Fixed.
