### ISSUE TITLE
cores, gpu and lfs information duplicated in the agent cfg

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1641]
agent cfg snippet:
```
"cores_per_node": 8,
    "cu_post_exec": null,
    "cu_pre_exec": null,
    "cu_tmp": null,
    "db_poll_sleeptime": 1.0,
    "dburl": "mongodb://138.201.86.166:27017/ee_exp_4c", 
    "debug": 10,
    "export_to_cu": null,
    "gpus": 0,
    "gpus_per_node": 1,
    "logdir": ".",
    "lrms": "FORK",
    "max_io_loglength": 1024,
    "mode": "shared",
    "mpi_launch_method": "MPIRUN",
    "owner": "agent_0",
    "pilot_id": "pilot.0000",
    "pilot_sandbox": "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017708.0025/pilot.0000/",
    "resource_cfg": {
        "agent_launch_method": "FORK",
        "agent_scheduler": "CONTINUOUS",
        "agent_spawner": "POPEN",
        "cores_per_node": 8,
        "default_remote_workdir": "$HOME",
        "description": "Your local machine.",
        "filesystem_endpoint": "file://localhost/", 
        "gpus_per_node": 1,
        "job_manager_endpoint": "fork://localhost/", 
        "label": "local.localhost",
        "lfs_path_per_node": "/tmp",
        "lfs_size_per_node": 1024,
        "local": {
            "filesystem_endpoint": "file://localhost/", 
            "job_manager_endpoint": "fork://localhost/"
        },
        "lrms": "FORK",
        "mpi_launch_method": "MPIRUN",
        "notes": "To use the ssh schema, make sure that ssh access to localhost is enabled.",
        "python_dist": "default",
        "rp_version": "local",
        "schemas": [
            "local",
            "ssh"
        ],
        "ssh": {
            "filesystem_endpoint": "sftp://localhost/", 
            "job_manager_endpoint": "ssh://localhost/"
        },
        "task_launch_method": "FORK",
        "virtenv_mode": "create"
    },
```

Note the 'cores_per_node' and 'gpus_per_node' (and 'lfs_per_node' in the da scheduler branch) duplicated in level 1 and inside "resource_cfg".

**Comment by iparask** [comment]
I think this development strand has been completed. @vivek-bala may I right?

**Comment by andre-merzky** [comment]
No, I think that duplication is still present. It's not an urgent issue as that config is only read by the agent, not by humans - but it confuses when debugging agent configurations.

**Comment by mturilli** [comment]
Should we put this on August 2020 release? It can be considered part of the ongoing configuration effort.

**Comment by andre-merzky** [comment]
I would like to not change this really.  The file is auto-generated, and the duplication exists because the values are used in different parts of the code (and thus in different config sections).  It *can* be resolved, but it's a bit of coding effort and restructuring which I think is not justified as the issue itelf is mostly cosmetic.  @mturilli : thoughts?

**Comment by mturilli** [comment]
Fine by me. I think apart from cosmetic issues, it is also an effect of lack of documentation about the entries in that file. Should we close this and open a ticket about documenting resource configuration files?

**Comment by andre-merzky** [comment]
That specific file really should not need documentation - it is assembled on the fly by the launcher and only read by the agent and it's components, so it really is an internal data structure.  I would worry that any documentation gets quickly out of sync if some unrelated RP internals change and keys change or are added / removed...

**Comment by mturilli** [comment]
Got it. Closing.
