### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by sdimitrovski95** [radical-cybertools/radical.pilot#1643]
I have been following the Radical Pilot installation instructions here: http://radicalpilot.readthedocs.io/en/latest/installation.html

When I try to do the basic example on the Cybertools webpage for Radical Pilot, I receive this in the terminal:
0.47.14
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    umgr = rp.UnitManager (session=session,scheduler=rp.SCHED_ROUND_ROBIN)
AttributeError: 'module' object has no attribute 'SCHED_ROUND_ROBIN'

Any guidance would be appreciated.

**Comment by iparask** [comment]
This is fixed in the documentation.
