### ISSUE TITLE
Devel stack not working on Titan

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1653]
stack: 

```
radical.pilot        : 0.47.14-v0.47.14-227-g8d218b87@devel
radical.utils        : 0.47.5-v0.47.5-27-g02cad9b@devel
saga                 : 0.47.6-v0.47.6-35-gf578245a@devel
```

I'm facing issues with 
[debug.log](https://github.com/radical-cybertools/radical.pilot/files/2161292/debug.log)
`ORTE` launch method on Titan. I ran `00_getting_started.py` and from the debug logs I see the following: `syntax error near unexpected token ('\nPROMPT-258->)`. Only client logs are created, agent sandbox is never created. 
[debug.log](https://github.com/radical-cybertools/radical.pilot/files/2161278/debug.log)

From the client side, I see that the unit callback shows state `FAILED`: 

```
umgr.0000           : MainProcess                     : umgr.0000.subscriber._state_sub_cb: INFO    : [Callback]: unit unit.000248 state: FAILED.

```

Client logs pwd: `/lustre/atlas/scratch/jdakka/chm126/radical.pilot/examples/rp.session.titan-ext4.jdakka.017715.0009`

**Comment by andre-merzky** [comment]
This is a genuine bug which I'll need to fix, apologies.

**Comment by andre-merzky** [comment]
Can you please attach the `pmgr.0000.launching.0.child.log` ?  Thanks!

**Comment by jdakka** [comment]
[rp.session.titan-ext4.jdakka.017715.0009.zip](https://github.com/radical-cybertools/radical.pilot/files/2164417/rp.session.titan-ext4.jdakka.017715.0009.zip)

**Comment by andre-merzky** [comment]
Jumana, can you please try the `fix/rcfg_expand` RP branch?  Thanks

**Comment by jdakka** [comment]
stack: 

```
radical.pilot        : 0.50.1-v0.50.1-2-g6b5621d8@fix-rcfg_expand
radical.utils        : 0.47.5-v0.47.5-27-g02cad9b@devel
saga                 : 0.47.6-v0.47.6-35-gf578245a@devel
```

Error from umgr.0000.staging.input.0.child.log:

```
MainProcess                     : MainThread     : ERROR   : failed to fet profile for pilot.0000
umgr.0000.staging.input.0.child.log:2018-07-05 14:47:01,136: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : ERROR   : worker <bound method Default.work of <Default(umgr.0000.staging.input.0, started)>> failed
```

[rp.session.titan-ext4.jdakka.017717.0001.zip](https://github.com/radical-cybertools/radical.pilot/files/2167853/rp.session.titan-ext4.jdakka.017717.0001.zip)

**Comment by andre-merzky** [comment]
By now you know how that works: the `grep ERROR *log` gives you the location of the `ERROR` log entry, and then you can look into the file to find the stackstrace, or more details on the problem.  So please do take that extra step next time. :-)

The problem seems to be a missing string expansion in the data staging directives.  My test case did not include data staging, apologies - I'll commit a fix shortly.

**Comment by iparask** [comment]
@jdakka is this issue been resolved?

**Comment by andre-merzky** [comment]
outdated...
