### ISSUE TITLE
Unkown Password

### ISSUE THREAD

**Issue by sdimitrovski95** [radical-cybertools/radical.pilot#1654]
I am trying to run the 00_getting_started.py example but get stuck with this error:
MainProcess                     : MainThread     : ERROR   : prompted for unknown password  (sd849@localhost's password: ) (/home/sd849/RADICALPilot/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))

I've tried fixing this with the information provided here: https://debian-administration.org/article/152/Password-less_logins_with_OpenSSH, but cannot seem to get past the error.

**Comment by andre-merzky** [comment]
Hey @sd849 - there are two options: fix the ssh setup, or using a different mechanism to access the host - which is easy for localhost.  So lets try the latter first...

In [`examples/config.json`, you'll find an entry `local.localhost`](https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/config.json#L3).  Please change that entry from 

```
"schema" : null,
```
to
```
"schema" : "local",
```  

and try again.

In the long run you will likely fare better with fixing the ssh setup, specifically once you want to use RP with remote resources.  In that case you may want to ask your local sysadmin for help - but maybe we can also assist.  If you will, please run the following commands from command line and paste the (longish) output:

```
ls -la ~/.ssh/
ssh -v localhost
```

**Comment by andre-merzky** [comment]
This is the core part of the message: ` u'errmsg': u'quota exceeded', `.  It looks like our default DB got filled up.  I cleaned old entries now, and you should be able to give it another try.

Best, Andre.

**Comment by iparask** [comment]
@sdimitrovski95 did this issue get resolved?

**Comment by sdimitrovski95** [comment]
@iparask, yes, after the database was cleared it worked.
