### ISSUE TITLE
Oversubscription flag in the scheduler disables multithreaded tasks from using entire node

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1661]
In [lines 145-162](https://github.com/radical-cybertools/radical.pilot/blob/project/DA-scheduler_algo/src/radical/pilot/agent/scheduler/continuous.py#L145-L162), the cores-per-node is reduced by the number of gpus-per-node. This does not allow multithreaded tasks to use the entire node.

I am wondering if reducing the number of cores-per-node is the correct way to do it. Alternative could be to internally separate cpu from cpu+gpu/gpu-only tasks and change their resource description accordingly or leave it to the user to know the information about resources allowing/disallowing 
over-subscription.

Right now expected behavior is hampered. E.g. I tried to execute tasks with 1 proc+16 threads per proc and the scheduler complained that the units are bigger than the nodes.

Thoughts?

**Comment by andre-merzky** [comment]
I agree that reducing the number of cores per node is rather brutal.  For your current usecase, you can enable oversubscription in the config file, but a better approach is indeed needed.

**Comment by andre-merzky** [comment]
What's the priority on this?

**Comment by vivek-bala** [comment]
I noticed this while testing the DA scheduler branch on BW. I am setting up my scripts by testing right now. But I should be starting with targeted experiments by the end of the month and will need to be able to use the entire node. But yes, I may be able to go ahead with the oversubscription flag in the config file.

**Comment by iparask** [comment]
Isn't it a fair assumption that a unit will always have at least one CPU process with one thread? As a result there is no need for oversubscribing the nodes. I am not sure of a use case that can actually benefit from this.

**Comment by andre-merzky** [comment]
@iparask: So you'd say that a CU description as below would be invalid / impossible?

```
cpu_processes = 0
gpu_processes = 1
```

**Comment by iparask** [comment]
Yes, it is. When running a GPU program, a CPU process is used to start and monitor the execution. That is at least my impression. @andre-merzky ,@vivek-bala do you have a different idea?

**Comment by iparask** [comment]
This is not the case anymore. I'm closing this issue
