### ISSUE TITLE
Units do not make it to staging output (Titan ORTE) 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1665]
Chaining off ticket [1664](https://github.com/radical-cybertools/radical.pilot/issues/1664)
stack: 

```
radical.entk         : 0.7.3-0.7.3@master
radical.pilot        : 0.50.3-v0.50.3@master
radical.utils        : 0.50.1-v0.50.1-1-gce60836@master
saga                 : 0.50.0-v0.50.0@master
```

Tracking `unit.00000`: it goes from `scheduling` to `executing` but does not make  it to `staging output`.

I'm testing a `/bin/hostname` workload in EnTK, [here](https://github.com/radical-cybertools/htbac/blob/fifo_queue/null/entk_2_pipelines_titan.py)

[rp.session.titan-ext4.jdakka.017723.0010_agent.zip](https://github.com/radical-cybertools/radical.pilot/files/2186276/rp.session.titan-ext4.jdakka.017723.0010_agent.zip)
[rp.session.titan-ext4.jdakka.017723.0010.zip](https://github.com/radical-cybertools/radical.pilot/files/2186277/rp.session.titan-ext4.jdakka.017723.0010.zip)

**Comment by andre-merzky** [comment]
Looks like we either suddenly create male-formed `orterun` commands, or the orte-deployment changed.  Either one is unexpected :(

**Comment by kristofarkas** [comment]
Given that Titan only has GPU nodes should we set gpu_reqs to 1, as opposed to leaving it None?

**Comment by andre-merzky** [comment]
That would be unrelated - at this point we already have the nodes acquired, but fail to place the compute units onto them....

**Comment by andre-merzky** [comment]
The constraints on orte core placement have been relaxed now, and this use case works again in the released version.
