### ISSUE TITLE
Unit sandboxes not being created with 0.50.2/devel

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1668]
`radical-stack` is:

```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/RepEx_RP_Devel

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.0-0.7.0@master
  radical.pilot        : 0.50.2-v0.50.2-6-g3af53b66@devel
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@master
```

logs are [here](https://github.com/radical-cybertools/radical.pilot/files/2192769/logs.tar.gz)
This is on SuperMIC.

**Comment by andre-merzky** [comment]
Can you please add a `gpus_per_node : 0` entry in the resource config, and try again?  Similar to [this titan entry](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_ornl.json#L44)

**Comment by SrinivasMushnoori** [comment]
My resource config looks like this:

```
                'resource': Resource,
                'walltime': 30,
                'cpus': Pilot_Cores,
                'gpus_per_node' : 0,
                'access_schema': 'gsissh',
                'queue': 'workq',
                'project': 'TG-MCB090174',
               
```

Still does not work, unfortunately.

**Comment by andre-merzky** [comment]
Wait, that is the pilot description...  I mean the used supermic resource
config under radical/pilot/configs/resource_xsede.json

...

**Comment by SrinivasMushnoori** [comment]
Oh I see, my apologies: I can be a bit dense sometimes. Attempting now.

**Comment by SrinivasMushnoori** [comment]
After making the edit, do I need to run `pip install --upgrade .` ?
Because doing so gives me the following:

```
scm177@two:~/EnTK_build2/radical.pilot$ pip install --upgrade .
Processing /home/scm177/EnTK_build2/radical.pilot
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-h4wb5ky7-build/setup.py", line 198
        def visit((prefix, strip, found), dirname, names):
                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-h4wb5ky7-build/
```

**Comment by andre-merzky** [comment]
This looks like a python3 error - are you in the right virtualenv?

...

**Comment by SrinivasMushnoori** [comment]
Virtualenv on the Client side? Yes, my stack is:

```

  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/RepEx_RP_Devel

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.3-0.7.3@master
  radical.pilot        : 0.50.4-v0.50.4-1-g6670e662@devel
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@devel
```

**Comment by SrinivasMushnoori** [comment]
To clarify: the message you quoted was the one I figured out and fixed. I edited that message later and updated it. Apologies.

**Comment by andre-merzky** [comment]
> To clarify: the message you quoted was the one I figured out and fixed. I edited that message later and updated it. Apologies.

No worries :-)

I think there was an error on how the config values were checked.  I attempted a fix in the `fix/issue_1668` branch - can you please give it a try?  Thanks!

**Comment by SrinivasMushnoori** [comment]
Just tried it. 
Unit sandboxes are now present, but for some reason I get this error from my MD kernel: 
`MPI version of PMEMD must be used with 2 or more processors!`
RP sending tasks for execution as nonmpi despite me having `mpi=True` in the EnTK layer?

**Comment by SrinivasMushnoori** [comment]
This has been fixed. Closing ticket. 
Thanks @andre-merzky !
