### ISSUE TITLE
Add section in RTD to document process of VE creation on BW

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1670]

**Comment by vivek-bala** [comment]
Instructions:

* Log in to the Blue Waters and change directory to the rp sandbox
```
cd /u/sciteam/balasubr/scratch/radical.pilot.sandbox 
```
* Download bash script to create VE
```
wget https://github.com/radical-cybertools/radical.pilot/blob/devel/bin/radical-pilot-create-static-ve
```
* Determine the version of RP being used in the client by executing ```radical-stack``` in the client.
The version for RP would look like X.Y.Z-<git tag> or X.Y.Z. 
* Determine the task launch method that is to be used (<launch_method>= aprun/orte)
* On BW (inside the sandbox), run the following command replacing 'X', 'Y', 'Z' with the version you determined.
```
sh radical-pilot-create-static-ve ve.ncsa.bw_<launch_method>.X.Y.Z bw
```

Currently, this process has to be repeated in the following conditions:
* change in the python distribution on BW
* change in RP leading to change in its version (X, Y, or Z)
* changes in the task launch method

Feel free to use this ticket to notify other RP+BW users if there are any changes to the python distribution on BW which requires recreating the VE. Although this requires leaving this ticket open till we have a permanent/stable solution.

@andre-merzky @jdakka please verify the instructions I have added above.
@andre-merzky do you think we can add these instructions (or a subset of it) to the RTD?

**Comment by jdakka** [comment]
@vivek-bala maybe just note that if the `VE` is already created, the user won't be able to run the static `VE` script unless he/she deletes that `VE` first.

**Comment by iparask** [comment]
Since BW is getting decommissioned, I do not think this is needed anymore
