### ISSUE TITLE
Unable to install radical pilot

### ISSUE THREAD

**Issue by Sid231** [radical-cybertools/radical.pilot#1676]
Hi,

I was able to run all the commands and there was no error. After I run the command:
radicalpilot-version
Response: -bash: radicalpilot-version: command not found

Here are the output of the following commands:
uname -a
Darwin Kumars-MBP.fios-router.home 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
python -V
Python 2.7.15
pip --version
pip 18.0 from /Users/siddhant/ve/lib/python2.7/site-packages/pip (python 2.7)
python -c 'import setuptools as s; print s.__version__'
40.0.0python -c 'import distutils as d; print d.__version__'
2.7.15

**Comment by vivek-bala** [comment]
Hey @Sid231 , the command in the documentation seems to be out of sync with the current release. The command has been changed to ```radical-pilot-version```` in the latest version.

**Comment by Sid231** [comment]
Hi @vivek-bala ,

```radical-pilot-version``` didn't work as well. It gave the following error:
-bash: radical-pilot-version: command not found

Another thing, in these sample docs and examples it says radical.pilot.
http://radical-cybertools.github.io/radical-pilot/basic_example.html
http://radicalpilot.readthedocs.io/en/latest/machconf.html#preconfigured-resources

**Comment by vivek-bala** [comment]
Hmmm. That's weird. Can you share the exact installation commands you used?

**Comment by Sid231** [comment]
Hi @vivek-bala 

Here are the installation commands i tried:
virtualenv --system-site-packages $HOME/ve
source $HOME/ve/bin/activate
pip install radical.pilot

I even tried these commands after the failure of the above ones:
virtualenv $HOME/ve
source $HOME/ve/bin/activate
pip install radical.pilot

**Comment by vivek-bala** [comment]
That looks okay. Let's try to debug this.

* What OS are you using? 
* Can you share the messages you get after ``pip install radical.pilot``?
* Are you able to run ``radical-stack`` after the above 3 installation commands. If so, please share the output.

**Comment by vivek-bala** [comment]
Ah great! Hard to say why it failed without the installation logs. For now, you can probably ignore it till you face the issue again.

**Comment by Sid231** [comment]
@vivek-bala Thank you!
