### ISSUE TITLE
Add radical-pilot-fetch-allfiles

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1684]
radical-pilot-fetch-logfiles currently fetches only \*.log files. Would very useful to have a command to fetch all files  (\*.\*) as sometimes errors are in \*.out or \*.err files.

To keep the list of cmds small, it might just be simpler to replace radical-pilot-fetch-logfiles with radical-pilot-fetch-allfiles as the former is a subset of the latter.

**Comment by SrinivasMushnoori** [comment]
The one issue I see with this is sometimes STDOUT files can get pretty large. Further, *.* would fetch files generated by the workload as well, which can similarly be very large. 

Am I incorrect?

**Comment by vivek-bala** [comment]
I am only referring the stdout files from the agent, not the workload. I suppose agent stdout files can get large as well, but at that point the logfiles are large as well. From what I have observed, the logfiles always have more information than the stdout files.

**Comment by andre-merzky** [comment]
Agree, this should be limited to non-workload data.  Ideal would actually be a single tool to fetch different file types, lilke `radical-pilot-fetch --out --err --log --prof <sid>` - with all of them being the default.  That would avoid some redundant code.

Any takers? :-)

**Comment by vivek-bala** [comment]
Makes sense to me :+1:

**Comment by iparask** [comment]
@vivek-bala is this still needed?

**Comment by vivek-bala** [comment]
Yes, most certainly! :)

**Comment by mturilli** [comment]
Ongoing.

**Comment by mturilli** [comment]
Done.
