### ISSUE TITLE
DA scheduler: orte on BW failing with error in launch method

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1686]
I created a ve on BW with version 0.50.5.
Script executed: https://github.com/radical-cybertools/radical.entk/blob/devel/misc/da-tagging-lfs/bin/lfs_tagging_dd.py
Stack on client:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/test-da-entk

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.4-0.7.3-10-gaffd55e@devel
  radical.pilot        : 0.50.5-v0.50.5-96-g5c40479@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.47.6-v0.47.6-35-gf578245@devel
```
Error:
```
2018-08-03 16:02:38,683: agent_0             : MainProcess                     : MainThread     : ERROR   : initialization error
Traceback (most recent call last):
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 838, in _ru_initialize
    self.ru_initialize_parent()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 593, in ru_initialize_parent
    self.initialize_parent()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 132, in initialize_parent
    self._start_sub_agents()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 349, in _start_sub_agents
    launch_script_hop='/usr/bin/env RP_SPAWNER_HOP=TRUE "%s"' % ls_name)
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 261, in construct_command
    node_id = node['uid'].rsplit('_', 1)[-1]
TypeError: list indices must be integers, not str
```

All logs attached.
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048.zip](https://github.com/radical-cybertools/radical.pilot/files/2258874/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0048.zip)

**Comment by vivek-bala** [comment]
FWIW I have been using the devel branch (0.50.7) with ORTE on BW for a couple of days and that is stable.

**Comment by andre-merzky** [comment]
Thanks for the ping back... :-)

**Comment by vivek-bala** [comment]
Hey Andre.. Was this meant to be closed? Is this fixed and to be tested?

**Comment by andre-merzky** [comment]
Oh, I interpreted your previous comment as confirmation that this is indeed fixed!  Should I read it differently?  My tests work ok at the moment - if that's not the case for you (other than the 3rd stage thing), please do attach the logs.

**Comment by vivek-bala** [comment]
Oops, yes. My second comment is about devel being stable on RP, whereas the issue is with the project/DA-scheduler branch.

> My tests work ok at the moment - if that's not the case for you (other than the 3rd stage thing), 

I think you are referring to a different ticket here, which still does not work for me :)

**Comment by andre-merzky** [comment]
Ah, sorry for the confusion!  If there is a difference between devel and DA-Scheduler though, I'll leave that ticket to the RCT class teams, ok?

**Comment by vivek-bala** [comment]
Okay. I think @iparask  mentioned he is taking a look into it this morning. Is that correct?

**Comment by iparask** [comment]
This has to do with how the node ids are set. It does not have to do with the scheduler. Let me see the logs and understand how the node names are created. The test I created for `ORTE` ([here](https://github.com/radical-cybertools/radical.pilot/blob/project/DA-scheduler_algo/tests/test_da_scheduler/test_orte_launch_method.py)) is passing, but the node ids have an [`_` in them](https://github.com/radical-cybertools/radical.pilot/blob/project/DA-scheduler_algo/tests/test_da_scheduler/test_orte_launch_method.py#L52)

**Comment by iparask** [comment]
So, @andre-merzky can you point me where the `node uids` are created for BW? The error is because of that and I am not sure whether or not we should change `ORTE` launch method.

**Comment by andre-merzky** [comment]
> So, @andre-merzky can you point me where the node uids are created for BW? The error is because of that and I am not sure whether or not we should change ORTE launch method.

I am not sure I understand that: the node IDs have not changed, so how does that suddenly break, and more specifically, how does that breakage happen between devel and the DA branch?

The node uid's are individually defined by the various LRMS plugins in the RP agent, and then picked up by the scheduler.  But before changing that, please lets clarify if this is indeed what is suddenly broken...

**Comment by iparask** [comment]
I am closing because there is no action for quite a while and because BW is getting decommissioned
