### ISSUE TITLE
RP Install Error: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by twmoveon** [radical-cybertools/radical.pilot#1690]
Hi all,
I got a problem when I tried to install RP according to documentation:

wuxiaodongdeMacBook-Pro:~ wuxiaodong$ pip -V
pip 1.4.1 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (python 3.6)
wuxiaodongdeMacBook-Pro:~ wuxiaodong$ PYTHON -V
Python 2.7.13
wuxiaodongdeMacBook-Pro:~ wuxiaodong$ source RADICALPilot/bin/activate
(RADICALPilot) wuxiaodongdeMacBook-Pro:~ wuxiaodong$ pip install radical.pilot
Collecting radical.pilot
  Using cached https://files.pythonhosted.org/packages/77/c7/059bfd4924ad4894e9b854016c88914b657757814ac0ebd9d6a0f66fb645/radical.pilot-0.50.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3f/gr5trxj55lj_wts05l63xdz80000gn/T/pip-install-t5s951en/radical.pilot/setup.py", line 198
        def visit((prefix, strip, found), dirname, names):
                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3f/gr5trxj55lj_wts05l63xdz80000gn/T/pip-install-t5s951en/radical.pilot/

I'm not able to find the file according to the path above. Hope someone could help me.
Thanks~

**Comment by twmoveon** [comment]
Version information is: 
pip (1.4.1)
virtualenv (16.0.0)
Python 2.7.13

**Comment by andre-merzky** [comment]
hi @twmoveon : there seems to be a problem with your pip installation: it pulls files from python3:

```
pip 1.4.1 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (python 3.6)
```

The error your get is indeed a Python3-error... :/

**Comment by twmoveon** [comment]
Thanks. I recall there are 2 versions of Python and 2 versions of pip...
