### ISSUE TITLE
RP with ORTE on BW: RP does not execute a unit 

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1691]
I am using RP with ORTE on BW. My application has 5 stages with 256, 512, 1024, 2048, and 4096 tasks respectively. Execution stalls at stage 3. Digging through EnTK and RP logs, I noticed that one unit, unit.1008, does not execute even though it gets launched by the executor. Since this unit does not reach any of its final states, EnTK simply waits for it and hence stalls in Stage 3.

Stack:
```
$ radical-stack 

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/ves/ve-bw-bms

  radical.entk         : 0.7.3
  radical.pilot        : 0.50.7
  radical.utils        : 0.50.1
  saga                 : 0.50.0
```

Snippet from executing component:
```
2018-08-06 14:15:45,286: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : DEBUG   : got unit (unit.001008)
2018-08-06 14:15:45,286: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2018-08-06 14:15:45,286: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : DEBUG   : Launching unit with ORTE (/projects/sciteam/gk4/openmpi/installed/2018_07_13_539f71d/bin/orterun).
2018-08-06 14:15:45,289: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : DEBUG   : Created launch_script: /mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.two.vivek.017749.0003/pilot.0000/unit.001008/unit.001008.sh
```

No errors reported in any logs:
```
h2ologin3:~/scratch/radical.pilot.sandbox/rp.session.two.vivek.017749.0003/pilot.0000> grep ERROR *.log
h2ologin3:~/scratch/radical.pilot.sandbox/rp.session.two.vivek.017749.0003/pilot.0000> 
```

All logfiles attached
[rp.session.two.vivek.017749.0003.zip](https://github.com/radical-cybertools/radical.pilot/files/2264059/rp.session.two.vivek.017749.0003.zip)

I have set permissions so that the sandbox is accessible on BW. The path to the rp session is ```/u/sciteam/balasubr/scratch/radical.pilot.sandbox/rp.session.two.vivek.017749.0003```.

**Comment by vivek-bala** [comment]
Note: I have encountered this multiple times where execution stalls at Stage 3 every time.

**Comment by andre-merzky** [comment]
Hey Vivek  -  can you please send the unit sandbox for `unit.001008`, and also the database dump?   Thanks!

**Comment by vivek-bala** [comment]
Attached the json dump and unit sandbox.
[json_plus_unit_sandbox.zip](https://github.com/radical-cybertools/radical.pilot/files/2265958/json_plus_unit_sandbox.zip)

**Comment by andre-merzky** [comment]
I am afraid this looks like an ORTE error :/

**Comment by mturilli** [comment]
This is going to hold a paper. Do we have a way to work on this?

**Comment by andre-merzky** [comment]
Update, with good news and bad news.  Good news: I can reproduce the problem reliably, even in newer versions of ORTE (BTW, in those versions, the 64k limit on units is gone, wohoo!).  Bad news: this seems not to be an ORTE problem, but a Python process management problem: ORTE can run any number of units just fine when I feed it from a shell driver - feeding the same commands from our Python executor works just as well - but its Python which seems to loose track of the spawned processes now and then.

I'll continue to work on this with priority - but I am hesitant to give any time estimate on a solution until the root cause is understood.  My best guess right now is that Python misses out on some `SIGCHLD` signals when collecting processes, but that is tricky to confirm (its not really possible to instrument signal handlers for logging in Python).

**Comment by vivek-bala** [comment]
Thanks for digging into this issue Andre. I need to use either Titan or BW at 4-8K tasks and cores for the paper. Can you suggest any temporary fixes for this issue? 

Do you know what is the source of the issue - We have reached greater scales before, why do we have the python process mgmt problem now? Is the python problem coming from the RP end or due to changes in system modules? I am trying to understand if there is a way to revert back to our earlier deployments in the agent side.

**Comment by vivek-bala** [comment]
Hey Andre, let me know if we can setup some time to look into this together. I am happy to help debug this issue.

**Comment by andre-merzky** [comment]
Hey Vivek - our current installation or OMPI seems to work only on the MOM-Nodes.  For large workloads, that will kill the nodes, so I need to find a way to configure OMPI to be able to use the compute nodes.  Sorry for the further delay...

**Comment by mturilli** [comment]
This is now critical^2 as experiments that will need to be ready for one of our IPDPS submissions depends on this. Any news on this?

**Comment by vivek-bala** [comment]
Let me know if I can help as well. If you can point me to specific fixes/todos, I will try to
pitch in as well.

**Comment by andre-merzky** [comment]
Vivek, I don't see problems on Titan anymore now.  Can you guide me how to test your specific setup and workload?  Thanks!

**Comment by vivek-bala** [comment]
Awesome! If you want to use the exact script I have to use, the script is https://github.com/radical-experiments/adap-bms-exps-ipdps18/blob/master/task-count-2/bin/runme.py. You can replace the stress-ng executable+args with /bin/sleep 600.

For a representative example, I can suggest two scripts:
1) Any RP example with 6 stages with 256, 512, 1024, 2048, 4096, 8192 single-core tasks, pilot size for 100% concurrency. This is the closest representative to my script.
2) Any RP example with 1 stage and 8192 single-core tasks on a pilot with 8192 cores. This is my upper limit on the pilot size and the number of tasks currently.

IIRC I tried 2) which failed with the original error. You probably encountered this already, but the error seemed to be the pilot size (and not the number of tasks) as I was able to run 8K tasks on a pilot with 32 cores.

Does that help?

**Comment by andre-merzky** [comment]
[2] was easiest to do, and that seems to run reliably on titan - I really just used `examples/00_getting_started.py` with `1024 * 8 + 16` cores for the pilot, and `1024 * 8` units using 1 core each.

I'd lie to try your runme - but it needs a RabbitMQ instance.  Do you have any I can use?  How would I specify the URL?  Thanks!

**Comment by vivek-bala** [comment]
> [2] was easiest to do, and that seems to run reliably on titan - I really just used examples/00_getting_started.py with 1024 * 8 + 16 cores for the pilot, and 1024 * 8 units using 1 core each.

Great! So that means 8192 concurrent tasks can run on Titan now.  

Just some additional questions for completion:

* Can 8192 concurrent tasks be run reliably or are they prone to errors? Any failure rate you encountered?
* Can you specify the upper bound on the number of concurrent units at this point?
* Also regarding the 64K limit from ORTE, is that limit on the total number of units or the number of concurrent units?

Thanks!

> I'd lie to try your runme - but it needs a RabbitMQ instance. Do you have any I can use? How would I specify the URL? Thanks!

Yes, you can use ```AppManager(hostname='two.radical-project.org', port=33154)```. I ran runme.py from radical two, so there is no specification of the hostname in that script.

**Comment by andre-merzky** [comment]
> Great! So that means 8192 concurrent tasks can run on Titan now.
I did a `sleep 60` and should look at the plots to confirm that they were indeed concurrent - but otherwise yes.

> Can 8192 concurrent tasks be run reliably or are they prone to errors? Any failure rate you encountered?

No failure rate so far - but not enough runs to tell for certain.  


> Can you specify the upper bound on the number of concurrent units at this point?

No


> Also regarding the 64K limit from ORTE, is that limit on the total number of units or the number of concurrent units?

That is the *total* number of units a pilot can execute (or, more precisely, the ORTE-DVM can execute).  Its is unrelated to concurrency.

BTW: right now I seem to have strange FS issues again :/  Will try your script as soon as this stabilizes again.

**Comment by vivek-bala** [comment]
Thanks for that info! Can you share the stack to use for this? I can give it a try as well.

**Comment by andre-merzky** [comment]
Things work again for me.  The stack is:

```
  radical.entk         : 0.7.6
  radical.pilot        : 0.50.8-v0.50.8-9-gaee27c8c@feature-shellfs_spawner
  radical.utils        : 0.50.2
  saga                 : 0.50.0
```

Some changes are in the ORTE installation, which is transparent.  You though need to make sure to use that RP branch, and to set the `agent_spawner` to `SHELLFS` in the respective resource config (is now the default for `ornl.titan_orte`, but not for others).

**Comment by vivek-bala** [comment]
Cool, thanks! Will try it out!

**Comment by andre-merzky** [comment]
Vivek, I see a hard limit at about 10k units - then we are running out of process handles.  If you want to go higher, we need to use more compute nodes for the agent, to distributed the load over multiple executor components.  Let me know if that's something you need, and I can help you to set up an agent config for that.

**Comment by andre-merzky** [comment]
There still *is* a failure rate: out of 500k units I have been running the last two days, I lost 2 (in different runs).  Both disappeared within the ORTE layer - I am fairly confident that we did do a correct handoff to ORTE.

**Comment by andre-merzky** [comment]
The failure rate is higher I am afraid - I was lucky with my initial runs.  On average, one of 100k units goes AWOL... :-(

**Comment by vivek-bala** [comment]
Thanks for the info. My requirement (8K) is well below those numbers, I think I should be okay. Job is on the queue, will keep you posted.

**Comment by vivek-bala** [comment]
Hey Andre, I tried the shellFS spawner branch. The first few runs failed but the scheduler [specified](https://github.com/radical-cybertools/radical.pilot/blob/dc2720af3d9ae353f55eede5fb59a4c78890ab83/src/radical/pilot/configs/resource_ornl.json#L100) for Titan seems to be HOMBRE. Once I changed that to CONTINUOUS, things seem to work. I have tested up to 2K tasks. Going larger now. Will keep you posted.

**Comment by andre-merzky** [comment]
Ah, right, hombre won't work for your use case...   Thanks for the ping-back, keep me posted :-)

**Comment by vivek-bala** [comment]
I am seeing the following errors on Titan now:

```
> grep ERROR *.log
agent_0.log:2018-09-27 14:38:38,795: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,814: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,815: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,815: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,815: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,815: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,816: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,816: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,816: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,816: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,817: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
agent_0.log:2018-09-27 14:38:40,817: agent_0             : MainProcess                     : DVMWatcher     : DEBUG   : dvm output: [titan-login8:30164] [[40324,0],0] ORTE_ERROR_LOG: Bad parameter in file /lustre/atlas2/csc230/world-shared/openmpi//src/ompi/orte/mca/errmgr/dvm/errmgr_dvm.c at line 160
```

Let me know what information I could provide to help debug this.

**Comment by andre-merzky** [comment]
@vivek-bala, can you please provide a set of commands to reproduce this?  Thanks.

**Comment by iparask** [comment]
@vivek-bala is this still affecting you?

**Comment by vivek-bala** [comment]
I suggest closing this. We don't support ORTE any more.
