### ISSUE TITLE
RP with aprun on Blue Waters stalls execution 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1693]
I am running local access on BW (gsissh is not working due to GSS credentials). After several attempted failures with HTBAC workloads, I tried debugging with an EnTK `stress-ng` workload. The script is attached in the .zip. 

I am submitting 2 pipelines, 4 stages, 10 tasks per stage. I notice that after `unit.000024` tasks are not being executed. I see that some units, i.e., `unit.000028` can be found in the `agent_scheduling` logs but the agent is deferring them. I do not see any units being executed past `unit.000024`. 

Client logs, verbose logs, and script: [deferring_units.zip](https://github.com/radical-cybertools/radical.pilot/files/2283135/deferring_units.zip)

Agent logs can be accessed directly on BW: `/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.h2ologin1.dakka.017752.0002/pilot.0000`

**Comment by SrinivasMushnoori** [comment]
I can replicate this issue on a RepEx workload. Funnily enough tasks stall after exactly `unit.000024` as in @jdakka 's case. Attaching logs shortly.

**Comment by andre-merzky** [comment]
@jdakka , @SrinivasMushnoori : can you please test the `feature/schedule_ordered` branch of RP?  That fixes the FIFO scheduler which does not seem to get triggered for rescheduling in your case.

**Comment by jdakka** [comment]
Fine until stage 3...then it stops scheduling units. 

I noticed the behavior of the `CONTINUOUS_FIFO` scheduler stops working properly after stage 2. In stage 1 I see the proper behavior: units from pipeline 2 are scheduled and then units from pipeline 1 are scheduled. In stage 2, units from pipeline 2 are scheduled and then units of pipeline 1 are scheduled (also correct). In stage 3, units of pipeline 2 are scheduled but it does not schedule the units of pipeline 1. Instead it keeps scheduling units of pipeline 2. Then it stalls...

* In the resource_ncsa.json I have set: `CONTINUOUS_FIFO` 

stack:

```
radical.entk         : 0.7.4-0.7.4@master
radical.pilot        : 0.50.8-v0.50.8-9-gb8ddd736@feature-schedule_ordered
radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
saga                 : 0.50.0-v0.50.0@devel
```

client: 
[tasks_stalling_3.zip](https://github.com/radical-cybertools/radical.pilot/files/2288714/tasks_stalling_3.zip)

agent logs on BW:

`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017757.0005/pilot.0000`

**Comment by jdakka** [comment]
I've produced results that have a smaller number of tasks per stage (2 pipelines, 4 stages, 2 tasks per stage) I've also added a post-exec for each task that maps which pipeline it belong to. In each unit's folder, the pipeline name (`p1`,`p2`) is written to a `pipeline.txt` file. 

These units are scheduled in the order we expect:
`unit.000000` and `unit.000001` = stage 1, pipeline 2
`unit.000002` and `unit.000003` = stage 1, pipeline 1
`unit.000004` and `unit.000005` = stage 2, pipeline 2

These units are not scheduled in the order we expect:
`unit.000006`, `unit.000007` = stage 3, pipeline 2
`unit.000007`, `unit.000008` = stage 4, pipeline 2

As we saw previously, the correct mapping of `unit.000006`, `unit.000007` should come from stage 2, pipeline 1.  unit.000007`, `unit.000008` should map to stage 3, pipeline 2. 

client logs:
[short_tasks.zip](https://github.com/radical-cybertools/radical.pilot/files/2292179/short_tasks.zip)

agent logs:
`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017758.0001/pilot.0000`

Let me know if this helps or if it's confusing.

**Comment by jdakka** [comment]
I also tried my 2 pipelines workload with the regular `CONTINUOUS` scheduler running with the master branches:

```
radical.entk         : 0.7.4-0.7.4@master
  radical.pilot        : 0.50.8-v0.50.8@master
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@master
  saga                 : 0.50.0-v0.50.0@master
```

Out of 80 tasks only 50 are executed, leading me to believe that this issue is independent of the scheduler. I'll try on `Comet` to isolate the CI. 

Client files:

[master_branch_tasks_stalling.zip](https://github.com/radical-cybertools/radical.pilot/files/2297424/master_branch_tasks_stalling.zip)

Agent files:
`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017760.0003/pilot.0000`

**Comment by andre-merzky** [comment]
Thanks  Jumana!

**Comment by jdakka** [comment]
Apologies, I used the wrong script to execute my workload and as a result I was getting the wrong output. I verified that both the `feature-schedule_ordered` branch and master are behaving accordingly.

**Comment by iparask** [comment]
I'm closing this as resolved!
