### ISSUE TITLE
Be sure to have access to Summit

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1696]

**Comment by iparask** [comment]
I applied. I am waiting instructions from Summit people.

**Comment by mturilli** [comment]
* Vivek: access
* Giannis: waiting
* Andre: testing

**Comment by andre-merzky** [comment]
I can access summit.

**Comment by mturilli** [comment]
Giannis: opened a ticket with ORNL, application process ongoing.

**Comment by iparask** [comment]
Got my fob, got to return the notarized documentation

**Comment by iparask** [comment]
Notarized document has been sent back to ORNL. I am waiting for their process to finish

**Comment by iparask** [comment]
I have access to Summit now. Matteo feel free to close this ticket!
