### ISSUE TITLE
Create static VE on Summit for RP bootstrap

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1697]
Investigate the support of Python on Summit

**Comment by mturilli** [comment]
Ongoing for next week

**Comment by mturilli** [comment]
* Default python 2.7 works out of the box on Summit. Seems to be a system python.
* We need to load the default gcc module.
* Virtual environment seems to be working: we can create the virtual env, likely we will not need a static VE. 
* TODO: Test manual bootstrap of the agent.

**Comment by mturilli** [comment]
Confirm static VE is not needed

**Comment by andre-merzky** [comment]
VE creation on the fly by the bootstrapper seems to work as expected - static VE is not needed, but the static VE creation script also is confirmed to work ok.
