### ISSUE TITLE
Issue with the resource "futuregrid.alamo"

### ISSUE THREAD

**Issue by Sid231** [radical-cybertools/radical.pilot#1700]
Hi! 
I am getting an error when I am creating a ComputePilotDescription with the "futuregrid.alamo" resource. Below is the code:

```
pd = rp.ComputePilotDescription()
pd.resource = "futuregrid.alamo"
pd.cores = 2
pd.runtime  = 10
p1 = pm.submit_pilots(pd)
```

Below is the error:
`RuntimeError: Resource 'futuregrid.alamo' is not known.`

Can you please help in understanding what all resources can be set for the ComputePilotDescription object?

**Comment by andre-merzky** [comment]
Hi Kumar, 

acceptable resources are those for which an entry in our [configuration files](https://github.com/radical-cybertools/radical.pilot/tree/devel/src/radical/pilot/configs) exist.  There are some futuregrid entries, but we have not used those for quite a while, and I am not sure how well they reflect the currect configuration of those machines.  I don't think we ever used alamo.  Please let me know if you need help with creating a config entry for that machine!

**Comment by Sid231** [comment]
Hi Andre!

Thanks for the info. I was just trying out an example from the API description of Radical Pilot.Will go for localhost configuration right now.
