### ISSUE TITLE
Prototype jsrun executor

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1703]

**Comment by andre-merzky** [comment]
So far, jsrun behaves as promised.

**Comment by mturilli** [comment]
All the command lines for jsrun we planned to use been defined and tested.

**Comment by andre-merzky** [comment]
Some core exists, and I think its not totally wrong, but its also not yet complete: https://github.com/radical-cybertools/radical.pilot/blob/feature/jsrun/src/radical/pilot/agent/lm/jsrun.py

**Comment by iparask** [comment]
I took a crack at it. I think it is almost ready. Just need @vivek-bala and @andre-merzky to take a look in case I did something completely wrong

**Comment by mturilli** [comment]
- First prototype written on the base of Tom's example;
- Created tests
- LRSM does not work: 
  - Does not parse the node list it gets from SummitDev. It gets the list but it does not parse it correctly.

**Comment by iparask** [comment]
Blocking issue #1741
