### ISSUE TITLE
`curl -1` Error with "tlsv1 alert protocol version" on SuperMIC

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1705]
So while running some experiments on SuperMIC I am seeing failures. I do a `fetch-logfiles` to find there are no logs on remote. `grep ERROR *log` turns up with nothing. However, digging into the pilot sandbox on remote (specifically the `bootstrap_0.err` and `bootstrap_0.out` I find that the pilot fails at VE creation. On double checking, there is no ve directory created in `radical.pilot.sandbox` 

Logs are [here](https://github.com/radical-cybertools/radical.pilot/files/2341118/supermic_ve.tar.gz)
(unsure how much help they will be)

Relevant output from the `bootstrap_0.out` is pasted below ( `bootstrap_0.err` is empty):

```
# -------------------------------------------------------------------
#
# Download virtualenv tgz
# cmd: curl -1 -k -L -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
#
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
WARNING: Couldn't download virtualenv via curl! Using system version.

# -------------------------------------------------------------------
#
# Create virtualenv
# cmd: virtualenv /worka/work/smushnoo/radical.pilot.sandbox/ve.xsede.supermic.0.50.8
#
/work/smushnoo/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017774.0004/bootstrap_0.sh: line 512: virtualenv: command not found
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
ERROR: Couldn't create virtualenv
Error on virtenv creation -- abort
removed `/worka/work/smushnoo/radical.pilot.sandbox/ve.xsede.supermic.0.50.8.lock'
```
`radical-stack` is:

```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.5-0.7.3-24-gf4030c3@devel
  radical.pilot        : 0.50.8-v0.50.8-6-g6e36785@devel
  radical.utils        : 0.50.1-v0.50.1-2-gfebbcd0@devel
  saga                 : 0.50.0-v0.50.0@devel

```
Please let me know if further info is needed from me.

**Comment by vivek-bala** [comment]
Are you able to reproduce this error? Can you check if you can run the following from the supermic login node:
```
curl -1 -k -L -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
```

**Comment by SrinivasMushnoori** [comment]
@vivek-bala that command works on the login node, yes.

**Comment by andre-merzky** [comment]
Thanks Srinivas.  What RP version are you using?  This looks like master or release, right?  Can you please check if the command Vivek gave indeed fails?  If it does, can you please retry without the `-1` option?  Thanks!

**Comment by vivek-bala** [comment]
The original error seems to be failure running the above cmd. Can you try your scripts to see if you can reproduce the error?

**Comment by SrinivasMushnoori** [comment]
@andre-merzky oops: I KNEW I was forgetting something, sorry. RP version is   `radical.pilot        : 0.50.8-v0.50.8-6-g6e36785@devel`
`radical-stack` output has been added to original post on this ticket. 

I ran the command on the login node with and without `-1` and it succeeds.

**Comment by SrinivasMushnoori** [comment]
Hi, has there been movement on this ticket?
Running the command on its own succeeds but RP still fails.

**Comment by andre-merzky** [comment]
Hi Srinivas - Vivek and I should have synced on who handles this - apologies.  Let me take this on.

Thanks for checking the command line on the login node!   Since it works there, but the bootstrapper complains about it, the next step would be to test how it behaves on a compute node (where the bootstrapper runs).  Can you put it into a simple job submission script and submit it to the batch queue?  Or, alternatively, you could check it in an interactive batch job.

Thanks, Andre.

**Comment by vivek-bala** [comment]
Ah I was under the impression that this was on srinivas' end:

> The original error seems to be failure running the above cmd. Can you try your scripts to see if you can reproduce the error?

Did you get a chance to run your entire script again? Do you get the same error?

**Comment by SrinivasMushnoori** [comment]
@vivek-bala by "entire script" do you mean a RepEx job? or am I misunderstanding you?

**Comment by vivek-bala** [comment]
Yes. The Repex job. 

Since the single line curl command works.

**Comment by vivek-bala** [comment]
I am also facing this issue now. The culprit is the ```module load python/2.7.7-anaconda``` we run before the bootstrapper. The single line curl command fails if I try it after the module load.

**Comment by vivek-bala** [comment]
I am opening a ticket with XSEDE. Let's see how that goes.

**Comment by SrinivasMushnoori** [comment]
I was just about to comment as well, but you seem to have beat me to the punch: the RepEx job still fails.

**Comment by vivek-bala** [comment]
> Please take out -k for secure SSL connections and transfers.
Thank you,
Wei Feinstein

- SuperMIC

**Comment by vivek-bala** [comment]
I think you have to remove the '-1', not '-k'.

**Comment by andre-merzky** [comment]
> Please take out -k for secure SSL connections and transfers.
> Thank you,
> Wei Feinstein
> 
> -from SuperMIC

Was there any explanation on why this happens?

**Comment by vivek-bala** [comment]
Not really, no. The above change fixed it though.

**Comment by andre-merzky** [comment]
Strange... :/

**Comment by jdakka** [comment]
I am facing the same issue, can we keep this ticket open?

**Comment by andre-merzky** [comment]
oh, apologies, of course...  I thought this has made it into the release already - but that's not the case apparently...  Will take care of it.

**Comment by jdakka** [comment]
As per @vivek-bala's suggestion I tried the following, removing `-1` works:

```
[jdakka@smic108 rp.session.two.jdakka.017800.0003]$ module load python/2.7.7-anaconda
[jdakka@smic108 rp.session.two.jdakka.017800.0003]$ curl -k -L -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   122    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   278  100   278    0     0   1271      0 --:--:-- --:--:-- --:--:--  1271
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1957k  100 1957k    0     0  3809k      0 --:--:-- --:--:-- --:--:-- 3809k
[jdakka@smic108 rp.session.two.jdakka.017800.0003]$ ls
bootstrap_0.sh  pilot.0000                                  radical.utils-0.50.2-v0.50.2-master.tar.gz                         saga-python-0.50.0-v0.50.0-master.tar.gz
env.orig        radical.pilot-0.50.8-v0.50.8-master.tar.gz  rp.session.two.jdakka.017800.0003.pmgr.0000.launching.0.child.tgz  virtualenv-1.9.tar.gz
[jdakka@smic108 rp.session.two.jdakka.017800.0003]$ curl -1 -k -L -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
```

**Comment by andre-merzky** [comment]
Could one of you please check branch fix/issue_1705 ?  Thanks!

**Comment by jdakka** [comment]
Sure I'll give it a go, and keep you posted.

**Comment by jdakka** [comment]
It works.

**Comment by andre-merzky** [comment]
Great, thanks - I'll push a bugfix release out then.

**Comment by mturilli** [comment]
We need to get the remote testing via Jenkins going.

**Comment by lee212** [comment]
Based on the thread, it is resolved now?

**Comment by andre-merzky** [comment]
yes,  thanks.
