### ISSUE TITLE
CU Execution stalls on OLCF Titan

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1713]
I have had an issue that whole workloads stall before CU pretask execution finishes. It seems everything is scheduled ok and input staged, but execution stalls in the pretask and no CUs are cancelled until the session is interrupted. This happens with most sessions, however I have had about 2/20 attempts successfully execute for an identical run. This has also only happened when using 100s of CUs, I can concurrently run very small workflows that execute just fine. The same apparent issue happened under older versions of the radical stack, as well as after I updated to this stack installed via pip:
```
  python               : 2.7.9
  pythonpath           : /sw/titan/.swci/0-login/opt/spack/20180315/linux-suse_linux11-x86_64/gcc-4.3.4/python-2.7.9-v6ctjewwdx6k2qs7ublexz7gnx457jo5/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas/proj-shared/bip149/jrossyra/admd/admdenv
  radical.pilot        : 0.50.8
  radical.utils        : 0.50.2
  saga                 : 0.50.0
```

Here are the logs from a run where I let the job time out.
[rp.session.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2380176/rp.session.tar.gz)

**Comment by mturilli** [comment]
As discussed in our meeting, can this be done for a smaller job (Andre: see the allocation needed to run that job)? If I remember correctly, you seem to have to have this issue only at this scale?

**Comment by andre-merzky** [comment]
You don't need to run a new job for the unix sandbox BTW - I can use one from the last run which stalled.
