### ISSUE TITLE
wrong CU environment on Bridges with RP devel

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1717]
I submit a pilot with the following `EnTK` task description and resource description to Bridges:

```
self.pre_exec = ['which python'] 
self.pre_exec += ['echo $PATH']

res_dict = {

        'resource': 'xsede.bridges',
        'project' : 'mc3bggp',
        'queue' : 'RM',
        'walltime': 10,
        'cpus': 1,
        'access_schema': 'gsissh'
}

```

On Bridges, in my `/.bashrc` I export my miniconda3 environment: `export PATH="/home/dakka/miniconda3/bin:$PATH"`

However, in my CU folder I see that the `pre-exec` does not point to the Python path that is in my `~/.bashrc`. 

`which python` shows:

```
/pylon5/mc3bggp/dakka/radical.pilot.sandbox/ve.xsede.bridges.0.50.8/bin/python
```

* So I ran the pre-bootstrap commands for the ssh launch method on a Bridges interactive node: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L592

* Then I ssh directly into the compute node (follow below). After running `which python` on the node which I ssh'ed into, I get the correct python path that is consistent with my `/.bashrc`: 

```
[dakka@r003 ~]$ module purge
[dakka@r003 ~]$ module load gcc
[dakka@r003 ~]$ module load mpi/gcc_openmpi
[dakka@r003 ~]$ module load slurm
[dakka@r003 ~]$ module load python2
[dakka@r003 ~]$ source /pylon5/mc3bggp/dakka/radical.pilot.sandbox/ve.xsede.bridges.0.50.8/bin/activate

(ve.xsede.bridges.0.50.8)[dakka@r003 radical.pilot.sandbox]$ hostname
r003.pvt.bridges.psc.edu
(ve.xsede.bridges.0.50.8)[dakka@r003 radical.pilot.sandbox]$ ssh dakka@r003.pvt.bridges.psc.edu
Last login: Tue Sep 25 10:56:16 2018 from r003.pvt.bridges.psc.edu
********************************* W A R N I N G ********************************
You have connected to r003.pvt.bridges.psc.edu 

This computing resource is the property of the Pittsburgh Supercomputing Center. 
It is for authorized use only.  By using this system, all users acknowledge 
notice of, and agree to comply with, PSC polices including the Resource Use 
Policy, available at http://www.psc.edu/index.php/policies. Unauthorized or 
improper use of this system may result in administrative disciplinary action, 
civil charges/criminal penalties, and/or other sanctions as set forth in PSC 
policies. By continuing to use this system you indicate your awareness of and 
consent to these terms and conditions of use.

LOG OFF IMMEDIATELY if you do not agree to the conditions stated in this warning

 

Please contact remarks@psc.edu with any comments/concerns.

********************************* W A R N I N G ********************************
[dakka@r003 ~]$ which python
~/miniconda3/bin/python
```

RCT stack:
```
radical.entk         : 0.7.4
radical.pilot        : 0.50.8-v0.50.8-7-g8652e961@devel
radical.utils        : 0.50.1-v0.50.1-2-gfebbcd0@devel
saga                 : 0.50.0-v0.50.0@devel
```

[rp.session.two.jdakka.017799.0008.zip](https://github.com/radical-cybertools/radical.pilot/files/2417096/rp.session.two.jdakka.017799.0008.zip)

**Comment by andre-merzky** [comment]
Jumana, what agent configuration are you using?

**Comment by iparask** [comment]
The default one I think.

**Comment by iparask** [comment]
I just found the reason. First the base class of the Launch Method sets up a set of environment variables that is exports by default. Those are `LD_LIBRARY_PATH`, `PATH`, and `PYTHONPATH`.

As a result, when a unit is executed via SSH these variables are passed, as shown in `agent_0.executing.0.child.log` line 206:
```
2018-09-25 10:47:52,967: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : INFO    : Launching unit unit.000000 via /bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto r010 LD_LIBRARY_PATH=/opt/packages/python/2_7_11_gcc/lib:/usr/mpi/gcc/openmpi-2.1.2-hfi/lib64:/opt/packages/gcc/5.3.0/lib64:/opt/packages/gcc/5.3.0/lib PATH=/pylon5/mc3bggp/dakka/radical.pilot.sandbox/ve.xsede.bridges.0.50.8/bin:/opt/packages/python/2_7_11_gcc/bin:/opt/packages/slurm/default/bin:/usr/mpi/gcc/openmpi-2.1.2-hfi/bin:/opt/packages/gcc/5.3.0/bin:/home/dakka/miniconda3/bin:/home/dakka/miniconda3/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/slash2/psc/sbin:/usr/local/slash2/psc/bin:/opt/puppetlabs/puppet/bin:/opt/packages/slash2/psc/sbin:/opt/puppetlabs/bin:/home/dakka/.local/bin:/home/dakka/bin:/usr/local/slash2/psc/sbin:/usr/local/slash2/psc/bin:/opt/puppetlabs/puppet/bin:/opt/packages/slash2/psc/sbin:/home/dakka/.local/bin:/home/dakka/bin PYTHONPATH=/pylon5/mc3bggp/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017799.0008/pilot.0000/rp_install/lib/python2.7/site-packages:: /pylon5/mc3bggp/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017799.0008/pilot.0000/unit.000000/unit.000000.sh in /pylon5/mc3bggp/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017799.0008/pilot.0000/unit.000000
```

This again brings back the unit's environment. I do not remember based on what we included it to the base class. @andre-merzky you may have a better idea as to why and how to fix this. I will bring back the method we did for Stampede in the discussion.

**Comment by jdakka** [comment]
The hack for now is to create a module on the resource and to add `module use -a <path-to-module>` and the cu's Python `$PATH` as pre-execs.

**Comment by jdakka** [comment]
This is becoming problematic, the unit env is being setup by the agent as well. I cannot source my `miniconda3` environment properly because my $LD_LIBRARY_PATH is set to `LD_LIBRARY_PATH=/usr/local/packages/python/2.7.7-anaconda/lib:`

**Comment by jdakka** [comment]
Update: this issue seems to be problematic so far with `Supermic`. On `Bridges` I am able to source the correct conda environment on by setting both $PATH and $LD_LIBRARY_PATH to point to the miniconda `/bin` and `/lib`.

**Comment by mturilli** [comment]
This is likely to become critical starting from Oct 10 2018 for the collaboration with the HyperSpace group.

**Comment by jdakka** [comment]
On Bridges, the mpi module specified in an EnTK task  is `module load mpi/intel_mpi`, however the CU defaults to the module loaded by the bootstrapper:`"module load mpi/gcc_openmpi"`

**Comment by mturilli** [comment]
Do you need that specific compiler or can you use `gcc`?

**Comment by lee212** [comment]
@jdakka , based on the thread, your workaround on bridges resolves this issue?, fixing conda environment and choosing gcc compiler?

**Comment by mturilli** [comment]
@iparask, @andre-merzky is this still an issue?

**Comment by andre-merzky** [comment]
env isolation issues remain - but this specific issue is gone.
