### ISSUE TITLE
Evaluate test suite for scheduler component of the agent

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1718]

**Comment by vivek-bala** [comment]
@iparask has also added the tests for the mpi units.

**Comment by mturilli** [comment]
Blocked #1740

**Comment by lee212** [comment]
Is this going to be routed to V2?

**Comment by mturilli** [comment]
I do not think so. Based on the work we did for Summit, I am under the impression that the background work has been done and we should be now ready to write unit and integration tests across Agent. Am I mistaken?

**Comment by iparask** [comment]
The scheduler tests are under way based on PR #2120.

**Comment by mturilli** [comment]
@andre-merzky #2120 requires your approval.

**Comment by andre-merzky** [comment]
Thanks, this is merged now.
