### ISSUE TITLE
Feature/cheyenne branch of RCT stack

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1722]
Currently, utils seem to be ahead of feature/cheyenne branch in RP and SAGA. Please see https://github.com/radical-collaboration/hpc-workflows/issues/65.

Short term solution could be to get the specific branch or version of radical utils.
Long term could be to merge the cheyenne branches into master/release.

Andre will you be able to advise on those two ideas.

**Comment by mturilli** [comment]
This is blocking for the hpc-workflow project and for the publication of one of its working group. Short term solution is perfectly fine as they need to get onto the machine ASAP.

**Comment by andre-merzky** [comment]
I brought the Cheyenne branches up to date wrt. master.  Please check and reconfirm both PRs - I have no concerns to push out the releases then.

**Comment by andre-merzky** [comment]
Can you please attach also the `*.{out,err,cfg}` files from the pilot sandbox?  Thanks!

**Comment by vivek-bala** [comment]
No sandbox is created. I believe the target location is TMPDIR, but there are new pilot sandboxes there.

**Comment by andre-merzky** [comment]
Uh, but your zip file above contains agent log files, which presumable are from the pilot sandbox?

**Comment by vivek-bala** [comment]
Oh wait, yes! I didn't run fetch-profiles though, are the agent logs automatically transferred? I see that the rp folder is created in $HOME as opposed to TMPDIR (which is specified in the config file). I see the error in the STDERR inside the units now:

STDERR:
```
MPT ERROR: invalid option -host
        (SGI MPT 2.15  12/18/16 02:59:28)
```

Cmd from the unit.*.sh:
```
# The command to run
prof cu_exec_start
/opt/sgi/mpt/mpt-2.15/bin/mpirun -np 2 -host localhost,localhost  /bin/date
RETVAL=$?
prof cu_exec_stop
```

Note that on cheyenne, we have to run from the login node.

**Comment by andre-merzky** [comment]
This seems to be a problem with the `mpirun` version used.  Can you please check what installations are available?  We can use `mpirun` and `mpiexec`, please check the version for those you find.  Thanks!

**Comment by vivek-bala** [comment]
I believe its the same:

```
vivekb@cheyenne3:~> which mpirun
/opt/sgi/mpt/mpt-2.15/bin/mpirun
vivekb@cheyenne3:~> mpirun --version
MPT: libxmpi.so 'SGI MPT 2.15  12/18/16 02:59:28'
vivekb@cheyenne3:~> which mpiexec
/opt/sgi/mpt/mpt-2.15/bin/mpiexec
vivekb@cheyenne3:~> mpiexec --version
MPT: libxmpi.so 'SGI MPT 2.15  12/18/16 02:59:28'
```

and this from the man page:
for mpirun:
```
MPT implements the MPI 3.1 standard,
```

for mpiexec:
```
mpiexec command presents the mpiexec interface described in section "4.1 Portable MPI Process Startup" of the "MPI-2: Extensions to the Message-Passing Interface" document in http://www.mpi-forum.org/docs/mpi-20-html/node42.htm
```

**Comment by andre-merzky** [comment]
Can you please check the man pages about the `-host` option?
(The URL cited in the `mpiexec` output is invalid)

**Comment by vivek-bala** [comment]
Man page for mpirun: https://gist.github.com/vivek-bala/7dd52330c798f9f5230aa2332d0f4b95

Side note: Trying to see if we can reduce the hops in info transfer. Do you think it might be useful to get you access to Cheyenne? (I see https://github.com/radical-collaboration/hpc-workflows/issues/22, but not sure if you get access though)

**Comment by andre-merzky** [comment]
Thanks for the man page.  That documents a host spec format which we did not encounter before, and do not yet support.  Two options: look around for a different MPI module or installation, or we add support.  Looking around is presumably quicker, so can you please do?  Otherwise I would switch to that as soon as BW is back for RP...

**Comment by lee212** [comment]
According to [this issue](https://github.com/radical-collaboration/hpc-workflows/issues/65), the branch has been tested on Cheyenne and merged. This can be closed now.
