### ISSUE TITLE
test decreased stack size on all resources

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1746]

**Comment by lee212** [comment]
Asking some explanation/update here

**Comment by andre-merzky** [comment]
The default stack size for Python threads is several MB on some machines.  Since RP uses many threads, this can easily kill a run on small machines, or we can hit cgroup limites or ulimits etc.

RP now tries to limit stacksize, but it needs testing if this actually works as expected.  This is not yet done - but priority can actually be lowerd...

**Comment by iparask** [comment]
What is the state of this issue?

**Comment by andre-merzky** [comment]
We should probably close it - if it ever becomes a problem, the error messages should be relatively clear (malloc problem during thread creation), and the fix is simple.
