### ISSUE TITLE
VE creation instruction on SummitDev

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1749]
These is the documentation that will allow to create a VE on `SummitDev`. It based on the steps I followed to create the one I use for testing.

Currently Loaded Modules:
```
  1) xalt/1.1.3   3) spectrum-mpi/10.2.0.0-20180110   5) hsi/5.0.2.p5
  2) DefApps    4) gcc/6.4.0    6) lsf-tools/2.0
```
Then, I used the [radical-pilot-create-static-ve](https://github.com/radical-cybertools/radical.pilot/blob/devel/bin/radical-pilot-create-static-ve) to create a virtual environment that works. After loading it I installed the `Summit` version of our tools.

**Comment by mturilli** [comment]
To be converted to: https://github.com/radical-cybertools/radical.pilot/wiki/Guide-Summit

**Comment by mturilli** [comment]
To be merged with #1751

**Comment by mturilli** [comment]
To be done by Dec 4 so to converge with #1751

**Comment by iparask** [comment]
Done in Gdoc from #1751

**Comment by mturilli** [comment]
Well done!
