### ISSUE TITLE
Summit E2E test plan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1750]
- [x] 1 unit, 1 generation on 1 core (IP, VB, AM)
- [x] 20 units, 1 generations on 1 node (IP, VB, AM)
- [x] 40 units. 2 generations on 1 node (IP)
- [x] 40 units. 1 generations on 2 nodes (IP)
- [x] 20 units, 2 cores per unit, 1 generation on 1 node (VB)
- [x] 40 units, 2 cores per unit, 2 generation on 1 nodes (VB)
- [x] 40 units, 2 cores per unit, 1 generation on 2 nodes (VB)

**Comment by mturilli** [comment]
- Fix the test specification for SummitDev
- Adjust workload description to documented slowness of Jsrun

**Comment by iparask** [comment]
SummitDEv has 20 cores per node instead of 42, thus the test is:

- [ ] 40 units. 2 generations on 1 node (IP)
- [ ] 40 units. 1 generations on 2 nodes (IP)
- [ ] 10 units, 2 cores per unit, 1 generation on 1 node (VB)
- [ ] 20 units, 2 cores per unit, 2 generation on 1 nodes (VB)
- [ ] 20 units, 2 cores per unit, 1 generation on 2 nodes (VB)

**Comment by vivek-bala** [comment]
(i) and (ii) confirmed

**Comment by vivek-bala** [comment]
Also test cross socket openMP threads

**Comment by mturilli** [comment]
Noticed an inconsistency while attempting OpenMP tests. Rerun all the tests (automatic) and see whether we are missing something.

**Comment by vivek-bala** [comment]
The inconsistency is no longer present. I reran all commands and they behaved as they did previously.
Cross socket openMP threads seem to be supported as well:

```
$ export OMP_NUM_THREADS=12
$ jsrun -n1 -a1 -c12 -g1 /ccs/home/vivekb/tools/Hello_jsrun/jsrun_layout
########################################################################

*** MPI Ranks: 1, OpenMP Threads: 12, GPUs per Resource Set: 1 ***
========================================================================
MPI Rank 000, OMP_thread 06 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 07 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 08 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 09 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 10 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 11 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 05 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 04 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 03 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 02 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 01 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
MPI Rank 000, OMP_thread 00 on HWThread 032 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 2 
```

```
$ export OMP_NUM_THREADS=20
$ jsrun -n1 -a1 -c20 -g1 /ccs/home/vivekb/tools/Hello_jsrun/jsrun_layout
########################################################################

*** MPI Ranks: 1, OpenMP Threads: 20, GPUs per Resource Set: 1 ***
========================================================================
MPI Rank 000, OMP_thread 06 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 07 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 08 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 09 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 10 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 11 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 12 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 13 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 14 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 15 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 16 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 17 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 18 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 19 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 05 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 04 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 03 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 02 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 01 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0 
MPI Rank 000, OMP_thread 00 on HWThread 000 of Node summitdev-r0c1n06 - RT_GPU_id 0 : GPU_id 0
```

This ticket can be closed as all cases have been tested.

**Comment by iparask** [comment]
I am just confused with the purpose of this ticket right now. 

Was it to test end to end our development or test `jsrun`? 

The launch method we have developed does not include `-c` for example, nor `-g` for GPUs.

**Comment by andre-merzky** [comment]
I am confused by the OpenMP behavior - was there really that much miscommunication about thread placement constraints, or do we miss something?  If this result holds in general, we would not need a separate scheduler at all, right?

**Comment by andre-merzky** [comment]
re scheduler: the socket scheduler (summit specific) will be kept, tested and maintained, but no decision has been made to have it replace the continuous scheduler.

**Comment by mturilli** [comment]
Rerun tests (automatically) with the new jsrun installation on SummitDev

**Comment by vivek-bala** [comment]
The installation procedure previously [documented](https://docs.google.com/document/d/1rNFx2n8aAg5bp1d1I-_RjAQ8sfGQDe55SZcmXe3Xd6Y/edit#) is not applicable any more since pyzmq installation fails. I have opened a ticket with Summitdev to figure that out. Will keep this thread posted.

**Comment by vivek-bala** [comment]
Currrent installation error: https://gist.github.com/vivek-bala/571d637d9dc80a85e20fb4ca48b2af39

**Comment by mturilli** [comment]
@andre-merzky to run all this on Summit! 💃
