### ISSUE TITLE
Write documentation for Scheduler and LRMS

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1751]

**Comment by mturilli** [comment]
@vivek-bala and @andre-merzky to add their part of documentation to the google doc.

**Comment by mturilli** [comment]
@andre-merzky @lee212 to review it for Nov 27

**Comment by mturilli** [comment]
All: iterate for Dec 4

**Comment by mturilli** [comment]
Comments still need to be addressed. Reopening.

**Comment by mturilli** [comment]
@andre-merzky to review this further.

**Comment by mturilli** [comment]
@mturilli to move the documentation to the RP wiki site.

**Comment by mturilli** [comment]
Hem...

**Comment by mturilli** [comment]
@lee212 to hiterate and @mturilli to review

**Comment by lee212** [comment]
forgot this, will look at it

**Comment by iparask** [comment]
I'm closing this issue as it is stale for a while
