### ISSUE TITLE
Convert notes on using Summit into a guide

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1752]
Use wiki page at: https://github.com/radical-cybertools/radical.pilot/wiki/Guide-Summit

**Comment by lee212** [comment]
It looks like we need to collect items in one piece.

**Comment by iparask** [comment]
I am not sure if we ever did this. Either way, I think it is valuable. We need to discuss whether or not we can do it.

**Comment by mturilli** [comment]
@mturilli to write the multiagent part of the documentation about Summit. More in general, we agreed to write a page for each supported resource on the wiki and, when it is ready, to move it to the official documentation of RP (and therefore on readthedocs).

**Comment by andre-merzky** [comment]
Converted this ticket into : Document resource-config settings for each supported resource

**Comment by mtitov** [comment]
@mtitov - actions to do - create a wiki page with RCT deployment on tested machines
- keep existing descriptions together

**Comment by andre-merzky** [comment]
Summit documentation  is complete ATM
