### ISSUE TITLE
Jsrun command looks incorrect for mpi+openmp compute units

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1753]
Compute unit description:
```
cud = rp.ComputeUnitDescription()
cud.pre_exec         = ['module load cuda']
cud.executable       = '/ccs/home/vivekb/tools/Hello_jsrun/jsrun_layout'
cud.arguments        = ['|','sort']
cud.gpu_processes    = 0
cud.cpu_processes    = 1
cud.cpu_threads      = 2
cud.cpu_process_type = rp.POSIX
cud.cpu_thread_type  = rp.POSIX
```

The jsrun command looks like:
```
/opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun -n1 -a1  -E "LD_LIBRARY_PATH" -E "PATH" -E "PYTHONPATH" -E "NODE_LFS_PATH"  /ccs/home/vivekb/tools/Hello_jsrun/jsrun_layout | "sort"
```

I think the jsrun command should look like:
```
/opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun -n1 -a1 -c2 -E "LD_LIBRARY_PATH" -E "PATH" -E "PYTHONPATH" -E "NODE_LFS_PATH"  /ccs/home/vivekb/tools/Hello_jsrun/jsrun_layout | "sort"
```

**Comment by iparask** [comment]
Can you try and run both interactively and see what is happening?

**Comment by vivek-bala** [comment]
The shell script sets OMP_NUM_THREADS=2 so I think it might work. Will confirm. 

Right now, I am testing why the jsrun_layout kernel works independently but not within a CU.

**Comment by vivek-bala** [comment]
The gpu specification that causes an error is captured in https://gist.github.com/vivek-bala/76c4c1767a9a37c07b51ed3bcb893e7e. Will open a ticket with ORNL with the same.

**Comment by vivek-bala** [comment]
Created a ticket with ORNL. Heard back:
```
Thank you for letting us know. Based on the manpage I do not believe this is the expected behavior.
The software stack on summitdev is rather old and we do anticipate upgrading it at some point (although I do not have an estimate of when that will be). Hopefully that will resolve things.

(Summit has a newer stack, but I'm unable to run jobs there at present. When I'm able to again, I can give things a try there.)
```

Will probably have to wait till jsrun is updated on Summitdev.

**Comment by mturilli** [comment]
Test with the updated stack on SummitDev

**Comment by vivek-bala** [comment]
To be done by Dec 21.

**Comment by vivek-bala** [comment]
The updated jsrun no longer has the gpu specification error.

New runs: https://gist.github.com/vivek-bala/e12a13057ad8ee37ffb3a718affeaf9d.

This ticket can be closed if there are no other questions.
