### ISSUE TITLE
ORTE communication failures

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1756]
I am running a single `mpirun` CU on `Bridges`. It requires 4 nodes. It begins execution but then I experience `ORTE` failures. I was able to reproduce this error 3x. I am using the `ssh` launch method on `Bridges`

`STDOUT`:

```
        10       26449.2315           37.88m
        10       26449.2315           65.85m
         3       45305.4642          153.30m
         3       45302.9857          251.34m
         4       38658.3404          151.89m
         4       38652.4337          250.95m
         5       33346.8268          149.54m
         5       33334.5021          249.13m
        20       15660.6816           29.72m
        20       15660.6816           57.64m
         6       29063.0881          147.43m
         6       29059.2406          247.47m
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[10092,0],0] on node r537
  Remote daemon: [[10092,0],2] on node r712

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
```

[re.session.two.jdakka.017836.0002-client.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2540597/re.session.two.jdakka.017836.0002-client.tar.gz)

agent logs are too large. they can be found at `/pylon5/mc3bggp/dakka/radical.pilot.sandbox/re.session.two.jdakka.017836.0002/pilot.0000`

**Comment by andre-merzky** [comment]
I am afraid the json file in the client tarball only contains the entk entities.  @vivek-bala : how can Jumana fetch the RP DB dump, too?

**Comment by andre-merzky** [comment]
Jumana, this seems to be a problem either in the Bridge's `openmpi` installation, or in an incompatibility with some module or library used by the application.  Since you launch with `mpirun`, I assume the python code uses `mpi4py` somewhere?  Has that `mpi4py` been compiled against the openmpi from `module load mpi/gcc_openmpi`?  If not, that might be the cause of the problem.  If you are not sure, can you open the python libdir where the `mpi4py` python module lives, and I can try to verify what it was compiled against.

**Comment by jdakka** [comment]
@andre-merzky 

`which mpirun` = `/usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpirun` 

 As I indicated in the `STDOUT`, the task was able to run the application for a few iterations before `ORTE` fails. 

Added the `rp json` 
[re.session.two.jdakka.017836.0002-client.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2542830/re.session.two.jdakka.017836.0002-client.tar.gz)

**Comment by mturilli** [comment]
This ticket caught my attention as uncovered some elements of our launched methods that I was not fully understanding. I had a brief chat with Andre and I am going to leave here some notes I put together.

How to choose a CU launch method for RP:
- SSH: for non-mpi CUs, when supported by the machine (not every machines does, Bridges does)
- Default mpi installation of the machine: mpi CU (preferred method, Bridges supports MVAPICH2, OpenMPI and Intel MPI)
- Our own OpenMPI installation: only for the cases in which the default mpi installation of the machine does not support the use case (fragile, avoid if possible).

I am going to assume we are not using SSH here because we need to run mpi CUs. Are we using the system OpenMPI as a launch method? If so, did we choose OpenMPI because the CU requires it and/or RP does not support MVAPICH2 or Intel MPI as launch methods?

Both Andre and do not fully understand the details of the use case. Can we have linked in this ticket the use case document?

**Comment by andre-merzky** [comment]
> I am going to assume we are not using SSH here because we need to run mpi CUs. Are we using the system OpenMPI as a launch method? If so, did we choose OpenMPI because the CU requires it and/or RP does not support MVAPICH2 or Intel MPI as launch methods?

I can clarify those parts I think:

  - ssh is configured for non-MPI tasks, and is thus not used for the CU in this case
  - we use mpirun from the `mpi/gcc_openmpi` modules, as configured [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L594)
  - I can't remember why exactly we chose that specific module when we [added bridges support in May 2017](https://github.com/radical-cybertools/radical.pilot/pull/1370) - but I assume it was either the default mpi module, or the first one which worked for our test workloads.

To reiterate the use case / deployment point: an MPI application usually needs to be linked against the same MPI version which is used to start it - in this case `mpi/gcc_openmpi`.  You need to make sure that either your application deployment uses that module, or you need to reconfigure RP to use whatever mpirun / mpiexec your application requires.

**Comment by jdakka** [comment]
I built `mpi4py` with the `gcc` compiler from [source](https://mpi4py.readthedocs.io/en/stable/install.html). I modified the `mpi.cfg`  to the following: 

```
mpi_dir                   = /usr/mpi/gcc/openmpi-2.1.2-hfi/bin
## mpi_dir              = /usr/local
## mpi_dir              = /usr/local/mpi
## mpi_dir              = /opt
## mpi_dir              = /opt/mpi
## mpi_dir =            = $ProgramFiles\MPI

mpicc                = /usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpicc
mpicxx               = /usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpicxx

## define_macros        =
## undef_macros         =
## include_dirs         = %(mpi_dir)s/include
## libraries            = mpi
## library_dirs         = %(mpi_dir)s/lib
runtime_library_dirs = /usr/mpi/gcc/openmpi-2.1.2-hfi/lib:/usr/mpi/gcc/openmpi-2.1.2-hfi/lib64:/opt/packages/gcc/5.3.0/bin/gcc
```
Then I proceeded to run the `mpi4py` `hello world` example. 

```
module load mpi/gcc_openmpi
source activate <ve>
/usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpirun -np 5 python helloworld.py
```
* Note I am using the same `mpirun` path as that used by `RP` to execute the unit. 
* Output:

```
Hello, World! I am process 0 of 5 on br018.pvt.bridges.psc.edu.
Hello, World! I am process 1 of 5 on br018.pvt.bridges.psc.edu.
Hello, World! I am process 2 of 5 on br018.pvt.bridges.psc.edu.
Hello, World! I am process 3 of 5 on br018.pvt.bridges.psc.edu.
Hello, World! I am process 4 of 5 on br018.pvt.bridges.psc.edu.
```

I ran the actual workload ([script](https://github.com/yngtodd/constellation/blob/master/constellation/gbm/space2/optimize.py)) that uses `mpi4py` the same way I ran `hello world` on 4 compute nodes, interactively. I used the same list of pre-execs and execs as the `unit.*.sh`:

```
# Pre-exec commands
prof cu_pre_start
export PATH="/home/dakka/miniconda3/bin:$PATH" ||  (echo "pre_exec failed"; false) || exit
export LD_LIBRARY_PATH="/home/dakka/miniconda3/lib:$LD_LIBRARY_PATH" ||  (echo "pre_exec failed"; false) || exit
module load mpi/gcc_openmpi ||  (echo "pre_exec failed"; false) || exit
source activate ve_hyperspace ||  (echo "pre_exec failed"; false) || exit
prof cu_pre_stop

# The command to run
prof cu_exec_start
/usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpirun -np 4 -host r537,r707,r712,r715  python "optimize.py" "--data_path" "/pylon5/mc3bggp/dakka/hyperspace_data/constellation/constellation/data/fashion" "--results_dir" "/pylon5/mc3bggp/dakka/hyperspace_data/results_shared_fs" 
```

The output shows the correct execution until the interactive wall time is reached. It still shows the `ORTE` error at the end, though. 
```
...
        10       26449.2315           66.30m
         3       45297.3912          255.28m
         3       45300.8879          160.46m
         4       38645.9380          253.06m
         4       38656.7394          159.04m
         5       33332.5218          250.97m
         5       33341.7588          156.99m
        20       15660.6816           29.97m
        20       15660.6816           57.81m
         6       29059.3093          248.64m
         6       29060.6742          154.41m
         7       25496.3020          245.51m
         7       25512.9988          151.34m
srun: Force Terminated job 4355424
srun: Job step aborted: Waiting up to 302 seconds for job step to finish.
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[36294,0],0] on node r703
  Remote daemon: [[36294,0],3] on node r714

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
``` 

I submitted a batch script to `Bridges` to see if it's a Bridges `MPI` problem. 

```
#!/bin/bash
#SBATCH -N 4
#SBATCH -p RM
#SBATCH -t 5:00:00
#SBATCH --ntasks-per-node 28
#SBATCH -A mc3bggp


export PATH="/home/dakka/miniconda3/bin:$PATH"
export LD_LIBRARY_PATH="/home/dakka/miniconda3/lib:$LD_LIBRARY_PATH"
module purge
module load slurm/default
module load mpi/gcc_openmpi
source activate ve_hyperspace

/usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpirun -n 4 python optimize.py --data_path /home/dakka/hyperspace/constellation/constellation/data/fashion --results_dir /home/dakka/hyperspace/constellation/constellation/gbm/space2/results_local_data

```

So far it's running for > 1 hour, which is longer than my RP jobs can run without running into the `ORTE` issue. I set the wall-time to 5 hours, so give enough time to see if the `ORTE` issue shows up. I'll post the final results here once I get the entire logs.

**Comment by andre-merzky** [comment]
thanks Jumana, this is quite interesting.  

There is one more thing I would like to ask you to try: can you please add `env > env.log` in the unit's `pre-exec` list?  That should create an `env.log` in the unit sandbox.  Can you send this to me for cleanup?  After doing so, I would ask you to rerun the manual test which seems to work, but with the env settings we just captured.  If we still don't get any insight, we should probably open a ticket with the sysadmins, to see if they have any advise - it's their OpenMPI installation after all...

**Comment by jdakka** [comment]
Apologies for delayed response, I was testing several duration all of last week to see at approximately what duration the issue surfaces. 

Fortunately/unfortunately the issue disappeared... I was able to run anywhere from 4 -> 16 MPI processes successfully for up-to 24 hour durations (1 hour, 2 hours, 5 hours, and 24 hours testing) with RCT. With several repetitions...

* It seems that the `OpenMPI` instability seems to have "stabilized" itself. Nevertheless it might be a good idea to notify `Bridges` about their `OpenMPI-gcc` installation. What do you think @andre-merzky? 
* @andre-merzky I captured all the `env.log` files for these tests, let me know if you need access to them.

**Comment by andre-merzky** [comment]
First,  I am glad this works now.  Phew! :-)

Yes, it might make sense to notify bridges support - but I honestly doubt they will (or want) to do anything.  I would leave it to you to decide if you want to open a ticket.  One metric might be on how much you want to use bridges in the future - if you need to rely on it for several months, it would be good to get some clarity.

I am happy to not look deeper into this if that works now.  If it reappears, please do capture the env settings again...
