### ISSUE TITLE
Create a Travis CI testing scheme

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1762]

**Comment by iparask** [comment]
https://travis-ci.org/radical-cybertools/radical.pilot

It turns green!

**Comment by iparask** [comment]
I created a test matrix, that means that we can see what fails and not to have to go through a huge number of lines with messages and such.

Right now, Travis is triggered with every commit in this branch. As we move forward, I suggest that Travis is triggered with every PR and as a crone job for devel and master. What do you think?

**Comment by andre-merzky** [comment]
> As we move forward, I suggest that Travis is triggered with every PR and as a crone job for devel and master. What do you think?

I agree.  Thanks!
