### ISSUE TITLE
Supporting checkpointing for applications that do not finish execution in a single run 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1763]
I would like to start a discussion regarding a use-case that has an MPI application which requires checkpointing because it cannot complete in the given walltime provided by most batch systems. Currently, the CU does not finish execution, and RP cannot provide the timestamp for `cu_exec_stop`. The pilot state shows `CANCELED` and cannot proceed to `AGENT_STAGING_OUTPUT_PENDING`. Therefore in my runs I am missing the analytical data that would show the correct overheads for the pilot and the units.

**Comment by andre-merzky** [comment]
I implemented a unit timeout.  The next step would be to progress to the staging states on timeout.  After that we need to catch the pilot timeout early enough (whatever this means), and then trigger timeout for all pending units.

**Comment by lee212** [comment]
It seems this is ongoing task according to the [wiki](om/radical-cybertools/radical.pilot/wiki/2019-01-30)

**Comment by iparask** [comment]
@andre-merzky, @lee212 is this done?

**Comment by andre-merzky** [comment]
No, this is not done - and I doubt we'll find the time for doing so until a current use case emerges (again).  Use cases requesting this feature come up from time to time, so I think this is a sufficiently supported feature request in general.

**Comment by iparask** [comment]
Then it's stays open
