### ISSUE TITLE
unable to redirect task output/error to specific file

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1765]
If the task executable itself wants to redirect the output/error to a specific file, it is currently not possible. This is due to the fact the RP itself redirects the output+error and overwrites that done by the task executable.
Example:
```
cud.executable = '/bin/cat'
cud.arguments = ['file1.txt', 'file2.txt', '>', 'output.txt']
```

output.txt is empty because the above translates to the following lines in the unit.*.sh script:
```
cat "file1.txt" "file2.txt" > "output.txt"  1>/home/vivek/radical.pilot.sandbox/re.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017849.0354/pilot.0000/unit.000000/STDOUT 2>/home/vivek/radical.pilot.sandbox/re.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017849.0354/pilot.0000/unit.000000/STDERR
```

**Comment by vivek-bala** [comment]
Hmmm okay. Let me test this out. This seems to be something new as I was able to redirect stdout/stderr using the above method previously.

**Comment by andre-merzky** [comment]
That this has worked might well be, but is really coincidental.  RP makes not promise in any way that the arguments end up on a shell command line.  This is bound to break for a nnumber of LM and Executor combinations...

**Comment by vivek-bala** [comment]
Yea, I agree with that. Works with cud.stdout and cud.stderr! Thanks.
