### ISSUE TITLE
Propose methods for specifying what files to include (or exclude) from testing

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1774]

**Comment by vivek-bala** [comment]
Please see 'omit' tag that can be added to the .coveragerc https://coverage.readthedocs.io/en/coverage-4.2/config.html

**Comment by iparask** [comment]
I added this file:

https://github.com/radical-cybertools/radical.pilot/blob/feature/lm_tests/.coveragerc

**Comment by andre-merzky** [comment]
This looks good to me - thanks.  `include` is much easier than `exclude`, at least for the time being, I'm glad that's available...
