### ISSUE TITLE
LFS path that contain evnironment variables do not expand

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1775]
An example is the following. On Bridges the local filesystem of the nodes is accessed by `$LOCAL`. The scheduler put that value to the CUs environment with the key `NODE_LFS_PATH`. Using the `popen` executor and `ssh` as the launch method creates the following confilct:

The Launch Method passes through ssh the `NODE_LFS_PATH=$LOCAL` and the executor adds in the unit script the following line:
`export NODE_LFS_PATH=$LOCAL` 

When `$LOCAL` is not present in the new `ssh` connection then the line in the script will empty the environment variable `NODE_LFS_PATH`, assuming that it was passed correctly by the `ssh` command. 

I propose the following solution:
In LRMS check if the lfs path has environment variables in it, by simple checking if there is a `$`, if yes then expand it with something like [`os.path.expandvars`](https://docs.python.org/2/library/os.path.html#os.path.expandvars)

That way the `NODE_LFS_PATH` will always be an absolute value and exporting inside the script should do the trick. I also checked the resources that have environment variables as LFS. They all depend on values that have to do with the jodid and/or userid, so the assumption that it is the same for all nodes still holds

**Comment by andre-merzky** [comment]
I think you are saying that in some cases `$LOCAL` is not set on the compute node, and thus needs to be expanded on the agent node?  Can you please past the currently resulting unit shell script?

I agree with the os.path.expandvars`.  You don't need to check for `$` though - the `expandvars` implementation checks that (almost) immediately anyway.

**Comment by iparask** [comment]
On a Bridges compute node `$LOCAL` is `/local/4608983` the number there is the jobid. Everytime we run something it will change. If I ssh from the agent node to another compute node that variable is gone.
Before the proposed change:
```shell
#!/bin/sh


# Environment variables
export RP_SESSION_ID="just_a_stage"
export RP_PILOT_ID="pilot.0000"
export RP_AGENT_ID="agent_0"
export RP_SPAWNER_ID="agent_0.executing.0.child"
export RP_UNIT_ID="unit.000000"
export RP_GTOD="/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/just_a_stage/pilot.0000/gtod"
export RP_TMP="None"
export RP_PROF="/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/just_a_stage/pilot.0000/unit.000000/unit.000000.prof"

prof(){
    if test -z "$RP_PROF"
    then
        return
    fi
    event=$1
    now=$($RP_GTOD)
    echo "$now,$event,unit_script,MainThread,$RP_UNIT_ID,AGENT_EXECUTING," >> $RP_PROF
}
export OMP_NUM_THREADS="1"
export "NODE_LFS_PATH=$LOCAL"

prof cu_start

# Change to unit sandbox
cd /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/just_a_stage/pilot.0000/unit.000000
prof cu_cd_done

# Pre-exec commands
prof cu_pre_start
module load psc_path/1.1 ||  (echo "pre_exec failed"; false) || exit
module load slurm/default ||  (echo "pre_exec failed"; false) || exit
module load intel/17.4 ||  (echo "pre_exec failed"; false) || exit
module load python3 ||  (echo "pre_exec failed"; false) || exit
source $SCRATCH/pytorchCuda/bin/activate ||  (echo "pre_exec failed"; false) || exit
hostname ||  (echo "pre_exec failed"; false) || exit
echo $NODE_LFS_PATH ||  (echo "pre_exec failed"; false) || exit
prof cu_pre_stop

# The command to run
prof cu_exec_start
python3 "tile_raster.py" "--scale_bands=299" "--input_image=WV03_20141107053034_1040010004196C00_14NOV07053034-P1BS-500248187200_01_P005_u08rf3031.tif" "--output_folder=./"
RETVAL=$?
prof cu_exec_stop

# Exit the script with the return code from the command
prof cu_stop
exit $RETVAL
```

and after:
```shell
#!/bin/sh


# Environment variables
export RP_SESSION_ID="just_a_stage"
export RP_PILOT_ID="pilot.0000"
export RP_AGENT_ID="agent_0"
export RP_SPAWNER_ID="agent_0.executing.0.child"
export RP_UNIT_ID="unit.000000"
export RP_GTOD="/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/just_a_stage/pilot.0000/gtod"
export RP_TMP="None"
export RP_PROF="/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/just_a_stage/pilot.0000/unit.000000/unit.000000.prof"

prof(){
    if test -z "$RP_PROF"
    then
        return
    fi
    event=$1
    now=$($RP_GTOD)
    echo "$now,$event,unit_script,MainThread,$RP_UNIT_ID,AGENT_EXECUTING," >> $RP_PROF
}
export OMP_NUM_THREADS="1"
export "NODE_LFS_PATH=/local/4608983"

prof cu_start

# Change to unit sandbox
cd /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/just_a_stage/pilot.0000/unit.000000
prof cu_cd_done

# Pre-exec commands
prof cu_pre_start
module load psc_path/1.1 ||  (echo "pre_exec failed"; false) || exit
module load slurm/default ||  (echo "pre_exec failed"; false) || exit
module load intel/17.4 ||  (echo "pre_exec failed"; false) || exit
module load python3 ||  (echo "pre_exec failed"; false) || exit
source $SCRATCH/pytorchCuda/bin/activate ||  (echo "pre_exec failed"; false) || exit
hostname ||  (echo "pre_exec failed"; false) || exit
echo $NODE_LFS_PATH ||  (echo "pre_exec failed"; false) || exit
prof cu_pre_stop

# The command to run
prof cu_exec_start
python3 "tile_raster.py" "--scale_bands=299" "--input_image=WV03_20141107053034_1040010004196C00_14NOV07053034-P1BS-500248187200_01_P005_u08rf3031.tif" "--output_folder=./"
RETVAL=$?
prof cu_exec_stop

# Exit the script with the return code from the command
prof cu_stop
exit $RETVAL
```

**Comment by iparask** [comment]
In the first case the `echo $NODE_LFS_PATH` returns an empty string, while in the second the correct value

**Comment by andre-merzky** [comment]
Ack, makes sense.

**Comment by vivek-bala** [comment]
Yes, that's my understanding as well. Given that, do you think it makes sense to do something like the following in the shell script:
```
if [ -z "$NODE_LFS_PATH" ]; then
    export "NODE_LFS_PATH=$LOCAL"
fi
```

This guards the case if the env variable is not available to the agent process, but is available to the compute process (it will attempt to overwrite NODE_LFS_PATH iff the LRMS did not set it).

What do you think?

**Comment by andre-merzky** [comment]
That guard should not be needed.  In my experience, the job (and thus the agent) should always see the full LRMS env.  If we ever hit a case where $LOCAL is set but different on the compute nodes, we probably need to rethink the approach anyway.  Lets go there once we see such a system...

**Comment by iparask** [comment]
First, if it is not set, it means that there is no local filesystem. Wrangler and Stampede2 are two examples. Comet on the other hand does `/scratch/$USER/$SLURM_JOBID` which is different from Bridges `$LOCAL`

Also, I agree with @andre-merzky .
