### ISSUE TITLE
Review test case configuration for exception testing

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1778]

**Comment by iparask** [comment]
The `if` statements inside the `for` loop tests also for exceptions: https://github.com/radical-cybertools/radical.pilot/blob/feature/lm_tests/tests/lm/unit/test_rsh.py#L64

An example of an unit that does that is https://github.com/radical-cybertools/radical.pilot/blob/feature/lm_tests/tests/test_cases/unit.000008.json#L36

**Comment by andre-merzky** [comment]
@iparask : Looks good to me!
