### ISSUE TITLE
Expand test to resource manager

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1779]

**Comment by andre-merzky** [comment]
no progress on my end, apologies.

**Comment by iparask** [comment]
@andre-merzky should we wait for you before we move forward with creating test?

**Comment by mturilli** [comment]
@iparask if you are ready to proceed on this, I would say please go ahead 👍

**Comment by andre-merzky** [comment]
Still no progress on my end, apologies.

**Comment by iparask** [comment]
Pushed slurm rm unit test!

**Comment by iparask** [comment]
@andre-merzky here is the last build: https://travis-ci.org/radical-cybertools/radical.pilot/builds/492388128

**Comment by mturilli** [comment]
@andre-merzky to review this.

**Comment by mturilli** [comment]
Ongoing.
@vivek-bala, @andre-merzky, @lee212 to write a test by Apr 9th

**Comment by iparask** [comment]
This is done
