### ISSUE TITLE
test jsrun layouts on summitdev

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1783]
jsrun versions are now in sync between summit and summitdev, and we can test.

**Comment by vivek-bala** [comment]
Currently encountering the same error that Giannis seems to have encountered from the email thread with Tom. Basically, jsrun can't seem to read resource layout files.

I acquired a node interactively and performed the following commands:
```
$ jsrun -n1 -a1 -S resource-file hostname
summitdev-r0c0n14
$ cat resource-file
RS 0: { host: 2, cpu: 0 , mem: 0-13107 }
$ jsrun -n1 -a1 -U resource-file hostname
ERROR: Not enough resources available to schedule job.
The resource file >>resource-file<< could not be opened.
Error when reading resource file resource-file
```

I have opened a new ticket with ORNL. Will keep everyone posted.

**Comment by iparask** [comment]
I think that the entries are not entirely correct. You have one node and in the resource file you specified host number 2 instead of host number 1 may I suggest a rerun with a resource file that look like:
```
RS 0: { host: 1, cpu: 0}
```

Let's not request any memory for the time being.

**Comment by vivek-bala** [comment]
Please see the results from testing the layout file mode of jsrun on Summitdev at https://gist.github.com/vivek-bala/2bc5857e437dce2972e8faab5e886e6f.

Note (please see above gist first):
* Summit is available now.
* '-n' and '-U' flags cannot be used together on Summit (although they can be on Summitdev). Number of resource sets is determined from the description in the layout file.

**Comment by iparask** [comment]
Okay! As I understand it, the way the resource file is created by the respective launch method works correctly with single core executables and signle threaded MPI executables. Am I correct here?

I will launch something tomorrow morning where I will submit several single core units on SummitDev and Summit

**Comment by vivek-bala** [comment]
> Okay! As I understand it, the way the resource file is created by the respective launch method works correctly with single core executables and signle threaded MPI executables. Am I correct here?

Yes, I think we are ready to support tasks with N MPI processes, 1 thread per process. 

As for the multi-threaded case (1 MPI process+M threads per process, N MPI processes+M threads per process), currently, we can control which physical core they use but not which HW thread of the physical core they use. We might need to use additional flags, but more importantly, it seems like this can't be tested on Summitdev.

> I will launch something tomorrow morning where I will submit several single core units on SummitDev and Summit

Sounds good. I'll see if I can run some tests on Summit by tomorrow.

**Comment by vivek-bala** [comment]
FWIW I can't log into Summit. The sys admins I was working with did tell me it is back online. I created a ticket for my connectivity issue. Can others log into Summit?
