### ISSUE TITLE
Update Instruction for VE creation on Summit

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1784]

**Comment by mturilli** [comment]
Ongoing.

**Comment by iparask** [comment]
I got access on Summit. I'll check the next couples of days

**Comment by iparask** [comment]
The ways to create a VE with the RCT on Summit are:

## Way 1

First, clone RCT repos and checkout the Summit branches for RP and SAGA.

```bash
module load python/2.7.15-anaconda2-5.3.0
module load zeromq
conda create -n rct_env python=2.7
pip install radical.utils
pip install saga-python/ --upgrade
pip install radical.pilot/ --upgrade
```

## Way 2

First, clone RCT repos and checkout the Summit branches for RP and SAGA.

```bash
module load python/2.7.15
module load zeromq
wget https://raw.githubusercontent.com/radical-cybertools/radical.pilot/devel/bin/radical-pilot-create-static-ve
chmod +x radical-pilot-create-static-ve
./radical-pilot-create-static-ve rct_env
pip install saga-python/ --upgrade
pip install radical.pilot/ --upgrade
```

**Comment by vivek-bala** [comment]
FYI Way 1 doesn't seem to be applicable any more. RU installation fails. Can someone else also verify?

**Comment by mturilli** [comment]
To be retested by @vivek-bala and @iparask

**Comment by iparask** [comment]
Is this still going on? I think our users are able to run on Summit as a result I will close this issue
