### ISSUE TITLE
Test end-to-end using multiple generations and different units

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1787]
I am testing the following configurations:

* [x] Single Core Unit 60 seconds per unit 1 node 2 generation
* [x] Single Core Unit 60 seconds per unit 2 nodes 2 generation
* [x] Dual-Core Unit 60 seconds per unit 1 nodes 2 generation
* [x] Dual-Core Unit 60 seconds per unit 2 nodes 4 generation
* [x] Random number of MPI processes from 1 to 20, Unit 60 seconds per unit 1 node 2 generation
* [ ] Random number of MPI processes from 1 to 40,  Unit 60 seconds per unit 2 nodes 2 generation

**Comment by mturilli** [comment]
@andre-merzky ongoing

**Comment by andre-merzky** [comment]
@andre-merzky : implement rate limiter

**Comment by mturilli** [comment]
Ongoing and broken. Partially blocked by #1806. We are hitting jsrun too fast, implementing a configurable limiter.

**Comment by andre-merzky** [comment]
rate limiter is obsolete per #1817, workload tests are underway

**Comment by iparask** [comment]
Closing as it is was done
