### ISSUE TITLE
Document unit description with examples of different configurations

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1788]
@iparask to give it a first go; @mturilli to iterate; @andre-merzky, @vivek-bala and @lee212 to review once done.

**Comment by iparask** [comment]
https://docs.google.com/document/d/1N2x08FkDsui6jnHazIBrfYdQ8GGyDTBGqA887F_wpTo/edit

**Comment by mturilli** [comment]
Iterate without table representation.

**Comment by mturilli** [comment]
Ongoing

**Comment by iparask** [comment]
I did an iteration, pleas take a look

**Comment by lee212** [comment]
This is completed.
