### ISSUE TITLE
Bug in jsrun launch method

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1790]
The flags we set are:

```python
flags = '-U %s -n%d -a%d ' % ('%s/rs_layout_cu_%s' % (task_sandbox,cu['uid']), task_procs, task_procs)
```

Based on JSRUN documentation the above flags are:
```bash
-bash-4.2$ jsrun --help
Usage: jsrun [OPTION...] [<command>]

  -a, --tasks_per_rs=<#>     Tasks per Resource set
  -n, --nrs=<# | ALL_HOSTS>  Number of resource sets.
  -U, --use_resources=<filename>   Filename with path where read resource
                             allocation.
```

So we should do 
```python
flags = '-U %s -n%d -a1 ' % ('%s/rs_layout_cu_%s' % (task_sandbox,cu['uid']), task_procs)
```

**Comment by mturilli** [comment]
Fixed in #1792

**Comment by mturilli** [comment]
@iparask to add a test for this. Once merged, we will close this ticket.

**Comment by iparask** [comment]
I fixed the test based on the changes that the launch method. But there is a bug in the launch method resource file construction.

Right now it does:
```python
            cores = ' '.join([str(core_set[0]) for core_set
                                               in  node['core_map']])
            gpus  = ' '.join([str(gpu_set[0])  for gpu_set
                                               in  node['gpu_map']])
```
which only takes the first core or GPU assigned to a process. I'll fix it and push!

**Comment by andre-merzky** [comment]
True, that would place the threads on the process cores, which is not what we want...  Thanks!

**Comment by andre-merzky** [comment]
Note: use one or more processes per resource set?  Consider that `-a n` only works for `n==1` right now.

**Comment by mturilli** [comment]
Depends on #1806 . Once implemented, this ticket should be closed as `-a` will be deprecated.

**Comment by mturilli** [comment]
Made obsolete by ERF syntax.
