### ISSUE TITLE
fix/scheduler_delays testing discussion

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1798]
I am moving the discussion of PR #1793 in here since it will clatter the PR with irrelevant questions>

@andre-merzky, here are the log files you requested. There are no errors in them.
[pilot.0000.log.zip](https://github.com/radical-cybertools/radical.pilot/files/2818660/pilot.0000.log.zip)

**Comment by iparask** [comment]
I see in the profile: 
```
[paraskev@login006 unit.000000]$ cat unit.000000.prof
1548796493.550688,cu_start,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
1548796493.557000,cu_cd_done,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
1548796493.568438,cu_pre_start,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
1548796493.729260,cu_pre_stop,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
1548796493.732816,cu_exec_start,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
1548797276.484939,cu_exec_stop,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
1548797276.490023,cu_stop,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
```
I also see the output as expected. Let me check the DB entry

**Comment by andre-merzky** [comment]
So, the CU finished but the agent did not learn about that...  what was the pilot runtime?

**Comment by iparask** [comment]
Yes. it was 2 hours but I killed it after half an hour of nothing happening. I'm running again to see what is happening!

**Comment by andre-merzky** [comment]
The unit runs for 13 min (according to the profiles above).  In the executor I see:

```

**Comment by andre-merzky** [comment]
Is this reproducible?  I still consider this to be a termination issue: the pilot cancellation killed the unit.  Any proposed action?

**Comment by iparask** [comment]
Closing as it is stale.
