### ISSUE TITLE
switch from jsrun rs format to erf

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1806]
See [here](https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/jsm/10.2/base/jsrun.html) and [here](https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/jsm/10.2/base/erf_format.html)

**Comment by andre-merzky** [comment]
ERF also allows to specify the command line in the file itself.  We should do that if possible, as it unclutters the shell script.  Note that multiple applications can be specified, so we can in principle run bulk-tasks.  that only makes sense for tasks which are somewhat uniform in runtime ...

**Comment by iparask** [comment]
>Note that multiple applications can be specified, so we can in principle run bulk-tasks. that only makes sense for tasks which are somewhat uniform in runtime ...

I agree with your there, since the example assumes a master/worker paradigm.

I have one question though. In the case of an MPI application which also uses GPU(s), how do we assign GPUs to a rank? Would it make sense to start from the first rank that drops to a node and continue from there?

**Comment by andre-merzky** [comment]
I don't think we can actually assign a GPU to a specific rank: (a) we don't know what process will be assigned what rank ID by MPI, and (b) we cannot set individual env vars per rank.

**Comment by iparask** [comment]
I agree with (a), but not (b). examples 9 and below from the `ERF` file shows that we can set which rank is going to use the GPU.

@mturilli, @vivek-bala do we have a use case where an MPI application requires a GPU or multiple GPUs? Can we ask which rank is going to use the GPUs? 

I want to see how test case:  "6 CU, each using n cores and 1 GPU on 1 work node" from Matteo's email

**Comment by andre-merzky** [comment]
> we can set which rank is...

Fair enough.  But since we do not distinguish that in our CU description, lets leave this out...

**Comment by vivek-bala** [comment]
Yes, we do. In the Princeton use case, each task (with specfem as executable) requires use of 384 GPUs. specfem is an MPI application that will spawn 384 processes each of which use 1 GPU. But compiling specfem can be difficult though. I don't think the Princeton folks have given it a try on Summit yet.

**Comment by iparask** [comment]
So I will place the GPU with the first process that is placed to a node and continue in a FCFS theme.

For example, ranks 1,2,3,4 are placed on the same node and we want 2 GPUs, I will assign the first gpu to rank 1 and the second with rank 2.

Is that okay?

**Comment by mturilli** [comment]
INSPIRE (and possibly Arvind's) use cases may have to run ML code with up to 32 GPUs. 

The proposed approach seems OK, what would be alternative approaches? How do we evaluate them?

**Comment by andre-merzky** [comment]
> INSPIRE (and possibly Arvind's) use cases may have to run ML code with up to 32 GPUs.
> The proposed approach seems OK, what would be alternative approaches? How do we evaluate them?

The scheduler will make sure that there's always at least one process on the node on which a GPU is allocated for the task.  The CU will be placed correctly.

IIUC, Ioannis question is not really about how to place the processes and GPUs (or how to schedule them), but 'just' about the question: if on a node, the scheduler decided to put more processes than GPUs, what process should get the GPU assigned?

Semantically we don't care for any of the use cases discussed in this ticket, AFAICS, because those use cases seem to require one GPU per rank, and the mapping is then trivial.

(@iparask : correct me if the above is wrong...)

> So I will place the GPU with the first process that is placed to a node and continue in a FCFS theme

Yes, for the time being that is what we should do.  We can move this decision to the scheduler once we see use cases where this is insufficient.

**Comment by iparask** [comment]
@andre-merzky since we require a GPU per rank then you are right!

> Yes, for the time being that is what we should do. We can move this decision to the scheduler once we see use cases where this is insufficient.

Let's discuss during our next dev call what can be a possible solution when the number of processes and GPUs are different!

Thank you all for the input!

**Comment by andre-merzky** [comment]
> Let's discuss during our next dev call what can be a possible solution when the number of processes and GPUs are different!

Didn't you state the solution above: FCFS?  When GPUs are exhausted, the remaining ranks will not get one.

**Comment by mturilli** [comment]
Done.
