### ISSUE TITLE
No REPORT in Getting Started Tutorial

### ISSUE THREAD

**Issue by uvaaland** [radical-cybertools/radical.pilot#1807]
Hi, I am running the example provided at the following link:

https://radicalpilot.readthedocs.io/en/latest/user_guide/00_getting_started.html

The program runs fine in my VM, but there is no output report, even though I am running with the flag `RADICAL_PILOT_VERBOSE=REPORT`. That is, I am not getting the report that is shown at the bottom of the above link.

I have also searched all the session folders, but cannot find a report.

**Comment by uvaaland** [comment]
Attached is the exact script that I am running:

[script.zip](https://github.com/radical-cybertools/radical.pilot/files/2841725/script.zip)

**Comment by vivek-bala** [comment]
Hey uno, can you try it again by specifying the environment variable in the terminal (as opposed to the script):
```
RADICAL_PILOT_VERBOSE=REPORT python 00_getting_started.py
```

**Comment by uvaaland** [comment]
Yes, I have tried that, and the result is the same. So the program runs fine, and I have checked the unit.0000*/STDOUT to verify that the execution is correct.

The only issue is that the above command prints no information or report.

**Comment by andre-merzky** [comment]
Thanks for your report (ha!)

Please try once more with `RADICAL_REPORT=True`.  The documented setting should work though, too - I'll look into it.

**Comment by uvaaland** [comment]
That works like a charm. It prints and I get a `radical.pilot.rep` file. How does one inspect this file? It looks a little funky when I open it in `vim`.

**Comment by andre-merzky** [comment]
Yeah, it's not really formatted for  human consumption, because of all the color code sequences.  You can replay it on the Terminal with `cat radical.pilot.rep` :-)  I should think of a better storage format - but so far that doesn't exist.  Let me know if this is important to you, and I can whip something up.  Like, storing the current format without colors and animations would make the file mostly readable, and is easy to implement.

**Comment by uvaaland** [comment]
Not at all, it was just a curiosity. That is all I have on my end, thanks for the help guys! :)

**Comment by andre-merzky** [comment]
Cool.  Please leave this ticket open - I need to either fix the setting or update the documentation....

**Comment by andre-merzky** [comment]
Documentation was updated meanwhile.
