### ISSUE TITLE
Disk quota reached on bridges

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1810]
I hit disk quota with my new runs. I've off-shored my data from `/pylon5/mc3bggp/dakka` (apart from static VEs) into another storage repository (not on Bridges). However this issue is still persistent leading me to believe that our project directory is approaching the storage limit. 

`projects` shows:

```
Resource: BRIDGES PYLON STORAGE
Allocation: 20,500.00
Balance: 12,307.83
```

Is there anything we can do to increase the storage on `/pylon5/`?

**Comment by iparask** [comment]
The disk quota is 20TBs on Bridges and that shows that 8TB are free. Can you include your pilot description and the client log files?

**Comment by jdakka** [comment]
[debug.log](https://github.com/radical-cybertools/radical.pilot/files/2856581/debug.log)
[re.session.two.jdakka.017938.0023.tar.zip](https://github.com/radical-cybertools/radical.pilot/files/2856582/re.session.two.jdakka.017938.0023.tar.zip)

`entk` resource description: 

```
  res_dict = {

        'resource': 'xsede.bridges',
        'project' : 'mc3bggp',
        'queue' : 'RM',
        'access_schema': 'gsissh',
        'walltime': 10,
        'cpus': 28
    }
```

**Comment by iparask** [comment]
Can you recreate the zip without creating a tar ball? I am not able to open it. Thank you!

**Comment by iparask** [comment]
Also, can you run a `du -sh` in your home directory in Bridges? The quota there is 10GB and SAGA is trying to create a file there.

**Comment by jdakka** [comment]
> Also, can you run a `du -sh` in your home directory in Bridges? The quota there is 10GB and SAGA is trying to create a file there.

This is the issue. I didn't realize that `saga` needs space in the home directory, I assumed everything was done in the project directory
