### ISSUE TITLE
RP support on Amarel (rutgers cluster)

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1813]
This is a requirement coming from the sea level rise project

**Comment by andre-merzky** [comment]
Can you add a pointer to Amarel's documentation, please?  How do we get access?  Thanks!

**Comment by iparask** [comment]
https://rutgers-oarc.github.io/training/

**Comment by andre-merzky** [comment]
@iparask , @mturilli : How do we get access?

**Comment by iparask** [comment]
As far as I understand Amarel is supported. I am closing this issue
