### ISSUE TITLE
Bridges default queue in config is incorrect

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1816]
The default queue specified in the [config file](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L599) is 'normal'. The default should be one of https://www.psc.edu/bridges/user-guide/running-jobs#partitions.

**Comment by andre-merzky** [comment]
Thanks @vivek-bala !  @iparask : can you suggest a suitable partition?

**Comment by lee212** [comment]
I believe this is NOT resolved yet. I suggest `RM` partition as a default.
