### ISSUE TITLE
netifaces conflict between RCT tools

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1820]
RU doesn't specify a version, so 0.10.9 gets installed. [See](https://github.com/radical-cybertools/radical.utils/blob/devel/setup.py#L293)
RP requires 0.10.4. [See](https://github.com/radical-cybertools/radical.pilot/blob/devel/setup.py#L234).

Error/warning during EnTK installation:
```
Successfully built radical.entk radical.pilot
radical-pilot 0.50.22 has requirement netifaces==0.10.4, but you'll have netifaces 0.10.9 which is incompatible.
```

**Comment by iparask** [comment]
@andre-merzky I suggest we completely remove the version requirement from RP as well. Otherwise it creates installation issues. Would you agree?

**Comment by andre-merzky** [comment]
Yes - that's already in the upcoming release.

**Comment by andre-merzky** [comment]
closed as fixed.
