### ISSUE TITLE
Documentation 3.2 - $ radicalpilot-version

### ISSUE THREAD

**Issue by rfauza** [radical-cybertools/radical.pilot#1825]
In the documentation for Radical Pilot, section 3.2 suggests a sanity check using the command $radicalpilot-version. This command does not work, installed package contains $radical-pilot-version

**Comment by andre-merzky** [comment]
Thanks for the ticket!  This is already fixed in the documentation source - I rebuilt the docs now to fix the [pages](https://radicalpilot.readthedocs.io/en/latest/installation.html#id1).
