### ISSUE TITLE
Iterate on the shell script for integration tests

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1834]
We should test for the actual placement of processes on the landing nodes. The current script should be rewritten so to do this.

**Comment by vivek-bala** [comment]
@vivek-bala to change assertions to compare output (string) with expected output

**Comment by mturilli** [comment]
@vivek-bala Integrate current tests and then start to iterate them increasing granularity.

**Comment by andre-merzky** [comment]
check on string, compare to lm_testing

**Comment by iparask** [comment]
If my memory serves well, Vivek did finish this.
