### ISSUE TITLE
Synchronize Summit test folder with the rest of the tests.

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1835]

**Comment by mturilli** [comment]
@andre-merzky to fix test for base class

**Comment by iparask** [comment]
It is the `test_create` in `test_base.py`. [Link](https://github.com/radical-cybertools/radical.pilot/blob/feature/tests_sync/tests/test_lm/test_unit/test_base.py#L32) @andre-merzky can you check that is passes correctly?

**Comment by andre-merzky** [comment]
blocked: nothing passes on summit right now, really...

**Comment by iparask** [comment]
Closing as inactive
