### ISSUE TITLE
Backporting of Message Channel Support

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1837]
This is about additional ZMQ bridges for application use, for example, pushing a message instead of writing an intermediate file between ENTK tasks. This feature is scheduled to Version 2 but backporting is requested to leverage this new feature beforehand.

**Comment by andre-merzky** [comment]
This can likely happen before v2, thus left open.

**Comment by andre-merzky** [comment]
This is implemented now - have a look at [this example](https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/misc/rp_app_comm.py) on how to use it.  The same directory also contain the worker and clients using the comm channels.
