### ISSUE TITLE
EnTK post-exec example fails with SHELLFS spawner but works with POPEN spawner

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1838]
> Please provide all error messages and the output of the following commands:

```
$ python -V
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/ves/ve-entk

  radical.entk         : 0.7.16-0.7.16-3-gb4b98683@devel
  radical.pilot        : 0.50.22
  radical.utils        : 0.50.3
  saga                 : 0.50.5

```

> If you can reproduce the problem, it would greatly simplify debugging if you can provide a minimal code example which we can use to reproduce the problem too.

Issue can be reproduced by running [this](https://github.com/radical-cybertools/radical.entk/blob/master/tests/test_integration/test_post_exec.py) EnTK test with SHELLFS spawner on localhost.

> On **most** tickets we will ask you to provide additional information, most often log files. You can obtain detailed logs by rerunning your code after setting the following environment variables:

Logfiles attached
[re.session.two.vivek.017975.0014.zip](https://github.com/radical-cybertools/radical.pilot/files/2990105/re.session.two.vivek.017975.0014.zip)

Sandbox is located on radical.two at /home/vivek/radical.pilot.sandbox/re.session.two.vivek.017975.0014

**Comment by iparask** [comment]
Is there any information about this issue?

**Comment by andre-merzky** [comment]
No, it's still a mystery (mostly because we did not invest time in debugging).  I would still like to keep the shellfs spawner alive: it's actually faster than popen, has better env isolation and process management, and is a fallback if popen gives us troubles.   But we would need to invest some resources in maintaining it...

**Comment by andre-merzky** [comment]
ShellFS spawner can be retired

**Comment by mturilli** [comment]
Close this ticket once shellfs is removed.

**Comment by mturilli** [comment]
@andre-merzky I think shellfs has been now removed?

**Comment by andre-merzky** [comment]
> @andre-merzky I think shellfs has been now removed?

It has.
