### ISSUE TITLE
Wrong sandbox location on summit

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1847]
According to the [config](https://github.com/radical-cybertools/radical.pilot/blob/fix/issue_1830/src/radical/pilot/configs/resource_ornl.json#L247)
the sandbox should be in $MEMBERWORK. 

My $MEMBERWORK points to `/gpfs/alpine/scratch/jdakka` 

However my sandbox is created in the $HOME directory which is `ccs/home/jdakka/radical.pilot.sandbox/re.session.login1.jdakka.017989.0002/pilot.0000`

Stack: 
```
  radical.entk         : 0.7.14-0.7.15-2-g5e5b1cb@fix-1830
  radical.pilot        : 0.50.22-v0.50.22-189-g3ac6a19@fix-issue_1830
  radical.utils        : 0.50.3
  saga                 : 0.50.0-v0.50.0-22-g8c260f8@feature-summit
```

*Could you make the changes in that fix since I need the `jsrun` flag to be parsed into the command (`smpi`)

**Comment by iparask** [comment]
Yeah, `$MEMBERWORK` is not writable. Somehow the pilot sandbox should go in `$MEMBERWORK/$PROJECT`.

**Comment by andre-merzky** [comment]
Hmm...  Are you sure you are using the correct resource label - can you please verify?

**Comment by andre-merzky** [comment]
> @andre-merzky , do you think it would make sense to pick the project name from the pilot description?

We do not yet have the ability to put placeholders like that in the config files.  But that is being implemented and we'll be able to do something like this in one of the next releases.

**Comment by andre-merzky** [comment]
PS.: are you aware that RP support for summit is broken for almost all use cases?  Ses [here](https://github.com/radical-cybertools/radical.pilot/wiki/summit-jsrun)

**Comment by andre-merzky** [comment]
Fixed by now
