### ISSUE TITLE
Support ssh access to Cheyenne

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1853]
Currently only 'local' is supported: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_ncar.json#L31

**Comment by andre-merzky** [comment]
We can create a config for that - but any connection setup etc. will have to happen outside of RP, because of the Yubi-key requirements.

**Comment by andre-merzky** [comment]
I added an ssh config entry to the `fix/cheyenne` branch.
