### ISSUE TITLE
Adding another bridge component to the agent_default.json  file

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1855]
Hello @andre-merzky, 

this ticket is regarding the RCT class, as we talked last week I Will @chengwill97 as well as I faced problems adding another bridge component to the `agent_default.json`,  by enabling the radical verbose we could see that the bridge component created under the name we gave, but RP keeps doing `gather results.
wait for # unit(s)` . until we do ctrl+C
The test was done with 2 different `radical-stack` as below :
Will `radical-stack` :
`radical.analytics     : 0.47.0`
`radical.pilot           : 0.47.10`
`radical.utils            : 0.47.4`
`saga                       : 0.47.3`
`session ==> `[rp_watershed_24tasks_24cores_9005.zip](https://github.com/radical-cybertools/radical.pilot/files/3143302/rp_watershed_24tasks_24cores_9005.zip)

Aymen `radical-stack` :
  `python               : 2.7.16`
  `virtualenv           : conda_env3`
  `radical.pilot        : 0.60.1`
  `radical.saga        : 0.60.0`
  `radical.utils         : 0.60.1`

`session ==> `[session.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/3143314/session.tar.gz)

**Comment by andre-merzky** [comment]
Hi @AymenFJA, 

the easiest way to close in on an error condition in RP is to do a `grep ERROR *.log`.  In the watershed sandbox, you will find that the agent does not find the ORTE installation, in the other case, you will find a json parse error in `agent_default.json` (line 103).

Having said that, the application should have finished when the parse error occurred.  There seems to have been a race condition: the pmgr (which caught that error) died while the umgr still came up, so that demise was not noticed.  I'll open an issue for that.

As for the watershed example, I am not sure why the agent does not complete when the LRMS hook fails.  The logs are inconclusive.  Is that reproducible,  ie. does that happen every time?

My advise would be to test the bridge startup on localhost, to avoid distraction of resource specific errors, and after a failed run, look through the log files to check for `ERROR` entries (there are also `.out` and `*.err` files in the session dirs to check).

**Comment by andre-merzky** [comment]
Any progress on localhost? :-)

**Comment by AymenFJA** [comment]
So, for me, I did submit my pilot locally (localhost) using anaconda python env. I submitted 2 units and its been doing `gather results` `wait for 2 unit(s)` doing that for 3 hours. I tried to do `grep ERROR *.*` or `*.log` , the only error I am getting is `keyboard interrupt ctrl+C `, my session above was actually done on localhost.

any ideas?

**Comment by andre-merzky** [comment]
Can you attach the client and remote side sandboxes, please?  Thanks

**Comment by AymenFJA** [comment]
I fixed it on `localhost` just now it appears that my `config.json`  was not set correctly.
I've added both the client and remote side sandbox. I will try it on one of the XSEDE resources and update this ticket.

[client_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3153803/client_session.zip)
[remote_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3153805/remote_session.zip)

**Comment by AymenFJA** [comment]
update: I tried to submit 1 pilot with 2 CUs on xsede comet, both are failing with the error below:

`[aymen@comet-ln3 pilot.0000]$ grep ERROR *.*
agent_0.log:2019-05-07 10:35:55,856: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms config hook failed: Couldn't find orte-dvm
bootstrap_0.out:ModuleCmd_Use.c(231):ERROR:64: Directory '/home/amerzky/ompi/modules' not found
bootstrap_0.out:ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'openmpi/2017_02_17_6da4dbb'
bootstrap_0.out:# ERROR
bootstrap_0.out:# ERROR`

I have attached both remote and client sessions.
[comet_cleint.zip](https://github.com/radical-cybertools/radical.pilot/files/3154025/comet_cleint.zip)
[comet_remote.zip](https://github.com/radical-cybertools/radical.pilot/files/3154026/comet_remote.zip)

**Comment by chengwill97** [comment]
> update: I tried to submit 1 pilot with 2 CUs on xsede comet, both are failing with the error below:
> 
> `[aymen@comet-ln3 pilot.0000]$ grep ERROR *.* agent_0.log:2019-05-07 10:35:55,856: agent_0 : MainProcess : MainThread : ERROR : lrms config hook failed: Couldn't find orte-dvm bootstrap_0.out:ModuleCmd_Use.c(231):ERROR:64: Directory '/home/amerzky/ompi/modules' not found bootstrap_0.out:ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'openmpi/2017_02_17_6da4dbb' bootstrap_0.out:# ERROR bootstrap_0.out:# ERROR`
> 
> I have attached both remote and client sessions.
> [comet_cleint.zip](https://github.com/radical-cybertools/radical.pilot/files/3154025/comet_cleint.zip)
> [comet_remote.zip](https://github.com/radical-cybertools/radical.pilot/files/3154026/comet_remote.zip)

I got the same error with the same version too.

**Comment by andre-merzky** [comment]
Uhm, all those zip files seem empty?

**Comment by AymenFJA** [comment]
Sorry, that was my mistake, I didn't check the files before upload. I uploaded both remote and client sessions again :)  .

**Comment by andre-merzky** [comment]
From the pilot logs:
```
$ grep ERROR *
agent_0.log:2019-05-07 10:35:55,856: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms config hook failed: Couldn't find orte-dvm
```
the orte configuration seems not to work - can you please try `xsede.comet_ssh` as resource label?

**Comment by AymenFJA** [comment]
I did try the `xsede.comet_ssh` , and although I was executing something simple `/bin/date`, the pilot keeps failing with the error : 


`2019-05-13 12:52:57,537: agent_0.scheduling.0.child: agent_0.scheduling.0            : MainThread     : ERROR   : worker <bound method Continuous._schedule_units of <Continuous(agent_0.scheduling.0, started)>> failed
Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.018029.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1267, in work_cb
    self._workers[state](things)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.018029.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 472, in _schedule_units
    if self._try_allocation(unit):
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.018029.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 191, in _try_allocation
    unit['slots'] = self._allocate_slot(unit['description'])
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.018029.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 237, in _allocate_slot
    slots = self._alloc_nompi(cud)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.018029.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 436, in _alloc_nompi
    raise ValueError(txt)
ValueError: Non-mpi unit does not fit onto single node.` .


My CU description :

            `cud = rp.ComputeUnitDescription()`
            `cud.executable       = '/bin/sleep'`
            `cud.arguments        = ['1']`
            `cud.gpu_processes    = 0`
            `cud.cpu_processes    = 1`
            `cud.cpu_threads      = 1`
            `cud.cpu_process_type = rp.POSIX`
            `cud.cpu_thread_type  = rp.POSIX`

**Comment by andre-merzky** [comment]
Sorry for the late response.

> ValueError: Non-mpi unit does not fit onto single node.

Seems like the tasks are too large for the target nodes?

**Comment by AymenFJA** [comment]
True, the exception is reasonable. I will close it now.
