### ISSUE TITLE
Issue Running Example on localhost

### ISSUE THREAD

**Issue by chengwill97** [radical-cybertools/radical.pilot#1858]
```
$ python -V
  Python 2.7.15
$ radical-stack
  python               : 2.7.15
  pythonpath           : 
  virtualenv           : bridge

  radical.pilot        : 0.60.1
  radical.saga         : 0.60.0
  radical.utils        : 0.60.1
```

If you can reproduce the problem, it would greatly simplify debugging if you can provide a minimal code example which we can use to repoduce the problem too.

On **most** tickets we will ask you to provide additional information, most often log files. You can obtain detailed logs by rerunning your code after setting the following environment variables:

Having trouble running examples on localhost.
I'm attaching the log file underneath.
[r.log](https://github.com/radical-cybertools/radical.pilot/files/3154385/r.log)

**Comment by andre-merzky** [comment]
outdated.
