### ISSUE TITLE
Question on Agent Configuration for multi-node placements

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1859]
I am creating a Github issue to continue the discussion in the RCT class and trace related developments here.

Items to investigate:
- launch prototype (function) executors
- change agent configuration to launch executors on all nodes

### Change of Agent Configuration
Along with the Aymen and Will's efforts for Bridges, communication channel, the configuration needs to be addressed first. 
```'target'     : 'node'``` probably does the placement on multi-nodes? where `'local'` does not?

**Comment by andre-merzky** [comment]
The FuncExecutor now uses a different mechanism to place executors - but for completeness:

> 'target' : 'node' probably does the placement on multi-nodes? where 'local' does not?

That is correct:  `local` places the sub-agent and its components on the same node where the pilot job landed (MOM-node or first compute node), `node` places it onto a *free* compute node.  When multiple `node` statements are used, then multiple compute nodes are used (one per statement).  The exact target node is determined by the agent at runtime.
