### ISSUE TITLE
RCT class example failing localhost

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1864]
I was trying to test the new rp branch rct/com and I am facing the following :
```
File "/home/aymenlinux/miniconda3/envs/conda_env2/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 133, in _default_state_cb raise RuntimeError('pilot %s failed - fatal!' % self.uid)
RuntimeError: pilot pilot.0000 failed - fatal!

radical-stack
 python               : 2.7.16
 virtualenv           : conda_env2

 radical.pilot        : 0.61.0-v0.61.0-39-gda8faa4@rct-comm
 radical.saga         : 0.60.0
 radical.utils        : 0.60.1
```
log files are attached.

[rp.session.Lenovo-P50.aymenlinux.018044.0003.zip](https://github.com/radical-cybertools/radical.pilot/files/3229107/rp.session.Lenovo-P50.aymenlinux.018044.0003.zip)
[rp.session.Lenovo-P50.aymenlinux.018044.0003_sand_box.zip](https://github.com/radical-cybertools/radical.pilot/files/3229108/rp.session.Lenovo-P50.aymenlinux.018044.0003_sand_box.zip)

**Comment by andre-merzky** [comment]
It looks like your system python is version 3 - from bootstrap_0.out:
```
PYTHON: /home/aymenlinux/miniconda3/bin/python
```
RCT will need python version 2.  You can add something like this is the `resource_local.json` config file (in the appropriate config section):
```
"python_interpreter"          : "/usr/bin/python2",
```
or whatever your path to Python2 is

**Comment by andre-merzky** [comment]
PS.: in issue comments, you can use tripe backticks to mark multiple  lines as block:

```
 ` ` `
this is code
this too
 ` ` `
```
(remove spaces between backticks above)

**Comment by AymenFJA** [comment]
This is my `Python -V` output :

` 2.7.16 :: Anaconda, Inc.`
My python path is the same as the Anaconda path
But I will try to add the `python_interpreter` to the  `resource_local.json`
thanks for PS :)

**Comment by andre-merzky** [comment]
Yes, your python in the shell where you start seems all right, otherwise RP would not have started.  But when you say `My python path is the same as the Anaconda path`, you mean that `which python` results in `/home/aymenlinux/miniconda3/bin/python`?  Hmm, then I am misinterpreting the problem, and your Python should be ok.  I was thrown off by `miniconda3`, assuming this implied Python3.  Let me check again.

**Comment by andre-merzky** [comment]
Yeah, your Python is all right - apologies, I should have looked further in your sandbox.

However, it seems to stumble over pip:
```
PIP installer     : /home/aymenlinux/.local/bin/pip
Traceback (most recent call last):
  File "/home/aymenlinux/.local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
``` 
I have no idea what that means unfortunately :-(

**Comment by andre-merzky** [comment]
@AymenFJA : see [here](https://github.com/pypa/pip/issues/5253) for a pip issue on the same topic.  The proposed resolution seems to be to uninstall and/or reinstall pip on system level.  No idea how that would effect pip in your `~/.local/`, but, oh well...

**Comment by AymenFJA** [comment]
Ok, working on it. Thanks @andre-merzky

**Comment by AymenFJA** [comment]
This is no more an issue. Closing.
