### ISSUE TITLE
RCT devel meeting list of tasks, June 12 2019

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1869]
Based on our discussion yesterday, we ended up in this list of tasks that we want to accomplish : 

- [x] Branch `feature/func_exe`: AM to open PR.
- [x] Branch `feature/summit_am` will be merged to `summit` (Andre will create a pull request).
- [x] Branch `feature/srun` AM to open PR.
- [x] Branch `rct/bridge` will be removed.
- [x] Branch `test/orte` will be removed (Supporting orte is stopped).
- [x] Branch `fix/hombre` AM will open PR
- [x] Branch `fix/issue_1729` will be archived.
- [x] Branch `fix/fifo_reschudle` will be archived.
- [x] Branch `feature/streaming` will be archived.
- [x] Branch `feature/jsrun` will be archived.
- [x] Branch `feature/gpu_devices` will be merged (Giannis will open a pull request).
- [x] Branch `feature/ev` will be archived.
- [x] Branch `feature/bulk_cb` : AM to open PR
- [x] Branch `feature/bridge_spawner` will be archived.
- [x] Branch `feature/partitions` will be deleted. 
- [x] Branch `feature/app_comm` need to be cleaned (By Andre).
- [x]  Branch `version/2` need to be archived.
- [x] Branch `feature/agent_isolation` will be deleted.
- [x] Branch `integration/molssi`: AM to open PR
- [x] Branch `fix/issue_1830` will be deleted.
- [x] Branch `fix/cuda` AM to open PR to feature/summit
- [x] Branch `feature/cleanup_lm` AM to check.
- [x] Branch `experiments/rp_paper` will be archived.
- [x] Branch `experiments/jdakka` will be deleted.
- [x] Branch `stale/partition_scheduler` will be archived.
- [x] Branch `usecases/vivek` will be deleted.
- [x] Branch `stale/pilotdata` will be archived.
- [x] Branch `experiments/swift` will be archived.
- [x] Titan related branches will be deleted

**Comment by AymenFJA** [comment]
Should we close this? @andre-merzky

**Comment by andre-merzky** [comment]
> Should we close this? @andre-merzky

As soon as you review the pull request and confirm it's working :-)

**Comment by andre-merzky** [comment]
Oh, my last reply did not match this ticket, apologies.  Yes, this can be closed - thanks @AymenFJA

**Comment by AymenFJA** [comment]
Thank you :).
