### ISSUE TITLE
Do not hardcode project number in resource_ornl.json

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1887]

**Comment by andre-merzky** [comment]
related: #292

Not that the solution proposed there also breaks in some cases: it points the sandbox to the *first* group listed in `id`, but that is usually not the project  ID.  In fact, that is most frequently the private personal group.  At some point we used something like `id -Gn | sed -e 's/.* //g'` which results in the *last* group listed, which **usually** is a valid project group - but it ain't necessarily so, and its also not the always the allocation the pilot was submitted under.

A proper solution would be to expand the resource config by keys from the pilot description.  That had been coded in the past already (see https://github.com/radical-cybertools/radical.pilot/blob/fix/expand_rcfg/src/radical/pilot/pmgr/launching/default.py#L543), but that code is likely out of sync with devel at that point and needs some serious review.  It is likely incomplete.
