### ISSUE TITLE
continuous scheduler barfs on GPU-only tasks

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1891]
... or chunks.  It falls over `assert(not len(cores) % threads_per_proc)`, which is indeed invalid if no cores are requested in the first place...

**Comment by andre-merzky** [comment]
This is *mostly* fixed by the new scheduler, but correct expression of GPU-only tasks  need a changed CU description.

**Comment by iparask** [comment]
@mturilli is this working for you? In my opinion a GPU task, requires at one CPU to run. Please let me know your thoughts.

**Comment by mturilli** [comment]
I am working on this right now and it is a bit messy. For example, if we run 6 concurrent GPU tasks, do we need to reserve 1 CPU for each GPU task or just 1 CPU for all of them?

**Comment by andre-merzky** [comment]
We usually can't co-place processes on the same core (and should not try to do so anyway as we do not know if the task needs the full core despite GPU support), so we have to allocate at least one core per task rank, independent if the rank uses a GPU or not.  So: 1 core per GPU task (if the GPU task has only one rank, i.e. `cpu_processes==1`).

**Comment by andre-merzky** [comment]
I should add that this is indeed working now - but the task description naming is off: `gpu_processes` is interpreted as `gpus_per_process` and should thus be renamed.

**Comment by andre-merzky** [comment]
key rename should be released.  Add deperation warning.

**Comment by iparask** [comment]
This is a more general problem of how we describe a compute unit.

**Comment by andre-merzky** [comment]
cannot happen anymore
