### ISSUE TITLE
RP agent error messages should end up in log files

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1924]
right now, complains about insufficient node numbers end up in `agent_0.err`.

**Comment by iparask** [comment]
I am not sure what this issue means.

**Comment by andre-merzky** [comment]
Some error modes are not logged as `ERROR` level log messages, but end up in the agent `stderr` file.  This requires the user to look into different files to find a possible cause for a problem.

**Comment by mturilli** [comment]
Do we have a list of the error messages we should catch?

**Comment by andre-merzky** [comment]
No, and I don't think a complete list can sensibly be created (we do not know the list of potential system errors we happen to catch, for example).  The STDERR stream should generally be caught and converted into log messages I think.

**Comment by mturilli** [comment]
@andre-merzky should we converge towards an agreed solution?

**Comment by andre-merzky** [comment]
I am actually not yet sure how: some of the error modes in question happen before the log system is up.  I understand users complaining about that, but I am not sure the problem is pressing enough to warrant major code changes...

**Comment by andre-merzky** [comment]
Closing as not needed anymore.
