### ISSUE TITLE
pilot.0000 failed - fatal!

### ISSUE THREAD

**Issue by karahbit** [radical-cybertools/radical.pilot#1927]
Hello guys,

I was trying to run the "getting started" example and I am getting this error:
```
Traceback (most recent call last):
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/utils/threads.py", line 380, in _run
    if not self.work_cb():
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1124, in work_cb
    ret = self._cb(topic=topic, msg=m)
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 294, in _state_sub_cb
    if not self._update_pilot(thing, publish=False):
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 335, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 184, in _update
    else      : cb(self, self.state)
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 132, in _default_state_cb
    raise RuntimeError('pilot %s failed - fatal!' % self.uid)
RuntimeError: pilot pilot.0000 failed - fatal!
```
My Python version is 
```
Python 2.7.16 :: Anaconda, Inc.
```
```
python               : 2.7.16
  pythonpath           : 
  virtualenv           : radical27

  radical.pilot        : 0.70.3
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```

I have attached two sessions as zip files.
[local_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3464249/local_session.zip)
[radical_sandbox_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3464250/radical_sandbox_session.zip)

**Comment by andre-merzky** [comment]
Hi @karahbit , 

your pilot bootstrapper complains:
```
virtenv /home/karahbit/radical.pilot.sandbox/ve.local.localhost.0.70.3 exists
0.2238,ve_activate_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
/home/karahbit/radical.pilot.sandbox/rp.session.js-156-87.jetstream-cloud.org.karahbit.018111.0001/bootstrap_0.sh: line 815: /home/karahbit/radical.pilot.sandbox/ve.local.localhost.0.70.3/bin/activate: No such file or directory
```
it does not like the virtualenv at `/home/karahbit/radical.pilot.sandbox/ve.local.localhost.0.70.3/`.  Could it be that a previous run has been manually interrupted?  If that happened while the pilot was still creating that virtualenv, it could leave that in an invalid state.

Can you please `rm -rf /home/karahbit/radical.pilot.sandbox/ve.local.localhost.0.70.3/` and run again?  Please allow for some time  (5 min or so) for the first run, it will need some time to setup the VE again.  If that fails, please attach the sandbox again for that run - thank you!

**Comment by shantenujha** [comment]
@karahbit  -- did this work?

**Comment by karahbit** [comment]
Dear all,

Thank you for your prompt response Andre. I have been waiting for the weekend to try it out since I’ve been packed with stuff to do at work. I’ll let you know how it goes this Saturday probably.

Best,
 George.

**Comment by karahbit** [comment]
I apologize for not updating the ticket before,

I updated to the latest version of RP, and it worked fine:

```  
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/karahbit/ve

  radical.pilot        : 0.72.0
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```

Thank you!
