### ISSUE TITLE
Version check to be done in string not byte

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1931]
This [line](https://github.com/radical-cybertools/radical.pilot/blob/devel/setup.py#L86) in setup.py returns a bytestream and not a string. It will introduce a `b` in the version number that may cause an error during installation

**Comment by mturilli** [comment]
Thanks. Fixed in RP porting to p3.

**Comment by mturilli** [comment]
BTW, seeing that the ticket did not indicated the solution but only the problem:
```
        version_detail = out.strip()
        version_detail = version_detail.decode()
```
