### ISSUE TITLE
Increasing runtime from 15 to 30 in 00_getting_started.py for Intel Compiler on KNL

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1936]
From my experience on Stampede2, the initial bootstrapping including venv setup takes 22+ minutes.

``
session lifetime: 1363.0s                                                     ok
``
My guess is that Intel compiler takes some time for python packages e.g. zmq to install and simple resolution would be increasing the default runtime in the example to 30 minutes which will be enough to complete.  This is referring to https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/00_getting_started.py#L59

**Comment by andre-merzky** [comment]
I see.  Can you open a PR for this?  Thanks!

**Comment by lee212** [comment]
#1938 created

**Comment by lee212** [comment]
PR #1938 merged
