### ISSUE TITLE
openmp / multicore and cores field of the cud

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#194]
In cases of OpenMP (or other multicore tasks) we currently need to specify that explicitly to both the `cud.cores` and the `OMP_NUM_THREADS` environment variable.

```
cores = 8 # Number of cores to use for once instance.
cudesc = radical.pilot.ComputeUnitDescription()
cudesc.cores       = cores
cudesc.environment = {'OMP_NUM_THREADS': cores}
```

Ideally that should not be necessary, and we would only have to set:

```
cores = 8 # Number of cores to use for once instance.
cudesc = radical.pilot.ComputeUnitDescription()
cudesc.cores       = cores
```

and 

```
export OMP_NUM_THREADS=8
```

would happen automagically.

**Comment by andre-merzky** [comment]
This is addressed in the feature/gpu branch.
