### ISSUE TITLE
Incorrect # cores calculation?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1943]
Asking 272+ CPUs (68 cores * 4 hardware threads) in EnTK launches 2 KNL nodes on Stampede2, not 68+ CPUs. This also raises ValueError from base.py in lrms like:
```
(base) login2(1192)$ more agent_0.err
Traceback (most recent call last):
  File "/work/06079/tg853783/stampede2/radical.pilot.sandbox/re.session.js-17-248.jetstream-cloud.org.hrlee.018124.0014/pilot.0000/rp_install/bin/radical-pil
ot-agent", line 71, in <module>
    bootstrap_3(sys.argv[1])
  File "/work/06079/tg853783/stampede2/radical.pilot.sandbox/re.session.js-17-248.jetstream-cloud.org.hrlee.018124.0014/pilot.0000/rp_install/bin/radical-pil
ot-agent", line 42, in bootstrap_3
    if agent_name == 'agent_0': agent = rpa.Agent_0(agent_name)
  File "/work/06079/tg853783/stampede2/radical.pilot.sandbox/re.session.js-17-248.jetstream-cloud.org.hrlee.018124.0014/pilot.0000/rp_install/lib/python2.7/s
ite-packages/radical/pilot/agent/agent_0.py", line 146, in __init__
    session=self._session)
  File "/work/06079/tg853783/stampede2/radical.pilot.sandbox/re.session.js-17-248.jetstream-cloud.org.hrlee.018124.0014/pilot.0000/rp_install/lib/python2.7/s
ite-packages/radical/pilot/agent/rm/base.py", line 242, in create
    return impl(cfg, session)
  File "/work/06079/tg853783/stampede2/radical.pilot.sandbox/re.session.js-17-248.jetstream-cloud.org.hrlee.018124.0014/pilot.0000/rp_install/lib/python2.7/s
ite-packages/radical/pilot/agent/rm/slurm.py", line 22, in __init__
    LRMS.__init__(self, cfg, session)
  File "/work/06079/tg853783/stampede2/radical.pilot.sandbox/re.session.js-17-248.jetstream-cloud.org.hrlee.018124.0014/pilot.0000/rp_install/lib/python2.7/s
ite-packages/radical/pilot/agent/rm/base.py", line 171, in __init__
    % (str(cores_avail), str(self.requested_cores)))
ValueError: Not enough cores available (136 < 340).
```

Tried to enable `RADICAL_DEBUG` as it says the ValueError is triggered when it's not enabled but the error is persistent.

**Comment by andre-merzky** [comment]
Thanks @lee212.  Can you please attach the pilot description (or the RE resource description), and the output of `radical-stack`?

**Comment by lee212** [comment]
my stack:
```
  python               : 2.7.5
  pythonpath           :
  virtualenv           : /home/hrlee/venv/entk

  radical.entk         : 0.7.16
  radical.pilot        : 0.70.3
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0

```
and resource description in EnTK
```
    res_dict = {

        'resource': 'xsede.stampede2_ssh',
        'queue': 'normal',
        'schema': 'local',
        'walltime': 10,
        'cpus': 273,
        'gpus': 0,
        'project': "TG-MCB090174"
    }
```

**Comment by andre-merzky** [comment]
Yeah, that looks wrong, I'll check!

**Comment by andre-merzky** [comment]
The slurm adaptor's system inspection for node core counts returns an incorrect value, this needs fixing on the SAGA layer.  How urgent is this?

**Comment by lee212** [comment]
This can wait. I might be able to use batch job commands instead.

**Comment by krb09** [comment]
Hello,

I am facing the same error. 

The script that I run works for 68 cores (Number of cores for 1 node on Stampede2) but does not work for cores>68. 

The error I receive: 

radical.entk.appmanager.0000.log:1580314375.040 : radical.entk.appmanager.0000 : 3377  : 140323562583808 : ERROR    : Error in AppManager
radical.entk.resource_manager.0000.log:1580314374.999 : radical.entk.resource_manager.0000 : 3377  : 140322067699456 : ERROR    : Pilot has failed

I also see the same error mentioned above
[session_cores.zip](https://github.com/radical-cybertools/radical.pilot/files/4135842/session_cores.zip)

"ValueError: Not enough cores available (68 < 150)"

My Radical-Stack is: 

python                   : 3.7.6
pythonpath           :
virtualenv              : /home/krb09/ve-entk-3.7

radical.analytics    : 0.90.7
radical.entk         : 1.0.0
radical.pilot        : 1.0.0
radical.saga         : 1.0.1
radical.utils        : 1.0.0

I have uploaded my session files. 

Thank you

**Comment by andre-merzky** [comment]
ref radical-cybertools/radical.saga/issues/738

**Comment by iparask** [comment]
I consider this ongoing.
