### ISSUE TITLE
need multinode testcase for agent schedulers

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1952]
We need to add a test case which covers tasks using 2.5 nodes on respective target resource.  Make sure to cover resources with blocked cores like summit.  Don't ask how I know that we need this...

**Comment by andre-merzky** [comment]
@iparask: please check (and close)

**Comment by mturilli** [comment]
@andre-merzky how do we want to proceed with this?

**Comment by andre-merzky** [comment]
This is implemented now.
