### ISSUE TITLE
Session create failed

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1953]
Hello, I was trying to submit a new set of weak and strong scaling experiments on Bridges. I am facing the following error :
```
Traceback (most recent call last):
  File "/home/aymen/miniconda3/envs/asift/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 133, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/aymen/miniconda3/envs/asift/lib/python2.7/site-packages/radical/pilot/session.py", line 256, in __init__
    % (dburl, e))
RuntimeError: Could not create new session (database URL (mongodb://radical:mLAb2017@ds145379.mlab.com:45379/radical) incorrect?): This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
```
although I am sure that my MongoDB is fully functional and working. I tried to add the `retryWrites=false` to my connection, but still, I am facing the same error.

`Radical-Stack`
```
 python               : 2.7.16
  pythonpath           :
  virtualenv           : asift

  radical.analytics    : 0.70.0
  radical.entk         : 0.70.0
  radical.pilot        : 0.70.3
  radical.saga         : 0.70.0
  radical.utils        : 0.70.1
```
Below is my session zip file :
[session.zip](https://github.com/radical-cybertools/radical.pilot/files/3553750/session.zip)

**Comment by mturilli** [comment]
Mlab is known to give issues since when it was acquired by MongoDB. You should use one of our deployment (one|two.radical-project) or run your own on a VM on jetstream. Let me know whether you need further support with this.

**Comment by AymenFJA** [comment]
update: I created new MongoDB and unfortunately I am facing the same problem. 

@mturilli  I followed your suggestion and i can approve that our MongoDB (one|two.radical-project) is working just fine for me.

Thanks for the help.

`This Ticket will be closed.`
