### ISSUE TITLE
Module for `comet_orte` is unavailable?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1955]
While I was testing available resources, I found the module location does not exist: `/home/amerzky/ompi/modules` but it is stated in the resource file: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L437

BTW, Sumpermic is okay with the ORTE module location.

**Comment by andre-merzky** [comment]
That label should indeed be removed, we don't support it anymore.

**Comment by andre-merzky** [comment]
That label has been removed.
