### ISSUE TITLE
simplify example config

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1989]
From #1987:

@ mturilli
> I think we should also depart from hard-coding project IDs into our example configs. Should we just pass it with a env and an exception if it is not defined?

@andre-merzky
> Ha, this surprises me! you suggest an env variable (I never though I'd see the day), and me saying nah, not really - whats wrong? Is the world coming to an end?? :-)
>
> In all sincerity though, I think env vars are great for settings which vary from run to run, and config files are great for settings which vary from user to user or resource to resource.
>
> Having said that, our examples/config.json is clearly not a satisfactory solution. Apart from the fact that I should not have committed the above, its obvious that it needs to be changed for every user on every tutorial.
> 
> I would envision a better solution to have something like a ~/.radical/pilot/examples.cfg with very much the same settings which we have in the current example config, so that those data are specific to users and tutorials, and only fall back to examples/examples.cfg if the above does not exist. We can then document that behavior in examples/examples.cfg and prepare it as a template for the user to place into ~/.radical as part of the tutorial setup. Would something like this makes sense IYO, or is it overkill / off target? I wouldn't mind having a go at it...

@mturilli
> I think about examples as something a new user wants to try out as sort of RP hello world. I would use the simplest, most self evident possible approach. To me, having to know about, and write or edit my own ~/.radical/pilot/examples.cf does not seem to fit that requirement. Maybe I am wrong in my approach to the whole examples thing though.

@andre-merzky
> We can check what other systems are doing. If I'm not mistaken, many do require changing code or config files before running any example. FWIW, so does EnTK :-)
> 
> A really self sufficient option would be to get rid of the config altogether, and have a small section at the beginning of each example, like
>
```
#!/usr/bin/env python

# configuration for target resource
RP_RESOURCE = 'local.localhost'
RP_SCHEMA   = 'fork'
RP_QUEUE    = None
...
```
> That is just a few lines, and easy to change and to reference in the documentation. We can still document our config system in one of the advanced examples (if we want).
>
> Not saying that this is the best way, but it is a rather simple and self-sufficient option.

**Comment by iparask** [comment]
Closing as resolved

**Comment by andre-merzky** [comment]
Hmm, this is not really resolved, is it?

**Comment by mturilli** [comment]
Agreed with @andre-merzky , we still need to decide what solution to adopt.

**Comment by mturilli** [comment]
I am happy to try to close this. The idea to have a cnfig file was, if memory serves well, related to using examples to 'test' RP before releasing it. We run all the tests and we did not want to have to change a couple of lines at the beginning of each file. I think this still makes sense even if we moved away from that 'testing' protocol. Thoughts?

**Comment by andre-merzky** [comment]
I don't think this ticket warrants much work - the cfg may not be perfect, but it also does not really make any troubles...  Agree on closing.
