### ISSUE TITLE
00_getting_started.py; Error processing the ERF, missing GPU index

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1990]
STDERR:
```
Error: Line 2:36:(RS GPU): syntax error, unexpected CLOSE_BRACKET, expecting NUM
BER or RANGE or WILDCARD
Error processing the ERF /gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox
/rp.session.login1.hrlee.018211.0000/pilot.0000/unit.000000//unit.000000.rs
```

unit.000000.rs:
```
cpu_index_using: physical
rank: 0: { host: 1; cpu: {0}; gpu: {}}
```

radical-stack:
```
  python               : 3.7.0
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : /autofs/nccs-svm1_home1/hrlee/venv3/entk

  radical.entk         : 0.90.0-v0.72.0-50-g657fbd3@python3-devel
  radical.pilot        : 0.90.1-v0.90.1-50-g7ab71cf@devel
  radical.saga         : 0.90.0-bv0.72.0-44-g67a0318@devel
  radical.utils        : 0.90.3-v0.90.3-94-gcaf4cba@devel
```

**Comment by andre-merzky** [comment]
This is surprising.  Did the jsrun spec change, do you happen to know?

Can you please attach the pilot sandbox and the unit description of the offending unit?

**Comment by lee212** [comment]
[rp.session.login4.hrlee.018214.0003.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/3848467/rp.session.login4.hrlee.018214.0003.tar.gz)

This is running `00_getting_started.py`, so the unit description is:

```
            cud = rp.ComputeUnitDescription()
            cud.executable    = '/bin/date'
            cud.cpu_processes = 1
```

**Comment by lee212** [comment]
Isn't this related? to: https://github.com/radical-cybertools/radical.pilot/blob/88e1761fc124b708d1542981fdaf99dba2f25b33/src/radical/pilot/agent/lm/jsrun.py#L31

**Comment by andre-merzky** [comment]
It is - but according to line 88, we should only trigger the creation of a gpu spec if `gpu_maps` was set by the scheduler.  That should not be the case for non-GPU tasks.

**Comment by lee212** [comment]
PR #2021 fixes this
