### ISSUE TITLE
job tests faulty: need to mock `os.environ`.

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2002]
I had to pass a recent PR despite a failing test.  The test was the ssh launch method which failed because the OS environment for `LD_LIBRARY_PATH` differed from what we encoded in the expected result.  If I change the expected result, then the tests fail when running for me locally.  Ultimately the LM is making a runtime decision based on the actual os env, and thus the result cannot be hard coded this way.  I assume we need to mock the os env for the tests, and this is what this ticket is about.

**Comment by andre-merzky** [comment]
This should be discussed on the next devel call.

**Comment by mtitov** [comment]
@andre-merzky  this issue was resolved indirectly (#2075), should we close it then?

**Comment by andre-merzky** [comment]
I actually don't see how that was resolved - the `LD_LIBRARY_PATH` env setting should still show up in the test results?

**Comment by mtitov** [comment]
That env variables were [set](https://github.com/radical-cybertools/radical.pilot/blob/devel/tests/test_lm/test_unit/test_ssh.py#L51) and then were tested [here as example](https://github.com/radical-cybertools/radical.pilot/blob/devel/tests/test_cases/unit.000003.json#L42)

**Comment by andre-merzky** [comment]
Great, thanks!
