### ISSUE TITLE
radical.pilot bootstrapping fails on Bridges

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2007]
The anaconda module is loaded for executing the agent, but the selected python distribution is`default`.

**Comment by andre-merzky** [comment]
I am sorry, I don't think I understand what you report.  With 'selected' you mean 'configured'?  Then why is the anaconda module loaded?  Or do you mean that the module is loaded because it's configured, but the module is broken?

**Comment by andre-merzky** [comment]
@iparask : ping

**Comment by iparask** [comment]
Let me run a quick test and I'll let you know today with either closing the ticket or opening a PR

**Comment by andre-merzky** [comment]
@iparask : ping :-)

**Comment by iparask** [comment]
This is merged. It can close
