### ISSUE TITLE
missing py3 porting (i.e. parenthesis) to `print` in examples?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2023]
While I ran readthedocs for entk, there were syntax errors produced by rp, for example, https://github.com/radical-cybertools/radical.pilot/blob/2917c34b50a904e03e1abf971696df37cc5a5f55/examples/data_staging/io_staging_pipeline.py#L22 is missing parenthesis for `print` function. Should we include those examples ready for py3?

**Comment by andre-merzky** [comment]
Yeah, that should probably be fixed - thanks.

**Comment by iparask** [comment]
This should be fixed in PR #2043

**Comment by andre-merzky** [comment]
Thanks @iparask !
