### ISSUE TITLE
python2/devel branch broken

### ISSUE THREAD

**Issue by karahbit** [radical-cybertools/radical.pilot#2028]
Hello,

When cloning the repo and manually installing the python2/devel branch through

```
pip install .
```

RP does not work, at least when running 00_getting_started.py. It just stays running forever, with the following stack:

```
  python               : 2.7.17
  pythonpath           : 
  virtualenv           : /home/karahbit/facts

  radical.pilot        : 0.73.1-v0.73.1-65-ge42948a3@python2-devel
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```

Now, when installing through

```
pip install radical.pilot
```

RP works, and the stack shows the following:

```
  python               : 2.7.17
  pythonpath           : 
  virtualenv           : /home/karahbit/facts

  radical.pilot        : 0.73.1
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```

**Comment by andre-merzky** [comment]
For the erroneous run, can you please attach the client and the pilot sandbox to this ticket?  Thanks!

**Comment by karahbit** [comment]
[radical_sandbox_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4028121/radical_sandbox_session.zip)
[local_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4028122/local_session.zip)

**Comment by andre-merzky** [comment]
I am sorry, George, but both zip files seem to be empty (only containing the session dir, but no log files etc. in them)?

**Comment by karahbit** [comment]
I apologize. I updated the files.

**Comment by andre-merzky** [comment]
Hmm, that stack is unfortunately inconsistent:
```
$ cat agent_0.scheduling.0.child.err
Process Process-17:7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/karahbit/radical.pilot.sandbox/rp.session.two.karahbit.018267.0006/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 591, in _schedule_units
    r_wait, a = self._schedule_waitpool()
  File "/home/karahbit/radical.pilot.sandbox/rp.session.two.karahbit.018267.0006/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 648, in _schedule_waitpool
    scheduled, unscheduled = ru.lazy_bisect(tasks,
AttributeError: 'module' object has no attribute 'lazy_bisect'
```

You will need an RU version where `lazy_bisect` is implemented.  Can you try the `backport/lazy_bisect` branch of radical.utils, please?

**Comment by karahbit** [comment]
I confirm that it works now with that fix on ```backport/lazy_bisect``` branch.

**Comment by andre-merzky** [comment]
Thanks, I'll update python2/devel then.
