### ISSUE TITLE
RP hang on submitting units.

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2040]
This is new behavior from ```RP py3```,  that we did not see in ```RP py2```. If I specify the number of cores more than the available physical cores using ``` cud.cpu_processes = 9 ``` while having a CPU with 8 cores in the VM (localhost) I don't see an exception, instead RADICAL Pilot hang on submitting units until I do `ctrl+c`.

The session zip file is attached.
[session.zip](https://github.com/radical-cybertools/radical.pilot/files/4123828/session.zip)

**Comment by andre-merzky** [comment]
Alas, it is a known problem - see #1127.  Closing this as a duplicate, but upping the  priority on the referenced ticket.

**Comment by AymenFJA** [comment]
Thank you @andre-merzky
