### ISSUE TITLE
RP units fail when submitting MPI applications/processes to Bridges

### ISSUE THREAD

**Issue by karahbit** [radical-cybertools/radical.pilot#2059]
The units folder in pilot.000 actually get created but they are empty inside. When trying to debug myself, I found the following error:

![image](https://user-images.githubusercontent.com/12532782/73802305-457bf800-478b-11ea-9208-7744a30c2731.png)

I do not know if I am doing something wrong/missing something or perhaps there is a bug in RP. Either way, I am trying to describe my units in the following way:
```
        n = 1   # number of units to run
        t_num = 1  # number of threads   (OpenMP)
        p_num = 2  # number of processes (MPI)
        report.info('create %d unit description(s)\n\t' % n)

        cuds = list()
        for i in range(0, n):

            # create a new CU description, and fill it.
            # Here we don't use dict initialization.
            cud = rp.ComputeUnitDescription()
            #---------- Executable_Bridges ----------
            cud.pre_exec     = ['conda activate']   # for mpi4py package
            cud.executable   = ['python3']
            cud.arguments    = ['/home/karahbit/mpi_hello.py']
            #cud.executable   = ['mpirun']
            #cud.arguments    = ['-n', p_num, 'python', '~/mpi_hello.py']
            cud.cpu_processes = p_num
            cud.cpu_process_type = rp.MPI
            cud.cpu_threads   = t_num
            cuds.append(cud)
            report.progress()
```

Where ```mpi_hello.py``` is the following:

```
"""
Parallel Hello World
"""

from mpi4py import MPI

comm = MPI.COMM_WORLD
size = MPI.COMM_WORLD.Get_size()
rank = MPI.COMM_WORLD.Get_rank()
host = MPI.Get_processor_name().split('.')[0]

print("Hello, World! I am process %d of %d on %s.\n" % (rank, size, host))

comm.Barrier()   # wait for everybody to synchronize here
```

My radical-stack is the following:
```
  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/karahbit/ve-entk3

  radical.analytics    : 0.90.7
  radical.entk         : 1.0.0
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.0
  radical.utils        : 1.0.0
```

And the session files:
[radical_sandbox_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4156941/radical_sandbox_session.zip)
[local_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4156942/local_session.zip)

**Comment by andre-merzky** [comment]
Hi @karahbit : Thanks for attaching the sandboxes!    The PR #2061 should fix this, can you please confirm if that is the case (by using the RP branch `fix/issue_2059`)?

**Comment by karahbit** [comment]
I tried installing RP from said branch, but I am getting a different error now:

<img width="798" alt="Screen Shot 2020-02-05 at 12 54 36 PM" src="https://user-images.githubusercontent.com/12532782/73868702-ee236980-4816-11ea-800d-5da5c4b68122.png">

**Comment by mturilli** [comment]
Probably this requires the devel branch of utils. Could you update utils in your stack and try again?

**Comment by karahbit** [comment]
After trying what @mturilli suggested, I was able to launch RP but now it is failing. I think SAGA is complaining somewhere on the client side in the "gather results" stage:

<img width="1915" alt="Screen Shot 2020-02-05 at 1 31 15 PM" src="https://user-images.githubusercontent.com/12532782/73871431-dbf7fa00-481b-11ea-80bb-e32decb492d2.png">

<img width="1846" alt="Screen Shot 2020-02-05 at 1 24 48 PM" src="https://user-images.githubusercontent.com/12532782/73871309-a226f380-481b-11ea-8316-d65d8e245e83.png">

**Comment by andre-merzky** [comment]
This looks like a pilot error - could you please attach the pilot sandbox (or try to grep for `ERROR` log entries there)?  Thanks!

**Comment by karahbit** [comment]
I tried GREP on the pilot but do not see anything that draws my attention. I will attach the sandbox:

[radical_sandbox_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4161545/radical_sandbox_session.zip)

**Comment by andre-merzky** [comment]
Oy, the pilot bootstrapper failed to install the RCT stack on the target resource - hmpf!  Can you please:

  - remove all virtualenv in the `radical.pilot.sandbox/` base (`ve.xsede.bridges*`)
  - try to run again
  - if still failing,please send your radical stack again, and I'll try to reproduce

Thanks!
