### ISSUE TITLE
Wrong setup requirements versioning

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2072]
RP's setup file has the wrong minimum version in dependencies. For example, the latest setup file requires `radical.utils>=0.90`, but RP imports `Description` from `radical.utils`, which does not exist until version `1.1`, I believe. As a result this error is produced:
`AttributeError: module 'radical.utils' has no attribute 'Description'`

**Comment by andre-merzky** [comment]
Oh, good catch - thanks, will fix immediately.
