### ISSUE TITLE
RP error in spawner when requesting 2 or more nodes for MPI applications

### ISSUE THREAD

**Issue by karahbit** [radical-cybertools/radical.pilot#2074]
When requesting 1 node, at least in Bridges, RP runs fine. However, when requesting more nodes than 1 I see the following error:

```
agent_executing.0000.log:1581634978.560 : agent_executing.0000 : 15593 : 139778410874624 : ERROR    : Error in spawner (local variable 'mpt_hosts_string' referenced before assignment)
agent_executing.0000.log:1581634978.562 : agent_executing.0000 : 15593 : 139778410874624 : ERROR    : error running CU
```

RP finishes, but the CU fails to execute properly. 

My radical-stack:

```
  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/karahbit/rct3_mpi_test

  radical.pilot        : 1.0.0-v1.0.0-102-gf58b012@devel
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0-v1.0.0-31-ga6ecd7a@devel
```

session files:
[radical_local_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4202262/radical_local_session.zip)
[radical_remote_session.zip](https://github.com/radical-cybertools/radical.pilot/files/4202263/radical_remote_session.zip)

**Comment by mturilli** [comment]
Following the error, `mpt_hosts_string` (https://github.com/radical-cybertools/radical.pilot/blob/6583ee053d6d43a1a6f965d2b48d44f4d216455a/src/radical/pilot/agent/launch_method/mpirun.py#L167) seems to be undefined `if len(host_list) > 42`?

**Comment by andre-merzky** [comment]
Oh, bridges switched to `mpirun-mpt`!  Good, then we finally have a machine triggering that code path :-)  (Cheyenne was the only other machine so far).

Thanks for reporting this.  I attempted a fix in branch `fix/issue_2074` - can you please give it a try?  Thanks @mturilli, that was spot on.

**Comment by karahbit** [comment]
I apologize for taking me this long to reply. Given that said branch fixed the bug, I will proceed to close the issue. Thanks!
