### ISSUE TITLE
Wrong package paths for unit tests in tests.test_lm.test_unit

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2075]
Example: `from   radical.pilot.agent.lm.mpirun import MPIRun`
Should be: `from   radical.pilot.agent.launch_method.mpirun import MPIRun`

**Comment by andre-merzky** [comment]
same holds for `rm` -> `resource_manager`

**Comment by mtitov** [comment]
Meanwhile, should these issues [#2002](https://github.com/radical-cybertools/radical.pilot/issues/2002) and [#1879](https://github.com/radical-cybertools/radical.pilot/issues/1879) also be connected?

Clear os.environ before testing with predefined variables, env variables (that are to be checked) are taken from `rp.agent.launch_method.base.LaunchMethod.EXPORT_ENV_VARIABLES` list

Similar issue was fixed in PR #2076

**Comment by andre-merzky** [comment]
> Meanwhile, should these issues [#2002](https://github.com/radical-cybertools/radical.pilot/issues/2002) and [#1879](https://github.com/radical-cybertools/radical.pilot/issues/1879) also be connected?

That depends on what you mean with 'connected' :-)   We could address them in the same PR, if that's what you are asking, if you think that's not much work.  Otherwise I'd rather merge this PR soon and open a new one for the env issues.

**Comment by mtitov** [comment]
I believe #1879 is solved then :) but I agree to close these related PR & issues, and have a separate for env issues.

**Comment by andre-merzky** [comment]
Ack.
