### ISSUE TITLE
Very large log files with DEBUG log level

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2085]
With the latest released stack, runs with 8K units, 4 nodes, 3h runtime creates 280+MB log files. These are written in the location from which the script is executed, rapidly exhausting the available quota  on machines with 'multi-factor authentication'. The major offender is `umgr.0000.log` with its dump of `state_pubsub:`. Given the parameters listed above, that file alone is 180MB. Should we reduce the size of the logs, maybe with multiple debug levels?

**Comment by andre-merzky** [comment]
This seems to be caused by the ZMQ queue logging in RU - radical-cybertools/radical.utils/pull/220 fixes this.
