### ISSUE TITLE
Install RCT stack into virtualenv for stable release

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2088]
This should reduce bootstrap time at cost of flexibility. This should be acceptable for stable releases.

**Comment by andre-merzky** [comment]
Prepare a conda pack for each release?
Needs conda-pack support for agent staging / bootstrapper first.

**Comment by mturilli** [comment]
Ping

**Comment by mtitov** [comment]
Experiments were conducted to use `conda-pack` with user's pre-set environment (create conda tar-ball, set resource config to use this packed environment on the remote machine) - https://gist.github.com/mtitov/78d43f35b9525ebaae977075fe433a1e

**Comment by andre-merzky** [comment]
Conda is now supported for all releases.  Conda-pack seems not required anymore (otherwise please reopen)
