### ISSUE TITLE
RP does not honor security context

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2113]
With project/covid-19 Stack, the following context is not honored by RP/SAGA:
```
ctx = rp.Context('ssh', {'user_id': userid})
session.add_context(ctx)
```
Workarounds exist but are cumbersome.

**Comment by andre-merzky** [comment]
You are right, we lost that feature about 2 years ago or so: the pmgr.launching component now is a separate component which creates it's own session instance, and that won't get the contexts from the original session.

That is well fixable (the contexts need to be attached to the session config to pick up again).  What is the priority on this ticket?

**Comment by mturilli** [comment]
The workaround is to edit the resource-*.json in RP and add `<user_id>@` in front of the resource name in the `ssh` entry. Not too painful so I would say low priority.

**Comment by andre-merzky** [comment]
You could add the user ID to the ssh config?   But I guess the use case is Frontera, where you have a different user name for the covid jobs.  Yeah, a separate ssh config entry would not work (for the same job service URL).

**Comment by andre-merzky** [comment]
Closing as outdated
