### ISSUE TITLE
RP needs to handle sub-projects on summit

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2121]
Some users are assigned to sub-projects (like `CHM155_001`) and need to be able to submit to it.  OTOH, the file system scratch dir is still located under the main project ID (`CHM155` in this case).  RP cannot separate the two.

Assuming the underscore separation is general (and I do not yet know a counter example, so lets assume it is), we should be able to derive the main project ID from it, and use it toward the file system interactions.

Alas, this is somewhat urgent.  @iparask : would you find the time today to look into this?  Otherwise I can do this first thing tomorrow morning.

**Comment by iparask** [comment]
I think I can spend a couple of hours, between meetings. I'll let you know the outcome during the devel meeting

**Comment by andre-merzky** [comment]
Thanks @iparask, appreciated.   As of some min ago, the user has a workaround in place though, so the priority on this one dropped.  So don't sweat too much over it.
