### ISSUE TITLE
RP testing [LM]

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2126]
Hi everyone,

having this ticket for discussions on updates in [RP testing for agent's LM](https://github.com/radical-cybertools/radical.pilot/wiki/RP-testing:-proposal-on-structure-reorganization)

everyone is welcome to make changes in proposal or bring up related topics to discuss

**Comment by iparask** [comment]
Thank yo @mtitov ! I'll look at it and let you know.

**Comment by iparask** [comment]
I agree with @mtitov proposal on organizing the test cases and I would like to second it.

**Comment by mtitov** [comment]
@iparask thank you! This update also should follow your proposed guideline, which brings really good points (some of that is missed at LM tests)

**Comment by andre-merzky** [comment]
This looks good to me.  I am a bit worried that we spend too much time organizing tests instead of writing them and getting them to work reliably - but not much :-)

**Comment by iparask** [comment]
My proposal about test coding guidelines are [here](https://github.com/radical-cybertools/radical.pilot/wiki/Tests-Coding-Guidelines). @andre-merzky we can enforce the new style with new tests, and not old. The same procedure with linting. Any opinions?

**Comment by andre-merzky** [comment]
I don't think the guidelines are enforceable the same way we enforce linting, but otherwise I agree.

**Comment by mtitov** [comment]
Corresponding reference was added to [Tests Coding Guidelines](https://github.com/radical-cybertools/radical.pilot/wiki/Tests-Coding-Guidelines)
