### ISSUE TITLE
Allocating System memory(RAM) 

### ISSUE THREAD

**Issue by Abdullah-Ghani** [radical-cybertools/radical.pilot#2132]
When I submit a job on Amarel, I can request through my batch script an option for system memory:

For example:

#!/bin/bash
#SBATCH --partition=kopp_1
#SBATCH --job-name=ssp_landwaterstorage_all
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=128000
#SBATCH --time=24:00:00
#SBATCH --output=out_all.txt
#SBATCH --error=error_all.txt
#SBATCH --export=ALL

The above example requests from the scheduler a single cpu, and ~128 GB of system memory per node.  Would it be possible to have this as an option in the resource description when running EnTK?
If not can it be added ?

**Comment by andre-merzky** [comment]
The SAGA layer can handle memory specification for job allocation requests - but the pilot layer is currently not able to express this, and thus the EnTK layer won't either.  

I can in principle be added, and is technically not too difficult either and is backward compatible,so it's really a benign feature request - but it takes some time and coding obviously.  Can you help me understand the priority of this feature (why do you need it, why now, what experiments depend on it)?  

We will discuss it on our next devel meeting on Tuesday.

**Comment by Abdullah-Ghani** [comment]
The reason I ask is that many of the current FACTS modules need only one cpu, but the localization process can eat up a lot of memory.

When submitting a job on Amarel, I can request through my batch script an option for system memory:

For example:

#!/bin/bash
#SBATCH --partition=kopp_1
#SBATCH --job-name=ssp_landwaterstorage_all
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=128000
#SBATCH --time=24:00:00
#SBATCH --output=out_all.txt
#SBATCH --error=error_all.txt
#SBATCH --export=ALL

For those workflows it would be helpful/appropriate to have an option for allocating system memory needs.

**Comment by Abdullah-Ghani** [comment]
To be a little more meticulous 

Amarel has a variety of nodes with cpus ranging from 12 to 56 and also there are nodes with memory ranging from 128Gb to 1.5Tb.

By default when you submit a job to slurm scheduler without specifying any parameters, slurm will assume that your job needs
1 cpu, 4 Gb of memory and runs for 2 minutes.

You can adjust these parameters by requesting as many cpus/mem you need.
for example, 

#!/bin/bash

#SBATCH --partition=main             # Partition (job queue)
#SBATCH --job-name=gau-ex            # Assign an short name to your job
#SBATCH --nodes=1                    # Number of nodes you require
#SBATCH --ntasks=1                   # Total # of tasks across all nodes
#SBATCH --cpus-per-task=16           # Cores per task (>1 if multithread tasks)
**#SBATCH --mem=2000**                   # Real memory (RAM) required (MB) or use G for Gygabytes, i.e. 10G
#SBATCH --time=00:20:00              # Total run time limit (HH:MM:SS)
#SBATCH --output=slurm.%N.%j.out     # STDOUT output file
#SBATCH --error=slurm.%N.%j.err      # STDERR output file (optional)

The above job will use 16 cpus and 2Gb of memory. 
If you want 128Gb of RAM, all you need is just to adjust --mem parameter.

To make sure that RP allocates the nodes with the appropriate memory usage requirements wouldn't it be necessary to have that parameter ?

**Comment by andre-merzky** [comment]
Thanks, that makes sense.

**Comment by andre-merzky** [comment]
@Abdullah-Ghani : this is now scheduled for implement this in May.  This year :-)

**Comment by Abdullah-Ghani** [comment]
Great 😄

**Comment by mtitov** [comment]
Hi @Abdullah-Ghani , can you please give a try with the following RP version: `pip install git+https://github.com/radical-cybertools/radical.pilot.git@feature/memory_allocation`. New attribute that pilot description will have is `memory`, and for now it is of `int` type
