### ISSUE TITLE
agent scheduler: support for noco-location

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2139]
Basically, instead of forcing two tasks to land on the same node, force them to land on *different* nodes, for example to reduce competition on limited resources such as network I/O.

**Comment by andre-merzky** [comment]
relates to #2152

**Comment by mturilli** [comment]
relates to https://github.com/radical-cybertools/radical.entk/pull/531

**Comment by andre-merzky** [comment]
TODO: clean up `tag` vs. `tags`

**Comment by mtitov** [comment]
attribute `tag` got obsolete (PR #2372), [no]co-location could be done with `tags` attribute (e.g., `{'colocate': 'tag.0000', 'exclusive': True}`)
