### ISSUE TITLE
New launch method, ddlrun, on Summit?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2141]
In order to integrate Horovod, a distributed training framework, into a workflow (i.e. covid-19 wf-2), a new launch method, `ddlrun` might have to be introduced at an RP layer, instead of `jsrun` or `prun`.

There are several packages/frameworks you can find to train networks in a distributed fashion but I see `ddlrun` is the only tool that I can use on Summit machine, at least it is there via a module, `ibm-wml-ce` instead of considering all the dependencies to build workable environment and software stacks.

I find these are useful about ddlrun on Summit:
- https://www.olcf.ornl.gov/wp-content/uploads/2019/10/DDLonSummit.pdf
- https://docs.olcf.ornl.gov/software/analytics/ibm-wml-ce.html

Maybe `ddlrun` is not necessarily included at RP as it seems a wrapper of `mpirun` and `jsrun` based on my experience. For example, when I launch a task with `ddlrun python ...` it actually invokes `jsrun` like:
```
+ export PYTHONPATH='...' ; 
export LSB_MCPU_HOSTS='batch1 1 a26n15 42 b07n01 42 b07n03 42 e29n06 42 e29n07 42 e29n08 42 e29n09 42 e29n10 42 e29n11 42 e29n12 42' ; 
export LSB_JOBID='79172' ; 
export LD_LIBRARY_PATH='...' ; 
export PATH='...' ; 
export DDL_HOST_PORT='2200' ; 
export DDL_HOST_LIST='' ; 
export DDL_OPTIONS='-mode p:6x10x1x1 ' ; 
/opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun --erf_input /tmp/DDLRUN/DDLRUN.ADxtMQspVYFS/RANKFILE 
bash -c 'source /sw/summit/ibm-wml-ce/anaconda-base/etc/profile.d/conda.sh && 
conda activate /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2 > /dev/null 2>&1 &&
/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2/bin/python 
/gpfs/alpine/med110/scratch/atrifan2/covid19/PLPro/entk_cvae_md_hvd/CVAE_exps/cvae/train_cvae.py -f ../bytes-train.tfrecords'
```

and the erf file temporarily created on a batch node looks like:
```
#2020-05-06 12:50:48 by rank_gen
#host = a26n15,b07n01,b07n03,e29n06,e29n07,e29n08,e29n09,e29n10,e29n11,e29n12
#aisles = 1
#racks = 1
#nodes = 10
#accelerators = 6
#sockets = 2
#cores = 21
#threads = 4


cpu_index_using: logical
overlapping_rs: allow
skip_missing_cpu: warn
skip_missing_gpu: allow
skip_missing_mem: allow
oversubscribe_cpu: warn
oversubscribe_gpu: allow
oversubscribe_mem: allow
launch_distribution: packed

rank: 0: { hostname: a26n15; cpu: {0-27} ; gpu: * ; mem: * }
rank: 1: { hostname: a26n15; cpu: {28-55} ; gpu: * ; mem: * }
rank: 2: { hostname: a26n15; cpu: {56-83} ; gpu: * ; mem: * }
rank: 3: { hostname: a26n15; cpu: {84-111} ; gpu: * ; mem: * }
rank: 4: { hostname: a26n15; cpu: {112-139} ; gpu: * ; mem: * }
rank: 5: { hostname: a26n15; cpu: {140-167} ; gpu: * ; mem: * }

rank: 6: { hostname: b07n01; cpu: {0-27} ; gpu: * ; mem: * }
rank: 7: { hostname: b07n01; cpu: {28-55} ; gpu: * ; mem: * }
rank: 8: { hostname: b07n01; cpu: {56-83} ; gpu: * ; mem: * }
rank: 9: { hostname: b07n01; cpu: {84-111} ; gpu: * ; mem: * }
rank: 10: { hostname: b07n01; cpu: {112-139} ; gpu: * ; mem: * }
rank: 11: { hostname: b07n01; cpu: {140-167} ; gpu: * ; mem: * }

...

```

This particular way of running distributed learning tasks only applies to ORNL Summit and others might be different, for example LLNL Lassen works with `horovodrun`, .

**Comment by andre-merzky** [comment]
On the one hand: this is exactly why we try to keep launch methods isolated and extensible, so adding this is not a problem.  On the other hand: oh boy, yet another time sink :-P

But for real: we should be able to add this if its needed.  From looking at the info provided, the effort to mimic the ddlrun behavior via our jsrun LM seems greater than adding the ddlrun LM proper.  Let's hope that Lassen / Longhorn / XYZ are not too different, so that we don't have to invest that time for each machine...

Having said all that: no idea who and when this will get done.  What is the priority?   @shantenujha , @mturilli : any input?

**Comment by andre-merzky** [comment]
examples:
```
ddlrun --nodes 18 --racks 4 --aisles 2 python <args>
ddlrun -H server1,server2,server3,server4 python <args>
```

**Comment by shantenujha** [comment]
@andre-merzky  I hope yesterday's discussion post-COVID call was helpful. I think the priority is high -- definitely on Lassen, as it has greater memory than Longhorn. 

Depending on how involved this ends up being: we should prioritize Lassen over Longhorn, as Lassen has greater memory than Longhorn, and thus we could create a bifurcation where smaller proteases run on Longhorn (using vanilla CVAE), and larger proteases on Lassen (using Horovod-CVAE).  This would allow ANL team to make better use of memory available on Lassen.

**Comment by andre-merzky** [comment]
Thanks @shantenujha .  @lee212 : Lassen being an LSF machine, I assume that ddlrun setup is similar on both machines.  Can you please confirm?  Thanks,

**Comment by andre-merzky** [comment]
@lee212 : what is the priotity on this ticket?  Thanks!

**Comment by andre-merzky** [comment]
close for inactivity...
