### ISSUE TITLE
Unit tests for agent executing methods

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2143]

**Comment by mtitov** [comment]
actually there is no tests for `agent_exec` at all (not just `funcs`), should we rename this ticket (to generalize) and go through all exec modules (same way as it was done for `scheduler`)?

**Comment by mtitov** [comment]
Originally proposed for `agent.executing.funcs.FUNCS`, but will be extended for all methods.

p.s. development is ongoing ([feature/test_agent_executing](https://github.com/radical-cybertools/radical.pilot/compare/feature/test_agent_executing))

**Comment by andre-merzky** [comment]
done
