### ISSUE TITLE
Very short units create negative durations

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2148]
With very short units, like those run by RP examples, the timestamps for their exec* start/stop times is recorded as the same:
```
[57.16381764411926, 'cu_start', 'unit_script', 'MainThread', 'unit.000000', 'AGENT_EXECUTING', '', 'unit']
[57.16381764411926, 'cu_cd_done', 'unit_script', 'MainThread', 'unit.000000', 'AGENT_EXECUTING', '', 'unit']
[57.16381764411926, 'cu_exec_start', 'unit_script', 'MainThread', 'unit.000000', 'AGENT_EXECUTING', '', 'unit']
[57.16381764411926, 'cu_exec_stop', 'unit_script', 'MainThread', 'unit.000000', 'AGENT_EXECUTING', '', 'unit']
[57.16381764411926, 'cu_stop', 'unit_script', 'MainThread', 'unit.000000', 'AGENT_EXECUTING', '', 'unit']
```
As discussed, this is a problem with the shell-level profiling and the need for a usable and fast method to record sub-second timestamps. The idea is to use non-posix `date` after checking that all the important resources we currently support support it. For resources that do not support it, we should revert to using second-level timestamps. 

Note that currently this is corner case as we do not have real-world sub-second units in the use cases we support. This is slowly changing though so we should address this problem.

**Comment by AymenFJA** [comment]
Facing the same problem here, my `Radical stack` is:  

```
  python               : 3.6.10
  pythonpath           : 
  virtualenv           : conda-parsl

  radical.analytics    : 0.90.7
  radical.pilot        : 1.4.1
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0
```

**Comment by andre-merzky** [comment]
We have a new radical module uploaded to pypi: [radical.gtod](https://github.com/radical-cybertools/radical.gtod).  That provides a utility, `radical-gtod`, which returns a epoch timestamp in subsecond resolution.  The agent should use that to create task script time stamps.

@mturilli , @mtitov : can you have a look at that module to see if that deploys ok for you and functions as expected?  I'll update RP once I get your ok.  Thanks!

**Comment by mtitov** [comment]
@andre-merzky, can you please give more context here? I'm confused with why it is a separate package. `radical.utils` has cli command `radical-utils-gtod` and C-file `gtod.c`, should that be extended with corresponding python-module under RU?

p.s. at `radical.gtod` only method `gtod` can be called now, seems like cli command `radical-gtod` is missed and thus test should be updated accordingly

**Comment by andre-merzky** [comment]
We discussed that on one of our devel calls.  The proposal to move the binary blob into it's own package is to keep compilation dependent deployment out of RU - that has given a host of problems in the past.  Instead we would specify RG as *optional* dependency, so that installation would still succeed even if RG deployment fails.  We would in that case use the existing mechanism as a (slower) fallback.

> p.s. at radical.gtod only method gtod can be called now, seems like cli command radical-gtod is missed and thus test should be updated accordingly

That binary should be created duing `pip install` - see [here](https://github.com/radical-cybertools/radical.gtod/blob/devel/setup.py#L172).  If that does not work, cn you let me know how you installed?  Thanks!

**Comment by mtitov** [comment]
@andre-merzky thank you! (yeah, I missed the part of having it separately, sorry). With the `pip install` worked fine.

**Comment by andre-merzky** [comment]
This is fixed
