### ISSUE TITLE
ZMQ hangs on Lassen

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2150]
Gotta love Python...  From [PEP.475](https://www.python.org/dev/peps/pep-0475/): 
> *Backward compatibility*
> Applications relying on the fact that system calls are interrupted with InterruptedError will hang. The authors of this PEP don't think that such applications exist, since they would be exposed to other issues such as race conditions (there is an opportunity for deadlock if the signal comes before the system call). Besides, such code would be non-portable.

Well, this is exactly what's happening on Lassen: the ZMQ send gets continuously interrupted.  We originally intercepted the `EINTR` and retried 3 times (see [here](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/zmq/utils.py#L11)), but Python now makes it impossible to obtain `EINTR`, since obviously our code didn't exist, or was broken - unlike now.

ARGH

**Comment by andre-merzky** [comment]
The ZMQ hang is caused by the system ZMQ installation:
```sh
$ ldd /p/gpfs1/merzky1/radical.pilot.sandbox/ve.llnl.lassen.1.4.0/lib/python3.7/site-packages/zmq/backend/cython/socket.cpython-37m-powerpc64le-linux-gnu.so | grep zmq
        libzmq.so.5 => /lib64/libzmq.so.5 (0x0000200000110000)  
```

It can be resolved by deploying a private version:
```sh
$ wget https://github.com/zeromq/libzmq/archive/wget https://github.com/zeromq/libzmq/archive/v4.3.2.tar.gz
$ tar zxvf v4.3.2.tar.gz
$ cd libzmq-4.3.2/
$ ./configure --prefix=`pwd -P`/install
$ make -j
$ make install
$ export LD_LIBRARY_PATH=`pwd -P`/install/lib:$LD_LIBRARY_PATH
$ export LD_RUN_PATH=`pwd -P`/install/lib:$LD_RUN_PATH
$ pip install --no-cache-dir --force-reinstall --ignore-installed --no-binary :all: --install-option="--zmq=`pwd -P`/install" pyzmq
```

Yes, that last line looks ridiculous, but it's the only option combination I found which actually uses that new install:
```
$ ldd /p/gpfs1/merzky1/radical.pilot.sandbox/ve.llnl.lassen.1.4.0/lib/python3.7/site-packages/zmq/backend/cython/socket.cpython-37m-powerpc64le-linux-gnu.so | grep -i zmq
        libzmq.so.5 => /p/gpfs1/merzky1/radical.pilot.sandbox/libzmq-4.3.2/install/lib/libzmq.so.5 (0x00002000000c0000)
```

This ZMQ module needs to be installed in the *pilot* virtualenv.  With this setup, the pilot will not experience the hangup and will continue.  Alas, jsrun now seems to fail:
```sh
agent_executing.0000.log:1589797633.294 : agent_executing.0000 : 76532 : 35184620270000 : INFO     : Unit unit.000000 has return code 255.
```

without leaving an error in `STDERR` or anywhere, so that still needs tracing down - might just be a missing module load or env setup.  Probably best to try to run the task launch command manually on an unteractive node and to invoke support on jsrun problems.

**Comment by mtitov** [comment]
@andre-merzky I confirm that reached this point as well. And then I've tried an interactive mode as you proposed as well - I tried to use already created "Resource Set" file `unit.000000.rs` - thus with the 1st run it didn't return anything, with the 2nd it returned an error:
```
[titov1@lassen709:~]$ lalloc 1
Disabling X forwarding, DISPLAY not set
+ exec bsub -nnodes 1 -Is -W 60 -core_isolation 2 /usr/tce/packages/lalloc/lalloc-2.0/bin/lexec
Job <1089186> is submitted to default queue <pbatch>.
<<Waiting for dispatch ...>>
<<Starting on lassen710>>
<<Waiting for JSM to become ready ...>>
<<Redirecting to compute node lassen610, setting up as private launch node>>
titov1@lassen610:~]$ jsrun -n 1 /usr/bin/date
Mon May 18 10:14:32 PDT 2020
[titov1@lassen610:~]$ cd /p/gpfs1/titov1/radical.pilot.sandbox/rp.session.lassen709.titov1.018400.0000/pilot.0000/unit.000000/
[titov1@lassen610:unit.000000]$ jsrun --erf_input unit.000000.rs /usr/bin/date
[titov1@lassen610:unit.000000]$ jsrun --erf_input unit.000000.rs /usr/bin/date
Error: error in ptssup_mkcltsock_afunix()
05-18-2020 10:15:31:153 55047 main: Error initializing RM connection. Exiting.
```
After I removed the 1st line in `unit.000000.rs` - it worked! (removed `cpu_index_using: physical\n` which is set [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/jsrun.py#L87))
```
(ve.rp) [titov1@lassen709:unit.000000]$ cat STDOUT
0 : PID     : 51848
0 : NODE    : lassen611
0 : CPUS    : 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001100000000
0 : GPUS    : 00000
0 : RANK    : 0
0 : THREADS : 2
0 : SLEEP   : 0
```

Need further your help in understanding of this - should that line be eliminated? or it is crucial for Summit?

**Comment by andre-merzky** [comment]
Cool!

@iparask : I think you looked into physical vs. logical resource IDs on summit, IIRC?  Any opinions?

@mtitov : I would prefer not to touch the summit code path, as it works well, and as of yet we don't know if that is also true with the changed resource sets.  Would you mind adding a switch based on the hostname?  Once that is in place we can give the same code on summit a try to see how it behaves.

I would also suggest to open a ticket with Lassen about the failure with the original resource set.

**Comment by andre-merzky** [comment]
Just for the record: I'll also open an issue about ZMQ, maybe they are willing to provide a libzmq module.  I would like not to get into the mode that we maintain libzmq installations on the machine...

**Comment by mtitov** [comment]
Looks like such ZMQ behavior occurs with pip installation (link to the system lib), with conda installation it uses libs from conda env (see the following example):
```
[titov1@lassen708:titov1]$ conda activate powerai
(powerai) [titov1@lassen708:titov1]$ ldd anaconda/envs/powerai/lib/python3.7/site-packages/zmq/backend/cython/socket.cpython-37m-powerpc64le-linux-gnu.so | grep -i zmq
	libzmq.so.5 => /usr/WS2/cv_ddmd/titov1/anaconda/envs/powerai/lib/python3.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5 (0x00002000000c0000)
	libsodium.so.23 => /usr/WS2/cv_ddmd/titov1/anaconda/envs/powerai/lib/python3.7/site-packages/zmq/backend/cython/../../../../.././libsodium.so.23 (0x0000200000440000)
	libstdc++.so.6 => /usr/WS2/cv_ddmd/titov1/anaconda/envs/powerai/lib/python3.7/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6 (0x00002000004b0000)
	libgcc_s.so.1 => /usr/WS2/cv_ddmd/titov1/anaconda/envs/powerai/lib/python3.7/site-packages/zmq/backend/cython/../../../../.././libgcc_s.so.1 (0x0000200000660000)
(powerai) [titov1@lassen708:titov1]$ conda list --show-channel-urls | grep zmq
pyzmq                     18.1.1           py37he6710b0_0    defaults
```
Later, when RP is launched using conda-env `powerai` and it creates env on its own, zmq lib still has correct links:
```
# config
            python_dist: "default",
            rp_version: "local",
            virtenv_dist: "default",
            virtenv_mode: "create",

# zmq links
(powerai) [titov1@lassen708:radical.pilot.sandbox]$ ldd ve.llnl.lassen.1.4.0/lib/python3.7/site-packages/zmq/backend/cython/socket.cpython-37m-powerpc64le-linux-gnu.so | grep -i zmq
	libzmq.so.5 => /usr/workspace/cv_ddmd/titov1/anaconda/envs/powerai/lib/libzmq.so.5 (0x00002000000c0000)
```
@andre-merzky since this is not an issue of RP, what our next steps? is ZMQ issue considered to be resolved?

**Comment by andre-merzky** [comment]
Ah, thanks for the ping - I forgot to open the Lassen issue to update ZMQ - will do.

**Comment by andre-merzky** [comment]
closed for lack of activity

**Comment by lee212** [comment]
I am seeing this error on Summit:
```
Error: error in ptssup_mkcltsock_afunix()
06-08-2021 12:33:25:749 19282 main: Error initializing RM connection. Exiting.
```
I am attempting to remove `cpu_index_using: physical` the line in the erf file to see if it fixes the issue. Any guidance?

**Comment by andre-merzky** [comment]
@mtitov : any idea what's up?  Maybe again a problem with the system `libzmq` or the compiler chain?

**Comment by mtitov** [comment]
Error that Hyungro mentioned is not related to zmq, but rather to `jsrun` option `--erf_input` and corresponding file format. That is something new for Summit and for the similar issue on Lassen the latest recommendation from the support team was to use the following line `cpu_index_using: logical` instead of what Hyungro showed.

@lee212 can you please do a test changing this [line](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/jsrun.py#L105) accordingly within your virtual env on Summit?

**Comment by lee212** [comment]
I just submitted a job with `logical` value, and will report if it fixes.
