### ISSUE TITLE
Tagging is not working any more

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2152]
Tags are defined in the Unit description as a dictionary (see [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_unit_description.py#L41) and [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_unit_description.py#L385)), while the scheduler checks for `tag` (see [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/scheduler/continuous.py#L364)).

First the check in the scheduler is different from the unit description key and second, there is no example in the documentation that shows how a tag can be a dictionary. If I remember correctly it was a string. This in turn affects EnTK's tagging capabilities

**Comment by andre-merzky** [comment]
closed as fixed.
