### ISSUE TITLE
Improve error handling for missing packages in bootstrap.sh

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2160]
`bootstrap.sh` may require non-built-in shell commands. When the commands are missing, a script may fail without producing errors at the terminal or in `.err` files, or the script may simply hang indefinitely. It may be excessive to attempt to document every tool that is assumed to be available from the various shell environments encountered in the Radical stack. A sufficient solution would be to improve the catching and reporting of errors from shell errors encountered in bootstrap.sh or other such scripts.

```
$ python -V
Python 3.6.9
$ radical-stack

  python               : 3.6.9
  pythonpath           :
  virtualenv           : /home/rp/rp-venv

  radical.pilot        : 1.4.0-v1.4.0-11-g644826767@HEAD-detached-at-644826767
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0
```

To reproduce, run the `examples/misc/task_overlay.py` script in an environment without `curl`, `dig`, and/or `ping`.

Example:

1. Check out https://github.com/eirrgang/radical.pilot/commit/6448267674bac1e2a5c66767cba5a5a9e7d563c8
2. Merge `devel` (e.g. https://github.com/radical-cybertools/radical.pilot/commit/f90f49361d776476eb74538731400f45ed881dca)
3. Set `cores` to a reasonable number, like 4, in the task_overlay.py script.
4. Build and launch the environment:
   ```
   cd docker
   docker build -t radicalpilot -f radicalpilot.dockerfile ..
   docker-compose -f stack.yml up
   ```
5. Either background the `docker-compose` or use a separate terminal to connect to the radical container.
   ```
    docker exec -ti -u rp docker_login_1 bash -c "cd && . /home/rp/rp-venv/bin/activate && python /radical.pilot/examples/misc/task_overlay.py"
   ```
   or
   ```
    docker exec -ti -u rp docker_login_1 bash
   ```
   and run the script.

**Comment by andre-merzky** [comment]
Closing as outdated
