### ISSUE TITLE
config discussion

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2161]
### current state:

  * flat hierarchy in resourcre configs (json)
  * pro: simple
  * con: many replication, undocumented, not type checked, hard to maintain, badly exposed in API

### cfg composition:

  * see [example](https://github.com/radical-cybertools/radical.pilot/blob/version/2/src/radical/pilot/configs/resource_local.json), different sections could be moved into separate files
  * pro: less repetition, easier to maintain, composition can be controled from pilot description
  * no type checking, still repetitions, no easy documentation

### cfg inheritance:
  * see [example](https://github.com/radical-cybertools/radical.utils/pull/242/files)
  * pro: easier to document (base json), no repetition
  * con: no type checking, not easily exposed on API level

### cfg composition + inheritance:
  * see [PR](https://github.com/radical-cybertools/radical.utils/pull/242) 
  * pro: less repetition, easier to maintain, composition can be controled from pilot description, easier to document (base json)
  * con: inheritance during loading, composition static for app lifetime, no type checking, no easy documentation (no sphinx)

### codify config sections as `ru.Description` classes
  * create schema for each class, inherit sub types, allow representation in file system
  * pro: use Python class inheritance, documentation easy via code docs (sphinx), type checking, exposure on API level
  * con: ?

**Comment by mtitov** [comment]
Since `radical.utils` version 1.5.2 config inheritance is implemented (`ru.Munch`-based, similar as `ru.Description`)
