### ISSUE TITLE
ResourceConfig documentation error?

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2181]
https://radicalpilot.readthedocs.io/en/stable/machconf.html#customizing-resource-configurations-programatically describes using `radical.pilot.ResourceConfig`, which doesn't seem to exist.

What is the appropriate way to programmatically query the default definition of a resource (without creating a Session), such as the preconfigured `local.localhost`?

  python               : 3.7.5
  pythonpath           : 
  virtualenv           : /Users/eric/.virtualenvs/SCALE-MS

  radical.pilot        : 1.4.1-v1.4.1-137-gda2913b2c@devel
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0

**Comment by mturilli** [comment]
Thank you for spotting the badly outdated piece of documentation. We dropped the object semantics and went for a dictionary one that is more consistent with what our developers prefer. While I try to fix that, here a quick untested alternative:
```
s = rp.Session()
cfg = copy.deepcopy(s.get_resource_config('local.localhost'))
cfg.python = 'anaconda'
cfg.label = 'local.localhost_anaconda'
s.add_resource_config(cfg)
```
`s.list_resources()` should give a list of existing resource labels. Note that I do not have a way to do this without creating a session.

Will ping back once I will have updated the documentation page.

**Comment by eirrgang** [comment]
I was looking for a way to query default values or programmatically access the schema before creating a Session, but it sounds like there may not be such a thing right now.

Maybe the config file location resolution could be more exposed to the client, or the deserializer or schema validation could be made easier to find.

May be related to #2161 

Oops... Is this a duplicate of #2086 ?

**Comment by mtitov** [comment]
This issue is resolved - https://radicalpilot.readthedocs.io/en/devel/machconf.html#customizing-resource-configurations-programmatically Should we close the ticket?

**Comment by andre-merzky** [comment]
Ping @eirrgang

**Comment by eirrgang** [comment]
The section referred to in this issue now appears accurate.

Is #2086 also resolved?

**Comment by andre-merzky** [comment]
Documentation is removed now, this is not supported anymore :-/
