### ISSUE TITLE
Tunneling for DB and APPs (separate flags?)

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2191]
With the current implementation, if tunneling is set by parameter `forward_tunnel_endpoint` in resource config, it is always used for MongoDB connection in the first place, and it cannot be set only for APP (source host for APP is set by environment variable `RP_APP_TUNNEL_ADDR`)
# 
Tunnel is created by `radical.pilot.agent.bootstrap_0.sh` (function `get_tunnel()`)

**Comment by andre-merzky** [comment]
Waits for MongoDB removal

**Comment by mturilli** [comment]
Relates to https://github.com/radical-cybertools/radical.pilot/discussions/2410

**Comment by andre-merzky** [comment]
closing as outdated
