### ISSUE TITLE
Update the config resource of cores and gpus in all examples

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2192]
This issue is tracking the progress of replacing the way RP specifying the number of  `cores` and `gpus` as follows :

```
 pd.cores = config[resources]['cores'] = 1 --> pd.cores = config[resource].get('cores', 1)
 pd.cores = config[resources]['gpus']  = 0 --> pd.gpus  = config[resource].get('gpus', 0) 
``` 
this suggestion is based on this [comment](https://github.com/radical-cybertools/radical.pilot/pull/2172#pullrequestreview-441760363). This will make the maintaining process of the config easier.

**Comment by andre-merzky** [comment]
Thanks @AymenFJA !  Can you please also add getters for the other gonfig settings (queue, project, etc - with `None` default values)?  Thank you!

**Comment by AymenFJA** [comment]
The PR #2172 is merged, this ticket will be closed.
