### ISSUE TITLE
Pilot heartbeat events are recorded in agent.0.prof

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2195]
I am not sure whether this is intentional but it seems not the best location for recording this event. We end up with a ton of:
```
1595418259.2930932,cmd,agent.0,Thread-7,pilot.0000,,pilot_heartbeat : {'pmgr': 'pmgr.0000'}
```

As a side effect, this event is also recorded as a pilot event and ends up poisoning the output of RADICAL-Analytics calls like:
```
session.get(etype='pilot', uid='pilot.0000')[0].timestamps()
```

**Comment by andre-merzky** [comment]
Should be filtered out by profile filter

**Comment by mturilli** [comment]
Now part of the discussion at https://github.com/radical-cybertools/radical.pilot/discussions/2408

**Comment by andre-merzky** [comment]
This is fixed.
