### ISSUE TITLE
Examples for LM tweaking

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2239]

**Comment by mtitov** [comment]
**Srun** ([link](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/srun.py#L110)) for WF3 at SuperMUC-NG
RP default: `srun --exclusive --cpu-bind=none --nodes %d --ntasks %d ...`
Asked for a run (without extra options): `srun --nodes %d --ntasks %d ...`

**Comment by mturilli** [comment]
Ping

**Comment by andre-merzky** [comment]
We don't use supermuc anymore, and I don't think the requirement listed above is still active.  @darkwhite29 ?

**Comment by mtitov** [comment]
This ticket is more as a discussion and `srun` command for supermuc was just as an example - to be able to create a launch command with default options, but also consider possibility to overwrite that default options if needed
