### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Achraf-Nagihi** [radical-cybertools/radical.pilot#2240]
hello i am trying to run my program from terminal with this command: 
```sh
lmp380 <in.cohesion
```
but instead i get :
```sh
lmp380 "<in.cohesion" 
```
which is not working
```py
        cud.executable       = 'lmp380'
        cud.arguments        = '< in.cohesion'
```
```sh
 $ radical-stack

     python               : 3.8.5
     pythonpath           : 
     virtualenv           : /home/kodai/RADICALPilot

     radical.gtod         : 1.5.0
     radical.pilot        : 1.5.2
     radical.saga         : 1.5.2
     radical.utils        : 1.5.3

**Comment by andre-merzky** [comment]
Indeed, shell directives are generally not supported as arguments.  If you really must run this under a shell, please do so explicitly:
```py
    cud.executable       = '/bin/sh'
    cud.arguments        = ['-c', 'lmp380 < in.cohesion']
```

**Comment by Achraf-Nagihi** [comment]
Okey, Thanks, can you please tell me what -c means ? or where can i find documentation about it .

**Comment by andre-merzky** [comment]
`-c` is a POSIX defined argument to the shell executable (`/bin/sh`) which instructs the shell to read it's commands from the argumentt list instead of `stdin` - see [here](https://pubs.opengroup.org/onlinepubs/009695399/utilities/sh.html) for details.  You can try this on command line:
```sh
$ /bin/sh -c 'for arg in foo bar; do echo $arg; done'
foo
bar
```

**Comment by Achraf-Nagihi** [comment]
Thank you, @andre-merzky :) .
