### ISSUE TITLE
clarify failure mode for `pilot.prep_env`

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2257]

**Comment by mturilli** [comment]
@andre-merzky is this still valid with the upcoming #2265 #2312 ?

**Comment by andre-merzky** [comment]
This should be largely addressed by #2312, or at least the problem should have shifted then.  But we should leave this ticket open, needs confirmation.

**Comment by andre-merzky** [comment]
Is fixed
