### ISSUE TITLE
Pilot timeout

### ISSUE THREAD

**Issue by adw62** [radical-cybertools/radical.pilot#2278]
Hello,

I'm a new user of RCT on Summit. I'm having a problem were RCT is timing out waiting for the pilot.

This issue is occurring for jobs which previously ran without issue but, after interruptions to the connection between Summit and the mongoDB at University College London* yesterday, will timeout very quickly (I'm not sure if this is related to my current issue as I have started new runs since the connection was restored)

The output to these commands are:
```
$ python -V  
Python 3.7.7

$ radical-stack
  python               : 3.7.7
  pythonpath           : /sw/summit/xalt/1.2.1/site:/sw/summit/xalt/1.2.1/libexec
  virtualenv           : 

  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7
  radical.saga         : 1.5.7
  radical.utils        : 1.5.7
```
I have attached a example script which fails after timing out.
[test1.txt](https://github.com/radical-cybertools/radical.pilot/files/5629530/test1.txt)

 Any help would be greatly appreciated.

\* Correction I think this is a MongoDB hosted by radical.

**Comment by mturilli** [comment]
Hi @adw62, let's try to use another MongoDB. Please enter your data here https://docs.google.com/spreadsheets/d/1Z-UNb6U7x6KPZbsV7Zcey_Cgx_UuHR_Sj-FYzkONEiE/edit#gid=472887260 (you will have to request access to the document that I will promptly authorized). Seeing that you are in a hurry, I will create your account right away. Note that the spreadsheet has multiple tabs at the bottom, please use the 'MongoDB' tab.

**Comment by mturilli** [comment]
@adw62 thank you for entering the data. Please note that you used an exiting user/db name, the same requested by Agastya. You my want to use his login or if you want you own you will have to enter a unique user/db name.

**Comment by adw62** [comment]
@mturilli Can I ask is a user name you are creating for me or one that I should have created previously and I need to now provide to you?

**Comment by mturilli** [comment]
You need a unique username. I modified your entry to that end. Are you on slack? I need to give you your password.

**Comment by adw62** [comment]
Yes, I have sent you a direct message.

**Comment by mturilli** [comment]
OK, I will leave this open until you confirm that the timeout issue has been addressed.

**Comment by mturilli** [comment]
@adw62 provided session and sandbox on summit at `/gpfs/alpine/world-shared/chm155/alex`. Upon inspection, the problem is with the recently updated `pip` interface, not with MongoDB. As reported by @iparask, `no such option: --build`, see `/gpfs/alpine/world-shared/chm155/alex/radical_err/sandbox/re.session.login4.adw62.018599.0009/pilot.0000/bootstrap_0.out` for details. 

@andre-merzky @iparask do we have a hotfix for this?

**Comment by mturilli** [comment]
@adw62 please try to use the `devel` branch of RADICAL-Pilot. That should fix the issue with the bootstrapper on Summit.

**Comment by adw62** [comment]
Moving to the `devel` branch has fixed the timeout issue. 

thanks,
Alex
