### ISSUE TITLE
Handle cores on Summit (manage ids of available and blocked cores)

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2279]
This ticket as a continuous discussion related to introduced resource config parameters `blocked_cores/gpus` in PR #2263 

Mikhail's comment

> I have something to discuss about cores (including blocked ones) on Summit:
> 
>     * each node has 2 sockets with 22 physical cores each
> 
>     * 1 core on each socket is not available for allocation through jsrun
>       
>       * Summit provides 42 cores (set through env variable LSB_DJOB_HOSTFILE)
>       * core ids: 0-20,22-42 (thus `#21` and `#43` are removed)
> 
> 
> Thus, we deal with all available cores per node, but their sequence of ids is "broken" in the middle.
> Should we not just read information about cores from Summit, but set cores_per_node on our side as well (what we currently don't do)? Then resource config would have 44 cores per node and cores `#21` and `#43` blocked?

Andre's comment

> Well, that sounds reasonable, but I'd rather not fix what isn't broken.  In other words, I am not sure of the side effects of that change.  Like, if we set cpn, then the pilot launcher will pick it up and use it to talk to SAGA.  Will SAGA still be able to get nodes with that cpn value even if LSF knows that that many cores are not usable?  And there are maybe other places where cpn is used - we would need to check those first.

Proposal: to check the possibility of changing cores id on RP side (RP and RS)

**Comment by mturilli** [comment]
Ping
