### ISSUE TITLE
Agent calls method `stop` (termination) twice

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2309]
When agent gets command `cancel_pilot` it (1) publishes command `terminate` to control pubsub ([link](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/agent_0.py#L518)) and (2) calls method `stop` (method of the base class `rpu.Component`) which then triggers its own method `finalize`. Command `terminate` is handled at the method `_cancel_monitor_cb` (also method of the base class `rpu.Component`, [link](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/utils/component.py#L538)), which also calls method `stop`.

Should the first or second call of `stop` be removed?

p.s. I found it since it triggered `ResourceManager.stop()` twice (from [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/agent_0.py#L259)), in agent's method `finalize`

**Comment by andre-merzky** [comment]
@mtitov : check if still valid

**Comment by mturilli** [comment]
@mtitov ping
