### ISSUE TITLE
State mismatch: PR (or SP) apparently unaware that a job has run out of walltime

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#231]
While running examples/late_binding.py I noticed the following in the verbose debug output following the regular cancellation of a job by the remote scheduler due to end of the given walltime:
```
2014:07:17 13:05:04 38118  MainThread   saga.ShellDirectory   : [DEBUG   ] read : [   12] [   45] (qstat: Unknown Job Id 1041326.s82\nPROMPT-1->)
2014:07:17 13:05:04 38118  MainThread   saga.PBSJobService    : [ERROR   ] Couldn't reconnect to job '[pbs+ssh://sierra.futuregrid.org]-[1041326]': qstat: Unknown Job Id 1041326.s82

2014:07:17 13:05:04 radical.pilot.PilotLauncherWorker-1: [ERROR   ] Couldn't determine job state for ComputePilot 53c7fc27dbbb4694e0f288a2. Assuming it has failed to launch.
```
Does this mean that either radical.pilot and/or saga.python are not aware of this type of state change?

**Comment by andre-merzky** [comment]
Mark, did you ponder over this?  Any suggested action?

**Comment by andre-merzky** [comment]
Mark, any updates? :)

**Comment by marksantcroos** [comment]
Not really, too many moving parts and different behaviour per system. Nothing actionable currently.

**Comment by andre-merzky** [comment]
Closing as not actionable (right now).  Thanks!
