### ISSUE TITLE
Pilot input staging in behaves differently based on how it is done

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2333]
We can define input staging for the pilot in two different ways. The first is through the pilot description and the second through the `pilot.stage_in()` method. While both ways are doing the same thing, they have different results. We want to do the following stage in `file1.txt > test/file1.txt`. If we do it through the pilot description, adding `'input_staging': ['file1.txt > test/file1.txt']`, the pilot will place the file under the pilot sandbox and will not create the test folder. If we do `pilot.stage_in(['file1.txt > test/file1.txt'])`, the file will be placed under a `test` folder in the pilot sandbox.

I think this is because these two actions, although similar, are treated differently. The first case is resolved in the `_start_pilot_bulk` in the PMGR, [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L664-L668), which uses RS to stage in the data. The second case calls PMGR's `_pilot_staging_inputs` ([here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pilot.py#L606)) which uses the PMGR stager component.

Is this difference between the two methods intended?

This is triggered by radical-cybertools/radical.entk#477

**Comment by andre-merzky** [comment]
The  difference is not intentional, and I would argue that creating the specified subdir is the correct one.  How does that related to the deletion of RE queues though?

**Comment by iparask** [comment]
I'm sorry I mentioned the wrong issue. I updated the previous comment.

**Comment by andre-merzky** [comment]
@kartikmodi : please check if this is still a problem

**Comment by andre-merzky** [comment]
This is addressed by now.
