### ISSUE TITLE
Task timeout

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2352]
During the HPC-workflow discussion on Friday, March 19, Wenjie mentioned that some of his tasks are executing indefinitely (RCT is not the cause of this behavior). As a result, he would like to add a timeout value per task.

1. ***Description***: Provide a timeout attribute in the task description. The executor will monitor task execution time and when the time has passed terminate the said task.
2. ***Example(s)***:
```python
 td = rp.TaskDescription()
td.executable    = '/bin/sleep'
td.arguments = ['120']
td.cpu_processes = 1
td.timeout = 60 # seconds

tmgr.submit_tasks(td)
...
# 60 seconds pass task get killed
```

Thank you!

**Comment by andre-merzky** [comment]
Raptor has that in place FWIW.  I agree that it seems useful for tasks in general, and it should be not too hard to implement for most launchers / executors.
