### ISSUE TITLE
GitHub Actions testing may miss venv-related coverage.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2373]
It looks like the RP GitLab Actions tests do not use a venv for the RP installation. It works because the user has write access to the installation directory created by the actions/setup-python action, but this may result in a hole in the coverage that would be easily plugged with just two (or 3) more lines.

Note that the venv needs to be activated for each `jobs.<name>.steps.run` entry.
E.g.
```
    - name: Install dependencies
      run: |
        python -m venv testenv
        . testenv/bin/activate
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade .
        
    - name: Test with pytest
      env:
        # use localhost for the host here because we are running the job on the VM.
        # If we were running the job on in a container this would be mongodb
        MONGODB_HOST: localhost
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }} # get randomly assigned published port
        RADILCAL_PILOT_DBURL:  mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/test
      run: |
        . testenv/bin/activate
        python -X dev -m pytest ...
```

**Comment by iparask** [comment]
Thank you, this fix is already included in PR #2375

**Comment by iparask** [comment]
When we use a venv to execute tests and report coverage codecov action send a faulty report. This made us to use Codecov's bash script.

However, we decided to revert the changes and use the codecov action, and as a consequence not a venv, for the security issues [codecov reported](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=2524780&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJ4oGmY--IC-onLm13EP5d4WfxqSvg4qw_i9qaTkWa0sZGD7Q9DYVWmtTJ-8AX0Iw7yENGXUrG1Jm2lU4k2Mzzg8ZxcLvXzhlSIdNe_J). We decided to keep the old version until we find a way to use Codecov's Github action with a venv.

Thank you.

**Comment by eirrgang** [comment]
What issue were you having with a "faulty report"?

I found that the built-in file path mappings were not sufficient for testing against an installed package, but I am using the codecov action with a venv. Maybe you need something like the following in your `.codecov.yml`?

```
fixes:
  - "*/site-packages/radical/::src/radical/"
```

**Comment by mtitov** [comment]
follow up comments on issue we had with virtualenv:
- `coverage` was running within virtualenv `testenv`, but Codecov wasn't and it tried to create a coverage report without having a `coverage` command;
- I moved report creation to the step where `coverage` was called and provided a path to that report to Codecov.
