### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2381]
The environment variable is spelled wrong.

https://github.com/radical-cybertools/radical.pilot/blob/d6a4dd59feb95c19ef465bbf44911f9232fa2874/.github/workflows/python-app.yml#L46

Are there any radical.pilot tests that actually create a `Session` successfully in a GitHub Actions workflow?

**Comment by andre-merzky** [comment]
Ha, that's funny (and embarrassing) :-P  

> Are there any radical.pilot tests that actually create a `Session` successfully in a GitHub Actions workflow

We currently don't run integration tests, so no 'real' session is created.  For the unit tests, we do create sessions, but we mock the DB interactions away IIRC.  Not finding the env is not a fatal error in itself - the session will fall back to a default URL.

Thanks for pointing that out!

**Comment by mtitov** [comment]
Resolved! Thanks for pointing that out!
