### ISSUE TITLE
Document and harden callback (un)registration.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2382]
`Task.unregister_callback()` and `TaskManager.unregister_callback()` are currently undocumented, and may not behave as expected.

There are also some caveats to the registration that should be explored, documented, and/or mitigated. The callbacks are currently registered using their `__name__` attribute as a hash key, leading to potentially unexpected behavior or limitations.

It may be that callbacks cannot be simply stored in a `set`, or effectively identified by its `id()` or `__hash__` value, because it might be called from a different process than the one in which it is registered (this would complicate `cb_data`, though, and no such caveat is documented), in which case this and the associated restrictions should be explored and documented. If this is the issue, then `__qualname__` would be a more useful attribute than `__name__`, and there should be checks on the reproducible importability of the callable at registration time.

It seems preferable to arrange to call the callback in its original process, as with [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Future.add_done_callback). If not, the documentation should note important differences between RP callbacks and similar patterns in the Python standard library (e.g. https://docs.python.org/3/library/weakref.html#weakref.ref, https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.add_done_callback, https://docs.python.org/3/library/functools.html#functools.singledispatch).

It should also be clarified whether there are any potential hashing collisions regarding registering and unregistering the same function as a callback independently for multiple Tasks, or multiple times for the same Task with different `cb_data` collections or `metric` values.

The `metric` parameter of `Task.register_callback()` is undocumented, and the relationship between `Task.register_callback()` and `TaskManager.register_callback()` (where `metric` is documented) is not obvious.

Note also that more normative alternatives to `cb_data` would be to allow users to use `functools.partial` to bind additional arguments, to use lambdas or closures, and/or to provide an optional `contextvars.Context` in which to run the callback.

See also https://github.com/SCALE-MS/scale-ms/issues/115#issuecomment-825031451

**Comment by andre-merzky** [comment]
Closing as outdated
