### ISSUE TITLE
radical.pilot.Session.add_context() is undocumented

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2383]
https://radicalpilot.readthedocs.io/en/stable/machconf.html#configuring-ssh-access describes using `radical.pilot.Session.add_context()`, but the [API documentation](https://radicalpilot.readthedocs.io/en/stable/apidoc.html#sessions) does not include this method.

**Comment by andre-merzky** [comment]
... and unsupported.  Closing.
