### ISSUE TITLE
Document schema for radical.pilot.Context

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2384]
https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Context is illustrated at https://radicalpilot.readthedocs.io/en/stable/machconf.html#configuring-ssh-access, but the interface is not explained. The [API documentation](https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Context) does not describe the available schema.

Relates to #2383

**Comment by andre-merzky** [comment]
Closing as outdated
