### ISSUE TITLE
radical.pilot `__repr__()` methods have confusing output.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2391]
RP objects can have confusing `repr()` output.

For Task and Pilot, at least, `__repr__()` gives a string representation of a list object, which is unconventional and confusing. It gives the appearance that a Pilot instance *is* a list. Furthermore, the elements represented are not related to the `__init__()` signature in any way.

Since this output duplicates the `__repr__()` output, it actually removes utility. If the `__repr__()` function were removed, it would be more obvious (at least in common debugging scenarios) that an object is in fact a Pilot instance and not an unexpected list.

My request would be either
1. to redefine `__repr__()` to return the conventional output that could conceivably be `eval` ed to instantiate the represented object,
2. format the output with a description between angle brackets (`<...>`), clearly indicating the object is a Pilot instance, or
3. to remove the `Pilot.__repr__()` definition so that the interpreter default is used.

A reasonable alternative could be to return the full dictionary representation. This would seem more appropriate for `__str__()`, but could be made more conventional by formatting in the form of a `PilotManager.submit_pilots()` call.

**Comment by eirrgang** [comment]
updated to indicate that Pilot is not the only class with a confusing `__repr__()`.

**Comment by mturilli** [comment]
@andre-merzky ping.

**Comment by andre-merzky** [comment]
All true, but alas this is not high on the priority list...

**Comment by eirrgang** [comment]
> All true, but alas this is not high on the priority list...

Would you want a pull request?

**Comment by andre-merzky** [comment]
> Would you want a pull request?

Sure, if you want to put something simple together?  Thanks!

**Comment by eirrgang** [comment]
> Sure, if you want to put something simple together? Thanks!

I can do that some time in July. Do you prefer option 1, 2, or 3?

**Comment by andre-merzky** [comment]
I don't think we'll support `eval(repr(obj)) == obj`, so 2 or 3 would make sense.  Either works for me really.
