### ISSUE TITLE
Support for Multi-Instance GPU (MIG) mode for NVIDIA A100 GPUs

### ISSUE THREAD

**Issue by braceal** [radical-cybertools/radical.pilot#2393]
1. ***Description***: Multi-Instance GPU (MIG) mode allows a single NVIDIA A100 GPU to be reconfigured at a hardware level down to a maximum of 7 instances. We plan to use MIG mode to run up to 7x more molecular dynamics simulation tasks per GPU (depending on system sizes) which enhances ensemble sampling. More information on our specific cluster and it's support of MIG mode can be found here: https://www.alcf.anl.gov/support-center/theta-gpu-nodes/running-jobs-thetagpu

2. ***Example(s)***: We would like to use a configurable option in the radical.entk layer that supports assigning task resources to MIG-enabled GPU instances.

**Comment by mturilli** [comment]
Once we support this via `--attrs mig-mode=True` on ThetaGPU, we should make it available on EnTK. Will be happy to open a ticket in EnTK once this is supported by RP.

**Comment by mtitov** [comment]
This option should go into SAGA, but corresponding parameters will be set in resource config.

@andre-merzky should we make changes here similar to what we did for LSF (Summit, Lassen): to have the following parameter in resource config:
```
"system_architecture"         : {"options": ["mig-mode=True"]}
```
and then in SAGA.Cobalt, read that information and add it with lines as (in `for` loop per option) `'#COBALT --attrs %s\n' % option`

**Comment by andre-merzky** [comment]
> @andre-merzky should we make changes here similar to what we did for LSF (Summit, Lassen): to have the following parameter in resource config   [...]

@mtitov : yes, that sounds like the right approach.

**Comment by mtitov** [comment]
Corresponding update was made for SAGA layer ([SAGA#827](https://github.com/radical-cybertools/radical.saga/pull/827)) and for now it is available from devel-branch there, thus adding a parameter `"system_architecture"` with `"options"`-key to resource config will bring that attributes (key-value pairs) to Cobalt script.

I also will do a review and update of launch method `aprun`

**Comment by mtitov** [comment]
RADICAL-SAGA has necessary [capabilities](https://github.com/radical-cybertools/radical.saga/blob/5b5ff399fbe4979ad2f9217129b97e50ea6283cb/src/radical/saga/adaptors/cobalt/cobaltjob.py#L260-L262) and corresponding resource description (`anl.theta_gpu`) has this option set
https://github.com/radical-cybertools/radical.pilot/blob/23138d8c05e0766876b7119492ab25456e53f760/src/radical/pilot/configs/resource_anl.json#L63
