### ISSUE TITLE
VMD/NAMD Segmentation fault by prrte launcher

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2402]
At Summit, `prun` doesn't get along with VMD/NAMD (compiled with MPI) as they failed with a segmentation fault. May I seek help to resolve this issue? I provide some details here:

The error message of VMD task looks like:
```
$ more re.session.login5.hrlee.018797.0007/pilot.0000/task.0000/task.0000.err
[batch5:127412] Calling PMIx_Spawn
[batch5:127412] JOB [8186,2] EXECUTING
Segmentation fault
[batch5:127412] PRUN: EVHANDLER WITH STATUS JOB ENDED(-145)
[batch5:127412] JOB [8186,2] COMPLETED WITH STATUS 0

```
And the `task.sh` has `prun` command correctly like:
```
$ grep prun re.session.login5.hrlee.018797.0007/pilot.0000/task.0000/task.0000.sh
prun --dvm-uri "prte-batch5126707.0;tcp4://10.134.0.45:41643"  --np 1 --map-by node:HWTCPUS:PE=4 --bind-to \
hwthread:overload-allowed --host h50n15:1 --pmixmca ptl_base_max_msg_size 1073741824 --verbose \
/gpfs/alpine/world-shared/bip212/git/MDFF-EnTK-April-2021/vmd1.sh
```

The wrapper script (`vmd1.sh`) is created to load specific modules (e.g., spectrum-mpi) and set `LD_LIBRARY_PATH`, (these are simply moved from `pre_exec`) as there are conflicts with prrte modules. 

The executable has no problem locating libraries but from other places. Again, the executable works fine with `jsrun` and `mpirun` but `prun`. and the behavior is the same with NAMD.

```
$ radical-stack

  python               : /gpfs/alpine/world-shared/bip212/conda/rct/bin/python3
  pythonpath           : /sw/summit/xalt/1.2.1/site:/sw/summit/xalt/1.2.1/libexec
  version              : 3.6.12
  virtualenv           : /gpfs/alpine/world-shared/bip212/conda/rct

  radical.entk         : 1.6.5
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.6
  radical.saga         : 1.6.6
  radical.utils        : 1.6.6

```

I attach sandboxes for further investigation.
- re.session.login5.hrlee.018797.0007.tar.gz (prun) 
[re.session.login5.hrlee.018797.0007.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/6684326/re.session.login5.hrlee.018797.0007.tar.gz)

- re.session.login5.hrlee.018798.0001.tar.gz (jsrun)
[re.session.login5.hrlee.018798.0001.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/6684404/re.session.login5.hrlee.018798.0001.tar.gz)

**Comment by mtitov** [comment]
@lee212 can you please attach `/gpfs/alpine/world-shared/bip212/git/MDFF-EnTK-April-2021/vmd1.sh` as well?

is the file `skipped_first_three_lines.env` just reflects env setup for `prrte`? (was it collected right before `prun` command?) do you have a pilot sandbox of a run where you did env setup from `jsrun` for `prrte`?

here is a comparison of loaded modules for `jsrun` and `prrte:
```
jsrun: export LOADEDMODULES="hsi/5.0.2.p5:lsf-tools/2.0:darshan-runtime/3.1.7:DefApps:gcc/8.1.1:zeromq/4.2.5:python/3.7.0"
prrte: export LOADEDMODULES="hsi/5.0.2.p5:lsf-tools/2.0:darshan-runtime/3.1.7:DefApps:gcc/6.4.0:libevent/2.1.12:hwloc/2.2.0:pmix/4.0.0:prrte/master"
```
should we try `prrte` run with the same modules loaded for `jsrun` (put it in wrapper script)?

**Comment by lee212** [comment]
```
$ cat /gpfs/alpine/world-shared/bip212/git/MDFF-EnTK-April-2021/vmd1.sh
#!/bin/sh
. /sw/summit/lmod/lmod/init/profile
module list
module purge
#  1) xl/16.1.1-5   2) spectrum-mpi/10.3.1.2-20200121   3) hsi/5.0.2.p5   4) xalt/1.2.1   5) lsf-tools/2.0   6) darshan-runtime/3.1.7   7) DefApps
tmp=$(tail -n+4 ../env.bs_0);printf "$tmp" > skipped_first_three_lines.env
curpath=$(pwd)
source `pwd`/skipped_first_three_lines.env
echo source `pwd`/skipped_first_three_lines.env
module load xl xalt spectrum-mpi hsi lsf-tools darshan-runtime DefApps
module list
#export LD_LIBRARY_PATH=/gpfs/alpine/world-shared/bip115/VMD_binaries/VMD-1.9.3-xlc-build-2019-Dec-12/vmd/:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-5/spectrum-mpi-10.3.1.2-20200121-p6nrnt6vtvkn356wqg6f74n6jspnpjd2/lib:$LD_LIBRARY_PATH
ldd /gpfs/alpine/world-shared/bip115/VMD_binaries/VMD-1.9.3-xlc-build-2019-Dec-12/vmd/vmd_SUMMIT
env
cd $curpath
echo $curpath
ls -al
/gpfs/alpine/world-shared/bip115/VMD_binaries/VMD-1.9.3-xlc-build-2019-Dec-12/bin/vmd -dispdev text -e first_stage.tcl
```

> is the file skipped_first_three_lines.env just reflects env setup for prrte? 

it is copy of env.bs_0 except a few lines of invalid syntax.

> do you have a pilot sandbox of a run where you did env setup from jsrun for prrte?

Is this about envs captured in `jsrun`? then yes I do have stored envs in `jsrun` so that I can check what variables are differently configured.

> should we try prrte run with the same modules loaded for jsrun (put it in wrapper script)?

I see gcc, zeromq and python are different, I can try to sync the module list.

**Comment by mtitov** [comment]
@lee212 the idea with env setup was the following - to get environment that was used for `jsrun` and use it for `prrte`, but in your example I see that for `prrte` you just re-used environment that already was set for it

btw, I don't see line `ldd /gpfs/alpine/world-shared/bip115/VMD_binaries/VMD-1.9.3-xlc-build-2019-Dec-12/vmd/vmd_SUMMIT` for `jsrun` task script, is it required?

**Comment by lee212** [comment]
It is not required, it's added to print out the path of shared libraries.

**Comment by mturilli** [comment]
@lee212 is this affecting the experiments for the MDFF paper?

**Comment by lee212** [comment]
This does not stall the paper but I think it would be good if we can show large (922 nodes) runs, where we currently include 400 node runs.

**Comment by lee212** [comment]
@mtitov 
[prte_env_for_vmd.txt](https://github.com/radical-cybertools/radical.pilot/files/6772487/prte_env_for_vmd.txt)
[jsrun_env_for_vmd.txt](https://github.com/radical-cybertools/radical.pilot/files/6772488/jsrun_env_for_vmd.txt)
would these help for debugging env variables between prte and jsrun?

**Comment by mtitov** [comment]
@lee212 I think my [comment](#issuecomment-865040891) above, about loaded modules for `jsrun` to use for `prrte` run (within wrapper for executable), could be a first step to try. If that will fail then extend wrapper with env variables from your file `jsrun_env_for_vmd.txt` (but tricky with what variables to pick and that should be done manually)

**Comment by lee212** [comment]
@mtitov , do you think this is either a module problem or an env problem? because I purged/reset module and loaded the same list used for jsrun in the wrapper (see the vmd1.sh), `module load xl xalt spectrum-mpi hsi lsf-tools darshan-runtime DefApps`
this won't work, the executable still throws segmentation error.
Also, the jsrun env is tested, I ignored what to load but override every variables defined in the jsrun, it throws seg fault again.

the vmd/namd commands are publicly available if you want to try:
https://github.com/radical-collaboration/MDFF-EnTK/blob/master/cfg/workflow_cfg.yml#L144-L145
input files are required but I can place them somewhere so that you can test these executable with prrte.

**Comment by mtitov** [comment]
@lee212 as I see at least `gcc` was missed (not clear was the right one loaded eventually)

**Comment by lee212** [comment]
gcc is not loaded in the executable with `jsrun`, and vmd does not require any module load, (default modules might be needed though).

**Comment by mtitov** [comment]
have the following conclusion* for now: because NAMD&VMD are built with Spectrum-MPI it conflicts w/ `prrte/prun`. If it is possible to build executables with `openmpi/master[.debug]` (modules should work from `/sw/ums/summit/ompix/…` trees) that would resolve the issue.

as a side note: use openmpi w/ `prrte/prun`, use spectrum-mpi w/ `jsrun`

(*) Big thanks to Thomas Naughton for help!

**Comment by andre-merzky** [comment]
@lee212 : to ping ORNL again

**Comment by andre-merzky** [comment]
resolved for now.

**Comment by benjha** [comment]
Ok guys, so after Summit upgrades there is no new openmpi yet on

`/sw/summit/ums/ompix/`

files/directories creation dates are recent thus looks like updating was started

**Comment by naughtont3** [comment]
@benjha I'll rebuild openmpi under `/sw/summit/ums/ompix/` and let you know when ready to test.
