### ISSUE TITLE
Error running DDMD on Bridges2

### ISSUE THREAD

**Issue by nsanjrani** [radical-cybertools/radical.pilot#2403]
I'm trying to run a simple DDMD example on Bridges2 but I encounter an error I'm not sure about. I have attached the task.0000.err file which explains the error and also the task.0000.sh file. I have also attached the radical.log file in case it helps. Please let me know if I need to attach anything else.

[Bridges2_errors.zip](https://github.com/radical-cybertools/radical.pilot/files/6685158/Bridges2_errors.zip)

**Comment by andre-merzky** [comment]
The resource config for bridges2 contains:
```
        "pre_bootstrap_0"             : ["module reset",
                                         "module load gcc",
                                         "module load openmpi/3.1.6-gcc8.3.1",
                                         "module load anaconda3"
                                        ],
```
so we explicitly load `openmpi` and form the `mpirun` command line accordingly: the options specified are expected to work for `mpirun` from OpenMPI  which does accept `-x`  However, the `mpirun` which gets **_used_** is from MPICH and based on Hydra (which does not know `-x`), .  It looks like the pre-exec commands switch the mpi version under our feet?

If you don't mind, please add an `module list` command as last entry in the task's `pre-exec`.  You should find the output, even for failing tasks, in `task.000000.out` - could you please paste it here?  

If this turns out to be the problem we have two options: change your `pre-exec` commands so that they don't switch MPI libraries, or changing the resource config so that `mpich` is being used.  I assume though that you application is linked against mpich, is that correct?

**Comment by nsanjrani** [comment]
I'm not entirely sure if it uses `mpich` but in the config file for DDMD it ensures the prerequisite is MPI for processes and OpenMP for threads. When I add the module list command it doesn't write anything to `task.0000.out` but it does add a line to the `task.0000.err` file which I've attached.

[task.0000.err.txt](https://github.com/radical-cybertools/radical.pilot/files/6685608/task.0000.err.txt)

**Comment by andre-merzky** [comment]
> 'm not entirely sure if it uses `mpich` but in the config file for DDMD it ensures the prerequisite is MPI for processes and OpenMP for threads. When I add the module list command it doesn't write anything to `task.0000.out` but it does add a line to the `task.0000.err` file which I've attached.

Ah, right - the `module` command, for whatever reason, seems to always write to `stderr`...  Thanks!

> [task.0000.err.txt](https://github.com/radical-cybertools/radical.pilot/files/6685608/task.0000.err.txt)

Well, now I am thoroughly confused: the `openmpi` module is still loaded, but the error clearly states:
```sh
[mpiexec@v011.ib.bridges2.psc.edu] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:91): unrecognized argument x
                                                                            ^^^^^^^^
```

and that indicates `mpich`.   WTH...

If you don't mind, can we iterate further: could you please also add a `which mpirun mpiexec` command, but please do so twice: once as first element in your `pre_exec` commands and once in last position.  Thank you!

**Comment by nsanjrani** [comment]
This time it wrote to the output file! Here it is:

[task.0000.out.txt](https://github.com/radical-cybertools/radical.pilot/files/6686055/task.0000.out.txt)

**Comment by andre-merzky** [comment]
And here we go:
```
1 /jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/openmpi-3.1.6-4mivpbjysgvfx23xkhssavhgkpgpnrug/bin/mpirun
2 /jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/openmpi-3.1.6-4mivpbjysgvfx23xkhssavhgkpgpnrug/bin/mpiexec
3 /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun
4 /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/
```
(I added line numbers)

The first two lines is what we expect, and before the `pre_exec` all is well.  Line 3 and 4 point to a different MPI now, so the module commands in the `pre_exec` seem to change that, even though the `openmpi` module remains loaded.

At this point I am not sure what the best course of action is.  There are two considerations:

(a) the module setup on Bridges2 is broken: intel MPI (MPICH) should not kick in when the `openmpi` module is still loaded.  This needs to be taken up by the sys admins.

(b) we can change the resource config to use the intel MPI - but please do check if your application code works with that.

@lee212 : Hyungro, can you please take over?  Can you clarify what DDMD needs, and adjust the resource config accordingly?

**Comment by lee212** [comment]
Oh I see, Intel MPI is loaded by `module load hdf5` like:
```
 module load openmpi/3.1.6-gcc8.3.1
[hrlee@bridges2-login013 experiment]$ which mpirun
/jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/openmpi-3.1.6-4mivpbjysgvfx23xkhssavhgkpgpnrug/bin/mpirun
[hrlee@bridges2-login013 experiment]$ module load hdf5
[hrlee@bridges2-login013 experiment]$ which mpirun
/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun
```

@nsanjrani , could you add a line of `module load openmpi/3.1.6-gcc8.3.1` followed by `module load hdf5` in your yaml file? I find four lines will be added in total. This might work, if not, we can try again by removing hdf5 as it can be loaded by conda env.

**Comment by nsanjrani** [comment]
Thank you @lee212 and @andre-merzky, it doesn't seem to be throwing that error now :)

**Comment by andre-merzky** [comment]
Great!  I am closing this issue then - please reopen if the same problem pops up again, or open a new one if you get stuck further down the road...
