### ISSUE TITLE
ORTE daemon failure

### ISSUE THREAD

**Issue by nsanjrani** [radical-cybertools/radical.pilot#2417]
When running DDMD on Bridges2, as identified by @lee212, `mpirun` fails on one of the hosts (`v026`) with the ORTE deamon failure error message. This means some of the MD tasks run but some of them fail and so DDMD can't continue to the next stages. I have attached a zipped folder containing a `radical.log` file and `task.0000.err` to show which error is coming up. A tar file of all the tasks in the first MD stage is also available to view on `/tmp` called `md_tasks.tar.gz` under the hostname `br014.ib.bridges2.psc.edu`.

[error.zip](https://github.com/radical-cybertools/radical.pilot/files/6758746/error.zip)

**Comment by andre-merzky** [comment]
Hi @nsanjrani - could you please attach the complete pilot sandbox, or provide access to it on Bridges?  There are several possible causes for this, and I would like to understand the full setup to narrow down the options.  Thanks, Andre.

**Comment by nsanjrani** [comment]
Sure! I've just put `radical.pilot.sandbox` on `/tmp`.

**Comment by andre-merzky** [comment]
Hi @nsanjrani - Bridges seems seems to have troubles, it goes up and down, and I did not yet manage to have a look at your files (right now, the home FS is not mounted...).  I suspect the files in `/tmp/` will also be gone, they usually get purged on reboot.  If you happen to have a tarball of the session trees, please attach them to the ticket.

**Comment by nsanjrani** [comment]
No worries! Luckily for us, the files are still there so I've zipped them for when you have time to have a look: [re.session.br014.ib.bridges2.psc.edu.sanjrani.018811.0010.zip](https://github.com/radical-cybertools/radical.pilot/files/6791600/re.session.br014.ib.bridges2.psc.edu.sanjrani.018811.0010.zip)

**Comment by andre-merzky** [comment]
Oh, it seems the error is simpler than I expected: you ran out of disk quota!
```sh
  File "/jet/home/sanjrani/anaconda3/envs/conda-entk/lib/python3.7/site-packages/simtk/openmm/app/statedatareporter.py", line 203, in report
    self._out.flush()
OSError: [Errno 122] Disk quota exceeded
```
The pilot job itself also failed because some logfiles could not be written, also because of quota limits.  I am afraid you will have to either clean out some old data to make space, or to request increased quota limits from the admins.  You should be able to see your current limits and the used space with the `quota` command.

**Comment by nsanjrani** [comment]
Ah I see, thanks a lot!!!

**Comment by andre-merzky** [comment]
Woulc you mind attaching a tarball of the pilot sandbox again?  Thank you!

**Comment by nsanjrani** [comment]
Yes sure! 
[re.session.br014.ib.bridges2.psc.edu.sanjrani.018821.0001.zip](https://github.com/radical-cybertools/radical.pilot/files/6809286/re.session.br014.ib.bridges2.psc.edu.sanjrani.018821.0001.zip)

**Comment by andre-merzky** [comment]
Hi @nsanjrani - if you check the task STDERR files, you will see something like this (shortened):
```
$ cat task.0163.err 

[...]
    data = self.agent_stage.read_task_json(stage_idx, task_idx)
  File "/jet/home/sanjrani/anaconda3/envs/conda-entk/lib/python3.7/site-packages/deepdrivemd/data/api.py", line 121, in read_task_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/jet/home/sanjrani/protlig_sim_5/agent_runs/stage0001/task0000/stage0001_task0000.json'
```

I can think of two reasons for this: either the expected input data are not present at that location in the file system, or that file system (`/jet/home/`) is not available on the compute nodes where the tasks are executing.   The [bridges documentation](https://www.psc.edu/resources/bridges-2/user-guide-2/) states
```
File Systems

The $HOME (/jet/home) and Ocean file systems are available on all of these nodes.  See the File Spaces section of this User Guide for more information on these file systems.
```

So I assume the latter is not the problem.  I am not sure how data in DDMD are supposed to be provisioned, i.e.,  if they should be provided by the user or by the client side of the application.

@lee212 : Hyungro, could you help to clarify please?

**Comment by andre-merzky** [comment]
PS.: please note that some tasks fail with a different error, for example:
```
$ cat task.0017/task.0017.err

The following have been reloaded with a version change:
  1) anaconda3/2020.11 => anaconda3/2020.07

Traceback (most recent call last):
  File "/jet/home/sanjrani/DeepDriveMD-pipeline/deepdrivemd/selection/latest/select_model.py", line 147, in <module>
    latest_model_checkpoint(cfg)
  File "/jet/home/sanjrani/DeepDriveMD-pipeline/deepdrivemd/selection/latest/select_model.py", line 115, in latest_model_checkpoint
    api, cfg.checkpoint_dir, cfg.checkpoint_suffix
  File "/jet/home/sanjrani/DeepDriveMD-pipeline/deepdrivemd/selection/latest/select_model.py", line 94, in latest_checkpoint
    return max(checkpoint_files, key=lambda x: int(x.name.split("-")[1]))
ValueError: max() arg is an empty sequence
```

**Comment by nsanjrani** [comment]
@lee212 can correct me if I'm wrong but I think these errors arise when previous tasks aren't completed as the next stages rely on them. So in the first instance the file is not found because it never ran due to the deamon failure error and the second error also doesn't work because it's looking for previous checkpoint files from the MD stage?

**Comment by andre-merzky** [comment]
Hmm, I would think that DDMD should not submit new tasks if previous dependent ones fail.  But am not very familiar with the DDMD code, sorry :-/

**Comment by lee212** [comment]
When I checked the file `re.session.br014.ib.bridges2.psc.edu.sanjrani.018821.0001.zip`, there are failed tasks with this error message:
```
--------------------------------------------------------------------------
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
```
And the hostname, `v014` is observed as well. The executable starts like `mpirun  ...  -host v014`, then I find this error message in the `.err`. The exit code is not stored in a file but EnTK prints out (e.g., `nohup.out`) which task is failed with task names and ids.

If there is a physical system failure at Bridges e.g., the host `v014` is not accessible then the report might have to go PSC ticket system first, `help@psc.edu`, as there is no programmatic exclusion of specific hosts.

The version of DDMD here is file-based, and most tasks are silently executed for example, `run_openmm.py` produces zero output message when it is finished successfully but outputs and logs are stored in the dedicated location e.g., `/jet/home/sanjrani/protlig_sim_5/molecular_dynamics_runs/stage0000/task0000`. And there is a procedural dependency, not data dependency in DDMD, which will create failures in the subsequent tasks.

**Comment by andre-merzky** [comment]
@lee212 : what is the recommended action in your opinion?  Just running again?

**Comment by lee212** [comment]
It would be nice if a certain host can be excluded when it's identified as not responsible.

**Comment by andre-merzky** [comment]
Close in favor of #2618
