### ISSUE TITLE
Question: dealing with jsrun Error: error in ptssup_mkcltsock_afunix() 

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2419]
I have EnTK code running the iterative pipeline, in specific, utilizing 100 Summit nodes, 100 pipelines for 16 iterations with 8 stages each, 12,800 tasks in total. My problem is that jsrun starts to fail at a certain time when a job makes progress like 2/3 tasks completed.

I see the jsrun failure like:
```
$ more unit.008773/unit.008773.err
Error: error in ptssup_mkcltsock_afunix()
07-07-2021 19:38:56:375 60873 main: Error initializing RM connection. Exiting.
```
(Ignore unit directory name in this example, as I captured this from the old stack 1.5.1 but the latest stack encounters a similar problem)

I recently saw this error, which seems odd because I was able to run larger runs than this e.g. 200 and 400 node runs.
If this is a system-related intermittent issue, I wonder if there is a workaround or a tip that I can benefit from.

**Comment by mtitov** [comment]
@lee212 is it related to what you reported earlier [here](https://github.com/radical-cybertools/radical.pilot/issues/2150#issuecomment-856952727)?

**Comment by lee212** [comment]
I think you're right, I find it is not using `cpu_index_using: logical`
