### ISSUE TITLE
create unit test that validates that all states are triggered by callbacks

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#242]

**Comment by andre-merzky** [comment]
There is now code in place which ensures that callbacks are triggered for all states.

**Comment by marksantcroos** [comment]
Isnt the sole purpose of a test to verify that the code works? :)

**Comment by andre-merzky** [comment]
Yes.  But the ticket was in response to an actual issue, and that is gone.  I agree on the test coverage -- but I don't think we should open tickets for all elements which need test coverage, because that is endless, kind off... :/

**Comment by marksantcroos** [comment]
Ok!
