### ISSUE TITLE
Logic error in TaskManager.unregister_callback for metrics=None

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2444]
At
https://github.com/radical-cybertools/radical.pilot/blob/68f455bae19fa6479a25f1113093d3b49938384b/src/radical/pilot/task_manager.py#L1201
the default value for `metrics` becomes `[['TASK_STATE', 'WAIT_QUEUE_SIZE']]`.

I believe that `['TASK_STATE', 'WAIT_QUEUE_SIZE']` is what is intended. E.g.

    if not metrics: metrics = rpc.TMGR_METRICS

To reduce future errors, maybe remove the `else` from the following line, as well.

**Comment by eirrgang** [comment]
Actually, I'm not sure that is an appropriate default, either, since the function seems to assume that the task uid is present for each of the metrics, when the default for Task.register_callback is just to use rp.constants.TASK_STATE, which would raise a ValueError at https://github.com/radical-cybertools/radical.pilot/blob/68f455bae19fa6479a25f1113093d3b49938384b/src/radical/pilot/task_manager.py#L1221

There also seems to be a bug at https://github.com/radical-cybertools/radical.pilot/blob/68f455bae19fa6479a25f1113093d3b49938384b/src/radical/pilot/task_manager.py#L1234 where the 'uid' and 'metric' keys are reversed.

**Comment by andre-merzky** [comment]
Hi @eirrgang - sorry for responding so late to the ticket!  #2501 should address most issues - thanks for catching them!  

I am not sure I understand this one though:

> Actually, I'm not sure that is an appropriate default, either, since the function seems to assume that the task uid is present for each of the metrics, when the default for Task.register_callback is just to use rp.constants.TASK_STATE, which would raise a ValueError at [radical.pilot/src/radical/pilot/task_manager.py](https://github.com/radical-cybertools/radical.pilot/blob/68f455bae19fa6479a25f1113093d3b49938384b/src/radical/pilot/task_manager.py#L1221)
>  ` if metric not in self._callbacks:`

the `TASK_STATE` is listed in `self._callbacks` if the default value of `rpc.TMGR_METRICS` is used, and also when the `rpc.TASK_STATE` metric is used on the `tmgr.register_callback` default is used.  What am I missing?

**Comment by eirrgang** [comment]
> Hi @eirrgang - sorry for responding so late to the ticket! #2501 should address most issues - thanks for catching them!
> 
> I am not sure I understand this one though:
> 
> > Actually, I'm not sure that is an appropriate default, either, since the function seems to assume that the task uid is present for each of the metrics, when the default for Task.register_callback is just to use rp.constants.TASK_STATE, which would raise a ValueError at [radical.pilot/src/radical/pilot/task_manager.py](https://github.com/radical-cybertools/radical.pilot/blob/68f455bae19fa6479a25f1113093d3b49938384b/src/radical/pilot/task_manager.py#L1221)
> > ` if metric not in self._callbacks:`
> 
> the `TASK_STATE` is listed in `self._callbacks` if the default value of `rpc.TMGR_METRICS` is used, and also when the `rpc.TASK_STATE` metric is used on the `tmgr.register_callback` default is used. What am I missing?

If `register_callback` is called without specifying a metric, the callback will be registered for `TASK_STATE`. If the user then calls `unregister_callback` with the symmetric signature (default *metric*), the function will try to unregister for  `metric = ['TASK_STATE', 'WAIT_QUEUE_SIZE']`.

Won't that cause an inappropriate `ValueError`?
