### ISSUE TITLE
support client side MongoDB tunnel

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2445]
The local tunnel URL needs to  be converted to a public MongoDB URL before being passed to the agent (which may set up its own tunnel).

**Comment by eirrgang** [comment]
The client might be accessing MongoDB through some sort of port forwarding, either through an ssh tunnel or a virtualization tool, like `docker compose`.

A workaround could be to allow the client to use the RADICAL_DB_URL from the environment, but to let a field in the `resource_X.json` file override the client-provided value for a particular resource.
