### ISSUE TITLE
Docstring syntax should not exceed PEP-287 spec.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2447]
Current RP docstrings use Sphinx-specific syntax that look like RST comments. Docstrings are generally assumed to be processable by docutils, but not necessarily by Sphinx. Sphinx-specific RST extensions (like `.. py:class::`) can look like comments to docutils based tools and get quietly ignored when documentation is accessed interactively, such as through a web-based tool or an IDE.

(See also https://www.python.org/dev/peps/pep-0287/ for the suggested scope of RST syntax and conventions in docstrings.)

Conversely, Google and Numpy style docstrings are readable with or without additional processing, and are easily processed by [`sphinxcontrib.napoleon`](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) when generating web documentation with Sphinx.

## Proposal

1. Choose either [Numpy or Google](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/#google-vs-numpy) docstring style for RP docstrings. (State in the style guide section of the docs.)
2. Over time, migrate docstrings to the selected style.

**Comment by eirrgang** [comment]
I would be happy to contribute docstring update PRs if RP adopts either Numpy or Google docstring style.

**Comment by eirrgang** [comment]
@andre-merzky expressed a preference for narrowing docstring width at the expense of docstring length, indicating Numpy style would be a better match than Google style.

**Comment by eirrgang** [comment]
The new docstrings used for `autofunc` in #2696 are in Google style, but don't get processed as cleanly as we might prefer without [sphinxcontrib.napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/).

I can volunteer to submit a PR to start using `napoleon`, but it would help if a decision could be made about whether to embrace Numpy or Google docstring style so that I could fix the formatting of currently non-conformant docstrings to get them to typeset properly.

**Comment by eirrgang** [comment]
> @andre-merzky expressed a preference for narrowing docstring width at the expense of docstring length, indicating Numpy style would be a better match than Google style.

@mturilli indicated a preference for Google style in #2905. Can I get a final ruling/confirmation?

Also, should I branch from `devel` or some other work-in-progress?

**Comment by mturilli** [comment]
@eirrgang , we discussed it internally and the final/ruling confirmation is: Google style. Let's branch from devel and thank you!
