### ISSUE TITLE
Supporting spock at ORNL

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2450]
This is high priority for CANDLE and Exaworks.
- @lee212 , @mtitov , @andre-merzky, @darkwhite29 , @vrpascuzzi will have to gain access to the machine as soon as available. I will keep this ticket update with the relevant info.

**Comment by andre-merzky** [comment]
Thanks @mturilli.  Do we have any information about how to apply for access?  I could not find anything on the OLCF pages unfortunately...

**Comment by mtitov** [comment]
Spock configuration is updated ([4890d19](https://github.com/radical-cybertools/radical.pilot/pull/2664/commits/4890d196a230bafc03d1e928edf49939acc957bb))

**Comment by andre-merzky** [comment]
Spock is supported now - otherwise #2620 is discussing further steps.
