### ISSUE TITLE
Removing XSEDE Comet support from RCT!

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2468]
XSEDE Comet retired this July and is no longer operating! It is recommended to remove any old machine that is no longer exists from RCT configurations. 

I will clean up the config files and create a pull request regarding this matter.

If you know any machine that is no longer exists and still in our RCT configurations, please report it here so it can be cleaned up.

**Comment by andre-merzky** [comment]
Thanks @AymenFJA - its much appreciated that you clean them up!

**Comment by mtitov** [comment]
- `xsede.bridges_mpiexec`
- `osg.*` (?)

@andre-merzky `resource_osg` is obsolete, isn't it?

**Comment by andre-merzky** [comment]
Yes, OSG is obsolete I'm afraid.

**Comment by AymenFJA** [comment]
Solved in the mentioned PR above.
