### ISSUE TITLE
Confirm file existence before data staging in

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2483]
Should RP ensure that files (and directories) exist before trying to stage them?
(*) with focus on staging for `pilot` and not for `task`

example of logging record about failed file
```
1642537009.288 : pmgr_launching.0000  : 29972 : 140520324400896 : DEBUG    : err: tar: pilot.0000/ascent_actions.yaml: File removed before we read it
```

**Comment by kartikmodi** [comment]
@mtitov Can you list the steps to reproduce this?

**Comment by kartikmodi** [comment]
@mtitov .
