### ISSUE TITLE
srun should use nodelist instead of nodefile

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2488]
up to a certain number of nodes

**Comment by AymenFJA** [comment]
Few things to highlights and consider:

1. `srun` should use by default `--nodelist` and not `--nodefile` for 2 reasons:

    -  SLURM versions <=18 do not support the option `--nodfile`. (Example SLURM on Amarel)
    -  Using `--nodefile` will leads to creating a file with node names in it, leading to I/O operation that can be expensive, if not needed.

2. Switching to `--nodefile` should happen in one scenario: requesting a certain number of nodes (beyond x numbers) that leads to exceeding the allowed number of characters in a single shell file? 

3. A corner case that I have no clue of how to proceed with if happened, we have a SLURM version that does not support `--nodefile` and the user requested a large number of nodes that exceed the number of allowed characters. This will leads to a certain failure based on what we mentioned earlier in 1 and 2.

**Comment by AymenFJA** [comment]
Update regarding the ticket from yesterday's development meeting: 

1.  The separator between the `--nodelist` and `--nodefile` is the number of nodes. Assuming that SLURM supports the `--nodefile`.
2. If the number of nodes is >42 nodes (that is what we agreed on based on Andre's advice) then we switch to `--nodefile`.
3. 
    ```
    If SLURM_version <=18 & nodes >42:
         set task to fail.
         exit
    ```
Based on these comments, we will add the mentioned cases to the `srun` launcher code.

**Comment by AymenFJA** [comment]
fixed and PR merged.
