### ISSUE TITLE
Missing radical-pilot-resources script in virtual environment's bin path

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2490]
The script  _radical-pilot-resources_ is expected to be in /bin of virtual env's.

Example here - 
https://radicalpilot.readthedocs.io/en/stable/user_guide/00_getting_started.html#executing-the-example

The script is not in the bin because it's missed in setup.py's scripts argument along with _radical-pilot-ve_ and _radical-pilot-limits.py_
I am not sure if _plot_profile.ipynb_ should also be in scripts list, since it's present in bin directory of source code but not in setup scripts list.

Lastly, _radical-pilot-fetch-logfiles_ is listed twice in the list.

**Comment by andre-merzky** [comment]
`plot_profile.ipynb` should probably be moved into the documentation and should be executed as part of the doc build pipeline.  @mturilli , would you agree?
