### ISSUE TITLE
`bootstrapper_0` fails to test existing conda env

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2492]
```shell
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

This might be related to #2489. The bootstrapper is failing to continue when calling `radical-utils-env.sh` https://github.com/radical-cybertools/radical.pilot/blob/5564775c076130bd25bdd3afd586dc8f5c41dbc7/src/radical/pilot/agent/bootstrap_0.sh#L154 to determine old/new `conda` installation.  This leads the entire RP-agent side to hang and unable to continue. 

RADICAL-Stack
```shell

  python               : /home/aymen/ve/raptor/bin/python3
  pythonpath           :
  version              : 3.7.6
  virtualenv           : /home/aymen/ve/raptor

  radical.gtod         : 1.6.7
  radical.pilot        : 1.11.2-v1.11.2-78-gc088983@feature-parsl_raptor_executor
  radical.saga         : 1.11.1
  radical.utils        : 1.11.0-v1.11.0-1-g7c9997f@hotfix-env_write
```

**Comment by mtitov** [comment]
@AymenFJA can you please put here packages description from the config
```
# e.g.
        "python_dist"                 : "default",
        "virtenv_dist"                : "default",
        "virtenv_mode"                : "local",
        "rp_version"                  : "installed",
```

**Comment by AymenFJA** [comment]
hey @mtitov here:
` ``json
        "rp_version"                  : "local",
      # "virtenv_mode"                : "local",
        "virtenv_mode"                : "create",
        "python_dist"                 : "anaconda",
```

**Comment by mtitov** [comment]
@AymenFJA can you please make a test with the following RU PR [#328](https://github.com/radical-cybertools/radical.utils/pull/328)
Looks like the issue comes from here https://github.com/radical-cybertools/radical.pilot/blob/5564775c076130bd25bdd3afd586dc8f5c41dbc7/src/radical/pilot/agent/bootstrap_0.sh#L17

**Comment by AymenFJA** [comment]
This issue is resolved with the `328 (merged)` PR. Closing for now. Thanks.
