### ISSUE TITLE
insufficient error message on missing mpiexec/mpirun

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2497]
Adding a more appropriate message for debugging or suggesting what could be a problem | Giving hints for mpi library not installed:

When running RP, it got a error in agent side i.e. logs in ~/radical.pilot.sandbox/rp.session.debian-x.workstation.019029.0011/pilot.0000.
The error log is -> 

```
1644114328.003 : agent.0              : 1583846 : 140617269974848 : DEBUG    : prepare lm MPIEXEC
1644114328.005 : agent.0              : 1583846 : 140617269974848 : ERROR    : unusable lm MPIEXEC
Traceback (most recent call last):
  File "/home/workstation/radical.pilot.sandbox/rp.session.debian-x.workstation.019029.0011/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/launch_method/base.py", line 145, in create
    return impl[name](name, lm_cfg, rm_info, log, prof)
  File "/home/workstation/radical.pilot.sandbox/rp.session.debian-x.workstation.019029.0011/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/launch_method/mpiexec.py", line 25, in __init__
    LaunchMethod.__init__(self, name, lm_cfg, rm_info, log, prof)
  File "/home/workstation/radical.pilot.sandbox/rp.session.debian-x.workstation.019029.0011/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/launch_method/base.py", line 82, in __init__
    lm_info = self._init_from_scratch(env_lm, env_sh)
  File "/home/workstation/radical.pilot.sandbox/rp.session.debian-x.workstation.019029.0011/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/launch_method/mpiexec.py", line 71, in _init_from_scratch
    mpi_version, mpi_flavor = self._get_mpi_info(lm_info['command'])
  File "/home/workstation/radical.pilot.sandbox/rp.session.debian-x.workstation.019029.0011/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/launch_method/base.py", line 253, in _get_mpi_info
    raise ValueError('no executable found')
ValueError: no executable found
1644114328.005 : agent.0              : 1583846 : 140617269974848 : ERROR    : skip LM MPIEXEC
.....<REPEAT>
```
The Exception says an executable is missing but doesn't clarify what executable is missing. 

Can we put a log message before raising an exception giving a hint, that "Your system might be missing an MPI dependency? Are you sure you have a mpi library installed and it is on the path? "

I do understand this is not an elegant way to deal with these things, maybe a initial dependency check might be better. 

Moreover,  I think I should add some information to the documentation in the Requirements section. 
https://radicalpilot.readthedocs.io/en/stable/installation.html#requirements

Lastly, should I add anything to this page in above context - 
https://radicalpilot.readthedocs.io/en/stable/faq.html

**Comment by andre-merzky** [comment]
> I do understand this is not an elegant way to deal with these things, maybe a initial dependency check might be better.

is maybe not as useful.  For one, `mpirun` is optional and the error only pops up when MPI applications are executed.  Only one of the example scripts does that (`09_mpi_tasks.py`).  It's probably worthwhile to add a note there?

In general, the target resources for RP are clusters where MPI is always available.

> Moreover, I think I should add some information to the documentation in the Requirements section.
> https://radicalpilot.readthedocs.io/en/stable/installation.html#requirements

FAQ makes sense, and also adding a note about *optional* MPI in the requirements section.
We should also make sure the exception message lists what executable was missing.

Do you want to create PR's for the documentation parts above?  I'm happy to fix the error message.

**Comment by kartikmodi** [comment]
@andre-merzky 
Yes, I would want to create PR for documentation specifying a "section with optional dependencies", so keeping this issue open until I create one.

However, since you have now created a PR #2500 which fixes the issues, the exception above would never occur (at least for mpiexec / mpirun). Do you still think adding the reported exception stack trace with a solution to [FAQ](https://radicalpilot.readthedocs.io/en/devel/faq.html#pop-up-do-you-want-the-application-python-to-accept-incoming-network-connections-on-macos) makes sense? If yes, any specific details I should add?
