### ISSUE TITLE
Radical stack fails while attempting to run on PSC Bridges 2

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#2505]
Hey folks

Trying to run, say, an RP example or an EnTK example on Bridges 2 fails. The terminal message is unhelpful:

```
Traceback (most recent call last):
  File "/home/scm177/Virtual_Envs/pace_env/lib/python3.6/site-packages/radical/entk/appman/appmanager.py", line 438, in run
    self._rmgr.submit_resource_request()
  File "/home/scm177/Virtual_Envs/pace_env/lib/python3.6/site-packages/radical/entk/execman/rp/resource_manager.py", line 199, in submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/home/scm177/Virtual_Envs/pace_env/lib/python3.6/site-packages/radical/pilot/pilot.py", line 558, in wait
    time.sleep(0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scm177/Virtual_Envs/pace_env/bin/pace.py", line 92, in <module>
    main()
  File "/home/scm177/Virtual_Envs/pace_env/bin/pace.py", line 88, in main
    candidate_manager.run()
  File "/home/scm177/Virtual_Envs/pace_env/bin/candidate_manager.py", line 29, in run
    self.app_manager.run()
  File "/home/scm177/Virtual_Envs/pace_env/lib/python3.6/site-packages/radical/entk/appman/appmanager.py", line 463, in run
    raise ree.EnTKError(ex) from ex
radical.entk.exceptions.EnTKError
```
There are no logs generated on the agent side, . [Clientside logs are here.](https://github.com/radical-cybertools/radical.pilot/files/8021063/logs_main.tar.gz)

While digging into the remote sandbox, I found `bootstrap_0.out` to contain the following:

```
# -------------------------------------------------------------------
bootstrap_0 running on host: r166.ib.bridges2.psc.edu.
bootstrap_0 started as     : './bootstrap_0.sh -d radical.utils-1.6.7.tar.gz:radical.saga-1.6.7-v1.6.7-10-g5e0a50b-fix-staging.tar.gz:radical.pilot-1.6.7.tar.gz -p pilot.0000 -s re.s\
ession.McEwan.scm177.019031.0001 -m create -r local -b anaconda -g default -v /ocean/projects/dmr170002p/mushnoor/radical.pilot.sandbox/ve.xsede.bridges2.1.6.7 -y 30 -z re.session.Mc\
Ewan.scm177.019031.0001.pmgr_launching.0000.tgz -e module reset -e module load gcc -e module load openmpi/3.1.6-gcc8.3.1 -e module load anaconda3'
safe environment of bootstrap_0
bootstrap_0 stderr redirected to stdout

# -------------------------------------------------------------------
#
# Running pre_bootstrap_0 command
# cmd: module reset
#
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules

#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
#ABORT
```

Tagging @drawadiagram and @akashban on this as well. 

Thanks!

**Comment by shantenujha** [comment]
@SrinivasMushnoori @AymenFJA @andre-merzky  

Just a quick check that @SrinivasMushnoori and team are functional and working on Bridges?

**Comment by AymenFJA** [comment]
Hey, @SrinivasMushnoori any updates?

**Comment by SrinivasMushnoori** [comment]
My apologies for missing this: it does seem to work in part: I am able to get onto the resource past the previous error reported. However, it still does not successfully launch the pilot: no logs on the agent side, but the `bootstrap_0.out` file has the following:
`reset final state to FAILED
# -------------------------------------------------------------------
# push final pilot state: re.session.McEwan.scm177.019053.0000 pilot.0000 FAILED
dburl   : mongodb://scm177:hnt3FWVZrADRuC8g@95.217.193.116:27017/repex_3
tunnel  : None
session : re.session.McEwan.scm177.019053.0000
pilot   : pilot.0000
state   : pilot.0000
Traceback (most recent call last):
  File "/ocean/projects/dmr170002p/mushnoor/radical.pilot.sandbox/re.session.McEwan.scm177.019053.0000/pilot.0000/rp_install/bin/radical-pilot-agent-statepush", line 67, in <module>
    mongo, db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/ocean/projects/dmr170002p/mushnoor/radical.pilot.sandbox/re.session.McEwan.scm177.019053.0000/pilot.0000/rp_install/lib/python3.8/site-packages/radical/utils/misc.py", line \
135, in mongodb_connect
    db.authenticate(user, pwd)
  File "/ocean/projects/dmr170002p/mushnoor/radical.pilot.sandbox/ve.xsede.bridges2.1.10.0/lib/python3.8/site-packages/pymongo/collection.py", line 2579, in __call__
    raise TypeError("'Collection' object is not callable. If you "
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.

# -------------------------------------------------------------------
#
# Done, exiting (0)
#
# -------------------------------------------------------------------
`

This is not something I have seen before, but it looks like installing the virtualenv is failing?

**Comment by AymenFJA** [comment]
@SrinivasMushnoori , can you please share your `radical-stack`? also, what is your `pymongo` version, you can check this by executing this command in the python interpreter:  
```python
import pymongo
pymongo.__version__
```

**Comment by SrinivasMushnoori** [comment]
```
(pace_env) scm177@McEwan:~/RCT/pace/examples/gromacs_example$ python
Python 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymongo
>>> pymongo.__version__
'3.12.0'
>>> exit()
(pace_env) scm177@McEwan:~/RCT/pace/examples/gromacs_example$ radical-stack
WARNING: You are using radical.entk version 1.6.7, however version 1.9.0 is available.

  python               : /home/scm177/Virtual_Envs/pace_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/pace_env

  radical.entk         : 1.6.7
  radical.gtod         : 1.6.7
  radical.pilot        : 1.10.0-v1.10.0@master
  radical.saga         : 1.6.7-v1.6.7-10-g5e0a50b@fix-staging
  radical.utils        : 1.6.7
```

**Comment by AymenFJA** [comment]
@SrinivasMushnoori , It seems like your `agent` side ve: (`ve.xsede.bridges2.1.10.0`) has the `pymongo >4` which can create the issue above. Based on that can you please:
1. upgrade your entire `radical-stack` as this issue was addressed in the most recent `radical-stack`.
2. can you remove `ve.xsede.bridges2.1.10.0` from the sandbox and run again.

**Comment by SrinivasMushnoori** [comment]
Done. Updated to the following stack:
```
(pace_env) scm177@McEwan:~/RCT/pace/examples/gromacs_example$ radical-stack

  python               : /home/scm177/Virtual_Envs/pace_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/pace_env

  radical.entk         : 1.12.0
  radical.gtod         : 1.6.7
  radical.pilot        : 1.12.0
  radical.saga         : 1.12.0
  radical.utils        : 1.12.0
```

I deleted the VE as well.

Job still does not run. On the agent sandbox, I do not see a new VE being created. As before, no logs on the agent side. `bootstrap_0.out` has the following contents:
```
safe environment of bootstrap_0
grep: env.orig: No such file or directory
grep: env.orig: No such file or directory
grep: env.orig: No such file or directory
bootstrap_0 stderr redirected to stdout

# -------------------------------------------------------------------
#
# Running pre_bootstrap_0 command
# cmd: module reset
#
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules

#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
#ABORT
```

**Comment by AymenFJA** [comment]
@SrinivasMushnoori  install from `radical.pilot/devel` for now or remove `module reset` as advised earlier. The fix has not made it to the release yet, please.

**Comment by SrinivasMushnoori** [comment]
AH. I see. Attempting. I eyeballed the bootstrap outfile but somehow missed that. Trying.

**Comment by AymenFJA** [comment]
Closing this for no response. Will open if needed.
