### ISSUE TITLE
Remove task log and the state_history from documentation

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2508]
Quoting from https://radicalpilot.readthedocs.io/en/devel/user_guide/02_failing_tasks.html#handle-failing-tasks
`...array of timed log messages, similar to the state_history array discussed before.`

But, the state_history is discussed before. The link on `before` points to the previous document ->
https://radicalpilot.readthedocs.io/en/devel/user_guide/01_task_details.html#chapter-user-guide-01
which doesn't mention state_history anywhere. 

Are we talking of task doc from  _get_session_docs_  which has a state_history key? 
Is state_history recognized, such an important attribute that we need to describe it here on the 3rd page of documentation?

**Comment by andre-merzky** [comment]
Uh, good catch, this is indeed outdated.  We don't support task log and the `state_history` anymore as it proved to cause a severe performance penalty.  They should be removed from the documentation.  Would you mind taking care of it?
