### ISSUE TITLE
4.1 Simple Bag of Tasks

### ISSUE THREAD

**Issue by AninditaChavan** [radical-cybertools/radical.pilot#2530]
Example code simple_bot.py does not run.
**Error:**
<img width="941" alt="Screen Shot 2022-02-27 at 5 32 33 PM" src="https://user-images.githubusercontent.com/20729102/155902707-f2a3f195-71e8-434c-b098-4c201af19a5a.png">
  

**Fixed after commenting the following line of code:**
<img width="701" alt="Screen Shot 2022-02-27 at 5 35 09 PM" src="https://user-images.githubusercontent.com/20729102/155902881-1e205619-e3e9-4c3f-bc93-e804e71b990a.png">

**Output mentioned in the documentation:**
<img width="964" alt="Screen Shot 2022-02-27 at 5 39 20 PM" src="https://user-images.githubusercontent.com/20729102/155902910-c4884177-4365-44a6-b5e8-7720e3b39656.png">

**Actual Output:**

<img width="642" alt="Screen Shot 2022-02-27 at 5 40 21 PM" src="https://user-images.githubusercontent.com/20729102/155902947-c27b4ca9-0795-4311-b477-dae9ff0c53c8.png">

**Comment by andre-merzky** [comment]
Will be closed by #2559
