### ISSUE TITLE
Documenting steps to run NB, corrections to get up and running with NB, dependencies and build process

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2539]
**Objective**: To push all changes required, I had to do to run the NB documentation properly on my system. These changes include 
- corrections in notebooks, some things/features are incomplete, so temporarily commenting them as well is needed, to stop the build from failing. Will add #TODOs
- Documentation of how to set up notebooks, run on the system, build  the documentation
- A working state of the tutorial.ipynb 
- Environment variables handling
- setup.py changes for dependencies

I cannot explain well enough here, so the PR will explain most of the things. I'll try to put comments. 
Expecting a lot of comments/questions on the PR. 

All these changes will go to docs/nov21 branch only.

**Comment by andre-merzky** [comment]
Completed - thanks @kartikmodi !
