### ISSUE TITLE
Supporting WSL and WSL2 (Windows Linux Subsystem)

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2545]
WSL or WSL2 is a subsystem for Linux lets developers run a GNU/Linux environment -- including most command-line tools, utilities, and applications -- directly on Windows, unmodified, without the overhead of a traditional virtual machine or dual-boot setup.

Now, this is becoming increasingly popular to use. I tried to run the example `00_getting_started` and it stumbles on the error:
```python
database   : [mongodb://aymen:****@95.217.193.116:27017/radical3]Traceback (most recent call last):
  File "00_getting_started.py", line 35, in <module>
    session = rp.Session()
  File "/home/aymenalsaadi/ve/raptor/lib/python3.8/site-packages/radical/pilot/session.py", line 154, in __init__
    self._initialize_primary(dburl)
  File "/home/aymenalsaadi/ve/raptor/lib/python3.8/site-packages/radical/pilot/session.py", line 204, in _initialize_primary
    self._cmgr.start_bridges()
  File "/home/aymenalsaadi/ve/raptor/lib/python3.8/site-packages/radical/pilot/utils/component.py", line 206, in start_bridges
    raise RuntimeError('could not start all bridges %s' % failed)
RuntimeError: could not start all bridges ['cmgr.0000', 'log_pubsub', 'state_pubsub', 'control_pubsub', 'stager_request_queue', 'stager_response_pubsub']
```

Note that if I check the log files it shows that all the bridges did start successfully:
```python
cmgr.0000.hb.log:1647137665.735 : cmgr.0000.hb         : 1363  : 139905873086272 : INFO     : started bridge cmgr.0000.hb
control_pubsub.log:1647140454.603 : control_pubsub       : 2343  : 140194336474944 : INFO     : started bridge control_pubsub
log_pubsub.log:1647140454.133 : log_pubsub           : 2315  : 140470188771136 : INFO     : started bridge log_pubsub
state_pubsub.log:1647270292.739 : state_pubsub         : 16676 : 140381596092224 : INFO     : started bridge state_pubsub
stager_request_queue.log:1647140454.892 : stager_request_queue : 2357  : 139812211197760 : INFO     : started bridge stager_request_queue
stager_response_pubsub.log:1647140455.175 : stager_response_pubsub : 2371  : 140171538925376 : INFO     : started bridge stager_response_pubsub
```
`radical-stack`

```shell
  python               : /home/aymenalsaadi/ve/raptor/bin/python3
  pythonpath           :
  version              : 3.8.10
  virtualenv           : /home/aymenalsaadi/ve/raptor

  radical.gtod         : 1.6.7
  radical.pilot        : 1.12.0
  radical.saga         : 1.12.0
  radical.utils        : 1.12.0
```

I tried to debug the error and it seems that this line: https://github.com/radical-cybertools/radical.pilot/blob/f8f908ab7708a6095701ebd6e1f55072224c4edc/src/radical/pilot/utils/component.py#L203

 report one or all the bridges did not start, this shows that there is an inconsistency between the logs and the error.

Also, I have attached the stack tree and it does stumble on the `heartbeat_wait` (`left most lemon green colored boxes`)
![profile](https://user-images.githubusercontent.com/27039262/158200867-759b75bf-f922-4240-9672-8fc7f686c959.png)

Any ideas about this behavior? and happy to work on this.

**Comment by andre-merzky** [comment]
I am sorry, no idea what's up there.

**Comment by AymenFJA** [comment]
This will be closed now due to WSL bug, will open once there is an update.
