### ISSUE TITLE
RCT releases within `conda`

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2546]
Published releases:
- [RE](https://anaconda.org/conda-forge/radical.entk)
```
 linux-ppc64le  v1.6.5
 linux-64  v1.11.0
 osx-64  v1.11.0
```
- [RP](https://anaconda.org/conda-forge/radical.pilot): all latest releases are 1.11
- [RS](https://anaconda.org/conda-forge/radical.saga): all latest releases are 1.12
- [RU](https://anaconda.org/conda-forge/radical.utils)
```
 linux-ppc64le  v1.6.6
 linux-64  v1.12.0
 osx-64  v1.12.0
```

example of missing `linux_ppc64le` CI files for RU (comparing with RS)
RU: https://github.com/conda-forge/radical.utils-feedstock/tree/master/.ci_support
RS: https://github.com/conda-forge/radical.saga-feedstock/tree/master/.ci_support

**Comment by mtitov** [comment]
(*) this affects `conda install ...` only, installation using `pip` within `conda` environment works for all releases correctly

**Comment by andre-merzky** [comment]
RU seems to be up to date now - but not for Python 3.10, so the 3.10 runs for RP still fail: 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=478477&view=logs&j=c64f2b93-e1ef-5004-dedf-97174a8ceb90

@mtitov : any idea how we can add 3.10 to RU?

**Comment by mtitov** [comment]
Resolved!

For now we are not able to support Py 3.10 due to `pymongo` dependency ([link](https://anaconda.org/conda-forge/pymongo/)), which started to support 3.10 in version 4, which we do not support :/ (RCT requirement `pymongo <4`)
