### ISSUE TITLE
Feature Request: run in an interactive job

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2573]
The agent will always assume it's running with the local resource manager - but we should be able to configure other resource managers.  However, those will not see the batch system's environment - that would need to be communicated from client to agent.

See radical-collaboration/hpc-workflows/issues/154

**Comment by andre-merzky** [comment]
@AymenFJA : apply for ExaWorks alloc on Summit (PI: Dan Laney)

**Comment by mtitov** [comment]
Project: CSC449 ("2.3.5.10 ExaWorks")

**Comment by AymenFJA** [comment]
@mtitov thanks :).

**Comment by AymenFJA** [comment]
Currently, I am facing this problem: 
```shell
  radical.saga.log BadParameter: 'JobDescription.Project' (csc449) not supported by radical.saga.adaptors.shell_job

 radical.saga.pty.log (ERROR\nNOK - command 'PING' failed\n/ccs/home/aymen/.radical/saga/adaptors/shell_job/wrapper.sh: line 990: PING: command not found\n)
```

**Comment by AymenFJA** [comment]
> Currently, I am facing this problem:
> 
> ```shell
>   radical.saga.log BadParameter: 'JobDescription.Project' (csc449) not supported by radical.saga.adaptors.shell_job
> 
>  radical.saga.pty.log (ERROR\nNOK - command 'PING' failed\n/ccs/home/aymen/.radical/saga/adaptors/shell_job/wrapper.sh: line 990: PING: command not found\n)
> ```

Update: Based on Andre's advice (today's devel meeting) we decided to: 

1- The shell_adaptor does not support `PROJECT` attributes. So we need to find an environment variable that can expose `summit` project number to construct the pilot_sandbox path.
2- Create an individual resource_config `summit_interactive`.
3- for the `command 'PING' failed` delete `ccs/home/aymen/.radical`.

**Comment by AymenFJA** [comment]
Update:

1.  I couldn't find an environment variable that exposes the `Project number of summit`. In my understanding, we have to find a way to ask the user to provide it.

**Comment by andre-merzky** [comment]
Dammit.  Maybe we can run `bjobs` and grep for the job id (which we know).  There might be a more efficient command to get the job info?

**Comment by AymenFJA** [comment]
> Dammit.  Maybe we can run `bjobs` and grep for the job id (which we know).  There might be a more efficient command to get the job info?

@andre-merzky figured it out. `
(base) bash-4.4$ env | grep CS449
LSB_PROJECT_NAME=CS449 `

**Comment by AymenFJA** [comment]
This is working now under this PR: #2575
