### ISSUE TITLE
Enable RAPTOR to use anaconda environment upon pilot creation

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2585]
Based on our discussion with @andre-merzky this is possible and under progress.

Example, currently RAPTOR supports `virtualenv` like this:

```
pilot.prepare_env(env_name='ve_raptor',
                             env_spec={'type'   : 'virtualenv',
                                                  'version': '3.8',
                                                  'setup'  : ['mpi4py',
                                                              'radical.pilot',]})
```

Instead, we would like RAPTOR to create/use `anaconda` environment, example: 

```
pilot.prepare_env(env_name='anaconda_raptor',
                             env_spec={'type'   : 'anaconda',
                                                  'version': '3.8',
                                                  'setup'  : ['mpi4py',
                                                              'radical.pilot',]})
```

**Comment by AymenFJA** [comment]
I noticed that our code docstring shows something that we are currently not or are in progress to support:

In this line we show that we do support Conda environment on the pilot side: 
https://github.com/radical-cybertools/radical.pilot/blob/64253944063236c9850d5a8b35d2308bd5e78b31/src/radical/pilot/pilot.py#L608

On the agent side we do assert to make sure we are using only `virtualenv`:

 https://github.com/radical-cybertools/radical.pilot/blob/7b033bf49e2b80c0600657a5c429127471d683b2/src/radical/pilot/agent/agent_0.py#L808

In the meantime, `radical-pilot-create-static-ve` does support `CONDA` and `VIRTUALENV`:

https://github.com/radical-cybertools/radical.pilot/blob/64253944063236c9850d5a8b35d2308bd5e78b31/bin/radical-pilot-create-static-ve#L138

**Comment by andre-merzky** [comment]
Yep.  The assert basically existed because we only tested with virtualenv so far.  If you have the time, feel free to remove it and to check how the conda code path behaves...

**Comment by AymenFJA** [comment]
@andre-merzky , I did that, and RP silently exists with no error in the logs.

```
RADICAL pilot: 1.14.0

new session: [parsl.radical.session.radical.3.aymen.019104.0001]               \
database   : [mongodb://aymen:****@9xxxxxx/radical3]             ok
create pilot manager                                                          ok
create task manager                                                           ok
submit 1 pilot(s)
        pilot.0000   local.localhost          12 cores       0 gpus           ok
submit: ########################################################################

--------------------------------------------------------------------------------
PMGR Is Active submitting tasks now

closing session parsl.radical.session.radical.3.aymen.019104.0001              \
close task manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                          timeout
                                                                              ok
+ parsl.radical.session.radical.3.aymen.019104.0001 (json)
+ pilot.0000 (profiles)
+ pilot.0000 (logfiles)
session lifetime: 49.0s
```

**Comment by andre-merzky** [comment]
This is supported now.
