### ISSUE TITLE
prepare_env may result in invalid state without sufficient error

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2589]
## updated description

If environment preparation encounters problems, a venv may be created that does not include the intended packages, and additional supporting files expected by RP may be missing. However, the `prepare_env` command may complete without errors. Tasks using `named_env` may launch and then fail with confusing errors.

## Original description

When I try to launch a task that uses a *named_env* referring to a `prepare_env` environment, I get strange errors from unexpectedly missing paths.

It seems that when reaching the conditional at
https://github.com/radical-cybertools/radical.pilot/blob/64253944063236c9850d5a8b35d2308bd5e78b31/src/radical/pilot/agent/launch_method/base.py#L200
the shell script is not yet detected. But by the time I look for it, the file exists.

When the conditional is entered, the `ru.env_prep(environment=ru.env_read(src)` fails because the file named at 
https://github.com/radical-cybertools/radical.pilot/blob/64253944063236c9850d5a8b35d2308bd5e78b31/src/radical/pilot/agent/launch_method/base.py#L194
does not exist.
I couldn't figure out where this file is suposed to be created, but I can't find it in my sandbox. The venv itself, though, exists.

A second issue may or may not be relevant: the `prepare_env` names packages that were intended to be installed from distribution archive files staged with `pilot.stage_in`, but for some reason they have not been staged and the `agent.0.log` has lines like

     WARNING: Requirement '/home/rp/radical.pilot.sandbox/rp.session.4407a266-c232-11ec-bf66-0242ac120004/pilot.752df9dd-20f0-4bf5-9a77-e115f28285d8/radical.utils-1.14.0.tar.gz' looks like a filename, but the file does not exist

As a result, the venv is missing intended packages. I don't know whether these warnings would have caused some other unexpected condition.

**Comment by eirrgang** [comment]
Interesting. So perhaps something about #2590 may be keeping `prepare_env` from doing what it is supposed to, but is not causing the `prepare_env` to actually produce an error, or for the dependent task to fail with useful output?

Note, this issue is from the same script as #2590: https://github.com/SCALE-MS/scale-ms/blob/4b0681b9e44a318ae402b3f4837e6737c34a8580/tests/test_rp_venv.py#L94

**Comment by andre-merzky** [comment]
Yes, that is my suspicion.  Not yet sure how that can happen though, but am trying to reproduce it.

**Comment by eirrgang** [comment]
I can confirm that the issue described here is avoided when the virtual environment can be prepared as intended.

Maybe this issue, then, should be reframed as "prepare_env needs to fail harder if environment is not complete"?

**Comment by andre-merzky** [comment]
CLose - please open if still a problem
