### ISSUE TITLE
Request for clearer behavior/documentation in `stage_in` directive targets

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2590]
https://radicalpilot.readthedocs.io/en/stable/datastaging.html#staging-directives does not describe or link to the documentation on recognized URI schemes, but there seem to be additional unexpected semantics.

The implication in the documentation is that `target` refers to the environment of the Task for input staging directives, so stage_in.target does not work as expected with absolute paths.

In RP 1.14, I have tried to use an absolute path for the `target` on a `pilot.stage_in()` call. I use a basic string representation of a path.

When I look at `stager.0000.log` on the client side, I see that the target path has been translated to `file:///mypath` and the file was staged locally.

In the same log file, I can see that automatically generated data staging was correctly targeted to ` sftp://rp@compute/home/rp/radical.pilot.sandbox/rp.session.e28...`

I think that translating an absolute path to a local file path for a stage_in.target is inconsistent with the documentation at https://radicalpilot.readthedocs.io/en/stable/datastaging.html#staging-directives

I also think it would be very helpful to link from that section (or from https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Pilot.stage_in) to documentation about the URI schemes that are recognized in staging directives.

```
$ radical-stack 

  python               : /home/rp/rp-venv/bin/python3
  pythonpath           : 
  version              : 3.9.5
  virtualenv           : /home/rp/rp-venv

  radical.gtod         : 1.13.0
  radical.pilot        : 1.14.0
  radical.saga         : 1.14.0
  radical.utils        : 1.14.0

$ cat rp.session.e287de52-c240-11ec-ba50-0242ac120004/stager.0000.log 
1650634450.583 : stager.0000          : 17794 : 140495621834496 : INFO     : connect pub to state_pubsub: tcp://172.18.0.4:42893
1650634450.584 : stager.0000          : 17794 : 140495621834496 : DEBUG    : registered publisher for state_pubsub
1650634450.585 : stager.0000          : 17794 : 140495621834496 : INFO     : connect pub to control_pubsub: tcp://172.18.0.4:37679
1650634450.585 : stager.0000          : 17794 : 140495621834496 : DEBUG    : registered publisher for control_pubsub
1650634450.586 : stager.0000          : 17794 : 140495621834496 : INFO     : connect sub to control_pubsub: tcp://172.18.0.4:42625
1650634450.588 : stager.0000          : 17794 : 140495621834496 : DEBUG    : registered input stager.0000.work.NEW
1650634450.588 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager.0000 register input NEW: stager.0000.work.NEW
1650634450.588 : stager.0000          : 17794 : 140495621834496 : DEBUG    : registered worker work [NEW]
1650634450.588 : stager.0000          : 17794 : 140495621834496 : INFO     : connect pub to stager_response_pubsub: tcp://172.18.0.4:43641
1650634450.589 : stager.0000          : 17794 : 140495621834496 : DEBUG    : registered publisher for stager_response_pubsub
1650634450.687 : stager.0000          : 17794 : 140495685551936 : DEBUG    : start heartbeat
1650634450.688 : stager.0000          : 17794 : 140495685551936 : INFO     : connect sub to heartbeat: tcp://172.18.0.4:40849
1650634456.737 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0000 (NEW)
1650634456.737 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0001 (NEW)
1650634456.737 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0002 (NEW)
1650634456.737 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager got  sds: ['sd.0000', 'sd.0001', 'sd.0002'] 
1650634456.737 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///tmp/rp.agent_cfg.u7xvlrrm
1650634456.737 : stager.0000          : 17794 : 140495621834496 : INFO     :       to sftp://rp@compute/home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9//agent.0.cfg
1650634457.595 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///home/rp/rp-venv/lib/python3.9/site-packages/radical/pilot/agent/bootstrap_0.sh
1650634457.595 : stager.0000          : 17794 : 140495621834496 : INFO     :       to sftp://rp@compute/home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9//bootstrap_0.sh
1650634458.022 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///home/rp/rp-venv/bin/radical-utils-env.sh
1650634458.022 : stager.0000          : 17794 : 140495621834496 : INFO     :       to sftp://rp@compute/home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9//radical-utils-env.sh
1650634458.446 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager done sds: ['sd.0000', 'sd.0001', 'sd.0002'] 
1650634458.819 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0003 (NEW)
1650634458.819 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager got  sds: ['sd.0003'] 
1650634458.819 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file://localhost//tmp/rp_agent_tmpzulld2rt/rp.session.e287de52-c240-11ec-ba50-0242ac120004.pmgr_launching.0000.tgz
1650634458.819 : stager.0000          : 17794 : 140495621834496 : INFO     :       to sftp://rp@compute/home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/rp.session.e287de52-c240-11ec-ba50-0242ac120004.pmgr_launching.0000.tgz
1650634459.294 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager done sds: ['sd.0003'] 
1650634461.772 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0000 (NEW)
1650634461.772 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0001 (NEW)
1650634461.772 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0002 (NEW)
1650634461.773 : stager.0000          : 17794 : 140495621834496 : DEBUG    : got sd.0003 (NEW)
1650634461.773 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager got  sds: ['sd.0000', 'sd.0001', 'sd.0002', 'sd.0003'] 
1650634461.773 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///home/rp/rp-venv/lib/python3.9/site-packages/radical/utils/radical.utils-1.14.0.tar.gz
1650634461.773 : stager.0000          : 17794 : 140495621834496 : INFO     :       to file:///home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9/radical.utils-1.14.0.tar.gz
1650634462.703 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///home/rp/rp-venv/lib/python3.9/site-packages/radical/saga/radical.saga-1.14.0.tar.gz
1650634462.703 : stager.0000          : 17794 : 140495621834496 : INFO     :       to file:///home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9/radical.saga-1.14.0.tar.gz
1650634463.017 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///home/rp/rp-venv/lib/python3.9/site-packages/radical/pilot/radical.pilot-1.14.0.tar.gz
1650634463.017 : stager.0000          : 17794 : 140495621834496 : INFO     :       to file:///home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9/radical.pilot-1.14.0.tar.gz
1650634463.331 : stager.0000          : 17794 : 140495621834496 : INFO     : transfer file:///tmp/tmpq_50srse/scalems-0+unknown.tar.gz
1650634463.331 : stager.0000          : 17794 : 140495621834496 : INFO     :       to file:///home/rp/radical.pilot.sandbox/rp.session.e287de52-c240-11ec-ba50-0242ac120004/pilot.41e2bce7-0610-4871-affc-3b5f378579f9/scalems-0+unknown.tar.gz
1650634463.646 : stager.0000          : 17794 : 140495621834496 : DEBUG    : stager done sds: ['sd.0000', 'sd.0001', 'sd.0002', 'sd.0003'] 
1650634544.766 : stager.0000          : 17794 : 140494956918528 : WARNING  : hb stager.0000[cmgr.0000]: 1650634544.8 - 1650634483.8 > 60: timeout
1650634544.823 : stager.0000          : 17794 : 140494956918528 : INFO     : stop stager.0000 (17794 : Thread-3) [__main__.hb_term_cb]
1650634544.823 : stager.0000          : 17794 : 140494956918528 : WARNING  : hb fail cmgr.0000: fatal (17794)

```

## Additional comments

The relationship between the documentation at https://radicalpilot.readthedocs.io/en/stable/apidoc.html?highlight=Url#radical.pilot.TaskDescription.pilot and https://radicalpilot.readthedocs.io/en/stable/datastaging.html#staging-directives is not clear. There is both redundant and non-overlapping information, and neither references the other.

I think that there may be some semantic and/or syntactical differences in staging directives for tasks vs. pilots, but it is not clear.

Also, references to `ru.Url` and `rp.Url` do not provide links to documentation about supported schemes.

**Comment by andre-merzky** [comment]
Thanks @eirrgang .  Can you please add the staging directive you added to the task description?  Thanks.

**Comment by eirrgang** [comment]
> Thanks @eirrgang . Can you please add the staging directive you added to the task description? Thanks.

This is from https://github.com/SCALE-MS/scale-ms/blob/4b0681b9e44a318ae402b3f4837e6737c34a8580/tests/test_rp_venv.py#L78

Complete artifacts should be available at https://github.com/SCALE-MS/scale-ms/actions/runs/2195314193

**Comment by andre-merzky** [comment]
Oh, now I get it: the suprising behavior is that an absolute path gets changed into a path relative to the sandbox, right?  Ok, thanks, will check.

**Comment by eirrgang** [comment]
A quick note:

I did not intend this to be a feature request to be able to place files anywhere in the remote filesystem. Rather
* I want to place a file relative to the session or pilot sandbox, rather than relative to a Task, and
* I wanted to bring attention to the fact that the relative behavior of absolute vs. relative paths is confusing.

Upon reflection, I realize that from the text "and target refers to the working directory of the Task", I assumed `target` always refers to the pilot agent environment. It seems reasonable that this doesn't need to be the case, and input_staging directives could be used to place files in the client environment. But this should be clarified in the documentation. It is definitely counter-intuitive, though, that a relative path will be interpreted as, effectively, `task:///path`, whereas an absolute path is interpreted as `file:///path`.

If a `pilot:///path` or `session:///` URI (or similar) were supported to place files relative to their respective sandboxes, I would consider that a superior solution so that the client code does not need to know the remote filesystem layout.

**Comment by eirrgang** [comment]
> closed this as [completed](https://github.com/radical-cybertools/radical.pilot/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/radical-cybertools/radical.pilot/commit/e61f7219882e0fd814cb526f01c9486d3f864193 [13 hours ago](https://github.com/radical-cybertools/radical.pilot/issues/2590#event-7200862552)

Is there a separate issue or PR to track the scheme documentation or the potentially confusing automatic conversion of `/path` to `file:///path`?

**Comment by eirrgang** [comment]
> Is there a separate issue or PR to track the scheme documentation or the potentially confusing automatic conversion of `/path` to `file:///path`?

Maybe #2441?

**Comment by andre-merzky** [comment]
Thanks for noting this, @eirrgang !

**Comment by eirrgang** [comment]
I think the behavior for this issue has been addressed, but the documentation is still scattered and insufficient.

Most notably:
* https://radicalpilot.readthedocs.io/en/stable/datastaging.html#staging-directives still does not describe or link to the different behaviors of different `rs.Url` schemes.
* The Url schemes described just after https://radicalpilot.readthedocs.io/en/stable/apidoc.html?highlight=Url#radical.pilot.TaskDescription.pilot are incomplete, as best I can tell.

Overall, I think it would be very helpful to consolidate the docs for staging directives and for supported URL schemes, moving various notes from disconnected function docstrings to some more centralized type or module docstring, then use the module docstring as the basis for the static RST docs such as chapters 5 and 6.

Would you prefer to address these documentation requests in a separate new issue or does the current issue still seem like the right scope?

**Comment by andre-merzky** [comment]
> Would you prefer to address these documentation requests in a separate new issue or does the current issue still seem like the right scope?

It's ok to keep them here IMHO.

**Comment by andre-merzky** [comment]
Staging locations are now supported and documented [here](https://radicalpilot.readthedocs.io/en/stable/tutorials/staging_data.html).
