### ISSUE TITLE
`pilot.cancel()` hangs in 1.14

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2592]

**Comment by eirrgang** [comment]
Ref https://github.com/SCALE-MS/scale-ms/actions/runs/2167943699/attempts/1

**Comment by andre-merzky** [comment]
Sorry for late response - but is this still the case?  I can't reproduce the error with the current stack.

**Comment by andre-merzky** [comment]
> If `pilot.cancel()` is part of the recommended RP session management protocol, we can add a test job back into the scalems automated test suite and see what happens.

Yes, `pilot.cancel()` is expected to work reliably.  If you think re-adding the test is worthwhile, then please - otherwise I am happy to close the issue and we can reopen once a reproducible case pops up.

**Comment by eirrgang** [comment]
> If you think re-adding the test is worthwhile

It is only worthwhile to me if `pilot.cancel()` is recommended as part of the shutdown procedure (and should be reintroduced to `scalems` at some point), as opposed to just calling `session.close()`.

Otherwise, it seems like RP-internal an integration test.

**Comment by andre-merzky** [comment]
`session.close()` is the way - `pilot.cancel()` will be called implicitly then.  Thanks!
