### ISSUE TITLE
jsrun issues with HPC-Workflows

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2593]
See https://github.com/radical-collaboration/hpc-workflows/issues/152

**Comment by mturilli** [comment]
Suggested to the user to use PRRTE. Waiting for Wenji. Ping user after 2 weeks.

**Comment by mtitov** [comment]
Temporary solution:

- use a particular branch of RP `temp/jsrun_hpcw` (`pip install git+https://github.com/radical-cybertools/radical.pilot.git@temp/jsrun_hpcw`), which enforces to use the following options for `jsrun`: `--bind rs -n{} -p{} -r6 -g1 -c1`

p.s. another approach that was checked is to use different `jsrun` executable ([link](https://github.com/radical-cybertools/radical.pilot/issues/2673#issuecomment-1230539080)) - didn't resolve the issue

**Comment by andre-merzky** [comment]
Note: we got a ping-back from Wenjie, asked for more details on current state and proposed to use `mpirun` as LM.

**Comment by AymenFJA** [comment]
As we discussed in the devel meeting, in case `mpi4py` is required to be deployed on Summit, please check this document: https://docs.olcf.ornl.gov/software/python/parallel_h5py.html?highlight=mpi4py#installing-mpi4py

**Comment by andre-merzky** [comment]
Note that in current devel branch, MPIRUN has replaced JSRUN as launch method - jsrun is now documented as broken on system level (ERF file interpretation is buggy), MPIRUN should be more stable.

**Comment by andre-merzky** [comment]
Closed until we have new information from either ORNL or end user.
