### ISSUE TITLE
task w/o `named_env` or `pre_exec` should run in the native env

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2609]
Right now we run the task in the launch method env - we should deactivate that and instead activate the virgin env we found when starting the pilot.

**Comment by iparask** [comment]
Hello team,

I'm exploring workflow/workload management systems for the Simons Observatory project I'm working on at Princeton. I believe that RP can play a role in executing the project's data analysis workflows.

To the point, I'm using NERSC Perlmutter and I want to load a python module that conflicts with the python module RP uses as the default. I also tried to reset the modules but that did not work either. The task description is:

```python
td = rp.TaskDescription()
td.pre_exec = ["module list",
               "module reset",
               "module avail",
               "module list"]
td.executable = '/usr/bin/sleep'
td.arguments = ['1']
td.mode = rp.TASK_PROC
td.ranks = 1
td.cores_per_rank = 1
```

and the task's STDERR looks like:

```
cpu-bind=MASK - nid005148, task  0  0 [892287]: mask 0x1 set

Currently Loaded Modules:
  1) craype-x86-milan
  2) libfabric/1.15.2.0
  3) craype-network-ofi
  4) xpmem/2.6.2-2.5_2.27__gd067c3f.shasta
  5) PrgEnv-gnu/8.3.3
  6) cray-dsmml/0.2.2
  7) cray-libsci/23.02.1.1
  8) cray-mpich/8.1.25
  9) craype/2.7.20
 10) gcc/11.2.0
 11) perftools-base/23.03.0
 12) cpe/23.03
 13) xalt/2.10.2
 14) Nsight-Compute/2022.1.1
 15) Nsight-Systems/2022.2.1
 16) cudatoolkit/11.7
 17) craype-accel-nvidia80
 18) gpu/1.0
 19) mongodb/100.5.2
 20) conda/Miniconda3-py311_23.5.2-0
 21) evp-patch
 22) python/3.11                           (dev)

  Where:
   dev:  Development Tools and Programming Languages



Unloading the cpe module is insufficient to restore the system defaults.
Please run 'source
/opt/cray/pe/cpe/23.03/restore_lmod_system_defaults.[csh|sh]'.
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: /global/common/software/sobs/perlmutter/modulefiles /opt/cray/pe/lmod/modulefiles/mpi/gnu/8.0/ofi/1.0/cray-mpich/8.0
pre_exec failed
srun: error: nid005148: task 0: Exited with exit code 1
srun: Terminating StepId=17705671.0
```

I think this is because the environment is not the default environment of the system when a task starts. Is there a plan for fixing this or is it not very high priority for now?

Thank you!

**Comment by mtitov** [comment]
@iparask Ioannis!! we have multiple solutions for you:
- seems like `module reset` doesn't do what's expected, would `module unload python` do? (*) after moving from MongoDB we didn't clean out `module load mongodb` for Perlmutter, that will be gone, thus the only module we load is `python`
- `td.pre_exec = ['source $RP_PILOT_SANDBOX/env/bs0_orig.sh']` reload environment, which was before RP's pre-bootstrapping
- you can create your env with [`pilot.prepare_env`](https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Pilot.prepare_env) and then use this environment for tasks [`td.named_env`](https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.TaskDescription.named_env)

**Comment by iparask** [comment]
@mtitov Hello!

> * seems like `module reset` doesn't do what's expected, would `module unload python` do? (*) after moving from MongoDB we didn't clean out `module load mongodb` for Perlmutter, that will be gone, thus the only module we load is `python`

`module unload python` does not work. This is the module I want to unload.

> * `td.pre_exec = ['source $RP_PILOT_SANDBOX/env/bs0_orig.sh']` reload environment, which was before RP's pre-bootstrapping

This worked with some additional things. 

> * you can create your env with [`pilot.prepare_env`](https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Pilot.prepare_env) and then use this environment for tasks [`td.named_env`](https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.TaskDescription.named_env)

There is already a module with all the necessary software python stack pre-install, so creating a new virtual env is redundant.

Do you think the task environment will be clean at some point, that is the same as when a slurm job starts?

**Comment by mtitov** [comment]
>> * `td.pre_exec = ['source $RP_PILOT_SANDBOX/env/bs0_orig.sh']` reload environment, which was before RP's pre-bootstrapping
>
> This worked with some additional things. 

> Do you think the task environment will be clean at some point, that is the same as when a slurm job starts?

@iparask Ioannis, can you please try this branch `fix/task_env` (PR https://github.com/radical-cybertools/radical.pilot/pull/3083, we use original env as a base for LM env setup), and then you wouldn't need to have sourcing it in `pre_exec`.

p.s. if LM requires some env configuration, that could be done in a corresponding config section
```
mkdir -p ~/.radical/pilot/configs
cat > ~/.radical/pilot/configs/resource_nersc.json <<EOF
{
    "perlmutter": {
        "launch_methods" : {"order": ["SRUN"],
                            "SRUN" : {
                                "pre_exec_cached": ['<load modules or set env for LM>']
                            }}
    }
}
EOF
```

**Comment by iparask** [comment]
It seems to work nicely. This is an interesting way of setting the environment. I'll check it out.

**Comment by iparask** [comment]
@mtitov, please let me know when this is released. Thank you!

**Comment by mtitov** [comment]
@iparask ok, we will not have it within the oncoming release, but will try to have it in the next one
