### ISSUE TITLE
Non parallel execution of concurrent tasks with SRun LM

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2620]
While having tests on Crusher@ORNL, I have found that 2 tasks (with 2 processes each) were executed sequentially on one node
```
1652996332.5415790,app_start,,MainThread,task.000000,AGENT_EXECUTING,
1652996332.5416700,app_start,,MainThread,task.000000,AGENT_EXECUTING,
1652996342.7865680,app_stop,,MainThread,task.000000,AGENT_EXECUTING,
1652996342.7867390,app_stop,,MainThread,task.000000,AGENT_EXECUTING,
...
1652996343.0564940,app_start,,MainThread,task.000001,AGENT_EXECUTING,
1652996343.0565940,app_start,,MainThread,task.000001,AGENT_EXECUTING,
1652996353.1155790,app_stop,,MainThread,task.000001,AGENT_EXECUTING,
1652996353.1158390,app_stop,,MainThread,task.000001,AGENT_EXECUTING,
```
and there was the following message for the second task
```
srun: Job 116069 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 116069
...
```

Found from other users, who encountered the similar issue, that the reason is: `srun` command, which executed first, allocated all the memory.

_Possible solution_

(1) specify the total memory allocation in `sbatch` (need to check - is it optional)
```
#SBATCH --mem=[XXXX]MB
```
(2) specify the memory use per `srun` command
```
srun --exclusive --ntasks=1 --mem-per-cpu [XXXX/<n_tasks>]MB sleep 10
```
need to check option `--mem` as well

**Comment by andre-merzky** [comment]
check if that relates to #2584
