### ISSUE TITLE
radical-pilot-create-static-ve should use explicit executable paths

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2622]
In RP 1.14, the radical-pilot-create-static-ve script sets `VIRTENV_CMD="$PYTHON -m venv"`, then creates and activates a virtual environment.

Before guaranteeing the existence of `pip` in the virtual environment, though, the script calls `pip install --no-cache-dir --upgrade setuptools pip wheel| progress || exit 1`.

If `python3 -m venv` does not guarantee the installation of `pip` for whichever python + venv package are resolved, the `pip` executable may correspond to a different Python installation.

This causes two problems.

* The packages may or may not be upgraded/installed to a usable location (depending on behavior that may be installation-specific or version-specific, and which may change in future versions of `pip`).
* The Python installation seen by the build system for `$MODULES` may not be consistent with that of the virtual environment.

Suggestion:
* Use `"$PREFIX"/bin/python -m pip` or `"$PREFIX"/bin/pip3` instead of a bare `pip`
* Ensure that the venv has access to pip using a mechanism appropriate to the virtual environment type. (E.g. `conda install pip`, `python -m ensurepip`, or other)
* Make sure to fail if `pip` is not available.

**Comment by andre-merzky** [comment]
I have not seen that case happening and could not find documentation on it, but it can't hurt.  The `conda` code path already installs pip explicitly, I added `ensurepip` to the `venv` code path.
