### ISSUE TITLE
radical-pilot-create-static-ve may not fail when it should

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2623]
In RP 1.14, the script includes commands that may fail, but which are piped into commands that may not fail.

However, `-o pipefail` does not appear to be set.

This means that, for example, `stdbuf -oL $VIRTENV_CMD "$PREFIX" | progress` will not cause the script to exit if the virtual environment could not be created.

Suggestion: change `set -e` to `set -eo pipefail`

**Comment by andre-merzky** [comment]
I'm afraid that `pipefail` is not a POSIX shell feature, and we try to stick to POSIX as far as possible.  The `progress` feature however is not really needed anymore (the script in the past was used interactively, but now rarely is), so we can get rid of most of the pipes...

**Comment by andre-merzky** [comment]
Uh, we apparently cleaned that up already - only two pipes left in the code and both are ok to fail ([here](https://github.com/radical-cybertools/radical.pilot/blob/devel/bin/radical-pilot-create-static-ve#L119=) and [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/bin/radical-pilot-create-static-ve#L55=))
