### ISSUE TITLE
Build Time of Notebooks is >30mins on readthedocs

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2630]
The build time of 9 notebooks of section 3 of the documentation is taking ~29mins on readthedocs as of now. 
However, if I add 1 more notebook the build time exceeds the maximum build of RTD.

It seems we are on 30mins plan somehow - https://docs.readthedocs.io/en/stable/builds.html#build-resources

I have already followed their recommendations listed here - https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html
Though they mention requesting more resources, I am not sure if we want to go that route, or we should think of better alternative.

Originated in #2553

**Comment by kartikmodi** [comment]
@mturilli We discussed in the meeting that we would like to drop an email to support@readthedocs.org as suggested by them on the links above. 
If the problem is not solved - 
1. Explore ways to merge several notebooks into one - trying to avoid bootstrapping, again and again, sharing sessions among notebooks, etc. - Suggested by @andre-merzky 
2. Explore the feasibility build on some other machine like three, and push the results directly to RTD

**Comment by mturilli** [comment]
This was an issue with multiple managers to be created at the same time on the same notebook.
