### ISSUE TITLE
ddmd.py terminates after sim_md tasks on non-localhost

### ISSUE THREAD

**Issue by vrpascuzzi** [radical-cybertools/radical.pilot#2631]
[`ddmd.py`](https://github.com/radical-cybertools/radical.pilot/blob/da1d6c46eb3260913771fa71654731016214ffe5/examples/misc/ddmd.py) is expected to execute a number of (as of now, mock) (1) MD simulation, (2) aggregation, (3) ML training and (4) 'agent' tasks such that each successive set of a given type of tasks is triggered by a callback which depends on the number of required tasks of another type.

The script works fine when run on `localhost` but when launching a job on compute nodes, the job terminates after the first set of tasks execute; other tasks are not scheduled.

Sandbox:
[rp.session.login3.pascuzzi.019165.0012.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/8968999/rp.session.login3.pascuzzi.019165.0012.tar.gz)

@mturilli, @andre-merzky

**Comment by andre-merzky** [comment]
This is resolved with making the task cancellation non-blocking.
