### ISSUE TITLE
Iteration of the state model

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#264]
This ticket aims to help sharing comments/opinions on the state model of radical pilot (and of any future system we will have to design/implement together). As such it is nor complete, nor exhaustive, nor cast on stone. Hopefully, with time, it will become as comprehensive as our goal will require it to be.

Here an attempt to summarize a discussion we had at dinner with too little alcohol to help. As usual, two issues beset this type of discussion: 

1. hill-defined problem - multiple questions are crammed into a 'problem'; 
2. hill-defined goal - the 'problem' is brought forward because of an undeclared 'gut feeling' that leads to a 'preference' that set the goal to 'get the code that way'. 

Instead, problems should well isolated and the goal should be posed by wanting to "understand, justify, and possibly quantify what the system needs in order to comply with the given set of requirements". 

* **Goal**
  * Refine the current state model of radical.pilot so to:
    * Adopt a consistent definition of state - i.e. all the states are 'states' and not a mix of information, log, events, and durations. 
    * Expose all and only the states on which a user - a programmer using the libraries of radical.pilot  - could directly operate by making decisions.
    * Make easier for the radical.pilot contributors to clearly distinguish between logging and needing/creating a state for one of the radical.pilot entities.
    * Stop having endless and pointless discussions in which everyone wants just to push his own opinion forward until all the others give up their own.
    * Define STATE_X :)

* **Questions**
  * What is a state?
    * Difference between (atomic) events and durations. 
      * An event is an atomic point in time - scheduled, queued, executed - while a duration encompasses multiple points in time - queuing, scheduling, executing. 
      * Durations start and end with an atomic event: queuing = (start queued, end queued); Scheduling = (start Scheduled, end Scheduled) and so on. You may notice that the semantic of the term (not the name) 'queued' is ambiguous. Does it refer to entering in a queue or exiting it? As such, it should not be used without specifying its relation with the duration 'queueing'. 
    * We suggest that a state is a duration bounded by two events because a state is meant to have a duration - an entity is in a state for a certain amount of time, no matter how short - and an entity enters and exits from that specific state. The same event may timestamp the end of a state and the beginning of another state. Such an event indicates a 'state transition'.
    * Both event and states are informative. An event tells us that something has happened in the system while a state tells us that something will keep happening for a certain, possibly unspecified, amount of time. A bit more formally, this is equivalent to say that the values of the (sub)set of properties that define an entity will not change for a period of time.

  * How do we represent events and states?
    * An event may be represented by a single timestamp plus one or more identifiers and properties (timestamp; name_event; value/relation/description/etc). A state needs at least two timestamps - start/end - plus identifiers and properties as needed.
    * We log events into MongoDB in the 'log' field, including the state transitions that each couple of events identifies.
    * We timestamp each event.
    * We set the property 'state' of an entity (e.g. instance) to the state name so that we can check for it and act upon it.

  * How a state differs from a log?
    * We log events both related and unrelated to a state. We may log:
      * an event that does not represent a state transition - callback x has fired;
      * events that are state transitions - pilot x has entered/exited queue y on resource z;
      * events about a state - pilot x is still in queue y on resource z.
    * Not all events needs to become state transitions of an entity. E.g. "pilot x received a request to execute CU y" is not a state transition while 'Pilot x is ready to execute CU' is the event starting the state 'ready to execute' as much as 'Pilot x has started to execute its first CU' is the event starting the state 'Executing' and possibly ending the state 'ready to execute'.

  * Are there special states?
    * Maybe. There are special events: 
      * Initial and Final;
      * Start and Done;
      * Begin and End, take your pick. 

      These are special events because before and after them there are no other events and, therefore, no other states. This events represent also the first and last state transition of an entity. 'DONE' or 'CREATED' we need to check on them but we understand that saying that a pilot that is no more a pilot is in a state DONE is, well, a bit of a special state. Maybe we should not set it in the pilot entity because keeping such entity around after it is DONE makes little sense. We might want to check for an event in the DB instead and stop calling it a state.

  * When it is useful to expose states to a user via an API?
    * __This is the question that is often mistakenly used to argue about what a state should be__. An entity has a set of states defined by every transition it goes through. Once well-defined, the states of an entity are a direct consequence on how we design its behavior and there should be little debate about whether it has a state or not! Do we have an event that is a state transition? Yes, well, then we have a state. 
    * __Another story__ is when we discuss about the API of the system and we ask ourselves: should we expose this state? This question should be answered pragmatically by understanding whether the user will have the possibility and/or the need to do something with the information that that entity is in that state.
    * We more or less agreed on the following: 
      * we should be careful to pretend to have complete knowledge about what a user will be able and/or need to do with the information about a state of an entity.
      * We should keep in mind that often aggregating/hiding states via an API is much simpler and less time consuming that recoding an entity so to have a new state. 
      * __Therefore, starting with a rich API and refining it down the road until it becomes minimal (and elegant) appears to be a pragmatic strategy.__

  * How states related to contracts?
    * States are periods in time in which the values of a (sub)set of properties of an entity remain constant -> This states may be exposed via an API -> The API represents the contract between the programmer and the user. As every lawyer will tell, never be in hurry to sign a contract!

OK, ufff, this was long but I hope rewarding in terms of laying the foundations for a constructive discussion. Now to the applied part. In the experimental branch we have the following states:

* Common States: NEW, DONE, CANCELED, FAILED, PENDING
* ComputePilot States: PENDING_LAUNCH, LAUNCHING, PENDING_ACTIVE, ACTIVE
* ComputeUnit States:  STATE_X, PENDING_INPUT_STAGING, STAGING_INPUT, PENDING_EXECUTION, SCHEDULING, EXECUTING, PENDING_OUTPUT_STAGING, STAGING_OUTPUT

Questions and some answers:
* Are these all states following the given definition?
  * NEW, DONE, CANCELED, FAILED are all 'special' states. Keeping them as states or transforming them into events is a matter of logical consistency and, upon careful consideration, possibly of pragmatic coding.
  * PENDING, PENDING_LAUNCH, PENDING_ACTIVE, PENDING_INPUT_STAGING, PENDING_EXECUTION, PENDING_OUTPUT_STAGING indicate a degree of inconsistency. If the entity is in a PENDING state, what type of pending? Why we have states for some type of pending and not for others? Possibly, some of the type of pending are generic names for other type of states like, for example, queueing, bootstrapping, and so on? Again, this is not a naming issue but it is about not being clear on the semantics of a name. An example of a naming issue would be for me discussing whether to use PENDING_INPUT_STAGING instead of STAGING_INPUT.
  * LAUNCHING, ACTIVE, SCHEDULING, EXECUTING, STAGING_INPUT, STAGING_OUTPUT seems clear enough to me.
  * STATE_X: following our discussions and this never-ending ticket we should be able to make an informed and shared decision about its definition (event or state) and its semantics. At least I really hope so! :)

* Are all the events signing their start/end being logged?
  * This is something to check once we will have agreed on the iteration of the state model. Should we have an explicit event model? No seriously...

* Which one should be exposed via the radical.pilot API?
  * At the moment I would expose them all. Let's see whether we can/need to use them. If not, we could hide/aggregate them at API level.

**Comment by andre-merzky** [comment]
There is reasonable agreement on the state model evolution by now -- see https://github.com/radical-cybertools/radical.pilot/wiki/State-Model-Evolution .  All other items discussed here seem to be addressed by the current profiling approach (ie. information are exposed via performance profiling, not via the state model).  So I will close this specific ticket.
