### ISSUE TITLE
Type error in master.py?

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2652]
https://github.com/radical-cybertools/radical.pilot/blob/5b704de493bfd4ad6180479a25436fbe1030869f/src/radical/pilot/raptor/master.py#L398 seems to show some sort of error. Immediately after assigning a list to `stats`, `stats` is subscripted as if it were a dictionary. Is this a bug or a dead code block? Or am I misreading it somehow?

**Comment by andre-merzky** [comment]
Fixed by PR #2780
