### ISSUE TITLE
Fail to run official example on localhost

### ISSUE THREAD

**Issue by LTMeyer** [radical-cybertools/radical.pilot#2659]
## Context

I wanted to try RP on localhost. I installed RP with `pip install radical.pilot`. I ran the example [`00_getting_started.py`](https://radicalpilot.readthedocs.io/en/stable/_downloads/f96f7e4620d725b0b15323eac9de9c35/00_getting_started.py) after having set up MongoDB. The code failed giving the following output. 

<blockquote>
================================================================================
Getting Started (RP version 1.15.1)                                            
================================================================================

new session: [rp.session.lucas.019209.0003]               \
database   : [mongodb://127.0.0.1:27017/rp]                                   ok
create pilot manager                                                          ok
create task manager                                                           ok

--------------------------------------------------------------------------------
submit pilots                                                                   

submit 1 pilot(s)
        pilot.0000   local.localhost           4 cores       0 gpus           ok

--------------------------------------------------------------------------------
submit 10 tasks                                                                 

create: ########################################################################
submit: ########################################################################
wait  : --------------
RADICAL Utils -- Stacktrace [45924] [MainThread]

lucas      45924   30577  2 18:07 pts/3    00:00:00  |   |       \_ python 00_getting_started.py
lucas      46420   45924  1 18:07 pts/5    00:00:00  |   |           \_ /usr/bin/zsh -i
lucas      46521   45924  1 18:07 pts/6    00:00:00  |   |           \_ /bin/sh -i
Traceback (most recent call last):
File "/home/lucas/Documents/Work/PhD/Code/sandbox/radical-pilot/00_getting_started.py", line 108, in <module>
tmgr.wait_tasks()
File "/home/lucas/miniconda3/lib/python3.9/site-packages/radical/pilot/task_manager.py", line 1011, in wait_tasks
time.sleep (0.1)
KeyboardInterrupt

--------------
exit requested

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.lucas.019209.0003      \
close task manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
+ rp.session.lucas.019209.0003 (json)
- pilot.0000 (profiles)
- pilot.0000 (logfiles)
session lifetime: 19.1s                                                       ok

--------------------------------------------------------------------------------
</blockquote>

## Expected Behaviour

The tasks are successfully executed and the example works as advertised in [the tutorial](https://radicalpilot.readthedocs.io/en/stable/user_guide/00_getting_started.html).

## Log files

1. The output is displayed above.
2. The files generated by `radical-pilot-fetch-logfiles` were empty.
3. Output of `grep -r ERROR.`
<blockquote>
pmgr.0000.log:1659715042.404 : pmgr.0000            : 43141 : 140655925905152 : ERROR    : [Callback]: pilot 'pilot.0000' failed (exit)
pmgr.0000.log:1659715042.404 : pmgr.0000            : 43141 : 140655925905152 : ERROR    : listener died
rp.log:1659715029.797 : pmgr_launching.0000  : 43361 : 140658246665024 : ERROR    : skip launcher PSI_J
Binary file rp.log matches
rp.session.lucas.019209.0002.log:1659715043.274 : rp.session.lucas.019209.0002 : 43141 : 140658053542720 : ERROR    : failed to fetch profiles for pilot.0000
</blockquote>

## Package Versions

- radical.gtod            1.13.0
- radical.pilot           1.15.1
- radical.saga            1.14.0
- radical.utils           1.15.0
- pyzmq                   23.2.0

I tried to remove all files and reinstall RP without success.

Let me know if I can provide more information.

**Comment by mtitov** [comment]
Hi @LTMeyer, can you please re-run with debug flag on?
```
RADICAL_LOG_LVL=DEBUG ./00_getting_started.py
```
We do limit log messages by default, and I suspect that the issue might be system-related (RP fails to run something due to a certain setup), but we'll see it from extended logs. And after that if you wouldn't mind could you attach corresponding sandboxes here (client sandbox - `<session>` directory within directory with the script; pilot sandbox - `<session>` directory in `$HOME/radical.pilot.sandbox/`)

**Comment by LTMeyer** [comment]
Hi @mtitov,
Thank you for your quick reply.
I ran the first example as you suggested, but I didn't see any change in the output. Actually I had previously setup the log level directly in the example with :
`os.env["RADICAL_LOG_LVL"] = "DEBUG"`

Here you'll find the archive containing the files in `$HOME/radical.pilot.sandox/<session>`:
[rp.session.lucas-Precision-7560.lucas.019210.0001.zip](https://github.com/radical-cybertools/radical.pilot/files/9275081/rp.session.lucas-Precision-7560.lucas.019210.0001.zip)

**Comment by andre-merzky** [comment]
Thanks for the archive @LTMeyer.  It looks like the pilot never started to execute.  You should find a directory in the location where you ran the example script, with the session name: `./rp.session.lucas-Precision-7560.lucas.019210.0001/`.  In there should be a number of log files, and a `grep ERROR *.log` should help to close into the cause of the problem.  If that does not yield anything, would you mind attaching an archive of that session directory also?  Thanks!

**Comment by LTMeyer** [comment]
Hi @mtitov,
The errors listed with `grep` are the same I put above :
>pmgr.0000.log:1659791140.981 : pmgr.0000            : 8821  : 139788602554112 : ERROR    : [Callback]: pilot 'pilot.0000' failed (exit)
pmgr.0000.log:1659791140.981 : pmgr.0000            : 8821  : 139788602554112 : ERROR    : listener died
rp.log:1659791127.563 : pmgr_launching.0000  : 9044  : 139675179746112 : ERROR    : skip launcher PSI_J
Binary file rp.log matches
rp.session.lucas-Precision-7560.lucas.019210.0001.log:1659791141.933 : rp.session.lucas-Precision-7560.lucas.019210.0001 : 8821  : 139790595035968 : ERROR    : failed to fetch profiles for pilot.0000

Here you can find an archive with most of the files of the session directory.
[rp.session.lucas-Precision-7560.lucas.019210.0001.zip](https://github.com/radical-cybertools/radical.pilot/files/9275805/rp.session.lucas-Precision-7560.lucas.019210.0001.zip)

I don't know if this is relevant but I'm using `zsh` as shell. 
pmgr_launching.0000.err reads :
> AssertionError: /bin/sh: 6: PING: not found

Besides, is there anything to configure regarding ssh?  `pmgr.0000.log` reads :
> 'To use the ssh schema, make sure that ssh access to localhost is enabled.'

**Comment by andre-merzky** [comment]
> I don't know if this is relevant but I'm using `zsh` as shell.

Oh, that is indeed relevant as we do not support `zsh` as login shell (see [FAQ 11.7](https://radicalpilot.readthedocs.io/en/stable/faq.html?highlight=zsh#error-could-not-detect-shell-prompt-timeout)).  The underlying reason is that our job submission interacts with the shell on the target resource (which is in this case localhost, but nevertheless) and there requires a POSIX shell.

We are currently working on a replacement for that interaction layer, [`psi/j`](https://github.com/ExaWorks/psi-j-python/).  As long as you are only running on localhost, installing that in your client virtualenv / condaenv / ... might help you out.  Alas, `psi/j` is not yet released to pypi, so you will have to clone the repo, install the dependencies (`pip install -r requirements.txt`) and the module itself (`pip install .`).  I hope this is not too much trouble - please let us know how that goes!

**Comment by LTMeyer** [comment]
> We are currently working on a replacement for that interaction layer, [`psi/j`](https://github.com/ExaWorks/psi-j-python/). As long as you are only running on localhost, installing that in your client virtualenv / condaenv / ... might help you out. Alas, `psi/j` is not yet released to pypi, so you will have to clone the repo, install the dependencies (`pip install -r requirements.txt`) and the module itself (`pip install .`). I hope this is not too much trouble - please let us know how that goes!

I thought this package was not necessary for RP to work. Nonetheless, once installed I was able to run the different examples without any of the previous error. Problem solved. :heavy_check_mark: 

> > I don't know if this is relevant but I'm using `zsh` as shell.
> 
> Oh, that is indeed relevant as we do not support `zsh` as login shell (see [FAQ 11.7](https://radicalpilot.readthedocs.io/en/stable/faq.html?highlight=zsh#error-could-not-detect-shell-prompt-timeout)). The underlying reason is that our job submission interacts with the shell on the target resource (which is in this case localhost, but nevertheless) and there requires a POSIX shell.
> 

Actually I also have `sh` installed but not used as default. RP didn't complain, so I assume it must find the `sh` path and not being troubled by `zsh` being also installed.

Thank you for the help.
