### ISSUE TITLE
pilot profiles should be transferred as tarball

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2663]
See https://github.com/radical-cybertools/radical.pilot/pull/2662/files#r942613889

**Comment by andre-merzky** [comment]
The cause for the current slow staging is as follows:  changes to speed up pilot termination does not leave the dying pilot enough time to pack profiles into a tarball.  Thus this [test](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/utils/session.py#L118) fails and `tarball_available` will remain set to `False`.  Thus in lien 170 in the same file we will begin to fetch profiles individually.  That is problematic for two reasons: (a) it is slow, as mentioned above, but also (b) it misses some raptor profiles which are located in the master sandboxes.

We should attempt to run a command on the target resource to create a tarball (recursively collect all profiles from all sandboxes) and then to stage the tarball (the latter code exists).

**Comment by kartikmodi** [comment]
> stage the tarball (the latter code exists).
Can you point this code location.
