### ISSUE TITLE
Run from Bridges2 login node

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2665]
- run from vetted machine via ssh (like Frontera)
  - run from vetted SanDiego VM
  - limit exemption on login node

contact support for advise

**Comment by AymenFJA** [comment]
Can I ask why from a login node and not interactively? Is there a specific case that requires running from a login node only? If so, what is it?

**Comment by AymenFJA** [comment]
@AymenFJA , commit Bridges-2 interactive resource config.
