### ISSUE TITLE
Report statistics about data transfer

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#268]
It would be useful to extend radicalpilot-stats so to report about total number of files staged in and out, total amount of MB, and total amount of time taken to stage from X to Y.

**Comment by andre-merzky** [comment]
This is straight forward to do by now, and should go into the analytics release.

**Comment by andre-merzky** [comment]
rather then reporting out-of-band, report data sizes in profiles.  Closing.
