### ISSUE TITLE
test cleans too much

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2685]
[this](https://github.com/radical-cybertools/radical.pilot/commit/28093105ddda39b4a98da86bd75647e9ec3aa7d2#diff-9a16516e57c25273d02053b7c382edb67850641c885466414aeb8cc4ee4d4e2dR20) commit added a cleanup hook to some rpu tests which makes sense, but unfortunately cleans out too much: it removes all `rp.session.*` dirs in `$PWD`.  It cleaned out some of my test sessions - those were easy to recreate, but I got worried about some sessions which might not.

The hook also cleans out the cache dir.  Less problematic maybe, but it would be better to only clean files the test creates.

Also, in line 127 of the same file is this:
```py
self.assertFalse(os.path.exists(rpu_db._CACHE_BASEDIR))
```
Since this runs before the cleanup, the assert will fail if the users cache dir exists - which is the case when at any point in the past the users fetched some session data.  I would suggest to either remove that assert, or to monkeypatch `rpu_db._CACHE_BASEDIR` to point to a different temporary location.  The latter would also help with the cleanup mentioned above.

Sorry for not catching this in the code review :-/

**Comment by mtitov** [comment]
Thank you, Andre, absolutely valid point! (sorry for removed sessions..)
