### ISSUE TITLE
Invalid Pilot documentation 

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2686]
This is related to #2218, the documentation shows that we support `virtualenv` here: https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Pilot.prepare_env. This is incorrect, as we switched from `virtualenv` to `venv`.  I do not know who to assign to this ticket, as Kartik is working on the documentation, I will let @andre-merzky decide.

**UPDATE: we do support both `virtualenv` and `venv` but the latter is not documented.**

**Comment by andre-merzky** [comment]
`virtualenv` is still supported FWIW, but I'll change the docstring to `venv` to be in sync with our code examples.

**Comment by eirrgang** [comment]
> `virtualenv` is still supported FWIW, but I'll change the docstring to `venv` to be in sync with our code examples.

For the moment, are they aliases to the same code path or are they functionally different? I.e. does one use the standard `venv` module and the other use the older `virtualenv` module?

**Comment by AymenFJA** [comment]
> `virtualenv` is still supported FWIW, but I'll change the docstring to `venv` to be in sync with our code examples.

oh, ok. I thought we totally abandoned `virtualenv ` thanks @andre-merzky.

**Comment by andre-merzky** [comment]
> > `virtualenv` is still supported FWIW, but I'll change the docstring to `venv` to be in sync with our code examples.
> 
> For the moment, are they aliases to the same code path or are they functionally different? I.e. does one use the standard `venv` module and the other use the older `virtualenv` module?

It's an alias and thus has no semantic differences, it exists only for backward compatibility.
