### ISSUE TITLE
better raptor documentation

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2688]
This is related to #2218. But in general, we need to document RAPTOR capabilities and setup, as it is really hard for an end user or even a new developer to understand or discover RAPTOR features/capabilities and configuration unless we have documentation for RAPTOR that I am not aware of?. To document it, we need someone who is familiar with RAPTOR.

**Comment by andre-merzky** [comment]
This is mostly addressed by now.
