### ISSUE TITLE
are path elements of `endpoint://` URLs always absolute paths?

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2699]

**Comment by eirrgang** [comment]
e.g. if `filesystem_endpoint` is a `sftp` URI, isn't the path based at the account's home directory? How, then, does that map to `endpoint:///`? (See also #2700)

**Comment by andre-merzky** [comment]
Depending on the FS endpoint, the *landing* dir may be indeed non-root, for example for an interactive `sftp` session.  For RP, radical.saga will do the translation to absolute path names (where possible).  Point in case:

```sh
$ sftp sftp://localhost/.bashrc /tmp/br
```

would fetch the file from the user's home dir.  but RS would allow this:

```py
import radical.saga as rs
src_dir = rs.filesystem.directory('sftp://localhost')
src_dir.change_dir('/')
scr_dir.copy('.bashrc', 'file://localhost/tmp/br')
```

which would fetch the file from the FS root.

Since `sftp` does not accept the URL as it is anyway, I consider it thus the responsibility of the user or of the application to ensure the correct handling of the default directory.

**Comment by eirrgang** [comment]
> Since sftp does not accept the URL as it is anyway, I consider it thus the responsibility of the user or of the application to ensure the correct handling of the default directory.

Does `endpoint:///` map to `filesystem_endpoint` or to `rs.filesystem.directory(get_resource_fs_url(...)).change_dir('/')`?

**Comment by andre-merzky** [comment]
`endpoint:///` will map, if possible, to the root of the respective file system.

**Comment by eirrgang** [comment]
These are the docstrings that need updates, then.

* https://github.com/radical-cybertools/radical.pilot/blob/7ee42b64270bbbcf3eea23942b4eff7f6cb321d3/src/radical/pilot/utils/misc.py#L160
* https://github.com/radical-cybertools/radical.pilot/blob/7ee42b64270bbbcf3eea23942b4eff7f6cb321d3/src/radical/pilot/staging_directives.py#L148
