### ISSUE TITLE
obtain resource sandbox depending on pilot's project ID w/o session

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2700]

**Comment by eirrgang** [comment]
See, for instance, #2668.

Use case:

Identify a readable/writable path to which data can be staged before submitting the pilot, with a well-defined translation between the available abstractions inside and outside a session. E.g. paths expressed in terms of the 'filesystem_endpoint' field (or other fields in the resource definition) and paths expressed in terms of the "sandbox" properties on RP objects or the URI schemes available to staging directives.

Ultimately,
* allow scripts to be written without hard-coding for specific resources
* allow a data provider abstraction to be conceived of separately from the RP compute provider abstraction. (specify the details needed such that usable paths can be robustly defined programmatically across the RP API boundary)

**Comment by eirrgang** [comment]
Presumably, this is possible in terms of `radical.pilot.utils.misc.get_resource_fs_url`.

I think an acceptable solution to this issue could be generalized beyond, specifically, the resource sandbox. The goal would be to robustly programmatically map the *same path*, *writable by the user*, between "offline" code (presumably based on `get_resource_fs_url()`) and a URI based on `endpoint:///`, `resource:///`, or `session:///` (or `pilot:///` or `task:///`) for use in a Task (such as a raptor Master, Worker, or Python function) or staging directive.

**Comment by andre-merzky** [comment]
It will not be possible to predict the session, pilot and task sandboxes - they can be set by the application at runtime via the session uid and the pilot and task descriptions and are thus not predictable.  To some extend that also holds for the resource and  the fs endpoint, as those are configurable in the resource configs - but its probably prudent to assume that those don't change between invocations.  Either way, I suggest to limit the requested functionality to the fs endpoint and the resource sandbox.

**Comment by eirrgang** [comment]
> It will not be possible to predict the session, pilot and task sandboxes - they can be set by the application at runtime via the session uid and the pilot and task descriptions and are thus not predictable.

It is not necessary to predict path elements that can be either queried or explicitly set. 

> To some extend that also holds for the resource and the fs endpoint, as those are configurable in the resource configs - but its probably prudent to assume that those don't change between invocations.

It is unnecessary to make such an assumption because of the tools in rp.utils.misc.

> Either way, I suggest to limit the requested functionality to the fs endpoint and the resource sandbox.

I'm not sure that I am asking for any functionality, unless it is easier to provide new functionality than to document a recipe in terms of existing functionality.

I don't mean that all possible mappings need to be easily determined. One would suffice.

Several of the URI schemes are already straightforward to define in terms of each other and the (queriable and settable) uids (though the directory structure is not well documented yet).

**Comment by andre-merzky** [comment]
I had a look at this again.  The resource fs root is now provided, but to get the actual resource sandbox outside of the session will not be possible in many cases: we will have to access the remote resource for env variable inspection etc.  For that we would, in turn, need a session, and we would basically re-implement what the pilot launcher does for sandbox creation.

Thus, if you need the actual resource sandbox path, then that has to come from an launched pilot instance as it is determined at launch time.  If that does not help because the use needs to stage data in advance, then the user should determine the staging path on the remote sandbox and make that independent from the RP sandbox locations - those data can always be (cheaply) linked into the sandboxes at runtime if that is of any advantage.

**Comment by eirrgang** [comment]
> an launched pilot instance as it is determined at launch time

It is determined from knowable things, though, right? Like the choice of target resource, the (queriable) resource config/definition, and user-settable `uid`s?

If the sandbox path can be set or asserted, that should be sufficient.

Maybe there is a problem in that the semantics or requirements of the `filesystem_endpoint` are insufficiently strongly specified? Can we start by clarifying that? (in #2588, presumably)

> the user should determine the staging path on the remote sandbox and make that independent from the RP sandbox locations

Yes, that would be fine. What mechanism does RP use to find a remote directory that is writable by the user in order to start the bootstrapping process? Can we use the same mechanism (or the same logic, at least) to find a writable directory and document a programmatic way to identify it in both the task and  pre-Session client environments?

**Comment by andre-merzky** [comment]
> It is determined from knowable things, though, right?

From inspectable things - but we can't do that inspection outside of a session.  For example, on ORNL's Andes, the path is `"default_remote_workdir":  "$MEMBERWORK/%(pd.project)s"`.  We could specify the `project` field of the pilot description manually, but we don't know the current value of `MEMBERWORK` w/o checking on the remote system.

> What mechanism does RP use to find a remote directory that is writable by the user in order to start the bootstrapping process?

Exactly that relevant config entry `default_remote_workdir`.  The same mechanism is what I described above as implemented in the launcher: connecting to the host and resolving the path there.  We need a session to connect.

**Comment by eirrgang** [comment]
> We need a session to connect.

If it can be resolved with a Session, but without a Pilot, that would be a big step forward.

If we can document the logic by which paths are constructed, then an API client could perform the same connection and construct the same path. If the logic is unstable, making the documentation hard to maintain, the least stable parts could be abstracted to API functions over time.

> we don't know the current value of MEMBERWORK w/o checking on the remote system

Is `MEMBERWORK` highly dynamic? Even if it isn't on ORNL, I suppose it is conceptually fair to assume that `default_remote_workdir` might not be knowable without logging in, and might not be consistent between connections. If that is the case, then maybe a single reference path is insufficient in the long run.

For interoperability with non-RP data managers, it may be necessary to add a field (or set of fields) that mean "root data staging target on an appropriate filesystem with appropriate permissions that is accessible to Sessions and robust across connections."

**Comment by andre-merzky** [comment]
> If it can be resolved with a Session, but without a Pilot, that would be a big step forward.

I would like to not implement this, as it needs too much code refactoring and API changes.  The user can choose a valid absolute path on the file system.

> Is MEMBERWORK highly dynamic?

I don't know, but also don't want to replace this with any heuristics.  Also, users are free to use any env variable in the resource config (for that specific setting), so all bets are off anyway.

We do provide the `endpoint_fs` URL which provides an access to the file system - I would like to keep all further details of the file system structure either for the user to determine, or to use the information the pilot detects at runtime.

**Comment by eirrgang** [comment]
> > If it can be resolved with a Session, but without a Pilot, that would be a big step forward.
> 
> I would like to not implement this, as it needs too much code refactoring and API changes.

I misunderstood, then. I thought you were saying it was already possible, once the Session had been created.

> The user can choose a valid absolute path on the file system.

Can you suggest a way for a user (or another module) to express this in a way that is usefully consumable by both RP and an API client author?

> We do provide the `endpoint_fs` URL which provides an access to the file system - I would like to keep all further details of the file system structure either for the user to determine, or to use the information the pilot detects at runtime.

It sounds like you are saying that issue #2700, as described, is a "won't fix"? Maybe it was too specific.

The issue @mturilli and I were trying to open was something along the lines of "find the interface between RP and a data provider/stager so that RP doesn't have to expand its responsibilities," or "as an application programmer, I want to stage data for tasks that I am managing for a user in terms of RP API so that I can avoid idle compute resources with minimal inconvenience for (extra input from) the user."

**Comment by andre-merzky** [comment]
> It sounds like you are saying that issue https://github.com/radical-cybertools/radical.pilot/issues/2700, as described, is a "won't fix"? 

Yes, correct - we can't provide that information before the pilot is launched.

> The issue @mturilli and I were trying to open was something along the lines [...]

Ack, I agree - but we do provide the filesystem URL so the file system is accessible, and the user can use absolute paths - that should address that use case, right?

**Comment by eirrgang** [comment]
> Ack, I agree - but we do provide the filesystem URL so the file system is accessible, and the user can use absolute paths - that should address that use case, right?

Even if the application has to ask the user to provide additional information (an application specific absolute path for data staging), we don't have a general way to use it to manipulate data or derive new paths unless we have a strongly specified way to turn an absolute path into a `endpoint:///` URL.

We could make a two-step goal.
1. Allow an API client to programmatically convert between `endpoint:///<path>` and absolute paths based on a user-provided remote writable absolute base directory path.
2. Allow an API client to programmatically convert between `endpoint:///<path>` and absolute paths based on a path that can be derived with API calls before computing resources (an HPC pilot job) are allocated, without additional user-input than what they would have had to provide anyway for RP.

**Comment by andre-merzky** [comment]
The `endpoint:///<path>` will be an absolute path in the root of the filesystem for the root as specified by the access protocol (the `endpoint_fs` URL).  It is not possible for RP to do a translation to any absolute root or to a root for another access protocol, as we only see / use that one.

But this is really academic - I can't think of a case where that matters.  For all practical purposes the path from `endpoint:///<path>` **is** the absolute path on that system.  I suggest we fix that once it brakes somewhere (because I don't think it will).

**Comment by eirrgang** [comment]
> The `endpoint:///<path>` will be an absolute path in the root of the filesystem for the root as specified by the access protocol (the `endpoint_fs` URL).

Excellent! That's the confirmation/clarification I was looking for.

> It is not possible for RP to do a translation to any absolute root or to a root for another access protocol, as we only see / use that one.

Yes. That's totally fine, I think.

> But this is really academic - I can't think of a case where that matters. For all practical purposes the path from `endpoint:///<path>` **is** the absolute path on that system. I suggest we fix that once it brakes somewhere (because I don't think it will).

It sounds like it, yes. Thank you for clarifying.

**Comment by andre-merzky** [comment]
> Excellent! That's the confirmation/clarification I was looking for.

Great, convergence at last :-)  Ok to close this issue?

**Comment by eirrgang** [comment]
> > Excellent! That's the confirmation/clarification I was looking for.
> 
> Great, convergence at last :-) Ok to close this issue?

I can submit documentation patches, as necessary, for Step 1 (which seems to be essentially resolved).

For "Step 2", should there maybe be a long-term issue to the effect of "establish a data-provider facing facet"? (Note that my questions so far have been based on being able to read RP's configuration information or to anticipate/understand its behavior. It would be equally acceptable to have a clear API for setting RP's configuration and resource definitions. It was previously determined that it was not feasible to programmatically update resource definitions robustly after certain phases of module import or Session launch, but I don't want to be overly/artificially constrained in proposed solutions when documenting the problem to be solved.)

**Comment by andre-merzky** [comment]
> It would be equally acceptable to have a clear API for setting RP's configuration and resource definitions.

I would consider that out of scope for this issue.

**Comment by eirrgang** [comment]
> > It would be equally acceptable to have a clear API for setting RP's configuration and resource definitions.
> 
> I would consider that out of scope for this issue.

I agree. I'm asking whether I should open a separate issue or whether you would like to work out with @mturilli whether to document it (or not) in some other roadmap scheme.

**Comment by andre-merzky** [comment]
Thanks for the new issue - closing this one.
