### ISSUE TITLE
rp.utils docs don't show up 

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2706]

**Comment by eirrgang** [comment]
See also https://github.com/radical-cybertools/radical.utils/issues/359

**Comment by eirrgang** [comment]
Where are they supposed to show up?

**Comment by andre-merzky** [comment]
https://radicalutils.readthedocs.io/en/latest/

**Comment by eirrgang** [comment]
> https://radicalutils.readthedocs.io/en/latest/

rp.utils (aka radical.pilot.utils) is supposed to be distinct from radical.utils, isn't it?

Otherwise, this issue overlaps with / duplicates https://github.com/radical-cybertools/radical.utils/issues/359

**Comment by andre-merzky** [comment]
Ah, sorry, mixed up tickets - I am working on RU docs right now.  Anyway, rp utils also don't show up in readthedocs...
