### ISSUE TITLE
Implement `ranks_per_node`

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2710]
This is required for https://github.com/radical-cybertools/radical.pilot/issues/2543 when the service to run needs to start on all agent nodes

**Comment by mturilli** [comment]
@andre-merzky I think we can/should close this?

**Comment by andre-merzky** [comment]
This is not yet implemented, so probably should remain open.  I am not sure about priority.

**Comment by mtitov** [comment]
close in favor https://github.com/radical-cybertools/radical.pilot/issues/2899
