### ISSUE TITLE
Using rp.misc.util.get_resource_fs_url to construct staging directives or path arguments for Tasks.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2723]
There is not a clean mapping between the `filesystem_endpoint` field (the result of `rp.misc.util.get_resource_fs_url()`) `endpoint:///path` or filesystem paths in Task environments.

- [ ] Are the URLs returned by `rp.misc.util.get_resource_fs_url()` guaranteed to be usable in staging directives? (Or are there schemes that are valid in `filesystem_endpoint` that are not valid in staging directives?)
- [ ] Is there a recipe of RP, RU, or RS commands that can convert all `filesystem_endpoint` URLs into local paths in the target environment (such as for a rp.rpt.Master to construct a path argument for a task)?
- [ ] If `filesystem_endpoint` is _not_ guaranteed to be usable in a staging directive, can we get a RP URL scheme that _is_ identically equal to the `filesystem_endpoint` field that is
    - usable in staging directives, and
    - convertible to a local filesystem path (i.e. `Union[str, pathlib.Path, os.PathLike]`) in the target environment

_Originally posted by @andre-merzky in https://github.com/radical-cybertools/radical.pilot/pull/2718#discussion_r985086698_

> That is because an URL does not have a notion of a relative path.  The need for `cd /` is an artifact of the service which interprets that URL and is outside the scope of what we can define.  We happen to handle it that way because SAGA works that way - but other tools may (and do) work differently.  The exposed URL is, per your use case, expected to be used outside of RP, and I just don't want to make assumptions on how it is used.
>
> For example, using that URL with `curl` or `rsync` does not allow a notion of `cd /`, and there is nothing we can do about it...

**Comment by andre-merzky** [comment]
I would prefer to see a use case which breaks when using `endpoint://` for staging directives before adding more code and documentation trying to achieve the same thing in a different way.

**Comment by eirrgang** [comment]
> I would prefer to see a use case which breaks when using endpoint:// for staging directives before adding more code and documentation trying to achieve the same thing in a different way.

I'm ready to start using `endpoint:///` and `rp.misc.util.get_resource_fs_url()` now. I'll test solutions and elaborate my notes as I go. In terms of additional documentation, I don't think it makes sense to try to contribute anything addressing these use cases before the docs are updated for machconf and the resource config fields.

## Case: A path is known to or determined by the client-side in terms of `filesystem_endpoint`.

Recipe: Construct a URL for use in a staging directive using a path known to be writable (according to the RP config)
1. Inspect the result of `rp.misc.util.get_resource_fs_url()`
2. Based on the URL scheme, connect to the service and determine the relative path to `rs.filesystem.directory(get_resource_fs_url(...)).change_dir('/')` (or equivalent)
3. Prepend the relative path of `filesystem_endpoint` to construct a `endpoint://` URL.

Recipe: Construct a filesystem path for use in a Task argument
1. Hope that an absolute path as determined above uses the same filesystem hierarchy as the Task environment and pass the absolute path.
Alt:
1. Construct an `endpoint://` URL as above.
2. Use an RP COPY or LINK staging directive to a `task://` URL to make the file available in the task's working directory.

## Case: A path is known to the client-side in terms of RP URLs or Task working directories.

Recipe X: Record a reference to a remote object.
* sandbox directories are noted in RP object attributes
* I don't think that there is a utility to "represent as local path if is-local-fsobject", but several of the URL schemes are well defined in terms of sandbox paths and the account's home directory (or `default_workdir`)
* Some inspection of the absolute path and the endpoint URLs may allow construction of a URI in terms of a persistent network service, but RS or other knowledge of the resource may be needed to access the filesystem object in some environments.

**Comment by andre-merzky** [comment]
> ## Case: A path is known to or determined by the client-side in terms of `filesystem_endpoint`.
> 
> **Recipe:** Construct a URL for use in a staging directive using a path known to be writable (according to the RP config)
> 
>     1. Inspect the result of `rp.misc.util.get_resource_fs_url()`
>     2. Based on the URL scheme, connect to the service and determine the relative path to `rs.filesystem.directory(get_resource_fs_url(...)).change_dir('/')` (or equivalent)
>     3. Prepend the relative path of `filesystem_endpoint` to construct a `endpoint://` URL.

URLs  don't have relative paths.  Also, there is nothing to prepend - once you did the `cd /`, you successfully derived `endpoint://`.  

Does that solve case A?


> **Recipe:** Construct a filesystem path for use in a Task argument
> 
>     1. Hope that an absolute path as determined above uses the same filesystem hierarchy as the Task environment and pass the absolute path.

I would wait with documenting any uncertainty about the above being true until we see at least one use case where an absolute path does not resolve for a task.


>     1. Construct an `endpoint://` URL as above.
>     2. Use an RP COPY or LINK staging directive to a `task://` URL to make the file available in the task's working directory.




> ## Case: A path is known to the client-side in terms of RP URLs or Task working directories.
> 
> Recipe X: Record a reference to a remote object.
> 
>     * sandbox directories are noted in RP object attributes
> 
>     * I don't think that there is a utility to "represent as local path if is-local-fsobject", but several of the URL schemes are well defined in terms of sandbox paths and the account's home directory (or `default_workdir`)
> 
>     * Some inspection of the absolute path and the endpoint URLs may allow construction of a URI in terms of a persistent network service, but RS or other knowledge of the resource may be needed to access the filesystem object in some environments.

The sandboxes URLs are all inspectable from pilot and task instances.

**Comment by eirrgang** [comment]
> URLs don't have relative paths. Also, there is nothing to prepend - once you did the cd /, you successfully derived endpoint://.

I am trying to document how a single software component would construct two references to the same object: one in terms of `rs` and `filesystem_endpoint`, and one in terms of `endpoint:///`. A path appended to (or stripped from) `filesystem_endpoint` will (in the general case) need additional path elements before being joined with `endpoint:///`.

> Does that solve case A?

I will test it and update if necessary. I'm not sure yet how hard it is in common resource configs to derive the relative path, for instance.

**Comment by eirrgang** [comment]
Yes, I mean the diff between the two. Presumably there is a rs call for
pwd. I don't think it is worthwhile to consider solutions here without rs,
since that is the most robust way to define `endpoint`

**Comment by eirrgang** [comment]
On Sat, Oct 1, 2022, 16:13 Andre Merzky ***@***.***> wrote:

> 1. Hope that an absolute path as determined above uses the same filesystem hierarchy as the Task environment and pass the absolute path.
>
> I would wait with documenting any uncertainty about the above being true
> until we see at least one use case where an absolute path does not resolve
> for a task.
>

I think that there must be a strong assumption in rp that this is true, at
least in the pilot agent environment, or else other things in RP would
fail. If there are caveats to these mappings due to configuration choices
that would break RP, I would consider that to be an invalid configuration,
and beyond the scope of API documentation or utilities.

I think that maybe I've latched onto a few details that you pointed out, in
the interest of clarity, that are out of the scope of supported (or
supportable) use cases. I will try to be more mindful of that.

Also, if you prefer that i track these use cases in some other medium, on
or off of the rp github site, please let me know. I don't think there is
anything in this issue that is currently actionable by the rp team. (I was
under the impression that it was a topic that there was interest in
tracking, but maybe not as a long lived "Issue".)

**Comment by andre-merzky** [comment]
> Yes, I mean the diff between the two. Presumably there is a rs call for pwd. I don't think it is worthwhile to consider solutions here without rs, since that is the most robust way to define `endpoint`

That call would be [`get_cwd()`](https://radicalsaga.readthedocs.io/en/devel/library/namespace/index.html#radical.saga.namespace.Entry.get_cwd).  Documentation for RS is probably in a worse state than that for RP, but that call should be self-explanatory I hope :-)

**Comment by andre-merzky** [comment]
> I think that maybe I've latched onto a few details that you pointed out, in the interest of clarity, that are out of the scope of supported (or supportable) use cases.

Yeah, sorry if that added to confusion...

Ack on tracking use cases vs. issues: we do have long living open issues, but experience shows that those are not terribly useful, they fall off the radar rather sooner than later.  Issues should be actionable in some way I think, so thanks for being mindful of that.
