### ISSUE TITLE
Unhandled missing dependency: mpi4py under raptor.MPIWorker

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2728]
If `mpi4py` is missing from the raptor worker environment, the job may silently hang.

When I remove `mpi4py` from the `prepare_env` [spec in `raptor.py`](https://github.com/radical-cybertools/radical.pilot/blob/5a63a7f8e04076edfa3e5becf17906aa069f45bf/examples/misc/raptor.py#L151), a ModuleNotFoundError appears in `master.000000.worker.0000.err`, but it does not propagate to the user, and the job hangs indefinitely.

_Originally posted by @eirrgang in https://github.com/radical-cybertools/radical.pilot/issues/2218#issuecomment-1274667214_

To reproduce:
1. Clone the repository.
2. Remove `mpi4py` from [`example/misc/raptor.py`](https://github.com/radical-cybertools/radical.pilot/blob/5a63a7f8e04076edfa3e5becf17906aa069f45bf/examples/misc/raptor.py#L151)
3. Install, or bring up the Docker environment.
    `cd docker; docker compose up --build`
4. Run the `examples/misc/raptor.py` example script. E.g. `docker compose exec -ti -u rp login bash -c ". /home/rp/rp-venv/bin/activate && cd /home/rp/radical.pilot/examples/misc && python raptor.py"`

**Comment by andre-merzky** [comment]
This is basically a duplicate of #2643: the workers will fail in this case, but unless the master is actively checking the worker state, no error notification will happen.  I would like to close this issue in favor of #2643, if that's ok @eirrgang ?

**Comment by eirrgang** [comment]
This seems unrelated to managing tasks, but it makes sense as part of #2643 if the scope there is somewhat broadened. I will close this issue and update the description at #2643.
