### ISSUE TITLE
Formalize the schema for raptor.Master.submit_workers() *descr* parameter.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2731]
The expected fields have been evolving for the dictionary passed as the *descr* argument to `rp.raptor.Master.submit_workers()`. Before the expected and allowed fields in the dictionary evolve further, it would be helpful to define a data structure or type hinting for this aggregate.

I think the RCT TypedDict would suffice, and the subclass docstring would be a good home for the notes currently in the `submit_workers()` docstring.

Also note that *environment* and *pre_exec* are currently optional fields, but are not mentioned in the `submit_workers()` docstring.

**Comment by andre-merzky** [comment]
This will be addressed as part of #2684

**Comment by andre-merzky** [comment]
This is now a proper `TaskDescription` and thus strongly typed.

**Comment by mturilli** [comment]
@eirrgang can we close this?

**Comment by eirrgang** [comment]
It is my understanding that this will be resolved when #2892 is merged. If there are remaining ambiguities, I believe they will be just documentation bugs that can be easily addressed in follow-up.
