### ISSUE TITLE
More helpful errors for bad staging directives.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2732]
Bad staging directives can cause task failures with very little indication of what went wrong.

I specified a task input_staging directive with `'target': 'task://name'` instead of `'target': 'task:///name'` and the error was difficult to discover. Admittedly, `'target': 'name'` accomplishes what I wanted, but I hope we can get a more informative failure mode, in the future.

The malformed staging directive resulted in task failure immediately after creating the task sandbox. The `*.err` files were all empty. The only indication that I could find of a problem was a pair of entries in `agent_0.log`

The first began with

    1665584081.530 : agent.0              : 8036  : 139777009506048 : ERROR    : invalid state: {'_id': 'scalems-rp-master.2a5fdc14-4a38-11ed-92d9-0242ac120005',

followed by the rest of the Task dict.
The next two lines were

    1665584081.530 : agent.0              : 8036  : 139777009506048 : DEBUG    : advance bulk: 1 [True, False, FAILED]
    1665584081.530 : agent.0              : 8036  : 139777009506048 : DEBUG    : final scalems-rp-master.2a5fdc14-4a38-11ed-92d9-0242ac120005 [FAILED]

**Comment by andre-merzky** [comment]
This came up in the context of Airflow integration again.
