### ISSUE TITLE
getting_started_local.py hangs

### ISSUE THREAD

**Issue by danielskatz** [radical-cybertools/radical.pilot#276]
Here's what happens:

(sagenv)dis-dlien-1:examples dsk$ python getting_started_local.py
[Callback]: ComputePilot '53dfeeb71d2f566368b50f02' state changed to Launching.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f04' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f05' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f06' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f07' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f08' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f09' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0a' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0b' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0c' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0d' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0e' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0f' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f10' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f11' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f12' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f13' state changed to PendingInputTransfer.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f04' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f05' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f06' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f07' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f05' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f04' state changed to PendingExecution.
[Callback]: ComputePilot '53dfeeb71d2f566368b50f02' state changed to PendingActive.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f08' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f09' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f06' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f07' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0a' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0b' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f08' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f09' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0c' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0d' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0a' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0b' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0e' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0f' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0c' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0d' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f10' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f11' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0e' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f0f' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f12' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f13' state changed to TransferringInput.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f10' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f11' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f12' state changed to PendingExecution.
[Callback]: ComputeUnit '53dfeeb71d2f566368b50f13' state changed to PendingExecution.

(after this, nothing more happens - I've waited about 10 minutes - then I kill the job)

Here's the traceback:
Traceback (most recent call last):
  File "getting_started_local.py", line 119, in <module>
    umgr.wait_units()
Process InputFileTransferWorker-1:
Process OutputFileTransferWorker-1:
Process OutputFileTransferWorker-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Process InputFileTransferWorker-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PilotLauncherWorker-1:
Traceback (most recent call last):
    self.run()
  File "/Users/dsk/sagenv/lib/python2.7/site-packages/radical.pilot-0.18-py2.7.egg/radical/pilot/controller/input_file_transfer_worker.py", line 79, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    time.sleep(1)
    self.run()
KeyboardInterrupt
  File "/Users/dsk/sagenv/lib/python2.7/site-packages/radical.pilot-0.18-py2.7.egg/radical/pilot/controller/pilot_launcher_worker.py", line 153, in run
    time.sleep(1)
KeyboardInterrupt
    self.run()
  File "/Users/dsk/sagenv/lib/python2.7/site-packages/radical.pilot-0.18-py2.7.egg/radical/pilot/controller/output_file_transfer_worker.py", line 79, in run
    self.run()
  File "/Users/dsk/sagenv/lib/python2.7/site-packages/radical.pilot-0.18-py2.7.egg/radical/pilot/controller/output_file_transfer_worker.py", line 79, in run
    time.sleep(1)
KeyboardInterrupt
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/dsk/sagenv/lib/python2.7/site-packages/radical.pilot-0.18-py2.7.egg/radical/pilot/controller/input_file_transfer_worker.py", line 79, in run
    time.sleep(1)
    time.sleep(1)
KeyboardInterrupt
KeyboardInterrupt
  File "/Users/dsk/sagenv/lib/python2.7/site-packages/radical.pilot-0.18-py2.7.egg/radical/pilot/unit_manager.py", line 535, in wait_units
    time.sleep(1)
KeyboardInterrupt

**Comment by marksantcroos** [comment]
Dan, did you have any luck with later versions of RP or you haven't tried anymore?

**Comment by danielskatz** [comment]
I didn't try again, sorry.

**Comment by andre-merzky** [comment]
No problem, Dan.   The code is now sufficiently different though that we would like to close this ticket, and rather start afresh whenever we can convince you to have another look at RP, if that's ok with you?
Thanks!

**Comment by danielskatz** [comment]
Yes please.

**Comment by marksantcroos** [comment]
Thanks
