### ISSUE TITLE
Update raptor master task example

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2767]
In a conversation with @andre-merzky , we concluded that calling `stop` after `join` doesn't make sense.

https://github.com/radical-cybertools/radical.pilot/blob/27ba881e5258cbcd13fd7d2b2fa96ce41e434e20/examples/misc/raptor_master.py#L314

However, calling `stop` before `join` will signal the master to stop as soon as possible (correct?), and it will not wait for tasks to be submitted from the client side.

It seems like the master task `main` function should probably not call `Master.stop()`, but `Master` could call `self.stop()` with some additional logic to determine when it is appropriate.

**Comment by mturilli** [comment]
@eirrgang can we close this?

**Comment by eirrgang** [comment]
> @eirrgang can we close this?

I believe this will be resolved by merging #2892. I will review #2892 to confirm.
