### ISSUE TITLE
Document integration between RP and Chimbuko (RECUP project)

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2770]
Report here resources to understand how RP was integrated with Chimbuko. Possibly, contact Chris and ask for copy of the presentation and details about where the code can be found.

For reference: https://dl.acm.org/doi/10.1145/3426462.3426465

**Comment by mturilli** [comment]
Convert provided script to a tutorial on using services in RP. Add the tutorial to the tutorials repository and reference it back into the main documentation.

**Comment by mtitov** [comment]
created repo with the corresponding examples - https://github.com/radical-collaboration/chimbuko

**Comment by mturilli** [comment]
Thanks @mtitov , I think we can consider this as DONE now.
