### ISSUE TITLE
Support Polaris at ANL

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2774]
ANL support contact:  Phil Carns. 

Polaris documentation might be partial. Create a configuration file for RP and support execution of MPI tasks.

**Comment by mtitov** [comment]
Sub-tasks
- [ ] Update RADICAL-SAGA Adapter PBSPro: identified options required by Polaris, but missed in the current version of the adapter;
- [ ] Update RP Resource Manager PBSPro: consider same approach as applied for Cobalt (e.g., use env variable `PBS_NODEFILE`);
- [ ] Create resource configuration
