### ISSUE TITLE
Non-trivial adjustments to Python invocation.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2799]
I'm not sure to what extent this is a feature request or a documentation request.

## Summary

For testing and debugging, a single-word value for the resource *python_interpreter* field is not sufficient.

Does this field accept lists or multi-word strings? How does this field interact with the `virtenv*` fields? What would be the best way to fine-tune the invocation of the Python interpreter at various levels of a full raptor execution stack?

## Case 1: Python command line flags

The `-W` and `-X` [flags](https://docs.python.org/3/using/cmdline.html#command-line) can be particularly helpful to evaluate code health or to troubleshoot deployments.

Flags affecting parsing, caching, and "optimization" (explicitly) can be relevant to performance. E.g. `-O`.

## Case 2: Coverage

To get test coverage for subclasses of raptor.Master and raptor.Worker, or for client code that is only executed in a raptor environment, we could use the Python [coverage](https://coverage.readthedocs.io/) package, and stage the XML output files back to the client to be aggregated.

1. Typical invocation uses `coverage` as an entry point instead of `python`.
2. At minimum, the `coverage` entry point requires arguments like `run` before the remaining command line arguments are deferred to the python interpreter.

## Case 3: Module `__main__` entry points

In various use cases, it may be helpful or required to insert module entry points into the command line invocation, following the `runpy` model. E.g. `python -m mpi4py`

In some cases, the effect can be duplicated with an installed entry point scripts, but this is not a general solution. Some tools do not provide such a script, or multiple modules may need to be chained in a specific order. In such cases, though, there are probably still alternatives available from within the scripting interface.

Case 3 in itself is probably not compelling as a feature request, but if there is an existing or preferred way to approach such things in the radical environment (launchers occupying more elements than just `arg[0]`), it would be nice to know.

## Questions

How would a user specify [command line arguments](https://docs.python.org/3/using/cmdline.html#command-line) or a Python interpreter with an unusual name (like `coverage`) for
* Pilot agent interpreters?
* A Task with a *named_env*?
* A (raptor Master) Task without a *named_env*?
* A raptor Worker process (with or without *named_env*) created with `Master.submit_workers()`?

How would these answers be affected by different values of "virtenv_mode", "virtenv", "python_dist", etc?

## See Also

If the features needed already exist, then this is just a documentation issue that could be included under #2588.

**Comment by andre-merzky** [comment]
For the second point (coverage), one could consider to use the following code within the Master:
```py
import coverage

cov = coverage.Coverage()
cov.start()

# .. call your code ..

cov.stop()
cov.save()

cov.html_report()
```

Similarly, the `-W` semantics of the Python interpreter flag can be reproduced with the [`warning module`](https://docs.python.org/3/library/warnings.html).  I am not aware for a similar approach to `-X` as that are flags which are specific to interpreter implementations.  Are there specific `-X` flags you expect to see used?

**Comment by eirrgang** [comment]
As discussed out-of-band, a related feature request could be to allow the `Master.submit_workers` to optionally use or extend `executable` and `arguments` from the worker description, rather than to set them without first checking for existing values.

**Comment by andre-merzky** [comment]
Closing as out of scope (for now)
