### ISSUE TITLE
PEP-440 versioning

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2807]
There is not a way to get a [PEP-440](https://peps.python.org/pep-0440/) compliant version identifier with any of the additional information in `rp.version_detail`.

This makes it difficult to use standard tools to compare the versions RP installations between official (minor) releases.

## Scenario

For most RP bugs, there is not a clear indication of when the bug has been fixed (such as a feature tag or planned release ID noted in the tracked issue, or even an expected new Python attribute). I can regularly check the `devel` branch in CI to discover when a fix has been merged to `devel`, but then I don't have a conditional that I can toggle for whether I expect my test to pass or fail, and I have to update my tests several times as the fix percolates to a tagged release.

## Example

```shell
$ pip install --upgrade --force git+https://github.com/radical-cybertools/radical.pilot.git@devel#egg=radical.pilot
$ radical-stack |grep pilot
  radical.pilot        : 1.20.0-v1.20.0-5-gc577ba7df@devel
```

This doesn't provide me with anything that is programmatically useful.

```python
>>> import radical.pilot as rp
>>> print(rp.version_detail)
1.20.0-v1.20.0-5-gc577ba7df@devel
>>> import packaging.version
>>> packaging.version.parse(rp.version_detail)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rp/rp-venv/lib/python3.9/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/rp/rp-venv/lib/python3.9/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '1.20.0-v1.20.0-5-gc577ba7df@devel'
>>> import pkg_resources
>>> v = pkg_resources.parse_version(rp.version_detail)
/home/rp/rp-venv/lib/python3.9/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.20.0-v1.20.0-5-gc577ba7df@devel is an invalid version and will not be supported in a future release
  warnings.warn(
>>> assert v.release is None
>>> assert v.local is None
>>> v.is_prerelease
False
>>> v.is_postrelease
False
>>> v.is_devrelease
False
```

## Possible fix

Without changing RP policies on annotating prerelease, post-release, or explicit `dev` vs. `release` versions, a version like the above could be PEP-440 normalized as `"1.20.0+5.gc577ba7df"`. Then, at least I could check for a `local` part of the version specifier to see that I am not looking at a pure release version.

```python
>>> packaging.version.parse("1.20.0+5.gc577ba7df").local
'5.gc577ba7df'
```

[`versioningit`](https://versioningit.readthedocs.io/en/stable/configuration.html) allows such version identifiers to be constructed from the git repository history, but allows for easy PEP-440 compliance. (It also provides a few ways to help get the full derived version information into the package metadata, so that it is visible in `pip list` or `importlib.metadata.version`)

A more useful fix would additionally include an update to the versioning policy to mark inter-release patches with prerelease identifiers or post-release dev identifiers.

## Workaround

While `pkg_resources` still supports "best-effort" processing to a LegacyVersion, we can detect non-tagged versions with `v.release is None`.

Otherwise, we could just check the parseability with a `try: packaging.version.parse(rp.version_detail); except packaging.version.InvalidVersion: ...`

These workarounds are, of course, mutually exclusive with an upstream solution. Accordingly, please clearly note in this tracked issue if an updated versioning scheme is to be merged to `devel`.

**Comment by andre-merzky** [comment]
The version of RCT modules is available as:
```
>>> import radical.pilot as rp
>>> rp.version
'1.18.1'
```

Is that what you are looking for?

**Comment by eirrgang** [comment]
> The version of RCT modules is available as:
> 
> ```
> >>> import radical.pilot as rp
> >>> rp.version
> '1.18.1'
> ```
> 
> Is that what you are looking for?

No. I'm looking for something different between, say, the tagged 1.18.1 release and a commit on the devel branch between the 1.18.1 tag and the 1.20.0 release.

If I don't know the exact commit ID in which a bug is fixed (especially _a priori_), I at least need a way to distinguish an installation that definitely doesn't have the bug fix from an installation in which the bug _might_ be fixed.

For example, now that I know that #2807 will be resolved in the next release, I want to be able to write new code against the patched version without breaking tests or compatibility for the current RP release. That leaves me with something like https://github.com/SCALE-MS/scale-ms/pull/285/files#diff-fbf594464d2ee4a6d3c61656cdffc274936647ffecc7c86b8809a072c1c6c22aR189

**Comment by andre-merzky** [comment]
We don't want users to rely on commit hashes really.  Having said that, we changed our release procedure so that after a release `x.y.0`, the `devel` branch (and thus all work branches) will  immediately be bumped to `x.y+1.0`.  That should allow you to parse `rp.version` for the next expected release and thus (hopefully) resolve this issue?

**Comment by eirrgang** [comment]
> We don't want users to rely on commit hashes really.

I don't want to rely on a specific commit hash, either, and I don't intend to. But I would like to be able to use standard version inspection tools to parse RP version strings. I think the PEP-440 guidelines are reasonable and achievable without too much trouble.

> Having said that, we changed our release procedure so that after a release `x.y.0`, the `devel` branch (and thus all work branches) will immediately be bumped to `x.y+1.0`. That should allow you to parse `rp.version` for the next expected release and thus (hopefully) resolve this issue?

That will be a huge help. But it would still be helpful to have a straightforward and canonical way to distinguish between a pre-release installation and an installation from an official tagged release. Do you have a suggestion?

**Comment by andre-merzky** [comment]
> a straightforward and canonical way to distinguish between a pre-release installation and an installation from an official tagged release. Do you have a suggestion?

```sh
$ python3 -c 'import radical.pilot as rp; print(rp.version == rp.version_detail)'
True
```

Those two will always be the same for a released installation.

I get the rationale for PEP440, and we may switch at some point.  I am hesitant to just do it as we have some tooling in place for the current format which I don't have the resources right now to ensure to be able to cope with the switch (needs to be backward compatible).

**Comment by eirrgang** [comment]
> Those two will always be the same for a released installation.

Good to know. Thanks. I'll close this issue, but should a note be added to documentation somewhere?

> I get the rationale for PEP440, and we may switch at some point.

I'll leave it to you to add a "won't fix" tag or "deferred" tag or whatever, if you think it is appropriate.
