### ISSUE TITLE
Output data is not moved back if CU is cancelled

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#281]
For RE use-case existing output data must be moved back to local machine from resource, after CU was cancelled - e.g. cu.cancel() call was performed. With current implementation this is not the case.

**Comment by andre-merzky** [comment]
Quick note that the use case for transfer-on-cancel also popped up in https://github.com/radical-cybertools/ExTASY/issues/221

**Comment by vivek-bala** [comment]
The difference between unit.cancel() (current implementation) and that required for https://github.com/radical-cybertools/ExTASY/issues/221 is that the pilot is Active in the former ?

**Comment by andre-merzky** [comment]
> The difference between unit.cancel() (current implementation) and that required for radical-cybertools/ExTASY#221 is that the pilot is Active in the former ?

Correct.  The *real* solution would be, I think, to add a third level of staging.  We do have unit-level staging, and pilot-level staging.  Adding a resource-level staging would allow for data persistency between pilots and sessions, independent of the pilot lifetime...

**Comment by marksantcroos** [comment]
pilot-level staging == resource-level staging. I guess what you refer to as pilot-level staging is the pilot sandbox staging, which is a special case of pilot-level staging.

**Comment by andre-merzky** [comment]
pilot-level staging != resource-level staging I think -- we don't really have (simple/viable) means to access the pilot sandbox after the pilot is gone -- for example for the next pilot to the same resource...

**Comment by marksantcroos** [comment]
Thats why I said that you refer to the special case only.

**Comment by andre-merzky** [comment]
fair enough...  Let me put it this way: we have no equivalent of `staging://` referring to a persistent location...

**Comment by andre-merzky** [comment]
outdated use case, closing?
