### ISSUE TITLE
RPEX PR Tracking

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2810]
This issue tracks the current open PR on the Parsl repository: https://github.com/Parsl/parsl/pull/2507.

This is ongoing work. The tests on Parsl are failing due to some errors that we need to address on RP level and RPEX level and there might be some related tickets to this PR in RCT.

Update as of 10/19/2023:

This PR is now open again with all of RP new changes on Parsl repo : https://github.com/Parsl/parsl/pull/2923

**Comment by AymenFJA** [comment]
Update: `RPEX` is updated to adapt the changes of RP/RAPTOR and Parsl here: https://github.com/AymenFJA/parsl

Next: add tests required by Parsl.

**Comment by AymenFJA** [comment]
related and maybe blocking: https://github.com/radical-cybertools/radical.pilot/issues/3003

**Comment by AymenFJA** [comment]
Update: We decided to test RPEX against the new work Andre is doing involving removing mongo DB as this will lower the requirements of having to create an pass `MongoDB` credentials to Parsl team, which might be a deal breaker.

This ticket is a byproduct result of testing the `no_db` with RPEX. https://github.com/radical-cybertools/radical.pilot/issues/3021 and ultimately **blocking.**

**Comment by Andrew-S-Rosen** [comment]
Just reaching out to say that this looks super cool! I look forward to trying it out. 😄

**Comment by AymenFJA** [comment]
> Just reaching out to say that this sounds super cool! I look forward to trying it out. 😄

@Andrew-S-Rosen, welcome :), and thanks for your comment. I look forward to you trying it once it is merged with `Parsl`. At the same time, feel free to add any feedback/suggestions, as they would be highly appreciated.

**Comment by benclifford** [comment]
@Andrew-S-Rosen you can, of course, try it from the PR before it's merged!
