### ISSUE TITLE
RAPTOR: raptor master fails with permission denied

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2828]
```
/home/aymen/radical.pilot.sandbox/rrp.xxxx.aymen.019334.0001//pilot.0000//master.000000/master.000000.exec.sh: 40: ./raptor_master.py: Permission denied
```

a workaround is to set `python3` as executable in the `raptor.cfg` master description: 

```
    "master_descr": {
        "named_env"    : "ve_raptor",
        "executable"   : "python3 raptor_master.py"
```
instead of 

```
    "master_descr": {
        "named_env"    : "ve_raptor",
        "executable"   : ./raptor_master.py"
```

```
  radical.gtod         : 1.20.1
  radical.pilot        : 1.22.0-v1.21.0-1-g37f65b858@devel
  radical.saga         : 1.21.0
  radical.utils        : 1.21.0
```

**Comment by andre-merzky** [comment]
What resource are you running on, and what resource label do you use?  I cannot reproduce this yet.

**Comment by AymenFJA** [comment]
> What resource are you running on, and what resource label do you use? I cannot reproduce this yet.

@andre-merzky  this only happens on `ornl.summit_interactive` and the schema is `interactive`

**Comment by mturilli** [comment]
@andre-merzky is this still current after the spring on RAPTOR?

**Comment by andre-merzky** [comment]
I don't know,  but suspect that it is.  It seems to point more to a data staging / permission issue than to a raptor issue.  @AymenFJA ?

**Comment by AymenFJA** [comment]
It is no longer happening closing.
