### ISSUE TITLE
Bootstrap failure should lead to pilot failure

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2849]
See #2845 - that error is fixed now, but (a) the pilot should have gone to failed state, and (b) subsequent runs should be able to re-create the VE or at least warn the user about the inability to recover from the broken ve.

**Comment by mturilli** [comment]
@andre-merzky ping?

**Comment by andre-merzky** [comment]
This is not yet addressed.

**Comment by andre-merzky** [comment]
The main failure mode has been addressed by now - bootstrap failure *will* result in pilot failure.  Thus closing.
