### ISSUE TITLE
Integrate contenerized tutorials into documentation

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2851]
Discuss how 'integration' should happen, e.g., just reference, inclusion, separation of concerns between user guide and tutorials, etc.

**Comment by mtitov** [comment]
Proposal: each RCT repo should keep tutorials **about** its tool, repo with all tutorials will contain references to the corresponding tutorials per tool, and tutorials describing how RCT tools are used (e.g., `parsl-rp`, `ddmd`)

Example:
```
radical.pilot
|__ docs
    |__ tutorials
        |__ rp-base.ipynb
        |__ rp-advanced.ipynb

tutorials
|__ tutorials                # or `src`?
    |__ radical.pilot
        |__ setup.sh         # collect tutorials from a related repo
        |__ environment.yml
    |__ parsl-rp
...
```

**Comment by mturilli** [comment]
Add RP-related tutorials to main documentation and reference back the users to the tutorial repository (as we did in ExaWorks)

**Comment by mtitov** [comment]
Tutorials repo is updated accordingly (https://github.com/radical-cybertools/tutorials/pull/4) and is ready for a proposed approach.

**Comment by mturilli** [comment]
@mtitov can we close this?

**Comment by mtitov** [comment]
Yes. This approach is set and we will follow it. Some improvement will be needed on the side of Tutorials repo (https://github.com/radical-cybertools/tutorials/issues/6), but that is outside of the scope of this ticket.
