### ISSUE TITLE
Sometimes `bootstrap_0_stop` event is not recorded

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2853]
RCT stack:

```
  python               : /home/mturilli/ve/docs/bin/python3
  pythonpath           :
  version              : 3.10.6
  virtualenv           : /home/mturilli/ve/docs

  radical.analytics    : 1.20.1
  radical.entk         : 1.30.0
  radical.gtod         : 1.20.1
  radical.pilot        : 1.22.0-v1.21.0-148-ga004e22d4@devel
  radical.saga         : 1.21.0
  radical.utils        : 1.21.0
```

Apparently, the run exits correctly:

```
$ python het.py het-2048.cfg
new session: [rp.session.mosto.mturilli.019432.0005]                           \
database   : [mongodb://rct-tutorial:****@95.217.193.116:27017/rct-tutorial]  ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   local.localhost        2048 cores     256 gpus           ok
create task manager                                                           ok
submit: ########################################################################
wait  : ########################################################################
	DONE      :  2048
                                                                              ok
closing session rp.session.mosto.mturilli.019432.0005                          \
close task manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                          timeout
                                                                              ok
+ rp.session.mosto.mturilli.019432.0005 (json)
+ pilot.0000 (profiles)
+ pilot.0000 (logfiles)
session lifetime: 888.8s                                                      ok
(docs) mturilli@mosto:~/github/radical.analytics/docs/source/bin$
```

But, the `bootstrap_0_stop` event is missing in `bootstrap_0.prof`:

```
#time,event,comp,thread,uid,state,msg
1678969905.683568,sync_abs,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,mosto:192.168.2.45:1678969905.683568:1678969905.683568:1678969905.683568
1678969905.717970,bootstrap_0_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969906.361555,ve_setup_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969906.502526,ve_activate_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969907.695583,ve_activate_stop,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969907.701869,rp_install_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969927.339136,rp_install_stop,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969927.344361,ve_setup_stop,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969932.811748,bootstrap_0_ok,bootstrap_0,MainThread,pilot.0000,pilot_state,
```

The missing event screws up the calculation of pilot runtime in analytics: `rp.utils.PILOT_DURATIONS_DEBUG['p_agent_runtime']` returns 0. We use that duration to derive the total overheads calculated as the difference between the total time spent running tasks and the time the pilot has been alive.

**Comment by mtitov** [comment]
Just to bring in some additional info, but `prof_utils.py` should be updated accordingly
That could happen if termination comes from a client side (or job is terminated by a batch system), thus "pilot" doesn't finalize on its own (usually the case for `FORK` resource manager, which is used in `local.localhost` resource)

And here is how it is handled in `prof_utils`
https://github.com/radical-cybertools/radical.pilot/blob/52dc44983252410f4d71ae77ab47ff3bc3e2c7d2/src/radical/pilot/utils/prof_utils.py#L901-L912

**Comment by mturilli** [comment]
I guess that is what needs to be investigated?

**Comment by andre-merzky** [comment]
So how exactly did you run the analysis (the code which ultimately stumbled over `rp.utils.PILOT_DURATIONS_DEBUG['p_agent_runtime']`)?

**Comment by mturilli** [comment]
https://github.com/radical-cybertools/radical.analytics/blob/docs/fix/docs/source/duration.ipynb note that, as per my commits, I manually edited session *05 adding the missing entry in the prof file so that the code linked here could work.

**Comment by andre-merzky** [comment]
Thanks, let me try to reproduce this.

**Comment by andre-merzky** [comment]
That notebook runs successfully for me on a clean clone of the repo and data.  Could you please remove `~/.radical/analytics/cache/` to make sure that the data are parsed again?  You may want to remove only the respective sessions from the cache if you want to avoid reparsing of other sessions.

**Comment by mturilli** [comment]
What should we do with this ticket? The fact that for you run cleanly might just indicate that sometimes it does, sometimes it does not. Truncation of events popped up often in our experiments and I think we never really pinned down the issue. Ideas?

**Comment by andre-merzky** [comment]
Not sure - did you give the above steps a try?  The code to recover that specific event is in place, and I would like to see it working before closing this ticket...
