### ISSUE TITLE
Outdated/inconsistent list of states

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2854]
For example, AGENT_EXECUTING is missing at https://github.com/radical-cybertools/radical.pilot/wiki/State-Model-Evolution. 
For the events, `schedule_ok` appears to be the same as `rank_stop`, inconsistent with its description `search for task resources succeeded` at https://github.com/radical-cybertools/radical.pilot/blob/devel/docs/source/events.md#agentschedulingcomponent-component

| AGENT_SCHEDULING | schedule_ok | AGENT_EXECUTING | rank_start | rank_stop |
|------------------|-------------|-----------------|------------|-----------|
|74.564040         | 76.938959   | 74.746904       | 74.852869  | 76.938959 |
|74.564040         | 79.496966   | 75.419437       | 76.838956  | 79.496966 |
|74.564040         | 79.803281   | 74.802605       | 75.299713  | 79.803281 |
|74.564040         | 79.884706   | 76.078326       | 77.578822  | 79.884706 |
|74.564040         | 79.886319   | 74.802605       | 75.187899  | 79.886319 |
| ...              | ...         | ...             | ...        | ...       |
|76.020281         | 874.008991  | 870.822930      | 870.897901 | 874.008991|
|76.020281         | 874.357593  | 865.092948      | 865.167044 | 874.357593|
|74.564040         | 876.502618  | 867.271827      | 867.348970 | 876.502618|
|74.564040         | 876.830234  | 869.627349      | 869.699714 | 876.830234|
|76.020281         | 877.318921  | 869.109047      | 869.174982 | 877.318921|

I am afraid that we will have to check all the states and all the event. We may want to use the sessions created for analytics so to avoid issues with different stacks.

**Comment by mtitov** [comment]
> For the events, schedule_ok appears to be the same as rank_stop, inconsistent with its description search for task resources succeeded

@mturilli something wrong with data, I've checked one of my latest session and it is not like that (and the code is consistent with the description)
```
[matitov@login5.summit pilot.0000]$ grep "schedule_ok" ./*.prof
./agent_scheduling.0000.prof:1678463565.8293118,schedule_ok,agent_scheduling.0000,Thread-1,task.0000,,
[matitov@login5.summit pilot.0000]$ grep "rank_stop" ./*.prof
./agent_staging_output.0000.prof:1678463578.6391289,rank_stop,,MainThread,task.0000,AGENT_EXECUTING,
```

or the point is that these data is not collected correctly?

**Comment by mturilli** [comment]
Good question. As per the other ticket, the run from which I got the data reported above looked successful. It closed 'naturally' and did not report any error. So maybe there is something wrong with the profiler and the timestamps where recorded improperly?

Here the session (*05) from which I derived that table: https://github.com/radical-cybertools/radical.analytics/tree/docs/fix/docs/source/sessions . Here the scripts and the config files (het-2048.cfg used for the session *05) https://github.com/radical-cybertools/radical.analytics/tree/docs/fix/docs/source/bin . If useful, I can provide also the full sandbox.

**Comment by mtitov** [comment]
@mturilli thank you Matteo, this is already useful, so I can say that absolute values for timestamps are different (that what we would expect), then the next step would be to review method/function that generated that relative timestamps (maybe there is an out of sync base timestamp, which is subtracted from other timestamps? -> several base timestamps?)

**Comment by mturilli** [comment]
Thank you for checking. The code that generated that table is gone now and you are right, the values in the profiles are indeed different. Let's close the second part of the ticket then as put it down to an error in my own code. The first part about updating the table of status may still be standing.

**Comment by andre-merzky** [comment]
The figure on https://radicalpilot.readthedocs.io/en/stable/overview.html#module-radical.pilot.states needs updating.

**Comment by mturilli** [comment]
@andre-merzky could you update the figure you indicated as needed? I am going to use it in `internals`.

**Comment by andre-merzky** [comment]
@mturilli : are there actions left to address this ticket?
