### ISSUE TITLE
Record the pilot animation presentation on video

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2856]
Add the video to `presentations/pilot.mp4` in https://radical-cybertools.github.io/.

**Comment by andre-merzky** [comment]
The video exists now, but I am not sure where to upload it.  The `https://radical-cybertools.github.io/` repo has no `presentations` folder nor has the web page a respective section, nor can I find the references `pilot.mp4`.  Any advice?  Thanks!

**Comment by andre-merzky** [comment]
Has been uploaded :-)
