### ISSUE TITLE
Execution is stalled for long time after using radical pilot to run a program on Rivanna cluster

### ISSUE THREAD

**Issue by arupcsedu** [radical-cybertools/radical.pilot#2894]
Hey guys,
I was having this issue for quite some time.

Execution is stalled for more than 10 minutes.
Please check the system information:
(rc_arup) -bash-4.2$radical-stack
  python               : /home/djy8hg/.conda/envs/rc_arup/bin/python3
  pythonpath           : 
  version              : 3.9.16
  virtualenv           : rc_arup
  radical.gtod         : 1.20.0
  radical.pilot        : 1.22.0-v1.4.0-4456-gff2e45f@2835-rivanna
  radical.saga         : 1.23.0-v1.22.0-1-g1e21463@devel
  radical.utils        : 1.21.0

I have checked the status of the PR [https://github.com/radical-cybertools/radical.pilot/pull/2855](https://github.com/radical-cybertools/radical.pilot/pull/2855 )

It seemed, interactive, and ssh testing are pending. Have a look at the below screenshot.
![image](https://user-images.githubusercontent.com/10251226/230632218-2a0c8a67-a057-4bf4-95ac-51173bf6b92f.png)

Attached the sandbox log as well.

[rp.session.udc-ba35-36.djy8hg.019454.0002.zip](https://github.com/radical-cybertools/radical.pilot/files/11179777/rp.session.udc-ba35-36.djy8hg.019454.0002.zip)
[rp.session.udc-ba35-36.djy8hg.019454.0003.zip](https://github.com/radical-cybertools/radical.pilot/files/11179795/rp.session.udc-ba35-36.djy8hg.019454.0003.zip)

**Comment by eirrgang** [comment]
Note that my tests of #2855 involved a more recent version of radical.utils than your radical-stack is reporting (but by now I can't remember why...). Have you tried the devel branch?

**Comment by eirrgang** [comment]
> Note that my tests of #2855 involved a more recent version of radical.utils than your radical-stack is reporting (but by now I can't remember why...). Have you tried the devel branch?

Oops. I was too slow. :-)

**Comment by arupcsedu** [comment]
With the devel branch, I am getting this error, although I added the below code in example/config.json

"uva.rivanna"  : {
        "project"  : null,
        "queue"    : "standard",
        "schema"   : "local",
        "cores"    : 8
    }

Added the resource_uva.json in the config folder as well.

These is the error:

================================================================================
 Getting Started (RP version 1.22.0)                                            
================================================================================
new session: [rp.session.udc-ba35-36.djy8hg.019454.0009]                       \
database   : [mongodb://rct-tutorial:****@95.217.193.116:27017/rct-tutorial]  ok
read config                                                                   ok
--------------------------------------------------------------------------------
submit pilots                                                                   
create pilot manager                                                          ok
submit 1 pilot(s)caught Exception: Resource domain 'uva' is unknown.
--------------------------------------------------------------------------------
finalize                                                                        
closing session rp.session.udc-ba35-36.djy8hg.019454.0009     \
close pilot manager                                                            \
wait for 0 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 13.8s                                                       ok
Traceback (most recent call last):
  File "./09_mpi_tasks.py", line 75, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/djy8hg/.conda/envs/rp/lib/python3.8/site-packages/radical/pilot/pilot_manager.py", line 602, in submit_pilots
    pilot = Pilot(pmgr=self, descr=pd)
  File "/home/djy8hg/.conda/envs/rp/lib/python3.8/site-packages/radical/pilot/pilot.py", line 111, in __init__
    = self._session._get_jsurl           (pilot)
  File "/home/djy8hg/.conda/envs/rp/lib/python3.8/site-packages/radical/pilot/session.py", line 959, in _get_jsurl
    rcfg    = self.get_resource_config(resrc, schema)
  File "/home/djy8hg/.conda/envs/rp/lib/python3.8/site-packages/radical/pilot/session.py", line 652, in get_resource_config
    raise RuntimeError("Resource domain '%s' is unknown." % domain)
RuntimeError: Resource domain 'uva' is unknown.

**Comment by mtitov** [comment]
@arupcsedu sorry for a confusion, Eric meant development branch for `radical.utils` only (but actually that devel updates were released in 1.22), thus you can reinitiate your stack
```
pip uninstall radical.pilot radical.saga radical.utils -y
pip install git+https://github.com/eirrgang/radical.pilot.git@2835-rivanna
```

**Comment by eirrgang** [comment]
> @arupcsedu sorry for a confusion, Eric meant development branch for `radical.utils` only (but actually that devel updates were released in 1.22), thus you can reinitiate your stack
> 
> ```
> pip uninstall radical.pilot radical.saga radical.utils -y
> pip install git+https://github.com/eirrgang/radical.pilot.git@2835-rivanna
> ```

Yes, I'm sorry for contributing confusion. I agree completely with @mtitov

**Comment by arupcsedu** [comment]
@mtitov and @eirrgang, Thank you, guys.

The first update was basically taken by executing the command you shared:
pip install git+https://github.com/eirrgang/radical.pilot.git@2835-rivanna
But I will cross check again and get back to you.

**Comment by arupcsedu** [comment]
Hey Guys,
After updating the devel, the same error. Have a look the logs.

(rp) -bash-4.2$./09_mpi_tasks.py uva.rivanna
================================================================================
 Getting Started (RP version 1.22.0)                                            
================================================================================
new session: [rp.session.udc-ba34-36.djy8hg.019455.0000]                       \
database   : [mongodb://rct-tutorial:****@95.217.193.11
[rp.session.udc-ba34-36.djy8hg.019455.0000_example.zip](https://github.com/radical-cybertools/radical.pilot/files/11182369/rp.session.udc-ba34-36.djy8hg.019455.0000_example.zip)
[rp.session.udc-ba34-36.djy8hg.019455.0000_sandbox.zip](https://github.com/radical-cybertools/radical.pilot/files/11182370/rp.session.udc-ba34-36.djy8hg.019455.0000_sandbox.zip)
6:27017/rct-tutorial]  ok
read config                                                                   ok
--------------------------------------------------------------------------------
submit pilots                                                                   
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   uva.rivanna               8 cores       0 gpus           ok
--------------------------------------------------------------------------------
submit tasks                                                                    
create task manager                                                           ok
create 2 task description(s)
        ..                                                                    ok
submit: ########################################################################
--------------------------------------------------------------------------------
gather results                                                                  
wait  :

**Comment by mtitov** [comment]
hi @arupcsedu , thank you for logs, seems like this issue is related to the race condition in SAGA component, can you please try this SAGA branch `hotfix/slurm_js_jobs`? 

```
pip uninstall radical.saga -y
pip install git+https://github.com/radical-cybertools/radical.saga.git@hotfix/slurm_js_jobs
```

**Comment by arupcsedu** [comment]
Still, I am getting the same.

Let me share a bit more information.
This operation creates a job on rivanna slurm and It is still in Queued state. Have a look the screenshot and logs.
![image](https://user-images.githubusercontent.com/10251226/230987168-3d30fd28-50e5-4c85-be07-93f8b461d13c.png)

================================================================================
 Getting Started (RP version 1.22.0)                                            
================================================================================
new session: [rp.session.udc-ba34-36.djy8hg.019457.0001]                       \
database   : [mongodb://rct-tutorial:****@95.217.193.116:27017/rct-tutorial]  ok
read config                                                                   ok
--------------------------------------------------------------------------------
submit pilots                                                                   
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   uva.rivanna               8 cores       0 gpus           ok
--------------------------------------------------------------------------------
submit tasks                                                                    
create task manager                                                           ok
create 2 task description(s)
        ..                                                                    ok
submit: ########################################################################
--------------------------------------------------------------------------------
gather results                                                                  
wait  : 


[rp.session.udc-ba34-36.djy8hg.019457.0001.zip](https://github.com/radical-cybertools/radical.pilot/files/11193582/rp.session.udc-ba34-36.djy8hg.019457.0001.zip)

I think it is better to wait for getting access to Rivanna for you guys. Do you guys have access, already?

**Comment by andre-merzky** [comment]
closing as outdated
