### ISSUE TITLE
automated mongo deployment

### ISSUE THREAD

**Issue by laszewsk** [radical-cybertools/radical.pilot#2927]
b) I was wondering if the mongodb deployment instructions could be expanded upon. I think you would benefit from a deployment in a container such as docker and singularity.  The native mongodb deployment is at times a bit complex to follow especially when it comes to securing mongo. Although you say others can get an instance from you, it may be worth while if you set up such a deployment via a script or command that is backed into radical.
c) I have done that in the past for my programs and deployed mongo via commandline, but I have not done that recently and uses an outdated version of mongo.

So what I think would be cool is to have either a makefile and config file with

radical-mongo.yaml - that includes some parameters for securing mongo (or not ;-))

and some thing like

make deploy-mongo

deploy-mongo:
	bin/deploy-mongo.sh —config=radical-mongo.yaml

and the script in bin 

bin/deploy-mongo.sh —config=radical-mongo.yaml

**Comment by andre-merzky** [comment]
Hi Gregor - we are in the process of removing the MongoDB dependency.  While it is actively worked on it might still take some weeks to stabilize - but it should arrive soon enough that the proposed won't be necessary I hope...

**Comment by laszewsk** [comment]
I am in high support of this!!!!
I made the mistake you use in the past mongo, but they some time ago changed the license and they do not document nicely how to set it up in a command line environment. I would make the deployment without mongo he default ;-)

**Comment by andre-merzky** [comment]
Indeed it will be the default.  Thanks for the encouraging words :-)  Our target timeline for the switch is June - but we need to do a lot of testing before we can release...  Either way, stay tuned!

**Comment by laszewsk** [comment]
PS: I replaced my mongo depencencies with this:

https://github.com/cloudmesh/yamldb

Its just bare minimum and not as sophisticated as mongo, but this simplified my setup ....

**Comment by andre-merzky** [comment]
closing as outdated
