### ISSUE TITLE
Rivanna Python3.11 is broken

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2958]
We need to move from `python3.11` to `python3.7` on Rivanna as it is broken: 
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.
```

I am preparing a PR to fix this.

**Comment by eirrgang** [comment]
Strange... it was working, wasn't it? Any idea how or when it broke?

**Comment by eirrgang** [comment]
Is there a support ticket open with rivanna administrators?

**Comment by AymenFJA** [comment]
@eirrgang Sorry, I did not see your comments until now. Yes, it was working before. Now, it seems like the `pip` is failing. Yes, there is a ticket with Rivanna's help desk but unfortunately no response so far.

**Comment by AymenFJA** [comment]
I pinged the support again, as no response from them so far.

**Comment by AymenFJA** [comment]
Rivanna updated their Python, so this ticket is no longer required.
