### ISSUE TITLE
Multiple Pilots Being Generated when Running FACTS on Amarel

### ISSUE THREAD

**Issue by AlexReedy** [radical-cybertools/radical.pilot#2965]
Hey all, I've been noting an issue recently where when I am running large configurations of FACTS runs (e.g. nsamples=20000 and nlocations=66190) there will be anywhere from 2-4 pilots created in the sandbox. It looks like some resubmission of the pilot but I am unable to diagnose the cause.

**Comment by mtitov** [comment]
@AlexReedy FACTS uses EnTK, and EnTK has a default number of attempts equal to [3](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/appman/config.json#L3), you can change it with a corresponding parameter here https://github.com/radical-collaboration/facts/blob/main/runFACTS.py#L76 - add `reattempts=1` (parameter `reattempts` actually sets the number of attempts)

**Comment by mtitov** [comment]
(*) New pilots start only if the previous ones failed to complete the execution of a workflow

**Comment by mtitov** [comment]
@AlexReedy Hi Alex, did you decrease the number of attempts as I wrote earlier, or it is not an issue anymore and one pilot completes everything?
