### ISSUE TITLE
Possibility to terminate services

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2967]
How we can control the termination process? - termination command as a part of task description, or special method for service tasks (`task.cancel()`)

p.s. it is needed for Chimbuko app (RECUP project), since some summary/statistics is collected during the termination

**Comment by mtitov** [comment]
@andre-merzky Example of a set of operations to terminate Chimbuko service

```
provdb_addr=$(cat chimbuko/provdb/provider.address)
echo "Provenance DB is on ${provdb_addr}"
pserver_addr=$(cat chimbuko/vars/chimbuko_ad_opts.var | sed 's/.*pserver_addr\s\([^ ]\+\).*/\1/')
echo "Pserver is on ${pserver_addr}"
echo "Shutting down pserver"
pshutdown "${pserver_addr}"
sleep 4
echo "Shutting down provDB"
provdb_shutdown "${provdb_addr}"
```

**Comment by andre-merzky** [comment]
TODO: check if signal forwarding is standardized for OpenMPI / MPICH / MVAPICH

**Comment by mtitov** [comment]
Use case SOMA+RCT:
- SOMA needs to dump monitoring data before the termination (which should be triggered by a corresponding RPC call)

**Comment by mtitov** [comment]
Close in favor https://github.com/radical-cybertools/radical.pilot/issues/3062
