### ISSUE TITLE
Functionality to Select Specific Nodes to Run on

### ISSUE THREAD

**Issue by AlexReedy** [radical-cybertools/radical.pilot#2974]
Wanted to open a ticket for this as per @mturilli request to ask if there was a way to request to pilot be run on a user specified node.

**Comment by mtitov** [comment]
@AlexReedy Alex, can you please expand more on this? Is it related to heterogeneous clusters as Amarel [1]?

[1] https://radicalpilot.readthedocs.io/en/stable/supported/amarel.html#general-description, second "Note" there

**Comment by andre-merzky** [comment]
closed by #3117
