### ISSUE TITLE
Add support for Sunspot@ALCF

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2976]
https://www.alcf.anl.gov/support-center/aurora-sunspot

**Comment by mtitov** [comment]
It is required to have active JLSE Aurora Early HW/SW (Arcticus, Florentia) account

I've submitted "Request for Access to Aurora Early Hardware Nodes" (https://jira.exascaleproject.org/servicedesk/customer/portal/10/ECPUSRPRG-1464)

**Comment by mtitov** [comment]
Following this steps https://www.jlse.anl.gov/accessing-jlse-resources/
(1) waiting for approval (it is in progress)
(2) waiting for approval (it is in progress)
(3) done
(4-8) after 1. and 2.

**Comment by mtitov** [comment]
Currently on step 5 (requested JLSE membership on 10/17, pinged on 10/25)

(*) for records - step 4 was reached only on 10/17

**Comment by andre-merzky** [comment]
got access, home directory problems are being worked on
