### ISSUE TITLE
RAPTOR: raptor_master.py question 

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3003]
In `raptor_master.py` specifically in line https://github.com/radical-cybertools/radical.pilot/blob/10d25ebaf603f4a57ed08a129c310a1ebfb213d5/examples/misc/raptor_master.py#L301 although there is a comment, it is still not clear: 

1. why do we have sleep `60s`? 
2. would that time need to be increased also when we have longer running tasks?
3. is there a better approach besides exposing this directly? 

This issue was raised while @mtitov  and I were discussing this in line with the examples.

**Comment by andre-merzky** [comment]
That sleep is likely a left over from a version where the `submit` call was not blocking and waiting for task completeness, but where it just submitted the tasks.  So yes, the sleep can indeed be removed now.

**Comment by AymenFJA** [comment]
Oh great, happy to do so. I will open a PR with that. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andre-merzky** [comment]
Hmm, that's unexpected.  Let me step through that code to see what's going on...
