### ISSUE TITLE
Startup flag (service URL) for the SOMA service

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3007]
Solution for a specific use case and the general approach will be provided later.

https://github.com/radical-cybertools/radical.pilot/discussions/3006

**Comment by mtitov** [comment]
Proposed approach: https://github.com/radical-cybertools/radical.pilot/compare/devel_nodb_2...feature/service_startup_flag

**Comment by andre-merzky** [comment]
From discussion: 
 - [] remove sub-agents
 - [] place components directly on target nodes
 - [] implement service as special components

first step: implement component for task monitoring
