### ISSUE TITLE
Cleanup NODB branch

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3015]
Cleanup and make it consistent

- [x] Resource configuration handling
(came from this commit https://github.com/radical-cybertools/radical.pilot/pull/2996/commits/348addbe3b28a376befcad6af040ac516a619d29#diff-defb43052dbd7dbe758dae920e512dd810713085d965c42b1162838e1b0165f8)
- [x] `fwd`-parameters, since proxy forwarding happens automatically ([link](https://github.com/radical-cybertools/radical.pilot/blob/devel_nodb_2/src/radical/pilot/session.py#L727))
  - use explicit flag instead of auto-forwarding 
- [x] RP `Bridges` keep hanging after session is closed (same was with `Components`, but it is fixed now)
  - turn on bridge-heartbeats again
- [x] Move file `<session_uid>.reg.json` into client sandbox
- [x] Bring back  `<session_uid>.json` instead of set of files per type (`pilot.0000.json`, `pmgr.0000.json`, `tasks.tmgr.0000.json`, `tmgr.0000.json`)? -> current setup breaks Analytics
  - expand the RP util method for profile-reading
- [x] Excessive log/debug messages
- [x] fix staging tests in GH actions
- [x] Aymen reproduced this outside of GH actions
- [ ] AM to test on some production machine
- [x] Create nodb branch for RE
- [x] Review config organization per components (specifically check config parameters used inside each component, e.g. [Popen fix](https://github.com/radical-cybertools/radical.pilot/pull/3016/commits/02decef861a9181349536714f1f3fc969a87040c#diff-080f40a6cd8ce65ade3f03c538d598f60291df70596b3ffcb45e0cad3e752af4))
- [x] CI - Analytics (e.g., https://github.com/radical-cybertools/radical.pilot/actions/runs/6177496641/job/16768747242?pr=3016)

**Comment by mturilli** [comment]
See also outstanding items at https://github.com/radical-cybertools/radical.pilot/issues/2948
