### ISSUE TITLE
CompBioMed/SEAVEA Hackathon 15 September 2023

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#3025]
https://www.compbiomed-conference.org/compbiomed-seavea-hackathon/

This is a catch all ticket to organize the upcoming hackathon. 
* Define an agenda (2h RCT introduction + SAEVE/CompBioMed-oriented hands on)
* Define the material (slides + RCT tutorials + hands on)
* Define the backend + instructions for the hands on(Docker)

**Comment by andre-merzky** [comment]
- no hybrid mode, but zoom link will be available
 - remote participation best from start time
 - info to Diana 'til Monday
 - no archer needed, but we prepare

**Comment by mturilli** [comment]
[] Create dedicated page at https://github.com/radical-cybertools/tutorials/wiki

**Comment by mturilli** [comment]
@andre-merzky this is now **CRITICAL**. Please upload the tutorials we discussed to the appropriate directory under src in the tutorials repository. Then create a Docker container and push it to our DockerHub with the tag `seavea-hackathon`. I have created our landing wikipage for you at https://github.com/radical-cybertools/tutorials/wiki/CompBioMed-SEAVEA-Hackathon . Please complete the instructions adding the name of the tutorials and some guidance about the exercises.

**Comment by mturilli** [comment]
Write notes in a discussion and discuss on Monday 26
