### ISSUE TITLE
Enforce task env within `exec.sh` script?

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3039]
Should we prepare task environment as we do for launcher environment, but use preserved RP's virtual environment

https://github.com/radical-cybertools/radical.pilot/blob/cf7c159246a45bbec81163facf6bec984e68bb96/src/radical/pilot/agent/executing/popen.py#L642-L644

Thus, if user doesn't provide `named_env`, then we activate RP's env
```python
    ret += '\n# named environment\n'
    if td['named_env']: 
        ...
    else:
        ret += '. $RP_PILOT_SANDBOX/env/rp_named_env.rp.sh\n'
```

**Comment by andre-merzky** [comment]
The first part would make sense (prepare the env).  I would suggest not to fall back to the RP env.  I like that we make the promise that the task runs by default in the virgin environment as found on the nodes when the bootstrapper lands.  That is the least likely env to conflict with user `module load` and `export` directives IMHO.
