### ISSUE TITLE
Add Interactive mode for Summit and Summit JSRUN

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3043]
This is related to Cylon-RP:

The current configuration of `summit` and `summit jsurn` do not expose the interactive mode.

**Comment by mtitov** [comment]
For that we have a separate configuration `summit_interactive` with both MPIRUN and JSRUN LMs (MPIRUN is the 1st in the order)

**Comment by AymenFJA** [comment]
And that is why I missed it as I forgot the challenges that we faced when we tried putting it in a single file. Sorry for the noise.
