### ISSUE TITLE
Review requirement to use only PRIMARY session for Task- and Pilot-Managers

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3047]
Based on the fix for EnTK*:
https://github.com/radical-cybertools/radical.entk/blob/4568f28f7552781b46f06b620df4d078eec62353/src/radical/entk/execman/rp/task_manager.py#L81-L86

Method `_tmgr` is set for `multiprocessing.Process` ([link](https://github.com/radical-cybertools/radical.entk/blob/4568f28f7552781b46f06b620df4d078eec62353/src/radical/entk/execman/rp/task_manager.py#L348))
```python
            session = self._rmgr.session
            self._rmgr._session = None

            self._tmgr_process = mp.Process(target=self._tmgr,
                                            name='task-manager',
                                            args=(self._uid,
                                                  self._rmgr,
                                                  self._zmq_info))
            self._tmgr_process.daemon = True

            self._rmgr._session = session
```

(*) https://github.com/radical-cybertools/radical.entk/pull/654

**Comment by andre-merzky** [comment]
We discussed this in the EnTK context.  At the moment the workaround in EnTK (reset the session type manually) seems well confined and stable, so we agreed not to change the RP level as it would increase complexity and documentation load with little other benefit.  We should revisit this if other, similar issues pop up some day.
