### ISSUE TITLE
Rework service tasks

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3062]
Based on Andre's proposal
> After discussion we plan to implement the following schema
> 
> * services are defined as normal RP tasks (special task type though)
> * service tasks are tagged to a specific pilot instance by setting the `pilot` field in the TD
> * they are submitted via the `tmgr`
> * we introduce a new control message which signals the event that a service task is `ready` (which implies it has reached `AGENT_EXECUTING` state.  That message type will have the `fwd` flag set by default
> * the `tmgr` will collect those events and will issue `ready`-callbacks which are definable on service task types

https://github.com/radical-cybertools/radical.pilot/discussions/3006#discussioncomment-6972640

**Comment by mtitov** [comment]
Should be considered https://github.com/radical-cybertools/radical.pilot/issues/2899 - approach is to use `tags` (exclusive per node)

**Comment by andre-merzky** [comment]
After this set of PRs is merged, we will consider the following branches for PRs/merges to progress on service tasks and related matters:

  - feature/nodb_and_tracer
  - feature/sched_reconfig
  - feature/service_startup
  - feature/zmq_events
  - fix/scheduler

These branches all improve the agent service management, profiling (including tapping into the profiling by those services), and adaptive task scheduling (the scheduler also tapping into the profiles and/or getting data from agent services).
