### ISSUE TITLE
Remove the Bson serlization layer due to mongo remove

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3078]
We added the `bson` serialization layer in our serializer as MongoDB did not like the byte object from dill/pickle. 

As mongo db is removed now we need to remove:

1. https://github.com/radical-cybertools/radical.pilot/blob/617023615d5734309155222e8c6d059c0b788030/src/radical/pilot/pytask.py#L36C16-L36C30
2. https://github.com/radical-cybertools/radical.pilot/blob/617023615d5734309155222e8c6d059c0b788030/src/radical/pilot/pytask.py#L62

**Comment by andre-merzky** [comment]
closing as outdated
