### ISSUE TITLE
Prepare EIS Demo for FACTS

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3084]
This ticket tracks the transformation of the current demo we have for the EIS team of FACTS/RCT here: https://github.com/radical-collaboration/facts/blob/facts_eis/notebooks/EIS_Demo/RCT-FACTS.ipynb into something more sophisticated showing the API of RCT and how to interact with it.

Things to consider when creating the demo:
- Show how RCT can be installed
- Show how RCT can be configured on the EIS.
- Show how RCT/EnTK can be used to build a single pipeline and N pipelines.
- Extract FACTs workflows output and visualize it.
- Visualize RCT data and profiling.

**Comment by andre-merzky** [comment]
Waiting for @AlexReedy for viz pipeline

**Comment by AlexReedy** [comment]
Oh I am very sorry I didn't know this ticket was open. So what is wrong with the current visualization?

**Comment by AymenFJA** [comment]
This is on my table now. We have to think about whether we should run the visualization pipeline as an executable or reconstruct the pipeline in the notebook.

**Comment by AlexReedy** [comment]
@AymenFJA and I met today and we now have a working visualization on EIS, changes pushed to https://github.com/radical-collaboration/facts/tree/facts_eis

**Comment by AymenFJA** [comment]
We updated the demo here: https://github.com/radical-collaboration/facts/blob/facts_eis/notebooks/EIS_Demo/RCT-FACTS.ipynb,

**Comment by mturilli** [comment]
Demo scheduled for Feb 22, 3pm E
