### ISSUE TITLE
Spack package for py-radical-* is old

### ISSUE THREAD

**Issue by BolarinwaSaheed** [radical-cybertools/radical.pilot#3112]
Please update the spack package for `py-radical-*`, currently they are at version _1.20.0_

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-radical-pilot/package.py

**Comment by andre-merzky** [comment]
@BolarinwaSaheed : thanks for the ping, we will take care of it.

**Comment by andre-merzky** [comment]
@mtitov : I would suggest that we clean out the old versions  which still depend on MongoDB - what do you think?

**Comment by mtitov** [comment]
Spack PR https://github.com/spack/spack/pull/41997

**Comment by mtitov** [comment]
The latest version of the RCT stack (1.47) is in the Spack develop-branch
