### ISSUE TITLE
Parsl-RP (RPEX): MPI RP local test hangs on Parsl CI.

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3116]
This is the main ticket: https://github.com/Parsl/parsl/issues/3013

A possible cause is due to the hanging process from RP. This assumption still needs to be confirmed.

Note: A call is proposed today at 11 EST to discuss this issue with Kevin from the Globus team.

**Comment by AymenFJA** [comment]
Update: the test was hanging as the CI test was not set correctly, leading to a missing `mpi4py` was is required by the RP runtime system.

**Comment by andre-merzky** [comment]
> Update: the test was hanging as the CI test env. was not set correctly, leading to a missing `mpi4py` was is required by the RP runtime system.

Why would the test hang instead of fail on a missing `mpi4py` - is that an RP problem?

**Comment by AymenFJA** [comment]
@andre-merzky  Yes, this is related to termination. I am opening a ticket soon regarding termination:

1. If a failure happens on the initialization level of the Master/Worker of RP, RP does not terminate.
2. If a failure happens, leftover processes are generally hanging at least the `rp.agent` labeled process.

**Comment by AymenFJA** [comment]
Closing this in favor of https://github.com/radical-cybertools/radical.pilot/issues/3119
