### ISSUE TITLE
apply DDMD task Descriptions

### ISSUE THREAD

**Issue by okilic1** [radical-cybertools/radical.pilot#3126]

**Comment by okilic1** [comment]
Finished modifying the structure. Currently testing the correctness.

**Comment by okilic1** [comment]
This ticket is related to the following branch: 
https://github.com/radical-cybertools/radical.pilot/tree/project/ddmd3

**Comment by okilic1** [comment]
Testing the mini-apps with the main structure

**Comment by mturilli** [comment]
Descriptions work, collecting data now.
