### ISSUE TITLE
PSIJ number of nodes should be None and not 0

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3201]
PSIJ expects the number of nodes to be None or 1 and not 0. RP sets the number of nodes to 0 by defaults which lead PSIJ to assume that the number of nodes is set and not None. This issue was raised on `UVA Rivanna`

**Comment by mtitov** [comment]
> sets the number of nodes to 0
(*) that is the case for heterogeneous clusters (cores-per-node parameter is unknown)

**Comment by AymenFJA** [comment]
> > sets the number of nodes to 0
> 
> (*) that is the case for heterogeneous clusters (cores-per-node parameter is unknown)

Correct

**Comment by AymenFJA** [comment]
I am closing this ticket as the associated PR is merged.
