### ISSUE TITLE
Task info is not updated properly

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3220]
@andre-merzky we started to have such errors in CI - https://github.com/radical-cybertools/radical.pilot/actions/runs/10497264247/job/29079702311

it seems that it comes from this update (probably some race condition)
https://github.com/radical-cybertools/radical.pilot/blob/7edf7f107dd6b85eb7be1838204aa9efbadd2223/src/radical/pilot/task_manager.py#L383-L384

with this, `tmgr.0000.json` contains the following info about tasks
```
...
    "tasks": {
        "task.000000": {
            "state": "TMGR_STAGING_OUTPUT",
            "type": "task",
            "uid": "task.000000"
        },
        "task.000001": {
            "state": "TMGR_STAGING_OUTPUT",
            "type": "task",
            "uid": "task.000001"
        },
...
```

**Comment by andre-merzky** [comment]
I can reproduce this now.  It indeed only happens with Python3.9 which makes debugging a bit tedious, but I am on it.
