### ISSUE TITLE
RCT version is missed in logs

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3228]
Session logs have `None` for RCT components version
```
1725478538.299 : rp.session.cuda001.amarel.rutgers.edu.ja961.019970.0002 : 24505 : 139655434643264 : INFO     : radical.pilot version: None
1725478538.299 : rp.session.cuda001.amarel.rutgers.edu.ja961.019970.0002 : 24505 : 139655434643264 : INFO     : radical.utils version: None
```

RCT stack version was captured in `env_rp.log` only
```
  radical.gtod         : 1.61.0
  radical.pilot        : 1.62.0
  radical.utils        : 1.61.0
```

**Comment by andre-merzky** [comment]
Yes, `version_detail` is none when installed from an release - and it probably should not be.  radical-cybertools/radical.utils/pull/418 fixes this now.  And  #3229 also fixes this by logging the short version string along with `version_detail`.
