### ISSUE TITLE
RADICAL-Pilot docker instructions are outdated

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3233]
The docker version of Radical-Pilot still mentions `Mongo DB`, which is no longer a requirement for Radical-Pilot.

https://github.com/radical-cybertools/radical.pilot/tree/devel/docker

**Comment by mtitov** [comment]
I would propose to remove the `docker` directory
(and maybe to make an explicit reference to [the tutorials repository](https://github.com/radical-cybertools/tutorials) in the readme file, which uses docker container with RCTs in it)

**Comment by mturilli** [comment]
Agree 100%.

**Comment by AymenFJA** [comment]
Solved in #3235
