### ISSUE TITLE
Wrong Interactive submission documentation 

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3238]
https://radicalpilot.readthedocs.io/en/stable/tutorials/submission.html#Configuring-an-RP-application-for-interactive-submission

```python
pd_init = {'resource'     : 'tacc.frontera',
           'access_schema': 'interactive',
           'runtime'      : 6000,
           'exit_on_error': True,
           'project'      : 'myproject',
           'queue'        : 'normal',
           'cores'        : 4096,
           'gpus'         : 0
          }
```

We should not specify `project` / `queue` in the `PilotDescription` as these parameters are specified via the interactive command resource request or the `sbatch` parameters.

**Comment by mtitov** [comment]
done
