### ISSUE TITLE
Agent task spawning performance

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#341]
Evidence for the need to optimize task time startup:
![541049a420a64132fe7d6fe2](https://cloud.githubusercontent.com/assets/2323492/4218234/cbc0a290-38ef-11e4-8927-a68d7f61433f.png)
The diagram shows 128 short tasks run by one out of 2 available pilots. Note that the pilot never reaches full utilization. A possible interpretation is: "the pilot manages to start ~40 CUs, then the first one seem to die off and the pilot is not keeping up with unit spawning". If confirmed, this is evidence for the need to optimize the time of task spawning within the agent.

**Comment by andre-merzky** [comment]
ping to team MD to reply.

Otherwise the ticket can probably go, as the pilot start time (the specific ticket topic) has mostly been taken care of, and performance / utilization is sufficiently addressed / discussed in other contexts.

**Comment by andre-merzky** [comment]
ping to team MD to reply.

This is the final call before the ticket is closed.  We'll raise the topic during the next pilot call, too.

**Comment by andre-merzky** [comment]
obsolete and superseded...
