### ISSUE TITLE
Radical Pilot on EC2 use-case

### ISSUE THREAD

**Issue by anjaniragothaman** [radical-cybertools/radical.pilot#343]
Radical pilot adapter for EC2 and S3 is required to work for eThread application. Information about the current implementation of eThread application can be found in the bitbucket repository: https://bitbucket.org/anjaniragothaman/e-thread-repo

Information about the data flow can found in Google drive RADICAL share (RADICAL/RADICAL-Cybertools/RADICAL-Pilot/use_cases)

**Comment by oleweidner** [comment]
I think this use-case is history.

**Comment by andre-merzky** [comment]
We still want to fix this at some point - but yes, priority is low, that is why nobody is assigned to the ticket...

**Comment by andre-merzky** [comment]
This is waiting for an active use case to emerge.
