### ISSUE TITLE
overthink coordination service

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#370]
We keep running into firewall issues with mongodb.

I dont know if there was a real process to select mongodb, but I think it is valid to re-do that process or actually do it at some point.

On the face of it, http://couchdb.apache.org/ offers similar functionality, but then with a REST interface, which addresses the firewall issues.

We might link this effort to abstracting away the coordination backend from the implementation.

**Comment by andre-merzky** [comment]
I am closing this as outdated.  Yes, we will rediscuss the role of MongoDB eventually -- but for now it is too deeply ingrained in the control flow to rip it out...
