### ISSUE TITLE
To PEP-8 or not to PEP-8... (and flake integration)

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#402]
No better time to bring this up than a Friday afternoon :-)

**Comment by andre-merzky** [comment]
There is mostly agreement on the coding style by now.  I'll leave this ticket open for flake and pylint integration.

**Comment by andre-merzky** [comment]
Well, no action here for 2 years, and it is not high on the priority list.  Closing now - I'll complain about coding styles on PRs, and would like to encourage pylint / flake usage in your favorite editor / IDE!
