### ISSUE TITLE
reconsider location of temporary files

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#413]
At some point we should give a careful look at the creation of all kinds of files and where we do it, mainly from a performance perspective, but also (not unrelated) from a resource consumption perspective.

**Comment by andre-merzky** [comment]
We do abuse the shared FS, and on large scale runs this is indeed hurting.  Needs fixing eventually.

**Comment by andre-merzky** [comment]
We are continuously improving on this end, but there is no specific actionable item right now - closing.
