### ISSUE TITLE
Fault-tolerance for file transfer

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#435]
Here the use case:
* 2-stages workflow: the output files of stage 1 are the input files for stage 2.
* Stage 2 will fail if not all the output files are not available.
* RP is set to fail if one of the CU of stage 1 fails.
* Late-binding is used on 4+ pilots.
* Input files are staged with the CU.

Upon a failure of input files staging:
```
CPUCount\': 6}'}, {'timestamp': datetime.datetime(2014, 11, 16, 23, 20, 33, 461614), 'logentry': 'Pilot launching failed!'}]
2014:11:16 23:20:52 radical.pilot.MainProcess: [ERROR   ] [u'Creating ComputeUnit sandbox directory sftp://stampede.tacc.utexas.edu/work/02855/mturilli/radical.pilot.sandbox/pilot-5469310520a6417aebb6a803//unit-5469311520a6417aebb6a80a.', u'Transferring input file file://localhost//home/mturilli/AIMES_demo_SC2014/Stage_1_Output/Stage_1_Input_0_3 -> sftp://stampede.tacc.utexas.edu/work/02855/mturilli/radical.pilot.sandbox/pilot-5469310520a6417aebb6a803//unit-5469311520a6417aebb6a80a/Stage_1_Input/Stage_1_Input_0_3']
```
The whole run fails. 

Fault-tolerance would probably involve attempting to transfer the input file up to a certain number of times before deeming the unit failed.

**Comment by andre-merzky** [comment]
closed in favor of #1129
