### ISSUE TITLE
Pilot doesn't get cancelled

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#460]
Maybe there is already a ticket regarding this, but I will open this one just in case. While using master branch I observe the following - workload basically gets finished, but the pilot continues to run until requested wall time expires. I will re-run to provide terminal output, but agent files can be foudn below:

AGENT.LOG:
https://gist.github.com/AntonsT/27ae47bd41d7e65d9d10

AGENT.STDERR:
https://gist.github.com/AntonsT/fa2e78c5607c420a415a

AGENT.STDOUT:
https://gist.github.com/AntonsT/4d50dbfb0d7d9feaf692

**Comment by andre-merzky** [comment]
Hi Antons, 

from the terminal output, I cannot infer that the workload is actually finishing.  The last activity there is the creation of a new unit sandbox, which I would think signals the startup for a new unit.   I don't see the unit arriving on that specific pilot -- but neither do I see any session closing or pilot cancelation attempt in the terminal output log.  Could you provide more details why you think the workload is completed, and why the pilot should finish?

Thanks!

**Comment by andre-merzky** [comment]
pilot cancellation should be cleaned up now.
