### ISSUE TITLE
MongoDB down?

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#467]
I got this error:
radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'mongodb://ec2-184-xx-xx-xxx.compute-1.amazonaws.com:27017/' incorrect?): [Errno 111] Connection refused

What is happening?

**Comment by mturilli** [comment]
Yes, the service is down because the VM on which it runs has its disk full. I am working on this. This is not a problem with radical.pilot so I am going to close this thicket and post this thread to radical-cybertools.
