### ISSUE TITLE
Specify resource tags in the documentation

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#472]
I have been asked why the FQDN of stampede was not working as resource identifier for radical.pilot. 

I looked for pointers at http://radicalpilot.readthedocs.org/en/latest/index.html and I did not find a page where the tags are specified, or how the tags should be found out. Maybe it is there but I failed to catch it, maybe it is mixed up with other information? I used the search box to look for xsede.stampede and it returned no hits, even if that tag is indeed used in some examples.

Would the page http://radicalpilot.readthedocs.org/en/latest/resources.html be the right place where to document the tag to be used for each resource? More in general, would be supporting both tags and FQDN be a good and viable idea?

**Comment by andre-merzky** [comment]
Hi Matteo, 

 http://radicalpilot.readthedocs.org/en/latest/resources.html is exactly where the tags are documented -- but (a) the tags were wrong, and (b) it seems not obvious that the resource names used there are the tags...  I fixed (a), let me think of a way to make (b) clearer...

**Comment by andre-merzky** [comment]
I applied some reformatting to that page -- is that clearer?  If you have any opinion on ho to further improve the page, please let us know (or feel free to do so in the readthedocs branch :)

**Comment by marksantcroos** [comment]
> but (a) the tags were wrong,  ....  I fixed (a)

Hmmm,

Didn't we fix that one recently already?

Did it broke again or was that in a different branch or so?

**Comment by andre-merzky** [comment]
Yeah, I also though we had fixed that, but could not find it anymore.  Me misremembering was the obvious answer to that, but if you also have some recollection *shrug*.  I guess we'll find out in one of our merges... :P

**Comment by marksantcroos** [comment]
See #438 and 54557bf. 0b3da4f broke it again.

**Comment by andre-merzky** [comment]
Yes, seems like this is what happened :(  Thanks!
