### ISSUE TITLE
bg/q larger allocations have different llq output

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#476]
Currently we use two fields of `llq -l $ID` to build our slots table:
```
BG Shape Allocated: 1x1x1x1
BG Node Board List: N/A
```
For allocations that are of Midplane size and larger, this format is not usable however.

By cursory inspection, it probably needs to be extended to also consider the following fields:
```
BG Midplane List: R00-M1
BG Size Allocated: 512
```

We can probably "switch" the logic over the size of the block.
```
BG Size Allocated: 512
```

My assumption is that for larger blocks, the midplane list will get expanded, and as only power of 2 allocations exist, thats it.

**Comment by andre-merzky** [comment]
Mark, is this still relevant?
