### ISSUE TITLE
cu.state_history has two StagingOutput states

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#477]
Printout of cu.state_history gives:
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 47, 716000), 'state': u'New'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 49, 491000), 'state': u'StagingInput'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 51, 301000), 'state': u'PendingExecution'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 50, 689000), 'state': u'Scheduling'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 50, 815000), 'state': u'Executing'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 55, 238000), 'state': u'StagingOutput'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 54, 171000), 'state': u'StagingOutput'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 25, 56, 360000), 'state': u'Done'}

**Comment by andre-merzky** [comment]
Thanks Antons!  Would you mind adding the CU description, so that we can try to reproduce the problem?  Thanks!

**Comment by AntonsT** [comment]
Sure Andre,

CU description is: <class 'radical.pilot.compute_unit_description.ComputeUnitDescription'> {'kernel': None, 'executable': '/opt/apps/intel13/mvapich2_1_9/amber/12.0/bin/sander.MPI', 'name': None, 'restartable': False, 'output_staging': [{'action': 'Transfer', 'source': 'ala10_remd_3_0.rst', 'flags': ['CreateParents', 'SkipFailed'], 'target': 'ala10_remd_3_0.rst', 'priority': 0}], 'stdout': None, 'pre_exec': ['module load TACC', 'module load amber/12.0'], 'mpi': True, 'environment': None, 'cleanup': False, 'arguments': ['-O', '-i ', 'ala10_remd_3_0.mdin', '-o ', 'ala10_remd_3_0.mdout', '-p ', '/work/02457/antontre/radical.pilot.sandbox/pilot-54c2a4e923769c06a39ba023/unit-54c2a4ed23769c06a39ba025/ala10.prmtop', '-c ', '/work/02457/antontre/radical.pilot.sandbox/pilot-54c2a4e923769c06a39ba023/unit-54c2a4ed23769c06a39ba025/ala10_minimized.inpcrd', '-r ', 'ala10_remd_3_0.rst', '-x ', 'ala10_remd_3_0.mdcrd', '-inf ', 'ala10_remd_3_0.mdinfo'], 'stderr': None, 'cores': 1, 'post_exec': None, 'input_staging': [{'action': 'Transfer', 'source': 'ala10_remd_3_0.mdin', 'flags': ['CreateParents', 'SkipFailed'], 'target': 'ala10_remd_3_0.mdin', 'priority': 0}, {'action': 'Transfer', 'source': '/experiments/treikalis/re-profiling/RepEx/examples/amber/amber_pattern_b_2d/amber_inp/ala10_chir.dat', 'flags': ['CreateParents', 'SkipFailed'], 'target': 'ala10_chir.dat', 'priority': 0}]}
CU timings by state: 
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 12, 772000), 'state': u'New'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 12, 882000), 'state': u'StagingInput'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 17, 478000), 'state': u'PendingExecution'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 17, 189000), 'state': u'Scheduling'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 17, 332000), 'state': u'Executing'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 23, 176000), 'state': u'StagingOutput'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 22, 268000), 'state': u'StagingOutput'}
{'timestamp': datetime.datetime(2015, 1, 23, 19, 47, 25, 139000), 'state': u'Done'}

Thanks,
Antons

**Comment by andre-merzky** [comment]
This has been reproduced.  A workaround is in `get_session_frames()` which re-interprets the entries (and does some other heuristics to get state history right).  A proper fix will be forthcoming with the client refactoring -- I'll thus close this issue.  Sorry for not having a proper fix straight away, but I am worried that removing the bogus entry (the first one) will trip some internal state checks...
