### ISSUE TITLE
User-specified MongoDB databases are not used by RP

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#480]
Master branch.

Case: the MongoDB server and database are specified in a variable like as `mongodb://54.221.194.147:24242/my_own_db`. The database  `my_own_db` is created by the session is stored under `radicalpilot`.

**Comment by mturilli** [comment]
This has not been fixed in 0.28. Every session is recorded under radicalpilot irrespectively of the DB indicated by the user.

**Comment by andre-merzky** [comment]
Damned, I distinctly remember that I patched that before -- no idea where that commit went...  Anyway, spilled milk, d316ab5 addresses this now in the current devel.
