### ISSUE TITLE
pid in data_frame is always unique

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#482]
Tested with several multi-pilot sessions:
```
session = '54c5f19923769c5acc554c11'
session_frame, pilot_frame, unit_frame = rpu.get_session_frames(db,session,cachedir)

pilot_frame[['Active','pid']]
     Active                       pid
0       NaN  54c5f23723769c5acc554c14
1   239.513  54c5f23a23769c5acc554c15
2  3414.501  54c5f23123769c5acc554c13

unit_frame['pid'].value_counts()
54c5f23123769c5acc554c13    2048
dtype: int64

unit_frame['uid'].value_counts()
54c5f28723769c5acc5552bd    1
...
54c5f25323769c5acc554e15    1
Length: 2048, dtype: int64
```

**Comment by andre-merzky** [comment]
I am not sure I understand -- the pilot ID (pid) is *supposed* to be unique for each pilot -- but multiple units can be assigned to the same pilot (ie the same pid).  What am I missing?

**Comment by marksantcroos** [comment]
> What am I missing?

Probably the 4th word in his message :)

**Comment by andre-merzky** [comment]
Sorry, but you need a bigger hammer to make the point...  'multi-pilot' will result in unique pid's for each pilot.  That is what the data frame shows, right?

```
pilot_frame[['Active','pid']]
     Active                       pid
0       NaN  54c5f23723769c5acc554c14
1   239.513  54c5f23a23769c5acc554c15
2  3414.501  54c5f23123769c5acc554c13
```

* pilot `0` with pid `54c5f23723769c5acc554c14` never came online
* pilot `1` with pid `54c5f23a23769c5acc554c15` came online after 240 seconds
* pilot `2` with pid `54c5f23a23769c5acc554c13` came online after 3415 seconds

HELP!  Bigger hammer please!

**Comment by marksantcroos** [comment]
Ah, I thought he was saying he saw only one pid (and I didnt actually look at the data).

In this case I dont understand it either :-)

**Comment by mturilli** [comment]
And the second DF command :) (Nasty?) jokes apart, apologies if the message was too succinct. As you can see from:
```
pilot_frame[['Active','pid']]
     Active                       pid
0       NaN  54c5f23723769c5acc554c14
1   239.513  54c5f23a23769c5acc554c15
2  3414.501  54c5f23123769c5acc554c13
```
In this specific session we have 2 pilots out of three that managed to get active during the execution of the given workload `54c5f23a23769c5acc554c15` and `54c5f23123769c5acc554c13`. In the following command:
```
unit_frame['pid'].value_counts()
54c5f23123769c5acc554c13    2048
dtype: int64
```
I filter the column 'pid' so to get a list of the values with >= repetitions in the column. The list is printed with a bit of metadata and it tells me that the value `54c5f23123769c5acc554c13` repeats 2048 times, i.e. for all the units as confirmed by the last C&Ped command showing - among other information - that we have a total of 2048 units. Therefore, all the units in the unit_DF have the uid set to `54c5f23123769c5acc554c13`. This is in contraction with knowing that two pilots have become active and a certain number of units (that I forgot to C&P here but that I look into) have been executed on `54c5f23a23769c5acc554c15` and another number of units have been instead executed on `54c5f23123769c5acc554c13`.

The command `unit_frame['pid'].value_counts()` should return something like:
```
54c5f23a23769c5acc554c15    700
54c5f23123769c5acc554c13    1348
```
Hope this clarify the issue a bit but please let me know whether I should specify the issue even further with longer listing of C&Ped commands.

**Comment by mturilli** [comment]
Just check the ticket online, s/uid/pid/ has been done but it is not
mirrored in the e-mail...

On Thu, Jan 29, 2015 at 5:13 PM, Mark Santcroos <notifications@github.com>
wrote:

> Ah, I thought he was saying he saw only one pid (and I didnt actually look
> at the data).
>
> In this case I dont understand it either :-)
>
> > On 29 Jan 2015, at 17:10 , Andre Merzky <notifications@github.com>
> wrote:
> >
> > Sorry, but you need a bigger hammer to make the point... 'multi-pilot'
> will result in unique pid's for each pilot. That is what the data frame
> shows, right?
> >
> > pilot_frame[['Active','pid']]
> > Active pid
> > 0 NaN 54c5f23723769c5acc554c14
> > 1 239.513 54c5f23a23769c5acc554c15
> > 2 3414.501 54c5f23123769c5acc554c13
> >
> > • pilot 0 with pid 54c5f23723769c5acc554c14 never came online
> > • pilot 1 with pid 54c5f23a23769c5acc554c15 came online after 240
> seconds
> > • pilot 2 with pid 54c5f23a23769c5acc554c13 came online after 3415
> seconds
> > HELP! Bigger hammer please!
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radical-cybertools/radical.pilot/issues/482#issuecomment-72052107>
> .
>



-- 
Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
Thanks, much clearer now, and fix is pushed!

**Comment by mturilli** [comment]
I am afraid now pid is always None:
```
>>> import os
>>> import radical.pilot.utils as rpu
>>> import pandas as pd
>>> pd.set_option('display.width', 1000)
>>> cachedir = os.getcwd()
>>> db = 'mongodb://54.221.194.147:24242/mturilli_aimesexperiments'
>>> session = '54cb289c23769c551f61de49'
>>> s_frame, p_frame, u_frame = rpu.get_session_frames(db,session,cachedir)
>>> 
>>> p_frame
    Active  Canceled  Done Failed  Launching   New Pending  PendingActive  PendingLaunch  cores  finished  n_units                       pid        resource  runtime                       sid  started
0      NaN       NaN  None   None      3.243  None    None         29.498          3.208      3       NaN        0  54cb289d23769c551f61de4b  xsede.stampede       56  54cb289c23769c551f61de49      NaN
1   87.975  1909.663  None   None     34.987  None    None         40.248         16.645      3  1909.663        5  54cb28a123769c551f61de4d  xsede.trestles       56  54cb289c23769c551f61de49   87.975
2  217.507  1909.907  None   None     29.500  None    None         34.985          4.247      3  1909.907        3  54cb289f23769c551f61de4c    xsede.gordon       56  54cb289c23769c551f61de49  217.507
>>> u_frame
  Canceled      Done  Executing Failed     New Pending  PendingExecution PendingInputStaging PendingOutputStaging  Scheduling  StagingInput  StagingOutput Unscheduled  cores  finished   pid                       sid   started                       uid
0     None  1001.547     91.929   None  16.764    None            91.644                None                 None      91.838        88.066        992.840        None      1   992.840  None  54cb289c23769c551f61de49    91.929  54cb28ad23769c551f61de51
1     None  1001.650     93.397   None  16.763    None            92.944                None                 None      93.309        88.131        994.178        None      1   994.178  None  54cb289c23769c551f61de49    93.397  54cb28ad23769c551f61de50
2     None  1002.691     93.662   None  16.772    None            93.048                None                 None      93.544        91.646        999.093        None      1   994.413  None  54cb289c23769c551f61de49    93.662  54cb28ad23769c551f61de53
3     None  1126.229    221.501   None  16.768    None           220.763                None                 None     221.372       217.628       1122.117        None      1  1122.117  None  54cb289c23769c551f61de49   221.501  54cb28ad23769c551f61de52
4     None  1126.333    222.999   None  16.775    None           222.369                None                 None     222.843       217.639       1123.556        None      1  1123.556  None  54cb289c23769c551f61de49   222.999  54cb28ad23769c551f61de55
5     None  1126.437    223.291   None  16.774    None           222.472                None                 None     223.078       220.765       1124.527        None      1  1123.792  None  54cb289c23769c551f61de49   223.291  54cb28ad23769c551f61de54
6     None  1907.313   1002.892   None  16.777    None          1002.702                None                 None    1002.783       992.923       1903.710        None      1  1903.709  None  54cb289c23769c551f61de49  1002.892  54cb28ad23769c551f61de56
7     None  1908.984   1003.157   None  16.761    None          1002.807                None                 None    1003.020       994.262       1903.945        None      1  1903.945  None  54cb289c23769c551f61de49  1003.157  54cb28ad23769c551f61de4f
```

**Comment by mturilli** [comment]
Please note also that in the unit frame, the value of finished is set to when StagingOutput begins. This is inconsistent with how 'finished' is used in the pilot frame. I think finished should be set to the final state reached by the element. For example, in the case of a unit, its 'finished' value should be set either to FAIL/CENCEL/DONE, depending on which final state it reached.

**Comment by andre-merzky** [comment]
This has been iterated out-of-band, and the date frames should be complete now.
