### ISSUE TITLE
new bootstrapper logic seems to have lost robustness

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#484]
I.e. dependencies not explicitly installed, no specific pip fallback, etc.

**Comment by andre-merzky** [comment]
Hi Mark -- happy to fix this, but can you please be more specific?  Which dependency is not installed, in which case (create/update, agent from pypi / staged)?   There are some things installed via easy_install, and rp falls back to easy_install, too -- you want fallbacks for the other pip's as well then?  I was rather inclined to try to get rid of the easy_install fallback :P  So, where is pip failing?  Do we there need easy_install for all packages?

**Comment by marksantcroos** [comment]
Well, it was there for a reason.

I've created this ticket because I dont have the time and energy to dive into that again now.

**Comment by andre-merzky** [comment]
You should not need to spend time.  If you give me the context (machine and mode), I'll take care of it...

**Comment by andre-merzky** [comment]
Mark -- since I am working on the bootstrapper, I would like to make sure this is addressed.  Could you provide some details, please?  Thanks!

**Comment by marksantcroos** [comment]
Will create separate tickets for them.
