### ISSUE TITLE
improve opening blurb

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#486]
"As I was preparing material for the tutorial, I realized we should update our opening blurb about
Pilot-Jobs
    http://radical-cybertools.github.io/radical-pilot/index.html

To be discussed."

**Comment by andre-merzky** [comment]
Shantenu, can you look if this looks ok right now?

**Comment by andre-merzky** [comment]
@shantenujha ping

**Comment by andre-merzky** [comment]
outdated.
