### ISSUE TITLE
radicalpilot-stats assumes default database name

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#487]
If session is created with non-default database name, radicalpilot-stats can't find it. 'radicalpilot-stats -m help' does not display any info on how to pass database name. In addition, documentation would contribute form a sentence on how to create a session so that it can be accessed with radicalpilot-stats. Currently knowledge of this is somewhat assumed.

**Comment by marksantcroos** [comment]
Actually it gets the non-default database name from the same environment variable that was used to generate the session.
That's not perfect of course.

+1 on the documentation.

**Comment by andre-merzky** [comment]
This tool is obsolete.
