### ISSUE TITLE
files in current directory not accepted as "./(filename)" by staging directives

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#488]
```
[Callback]: ComputePilot '54e6649a2330e023f2a70886' state changed to Launching.
An error occurred: copy from file://./penta.crd to sftp://stampede.tacc.utexas.edu/work/02734/vivek91/radical.pilot.sandbox/pilot-54e6649a2330e023f2a70886/staging_area/penta.crd is not supported (/home/vivek/Research/data_test/local/lib/python2.7/site-packages/saga_python-0.25-py2.7.egg/saga/adaptors/shell/shell_file.py +561 (copy)  :  % (src, tgt)))

```

**Comment by marksantcroos** [comment]
Do you need to be able to specify it like that?
We might be able to solve this, but generally its best to keep your url's as simple as possible.

**Comment by vivek-bala** [comment]
Hmmm I think so.. the files are detected when not using directives (input_staging = ['./file.dat']).

Consider a list , files = ['file1.dat','/home/user/file2.dat'] (files in different directories). That forces me to add os.getcwd() to file1.dat and not the second file. I think this if-else situation could be addressed in the lower layers and allow usage of './file1.dat'. What do you think ?

**Comment by marksantcroos** [comment]
Hmmm, then I might have misunderstood your statement.

Do you specify "file.dat" or "./file.dat"?

**Comment by marksantcroos** [comment]
Btw, looking at the implementation I also dont understand why a dict would be treated differently than a string in this case.
Can you paste your staging dict here?

**Comment by marksantcroos** [comment]
ps. I agree that this should work :)

**Comment by vivek-bala** [comment]
I am using './file.dat' format for which I have to do something like the following (probably shouldn't have brought in 'file.dat')
```
list_of_files = ['./mdshort.in',
                     './min.in',
                     './penta.crd',
                     './penta.top',
                     '%s/../../Analyzer/CoCo/postexec.py'%curdir
                      ]

    for item in list_of_files:
        if item.startswith('.'):
            dict = {
                'source': 'file://%s/%s'%(os.getcwd(),os.path.basename(item)),
                'target': "%s%s" % (MY_STAGING_AREA,os.path.basename(item)),
                'action': radical.pilot.TRANSFER
                }
        else:
            dict = {
                'source': 'file://%s'%(item),
                'target': "%s%s" % (MY_STAGING_AREA,os.path.basename(item)),
                'action': radical.pilot.TRANSFER
                }
        sd_pilot.append(dict)

    pilot.stage_in(sd_pilot)
```

**Comment by marksantcroos** [comment]
> I am using './file.dat' format for which I have to do something like the following (probably shouldn't have brought in 'file.dat')

Ah ok, that explains.

> 'source': 'file://%s/%s'%(os.getcwd(),os.path.basename(item)),

How exact is this code to what you really have?

A possible explanation could be that a URL is defined as: `schema://host[:port]/path`.
If you end up with something like: `file://./data`, then `.` is the host, which would be in accordance with the error you posted.

If you are putting in a correct url though, then we need to see where it gets mangled.

**Comment by vivek-bala** [comment]
```'source': 'file://%s/%s'%(os.getcwd(),os.path.basename(item))``` translates to ```'source':'file:///home/vivek/mdshort.in'``` which works fine.

But if I didn't have an if condition to deal with filename='./mdshort.in', ```'source': 'file://%s'%(item) ``` translates to ```'source':'file://./mdshort.in```.

**Comment by marksantcroos** [comment]
> But if I didn't have an if condition to deal with filename='./mdshort.in', 'source': 'file://%s'%(item) translates to 'source':'file://./mdshort.in which fails with the original error.

That is correct, and there is also not much we can/should do about that. URLs are quite well specified. You dont want bottom layers to start guessing what you mean.

If you want, you can construct your URLs using the Url class:
```
u = radical.pilot.Url()
u.schema = 'file'
u.path = '/home/vivek/mdshort.in'
```

**Comment by andre-merzky** [comment]
`'source': 'file://%s'%(item)`
could be changed to
`'source': 'file:///%s'%(item)`
to handle the `./` case -- but Marks proposal to use the URL class is cleaner (but also more lines).

**Comment by vivek-bala** [comment]
``` 'source': 'file:///%s'%(item)``` didn't seem to work. 

An error occurred: file copy failed: mput  "/penta.crd" "/work/02734/vivek91/radical.pilot.sandbox/pilot-54e7db182330e061995b5cc5/staging_area/penta.crd"

Either way, I guess such filename cases need to be handled in the top layers. So will make the changes thanks.
