### ISSUE TITLE
simultaneous staging of an output and transfer to local machine creates a "staging:" folder on local machine

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#490]
In the staging shared data example : https://github.com/radical-cybertools/radical.pilot/blob/readthedocs/examples/io_staging_shared.py.

Along with transfering the result back to the local machine, I also need to copy/link it to the staging area. So I create a directive and add to the output_staging list as follows :-

```
            out_stage = {   'source': output_file,
                        'target': '%s%s'%(MY_STAGING_AREA,output_file),
                        'action': radical.pilot.LINK
                        }


            # Actual task description.
            # Concatenate the shared input and the task specific input.
            cud = radical.pilot.ComputeUnitDescription()
            cud.executable = '/bin/bash'
            cud.arguments = ['-c', 'cat %s %s > %s' %
                             (SHARED_INPUT_FILE, input_file, output_file)]
            cud.cores = 1
            cud.input_staging = [sd_shared, input_file]
            cud.output_staging = [output_file,out_stage]

            compute_unit_descs.append(cud)
```

The output_file is copied/linked to the staging area as well as transferred to the local machine. But in addition there is a folder created in the local machine called 'staging:' in which another copy of the output file is present.

**Comment by marksantcroos** [comment]
Hi Vivek,

Good catch!

Fixed in devel.
Will do some more tests and backport it to master also.

Thanks

Mark

**Comment by marksantcroos** [comment]
Now in master too. As soon as somebody deems a RP release useful this will hit pypi.
