### ISSUE TITLE
staging directive to download a hosted file ?

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#491]
For files which are hosted, like the lsdmap-reweighting file (https://raw.githubusercontent.com/jp43/lsdmap/master/dmdmd/reweighting.py), does it make sense to have a directive to be able to directly download it ? (a "download" action operator ?)

**Comment by marksantcroos** [comment]
This should be covered by "COPY" in theory.
Didn't try it though, so it might not work currently, but in principle it will.
Will look at it.

**Comment by vivek-bala** [comment]
Oh ok, I didn't try it with 'copy'. I'll give it a try.

**Comment by vivek-bala** [comment]
Nope, it does not fail but also does not download the file.

**Comment by marksantcroos** [comment]
Yeah, just checked the code, that will not work currently indeed.
Its designed to work like that though, so let me take a crack at implementing it.

**Comment by marksantcroos** [comment]
Ok, I investigated this a bit more.

There are two scenario's:

1. Download a "shared" file to be used by "all" CUs. This has to be done by the agent. This requires an extension of both the agent and the pilot staging method.
2. Download a file per CU. This is relatively straightforward, and only impacts the input staging part of the agent.

Note that I dont expect either of these two functionalities to be cherry-picked back, so dont hold your breath for this.

**Comment by andre-merzky** [comment]
This is closed with  #526
