### ISSUE TITLE
What is SAGA-Pilot?

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#492]
While reading the introduction to RADICAL-Pilot, I came across the term "SAGA-Pilot". This is confusing me because I don't know exactly what this term is referring to. I found the term in Section 1 of the documentation here: http://radicalpilot.readthedocs.org/en/latest/intro.html

**Comment by andre-merzky** [comment]
SAGA-Pilot is the old name for RP, which is not in use anymore since... ages.  The one you point to seems to have slipped through our regex-filter (it spans two lines... :P) -- it is now fixed in git, and will hit the published docs in some minutes.  Thanks!

**Comment by AntonsT** [comment]
Diagram still has SAGA-Pilot in it.

**Comment by andre-merzky** [comment]
We don't have the sources for that fig anymore, so I replaced it with a more recent fig we created in a different context...
