### ISSUE TITLE
Multiple Pilots Example

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#493]
I think that an example showing how to use multiple pilots would be very useful and it will answer questions like: 
How do someone submit a CU to specific pilot? 
How can I write a script where I have different pilots in different sources?

Thank you

**Comment by marksantcroos** [comment]
I have one, but that one is not functional because of #511.

We should probably convert that into a test, and once that works, turn it into an example.

**Comment by andre-merzky** [comment]
#511 is closed now - but I have a couple of multi-pilot scripts around.  Mark, let me know if you want to delegate this ticket to me...

**Comment by marksantcroos** [comment]
Ok good, thanks.

My script is here:
https://github.com/radical-cybertools/radical.pilot/blob/devel/tests/issue359.py

You are the proud owner now.

**Comment by iparask** [comment]
I forgot to mention the ticket to the commit. Here it is a7765006630ec627ec5a935a91aabc2c3d8af7d1

**Comment by andre-merzky** [comment]
Thanks Iannis!
