### ISSUE TITLE
CU reports fail but....

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#495]
I have CUs, eg. with number 5500dc479f541c23e946831e, that reports failure but when I look in the folder everything is okay and the correct result is written in the STDOUT file and I have CUs, eg 5500dd4a9f541c23e9468565, that are missing the shell script.

I am submitting each CU to the pilot after the description while the pilot is active and not all of them in bulk. 

You can find the log here: https://gist.github.com/iparask/c7147611e894f98512ab

**Comment by marksantcroos** [comment]
`Error: blob is too big`

**Comment by iparask** [comment]
It is 21MB if that is the reason you got the blob error

I can upload it to a web server or you can download a tar with it if you go to the link from your web broswer.

Tell me what is more convinient

**Comment by andre-merzky** [comment]
Either one works I guess.  You can also deposit on our Amazon VMs...

Thanks!

**Comment by marksantcroos** [comment]
Ok, I downloaded it now.

Dont know why I missed that button yesterday.

**Comment by marksantcroos** [comment]
> On 12 Mar 2015, at 1:58 , Ioannis Paraskevakos <notifications@github.com> wrote:
> 
> I have CUs, eg. with number 5500dc479f541c23e946831e, that reports failure but when I look in the folder everything is okay and the correct result is written in the STDOUT file and I have CUs, eg 5500dd4a9f541c23e9468565, that are missing the shell script.

It goes from PendingInputStaging to Failed. So the transfer is suspect.
What does the CU Desc look like?

**Comment by iparask** [comment]
fshared_0 = {'source': os.path.join(MY_STAGING_AREA, SHARED_HAUSDORFF),
                         'target': SHARED_HAUSDORFF,
                         'action': rp.COPY}

            fshared_1 = {'source': os.path.join(MY_STAGING_AREA, ( 'traj_flat%d.npz.npy' % i  )),
                         'target': 'traj_flat%d.npz.npy' % i,
                         'action': rp.LINK}

            fshared_2 = {'source': os.path.join(MY_STAGING_AREA, ( 'traj_flat%d.npz.npy' % j  )),
                         'target': 'traj_flat%d.npz.npy' % j,
                         'action': rp.LINK}

            # define the compute unit, to compute over the trajectory pair
            cudesc = rp.ComputeUnitDescription()
            cudesc.executable    = "python"
            cudesc.pre_exec      = ["module load python/2.7.3-epd-7.3.2"]
            cudesc.input_staging = [fshared_0, fshared_1, fshared_2]
            cudesc.arguments     = ['hausdorff.py', '-v', i, j]
            cudesc.cores         = 1

**Comment by marksantcroos** [comment]
Thanks.

Can you provide the agent.log?

**Comment by iparask** [comment]
There you go: https://gist.github.com/iparask/5251b2b44ea85b86cb48

**Comment by marksantcroos** [comment]
2015-03-11 19:22:36,687 - radical.pilot.agent - INFO - Task 5500dc479f541c23e946831e terminated with return code 0.

So that explains why the output you expect is actually there in the unit directory.
(All CUs seem to exit with 0 fwiw)


2015-03-11 19:24:38,800 - radical.pilot.agent - ERROR - Linking /work/03170/tg824689/radical.pilot.sandbox/pilot-5500db729f541c23e9468130/staging_area/traj_flat45.npz.npy to /work/03170/tg824689/radical.pilot.sandbox/pilot-5500db729f541c23e9468130/unit-5500dcb39f541c23e9468456/traj_flat45.npz.npy failed.

Does /work/03170/tg824689/radical.pilot.sandbox/pilot-5500db729f541c23e9468130/staging_area/traj_flat45.npz.npy exist?


To assist debugging in further runs, can you change your session.close() to "session.close(cleanup=False)"?

**Comment by iparask** [comment]
Yes it does. Also it is properly copied to the unit folder I see there and the shell script was run and the CU reported Done.

Ok, I will add cleanup false. It is not enough to the pilot's description?

I can run it again and provide you with any log file you want. I was able to reproduce it yesterday.

**Comment by marksantcroos** [comment]
> On 12 Mar 2015, at 21:38 , Ioannis Paraskevakos <notifications@github.com> wrote:
> 
> Yes it does. Also it is properly copied to the unit folder I see there and the shell script was run and the CU reported Done.

Linked you mean, right?

> Ok, I will add cleanup false. It is not enough to the pilot's description?

Im not sure what the exact semantics of that is in master to be honest.
But changing it for the session should give me the info in the db that I need.

> I can run it again and provide you with any log file you want. I was able to reproduce it yesterday.

Yes, that would be useful.

**Comment by iparask** [comment]
Yes I mean linked.

Perfect. Only Radical Pilot debug information or you want also SAGA debug information?

**Comment by marksantcroos** [comment]
> On 12 Mar 2015, at 21:47 , Ioannis Paraskevakos <notifications@github.com> wrote:
> 
> Yes I mean linked.
> 
> Perfect. Only Radical Pilot debug information or you want also SAGA debug information?

SAGA won't help much here as its about the agent.

Which reminds me that we need a switch for that on the agent side too :)

**Comment by iparask** [comment]
There you go: https://gist.github.com/iparask/a0762d11ff92e6871254

local_stdout.log is the scripts prints and callbacks, debug_out.log is the debug output

**Comment by marksantcroos** [comment]
Ok, something is definitely wrong.

Staging goes fine, the task is launched, and executes fine.
Then 20 seconds later the staging is attempted again, fails, and marks the task as failed.

So far no idea why this is happening.

I'm a bit hesitant diving into master on this level.
If in any way you could try devel or test/bootstrapper that would be awesome.

**Comment by iparask** [comment]
I will give both a try and come back with results.

**Comment by iparask** [comment]
I just tried this script with devel and everything went fine. With test/bootstrapper, it did not work. At some point it was like waiting for something. I have at the beginning of the script a number of CUs, 50, that are submitted in bulk. After those CUs finish their jobs I start submitting 1225 Cus one at a time.

Here is the debug log: https://gist.github.com/iparask/0360d29ab9ab8aef26a0

**Comment by marksantcroos** [comment]
Did you interrupt the run? (Like ctrl-c?)

I don't see immediately that something is wrong with it.

Can you run it with smaller numbers, that might make it easier to comprehend?

**Comment by iparask** [comment]
I did interrupt the run actually.
Now here is a uninterrupted run: https://gist.github.com/iparask/ca7c77ea65d7f7cf0141

The total number of CUs is 465. The first 30 are submitted in bulk and the rest one at a time. All the CUs have been submitted and executed correctly. I think the script never returned from the umgr.wait_units because I have prints before and after it and I saw only the first print.

**Comment by marksantcroos** [comment]
So there is no problem or am I misunderstanding?

**Comment by iparask** [comment]
You are right. Based on the ticket title there is no problem.

I put the log in case it provides you information for anything else. The problem, if you like, is that it never return although everything was finished and waited until the pilot timedout. But this is irrelevant to the ticket.

**Comment by marksantcroos** [comment]
Depends on how you use it whether it is a problem.
The pilot has no idea if there will be no more units coming, so it will run until end of walltime.
But if the application knows it is done, it should tear things down.
If that doesn't work, then there is a problem.

**Comment by iparask** [comment]
And by using the wait_units() method of the Unit manager my application recognizes that all the units it submitted finished and then tear things down, right?

**Comment by marksantcroos** [comment]
Right, so if that doesnt return, then there is an issue.

**Comment by iparask** [comment]
It did not return when I submitted the units one by one. If you see line 7182 of the log it says:
2015:03:18 14:35:28 9056   MainThread   radical.pilot         : [DEBUG   ] schedule (198 units waiting)

and

line 9931:
2015:03:18 14:39:54 9056   Thread-3     radical.pilot         : [DEBUG   ] schedule (0 units waiting)

And there are no more units executing

**Comment by marksantcroos** [comment]
> And there are no more units executing

Why you say so?

$ grep -c "RUN ComputeUnit .* to 'Done" bootstrap_debug.log 
436

**Comment by andre-merzky** [comment]
`0 units waiting` means that no units are in the unit manager wait queue, ie. no units are waiting to get assigned to a pilot.  That does not mean that the pilot executed all units it got...

**Comment by iparask** [comment]
This is the stdout log: https://gist.github.com/iparask/cfe732227faa1b2658fd

The done callbacks are 466.

**Comment by marksantcroos** [comment]
Hmmm, how can that number be different?

Anyway, if that is the case, and you have the impression that the wait() is not returning, then there is a bug.

**Comment by iparask** [comment]
I made a mistake about the number. There are some extra prints in the middle from the untis.
Let me make another run, with no redundant prints and I will upload everything again all the logs as well as the part of the script that shows me what I think.

**Comment by iparask** [comment]
Okay, I rerun everything and the results are more weird than I thought. 

I am explaining.

If you look at the stdout log files you will see that the submission of all units is done ( a code snippet is always there), but after "everything" is run the script does not continue after wait. I am saying "everything" because from the 465 CUs that should have run, the 434 report done. But when I check the sandbox folder all 465 unit folders exit and all of have actually run. I know this as a fact because I got the values of all STDOUT files and they are what they should be.

As a reminders this is with test/bootstrap branch.

In the gist you can find the agent.log, agent.out, agent.err, the code snippet from my script, the stdout log from running the scripts and the verbose debug log

The prints after the one-by-one submission ended are at lines 1489 - 1490 and the script goes to wait_units.

https://gist.github.com/iparask/beb02dc2d941faa83782

**Comment by andre-merzky** [comment]
last line on agent.err says:

slurmd[c560-501]: *** JOB 5000155 CANCELLED AT 2015-03-18T16:33:10 DUE TO TIME LIMIT ***

You should see the pilot going into cancelled state -- it may take up to a minute though for RP to see that the pilot got cancelled.  Is that happening?

**Comment by andre-merzky** [comment]
Hmm, the debug output also shows the pilot is failing, and that the pilot state callback then shuts the application down:

```
2015:03:18 17:35:25 11352  Thread-1     radical.pilot         : [INFO    ] ComputePilot 'pilot.0000' state changed from 'Active' to 'Failed'.
2015:03:18 17:35:25 11352  Thread-1     radical.pilot         : [ERROR   ] pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/iparask/RadicalPilotDevel/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 346, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/iparask/RadicalPilotDevel/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 241, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "rp_hausdorff.py", line 15, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```

That looks like as it should be, to me...

**Comment by iparask** [comment]
I see: [Callback]: ComputePilot 'pilot.0000' state: Failed.

**Comment by andre-merzky** [comment]
Yes, that looks correct -- the pilot exceeded its  time limit, and slurm killed it.  The pilot system will see the pilot is gone, and declare it dead (failed).

I may be misunderstanding the  ticket -- but what would be the expected outcome, in your opinion?

**Comment by iparask** [comment]
So 465 units were submitted. From the code snippet, the NUMBER_OF_TRAJECTORIES is equal to 30 and the size of the all_pairs (NUMBER_OF_TRAJECTORIES) is 435. Based on the last debug log 434 units returned in total and after that there were no units to be scheduled.

Where did the rest 30 submitted units go? And regardless what happened to those 30 units, shouldn't  wait_units() have returned for my script to close everything? The pilot was seating there doing nothing for almost half an hour. Check the time difference between lines 9686 and 9914 from the debug log.

**Comment by marksantcroos** [comment]
So did you run it with a smaller number too?
I would like to rule out problems of scale from logic problems.

**Comment by iparask** [comment]
The last run was with the one third of the units compared to the first, from 1275 to 465.
I can run it for even smaller but tell me approximately how many units do you want to have in total?

**Comment by marksantcroos** [comment]
As small as you can?

If that works, and you are free in choosing the numbers, you might be able to find the sweet spot with a binary search.

**Comment by marksantcroos** [comment]
Whats the status of this one?

**Comment by iparask** [comment]
Let me to back to that again the next days

**Comment by marksantcroos** [comment]
@iparask More luck with later versions?

**Comment by andre-merzky** [comment]
ping for an update... :)

**Comment by andre-merzky** [comment]
ping for an update... :)

**Comment by iparask** [comment]
It is gone. If it pops up I will reopen the ticket.
