### ISSUE TITLE
bootstrapping fails on joule

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#497]
Tail of agent.out:
```
Successfully installed radical.pilot radical.utils saga-python
#
# SUCCESS
#
# -------------------------------------------------------------------

---------------------------------------------------------------------

 (/gpfs/home/HCP056/sxz03/mas16-sxz03/radical.pilot.sandbox/ve_joule/bin/python)
PYTHONPATH: /gpfs/home/HCP056/sxz03/mas16-sxz03/radical.pilot.sandbox/ve_joule/rp_install/lib/python2.7/site-packages:
utils : 
install failed!
```

Tail of agent.err:
```
/gpfs/home/HCP056/sxz03/mas16-sxz03/radical.pilot.sandbox/ve_joule/lib/python2.7/site-packages/pkg_resources/__init__.py:2512: PEP440Warning: 'apache (libcloud-0.9.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
no previously-included directories found matching 'libcloud/test/secrets.py'
zip_safe flag not set; analyzing archive contents...
backports.__init__: module references __path__
Python 2.7.5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named utils
```

**Comment by marksantcroos** [comment]
I think the hint to this problem is you ignoring my question here:
https://github.com/radical-cybertools/radical.pilot/commit/8db85312edf95973f114fb001af29094b93da0d6#commitcomment-9914994

**Comment by marksantcroos** [comment]
To be more explicit:
```
-bash-4.1$ ls -l ve_joule/rp_install/lib/python2.7/site-packages/radical/
total 64
-rw-r--r-- 1 mas16-sxz03 sxz03  66 Mar 12 08:45 __init__.py
-rw-r--r-- 1 mas16-sxz03 sxz03 297 Mar 12 08:45 __init__.pyc
-bash-4.1$ ls -l ve_joule/rp_install/lib64/python2.7/site-packages/radical/
total 128
drwxr-xr-x 10 mas16-sxz03 sxz03 32768 Mar 12 08:45 pilot
drwxr-xr-x  7 mas16-sxz03 sxz03 32768 Mar 12 08:45 utils
```

**Comment by andre-merzky** [comment]
Ah, darn...  Yes, that should be addressed by the distutil inspection as you suggested...  thanks!

**Comment by marksantcroos** [comment]
Yeah, should ...

**Comment by marksantcroos** [comment]
You have an account on joule yourself, so please see why it fails after this fix.

**Comment by marksantcroos** [comment]
-bash-4.1$ pwd
/gpfs/home/HCP056/sxz03/mas16-sxz03/radical.pilot.sandbox/ve_joule
-bash-4.1$ find . -name radical
./lib/python2.7/site-packages/radical
./rp_install/lib64/python2.7/site-packages/radical

**Comment by marksantcroos** [comment]
1e2f3ed seems to fix it and no regressions on other systems so far.

**Comment by marksantcroos** [comment]
Latest changes break bootstrapping on joule again.

No apparent failures during the installation except for the following at the end:
```
ImportError: No module named utils
```

config:
``` json
"rp_version": "local",
"virtenv": "%(global_sandbox)s/ve_joule",
"virtenv_mode": "create"
```

**Comment by andre-merzky** [comment]
Alas, its down  for maintenance -- I'll check as it comes back...

**Comment by andre-merzky** [comment]
I found this one, finally: the paths to `lib64/` in the VE is a symlink to `lib/`, so the path normalization converts that to `lib/` -- but pip installs into `lib64/`.  Duh.

I think I got a handle on that now -- but joule now fails for me because the agent won't connect to mongodb.  My config may be off, not sure...  Any idea?

**Comment by marksantcroos** [comment]
Yeah, I figured so much. Thanks for fixing.

Tunnel disappeared because of a headnode reset, modulo mongo version issues its ok now!
