### ISSUE TITLE
saga verbose on agent?

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#500]

**Comment by andre-merzky** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/test/bootstrapper/src/radical/pilot/bootstrapper/default_bootstrapper.sh#L1080

;)

**Comment by marksantcroos** [comment]
?

**Comment by andre-merzky** [comment]
That line is already setting SAGA_VERBOSE for the new agent?  If that is not what the ticket is about, can you add some more details, please?

**Comment by marksantcroos** [comment]
We might want to have some more control over it instead of this all or nothing.
Let me think about what would be useful.
