### ISSUE TITLE
CUs log attribute not set

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#501]
What I realized is that the unit log attribute gives me a type error: string indices must be integers when I use the Pilot's directives for file staging and I pass a list of dictionaries for input staging. 

On the other hand, when I destroyed the dictionary and passed to the input staging a list of strings, the log attribute is a list of radical.pilot.logentry.Logentry objects.

**Comment by marksantcroos** [comment]
Sorry, I have problems parsing this ticket.
Can you clarify a bit more?

**Comment by iparask** [comment]
units = []
        for i, j in all_pairs (NUMBER_OF_TRAJECTORIES) :

            fshared_0 = {'source': os.path.join(MY_STAGING_AREA, SHARED_HAUSDORFF),
                         'target': SHARED_HAUSDORFF,
                         'action': rp.COPY}

            fshared_1 = {'source': 'file:///~/traj_flat%d.npz.npy' % i ,
                         'target': 'traj_flat%d.npz.npy' % i,
                         'action': rp.LINK}

            fshared_2 = {'source': 'file://~/traj_flat%d.npz.npy' % j ,
                         'target': 'traj_flat%d.npz.npy' % j,
                         'action': rp.LINK}

            # define the compute unit, to compute over the trajectory pair
            cudesc = rp.ComputeUnitDescription()
            cudesc.executable    = "python"
            cudesc.pre_exec      = []
            cudesc.input_staging = [fshared_0, fshared_1, fshared_2]
            cudesc.arguments     = ['hausdorff.py', '-v', i, j]
            cudesc.cores         = 1

            cudesc_list.append (cudesc)
        # submit, run and wait and...
        print "submited units to unit manager ..."
        units = umgr.submit_units (cudesc_list)
        print "wait for units ..."
        umgr.wait_units()

        print type(units[0].log)

If input_staging is as here a list of dictionaries, the print command returns:
TypeError: string indices must be integers
An error occurred: string indices must be integers

If input becomes, for example, a list of values or just one dictionary then the print command prints type list of radical.pilot.logentry.Logentry objects.

**Comment by marksantcroos** [comment]
Ok, clear, thanks for that.

AFAIK, there is no direct link between staging directives and log, other than that changes in the staging directives have alternative execution of the CU (read: failure) and thereby influence the log entries.

So this particular code has changed in devel.
@andre-merzky The commit (5c5c0cf) that changed this has the infamous message of "snapshot". Any idea why you changed it?

**Comment by andre-merzky** [comment]
That was part of a larger, inter-depent set of changes on the bootstrapping.  The Logentry had also an attribute name  changed (to avoid the confusion that a logentry has a logentry, both being different types).

I don't yet see how/where that commit causes the bug -- it probably does a `set` where it should do a `push`, somewhere...  Let me go through it...

Thanks!

**Comment by andre-merzky** [comment]
@iparask : to be sure: you are hitting that problem on the devel branch?

**Comment by iparask** [comment]
I am getting an error when I try to import it.

**Comment by marksantcroos** [comment]
Andre (and myself) wanted to know if "it" is master or devel :-)

**Comment by iparask** [comment]
I installed devel branch and got an error when I tried to import radical pilot. The error in case you need it is here: https://gist.github.com/iparask/da3333f903efef63c85b

**Comment by marksantcroos** [comment]
You need the devel branches of radical.utils and saga-python too.

**Comment by iparask** [comment]
Okay! Thank you!

Now the pilot goes from launching to failed. 

https://gist.github.com/iparask/5ba160336bd79215ac16

**Comment by iparask** [comment]
Scratch the previous comment, if you do not need it. I used the command python setup.py install to install everything, now I used pip install . --upgrade. 

I managed to run my script with the devel branch and the logentry is set properly.

**Comment by marksantcroos** [comment]
Thats good to hear. I guess this reminds us that we really want to get devel in a good state.
