### ISSUE TITLE
multiple pilots and direct binding

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#510]
The current implementation doesn't seem to implement the originally intended API, e.g. `pilot.submit_unit()`.

We now need multiple unit managers to render that.

This might be fine ultimately, but it needs a thought and conclusion.

**Comment by oleweidner** [comment]
Somewhat related: 

Is there a document or wiki page documenting API changes from 0.23 to 0.24? In the interest of sanity I hope that only API calls are added and not removed or changed. 

This information would be highly relevant to all projects using RP.

**Comment by andre-merzky** [comment]
The changes from 0.23 to 0.24 focus on agent refactoring -- I am not aware of any API changes.

**Comment by oleweidner** [comment]
Good news :-)

**Comment by andre-merzky** [comment]
implemented.
