### ISSUE TITLE
align attributes, dicts, json on rp client side

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#512]
but still picked up ... why?

**Comment by andre-merzky** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/resource_config.py#L178

**Comment by andre-merzky** [comment]
this ticket is now re-interpretated:  the use of saga attributes, dicts and json throughout the RP code should be made more consistent, conceptually, syntactically and semantically.

**Comment by andre-merzky** [comment]
I consider this addressed, please reopen if specific problems remain.
