### ISSUE TITLE
Run on trestles is timing out

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#513]
I am experiencing runs timing out on Trestles. I don't see any errors reported via "rp debug" before run is actually timing out. I have checked cu directories on resource and for the last one executable was not even launched. There are no errors for any of the cu's. Complete terminal output can be found at: https://gist.github.com/AntonsT/68b86ef6709de2b08046

**Comment by marksantcroos** [comment]
This is with the released version, right?

If so, given the testing phase of devel that has started, would you mind giving that a try?

**Comment by AntonsT** [comment]
Will do.

**Comment by andre-merzky** [comment]
Antons, would you have the agent.out/err/log files still available for this run?  If not, could you please rerun and keep them around?  Thanks!

**Comment by andre-merzky** [comment]
Also, can you please check how large largest units are?  The pilot is 16 cores wide, correct?

**Comment by AntonsT** [comment]
The issue was with specifying number of cores for CU > Pilot size. Thanks for pointing this out Andre! and apologies for the inconvenience.
