### ISSUE TITLE
slot history recording missing?

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#517]
`radicalpilot-stats -m stat,plot` gives:
```
no slot configuration for session rp.session.netbook.mark.016519.0011
Please enable benchmarking: export RADICAL_PILOT_BENCHMARK=
```

However, that env variable is not used in devel branch anymore.

I vaguely remember that this was turned of, but at least the tools need to be in sync then.

**Comment by andre-merzky** [comment]
This is fixed by now.
