### ISSUE TITLE
blue waters: stdout/stderr behavior and cleaned pilot directory

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#519]
From email:
```
BW Job ID: 1488389.nid11293 
Job Name: SAGA-Python-PBSJobScript.PdQ4fK 
Exec host list suppressed in email 
An error has occurred processing your job, see below. 
request to copy stageout files failed on node '26209' for job 1488389.nid11293

Unable to copy file /mnt/a/u/sciteam/marksant/1488389.nid11293.OU to marksant@h2ologin2:/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016519.0015-pilot.0000/agent.out, error 1
*** error from copy
/bin/mv: cannot move `/mnt/a/u/sciteam/marksant/1488389.nid11293.OU' to `/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016519.0015-pilot.0000/agent.out': No such file or directory
touch: cannot touch `/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016519.0015-pilot.0000/agent.out': No such file or directory
*** end error output

Unable to copy file /mnt/a/u/sciteam/marksant/1488389.nid11293.ER to marksant@h2ologin2:/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016519.0015-pilot.0000/agent.err, error 1
*** error from copy
/bin/mv: cannot move `/mnt/a/u/sciteam/marksant/1488389.nid11293.ER' to `/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016519.0015-pilot.0000/agent.err': No such file or directory
touch: cannot touch `/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016519.0015-pilot.0000/agent.err': No such file or directory
*** end error output
```

**Comment by andre-merzky** [comment]
Does that tell us that the pilot workdir is not the same as the pilot sandbox?  I am not     sure how to interprete that otherwise... :/

**Comment by marksantcroos** [comment]
No, that tells you that the stdout/stderr are not in the $PWD, $CWD, $WORKDIR, $WHATEVER during execution. At least not by default.

**Comment by marksantcroos** [comment]
So a couple of issues here.

- One is a problem in our PBS adaptor, it actually doesn't pass the work directory as an argument, but sets it as an environment variable. That means that the variable will be available to the job, but that qsub itself is not aware of it. That makes that the files are created in $HOME instead of the sandbox.
(This might be another side effect of squeezing TORQUE and PBSPro into one adaptor)

- The second issue is that the files don't have their final names during execution of the job. I don't see any way how to control this.

So is this a real problem?

- If sandbox cleanup is not enabled, this situation won't arise.

- If we do automagic cleanup, we could opt to not create them in the first place.

- Finally, it might be the cleanest to do the cleanup outside of the job, then this situation won't arise either.

**Comment by andre-merzky** [comment]
For the first problem, wouldn't the fix be to honor the workdir in our qsub script?  I would be uncomfortable *not* doing this, because of cleanup, race conditions, non-shared FS for the staging area, etc.

For the second problem, do we need to rely on PBS for catching stdout/stderr of the agent?  We handle stdout/stderr on our own for units, I don't see why handling it for the bootstrapper and pilot should be any more difficult?

**Comment by marksantcroos** [comment]
> For the first problem, wouldn't the fix be to honor the workdir in our qsub script? I would be uncomfortable not doing this, because of cleanup, race conditions, non-shared FS for the staging area, etc

It doesn't solve anything here, but yes, this needs to be addressed in general.
See https://github.com/radical-cybertools/saga-python/issues/421.

> For the second problem, do we need to rely on PBS for catching stdout/stderr of the agent? We handle stdout/stderr on our own for units, I don't see why handling it for the bootstrapper and pilot should be any more difficult?

Right. I think we recently discussed this in the context of logging output, and I think I agree.

Note that neither of this actually solve the original problem of this ticket.

**Comment by andre-merzky** [comment]
Mark, is this still relevant?

**Comment by andre-merzky** [comment]
Mark, is this still relevant?
