### ISSUE TITLE
mpi rank reporting not universal?

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#520]
Seen before, but never really investigated (at least that I remember), the Crays report "rank 1/1/nid22168" regardless of the number of cores.

**Comment by marksantcroos** [comment]
This might actually be related to mpi4py. We could consider distributing and compiling a C version on the fly. Might actually be more simple in practice.

**Comment by andre-merzky** [comment]
+1 -- I think this is in fact much simpler than the circus we do to get mpi4py usable...  I would also not mind a shell version ;)  I am only half kidding, as that would be backend specific -- but then again, it would only need mpirun: https://github.com/radical-cybertools/radical.pilot/blob/master/tests/mpi_stampede_test.py#L82  We have been using that silently for some machines for a while, w/o a problem...

```

```

**Comment by marksantcroos** [comment]
My argument for not using the environment variables (only) is that our "application" wouldn't be a real "consumer", but rather retrofitting whatever variables we find.
But that might not be a strong argument.

**Comment by andre-merzky** [comment]
Mark, should we get that sorted out before the tutorials?

**Comment by andre-merzky** [comment]
I would be in favor of a compiled test as you suggested, that is closer to the application.  Also, it would confirm the viability of the ORTE installation on those resources where that matters?

**Comment by andre-merzky** [comment]
Closed due to lack of activity
