### ISSUE TITLE
capability on par with (production) BigJob

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#527]

**Comment by marksantcroos** [comment]
This sounds like a milestone, not an actionable item.

**Comment by andre-merzky** [comment]
yeah, I know.  We probably should convert that into more actionable items (beyond 'support PilotData') -- but right now I do not know what those actionable items are...

**Comment by andre-merzky** [comment]
I think that PilotData is the only item which was explicitly identified.  I close this generic ticket and open a specific one for PD.
