### ISSUE TITLE
Resource: SuperMUC fully supported

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#528]

**Comment by marksantcroos** [comment]
In relation to #647 and #615 I've been trying to get RP going with the default version of python on SuperMUC.
That is an anaconda version, which doesn't work with virtualenv, as it has its own way of dealing with (virtual) environments.
I've created a separate ticket for that in #669.

**Comment by andre-merzky** [comment]
Our allocation on supermuc expired.
