### ISSUE TITLE
Resource: Experimental support for Hopper

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#533]

**Comment by marksantcroos** [comment]
Whats the definition of this? Hopper has been "supported" for a while already.

**Comment by andre-merzky** [comment]
Then we'll close it at next release.  Definition for 'experimental' is, IMHO, that the MPI test passes, and that bootstrapping is stable.  Hopper had been specifically mentioned by the AIMES folx, thus the ticket to ensure that status...

**Comment by mturilli** [comment]
For the AIMES use case it would be relevant to be able to run CUs with less than 24 cores. This should be addressed by the scheduler that, AFAIH, is going to be available once devel will be released.

**Comment by marksantcroos** [comment]
With CCM we should be able to get you core granularity on Hopper and Edison.

**Comment by mturilli** [comment]
Right, CCM, too many acronyms for my buggy memory. Great! And titan maybe? :)

**Comment by marksantcroos** [comment]
Titan doesn't have Cluster Compatibility Mode (CCM) as far as I can distill from the documentation.
But we have a separate ticket for Titan at #532 :-)

**Comment by marksantcroos** [comment]
See #577.
