### ISSUE TITLE
Resource: Experimental support for OSG

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#535]

**Comment by andre-merzky** [comment]
*experimental* support for OSG is now available in the `feature/osgng` branch.  I'll leave this ticket open until that is merged into devel.

**Comment by mturilli** [comment]
As a follow up of a meeting about RP support of OSG for AIMES-related experiments here 2 scenarios and related questions. Scenarios and questions are meant to be refined as a results of the discussion in this ticket. The goal is to clarify the requirements for the RP support of OSG.

**Scenario 1**: we need to run a multi-task workload via RP on OSG. We want to use OSG WMS to ask for n single-core pilots with n = to the number of tasks of the workload. 
Questions:
  1. What is the highest number of single-core pilots we can ask for?
  2. What is the longest walltime we can ask for?
  3. What WMS endpoints are currently supported other than the XSEDE one?

**Scenario 2**: we need to run a multi-task workload via RP on OSG. We want to describe n single-core pilots with n = to the number of tasks. For each pilot description, we want to explicitly specify a OSG _resource_ not a WMS. 
Questions:
  1. Can we specify the name of an OSG resource in the pilot description?
    1. If so, do we have a list of OSG resource tags in the Radical pilot configuration file?
  2. Can we specify the queue for each resource?
  3. Can we specify the walltime for each pilot on each resource?

**Comment by andre-merzky** [comment]
> Scenario 1:
> 1. What is the highest number of single-core pilots we can ask for?
> 2. What is the longest walltime we can ask for?

I would like to understand the details of these two questions.  Naively, I would answer 'infinite' to both, which is probably useless :P  

Are you asking how many pilots RP can accept w/o breaking down?  w/o performance degredation?  w/o OSG declining pilot submission?  Or how many make sense for the given workload?

Similar for walltime: are you looking for the value range supported by RP / supported by OSG / a value which makes sense for the workload?


> 3. What WMS endpoints are currently supported other than the XSEDE one?

In the context of 3.,  I wanted to remind that (IIRC) the submission scheme is different once the user is a member of a VO.  AFAIK we don't have that luxury yet, or do we?

**Comment by mturilli** [comment]
> Are you asking how many pilots RP can accept w/o breaking down?  w/o performance degredation?  
> w/o OSG declining pilot submission?  Or how many make sense for the given workload?

This first three, not the fourth.

> Similar for walltime: are you looking for the value range supported by RP / supported by OSG / a 
> value which makes sense for the workload?

The first two, not the third.

> .3. What WMS endpoints are currently supported other than the XSEDE one?

In the context of 3.,  I wanted to remind that (IIRC) the submission scheme is different once the user is a member of a VO.  AFAIK we don't have that luxury yet, or do we?

I do not understand the question.

**Comment by marksantcroos** [comment]
> Can we specify the name of an OSG resource in the pilot description?

Yes, see https://github.com/radical-cybertools/radical.pilot/blob/feature/osgng/examples/getting_started_osg.py#L121

> If so, do we have a list of OSG resource tags in the Radical pilot configuration file?

No.

> Can we specify the queue for each resource?

AFAIK there is no concept of `queue` on that level. Why would you want it? And why not in scenario 1?

> Can we specify the walltime for each pilot on each resource?

Yes, there is no difference with scenario 1.

**Comment by andre-merzky** [comment]
>> Are you asking how many pilots RP can accept w/o breaking down? w/o performance degredation? 
>> w/o OSG declining pilot submission? Or how many make sense for the given workload?
> This first three, not the fourth.

1/2: RP performance will gradually degrade with number of pilots, exact cutoff needs to be found experimentally, we have not done that.

3: I don't think that  OSG has a hard limit on the number of jobs to submit -- but the documentation states explicitly that site administrators may become unhappy when sites get swamped with jobs.  See also remark on VOs below.

 
>> Similar for walltime: are you looking for the value range supported by RP / supported by OSG / a 
>> value which makes sense for the workload?
> The first two, not the third.

1: For RP, the walltime is an integer, and has the boundary of a Python int.  No interpretation is done otherwise.

2: OSG has, AFAIK, no hard limit on job lifetime either.  The documentation clearly states that only a few sites support jobs running for longer than 24 hours.  So, longer jobs are not forbidden, but have a smaller chance of finding a resource to   get scheduled on by OSG.  I could not find any site specific documentation on life time limits.  See also remarks on VO below.
 
>>> What WMS endpoints are currently supported other than the XSEDE one?
>>
>> In the context of 3., I wanted to remind that (IIRC) the submission scheme is different once the user is a member of a VO. AFAIK we don't have that luxury yet, or do we?
> 
> I do not understand the question.

OSG is a collection of sites.  Those sites accept to run jobs from users which are members of certain VOs.  A site may or may not accept jobs from any specific VO -- so what site is available to a specific user depends on what VOs that user is member of.  A site also may or may not have specific runtime limits in place for jobs from a specific VO, or may have VO specific limits on the number of jobs they are willing to accept in a certain period of time.

I am thus not sure if the questions above can be clearly answered 'for OSG', but would suspect they only have answers for each tuple `[SITE, VO]`.  

At the moment, we are not part of a VO at all, I think?

The page at [1] documents how a user can find a list of available resource endpoints *for a given VO*.  AFAIK, querying the BDII or ReSS gives more information about the individual sites - they expose GLUE information for those (I do not know how those endpoints related to the GlideIn endpoints we can specify in RP right now as CandidateHosts).   I think this is what PANDA uses for example to find the set of sites to place pilots on.

[1] https://twiki.opensciencegrid.org/bin/view/Documentation/FindAvailableResource

**Comment by mturilli** [comment]
On Mon, Nov 23, 2015 at 4:42 AM, Mark Santcroos <notifications@github.com>
wrote:

> Can we specify the name of an OSG resource in the pilot description?
>
> Yes, see
> https://github.com/radical-cybertools/radical.pilot/blob/feature/osgng/examples/getting_started_osg.py#L121
>
Thanks. What is the list of OSG sites we can access as RADICAL? At the
moment I know about the XSEDE and OSG Connect submit nodes/hosts:
submit-1.osg.xsede.org and  login.osgconnect.net. As far as I understand,
these are not 'sites' (OSG resources in my question) but two front ends for
the same OSG entry point. This entry point schedules jobs on ~120 sites.

> If so, do we have a list of OSG resource tags in the Radical pilot
> configuration file?
>
> No.
>
Should we?

> Can we specify the queue for each resource?
>
> AFAIK there is no concept of queue on that level. Why would you want it?
>
In absence of specific documentation, I am trying to understand what is the
'OSG template' of a pilot description in RP and how it (semantically) maps
to the 'HPC' one. This is relevant to my research because queue selection
can be one of the decisions in an execution strategy for HPC DCRs.

> And why not in scenario 1?
>
Fair. I expect the WMS - or should we say entry point? - to abstract that
specific notion. Apparently, this is done also at 'site' level.

> Can we specify the walltime for each pilot on each resource?
>
> Yes, there is no difference with scenario 1.
>
Thanks.

-- 
Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by mturilli** [comment]
On Mon, Nov 23, 2015 at 5:30 AM, Andre Merzky <notifications@github.com>
wrote:

> At the moment, we are not part of a VO at all, I think?


AFAIK, as RADICAL members we are part of the OSG VO:
http://myosg.grid.iu.edu/vosummary?all_vos=on&active=on&active_value=1

-- 
Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by marksantcroos** [comment]
> AFAIK, as RADICAL members we are part of the OSG VO:

Not really, the WMS proxy is a member.

> What is the list of OSG sites we can access as RADICAL?

(You might want to put on sunglasses while looking at the command)
```
$ ldapsearch -LLL -h is.grid.iu.edu -p 2170 -x -b 'o=grid' '(&(objectClass=GlueCE)(GlueCEAccessControlBaseRule=VO:osg))' GLIDEIN_ResourceName|grep -v dn:|cut -f2 -d=|cut -f1 -d,|sort|uniq

AGLT2
Beocat
BNL-ATLAS
BNL-ATLAS-ITB
BNL_Test_2
BU_ATLAS_Tier2
cinvestav
CIT_CMS_T2
CIT_ITB_1
Clemson-Palmetto
FLTECH
FNAL_GPGRID_1
GLOW
local
LUCILLE
MIT_CMS
MWT2
NERSC-PDSF
NYSGRID_CORNELL_NYS1
OU_OSCER_ATLAS
Purdue-Carter
Purdue-Hadoop
SMU_HPC
SPRACE
SWT2_CPB
UCD
UC_ITB
UCSDT2
UERJ
UFlorida-HPC
uprm-cms
USCMS-FNAL-WC1
```

I assume bundles will provide you this information though?

> If so, do we have a list of OSG resource tags in the Radical pilot
>  configuration file?
> 
> >  No.
>
> Should we?

Probably not, as the information is dynamic. As you know, RP is not an (O)WMS ;-)

**Comment by marksantcroos** [comment]
> 2: OSG has, AFAIK, no hard limit on job lifetime either. The documentation clearly states that only a few sites support jobs running for longer than 24 hours. So, longer jobs are not forbidden, but have a smaller chance of finding a resource to get scheduled on by OSG. I could not find any site specific documentation on life time limits. See also remarks on VO below.

Based on my experience 12 hours is a sane upper limit to maintain from a user perspective.

**Comment by mturilli** [comment]
On Mon, Nov 23, 2015 at 10:29 AM, Mark Santcroos <notifications@github.com>
wrote:

What is the list of OSG sites we can access as RADICAL?
>
> (You might want to put on sunglasses while looking at the command)
>
> $ ldapsearch -LLL -h is.grid.iu.edu -p 2170 -x -b 'o=grid' '(&(objectClass=GlueCE)(GlueCEAccessControlBaseRule=VO:osg))' GLIDEIN_ResourceName|grep -v dn:|cut -f2 -d=|cut -f1 -d,|sort|uniq
>
> Thank you.

> I assume bundles will provide you this information though?
>
They are asking us to tell them what information they should provide. This
ticket is motivated in part by that request.

**Comment by andre-merzky** [comment]
The original ticket topic was 'experimental OSG support',  which is now available.  I will thus close this ticket, and would suggest to @mturilli and @marksantcroos to open individual tickets for the discussion points above, if they are still relevant.
