### ISSUE TITLE
Support DataFrames

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#537]
Information extracted from MongoDB should be provided as DataFrames, for easier analysis

**Comment by marksantcroos** [comment]
How do we see this? An extension of radicalpilot-stats?

I have a "fork" of radicalpilot-stats that does this.
How does Matteo turn it into DFs?

**Comment by andre-merzky** [comment]
There is already a patch in radical.pilot.utils, which adds `get_session_frames(sid)` to the already existing `get_session_data(sid)`.  I'd like to iterate on the frame structure though.  Would you mind sharing your branch? :)

**Comment by marksantcroos** [comment]
Right, I'm using `get_session_frames()` and not much beyond that (yet):

``` python
session_frame, pilot_frame, unit_frame = rpu.get_session_frames(db, session, cachedir)
store = pandas.HDFStore('store.h5')
store['session'] = session_frame
store['pilots'] = pilot_frame
store['units'] = unit_frame
```

Obvious extensions to this are selecting the storage and accumulation mechanism.

Regarding iterating the structure, relevant for that is probably #524.

Again Matteo's experience/insight is welcome here.

**Comment by andre-merzky** [comment]
`get_session_frames()` has been backported and seems to function as expected.
