### ISSUE TITLE
v0.23-431-g6e3c8ad@devel on Archer; mpi_test.py

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#546]
Results in:
```
File "mpi_test.py", line 187, in <module>
    run_test (cfg)
  File "mpi_test.py", line 131, in run_test
    assert ('mpi rank %d/%d' % (i+1, cfg['cu_cores']) in unit.stdout)
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by andre-merzky** [comment]
I assume that the prints before that showed no stdout for the units?

**Comment by AntonsT** [comment]
(terminal output](https://gist.github.com/AntonsT/6424d38a73856211d88f)
(verbose flags)[https://gist.github.com/AntonsT/78a775a5ad6096fb404a]

**Comment by andre-merzky** [comment]
Thanks Antons.  It seems that the CUs are running ok, so its really 'just' stdout which is missing.  Well, the short queue on archer is gone MIA again, so I'll debug that tomorrow.

**Comment by andre-merzky** [comment]
stdout and stderr are back on the units.
