### ISSUE TITLE
agent profiling data as dataframes

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#547]

**Comment by andre-merzky** [comment]
I think this should be done post-mortem, because (a) we would have pandas as a agent dependency otherwise, and (b) I would like to avoid any further runtime and memory overhead.

**Comment by marksantcroos** [comment]
> On 01 Apr 2015, at 21:21 , Andre Merzky <notifications@github.com> wrote:
> I think this should be done post-mortem, because (a) we would have pandas as a agent dependency otherwise, and (b) I would like to avoid any further runtime and memory overhead.

Correct, thats what we agreed upon already.

**Comment by andre-merzky** [comment]
This is implemented now
