### ISSUE TITLE
Error canceling job via 'qdel': qdel: Request invalid for state of job 2768960.sdb; v0.23-431-g6e3c8ad@devel; Archer

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#551]
Not sure if this is RP or SAGA error, but I am getting this:
```
2015:04:01 15:51:51 10662  MainThread   saga.PBSJobService    : [ERROR   ] Error canceling job via 'qdel': qdel: Request invalid for state of job 2768960.sdb
```

RP script completes normally.

**Comment by andre-merzky** [comment]
That is an expected SAGA-level error message in the log -- the case is very well handled in RP, and does not indicate an error condition.

**Comment by AntonsT** [comment]
Why it is tagged as ERROR then?

**Comment by andre-merzky** [comment]
It is a message from the SAGA layer which shows up in the log.  SAGA attempts an operation, and it fails -- so it is an error on SAGA level.  But RP issues that operation, full knowing that there is a likelyhood of failure, so the error is caught and handled.

it is like:

`ps -ef | grep 1234 && kill 1234`

grep would give an error here, but the whole purpose of running grep is getting that error state to determine if the kill should be issued.  Stupid example, I know, but I hope it makes the point... :)

**Comment by marksantcroos** [comment]
Antons might have wondered why he sees the error in the first place as he might not have asked for SAGA messages?

**Comment by andre-merzky** [comment]
I am not sure if he is asking that, maybe :)

There is a long standing issue somewhere that RADICAL_PILOT_VERBOSE also triggers SAGA_VERBOSE level debug messages.  To fix that seems to need some work in the logging system, that has somewhat slipped to the end of the priority list over time... :/
