### ISSUE TITLE
Change in Host Python version requires new release

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#552]
Today we experienced the following: 

* Andre released RP 0.24 yesterday. Running jobs on stampede worked fine.
* Tonight, TACC updated the default Python version on Stampede. 
* RP 0.24 agent stopped working on Stampede because it couldn't find the Python interpreter

Andre updated the resource configuration and released RP 0.25 to fix the issue (thanks Andre!) and we managed to pull of the ExTASY demo. However, if Andre (and Mark) wouldn't have been around, RP would have remained unusable on Stampede.

IMHO it is quite problematic if small changes on the target hosts (like updated Python version) require a new release of RP. Of course I know how difficult it can be to make the agent run on the various platforms in the first place, hence the elaborate configuration files. But if every small update potentially causes the RP agent to stop working, our deployment model might be a little bit too inflexible and makes too many assumptions about the remote end. From a practical perspective, this will put us continuously on the spot as the only people who can make things work again. For a piece of software that tries to provide a light-weight alternative to all these big and clunky WMS out there, this is not a good thing. 

I am not saying that we should change the way we do deployment at the moment, but in the long run I think this needs to be addressed as it is quite a usability killer for Radical-Pilot.

My $0.02

**Comment by marksantcroos** [comment]
Interestingly you actually introduced these hard coded paths, and at the time I suggested not to do that for reasons like today's events. (I can search for the thread if you insist)

We've been gradually removing these in the devel branch also. I will make it an action on me to look for remaining cases. 

Note that this doesn't cover all changes on resource site, but it covers a large portion of them.

Considering that releases are cheap and the fact that these configs can not be automatically detected, we are actually close to the best we can do.

**Comment by andre-merzky** [comment]
Either we have resource configs, or we detect things automatically.  Either can fail.  After long discussions we opted for the configs, to have more control and predictable behavior -- but those configs are bound to need maintenance.  That such maintenance was needed hours before the tutorial is bad luck (and as such will happen again), but I don't think that this changes anything wrt. to the original arguments...

Also, the diff of the release was literally one line (modulo changelog), a path name, and thus pretty much harmless.  If Mark or  I would not have been around, then http://radicalpilot.readthedocs.org/en/latest/machconf.html#customizing-resource-configurations-programatically would have been used to change the config on the fly...

**Comment by oleweidner** [comment]
This was not meant to be an exercise in "pointing fingers" but rather a report / perspective triggered by a specific incident. It was merely meant to provoke thought and discussion through challenging the status quo and the conclusions drawn from our long (sometime a bit hypothetical) discussions. 

I leave it of course to the team to decide whether any conclusions need to be drawn from this at all.
