### ISSUE TITLE
Add metadata to session dataframe

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#554]
I open this ticket to keep track of the metadata we would find useful to have in the session dataframe. For now I have:
* Name of the scheduler used

**Comment by marksantcroos** [comment]
Agreed, although this is not a property of the session, but of the UnitManager.
Probably points to the fact that we also need to expose that.

**Comment by andre-merzky** [comment]
Mark, what is the status of this?  I think that was implemented,  right?  Is it documented?

**Comment by andre-merzky** [comment]
This is implemented.
