### ISSUE TITLE
Stray {'STDERR': '', 'STDOUT': ''} in output

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#556]
When I use the latest devel branch, I see the following stray output:

```
{'STDERR': '', 'STDOUT': ''}
{'STDERR': '', 'STDOUT': ''}
{'STDERR': '', 'STDOUT': ''}
```

I think this comes from Radical-Pilot.

**Comment by andre-merzky** [comment]
Thanks, this is fixed now in saga-python.
