### ISSUE TITLE
CU.Allocating state name suggests CU is actively allocating resources

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#558]
Please close if irrelevant.

```
RUN ComputeUnit 'unit.000008' state changed from 'Allocating' to 'Executing'.
```

While completely irrelevant for the functionality of RP, I think the state name 'Allocating' is not the most accurate state description for a CU waiting for resources as it suggests that a CU actively and independently 'allocates' resources. As far as I understand that is not the case. 

Shouldn't  this rather be called 'Waiting' or 'Scheduled'?

**Comment by andre-merzky** [comment]
Ack - the name will change to `AGENT_SCHEDULING` soon.

**Comment by oleweidner** [comment]
What about `PILOT_SCHEDULING` - I think that would be easier to understand for the user.

**Comment by andre-merzky** [comment]
We discussed state naming in the context of https://docs.google.com/drawings/d/1JykjVYGMz2KPdBphyFO2kmL79Y9qX-wSIIh7l_VS_kU -- and I am quite relieved that the naming discussion has been closed.  I am not in favor of opening it again, to be honest...
