### ISSUE TITLE
Map the new state model to the old one

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#560]
With the changes to the state model of the new release it would be important to map the new states to the old ones. Without such a mapping, it is not possible to map the experimental results obtained with the old version to those obtained with the new one.

**Comment by andre-merzky** [comment]
I would propose the following: add a flag on `get_session_frames(state_model='v1')` to get the session data translated into the old state model.  That would not make the old state model pop up in any other places than data analysis -- but that is where it matters to you I think, nowhere else...

**Comment by mturilli** [comment]
I was simply thinking to a piece of documentation with a visual representation of the mapping. Basically, the diagram you have in googledoc with another diagram on its right and dashed lines showing what new states map to an old state - as the new state model is more granular than the old one.

Code-wise, I do expect to take full advantage of the greater granularity of the new state model so while a translation at DF tables could be useful, once the mapping has been established, I would probably want to adapt my analysis code to use the new DFs. What do you think?

**Comment by mturilli** [comment]
Thank you Andre, this addressed this ticket:
https://github.com/radical-cybertools/radical.pilot/wiki/State-Model-Evolution

Before closing it, would it be possible to transfer this piece of documentation into the official documentation?

**Comment by andre-merzky** [comment]
Done :)
