### ISSUE TITLE
no stderr staging on failed units

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#561]
a failed unit is moved into `FAILED` state immediately -- but stderr is uploaded to mongodb during `AGENT_STAGING_OUTPUT`, which is never passed through.  We probably should do stdout/stderr upload independent of staging (as was done in the past).

**Comment by andre-merzky** [comment]
My proposal would be to make the CU state model strictly linear. Well, it is linear already, in the sense that there are no loops defined (lets discuss 'restart' separately) -- but the state model does allow to skip states.  Specifically, staging states can be skipped if no staging directives are set.  I would like to use the `AGENT_STAGING_INPUT` state to create the workdir (even if it might already exist due to implicit creation during `UMGR_STAGING_INPUT`), and would like to use `AGENT_STAGING_OUTPUT`/`UMGR_STAGING_OUTPUT` to properly stage stdout/stderr/log.  The latter would imply that also units which fail or are cancelled in `EXECUTING` don't go to `FAILED`/`CANCELED` immediately, but still pass through `AGENT_STAGING_OUTPUT`/`UMGR_STAGING_OUTPUT` before ending up in the respective final state.

That has implications for units which don't do staging at all and run successfull -- they have to pass more components, and thus have a higher overall time they spend in RP.  That time should be sub-second though, as passing through noop components is very fast.  I don't see that influencing the overall unit throughput of RP (in steady state).

There is the possibility of congestion: assume a CU with large file staging, followed by many units with no staging -- the latter units would be stalled by the staging component until the first unit passed through.  That is somewhat elevated by the ability to have multiple concurrent stagers, but the core issue remains (only that more concurrent 'heavy' CUs are needed to stall the pipeline.  That issue is up for optimization, and exists (to a lesser degree though) already for CUs which have imbalanced staging requirements.  That optimization can be done on the unit scheduling level, which could prefer 'light' CUs over 'heavy' ones.

Anyway, this is what I think.  The alternatives would be :+1: 

* return to the mode where the ExecWorker pushes out stderr/stdout -- but this stalls the ExecWorker, which will lower resource utilization, which is much more critical for high CU throughput
* perform staging of stdout/stderr outside of the ExecWorker, w/o going through the explicit staging states.  I find that ugly: to execute a state's semantics but not calling it out in the state progression.
* don't do staging of stdout/stderr on failed / cancelled units -- but that negates an explicitly mentioned use case.

Feedback welcome!  Are there other alternatives?  Am I missing any implications?

**Comment by marksantcroos** [comment]
> My proposal would be to make the CU state model strictly linear. Well, it is linear already, in the sense that there are no loops defined (lets discuss 'restart' separately) -- but the state model does allow to skip states. Specifically, staging states can be skipped if no staging directives are set.

I think I can agree on everything below without agreeing to the strict model. If there is no output to be staged (including stdout/stderr), why wouldn't we be able to skip?

> I would like to use the AGENT_STAGING_INPUT state to create the workdir (even if it might already exist due to implicit creation during UMGR_STAGING_INPUT), 

Bits like this sound like a pretty nice idea.

> and would like to use AGENT_STAGING_OUTPUT/UMGR_STAGING_OUTPUT to properly stage stdout/stderr/log.

Right.

> The latter would imply that also units which fail or are cancelled in EXECUTING don't go to FAILED/CANCELED immediately, but still pass through AGENT_STAGING_OUTPUT/UMGR_STAGING_OUTPUT before ending up in the respective final state.

Which is perfectly fine I think.

> That has implications for units which don't do staging at all and run successfull -- they have to pass more components, and thus have a higher overall time they spend in RP. That time should be sub-second though, as passing through noop components is very fast. I don't see that influencing the overall unit throughput of RP (in steady state).

Right, if it is really just pass-through, I'm not concerned.
But as said in my first comment, this might not be required at all.

> There is the possibility of congestion: assume a CU with large file staging, followed by many units with no staging -- the latter units would be stalled by the staging component until the first unit passed through.

If there is no staging for the later units then I would consider the fact that they are stalled a resolvable implementation detail.

> That is somewhat elevated by the ability to have multiple concurrent stagers, but the core issue remains (only that more concurrent 'heavy' CUs are needed to stall the pipeline. That issue is up for optimization, and exists (to a lesser degree though) already for CUs which have imbalanced staging requirements. 

I'm tempted to say that we don't need multiple `complete stagers`, as these are by definition I/O bound. It would be enough to make the transfers asynchronous I would say.

> That optimization can be done on the unit scheduling level, which could prefer 'light' CUs over 'heavy' ones.
 
Right, we already have the priority mechanism in the StagingDirective too.

> Anyway, this is what I think. The alternatives would be:
> 
> return to the mode where the ExecWorker pushes out stderr/stdout -- but this stalls the ExecWorker, which will lower resource utilization, which is much more critical for high CU throughput

Agreed on the disadvantages. I don't feel like going back there. Its neither cleaner or better.

> perform staging of stdout/stderr outside of the ExecWorker, w/o going through the explicit staging states. I find that ugly: to execute a state's semantics but not calling it out in the state progression.

Agreed on not discriminating.

>  don't do staging of stdout/stderr on failed / cancelled units -- but that negates an explicitly mentioned use case.

Right, I would not be happy with dropping that feature either. Plus, this is only one of the benefits, not the only one.

**Comment by andre-merzky** [comment]
>> My proposal would be to make the CU state model strictly linear. Well, it is linear already, in the sense  that there are no loops defined (lets discuss 'restart' separately) -- but the state model does allow to skip states. Specifically, staging states can be skipped if no staging directives are set.

> I think I can agree on everything below without agreeing to the strict model. If there is no output to be staged (including stdout/stderr), why wouldn't we be able to skip?

To at least check if there is stdout/stderr to be shipped for example.  But I see your point in general, and agree.

I consider any non-linearity as an optimization.  As such, I would design for the non-optimized case, and then introduce the ability to skip components in well defined points along the path as an optimization.

**Comment by marksantcroos** [comment]
Ack both.

**Comment by andre-merzky** [comment]
this should actually be fixed in devel now, but needs testing.  Antons,  would you mind giving this a try?

**Comment by andre-merzky** [comment]
I should have been more explicit:  `cu.stdout` and `cu.stderr` should be set on FAILED units now.

**Comment by andre-merzky** [comment]
This is implemented now.
