### ISSUE TITLE
Termination Hangs...

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#563]
I see this error when the script has finished and tries to close:

Traceback (most recent call last):
  File "/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 553, in register_cancel_pilots_request
    job.cancel ()
  File "/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/saga/job/job.py", line 462, in cancel
    return self._adaptor.cancel (timeout, ttype=ttype)
  File "/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 1181, in cancel
    self.js._job_cancel(self._id)
  File "/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 705, in _job_cancel
    "Could not cancel job %s because: %s" % (pid,out))
NoSuccess: Could not cancel job 5095114 because: scancel: error: Kill job error on job id 5095114: Invalid job id specified
 (/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +705 (_job_cancel)  :  "Could not cancel job %s because: %s" % (pid,out)))
2015:04:10 15:50:41 radical.pilot.MainProcess: [DEBUG   ] Reconnected to existing ComputePilot {'uid': '5527eab723769c11510b8d3b', 'stdout': None, 'start_time': datetime.datetime(2015, 4, 10, 15, 24, 13, 38000), 'resource_detail': {'cores_per_node': 16, 'nodes': [u'c404-804', u'c405-001']}, 'submission_time': datetime.datetime(2015, 4, 10, 15, 22, 36, 457000), 'logfile': None, 'resource': u'xsede.stampede', 'log': [<radical.pilot.logentry.Logentry object at 0x7f2adc16ef90>, <radical.pilot.logentry.Logentry object at 0x7f2adc16ead0>, <radical.pilot.logentry.Logentry object at 0x7f2adc16eb10>, <radical.pilot.logentry.Logentry object at 0x7f2adc16e0d0>, <radical.pilot.logentry.Logentry object at 0x7f2adc16ef50>, <radical.pilot.logentry.Logentry object at 0x7f2adc16efd0>], 'sandbox': u'sftp://stampede.tacc.utexas.edu/work/03170/tg824689/radical.pilot.sandbox/pilot-5527eab723769c11510b8d3b/', 'state': u'Active', 'stop_time': None, 'stderr': None}
2015:04:10 15:50:41 radical.pilot.MainProcess: [ERROR   ] pmgr    5527eab723769c11510b8d3a wait for pilot  5527eab723769c11510b8d3b (Active)
2015:04:10 15:50:42 radical.pilot.MainProcess: [ERROR   ] pmgr    5527eab723769c11510b8d3a wait for pilot  5527eab723769c11510b8d3b (Active)
2015:04:10 15:50:44 radical.pilot.MainProcess: [ERROR   ] pmgr    5527eab723769c11510b8d3a wait for pilot  5527eab723769c11510b8d3b (Active)

the pmgr ... (Active) goes on.

**Comment by vivek-bala** [comment]
it has been the same for me.

**Comment by andre-merzky** [comment]
cancellation should be cleaned up now.
