### ISSUE TITLE
Session DataFrame returns 0 units

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#564]
```
>>> import os
>>> import radical.pilot.utils as rpu
>>> import pandas as pd
>>> pd.set_option('display.width', 1000)
>>> cachedir = os.getcwd()
>>> db = 'mongodb://54.221.194.147:24242/mturilli_aimesexperiments'
>>> session = '550ba0ca23769c406952b842'
>>> s_frame, p_frame, u_frame = rpu.get_session_frames(db,session,cachedir)
>>> s_frame
   finished  n_pilots  n_units                       sid       started
0  1983.019         3        0  550ba0ca23769c406952b842  1.426825e+09
```

**Comment by andre-merzky** [comment]
Hmm, this command seems to work, and gives me 64 units:

```
./bin/radicalpilot-stats -m frame -s 550ba0ca23769c406952b842
```

it is also just calling `rpu.get_session_frames(db,session,cachedir)` (see https://github.com/radical-cybertools/radical.pilot/blob/feature/aimes-experiments/bin/radicalpilot-stats#L867).  Not sure why no units show up for you... :/

**Comment by andre-merzky** [comment]
Ah, sorry, I misparsed the ticket it seems.  patch is committed - the session frame now has a number consistent with the number of entries in the unit frame...
