### ISSUE TITLE
Spurious '?' in debug output

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#570]
```
actively cancel pilot pilot.0000? state: Active
```

This seems to come from here: https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/controller/pilot_manager_controller.py#L515

On a related note: would it make more sense to let the pilot and cu ids start with '1' instead with '0'? Small detail, but saying that the '0th' pilot or '0th' CU has failed sounds a bit confusing.

**Comment by andre-merzky** [comment]
removed the `?`, thanks.

Starting from `0` sounds ok for an ID, IMHO.
