### ISSUE TITLE
extract project out of pilot desc to determine remote working dir

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#571]
Some systems (e.g. ARCHER, Titan) need some magic to determine the workdir.
In most cases we can guess it, but its not fool proof.

We have the information in the pdesc though.
We could use some macro like %{project} or so to refer to it.

Low prio. Raise prio when we get people with multiple projects.

**Comment by andre-merzky** [comment]
This is implemented in v2.
