### ISSUE TITLE
STDOUT: [... CONTENT SHORTENED ...]

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#583]
Currently many usecases in RepEx are relying on STDOUT being transferred back using cu.stdout. In rp 0.28 was introduced a limit MAX_IO_LOGLENGTH = 1024. I would like to ask what is the motivation for this? In principle I am not against going back to file transfers for large STDOUTs, but I would appreciate if such decisions would be communicated and reflected in documentation.

**Comment by andre-merzky** [comment]
At the moment, stdout/stderr are communicated via mongodb.  There are limits to collection and document sizes which we hit in the past -- the limitation on stdout/stderr transfer are used to keep the document  sizes in check.

I am not sure what the old limits were (we have limits for quite some time, but several releases ago it was indeed unlimited).  Apologies if/that this changed unannounced!  We should probably move to proper file staging for stdout/stderr anyway, which would obviously remove those limits.  I'll keep this ticket open for that purpose.

In the short run: is the current limit breaking something for you guys?

**Comment by AntonsT** [comment]
>At the moment, stdout/stderr are communicated via mongodb

I don't know how to respond to this.

>There are limits to collection and document sizes which we hit in the past -- the limitation on stdout/stderr >transfer are used to keep the document sizes in check.

Document size limit is 16 megabytes. I am not sure what is the limit on collections, but I don't think that was reached by any of the Repex usecases. 

>I am not sure what the old limits were (we have limits for quite some time, but several releases ago it was indeed unlimited).

In 0.26 this limit was not present. 

> We should probably move to proper file staging for stdout/stderr anyway, which would obviously remove > those limits. 

As mentioned before I am not against it.

>In the short run: is the current limit breaking something for you guys?

Well it does, but I will revert back to file transfers then.

**Comment by andre-merzky** [comment]
I am turning this into a documentation ticket.  We need to document that `cu.stdout`/`cu.stderr` are for human consumption, and that explicit staging should be used if the data are required by the application.

**Comment by andre-merzky** [comment]
Done.
