### ISSUE TITLE
bash segfaults on archer after pip enters infinite recursion 

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#587]
A version of bash compiled with debug flags shows that the segfault which happens in the extasy lsdmap/gromacs tutorial on archer is caused by pip entering an infinite loop, and thus bash entering and inifnite command loop, exhausting the stack,

Up to the first pip install command, the bootstrapper seems to behave ok.  I then see the following shell trace:

```
+ echo '# update radical.utils-0.28/ via pip'
+ echo '# cmd: pip install  --src '\''/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install/src'\'' --build '\''/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install/build'\'' --install-option='\''--prefix=/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install'\'' radical.utils-0.28/'
+ echo '#'
+ eval 'pip install  --src '\''/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install/src'\'' --build '\''/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install/build'\'' --install-option='\''--prefix=/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install'\'' radical.utils-0.28/'
++ pip install --src /work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install/src --build /work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install/build --install-option=--prefix=/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016553.0000-pilot.0000/rp_install radical.utils-0.28/
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
++ pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt
...
```

etc. etc.  I would not be surprised if the archer admins tried to apply a similar cert bundle fix to pip which we had to do on some other systems...  Indeed I find this in the loaded python module (`/opt/modules/packages-archer/python/2.7.6`):

```
set-alias pip "pip --cert /home/y07/y07/cse/curl/7.34.0/lib/ca-bundle.crt"
```

and that damn much looks like a recursive alias definition to me (but I don't know if module catches recursion...).  I think (but am not sure) that module's `set-alias` above translates into a `eval pip() {pip --cert ...}`, because I see that in the shell traces.

Anyway, this ticket is just a placeholder right now -- we should either redefine pip in the bootstrapper (and use our own cert bundle again), or raise a ticket with the archer folx...

**Comment by marksantcroos** [comment]
```
$ alias|grep pip
$ grep pip ~/privatemodules/pip 
set-alias pip "pip --cert certfile"
$ module load pip
$ alias|grep pip
alias pip='pip --cert certfile'
```

**Comment by andre-merzky** [comment]
A new release was pushed (@v0.30) which should solve this specific segfault problem.

**Comment by andre-merzky** [comment]
Note on the resolution: the problem disappears when we use the `python/2.7.8-ucs4` module instead, which seems not to redefine pip, and thus runs not into any recursion.
