### ISSUE TITLE
pilot agent env seeps into cu env

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#588]
Specifically, the pilot agent does `module load python/2.7.6-ucs4` on archer now, but ensemblemd uses `module load python` which loads a `python/2.7.6`, which is different on a compilation level.  CUs in that configuration crash because of a python library symbol mismatch --  a `module unload python/2.7.6-ucs4` in the CU's pre-exec 'fixes' it, but can only be considered a workaround.

We probably need to shield the CU env better, similar to what we do as `deactivate()`...

**Comment by marksantcroos** [comment]
I'm not sure whether this is really different than the situation you would get on a normal login prompt:
you get whatever arbitrary list of modules loaded by default and you adapt accordingly.

Of course we could choose to actively unload everything, but that only creates different issues (all CU's needing to load everything explicitly)

**Comment by marksantcroos** [comment]
In case if that wasn't clear: `module load python` and `module load python/2.7.6` are both NOOPs if performed after `module load python/2.7.6-ucs4`.

**Comment by andre-merzky** [comment]
We may want to unload those modules which we load in the pilot pre-exec.  Unclear is if that also unloads modules which were loaded before (via bashrc or on system level).  

I guess we first need to define what the expectation is for the CU env...

**Comment by mturilli** [comment]
Right but I do see a difference between the two options: we do not know what has been already loaded while we know that nothing has been loaded. Between the two, I would go for the latter as while it is true I have to lead everything that is needed by my kernel, at least I do not have to use a try and error to understand what has been already loaded. Does it make sense?

**Comment by andre-merzky** [comment]
Matteo: we can check what was initially loaded, via `module list` -- so restoring that state would be possible...

**Comment by mturilli** [comment]
I am not sure I follow: I am trying to see this from the user point of view. What I know about is my kernel what is needed for it to run. I do not know what RP has loaded to run its agent and, ideally, I should not care. If modules are loaded without my knowledge and something goes wrong, I will have to do a test run and see what is there and then unload accordingly. This seems less desirable to me (the user in this case) than just to be told that I have to explicitly load everything needed for my kernel to execute.

**Comment by marksantcroos** [comment]
> I am not sure I follow: I am trying to see this from the user point of view.

Dont worry, there is only one perspective for this matter :-)

**Comment by marksantcroos** [comment]
I guess what Andre wanted to convey is that we can give the CU the environment that the Agent found before it did anything. (Note that this actually needs to be done by the bootstrapper, and not the agent, so it does involve some magic)

**Comment by andre-merzky** [comment]
Thanks Mark -- yes, that was the point, to attempt to restore the env (the module set) we found when starting the bootstrapper.  Magic should not be too difficult -- yet another command line arg to the agent, I think we have still a free letter or two... :P

**Comment by andre-merzky** [comment]
We do a sufficiently good job now in recreating the original env, I believe.  This will be closed until it becomes an issue again.
