### ISSUE TITLE
Tasks are not backfilled when two pilots are active

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#591]
![run-8_late_uniform_4_rp session ip-10-184-31-85 mturilli 016556 0006](https://cloud.githubusercontent.com/assets/2323492/7437732/45ffe382-f028-11e4-8a67-c405f5ea5e92.png)
![run-128_late_uniform_2_rp session ip-10-184-31-85 mturilli 016556 0007](https://cloud.githubusercontent.com/assets/2323492/7437734/4a8cbc22-f028-11e4-9702-807540e779fe.png)

**Comment by mturilli** [comment]
Update: log files provided off-ticket, currently running further debugging tests.

**Comment by andre-merzky** [comment]
Matteo, please test the fix in devel and close if this issue is corrected - thanks!

**Comment by mturilli** [comment]
Test is ongoing.

For future reference: CU over subscription directly affects my measurements. My experiments assume that every CU is unbound until the required number of cores are effectively available. In this context, over subscription is a form of localized early binding that alters the number of CUs that run on each pilot and, as such, the overall TTC of the test workload. Can we make this - and other future form of optimization related to scheduling and binding - configurable and disabled by default?

**Comment by andre-merzky** [comment]
It now is disabled, and when being enabled again, it will be configurable.  We'll discuss other similar optimizations in advance.

**Comment by mturilli** [comment]
![rp session ip-10-184-31-85 mturilli 016560 0000](https://cloud.githubusercontent.com/assets/2323492/7478488/26d40de0-f329-11e4-9f31-8b3ae1ef6777.png)
