### ISSUE TITLE
create release procedure

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#600]
I dont think we have it yet, otherwise I would like to know its location.

What I often stumble upon is that the update version file is not merged back to the devel, which is easy to forget, and with a step by step guide, we would rely less on human brains for things like this.

**Comment by andre-merzky** [comment]
https://github.com/radical-cybertools/radical.pilot/wiki/Release-Procedure

That page would benefit from an update indeed.

**Comment by marksantcroos** [comment]
I propose you let me do the next release to see how much implicit knowledge there is?

**Comment by andre-merzky** [comment]
Ack!

**Comment by andre-merzky** [comment]
One obvously missing step (which tripped me last time as you'll remember) is to merge master back into readthedocs...

**Comment by marksantcroos** [comment]
Created a section new style "Preparing a hotfix release" on the wiki page.
Review welcome.

**Comment by andre-merzky** [comment]
Looks good to me!

**Comment by marksantcroos** [comment]
Github also has the concept of releases now, I added the latest one, which can be seen at: https://github.com/radical-cybertools/radical.pilot/releases

Not sure if it buys us much though.

**Comment by marksantcroos** [comment]
Back to the usual Release Manager :-)

**Comment by andre-merzky** [comment]
So  did you find the currently documented release procedure acceptable (+ the new pull request detour)?

**Comment by marksantcroos** [comment]
Does `currently` refer to what I wrote or the old information?

**Comment by andre-merzky** [comment]
I like the detail on the new writeup -- but the procedure seems basically the same, right?  apart from `VERSION` etc changed in devel and pulled to master instead of the way around, which does not matter much I guess.  So, given that the release is out, I take it the procedure overall works ok?

**Comment by marksantcroos** [comment]
And apart from Changelog modifications, etc.

So yes, basically the same :-)

(But how could it not have been basically the same?)

**Comment by andre-merzky** [comment]
Yeah, maybe that was a useless question... :P  So I'll adapt your test for the 'normal' (ie. not-hotfix) releases.

**Comment by andre-merzky** [comment]
Would you please review https://github.com/radical-cybertools/radical.pilot/wiki/Release-Procedure again?  Thanks.

**Comment by marksantcroos** [comment]
Yes, but will do that in the context of an actual release only.

**Comment by andre-merzky** [comment]
ack

**Comment by andre-merzky** [comment]
Mark, I assume we can close this one?

**Comment by marksantcroos** [comment]
Yes, and create a new one to find a way how to follow it ;-)
