### ISSUE TITLE
bootstrapper: rp_install should not live under virtenv

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#617]
I wondered and asked before why it is currently like that, but I now have a real reason to doubt it.

If one wants to "use" a shared VE, I think the only option is to use rp_version="DEBUG", while all the other options should also be fine?

**Comment by andre-merzky** [comment]
We can move rp_install elsewhere, np.  Inside the VE dir was convenient though, as the locking then locks both, the VE proper and rp_install.  When moving rp_install elsewhere we probably need a different collision avoidance mechanism (ie. a different lock).  I don't see any other significant implications.  The `DEBUG` mode with rp_install in the pilot sandbox shows that this works.

**Comment by marksantcroos** [comment]
Wanted to confirm that the assumption was valid.
No hurry, but something to keep in mind when we want to touch the bootstrapper again.
Can live with using debug for now.

**Comment by andre-merzky** [comment]
ack

**Comment by andre-merzky** [comment]
Do we need this implemented for supermuc?

**Comment by andre-merzky** [comment]
see also #616

**Comment by marksantcroos** [comment]
> Do we need this implemented for supermuc?

Dont know whether this is an extra complicating factor. I got it work with a static VE, so probably not.

**Comment by andre-merzky** [comment]
The question would be if it works for others with your static ve :)  But I think that this only requires the locking to be fixed, not the rp_install location...

**Comment by marksantcroos** [comment]
To get it to work also requires quick and dirty code changes.

**Comment by andre-merzky** [comment]
This is fixed now.
