### ISSUE TITLE
add runtime to cu desc

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#619]

**Comment by andre-merzky** [comment]
This is for scheduling purposes, or would you actually enforce the runtime?

**Comment by marksantcroos** [comment]
Initially for the former, but that also requires the latter to be useful.

**Comment by andre-merzky** [comment]
Do we have a use case for the enforcement?  And, for that matter, does anybody intent to work on a scheduler which uses this?
