### ISSUE TITLE
Hopper drops ssh connections after 8 hours

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#629]
To: mturilli@nersc.gov
Subject: hopper02 logoff message
From: root@hopper02.nersc.gov (root)

You have been logged off for being idle for more than 8 hour(s).

If you have questions, please call NERSC consulting
at (510)486-8600 or (800)66-NERSC.

-------------------

Username:  mturilli
Idle Time: 9:55
Tty Name:  pts/58
Pid List:   19077

-------------------

**Comment by marksantcroos** [comment]
Do you also have the point where this then fails from RP perspective?

**Comment by andre-merzky** [comment]
closed in favor of #442
