### ISSUE TITLE
id generation logic

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#630]
I my experiments I run from one script multiple sessions.

The session id's end up being:
```
rp.session.netbook.mark.016588.0011-pilot.0000
rp.session.netbook.mark.016588.0012-pilot.0001
rp.session.netbook.mark.016588.0013-pilot.0002
rp.session.netbook.mark.016588.0014-pilot.0003
rp.session.netbook.mark.016588.0015-pilot.0004
rp.session.netbook.mark.016588.0016-pilot.0005
rp.session.netbook.mark.016588.0017-pilot.0006
```
i.e. the pilot id are incremental.

Also, the unit id's become consecutive, i.e. dont start from 0 except within the first pilot.

Is this expected/intended?

**Comment by andre-merzky** [comment]
The ID counter for pilots are unique per application instance, so this is indeed expected.  If you think this is confusing, I can make them unique per session...

**Comment by marksantcroos** [comment]
My assumption was that the session was the container, and that everything inside there all numbers within would  be unique.
Whats the current rationale?

**Comment by andre-merzky** [comment]
There is not much of a rationale,  only that the implementation of the ID generation uses counters which are unique per application instance, not unique per some name space.  I can implement the latter though, its not difficult...

**Comment by marksantcroos** [comment]
Let's see how much of a pain it is to parse it in this state :)

**Comment by andre-merzky** [comment]
:)

**Comment by andre-merzky** [comment]
Soo, how difficult is it? :)

**Comment by andre-merzky** [comment]
The simplest approach to this problem would be to add a `reset_counters` call to RU, which would reset all application-scoped counters to `0`.

**Comment by andre-merzky** [comment]
This is fixed by now.
