### ISSUE TITLE
add aliases for rice machines

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#637]
"biou.rice.edu" : rice.biou
"davinci.rice.edu" : rice.davinci

**Comment by marksantcroos** [comment]
Whats the context of this request?

**Comment by vivek-bala** [comment]
So that the remote host could also be specified as biou.rice.edu or davinci.rice.edu in radical pilot (possibly in https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/configs/aliases.json). 

That is the format being used in mdkernels: https://github.com/radical-cybertools/radical.ensemblemd.mdkernels/blob/master/src/radical/ensemblemd/mdkernels/configs/amber.json

We ran into an unknown host error when eugen from Rice tried "davinci.rice.edu" as the remote host.

**Comment by marksantcroos** [comment]
The aliases were temporary for backwards compatibility, not as a general feature.
Can't you change it in the kernels?

**Comment by vivek-bala** [comment]
Oh ok. Didn't know it was temporary. I'll change it in mdkernels then.

**Comment by marksantcroos** [comment]
Thanks, appreciated.
