### ISSUE TITLE
RP fails on rice.biou: pip not found.

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#640]
Adding ```module load python/2.7.6``` in https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/configs/rice.json#L42 fixes it.

Default is python/2.6.6

**Comment by andre-merzky** [comment]
We'll pick this up once rice is used again.

**Comment by andre-merzky** [comment]
We don't have access to the machine anymore AFAIK.
