### ISSUE TITLE
proper manifest file

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#641]
With the current manifest file, shell scripts dont always get installed, which is faced when using the shell spawner.

Was able to fix/workaround it with:

``` diff
diff --git a/MANIFEST.in b/MANIFEST.in
index 399ace2..e673e94 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1 +1,2 @@
 include *.py *.json *.sh MANIFEST.in README.md CHANGES.md LICENSE.md VERSION
+recursive-include src *.sh
```

I think the current manifest file only specifies to include files in the root dir.

**Comment by andre-merzky** [comment]
Interesting!  Do you know why https://github.com/radical-cybertools/radical.pilot/blob/master/setup.py#L184  should not suffice though?  IIUC, this should cause .sh files to be picked up correctly?  

How do you  trigger the problem, is it reproducible?  Do you also have in saga (which also has the wrapper script, and its not separately listed in the manifest, it though has:

```
recursive-include src   *
```
)

**Comment by marksantcroos** [comment]
It might be related to the version of sdist or so, and yes, its repeatable. Triggered this on Titan.

But doesn't the MANIFEST file has its purpose?

Didn't have problems with SAGA there, but I'm also not sure if I could have problems with SAGA there. And like you said, SAGA does have the proper MANIFEST.

**Comment by andre-merzky** [comment]
I am still not sure I understand the purpose of the MANIFEST in the context of `pip install` -- but your proposal looks simple enough, so  I guess we just do that...

**Comment by andre-merzky** [comment]
This is in place now.
