### ISSUE TITLE
Simple bot fails with devel on localhost

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#644]
I am trying to run locally the simple bot example with the devel branches for RP,utils and saga-python

The callbacks show the pilot going from PendingActive to Failed with this error:

```
2015:06:23 17:45:07 
6361   Thread-1     radical.pilot         : [ERROR   ] pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/hadoop/RadicalPilotDev/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 346, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/hadoop/RadicalPilotDev/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 241, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "simple_bot.py", line 30, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```

In the agent.err file this error exists:

```
2015:06:23 17:45:06 6954   MainThread   radical.pilot.agent   : [INFO    ] Configuring LRMS FORK.
2015:06:23 17:45:06 6954   MainThread   radical.pilot.agent   : [INFO    ] Using fork on localhost.
2015:06:23 17:45:06 6954   MainThread   radical.pilot.agent   : [WARNING ] more cores available: using requested 1 instead of available 4.
2015:06:23 17:45:06 6954   MainThread   radical.pilot.agent   : [INFO    ] Discovered execution environment: ['localhost']
2015:06:23 17:45:06 6954   MainThread   radical.pilot.agent   : [INFO    ] Discovered launch command: ''.
2015:06:23 17:45:06 6954   MainThread   radical.pilot.agent   : [ERROR   ] LaunchMethod cannot be used: Launch command not found for LaunchMethod 'MPIEXEC'!
Traceback (most recent call last):
  File "/home/hadoop/radical.pilot.sandbox/rp.session.localhost.localdomain.hadoop.016609.0001-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 1339, in create
    return implementation(name, config, logger, scheduler)
  File "/home/hadoop/radical.pilot.sandbox/rp.session.localhost.localdomain.hadoop.016609.0001-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 1544, in __init__
    LaunchMethod.__init__(self, name, config, logger, scheduler)
  File "/home/hadoop/radical.pilot.sandbox/rp.session.localhost.localdomain.hadoop.016609.0001-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 1307, in __init__
    raise RuntimeError("Launch command not found for LaunchMethod '%s'" % name)
RuntimeError: Launch command not found for LaunchMethod 'MPIEXEC'
```

**Comment by andre-merzky** [comment]
My initial guess would be that `mpiexec` is missing :)  RP needs that to start MPI executables.  

What is confusing though is that the `simple_bot.py` only describes single-core CUs, and does not declare them to be MPI applications (https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/tutorial/simple_bot.py#L138).  The default for `MPI`` is set to `False` in the `ComputeUnitDescription` (https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_unit_description.py#L186), and the agent should only use the mpi launcher if this is set to `True` (https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3480).

I don't really understand why the mpi launcher is kicking in -- did you change the example by any chance, to test multicore CUs?

**Comment by iparask** [comment]
No, I did not.

Where should I look to give you more information?

**Comment by andre-merzky** [comment]
In order to get unstuck, you might just want to install mpiexec, eg. via openmpi.  I'll  try to reproduce the problem.

**Comment by iparask** [comment]
Did that also.
In the debug messages I found this:
...
2015:06:23 18:29:26 8390   PilotLauncherWorker-1 radical.pilot         : [DEBUG   ] Submitting SAGA job with description: {'Queue': None, 'Executable': '/bin/bash', 'TotalPhysicalMemory': None, 'WorkingDirectory': '/home/hadoop/radical.pilot.sandbox/rp.session.localhost.localdomain.hadoop.016609.0003-pilot.0000/', 'Project': None, 'WallTimeLimit': 10, 'Arguments': ['-l pilot_bootstrapper.sh', " -b 'radical.utils-0.28.tar.gz:saga-python-0.28.tar.gz:radical.pilot-v0.33-141-ga856a56-devel.tar.gz' -c '1' -d '10' -g '/home/hadoop/radical.pilot.sandbox/ve_localhost' -j 'FORK' -k 'MPIEXEC' -l 'FORK' -m 'localhost:27017' -n 'radicalpilot' -o 'SHELL' -p 'pilot.0000' -q 'CONTINUOUS' -r '10' -s 'rp.session.localhost.localdomain.hadoop.016609.0003' -t 'multicore' -u 'create' -v 'debug' -x 'lue'"], 'Error': 'agent.err', 'Output': 'agent.out', 'TotalCPUCount': 1}
...

**Comment by andre-merzky** [comment]
That looks about right -- the parameters `-j 'FORK' -k 'MPIEXEC'` specify the launch methods for non-mpi and mpi CUs.  They are defined in `src/radical/pilot/configs/local.json`.

**Comment by marksantcroos** [comment]
> I don't really understand why the mpi launcher is kicking in -- did you change the example by any chance, to test multicore CUs?

It's not kicking in to launch, this is during the discovery part.
I believe in one point in time this was non-fatal for MPI launchers, but it is now.

We can either:
- Turn the error into a warning (solves it for localhost, but hides problems on real hosts
- Somehow make local(host) a special case (and make it non-fatal)
- Remove it from the resource config

**Comment by andre-merzky** [comment]
Ah, my bad, I missed that (even though the log says so in big fat letters...) :/

Non-fatal error log sounds ok to me really -- the launching of MPI CUs will complain loud enough later on: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3487

**Comment by andre-merzky** [comment]
Mark, can I give this one to you?

**Comment by andre-merzky** [comment]
This is not fatal anymore.
