### ISSUE TITLE
all lrms's in agent need to maintain ordering of the node_list

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#650]

**Comment by andre-merzky** [comment]
Is that still valid?  Why is this so?  so that CUs which span nodes are not scattered by the scheduler?

**Comment by marksantcroos** [comment]
Well, indirectly. The main reason was that if we reorder things, then we loose track of which was the "first" and "last". Which was/is relevant for sub-agent placement.
New ORTE approach might make this less relevant though.

**Comment by andre-merzky** [comment]
Is this still relevant for libORTE?  Otherwise I am not sure how to enforce this, sounds more like a documentation issue?

**Comment by andre-merzky** [comment]
Can you give an update, please?

**Comment by marksantcroos** [comment]
Yeah, its a "documentation" issue. Its still relevant for ORTE if there are sub-agents on the worker nodes.

**Comment by andre-merzky** [comment]
This turned out to be not relevant - we don't care if the agent is placed in the middle.
