### ISSUE TITLE
output of pre and post doesn't end up in stderr/stdout

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#656]
Is that a feature or a bug?

**Comment by andre-merzky** [comment]
For applications which parse stout it should not show up, for users looking to debug things it would be nice.  I don't think we want to make it configurable, so *not* having it in stderr/stdout seems the safer option.  We should make sure it ends up in the log files, and possibly in the DB entries (unit.log).

**Comment by andre-merzky** [comment]
Closed due to lack of activity.
