### ISSUE TITLE
Pilot Data staging timing

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#664]
Hey guys,

is there a way to find the time needed for the pilot to stage data via the the pilot's data directives?

Thank you,
Giannis

**Comment by andre-merzky** [comment]
This is a synchronous call (ie. the call only returns when the data has been staged), so you can time that externally.  At this point it is not available as part of the profile data -- but it will eventually be added.  Happy to leave the ticket open until then...

**Comment by marksantcroos** [comment]
Giannis, did you actually mean the staging on the pilot only, or in general?
If so, then see #268 too.

**Comment by iparask** [comment]
Yes, I mean the staging on the pilot only. #268 actually covers it since it is more general.

Fell free to close this one if you also agree that there is an overlap
