### ISSUE TITLE
many pilot (aka ssh connection) issues at scale

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#672]
On OSG, during the lifetime of a session I launch 50 pilots to one submit node.

For one reason or the other, in no point in time did I have 50 pilots running concurrently (e.g. because walltime ran out of the first while others were still launching)

However, I still see 50 "master" channels open at the end of the application:
```
netbook:configs mark$ ps uwax|grep ssh|grep ControlMaster|wc -l
     155
netbook:configs mark$ ps uwax|grep ssh|grep Permit|wc -l
      51
```

This is just one of the many issues that we will encounter while scaling in the direction of many pilots.

**Comment by andre-merzky** [comment]
This is fixed now, via bulk ops.
