### ISSUE TITLE
some cu's stay stuck in PendingAgentInputStaging

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#673]
and therefore umgr.wait_units() will never return.

50 pilots

backfilling scheduler

I think what happens is that pilots disappear during scheduling and that units get assigned to non-living pilots.

**Comment by marksantcroos** [comment]
So I'm happy to threat some errors higher in the stack, but at least RP should mark them as failed I guess.

**Comment by andre-merzky** [comment]
many pilots is certainly not a use case we have optimized (or even cared for).  The above though sounds like an error even in the small-number-of-pilots case, we probably did not trigger it though...   We have some code in place to recover units from failing pilots, but that is only for the backfilling scheduler.  This should probably be caught on level up, on the generic scheduler layer.

https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/scheduler/backfilling.py#L186

**Comment by marksantcroos** [comment]
> We have some code in place to recover units from failing pilots, but that is only for the backfilling scheduler.

Obviously I was using that scheduler already so that doesn't cut it.

**Comment by andre-merzky** [comment]
Units are now canceled for failing pilots.
