### ISSUE TITLE
Using /bin/bash executable with the SHELL spawner does not seem to load/pass the env

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#676]
I am trying to use /bin/bash as the executable for one of the analysis stages. I use the '-l' and '-c' arguments as well to keep the same environment during execution.
```
cud.pre_exec = ['module load intel/15.0.2','module load boost','module load gromacs']
cud.executable     = "/bin/bash"
cud.arguments      = ['-l','-c',"module list"]
```

In STDERR:
No modules loaded

This can be reproduced with the getting started example: https://gist.github.com/vivek-bala/9f0fc1fbeaeeb1708017

**Comment by andre-merzky** [comment]
`bash -l` will create a new login shell, which is likely not inheriting the module list from the shell instance where the preexec commands were executed.  Please try again without `-l`.

**Comment by vivek-bala** [comment]
I removed '-l' and I still encounter the same.

cmd: https://gist.github.com/vivek-bala/a58ff184f33a6f76e66e

**Comment by vivek-bala** [comment]
This might not be due to /bin/bash. I load modules for amber with 'pmemd' executable. 

In STDERR:
//work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016654.0024-pilot.0000/pilot.0000-ExecWorker-0/71985.0/cmd: line 35: pmemd: command not found

But I can execute python files (which contain gromacs commands within) successfully.

**Comment by andre-merzky** [comment]
It might well be the bash startup.  Bash sources/runs a number of initialization files on startup -- the exact sequence and oder depends on several factor.  Have a look at [this Blog](http://blog.flowblok.id.au/2013-02/shell-startup-scripts.html), and specifically at [this picture](http://blog.flowblok.id.au/static/images/shell-startup-actual.png).  If any of the files used during bash startup has a `module purge` (or similar), you'll loose your settings from the pre-exec.

Do you need to run bash?  Is your executable a lengthy script or so?

**Comment by andre-merzky** [comment]
I should add: you may want to use /bin/sh for shell scripts, as that has a somewhat less confused startup sequence, and is thus somewhat easier to control...

**Comment by vivek-bala** [comment]
But in this example, I am just loading the modules and then listing them.

In the science workloads, I don't think there are any module purges or any commands that would modify the environment. 

The place I require /bin/bash is to pipe the input to gromacs command (since the gromacs command prompts the user for intermediate input), so I basically do a /bin/bash '-l' '-c' 'echo 2 | gromacs command' .

**Comment by vivek-bala** [comment]
I am again confused as to why I might see this error with the amber case where I am not using /bin/bash.

**Comment by vivek-bala** [comment]
I have updated the repo so that you can reproduce the error. You can follow the documentation: http://extasy.readthedocs.org/en/extasy_0.2/pages/grlsd.html.

You would notice that the gromacs (simulation) stage and pre_lsdmap (analysis) stage have the same module loads/ env setups, but the pre_lsdmap does not recognize the "gromacs" command (they are both invoked the same way - via a python file).

**Comment by andre-merzky** [comment]
Hi Vivek -- would you mind running the  following commands on stampede:

```
login1.stampede(8)$ module purge
login1.stampede(9)$ module list
No modules loaded
login1.stampede(12)$ module load TACC
login1.stampede(13)$ module list
Currently Loaded Modules:
  1) TACC-paths   2) Linux   3) cluster-paths   4) intel/13.0.2.146   5) mvapich2/1.9a2   6) xalt/0.4.6   7) cluster   8) TACC
login1.stampede(14)$ /bin/bash "-c" "module list"
Currently Loaded Modules:
  1) TACC-paths   2) Linux   3) cluster-paths   4) intel/13.0.2.146   5) mvapich2/1.9a2   6) xalt/0.4.6   7) cluster   8) TACC
```

This is basically what your script does I think -- I copied the bash line from your gist. What happens for you?

If the above works, could you please also try this:  create a file t as below, and  run so:

```
login1.stampede(34)$ cat t
module purge
echo 1
module list
module load TACC
echo 2
module list
echo 3
/bin/bash "-c" "module list"
echo 4
login1.stampede(35)$ ((bash -l t) 1>tout 2>tout 0</dev/null )&
```

what is then in 'tout' (after some seconds)?

Thanks

**Comment by vivek-bala** [comment]
Here are the outputs:

```
$ module purge
login2.stampede(3)$ module list
No modules loaded

login2.stampede(4)$ module load TACC
login2.stampede(5)$ module list

Currently Loaded Modules:
  1) TACC-paths   2) Linux   3) cluster-paths   4) intel/13.0.2.146   5) mvapich2/1.9a2   6) xalt/0.4.6   7) cluster   8) TACC

login2.stampede(6)$ /bin/bash "-c" "module list"

Currently Loaded Modules:
  1) TACC-paths   2) Linux   3) cluster-paths   4) intel/13.0.2.146   5) mvapich2/1.9a2   6) xalt/0.4.6   7) cluster   8) TACC
```
```
$ cat t
module purge
echo 1
module list
module load TACC
echo 2
module list
echo 3
/bin/bash "-c" "module list"
echo 4
$ ((bash -l t) 1>tout 2>tout 0</dev/null )&
[1] 20493
```

**Comment by andre-merzky** [comment]
It seems to be more of the same module loading fuckery on Stampede.  When I try to reduce it to a couple of commands, then I see the `80: no such command` thingie popping up again... :/  Which also explains of course why we see it with the SHELL spawner and not with the POPEN spawner...

**Comment by andre-merzky** [comment]
minimal example:

```
c559-001.stampede(37)$ cat d.sh
#!/bin/sh

shopt -s checkwinsize
export COLUMNS=80
module load intel/15.0.2
module load boost
module load gromacs
module load python

trjconv 
```

```
c559-001.stampede(35)$ /usr/bin/ssh -o StrictHostKeyChecking=no localhost sh `pwd`/d.sh

/home1/01083/tg803521/radical.pilot.sandbox/rp.session.cameo.merzky.016656.0006-pilot.0000/pilot.0000-ExecWorker-0/130281.0/d.sh: line 10: trjconv: command not found
```

```
c559-001.stampede(36)$ sh d.sh

The following have been reloaded with a version change:
  1) intel/13.0.2.146 => intel/15.0.2  2) mvapich2/1.9a2 => mvapich2/2.1

...
GROMACS:      gmx trjconv, VERSION 5.0.4
Executable:   /opt/apps/intel15/mvapich2_2_1/gromacs/5.0.4/bin/gmx
...
```

**Comment by andre-merzky** [comment]
Headnode:

```
login1.stampede(5)$ ssh localhost 'bash -c "module load gromacs; module list"'

Currently Loaded Modules:
  1) TACC-paths      4) intel/13.0.2.146   7) cluster
  2) Linux           5) mvapich2/1.9a2     8) TACC
  3) cluster-paths   6) xalt/0.4.6         9) gromacs/5.0.1

```

compute node:
```
c559-001.stampede(44)$ ssh localhost 'bash-c "module load gromacs; module list"'
bash: bash-c: command not found
c559-001.stampede(45)$ ssh localhost 'bash -c "module load gromacs; module list"'
Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "gromacs"

   Try: "module spider gromacs" to see how to load the module(s).


No modules loaded
```

**Comment by andre-merzky** [comment]
This is now an XSEDE ticket (#34279)

**Comment by andre-merzky** [comment]
Vivek -- has this been resolved along with the other stampede env issues?

**Comment by vivek-bala** [comment]
The default spawner is back to POPEN I think, I see no issues with that anymore on Stampede. Do you want me to test with SHELL ?

**Comment by andre-merzky** [comment]
If that is not too much effort, I would appreciate it.  Otherwise I'll look into it at a later point.  There is no need to switch away from popen at the moment, so this is not urgent I think...

**Comment by vivek-bala** [comment]
Sure, will do. Just wanted to confirm before I test.

**Comment by andre-merzky** [comment]
Thanks! :)

**Comment by vivek-bala** [comment]
```
cud.pre_exec = ['module load TACC','module load intel/15.0.2','module load boost','module load gromacs']
cud.executable     = "/bin/bash"
cud.arguments      = ['-l','-c',"module list"]
```

POPEN:
```
$ cat STDERR 

The following have been reloaded with a version change:
  1) intel/13.0.2.146 => intel/15.0.2  2) mvapich2/1.9a2 => mvapich2/2.1


If you want to use the GPU version, remember to load cuda/6.0 (only available on the gpu and gpudev queues)
	 module load cuda/6.0


Currently Loaded Modules:
  1) xalt/0.6   3) intel/15.0.2   5) boost/1.55.0  (m)
  2) TACC       4) mvapich2/2.1   6) gromacs/5.0.4

  Where:
   m:  built for host and native MIC
```

SHELL:
```
$ cat STDERR 
No modules loaded
```

**Comment by vivek-bala** [comment]
Trying out prev suggestions,

1)
```
cud.pre_exec = ['module load TACC','module load intel/15.0.2','module load boost','module load gromacs']
cud.executable     = "/bin/bash"
cud.arguments      = ['-c',"module list"]
```

SHELL:
```
$ cat STDERR
No modules loaded
```

2)
```
cud.pre_exec = ['module load TACC','module load intel/15.0.2','module load boost','module load gromacs']
cud.executable     = "/bin/sh"
cud.arguments      = ['-c',"module list"]
```

SHELL: STDERR and STDOUT are both empty

**Comment by andre-merzky** [comment]
module loading has been fixed on stampede.
