### ISSUE TITLE
update_unit_state timestamp input

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#679]
As it is now the timestamp of a state update depends on when the call of the same named method is taking place. 

Shouldn't be possible to set the timestamp of a state transition?

I think it is needed in order to set the timestamp correctly for the state transition of a YARN application, but it may be needed in general.

**Comment by andre-merzky** [comment]
the `prof` method in the feature/module_profiling accepts a `timestamp` parameter which will make this possible.

https://github.com/radical-cybertools/radical.pilot/blob/feature/module_profiling/src/radical/pilot/utils/prof_utils.py#L115

**Comment by iparask** [comment]
I am closing this ticket. I got my answer
