### ISSUE TITLE
Error running agent: Not enough cores available (24) to satisfy allocation request (48)

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#682]
For both RP 0.34 and RP v0.34-273-g5361049@devel Amber "hello world" example on COMET results in:

```
Error running agent: Not enough cores available (24) to satisfy allocation request (48)
```

When specifying pilot size 48 and having 48, 1 core CU's

**Comment by andre-merzky** [comment]
Antons, do you have a code example which triggers that?   Like, a set of CU and Pilot descriptions?

Thanks, Andre.

**Comment by andre-merzky** [comment]
Antons, could you please use the `feature/session_recording` branch to run the same application, and set `RADICAL_PILOT_RECORD_SESSION=/tmp/rp_session_records/`?  After the application run, you should see a bunch of json files beneath that directory.  Could you send the pilot description and unit descriptions in question (or tarball them)?

Thanks!  (and sorry for abusing you as tester for the session recording -- but if that works, it will make debugging somewhat easier, as it separates the RP layer from the application layer...)

**Comment by AntonsT** [comment]
>Antons, do you have a code example which triggers that? Like, a set of CU and Pilot descriptions?

Yes Andre: https://github.com/radical-experiments/radical.canon/blob/master/amber/medium/trivial-comet.py

**Comment by andre-merzky** [comment]
Thanks!

**Comment by AntonsT** [comment]
Andre, archive with json files can be found at: https://github.com/radical-experiments/radical.canon/blob/master/amber/medium/rp.session.antons-pc.antons.016662.0012.tar.gz

**Comment by AntonsT** [comment]
This is with RP feature/session_recording branch.

**Comment by AntonsT** [comment]
You are welcome.

**Comment by marksantcroos** [comment]
Is this with SAGA devel too?

**Comment by AntonsT** [comment]
No

**Comment by marksantcroos** [comment]
Ok, when using RP devel its generally a good idea to use devel from our other software too as the progress is often in tandem.

**Comment by AntonsT** [comment]
Works with all devel
