### ISSUE TITLE
RP v0.34 MPI "Hello World" fails on stampede

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#685]
with:

```
[cli_121]: aborting job:
Fatal error in PMPI_Init_thread:
Other MPI error, error stack:
MPIR_Init_thread(436)...:
MPID_Init(371)..........: channel initialization failed
MPIDI_CH3_Init(285).....:
MPIDI_CH3I_CM_Init(1106): Error initializing MVAPICH2 ptmalloc2 library
```

Code: [stampede_mpi.py](https://github.com/radical-experiments/radical.canon/blob/master/amber/medium/stampede_mpi.py)

[hello_mpi.py](https://github.com/radical-experiments/radical.canon/blob/master/amber/medium/hello_mpi.py)

I am not sure if there is already a ticket regarding this, so I am opening a new one.

**Comment by marksantcroos** [comment]
How does this work with devel?

**Comment by AntonsT** [comment]
Stampede is now on maintenance, so I can't check.

**Comment by andre-merzky** [comment]
Antons, can you please check once you are back?  Thanks!

**Comment by AntonsT** [comment]
>How does this work with devel?

With devel it results in:

```
Traceback (most recent call last):
  File "stampede_mpi.py", line 8, in <module>
    import radical.pilot as rp
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from .scheduler  import *
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 21, in <module>
    logger = ru.get_logger('radical.pilot')
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/utils/logger.py", line 141, in get_logger
    logger.setLevel(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 1128, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 187, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'info'
```

With RP.0.35 it seems to work.

Thanks,
Antons

**Comment by marksantcroos** [comment]
Does your RADICAL_PILOT_VERBOSE variable happen to have 'info' as value? If so, can you try to make it capitals?

**Comment by AntonsT** [comment]
>Does your RADICAL_PILOT_VERBOSE variable happen to have 'info' as value?

Of course it does! I am using RP according to [documentation](http://radicalpilot.readthedocs.org/en/stable/developer.html#debugging)

**Comment by marksantcroos** [comment]
Ah, so you were the one that read it.

**Comment by marksantcroos** [comment]
Andre, I guess this is related to your recent logging changes?

**Comment by AntonsT** [comment]
With 'INFO' flag for rp (for both devel-stack and master), STDERR at CU level contains:
```
WARNING: Error in initializing MVAPICH2 ptmalloc library.Continuing without InfiniBand registration cache support.
``` 
 CU's are reported as done and output of hellp_world.py is as expected, not sure what would happen if more complex MPI code would be executed.

**Comment by andre-merzky** [comment]
FWIW, the log-level error is fixed in a branch.

**Comment by andre-merzky** [comment]
This is considered fixed by now.
