### ISSUE TITLE
pyzmq installation fails on osx without pre-installed zmq libraries

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#688]
`sudo port install zmq` helped me out (so would have a `brew` I guess).

**Comment by andre-merzky** [comment]
Do you know why the pip-installs-things-on-the-fly mode does not work?  Missing / incompatible compiler?

**Comment by marksantcroos** [comment]
No, more subtile C++ error. Didn't want to look into it.

**Comment by andre-merzky** [comment]
:/

**Comment by andre-merzky** [comment]
Didn't pop up anymore, and out of scope.
