### ISSUE TITLE
modules changes on stampede

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#689]
I think the modules 'cluster' and 'Linux' have been removed from Stampede. RP-devel currently fails on stampede since it tries to load these modules. Removing the two from the config worked.

**Comment by andre-merzky** [comment]
Thanks Vivek!

How are modules holding up otherwise after the maintenance?  Are the application codes still loading ok?

**Comment by vivek-bala** [comment]
Yes, generally they seem to be stable. I am facing no problems with the specific modules I have been using for my applications. 

Also, want to point out that although mpi4py is available with python/2.7.9 on Stampede. I had to manually set the PATH to ```/opt/apps/intel13/mvapich2_1_9/python/2.7.9/lib/python2.7/site-packages/mpi4py```

**Comment by marksantcroos** [comment]
Does the latter require action? I notice intel13 though ...

**Comment by vivek-bala** [comment]
Sorry, I didn't get your question.

**Comment by marksantcroos** [comment]
I meant does the issue with setting a manual path means this ticket can not be closed? And at the same time I noticed you mention intel13 which sounds like a conflict with the new defaults.

**Comment by vivek-bala** [comment]
> I meant does the issue with setting a manual path means this ticket can not be closed?

No, I just wanted to notify about it.

> And at the same time I noticed you mention intel13 which sounds like a conflict with the new defaults.

I require netcdf and hdf5 modules on Stampede which are only available with intel/13.0.2.146.
