### ISSUE TITLE
record orte version in session/profile

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#692]

**Comment by marksantcroos** [comment]
A combination of these two should probably suffice:
```
> orte-info | head -2
                Open RTE: 3.0.0a1
                Open RTE repo revision: dev-2344-g7a7d4f2
```

**Comment by andre-merzky** [comment]
This should go to the log file, not the profile, I guess...

**Comment by marksantcroos** [comment]
And jump through another hoop to get it out?

**Comment by andre-merzky** [comment]
Depends on where you want to get it out...  But that raises a good point: we now have a mechanism to fetch profile -- it would be easy to expand to also fetch logfiles etc...
