### ISSUE TITLE
SuperMic not in XSEDE config

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#693]
Supermic is not in the configuration file of xsede. 

So the label cannot be xsede.supermic as it is mentioned in the testing doc. I will use lsu.supermic.

Error Message:
test_mpi.py
no config found for xsede.supermic
known targets: das4.fs2, nersc.hopper_ccm, iu.bigred2, radical.tutorial, nersc.edison_ccm, xsede.stampede, xsede.trestles, nersc.edison, ncsa.bw, futuregrid.bravo, xsede.gordon, stfc.joule, ornl.titan, ncar.yellowstone, xsede.comet, iu.bigred2_ccm, rice.davinci, lrz.supermuc, nersc.hopper, xsede.blacklight, futuregrid.india, lsu.supermic, epsrc.archer, local.localhost

**Comment by andre-merzky** [comment]
Thanks Ioannis -- yes, please use the LSU entry.  Mark, can I move the entry to xsede, or is there a good reason to open a new namespace for it?

**Comment by marksantcroos** [comment]
SuperMIC is not an XSEDE machine.

**Comment by andre-merzky** [comment]
Interesting you say that.  The address though is `torque+ssh://supermic.cct-lsu.xsede.org`, and it is (for me at least) listed on `https://www.xsede.org/group/xup/my-xsede` as XSEDE resource (and uses my xsede credentials).  Has that status changed somehow?

**Comment by marksantcroos** [comment]
Per http://www.hpc.lsu.edu/docs/guides.php?system=SuperMIC, "40% towards XSEDE".

Ultimately I couldn't care less, I've never been in favor of the xsede denomination though.

**Comment by marksantcroos** [comment]
And to answer your other question:
```
$ host supermic.cct-lsu.xsede.org
supermic.cct-lsu.xsede.org is an alias for smic1.hpc.lsu.edu.
```
But that is true for most other systems in the xsede resource class.

**Comment by andre-merzky** [comment]
supermic is now in the xsede namespace, but retains an LSU alias.
