### ISSUE TITLE
ComputeUnit 'unit.000224' state changed from 'Failed' to 'Done'.

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#695]
For one of the repex runs on Stampede I got this state transition info:
```
2015:08:24 11:07:52 3185   Thread-3     radical.pilot         : [INFO    ] RUN ComputeUnit 'unit.000224' state changed from 'Failed' to 'Done'.
```

According to current CU state transition diagram this should not happen. Am I right?

[terminal](https://gist.githubusercontent.com/AntonsT/6a5ab7443a8ab87b6ec9/raw/3b4cac271c5e8fdac123be4d84d6825244c50f86/terminal-out) 
[agent.err](https://gist.githubusercontent.com/AntonsT/a7f681d24b9f73570cb8/raw/7881c81c6672838434907ab2057a8df80a112b37/agent.err)
[agent.out](https://gist.githubusercontent.com/AntonsT/71fda6cf7ca149ca7c16/raw/31b63970cfa02fc3ba5d6c5bc631562749c27c63/agent.out)
[agent.log](https://gist.githubusercontent.com/AntonsT/0e921679e416cefc5d80/raw/49f9014fe5887443bf75cfa8824127632f6ed83e/agent.log)

**Comment by marksantcroos** [comment]
Yes, that should not happen indeed, but we are aware of race conditions.
This is with the released version, right? Some of them have been fixed meanwhile.

**Comment by andre-merzky** [comment]
I'm afraid the pilot reports `v0.34-286-gaec4093@devel` :(  I'll try to track this down.

**Comment by andre-merzky** [comment]
PS.: Antons, please always report the version you use :)

**Comment by marksantcroos** [comment]
Hmm, the agent.log reports this:
```
2015-08-24 10:06:37,456 - radical.pilot.agent - INFO - Using RADICAL-Utils version v0.29
2015-08-24 10:06:37,457 - radical.pilot.agent - INFO - Using RADICAL-SAGA  version v0.29
2015-08-24 10:06:37,457 - radical.pilot.agent - INFO - Using RADICAL-Pilot version v0.34 ($Id$)
```

**Comment by andre-merzky** [comment]
Hmm, indeed.  Lets wait for Antons then to clarify...

**Comment by AntonsT** [comment]
RP version is: v0.34-286-gaec4093@devel
Saga version reports: v0.29 without a devel tag for some reason, but I am sure I have installed devel
Utils reports: v0.29-9-g3387b95@devel

**Comment by andre-merzky** [comment]
Antons, I pushed a branch `fix/issue_695`, could you give that a try, please?  The problem seems to occur if one file staging fails, and a later one succeeds (basically, a break was missing to abort further attempts).

**Comment by andre-merzky** [comment]
We consider this fixed now in devel, please reopen if the problem persists!
