### ISSUE TITLE
examples/getting_started_local.py fails

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#697]
```
$ radicalpilot-version 
v0.34-288-gf765850@devel
$ sagapython-version 
v0.29
$ sw_vers 
ProductName: Mac OS X
ProductVersion: 10.10.5
BuildVersion: 14F27
```
Note: radicalutils-version does not exist.

Upon running ```examples/getting_started_local.py```, all the CUs get up to the ```Allocating``` status and then hang there. Logs have no error or warning, the pilot reaches the end of its walltime, get canceled, and then the scripts hangs indefinitely. Cancellation (Ctrl+c) does work.

**Comment by andre-merzky** [comment]
Would you mind sending the agent.* files from the sandbox?  Thanks!

**Comment by marksantcroos** [comment]
> Note: radicalutils-version does not exist.

This is fixed now in a branch and will hit a release at some point.

**Comment by andre-merzky** [comment]
Matteo, I am going to close this, as we believe it is addressed, but please reopen if still pops up for you, obviously.  Thanks!
