### ISSUE TITLE
RP devel installation fails

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#709]
I created a new Ubuntu VM in order to test the feature/yarn_devel_merge branch. When I tried to install RP, I got errors when it was trying to install libzmq as a Python extension.

The way I solved was by installing the python-dev package in Ubuntu. I can give it a try again to another VM if you want to show you the exact errors

**Comment by marksantcroos** [comment]
Thanks for reporting.
We've seen similar and other deployment issues on the requirements for zmq on other systems too, so its good to get an overview of the problems and their solutions.

**Comment by andre-merzky** [comment]
python devel is indeed required for all python modules which have compiled elements.  I thought though that pymongo already required that anyway -- did that change recently?

**Comment by iparask** [comment]
When I installed the released version from pip not the devel branches, it did not request anything.

I will check it again if pymongo needs it and come back

**Comment by andre-merzky** [comment]
That answers it already, thanks.  Then yes, the python-dev dependency is new. Hmm....

**Comment by andre-merzky** [comment]
```
(ve)merzky@cameo:/tmp $ pip install pymongo
Downloading/unpacking pymongo
  Downloading pymongo-3.0.3.tar.gz (419kB): 419kB downloaded
  Running setup.py egg_info for package pymongo
    
Installing collected packages: pymongo
  Running setup.py install for pymongo
    building 'bson._cbson' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/_cbsonmodule.c -o build/temp.linux-x86_64-2.7/bson/_cbsonmodule.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/time64.c -o build/temp.linux-x86_64-2.7/bson/time64.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/buffer.c -o build/temp.linux-x86_64-2.7/bson/buffer.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/encoding_helpers.c -o build/temp.linux-x86_64-2.7/bson/encoding_helpers.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bson/_cbsonmodule.o build/temp.linux-x86_64-2.7/bson/time64.o build/temp.linux-x86_64-2.7/bson/buffer.o build/temp.linux-x86_64-2.7/bson/encoding_helpers.o -o build/lib.linux-x86_64-2.7/bson/_cbson.so
    building 'pymongo._cmessage' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c pymongo/_cmessagemodule.c -o build/temp.linux-x86_64-2.7/pymongo/_cmessagemodule.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/buffer.c -o build/temp.linux-x86_64-2.7/bson/buffer.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pymongo/_cmessagemodule.o build/temp.linux-x86_64-2.7/bson/buffer.o -o build/lib.linux-x86_64-2.7/pymongo/_cmessage.so
    
Successfully installed pymongo
Cleaning up...
```

**Comment by iparask** [comment]
So does  it need python-dev or not?

Let me check again. I will create a clean VM and try to instal pymongo. If it needs it I will see it.

I will also try to install RP, after that. If pymongo fails RP also will fail no matter what. But if RP succeeds then there is something going on there.

**Comment by iparask** [comment]
So, the results are a bit weird... In the gists [1] and [2] you can see that both pymongo asked for python-devel, but their installation did not fail.

Also, what is interesting is that even with those fails from python-dev, I was able to run simle_bot locally using the MongoDB we have in Amazon.

[1] https://gist.github.com/iparask/f62174bd92564e327a52
[2] https://gist.github.com/iparask/3fced4332801e3458082

**Comment by marksantcroos** [comment]
The "optimized" compiled installation is optional. There is a native python version as fallback.

**Comment by andre-merzky** [comment]
Mark, that makes sense.  I don't think there is  such an option for zmq.  Do you consider the dependency on python-devel a problem, ie. so much of a problem that is questions the choice of zmq?  I guess not so much on the client machine, really, as most packaging systems will have it readily available -- but we also need that requirement on the target resource...

**Comment by marksantcroos** [comment]
I didnt find a system where I ultimately didn't manage to compile it, so its more about robustness than anything else. So I dont consider it a show-stopper currently.

**Comment by andre-merzky** [comment]
Ok.  I'll leave the ticket open until we have that properly documented.

**Comment by iparask** [comment]
closing as outdated. Haven't seen this issue from then
