### ISSUE TITLE
RP Launching fails with anaconda

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#716]
Hello guys,

when I try to run the simple_bot example on Stampede I get this error:

2015:09:10 19:29:37 142501 PilotLauncherWorker-1 radical.pilot         : [ERROR   ] DoesNotExist: file copy failed: mput  "/opt/anaconda/lib/python2.7/site-packages/radical/utils/radical.utils-0.35.tar.gz" "/work/03170/tg824689/radical.pilot.sandbox/rp.session.radical-5.jupyter.016688.0003-pilot.0000/radical.utils-0.35.tar.gz"

In the local machine I have Anaconda as you can see. The file does not exist. I tried to reinstal with pip but again it did not create the specific file.

Thank you

**Comment by marksantcroos** [comment]
Ah yes, there is that part on the client side too. I didn't think of it, but it doesn't surprise me either given that anaconda does all of this differently.

**Comment by iparask** [comment]
Okay I see.

But I remembered that Anaconda can also be installed in user space. So, I installed Anaconda in user space with no sudo privileges and by just doing pip install and actually the example runs properly on Stampede.

Now, the question I have is the difference in Anaconda or how RPs installation runs?

Also, if install RP as a system package and not through a virtualenv will I face similar problems? The last is a bit off topic, but I hope you see where I am going.

**Comment by marksantcroos** [comment]
> Now, the question I have is the difference in Anaconda or how RPs installation runs?

I think the answer is the interaction between the two, but that might depend on what you exactly meant ;)

> Also, if install RP as a system package and not through a virtualenv will I face similar problems? The last is a bit off topic, but I hope you see where I am going.

I really don't know. I guess the only way to find out is to try it.

**Comment by andre-merzky** [comment]
sdist building fails also for wheels...

**Comment by marksantcroos** [comment]
And if you upgrade pip to 1.4.1 (`pip install --upgrade pip==1.4.1`)
Then uninstall RU, SAGA and RP and install again.

**Comment by andre-merzky** [comment]
Possibly include `bdist_wheel` in the setup.py check on sdist build

**Comment by iparask** [comment]
I think it is time to close this one, right?

**Comment by andre-merzky** [comment]
Yes, indeed :)
