### ISSUE TITLE
Schema checking from Pilot Manager Controller

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#718]
Hello guys,

in the pilot manager controller there is a schema check, lines 408 - 415, where it checks for ssh or gsissh with a + in front assuming that there are two ways for the job_manager_endpoint. I want to add chameleon and I used just ssh://..... as the url. That may not be correct, but I do not think that it violates how a configuration file should be.

Do you think that I should add a check without the + or that the configuration should change. You can see how I wrote the configuration in the resource_yarn.json that exists in the feature/yarn_devel_merge branch. 

Thank you!

**Comment by marksantcroos** [comment]
Your Chameleon entry looks good regarding the endpoints.

There was a recent change to PilotManagerController that you might have in your branch already or not, so currently it looks like:

``` python
# The PTYShell will swallow in the job part of the scheme
if js_url.scheme.endswith('+ssh'):
    js_url.scheme = 'ssh'
elif js_url.scheme.endswith('+gsissh'):
    js_url.scheme = 'gsissh'
elif js_url.scheme == 'fork':
    pass
elif '+' not in js_url.scheme:
    js_url.scheme = 'fork'
else:
    raise Exception("Are there more flavours we need to support?! (%s)" % js_url.scheme)
```

I would propose to change it to the following:

``` python
# The PTYShell will swallow in the job part of the scheme
if js_url.scheme.endswith('+ssh'):
    # For remote adaptor usage over ssh, us that here
    js_url.scheme = 'ssh'
elif js_url.scheme.endswith('+gsissh'):
    # For remote adaptor usage over gsissh, use that here
    js_url.scheme = 'gsissh'
elif js_url.scheme in ['fork', 'ssh', 'gsissh']:
    # Use the scheme as is for non-queuing adaptor mechanisms
    pass
elif '+' not in js_url.scheme:
    # For local access to queueing systems use fork
    js_url.scheme = 'fork'
else:
    raise Exception("Are there more flavours we need to support?! (%s)" % js_url.scheme)
```

You agree that would address your issue?

**Comment by iparask** [comment]
It did! Thank you Mark!

I am closing this ticket.

**Comment by marksantcroos** [comment]
Good to know. I'll actually open the ticket again to make the change to devel too.

**Comment by iparask** [comment]
Merged in devel
