### ISSUE TITLE
toggle rp_version in resource configs at release time

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#727]
Ideally for released versions, on bootstrap the exact version would be installed once.
And in all (devel) branches we would install the debug version.

**Comment by andre-merzky** [comment]
maybe something like:

```
if ! test -z RADICAL_DEBUG; then
  if rp_install_module.check_version() < this_module.check_version(); then
    pip uninstall rp_install_module
    pip install --upgrade this_module
  fi
fi
```

?

or do you rather envision something which hard codes a different rp_version in the config file as part of the release procedure?  But that would not necessarily be able to trigger a conditional update I think...

**Comment by marksantcroos** [comment]
> or do you rather envision something which hard codes a different rp_version in the config file as part of the release procedure?

Yes.

> But that would not necessarily be able to trigger a conditional update I think...

We could hardcode the version dependency?

**Comment by marksantcroos** [comment]
As part of that, I would probably remove the rp_version from most config files, and rather change the default.

**Comment by andre-merzky** [comment]
I agree with the default - but similar to our previous discussion today, I would actually leave the default in for verbosity :)  But that is just me.

About the hard coded dependency: any proposal on how this would look like?  you mean something like adding `rp_install_version : 0.35`?  That would then fix the version unless RP_DEBUG is set or something?

**Comment by andre-merzky** [comment]
VE creation is now per RP version.
