### ISSUE TITLE
How to pass credentials to different machines?

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#743]
I am reading the documentation and I cannot find how I can specify which credentials are for which pilot description.

Is there a way to do it or I should include all the credentials in the same Session context and somehow all will work out?

There is also the solution to create a different session for each pilot.

**Comment by andre-merzky** [comment]
If those credentials are all ssh or gsissh keypairs, then you can indeed all add them to the same session, and things should work out magically.  If you want to use multiple username/password pairs, things get more complicated.  So, before going further, which is it? :)

**Comment by iparask** [comment]
They are ssh key pairs! Okay thank you!
None the less, The documentation should say that a session can accept multiple contexts

**Comment by andre-merzky** [comment]
Agreed.  I already added the documentation tag to the ticket -- please leave the ticket open.

**Comment by iparask** [comment]
Obviously, I misunderstood your previous statement. I want to create two pilots for different machines, that I have different user names. In both machines I use ssh. So, I create two rp.Context('ssh') and add my credentials, i.e. my usernames there.

I said obviously at the beginning because my run failed. The reason it failed is that it used the wrong credentials to the wrong machine.

**Comment by andre-merzky** [comment]
> The reason it failed is that it used the wrong credentials to the wrong machine.

The wrong credential, or the wrong username?

But either way, I hear you.  I don't have a satisfactory answer, but I do have a workaround :)  

You can create an `~/.ssh/config` with contents like this:

```
host stampede.tacc.xsede.org stampede
  user                   = tg803521

host trestles.sdsc.xsede.org trestles
  user                   = amerzky

host comet.sdsc.xsede.org comet
  user                   = amerzky
```

etc.  That will be used by ssh to pick the correct username for each machine, independent of any context settings in RP or SAGA.  That is also useful if you want to use ssh on command line,  btw.  You may want to have a look at http://www.cyberciti.biz/faq/create-ssh-config-file-on-linux-unix/ and http://linux.die.net/man/5/ssh_config, for examples and details.

**Comment by iparask** [comment]
Thanks Andre! I was able to run an example with machines that I have the same user name.

But if I try to run on machines with different user names, although I created the config file, again it fails with this exception:

caught Exception: prompted for unknown password (iparask@stampede.tacc.utexas.edu's password: ) (/home/iparask/RadicalPilotEnv/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +310 (_initialize_pty)  :  % match))
closing session

I do have two context added to the session one for Stampede and one for Gordon.

**Comment by iparask** [comment]
I added a part to this commit a776500 that explains how to create the ssh config file.

**Comment by andre-merzky** [comment]
We probably clarified that in the call, but here for the record: the point if the config file is to not need contexts in the first place...

**Comment by andre-merzky** [comment]
Thanks for the doc part, Ianiis!
