### ISSUE TITLE
Missing module encountered while executing getting started local example

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#747]
Elena from Edinburgh ran into the following issue.

Pilot fails right after going into PendingActive. Looking at the agent.err file tells that module **hostlist**, which is required by the agent(https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L150), is missing. 

This is on python-2.7.5. I'm not sure if this is not available in 2.7.5  or something specific to that installation, but maybe this could be documented (installation section/ FAQ).

Complete thread: https://bitbucket.org/extasy-project/extasy/issues/6/readthedocs-for-extasy-01-running-01

**Comment by marksantcroos** [comment]
I dont think this is a documentation issue.
It is supposed to get installed automagically, so the user doesn't need to do anything.

The fact that the installation apparently failed, but that the agent still started is weird though.

Would need to see full logs to judge better.

**Comment by vivek-bala** [comment]
The verbose log is available at https://gist.github.com/anonymous/7841805eebb19ead9c71

**Comment by andre-merzky** [comment]
Would you also have the logs from the agent side?  Specifically the one which shows the missing module message / stacktrace, and bootstrap_1.err/out.

**Comment by vivek-bala** [comment]
This is using rp 0.35. Are bootstrap_1.err/out produced ?

Agent.err:
```
more agent.err Python 2.7.5 Traceback (most recent call last): File "/Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016701.0003-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 150, in <module> import hostlist ImportError: No module named hostlist
```

**Comment by andre-merzky** [comment]
Ah, thanks for the version info! (please always include that in the ticket message -- but I should have seen that in the gist log you provided...

This looks like the pilot is running on localhost?  Please ask Elena to remove `$HOME/radical.pilot.sandbox/ve_local/` (and any other virtualenv in `$HOME/radical.pilot.sandbox/`),  and then try again.  I think this is a problem with an old, incomplete virtualenv and the default local resource config, which is not set to update that VE.

If that fails, can you please also send Agent.out then, which contains the installation log?

Thanks!

**Comment by vivek-bala** [comment]
Elena Breitmoser reporter

I do the following

1) Fresh virtualenv
```
virtualenv-1.11.6/scripts/virtualenv ExTASY-tools 
source ExTASY-tools/bin/activate 
pip install --upgrade git+https://github.com/radical-cybertools/ExTASY.git@extasy-0.1#egg=radical.ensemblemd.extasy
 pip install --upgrade git+https://github.com/radical-cybertools/ExTASY.git@devel#egg=radical.ensemblemd.extasy
pip install --upgrade git+https://github.com/radical-cybertools/radical.ensemblemd.mdkernels.git@devel#egg=radical.ensemblemd.mdkernels
```

```
echo $RADICAL_PILOT_VERBOSE debug 
echo $RADICAL_PILOT_DBURL mongodb://extasy:extasyproject@extasy-db.epcc.ed.ac.uk/radicalpilot
```

python getting_started_local.py 

The output of this can be found in https://gist.github.com/anonymous/73f3d196a5cb517ce70a

2) I use normal python 

3) I removed the old ve_localhost, there is a new one now 4) The unit.000000 directory is still empty 5) more agent.err Python 2.7.5 Traceback (most recent call last): File "/Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016702.0001-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 150, in <module> import hostlist ImportError: No module named hostlist 6) agent.out can be found at https://gist.github.com/anonymous/75cad7ae6e7a3894d123

**Comment by marksantcroos** [comment]
From the agent.out:
```
Requirement already satisfied (use --upgrade to upgrade): python-hostlist in /Users/elenabreitmoser/Library/Python/2.7/lib/python/site-packages/python_hostlist-1.14-py2.7.egg (from radical.pilot==0.35)
```
It seems there is something lingering outside of the VE.
Can that `python_hostlist` be removed/uninstalled?

**Comment by ebreitmo** [comment]
It was complaining about python-hostlist outside of my virtualenv. I uninstalled it.

When I run 'python getting_started_local.py':
https://gist.github.com/ebreitmo/19e5cfe7442a86e30570

The directory 'unit.000000' is still empty.
agent.out can be found in https://gist.github.com/ebreitmo/ae6c5404fbb5fd70f00a
agent.err can be found in https://gist.github.com/ebreitmo/469216c345366b795016

**Comment by andre-merzky** [comment]
Dear Elena, 

could you please send the data in

```
cd //Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016706.0004-pilot.0000/pilot.0000-ExecWorker-0/3105.0/
cat *
```

Doing a `cat *` in that dir should suffice, no need to cat the individual files.

Also, if you would not mind, could you please run this command on your terminal and send the output?

```
awk 'BEGIN{srand(); print srand()}'
```

Thanks!

**Comment by ebreitmo** [comment]
Hi Andre,

awk 'BEGIN{srand(); print srand()}'
1443439027
cat *
//Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016706.0004-pilot.0000/pilot.0000-ExecWorker-0/monitor.sh: line 62: //Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016706.0004-pilot.0000/pilot.0000-ExecWorker-0/3105.0/cmd: Undefined error: 0
1
3105
3116
NEW 
RUNNING 
FAILED 
START : 1443434187
STOP   : 1443434187
3105.0

**Comment by andre-merzky** [comment]
Oops - that looks wrong indeed: the actual `cmd` script (which contains the CU commands) is missing.

Could you please send the output of:

```
uname -a
ls -la /bin/sh
cat /Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016706.0004-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/VERSION
```

How did you install radical.pilot?  Is it possible to get access to the machine you are running this on?  I guess it is a notebook though (MBP), so probably behind a NAT and firewall... :/

We can get you running with a quick workaround -- how exactly depends a little on your install procedure.  But I still would like to understand why that happens in the first place, obviously.

Thanks!

**Comment by ebreitmo** [comment]
I am running on my Mac:

uname -a
Darwin mbp-eb.epcc.ed.ac.uk 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64



ls -la /bin/sh
-r-xr-xr-x  1 root  wheel  1228416 18 Aug 11:54 /bin/sh

cat /Users/elenabreitmoser/radical.pilot.sandbox/rp.session.mbp-eb.epcc.ed.ac.uk.elenabreitmoser.016706.0004-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/VERSION
0.35


I installed radical pilot like this:
1) Fresh virtualenv

virtualenv-1.11.6/scripts/virtualenv ExTASY-tools source ExTASY-tools/bin/activate pip install --upgrade git+https://github.com/radical-cybertools/ExTASY.git@extasy-0.1#egg=radical.ensemblemd.extasy pip install --upgrade git+https://github.com/radical-cybertools/ExTASY.git@devel#egg=radical.ensemblemd.extasy pip install --upgrade git+https://github.com/radical-cybertools/radical.ensemblemd.mdkernels.git@devel#egg=radical.ensemblemd.mdkernels

echo $RADICAL_PILOT_VERBOSE debug echo $RADICAL_PILOT_DBURL
mongodb://extasy:extasyproject@extasy-db.epcc.ed.ac.uk/radicalpilot

Can we do a Skype with screen sharing, then you could talk me through what needs to be done? My skype name is e.breitmoser

**Comment by andre-merzky** [comment]
Note from skype: advices Elena to switch to `POPEN` for the time being.  Ticket stays open.

**Comment by ebreitmo** [comment]
I changed SHELL to POPEN in local.json, then ran 'python getting_started_local.py' again.

Now there is no red error message on the screen and in unit.000000 there are

-rwxr--r--  1 elenabreitmoser  staff  1081 28 Sep 13:07 radical_pilot_cu_launch_script.sh
-rw-r--r--  1 elenabreitmoser  staff     0 28 Sep 13:07 STDOUT
-rw-r--r--  1 elenabreitmoser  staff     0 28 Sep 13:07 STDERR
-rw-r--r--  1 elenabreitmoser  staff    84 28 Sep 13:07 PROF

**Comment by andre-merzky** [comment]
That looks much better :)  Is the run finishing successfully overall?

**Comment by ebreitmo** [comment]
The output of running the code can be found in https://gist.github.com/ebreitmo/cf7987b49683296e0caa.
What defines a successful run?

**Comment by vivek-bala** [comment]
```
[Callback]: ComputeUnit 00001 'unit_000: unit.000000' (on pilot.0000) state: Done.
```

That would be a successful run (assuming you are submitting only 1 UNIT).

**Comment by ebreitmo** [comment]
Ok, thanks, that's somewhere in the screen output!

**Comment by andre-merzky** [comment]
Great :)  

So,  yeah, with 'successful run'  I indeed meant that all ComputeUnits finish w/o error.

**Comment by andre-merzky** [comment]
a 0.35.1 hotfix version of radical.pilot has been pushed to pypi which should address this problem.  We would appreciate feedback if this is indeed the case.

Thanks!

**Comment by ebreitmo** [comment]
[29/09/2015 16:07:12] E Breitmoser: Iain tried it and it works for him (on a mac)
[29/09/2015 16:07:16] E Breitmoser: mbp-ib: ibethune$ virtualenv /Desktop/extasy-test
mbp-ib: ibethune$ source /Desktop/extasy-test/bin/activate
(extasy-test)mbp-ib:~ ibethune$ pip install --upgrade git+https://github.com/radical-cybertools/ExTASY.git@devel#egg=radical.ensemblemd.extasy
(extasy-test)mbp-ib:~ ibethune$ pip install --upgrade git+https://github.com/radical-cybertools/radical.ensemblemd.mdkernels.git@master#egg=radical.ensemblemd.mdkernels
(extasy-test)mbp-ib:~ ibethune$ python -c 'import radical.ensemblemd.extasy as extasy; print extasy.version'
0.1-21-ge64679d
(extasy-test)mbp-ib:~ python -c 'import radical.pilot as pilot; print pilot.version' 
0.35.1
(extasy-test)mbp-ib: ibethune$ mkdir /Desktop/extasy-tutorial
(extasy-test)mbp-ib:~ ibethune$ cd Desktop/extasy-tutorial/
(extasy-test)mbp-ib:extasy-tutorial ibethune$ curl -k -O  https://raw.githubusercontent.com/radical-cybertools/ExTASY/devel/tarballs/coam-on-archer.tar.gz
(extasy-test)mbp-ib:extasy-tutorial ibethune$ tar xvfz coam-on-archer.tar.gz
(extasy-test)mbp-ib:extasy-tutorial ibethune$ vi coam-on-archer/archer.rcfg 
(extasy-test)mbp-ib:extasy-tutorial ibethune$ vi coam-on-archer/cocoamber.wcfg
(extasy-test)mbp-ib:extasy-tutorial ibethune$ cd coam-on-archer
(extasy-test)mbp-ib:coam-on-archer ibethune$ EXTASY_DEBUG=True RADICAL_PILOT_VERBOSE='debug' SAGA_VERBOSE='debug' extasy --RPconfig archer.rcfg --Kconfig cocoamber.wcfg 2> extasy.log
[29/09/2015 16:07:42] E Breitmoser: Any idea of where to look for differences in our environments?

**Comment by andre-merzky** [comment]
This is considered resolved.  Thanks!
