### ISSUE TITLE
make `sub_agents` field in the `agent_config` into a `dict` (`{name:location}`)

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#761]

**Comment by marksantcroos** [comment]
What is the advantage of moving the location from the actual sub-agent config to the main agent config?

**Comment by andre-merzky** [comment]
Assume sub-agent.0.  At the moment it needs to iterate over all the sub-agent entries in order to find out where to start them, whereas the subagents ignore that config item.  In other words: the exec target is information which is needed by the entity which starts the sub-agent, not by the sub-agent itself.

This is related to a remark you made (quite) a while back, that in the agent sometimes we iterate over the sub-agent configs, and sometimes iterate over the sub-agent names.

Semantically the change is void.

**Comment by marksantcroos** [comment]
Ok, thanks, that makes sense.

Do we also want to store the actual node of the sub-agent after scheduling, and if so, where?

**Comment by andre-merzky** [comment]
Good point, that may indeed be worthwhile keeping around.  We can store the information right after we created the LRMS, as that is where we do the agent node scheduling right now, so very early (obviously).  the question is 'where'.  We can add it to the agent-configs (just like we do with the bridge addresses) as  eventually sub-agents may need it to start second-gen sub-agents, if that ever becomes a thing.  That would be  somewhat clean.  But we never push the sub-agent configs into MongoDB, and probably don't want to...

**Comment by marksantcroos** [comment]
ps. We also loose ordering by moving to a dict, but if that becomes a problem we'll just move back to a list of dicts or so.

**Comment by marksantcroos** [comment]
> the question is 'where'

Yeah, currently we dont really need it in the sub-agents, so an "lrms_info" entry a la "lm_info" would probably be good enough. I'll do that once I do more fancy agent placement.

**Comment by andre-merzky** [comment]
I think those points are now all addressed (in different ways though).
