### ISSUE TITLE
Debug messages level with release/0.36

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#768]
Hello,

the debug messages are at the same level as the standard output. Is this how it is supposed to be?

**Comment by andre-merzky** [comment]
Hi Iannis, 

Both, debug messages and stdout end out on standard output, by default.  I am not sure what you mean with 'same level'?  Debug message prints are dependent on the used log level, normal output is always printed.

**Comment by iparask** [comment]
I mean that when I do python gettiing_started_local.py 2>debug.log with the RP, SAGA and Util verbose to DEBUG I see all messages and nothing is written to the debug.log file.

**Comment by andre-merzky** [comment]
Yeah, utils indeed sets stdout as default (https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/logger.py#L159).  That indeed should be stderr I guess.  Unless @marksantcroos disagrees, I'll change it to stderr.

**Comment by marksantcroos** [comment]
Its probably not a bad idea to change it indeed to be able to separate the print()'s form the application and the debugging info. Does this also move the demo() output to stderr or not?

**Comment by marksantcroos** [comment]
> Does this also move the demo() output to stderr or not?

To answer myself, based on https://github.com/radical-cybertools/radical.utils/blob/hotfix/log_target/src/radical/utils/reporter.py#L82 I would say those go stdout?

**Comment by andre-merzky** [comment]
Indeed - reporter goes to stdout by default.

**Comment by andre-merzky** [comment]
A fix has been merged into utils
