### ISSUE TITLE
Documentation: how to set up secure MongoDB instance for radical.pilot

### ISSUE THREAD

**Issue by dotsdl** [radical-cybertools/radical.pilot#773]
I wish to use radical.pilot for submitting jobs to remote clusters, but first need to set up a reachable MongoDB server. However, the [docs](http://radicalpilot.readthedocs.org/en/latest/installation.html#requirements) currently don't give any detail on how to do that, although they allude to it "at the end of the section."

**Comment by marksantcroos** [comment]
Thanks for catching that. We need to fix that. In the meantime, here are the instructions from the MongoDB website: https://docs.mongodb.org/manual/installation/
We don't require anything special form the installation.

**Comment by andre-merzky** [comment]
The linked MongoDB documentation seems to be complete wrt. ssl setup, the linked mlab approach also offers secure access.  we consider this addressed.
