### ISSUE TITLE
default python module change on blue waters

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#788]
with:
```
Traceback (most recent call last):
  File "/home/antons/rp36/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 328, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/antons/rp36/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 249, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "test_mpi.py", line 25, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```

[debug](https://gist.github.com/AntonsT/0d8b68e7ab27ff1324ac)
[terminal](https://gist.github.com/AntonsT/0fac88b6b3736b1b80ce)
[sandbox](https://github.com/AntonsT/rp-logs/blob/master/rp.session.antons-pc.antons.016710.0042-pilot.0000.tar.gz)

**Comment by AntonsT** [comment]
Bootstrapper uses a depricated module bw-python:

```
The bw-python module is deprecated and will be removed in the near future.
Please use the new build by module load bwpy
Report any issues encountered with the bwpy build

Python 2.7.5
```

**Comment by marksantcroos** [comment]
Thanks for the notice. Andre actually stumbled upon the bwpy module recently and we wondered out loud what it was.
The deprecation of bw-python is very recently as the documentation still points to it.
We will adjust accordingly.

Note that the failure is unrelated to this, and more has to do with the fact that we didn't provide a mpi test for bw.

**Comment by andre-merzky** [comment]
Outdated.
