### ISSUE TITLE
v0.36RC1 fails on SuperMic

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#789]
I am getting this error in the bootstrap_3.log:

```
2015-10-04 23:07:32,498: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   :   File "/worka/work/iparaske/radical.pilot.sandbox/ve_supermic/rp_install/bin/radical-pilot-agent-multicore.py", line 6050, in bootstrap_3
    nodeip = LRMS.hostip(cfg.get('network_interface'))
  File "/worka/work/iparaske/radical.pilot.sandbox/ve_supermic/rp_install/bin/radical-pilot-agent-multicore.py", line 2398, in hostip
    ip = netifaces.ifaddresses(pref)[af][0]['addr']
```

**Comment by iparask** [comment]
Include getting_started_remote example with the same error

**Comment by marksantcroos** [comment]
Is there anything more? As I dont see the actual error in your output.

**Comment by andre-merzky** [comment]
Indeed, Iannis, you usually may want to quote a couple of lines before and after the stack trace.  Thanks!

**Comment by iparask** [comment]
Here is the whole file:

https://gist.github.com/iparask/66cab53c23b0d07c3a71

**Comment by andre-merzky** [comment]
Thanks -- would you mind  creating a tarball of the agent sandbox and posting it?

**Comment by iparask** [comment]
Here:

http://eceweb1.rutgers.edu/~ip176/sandbox.tar.gz

**Comment by andre-merzky** [comment]
Thanks Iannis!

Mark, it seems that the line:

```         
         af = netifaces.AF_INET
         ip = netifaces.ifaddresses(pref)[af][0]['addr']
```

stumbles because the `af` lookup in the dict fails.  I am not sure if any `pref` got selected before -- we should probably log that...
