### ISSUE TITLE
cu.stdout Empty @ feature/yarn

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#791]
Hello guys,

I have always cu.stdout empty. I try to print it before I close the session and it is always none. 

Can you tell me where it is set? I think there is a bug in the way I use it to capture the outputs of the YARN application

**Comment by andre-merzky** [comment]
That has only recently be backported to RP.  Is the yarn branch in sync with devel?  If so, would you please send an example application?

**Comment by iparask** [comment]
No it is not yet. Do you think should I merge them?

**Comment by iparask** [comment]
So this was resolved when I merged with devel. I am closing the ticket
