### ISSUE TITLE
py.test behaviour with multiple fixtures

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#799]
Converting discussion on e-mail thread into a ticket:

Hi Andre,

I have pushed a small generic example to feature/testing. To run do:
cd tests/test_suites/remote_generic
py.test --junitxml result.xml test_suite_remote_generic.py

Your credentials are in https://github.com/radical-cybertools/radical.pilot/blob/feature/testing/tests/test_suites/pytest_credentials.json and are picked up. Hope this works.

There is a single test: https://github.com/radical-cybertools/radical.pilot/blob/feature/testing/tests/test_suites/remote_generic/test_suite_remote_generic.py#L157 which runs 4 bin/date tasks. There are two fixtures: one for gordon https://github.com/radical-cybertools/radical.pilot/blob/feature/testing/tests/test_suites/remote_generic/test_suite_remote_generic.py#L56 and one for comet https://github.com/radical-cybertools/radical.pilot/blob/feature/testing/tests/test_suites/remote_generic/test_suite_remote_generic.py#L108 Test uses session, pilot, pmgr and umgr from gordon fixture, but workload is executed on both gordon and comet. It should only be executed on gordon! Also I see pilot directories created for both sessions on both machines, e.g. 4 pilot directories in total, instead of two, but only two pilots are launched (which is expected). I have no explanation for this behaviour. If I would set-up doing some arithmetic this would work as expected.

Thanks,
Antons

**Comment by AntonsT** [comment]
Hi Antons,

I just pushed a couple of changes.  In the pilot_launcher, pytest
stumbled over some unicode output -- I convert that into explicit
strings now.  For easier debugging, I replaces the cordon and comet
fixtures with two (different) local ones.  And finally I changed the
cfg file to parseable JSON.  After that, the tests seem to 'run' --
but there the results file seem to say that no test exists actually:

$ cat /home/merzky/saga/radical.pilot/tests/test_suites/remote_generic/result.xml
<?xml version="1.0" encoding="utf-8"?><testsuite errors="0"
failures="0" name="pytest" skips="0" tests="0"
time="8.099"></testsuite>

The local sandbox seem to indicate that two pilots get started, which
seems to match expectations.  Can you please try the current setup,
and let me know if / where that goes wrong for you?

Best, Andre.

**Comment by AntonsT** [comment]
Hi Andre,

Thanks for your feedback.

>After that, the tests seem to 'run' --
>but there the results file seem to say that no test exists actually

This is because pilot requests 16 cores. on localhost things seem to work properly right now, but with remote machines the output is still the same. Fixtures are virtually identical, so I am not sure that causes this issue to persist.

Thanks,
Antons

**Comment by AntonsT** [comment]
Hi Antons -- I did not really get around testing the remote once,
should probably do that.  But indeed, the local fixtures are basically
cut-and-paste-and-string-changes of the remote ones, so any difference
would be / is surprising... :/

**Comment by andre-merzky** [comment]
Antons, what is the state of this actually?  I think we dropped the ball on this end...

**Comment by andre-merzky** [comment]
This should be revisited.

**Comment by andre-merzky** [comment]
outdated.
