### ISSUE TITLE
ValueError: doubled info entry asoc_adv_u

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#801]
```
Traceback (most recent call last):
  File "inject.py", line 216, in <module>
    inject_all(session_ids, 'pickle')
  File "inject.py", line 147, in inject_all
    inject(sid)
  File "inject.py", line 105, in inject
    tr_cu_prof_fr = rpu.get_info_df(cu_prof_fr)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/pilot/utils/analysis.py", line 522, in get_info_df
    raise ValueError('doubled info entry %s' % i)
ValueError: doubled info entry asoc_adv_u
```

Will try to dig deeper.

**Comment by marksantcroos** [comment]
After adding the uid to the message too:
```
ValueError: doubled info entry asoc_adv_u (uid:unit.000441)
```

```
$ grep advance *|grep AgentStagingOutput | grep unit.000441
agent_0.AgentStagingOutputComponent.0.child.prof:43.9447,agent_0.AgentStagingOutputComponent.0.child:MainThread,unit.000441,AgentStagingOutput,advance,
agent_0.AgentStagingOutputComponent.0.child.prof:43.9892,agent_0.AgentStagingOutputComponent.0.child:MainThread,unit.000441,Failed,advance,
agent_4.AgentExecutingWatcher_POPEN.6.prof:22.1908,agent_4.AgentExecutingWatcher_POPEN.6:Watcher,unit.000441,AgentStagingOutputPending,advance,
```

So when a unit fails, it creates a message that causes a duplicate entry.

**Comment by andre-merzky** [comment]
Its not actually a duplicated profile entry though, as it refers to different states...  I think the reason for this is that we defer the `FAILED` state until after we handled stdout/stderr, which we also want to get for a `FAILED` unit.  So we move the unit to output staging, do that output staging (so it goes into that state in the output stager), and then the output stager advances to `FAILED`, causing that second entry.

I guess the simplest and cleanest solution would be to differentiate the two DF entries based on state?

**Comment by andre-merzky** [comment]
see https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3992

and https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L5067

**Comment by marksantcroos** [comment]
> I guess the simplest and cleanest solution would be to differentiate the two DF entries based on state?

Thats sounds about right. That would only be for the intermediate step though I guess? I.e. it wont change the transposed DF?

**Comment by marksantcroos** [comment]
Do you have time to work on this or should I take that up myself?

**Comment by andre-merzky** [comment]
I would not mind if you take the ticket, honestly...

Thanks!

**Comment by marksantcroos** [comment]
Fixed.
