### ISSUE TITLE
gtod build fails on comet (sometimes)

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#806]
```
$ cat bootstrap_1.err 
/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1: error while loading shared libraries: libmpfr.so.1: cannot open shared object file: No such file or directory
```

Will investigate.

**Comment by marksantcroos** [comment]
This happened often enough that I submitted a ticket to XSEDE (#36660).

**Comment by andre-merzky** [comment]
We could alleviate the problem by moving it to `$HOME/radical.pilot.sandbox/gtod/`, and only build if  it does not exist.  Once that worked, all following pilots will have it.

A ticket is the right thing to do of course...

**Comment by marksantcroos** [comment]
> We could alleviate the problem by moving it to $HOME/radical.pilot.sandbox/gtod/, and only build if it does not exist. Once that worked, all following pilots will have it.

We would also have to verify that it still works then.

**Comment by marksantcroos** [comment]
```
Mark

Just to update - we had an issue where mpfr was getting left out of the installs on some nodes (oddly enough not on all). In any case we have explicitly added it to the list of install on every node and its in place now.

This issue should be resolved now.

-Mahidhar
```
