### ISSUE TITLE
reconsider point in time to consider pilot ACTIVE

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#813]
Its now coupled to the job status I think, but with the more involved startup, we might want to postpone that state.

**Comment by andre-merzky** [comment]
I agree with that -- from the application perspective, the pilot is active when it start pulling units...

**Comment by marksantcroos** [comment]
Why did we not do this in the first place actually? I remember being a proponent of splitting them up further. Was there a good reason not too?

Just discussed this with Matteo, and changing this sounds like the right thing to do.

Current state progression:

- NEW
- PENDING_LAUNCH  
- LAUNCHING
- PENDING_ACTIVE
- ACTIVE

My proposal:

- NEW
- PENDING_SUBMITTING - who: client, when: reaches facade
- SUBMITTING - who: client, when: pre-qsub
- PENDING_BOOTSTRAPPING - who: client, when: post qsub/saga job queued
- BOOTSTRAPPING - who: client, when: saga job running
- PENDING_RUNNING - who: agent, when: as soon as the agent has a mongodb connection
- RUNNING  - who: agent, when: agent is ready to pull cu's

I choose new labels to not have new semantics for the existing labels. We can also re-use the existing ones if people feel strongly about that.

**Comment by andre-merzky** [comment]
This should be discussed in the context of the upcoming analytics release.

**Comment by andre-merzky** [comment]
ping: this came up again during discussion of timings and analytics, and is considered worthwhile pursuing soon.

**Comment by andre-merzky** [comment]
This is implemented now.  The change opens the space for a `AGENT_BOOTSTRAPPING` state.
