### ISSUE TITLE
prof frames `state_from` not consistently correct

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#815]
Is that supposed to be "correct" or is it best effort?

**Comment by andre-merzky** [comment]
What exactly seems to be incorrect?  Yes, it is supposed to be correct. IIRC, sync problems can screw state ordering up,and thus also state_from.  Could that be a problem?

**Comment by marksantcroos** [comment]
Possibly, for `state=Executing` I see either `state_from=ExecutingPending` or `state_from=AllocatingPending` and for `state=AgentStagingOutputPending` I see `state_from=ExecutingPending` and `state_from=Executing`.

**Comment by andre-merzky** [comment]
:(  Yeah, maybe we need to rethink profile synchronization...

**Comment by andre-merzky** [comment]
Mark, is this still an issue?  Code-wise I am pretty sure that the component base class has the right probes for all state advances now.

**Comment by marksantcroos** [comment]
I don't know, as I made sure I don't rely on it to be correct.
