### ISSUE TITLE
Can the current RP verbosity be disabled/reduced ?

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#816]
These msgs seem to be from RP itself (and not the user script),

```
create session rp.session.ip-10-184-31-85.vivek.016716.0026                   ok
create pilot manager                                                          ok
create pilot description                                                      ok
```

Can they be disabled ?

**Comment by andre-merzky** [comment]
Yes, they can.  Apologies for the default verbosity, there is a mixup in the default reporting level.  Let me check how to best handle this...

**Comment by andre-merzky** [comment]
DONE - only shows up on loge level REPORT now
