### ISSUE TITLE
SIte Packages should be included to ve_*?

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#826]
I am not sure if this correct or not, but shouldn't the ve that RP creates in the sandbox include the packages that may already be installed in the system?

For example, I have numpy installed in my localhost, but when I try to run a CU with numpy the module does not exist.

If yes, I may propose to add the flag --system-site-packages to the ve creation?

**Comment by marksantcroos** [comment]
No, not really, as the VE is for the Agent, and not for the CUs. And as you have discovered, the VE creation is a very delicate process to get right on my systems in the first place.

**Comment by iparask** [comment]
I see.

Is it not correct to assume that the CUs run under the VE that is created for the Agent?

So in the case someone has pre-installed packages that will be used that should somehow defined in the pre_exec attribute. If a module is loaded then it is okay, but if not how it can be defined?

**Comment by marksantcroos** [comment]
> Is it not correct to assume that the CUs run under the VE that is created for the Agent?

Nope. We actually try as much as possible to isolate the CU from that:
https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3748



> So in the case someone has pre-installed packages that will be used that should somehow defined in the pre_exec attribute. If a module is loaded then it is okay, but if not how it can be defined?

General recommendation is to provide a fresh setup for the CU. So you could create an CU VE out of band and source it in your CU or create one dynamically in your CU.
