### ISSUE TITLE
cu.as_dict()['execution_details'] should be leveled-up

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#827]
There is no semantic distinction between things in execution detail and things in the dict proper.  We also should make  sure that the fields defined in either are filled and documented.  Some has been lost  during restructuring...

**Comment by marksantcroos** [comment]
ECANTPARSE.

**Comment by andre-merzky** [comment]
Right now, unit.as_dict gives something like

```
state : DONE
description: {}
started : 12445.0
execution_details: {
    pilot: pilot-0006
    state_history: []
}
```

I think that additional dict level (execution_details) is confusing and unnecessary.

**Comment by marksantcroos** [comment]
Ah :) Yes, I agree!

**Comment by andre-merzky** [comment]
I might attempt doing so for 0.37 -- we use the above in some doc examples for unit inspection...

**Comment by andre-merzky** [comment]
This has been implemented.
