### ISSUE TITLE
detect invalid fields in staging directive

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#846]
We use the label `mode` in many places in RP and RCT -- but in the staging directives, we call the switching property `action`.  I wonder if it makes sense to also use `mode` here?  Mostly because I repeat the same typo again and again, and no error pops up to tell me about it -- just unexpected results... :P

**Comment by marksantcroos** [comment]
Im not against a different label, but in the context of file operations, I rather reserve `mode` for `file modes`.

> and no error pops up to tell me about it -- just unexpected results... :P

I would be more in favor of fixing this: i.e. bailing out on any unknown field in the conversion from the dict.

**Comment by andre-merzky** [comment]
Ack.  I'll leave the ticket then open  for the field check...

**Comment by andre-merzky** [comment]
This check is implemented now.
