### ISSUE TITLE
Unclear documentation - 4.1.4 (end)

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.pilot#851]
In

http://radicalpilot.readthedocs.org/en/release-v0.37/user_guide/00_getting_started.html

I was left trying to parse the following:

Compute units are executed by pilots, but how does a pilot know which units to
execute?  That relation is established by the `:class:radical.pilot.UnitManager`
class which accepts ComputeUnitDescriptions as we created above, and assigns
them, according to some scheduling algorithm, to the set of available pilots.
It returns the `:class:radical.pilot.ComputeUnit` handles,
for whose completion the application can then wait:

and it definitely did not help me understand the following snippet of code:

# create a unit manager, submit units, and wait for their completion
umgr = rp.UnitManager(session=session)
umgr.add_pilots(pilot)
umgr.submit_units(cuds)
umgr.wait_units()

**Comment by andre-merzky** [comment]
done
