### ISSUE TITLE
Mongodb is not working.

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#860]
Hello,

after running a couple of enmd examples, I got this error:

radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'mongodb://54.221.194.147:24242/test_georgeha' incorrect?): timed out

Now. I can't run anything

**Comment by marksantcroos** [comment]
Try again.

**Comment by georgeha** [comment]
Still, it doesn't work.

**Comment by marksantcroos** [comment]
What does the following tell you?

```
$ telnet 54.221.194.147 24242
```

**Comment by georgeha** [comment]
Trying 54.221.194.147...
telnet: connect to address 54.221.194.147: Operation timed out
telnet: Unable to connect to remote host

**Comment by marksantcroos** [comment]
Are you behind some firewall perhaps?

**Comment by georgeha** [comment]
It worked! I changed wifi network. Thank you!
