### ISSUE TITLE
add archer ssh key setup links to resource config

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#862]
Thats probably the right place for resource specific issues.

https://www.archer.ac.uk/documentation/user-guide/connecting.php#sec-2.3 http://radicalpilot.readthedocs.org/en/release-v0.37/faq.html#avoid-the-error-permission-denied-publickey-keyboard-interactive-in-agent-stderr-or-stderr
http://radicalpilot.readthedocs.org/en/release-v0.37/resources.html#archer

**Comment by andre-merzky** [comment]
Outdated.
