### ISSUE TITLE
RP Support for Grace cluster at Yale

### ISSUE THREAD

**Issue by leelasd** [radical-cybertools/radical.pilot#869]
The documentation for the cluster can be found here 
http://hpc.yale.edu/grace/

Please help me with setting up RP

**Comment by marksantcroos** [comment]
[Grace _ Yale HPC.pdf](https://github.com/radical-cybertools/radical.pilot/files/18500/Grace._.Yale.HPC.pdf)

**Comment by andre-merzky** [comment]
Thanks!

**Comment by marksantcroos** [comment]
This is largely working now.

Remaining problem is that LSF returns scattered cores over the various nodes and RP swallows on that as it assumes homogeneous nodes with ditto core counts.

Immediate solution: use low core counts for the pilot
Intermediate solution: add some "spawn magic" to LSF saga adapter to prevent the scattering from happening or have it happening in predictable ways
Long term solution: Have RP grok scattered cores

**Comment by marksantcroos** [comment]
Hi @leelasd, I've also created a feature/yale_grace branch on SAGA.
Can you install/update that branch for both RP and SAGA?
Let me know how it goes!

**Comment by andre-merzky** [comment]
Due to lack of feedback I would suggest closing the ticket.  Mark,  is the SAGA branch mergeable w/o confirmation on this ticket?

**Comment by marksantcroos** [comment]
> Due to lack of feedback I would suggest closing the ticket.

ACK.

> Mark, is the SAGA branch mergeable w/o confirmation on this ticket?

Thats merged already.
