### ISSUE TITLE
job not killed when agent launch fails because of missing sdists

### ISSUE THREAD

**Issue by leelasd** [radical-cybertools/radical.pilot#870]

**Comment by andre-merzky** [comment]
Missing sdists should pop up as an error in the bootstrapper, and AFAICS the bootstrapper should fail then -- so I think your observation says that this is not what happens, but that the bootstrapper is continuing / hanging?

Would you be able to provide the bootstrap_1.out/err/log files from the pilot sandbox?  Thanks!

**Comment by leelasd** [comment]
Snafu from Mark.
