### ISSUE TITLE
slurm disable automatic requeue

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#878]
We probably want that.

See https://portal.xsede.org/sdsc-comet#running-jobscripts-requeue

**Comment by andre-merzky** [comment]
yep.

**Comment by marksantcroos** [comment]
Although this might be a sensible default for SAGA and thereby not a RP issue.

**Comment by andre-merzky** [comment]
Closed as too limiting - we need to handle node failures.
