### ISSUE TITLE
reporter and debug

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#879]
Since the tutorial Im starting to appreciate the reporter.

What I would like is to see the pretty stuff on my terminal and be able to redirect DEBUG output to a file or so. (Im happy to do the redirection on shell level)

AFAIK, this is currently not possible. Happy to be corrected :-)

**Comment by andre-merzky** [comment]
No, it is not possible right now, but I also was wishing for this earlier today really :D  Wold make running experiments less tedious, really, because it makes it easier to follow the overall progress...

I'll look into it...

**Comment by andre-merzky** [comment]
This is implemented in RU now.
