### ISSUE TITLE
RP-0.37.10 behavior with multiple workers on SuperMIC

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#890]
If I am using a default agent configuration for an experiment involving 64 replicas and I request 80 cores, it takes ~133.21 seconds to perform 6000 time-steps, but if I change number of workers in agent_default.json to 8, e.g.:
```
"components" : {
                "AgentStagingInputComponent"  : 8,
                "AgentSchedulingComponent"    : 8,
                "AgentExecutingComponent"     : 8,
                "AgentStagingOutputComponent" : 8
            }
``` 

it takes ~406.49 seconds to perform 6000 time-steps. The only thing I change is number of workers. How can I use agent config to extract more performance from RP?

**Comment by andre-merzky** [comment]
I think we mentioned in another thread that more workers on the same not are not necessarily beneficial, as those begin to thrash the system.  Agent components are, at this point, implemented relatively efficiently -- they use the system on the node pretty well.  To increase component throughput via component concurrency, you'll likely have to sacrifice more nodes and spread the components over multiple sub-agents.  As mentioned before, the cray config shows how sub-agents are defined.

Some more nodes: please only use one scheduling component -- schedulers algorithms are not (yet) able to span concurrent component instances.  In fact, decreasing schedulers to '1' may make already a difference for you, please try.  Also, please make sure you have a sufficient number of nodes left to run your workload -- sub-agents will allocate a full node.

**Comment by antonst** [comment]
Thank you for a detailed reply Andre, but why time to perform 6000 steps at CU level changes? My understanding was that it should not change. OK, agent can occupy 1,2,3 nodes and CU's might wait for other CU's to finish, but why for individual CU's execution time is affected?

**Comment by andre-merzky** [comment]
Without looking at profiles I can't give you a definite answer.  But as said above, I assume two things:  component instances are beginning to thrash the system when competing for resources, and multiple scheduler instanced wreaking havoc.  For the last point: I would assume that too many units get assigned to the same set of cores/nodes, and that they'll thus also thrash those nodes, competing for memory and CPU.

But again, this is guesswork -- you may want to turn on profiling and check where the time is actually spent.  In the devel branch, have a look at `examples/misc/profile_analysis.py` which shows how to go from profiling to plotting some time-dependent measures,  such as state changes and CU concurrency.

**Comment by andre-merzky** [comment]
As said in the previous reply, w/o looking at the profiles it is difficult
to judge where the time is spent.  Do you happen to have profiles
available, by any chance?



On Wed, Nov 18, 2015 at 10:56 PM, Antons <notifications@github.com> wrote:

> I have tried to use a default agent config on Stampede and allocate 32
> cores while launching only 16 single core tasks and even with this
> configuration for some cycles I get 2x of expected execution time for CU's.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radical-cybertools/radical.pilot/issues/890#issuecomment-157877421>
> .
>



-- 
99 little bugs in the code.
99 little bugs in the code.
Take one down, patch it around.

127 little bugs in the code...

**Comment by antonst** [comment]
Please ignore last message :-)

**Comment by andre-merzky** [comment]
sure thing! :)

**Comment by andre-merzky** [comment]
Close due to inactivity.
