### ISSUE TITLE
Forced shutdown when submitting pilots to Stampede and Comet

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#896]
*Moved from Enmd Tickets*

I've been consistently running into an error just after deallocation that tells me ```pilot manager controller thread caught system exit -- forcing application shutdown```

I also get the following as output:

```
Traceback (most recent call last):
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 137, in pilot_state_cb
    sys.exit(0)
SystemExit: 0
Traceback (most recent call last):
  File "repex.py", line 289, in <module>
    cluster.deallocate()
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 103, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close (terminate=terminate)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 175, in close
    self.cancel_pilots()
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 566, in cancel_pilots
    self._worker.register_cancel_pilots_request(pilot_ids=pilot_ids)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 601, in register_cancel_pilots_request
    time.sleep(0.3)
```

This happens on both Comet and Stampede, no matter what I am running. The application never uses up all the walltime either, so I'm not sure what's happening. I tried to submit a variant on the example repex script, and I've been getting this error on both machines. The application does start running and generating output, but it never terminates and never generates the total output

**Comment by andre-merzky** [comment]
Please have a look into the agent sandbox on the target resource.  That should be somewhere in
`$HOME/radical.pilot.sandbox/<session_id>`.  On some machines, the sandbox is on a scratch space, or, like on stampede, in `/$WORK/radical.pilot.sandbox/...`.  You should see a bunch of log files and such in that sandbox -- can you please pack them up and send attach the tarball to the ticket?

```
tar zcvf rp_agent.log a* b*
```

Thanks!

**Comment by Nikhil-Shenoy** [comment]
Andre, Github won't let me upload the file here

**Comment by andre-merzky** [comment]
feel free to sent it per mail, or to upload it elsewhere and provide a link...

**Comment by Nikhil-Shenoy** [comment]
sent

**Comment by andre-merzky** [comment]
Are you using the RP release from pypi, or some branch?  Also, you say this happens after deallocation -- so the application is basically done and completed, and this is 'just' a shutdown issue?

**Comment by andre-merzky** [comment]
The stack trace you posted is pointing into ensemblemd,  to

```
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 137, in pilot_state_cb
``` 

which is (https://github.com/radical-cybertools/radical.ensemblemd/blob/devel/src/radical/ensemblemd/single_cluster_environment.py#L137) an empty line.  So I assume you use a different branch?  Would you mind pointing me to that?  Thanks!

**Comment by Nikhil-Shenoy** [comment]
Turns out I was using the master branch for the script. Should I be using the devel branch instead?

Also, the last three non-error messages I see are ```Dealloacting Cluster```, ```Resource xsede.comet state has changed to Canceled```, and ```Resource allocation canceled```. However, I don't get the total output that I would expect from the application.

**Comment by andre-merzky** [comment]
Line 137 does not match in the master branch either though:

https://github.com/radical-cybertools/radical.ensemblemd/blob/master/src/radical/ensemblemd/single_cluster_environment.py#L137

On what branch of EnMD to use: I can't answer that, really -- Vivek can probably give you some advise.   Unless we understand why the pilot state callback calls sys.exit() on the Cancelled pilot I am hesitant to guess what happens to the output.

**Comment by Nikhil-Shenoy** [comment]
Do you think it might be a version issue? I get ```v0.37.10@master``` from the ```radicalpilot-version``` command.

And I was asking about which RP branch to use.

**Comment by vivek-bala** [comment]
Hey,

The released version should be stable. Can the link to the verbose output
be pasted here ? I can take a look too.

- Vivek

**Comment by vivek-bala** [comment]
Released version again, which will get installed while installing
ensemblemd.

**Comment by Nikhil-Shenoy** [comment]
[verbose_output.txt](https://github.com/radical-cybertools/radical.pilot/files/29185/verbose_output.txt)

**Comment by vivek-bala** [comment]
enmd execution seems to be successful. Could you run it with
RADICAL_PILOT_VERBOSE=debug (in addition) please?

**Comment by Nikhil-Shenoy** [comment]
Here's the output with RADICAL_PILOT_VERBOSE=debug:

[rp_enmd_verbose_output.txt](https://github.com/radical-cybertools/radical.pilot/files/29206/rp_enmd_verbose_output.txt)

**Comment by andre-merzky** [comment]
I still don't know what EnMD version is being used.  I don't see a version where line 137 of the SCE raises a sys.exit().  Vivek, can you help me out here?

**Comment by Nikhil-Shenoy** [comment]
EnMD version is 0.3.6-60-g9bc7463. Should I pull and then run again?

**Comment by andre-merzky** [comment]
Thanks, *now* I see it :)  Please, always report the version numbers in your tickets...

So, that code actually behaves as expected -- but the expected is probably not what you want... :P 

The pilot state callback indeed calls `sys.exit()` when the pilot gets cancelled - but the cancellation is triggered during `deallocate()`, so you'll *always* see a `sys.exit()` during deallocate (or right after).

This has meanwhile changed in devel indeed, so switching to the devel branch should fix your problem.

**Comment by Nikhil-Shenoy** [comment]
Ahhh yes that did it! Thanks to both of you!

And I'll be sure to put the version numbers in next time.

**Comment by vivek-bala** [comment]
Yes please. The current version is 0.3.14. The file you have attached
doesn't have RP verbose messages bdw.

 Also, if you're using a specific branch, always better to pull and
reinstall everytime. But generally better to use released version.

- Vivek

**Comment by andre-merzky** [comment]
I consider this an EnsembleMD issue -- from the RP side of things, all is as expected.
