### ISSUE TITLE
create a symlink from the pilot sandbox basedir to $HOME

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#897]
so that users don't need to look through resource configs and search file systems to find a sandbox when we ask for log files etc

**Comment by marksantcroos** [comment]
This has to be done manually, as we have systems with shared fs where the sandboxes live in a different place.

**Comment by marksantcroos** [comment]
Or make it easier to find in the documentation :)

**Comment by andre-merzky** [comment]
ack on the documentation.

I don't understand your point about manual: when the bootstrapper runs, we obviously have access to the sandbox root (`$PWD/..`).  Are you saying there are systems where, at that point, we don't have access to `$HOME`, and thus can't create the symlink?

**Comment by marksantcroos** [comment]
Thats one situation. The other situation is that multiple pilots will want to make a different symlink.

**Comment by andre-merzky** [comment]
Ah, sorry if I was not clear -- I proposed `ln -s $WORK/radical.pilot.sandbox $HOME`, not to link the individual pilot sandboxes.

If $HOME is not accessible, then no, that won't work.  But I assume that to be the exception for most HPC clusters at least, right?

**Comment by marksantcroos** [comment]
> Ah, sorry if I was not clear -- I proposed ln -s $WORK/radical.pilot.sandbox $HOME, not to link the individual pilot sandboxes.

I know, I was referring to that.

**Comment by andre-merzky** [comment]
The I don't understand why you think pilots would create different links -- the root sandbox is fixed per resource, how/why would pilots try to  set different ones?  Don't leave me guessing ;)

If user sets an individual sandbox on the description, then the link would not be helpful.  But in this case the user (or at least the app coder) would know the sandbox location anyway...

**Comment by marksantcroos** [comment]
Single $HOME with multiple $SCRATCH/$WORK locations.

**Comment by andre-merzky** [comment]
Do we know such a case?

**Comment by marksantcroos** [comment]
Sites where we have multiple resources, from the top of my head NERSC and SDSC.

**Comment by marksantcroos** [comment]
And on ARCHER, TITAN, $HOME is not visible.

**Comment by andre-merzky** [comment]
Thanks, got it...

**Comment by andre-merzky** [comment]
closing as WONTFIX
