### ISSUE TITLE
profile/log tarball creation fails regularly

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#908]
End up with a 0 byte .tgz and the following in bootstrap_1.err:

```
tar (child): gzip: Cannot exec: File exists
tar (child): Error is not recoverable: exiting now
tar (child): gzip: Cannot exec: File exists
tar (child): Error is not recoverable: exiting now
```

This is on Comet.

**Comment by andre-merzky** [comment]
Any insight on what is going on here?

**Comment by andre-merzky** [comment]
Is this still an issue?  I don't see that on comet.

**Comment by marksantcroos** [comment]
Didn't run on comet for a while, but enough happened in that space that its ok to close.
