### ISSUE TITLE
ability to select gpu nodes

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#923]
This got triggered by @antonst for use on Blue Waters.
We hacked up his SAGA installation now, but we need a proper solution.

I'm thinking of adding a flag to the pilot description "gpu=true" / "type=gpu", configure some suffix to the job url per resource, and change the saga adaptor to translate that into the right job description.

**Comment by antonst** [comment]
For completeness, in addition to "gpu=True" and "gpu=False" you might also consider an option "gpu=True or False" / "gpu=Any", e.g. for Blue Waters we have: 
"xe" == "gpu=False";  "xk" == "gpu=True";  "x" (xe or xk non-specific) ==  "gpu=Any"

**Comment by drelu** [comment]
Also, this new feature should be added to the SLURM adaptor to make the GPU nodes on Comet accessible: #SBATCH --gres=gpu:2 

http://www.sdsc.edu/support/user_guides/comet.html

**Comment by andre-merzky** [comment]
Antons, I created a `feature/bw_ppn_xk` branch on both RP and RS.  Could you give that stack a try?  Selecting the resource label `ncsa.bw_xk` should now give you GPU nodes.  Can you please repeat the GPU experiment as you did on stampede?

**Comment by antonst** [comment]
Thanks Andre! I have tried  `feature/bw_ppn_xk` branch and at a first glance this seems to work, at least the first cycle finished successfully. For most CUs in STDOUT I am getting:
```
Error selecting compatible GPU all CUDA-capable devices are busy or unavailable
``` 

but! after several such messages workload actually gets executed, at least I see appropriate outputs.

**Comment by andre-merzky** [comment]
How many cores do you specify per CU?

**Comment by antonst** [comment]
16

**Comment by andre-merzky** [comment]
Hmm, not sure where the error could come from - the GPU should not be busy then.  Any idea?

**Comment by antonst** [comment]
but pmemd.cuda actually runs after ~5 secs and produces output!

**Comment by antonst** [comment]
will run outside RepEx to see if there is any difference

**Comment by andre-merzky** [comment]
thanks!

**Comment by antonst** [comment]
No, does not work outside RepEx as well. I get the same message:

```
Error selecting compatible GPU all CUDA-capable devices are busy or unavailable
```

**Comment by antonst** [comment]
Example script for amber only can be found at:
```
https://github.com/radical-experiments/radical.canon/blob/master/amber/medium/trivial-bw-gpu.py
```

**Comment by andre-merzky** [comment]
ok - so that is not an RP problem it seems?  Can you take this up with the CDI folx then?  Thanks!

**Comment by antonst** [comment]
Since for aprun is passed "-n 16", it tries to run the code 16 times on a single GPU, hence the error message. It is possible to multiplex a single GPU by setting some environment variables, but this is not what we want. To get this working to aprun should be passed "-n 1" and the following should be added to job script:

```
source /opt/modules/default/init/bash
module swap PrgEnv-cray PrgEnv-gnu
module add cudatoolkit
```

**Comment by andre-merzky** [comment]
Hmm, wait -- BW is actually not supposed to use aprun, but orte-submit, at least in devel.  What branch are you using?

The module settings can go into the CU pre-exec I assume, right?

**Comment by andre-merzky** [comment]
PS.: not devel, I meant the `feature/bw_ppn_xk` branch ...

**Comment by marksantcroos** [comment]
This sounds like #866 and should be fixed?

**Comment by antonst** [comment]
It is orte, I was using aprun for testing

**Comment by andre-merzky** [comment]
So, do you see the same behavior with a stock agent?  As per Mark's comment, are you using an agent which has https://github.com/radical-cybertools/radical.pilot/commit/7b89290f15ed1dde5313d92f3a76a8b578177f00 included?

**Comment by antonst** [comment]
yes, with orte-submit behaviour is the same, e.g. when a single CU (requesting 1 core) is submitted at a time it works just fine, but multiple CU's end up on a single node, which results in aforementioned error

**Comment by marksantcroos** [comment]
So lets step back. You try to run multiple CUs on one node concurrently and you get GPU locking errors. Isnt that what is supposed to happen? And isn't the solution to specify as much cores per CU so that only one runs per node?

**Comment by antonst** [comment]
Mark, so what are you suggesting as a solution?

**Comment by marksantcroos** [comment]
`cu_desc.cores = N`

**Comment by marksantcroos** [comment]
Andre suggested `pdesc.gpus = N`, analogous to `cores` and I tend to agree now. Let this idea settle for a bit.

**Comment by mturilli** [comment]
The experiments for a publication for the HPC Workflow project depends on GPU support on Titan. The submission deadline for the publication is Sept 23; the deadline to start the experiments for that publication is June 1. On these bases, we should be ready to start to test GPU support on Titan by May 15. 

Please see details at:
https://github.com/radical-collaboration/hpc-workflows/milestones
https://github.com/radical-collaboration/hpc-workflows/milestone/2

**Comment by ibethune** [comment]
@mturilli I understand if you take the feature/gpu branches from RP and Saga then you should be able to request a specific number of GPUs in your pilot.  At the moment there is no plan to do the scheduling aspect, but as long as you set each CU to require 16 cores then you will get one GPU per CU.

**Comment by mturilli** [comment]
Thanks @ibethune. We will initiate testing of feature/gpu branches from RP and Saga on Titan with our two use cases.

**Comment by andre-merzky** [comment]
The scheduling part is now also implemented in the feature/gpu branch.

**Comment by andre-merzky** [comment]
This is implemented and merged
