### ISSUE TITLE
make python modules requirements lrms / lm specific

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#926]
E.g., on non-spark, we dont want to install spark.
(Same thing for ORTE)

**Comment by andre-merzky** [comment]
I am not sure I understand what the requested action is.

**Comment by andre-merzky** [comment]
ping?

**Comment by iparask** [comment]
I think the resource config to the agent solves this issue. Right Mark?

**Comment by marksantcroos** [comment]
Currently because of the way we load the components/modules, all possible python modules become a requirement for every installation of RP. We probably want to limit the loading of Spark only to when Spark is going to be used.

**Comment by andre-merzky** [comment]
spark is not a python module, and this is not loaded as such.

I agree with the general point I guess -- we only want to install things into the pilot sandbox which are going to be used...

**Comment by andre-merzky** [comment]
Mark, is this actionable at this point?

**Comment by marksantcroos** [comment]
Concrete action is to move the import in the ORTE LIB LM, but its ok to consider that a TODO and not an issue.
