### ISSUE TITLE
Gordon pilots fail to bootstrap with gcc error

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#931]
Reproduced with both master and devel:
```
intel/2013.1.117(49):ERROR:105: Unable to locate a modulefile for 'mkl'
/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1: error while loading shared libraries: libmpfr.so.1: cannot open shared object file: No such file or directory
```

**Comment by mingtaiha** [comment]
Error is reproduced when running the AIMES experiment, using RP 0.39.RC1, radical.utils 0.39.RC1, SAGA 0.40. This occurs shortly after the pilot becomes PendingActive, before the Executing stage.

Last line from bootstrap_1.out
```
can't build gtod binary!
```

Output from bootstrap_1.err
```
/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1: error while loading shared libraries: libmpfr.so.1: cannot open shared object file: No such file or directory
```

**Comment by mturilli** [comment]
This is still happening with RP 0.39RC1. Pilots fail with:
```
/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1: error while loading shared libraries: libmpfr.so.1: cannot open shared object file: No such file or directory
```

**Comment by marksantcroos** [comment]
Do you guys have a usable allocation on Gordon? I don't. The only one I see is the Champion one and that is overdrawn.

**Comment by andre-merzky** [comment]
yes, TG-MCB090174 should work.  I'll give it a spin.

**Comment by andre-merzky** [comment]
We opened an XSEDE ticket for this one,  there is something wrong with either the module files or my understanding of their use...

**Comment by andre-merzky** [comment]
Quick update: an RPM is missing on the compute nodes.  Admins want to fix the configuration, I don't know when that will happen.  Us working around it would require yet another switch in the config file and bootstrapper, so I'd rather wait for a couple of days before jumping the gun.

If somebody urgently needs to use gordon, here is the workaround:

 - create a file named 'cc' with this content (for example in `$HOME/bin/`:
```
#!/bin/sh
gcc "$@"
```
 - `chmod 0755 $HOME/bin/cc`
 - in `resource_xsede.cfg`, change the `pre_bootstrap_1` to contain:
   - `export PATH=$HOME/bin/:"$PATH"`
   - module load gnu

This will fake a workable `cc` by rerouting the command to `gcc`.

**Comment by andre-merzky** [comment]
Gordon has been fixed (the admins installed the missing lib), RP now works again.
