### ISSUE TITLE
jpos error in mac OS

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#935]
https://github.com/radical-cybertools/radical.pilot/blob/fc047d9821b26ce2026fb7c0da7c9dc43d5cd7a4/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L2832

I noticed that in mac OS, -f must be omitted otherwise you get an error.

**Comment by andre-merzky** [comment]
https://docs.python.org/2/library/os.html#os.readlink ;)

**Comment by marksantcroos** [comment]
Can this be closed?

**Comment by iparask** [comment]
Can you check [this](https://github.com/radical-cybertools/radical.pilot/blob/feature/yarn_multinode/src/radical/pilot/agent/lm/yarn.py#L216)?

Lines 216 - 225

**Comment by andre-merzky** [comment]
that looks like dark magic -- but if that works.. :)

**Comment by georgeha** [comment]
Using os.readlink I get  this:
'/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java'

while using giannis' solution:
'/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java'

**Comment by iparask** [comment]
Mac people, which is the correct java path?

@andre-merzky os.path.realpath in linux at least follow all the symlinks until the actual path. I hoped it would do the same in MacOS.

Apparently not.

**Comment by andre-merzky** [comment]
```
cd /tmp
touch a
ln -s a b
ln -s b c
ln -s c d
python -c 'import os; print os.path.realpath("/tmp/d")'
```

This seems to work correctly on MacOS, resulting in `/private/tmp/a`.  Is that different for you?

**Comment by georgeha** [comment]
No, it doens't work
1. jpos = subprocess.check_output(['readlink', -f, '/usr/bin/java']).split('bin') ,  -f argument doesn't exists in Mac OS and if I remove this, I have this error:
/Users/giorgos/radical.pilot.sandbox/rp.session.gxatz.local.giorgos.016864.0007-pilot.0000/spark-1.5.2/sbin/../    bin/spark-class: line 77: /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java/bin/java:     Not a directory
Spark-class adds /bin/java to the $JAVA_HOME variable.

How about using an if argument and set $JAVA_HOME in a different way for Mac os, using sys.platform?

**Comment by andre-merzky** [comment]
I understand that 'readlink -f' is not supported in MacOS.  The question is if Python's `os.path.realpath` works.  But maybe you meant that?  If it doesn't, would you mind running the above sequence of commands in a shell, and send the output, along with the output of:

```
uname -a
python -V
```

Thanks, Andre.

**Comment by georgeha** [comment]
uname -a
Darwin gxatz.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
python -V
Python 2.7.5

realpath returns this path:
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java

but I have the following error:
/Users/giorgos/radical.pilot.sandbox/rp.session.gxatz.local.giorgos.016864.0007-pilot.0000/spark-1.5.2/sbin/../ bin/spark-class: line 77: /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java/bin/java: Not a directory

I found in spark-class file these commands:
# Find the java binary
if [ -n "${JAVA_HOME}" ]; then
  RUNNER="${JAVA_HOME}/bin/java"
else
  if [ `command -v java` ]; then
    RUNNER="java"
  else
    echo "JAVA_HOME is not set" >&2
    exit 1
  fi  
fi

So I guess that these commands add an extra /bin/java??

**Comment by andre-merzky** [comment]
George, would you mind running this sequence, please, only so that we are on the same page?  Thanks!

```
cd /tmp
touch a
ln -s a b
ln -s b c
ln -s c d
python -c 'import os; print os.path.realpath("/tmp/d")'
```

**Comment by georgeha** [comment]
I tried that I have the same output with you

**Comment by andre-merzky** [comment]
Well, then os.path.realpath is what you in fact want to use, right?  Now, why you have the 'is not a directory' error: I would think you need to strip the last two path elements (bin/java) so as to derive the JAVA_HOME dir:

```
java_bin  = radical.utils.which('java')
java_home = os.path.dirname(os.path.dirname(os.path.realpath(java_bin)))
```

On MacOS, that gives for me:

```
cameo:~ merzky$ source ve/bin/activate
(ve)cameo:~ merzky$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import radical.utils as ru
>>> java_bin  = ru.which('java')
>>> print java_bin
/usr/bin/java
>>> import os
>>> java_home = os.path.dirname(os.path.dirname(os.path.realpath(java_bin)))
>>> print java_home
/System/Library/Frameworks/JavaVM.framework/Versions/A
```

Is that the path you are looking for?

**Comment by andre-merzky** [comment]
Closing for lack of feedback.
