### ISSUE TITLE
Support for folder transfer in RP

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#936]
Currently, only file transfer seems to be supported. It would be very useful to support transfer of folders as well, both at unit-level and pilot-level.

**Comment by marksantcroos** [comment]
This is semantically not as simple as it sounds and was a conscious design decision not to support.

That doesn't mean this decision can't be revisited of course. A similar discussion arose around wildcards.

**Comment by andre-merzky** [comment]
I would assume that both (folders and wildcards) are essentially SAGA level features which we would need to implement/test?  I cannot easily think of RP adding further semantics...

**Comment by marksantcroos** [comment]
Its not so much about adding semantics, more about maintaining semantics.

We currently assume a file is an atomic non-mutable unit once it is passed to the control of RP.

In principle you can do the same with directories, but it requires more care with regards to consistency about the content of it.

**Comment by jhprinz** [comment]
I had a similar request and in my specific case I do not require transfer of folders to or from the application. A soft link of a folder from the staging area to the unit is all I need. Would this also be SAGA level? 

I think the pilot could take care of that on the remote machine, at least it could do that, right? I can still use the `pre_exec` phase to do the same thing. It just seems more consistent when all of the file preparations can be done in the same way.

**Comment by andre-merzky** [comment]
This is now implemented via tar staging.
