### ISSUE TITLE
RP installation fails on Stampede VE

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#937]
While the `bootstrapper_1` runs and tries to install pyzmq it issues a syntax error. As a result RP installation fails on Stampede.

The bootstrapper's log is [here](https://gist.github.com/iparask/1f5c5a78a6ab8e9f09bd)

**Comment by marksantcroos** [comment]
The bootstrapping seems to complete fine. Whats the actual problem?

**Comment by marksantcroos** [comment]
Given your other ticket, does this mean you dont have a bootstrapping issue?

**Comment by iparask** [comment]
ok you are right. I just found the rp installation in the VE
