### ISSUE TITLE
CU Pre Exec Conditions on Stampede

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#938]
Is there a way to make sure if the cu pre_exec conditions are actually enabled? I am loading a module and I am echoing the LOADEDMODULES env from the same CU and it is empty or at least that is what I think. Also if I add a `module list` in the pre exec there is nothing in the STDERR output of the CU.

Is this something expected?

**Comment by iparask** [comment]
Actually, this turns like being a bug. I try to run the following CU:

```
cud.pre_exec    = [ 'module load TACC', 'module load python/2.7.9']
cud.executable  = 'python'
cud.arguments   = ['-c','import numpy as np;print np.__version__;']
```

and it fails to print the NumPy version. I also tried it on Comet and again nothing. If I run the sh script of the CU a command prompt on a compute node it runs correctly.

Either I am doing something extremely stupid or something weird is happeing.

**Comment by marksantcroos** [comment]
A couple of things:

- pre_exec works fine, its the behavior of `module` on stampede compute nodes that confuses matters here;
- When you call 'python', it picks up the python from the pilot ve, which doesnt have numpy;
- The workaround is: `cud.executable = '/opt/apps/intel15/python/2.7.9/bin/python'`;
- We need to investigate how to get a proper functioning `module` command in the CU.

**Comment by iparask** [comment]
So if I want to use a module in any machine I need to call python from the whole path?!
It worked! Thank you

**Comment by vivek-bala** [comment]
> We need to investigate how to get a proper functioning module command in the CU.

I think Stampede's been changing loaded modules. Upon login, I don't have any modules loaded. I need to do a ```module reset``` in order to get the usual 4 modules back. I saw the same on compute nodes.

The following worked:
```
cudesc.pre_exec = ['module reset','module load python/2.7.9']
cudesc.executable  = "python"
cudesc.arguments   = ['-c','import numpy; print numpy.__version__']
```

**Comment by marksantcroos** [comment]
Thanks Vivek! Thats certainly better than hardcoding the path.

**Comment by andre-merzky** [comment]
The agent does a manual `deactivate()` for units.  Should we also reset the PATH so that python is not picked up from the pilot VE?

**Comment by andre-merzky** [comment]
The VE leakage is fixed now.
