### ISSUE TITLE
syntax for file url specification for pilot staging

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#940]
Specifying source file path as './file1.txt' does not seem to be picked up while pilot staging. 

```
shared_data = {
'source': 'file:///./file1.txt',
'target': 'staging:///file1.txt',
'action': rp.TRANSFER
}
```

But this works in directives for unit staging. I guess the "." is internally expanded in this case.

**Comment by vivek-bala** [comment]
The same for pilot staging would be useful and consistent.

**Comment by marksantcroos** [comment]
What would you expect `file:///./file1.txt` to refer to?

**Comment by andre-merzky** [comment]
presumably this is supposed to be a path relative to `$PWD`...

**Comment by andre-merzky** [comment]
see also #1192

**Comment by andre-merzky** [comment]
This is fixed with custom schemas.
