### ISSUE TITLE
IP retrieval  on the SPARK feature

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#943]
Hello George,

In line [3107](https://github.com/radical-cybertools/radical.pilot/blob/feature/spark/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3107) you find out the master node ip using a web service. You can use the hostnames of the nodes to do that

**Comment by georgeha** [comment]
Thanks Yiannis,

Fixed.
