### ISSUE TITLE
OSG: zeromq build fails at FIU_HPCOSG_CE

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#946]
```
In file included from bundled/zeromq/src/address.cpp:31:

bundled/zeromq/src/address.hpp:33:18: error: string: No such file or directory

bundled/zeromq/src/address.cpp:38:19: error: sstream: No such file or directory
```

**Comment by andre-merzky** [comment]
I was about to add that exclusion to the OSG example.  Should we rather put those unattractive sites into the resource config, possibly?

**Comment by marksantcroos** [comment]
Ideally yes, but I wouldn't spend my time there now.

**Comment by andre-merzky** [comment]
ack

**Comment by marksantcroos** [comment]
fwiw, that particular exclusion is already in the devel branch.

**Comment by andre-merzky** [comment]
Mark, I am going to close this one -- exclusions seem to be the way to go for now...
