### ISSUE TITLE
RC Testing: couldn't pull rp repository properly

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#950]
When I used the command `git clone git@github.com:radical-cybertools/radical.pilot.git rp` to try and pull the repository, I get this error:

`Cloning into 'rp'...`
`Permission denied (publickey).`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights`
`and the repository exists.`

However, I cloned it using this instead: 

`git clone https://github.com/radical-cybertools/radical-pilot rp`

The same goes for RU.

**Comment by andre-merzky** [comment]
What is the github ID you are using?  Did you register your ssh key, and is it the correct key used?  

This sounds more like a github/ssh setup issue than a radical pilot issue...
