### ISSUE TITLE
RADICAL_LOG_TARGETS appears to be broken

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#954]
RP 0.39RC1

The following seems not to be working:
```
export RADICAL_VERBOSE=DEBUG
export RADICAL_LOG_TARGETS=`pwd`/logs/radical_debug.log
```
DEBUG output is sent to STDOUT but not written to \`pwd\`/logs/radical_debug.log

**Comment by andre-merzky** [comment]
that should be `RADICAL_LOG_TARGET` (singular).

**Comment by mturilli** [comment]
That fixed it (documented?)

**Comment by andre-merzky** [comment]
No, the log targets are really an undocumented  feature.  If you think this is stable enough to document, we can do so I guess...
