### ISSUE TITLE
Add support for darter

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#955]

**Comment by mturilli** [comment]
Any update about when RP will support Darter?

**Comment by marksantcroos** [comment]
Shall I take this one Andre? Seems like a better fit.

**Comment by andre-merzky** [comment]
Thanks Mark, that would help!

**Comment by marksantcroos** [comment]
I did the first needful things from RP perspective, but ran into an issue that (gsi)sftp doesn't work as advertised. Have opened a ticket with the helpdesk for that.

**Comment by marksantcroos** [comment]
Won't happen anymore.
