### ISSUE TITLE
No example scripts on Examples page in RP Read the Docs page

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#957]
In each of the four types of examples listed in, there is a line that says "Download the file *.py with the following command:". However, there is no download link to any of the scripts. This occurs across the "latest", "stable", and "release-v0.37" versions of Read the Docs. Where can I find the files for testing?

I'm talking about the examples found here: http://radicalpilot.readthedocs.org/en/latest/tutorial/index.html

**Comment by Nikhil-Shenoy** [comment]
The files in question are `simple_bot.py`, `chained_tasks.py`, `coupled_tasks.py`, `mpi_tasks.py`

**Comment by andre-merzky** [comment]
Thanks Nikhil, this is  fixed now!
