### ISSUE TITLE
Multiple pilots example on localhost

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#960]
How are we supposed to run the multiple pilots example?

I run it in localhost based on the testing protocol, but it submitted only one pilot. Is there some other way to do it?

It is not clear from the protocol.

Thank you,
Giannis

**Comment by andre-merzky** [comment]
The codes accept multiple resource tags on command line, so, for example:

```
python 03_multiple_pilots.py local.localhost xsede.stampede epsrc.archer
```

would run test 03 on these three resources....

**Comment by andre-merzky** [comment]
Well, I should add, as a corollary,  the following would run 3 multiple pilots on *one* resource:

```
python 03_multiple_pilots.py xsede.stampede xsede.stampede xsede.stampede
```

**Comment by iparask** [comment]
Thank you!
