### ISSUE TITLE
no lockfile during installation of rp_install

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#967]

**Comment by andre-merzky** [comment]
do you mean that lockfile is missing, or that it should go?

**Comment by marksantcroos** [comment]
There is no lock during that phase.

**Comment by andre-merzky** [comment]
ok, thanks

**Comment by andre-merzky** [comment]
But wait, rp_install lives in the pilot sandbox, so it is privat to the pilot.  Why would we want to lock it?

**Comment by marksantcroos** [comment]
Only in 'debug' mode, not in 'local' mode.

**Comment by andre-merzky** [comment]
Ah got it, thanks.

**Comment by andre-merzky** [comment]
Has been addressed indirectly - rp_install is now private
