### ISSUE TITLE
Merge the configurations in the pilot launcher.

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#968]
Is this okay?

**Comment by andre-merzky** [comment]
Yes, thanks, I'll look into this.

Mark, for context: Iannis needs to specify module load commands etc. when starting the spark cluster.  We have that all set in the resource config -- but those settings are not (easily) visible to the agent, so the proposal is to merge the resource config into the agent config before staging it to the resource.

**Comment by andre-merzky** [comment]
Iannis - that is implemented in 190f76f.  Can you give that a try?

**Comment by marksantcroos** [comment]
I still don't really understand. Isn't this similar to the prebootstrap_2 feature?

**Comment by andre-merzky** [comment]
Assume the LRMS_SPARK wants to call, in its config hook:
```
ssh node_1 'module load python/2.7.4; python spark_startup.py'
```

and wants, for reasons, use the same module load sequence as the pilot.  How would it know that sequence?  The bootstrapper can enact the pre_bootstrap_n ones, but can't tell them to the agent, so that the agent can use them, too...

**Comment by marksantcroos** [comment]
Right, Im questioning exactly that.
Is the agent now going to 'grep' for `^module load python.*` in the resource config?

**Comment by andre-merzky** [comment]
It's programmatically available in the agent config now, that is the point, so it can access it as
`self._agent_cfg['resource_cfg']['pre_bootstrap_2']`.  The grep in some files is exactly what we try to avoid...

**Comment by marksantcroos** [comment]
Same same no difference. There are still no semantics.

There is no _need_ to run `module load python`, that's just an artifact. We should be discussing what is really needed to run spark.

**Comment by andre-merzky** [comment]
I leave it to Ioannis to answer that -- but I have no reason to question his judgement at this point, really.  Also, in general, I don't find it too far fetched to inform the agent about the configuration of the resource it is running on.  In fact, that would make the agent config simpler in some respects, as we already copy quite a number of fields from one to the other:
https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/controller/pilot_launcher_worker.py#L387 and https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/controller/pilot_launcher_worker.py#L662

**Comment by iparask** [comment]
In order to run correctly a multinode spark cluster the daemons that are started on all the nodes should use the same python subversion and to provide the path to the python executable that will be used. If an explicit path is not set in the spark environment the default will be used.

Also what I found out is that even if the agent does a which python to find the path, that is not enough to use that executable correctly.

Does this answer your question? I will provide more information later

**Comment by andre-merzky** [comment]
I am closing this due to lack of feedback.  Spark/Yarn branches are about to be consolidated.
