### ISSUE TITLE
Missing Agent States in get_session_frames

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#974]
I am using `get_session_frames` but I do not get the stages AgentSchedulingPending and AgentScheduling states. Are they the same as Scheduling and Unscheduled, or are they not included in the function?

Here are the versions of tools I am using:
RP: 0.40.1
SAGA: 0.40.1
Radical Utils: 0.40

Thanks for the help

**Comment by andre-merzky** [comment]
state profiling has been completed by now (in the split-module branch at least)
