### ISSUE TITLE
doubled info entry aec_pub_u

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#976]
```
Failed to pre-process data for session rp.session.radical.marksant.016864.0025 (doubled info entry aec_pub_u (uid:unit.000070.clone_00222))
```
```
137.0068,agent_1.AgentExecutingComponent.0.child:Dummy-1,unit.000070.clone_00222,,passed,ExecWatcher picked up unit
137.0068,agent_1.AgentExecutingComponent.0.child:Dummy-1,unit.000070.clone_00222,Executing,advance,
137.0069,agent_1.AgentExecutingComponent.0.child:Dummy-1,unit.000070.clone_00222,Executing,publish,
137.0071,agent_1.AgentExecutingComponent.0.child:Dummy-1,unit.000070.clone_00222,,passed,ExecWatcher picked up unit
137.0071,agent_1.AgentExecutingComponent.0.child:Dummy-1,unit.000070.clone_00222,Executing,advance,
137.0072,agent_1.AgentExecutingComponent.0.child:Dummy-1,unit.000070.clone_00222,Executing,publish,
```

**Comment by andre-merzky** [comment]
yeah, that should not happen.  Would you please attache the used agent.cfg?

**Comment by andre-merzky** [comment]
Do you clone in two places?

**Comment by marksantcroos** [comment]
> Would you please attache the used agent.cfg?

[rp.session.radical.marksant.016864.0025_agent_0.cfg.txt](https://github.com/radical-cybertools/radical.pilot/files/159882/rp.session.radical.marksant.016864.0025_agent_0.cfg.txt)


> Do you clone in two places?

No, just one.

**Comment by marksantcroos** [comment]
By looking at RP code, its likely an ORTE issue. As I think this can only happen when the callback gets called twice.

**Comment by marksantcroos** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/feature/ortelib/src/radical/pilot/agent/executing/orte.py#L243

**Comment by andre-merzky** [comment]
That would explain it nicely - I have not seen duplicated units in any of the earlier micro benchmarks.  But I would not exclude a race on the cloning or whatever, so please let me know if I should have a closer look.  FWIW, the config looks very sane, AFAICS.  Is the problem reproducible?

Thanks, Andre.

**Comment by marksantcroos** [comment]
> Is the problem reproducible?

Is doesn't happen often (maybe even only once) and it happened in a large run.

**Comment by andre-merzky** [comment]
Mark, is this still an issue?

**Comment by marksantcroos** [comment]
Forgot whether I worked around it, or whether I fixed it, but lets close for now.
