### ISSUE TITLE
Support for bridges-pylon.psc.xsede.org

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#980]

**Comment by mturilli** [comment]
Update from XSEDE: The system is at the end of its acceptance phase. Access should be enabled by March 17 2016, possibly earlier. Ssh login as reported via bridges.psc.edu.

**Comment by ibethune** [comment]
Consider for next release

**Comment by ibethune** [comment]
@shantenujha can you let me know if there is any reason why we should be supporting bridges in the context of the next release i.e. external users or group members who will start using it.  If not, we keep it out of scope.

**Comment by shantenujha** [comment]
@ibethune I think we should start supporting Bridges, not necessarily 0.46 but as soon as convenient --- all things considered. XSEDE allocation are 'gently nudging' us to Bridges (we've ended up with >2M core hours). Their reasons may be non-technical and purely load-balancing across different XSEDE resources.

**Comment by ibethune** [comment]
OK, I'll leave this for the next release then, since split_module + gpu + ongoing fixes is enough for 0.46 IMO.

**Comment by vivek-bala** [comment]
Is it possible to move this to high priority? The main reason is the long waiting times on the other xsede machines (stampede, comet, supermic). It will be useful to have another machine where the queue is hopefully frendlier.

**Comment by andre-merzky** [comment]
A first shot at brodges support is in `feature/bridges` - but ironically (given the last comment) I can't get any jobs through the queue for further testing :P 

Question for clarification: the ticket says `bridges-pylon`, not `bridges`, but pylon is a storage point.  Is that a typo or am I missing something use case specific here?

**Comment by shantenujha** [comment]
Have you used XDMoD to determine queue waiting time distributions (over time and job size)?

**Comment by andre-merzky** [comment]
I stumbled over a connectivity snafu on bridges which prevents the pilot from connecting to the DB. An XSEDE ticket was opened. This RP issue will be on hold until that ticket is solved.

**Comment by mingtaiha** [comment]
Will Bridges support be part of the release after next (v0.47)?

**Comment by andre-merzky** [comment]
closing this ticket in favor of #1353.
