### ISSUE TITLE
Stampede: different environment with mpi enabled vs disabled

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#984]
I am encountering different software environment on stampede with mpi enabled vs disabled.

```
cud = rp.ComputeUnitDescription()
cud.pre_exec = ['module load TACC','module load intel/15.0.2','module load boost','module load cxx11','module load gromacs']
cud.executable = 'gmx'
cud.arguments = 'grompp'
```

fails with 
```
/work/02734/vivek91/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.016876.0016-pilot.0000/unit.000000/radical_pilot_cu_launch_script.sh: line 15: gmx: command not found
```

But the same CUD with MPI enabled (and thus using mpirun_rsh on stampede) is able to find the gromacs executable.

```
cud = rp.ComputeUnitDescription()
cud.pre_exec = ['module load TACC','module load intel/15.0.2','module load boost','module load cxx11','module load gromacs']
cud.executable = 'gmx'
cud.arguments = 'grompp'
cud.mpi =True
```

I am seeing this for (non-gromacs) python scripts as well where I use numpy. Once I set ```cud.mpi=True``` numpy is detected, otherwise the script fails because it can't find numpy.

Seems to be the cause for https://bitbucket.org/extasy-project/extasy-workflows/issues/5/gmxcoco-workflow-on-stampede-gmx-command as well.

**Comment by marksantcroos** [comment]
Does the module purge trick work that you tried in other situations?

**Comment by vivek-bala** [comment]
If I try a ```module list``` in the first case, I don't see any modules listed (no output).

**Comment by vivek-bala** [comment]
```
cud = rp.ComputeUnitDescription()
cud.pre_exec = ['module load TACC','module load intel/15.0.2','module load boost','module load cxx11','module load gromacs']
cud.executable = '/bin/bash'
cud.arguments = ['-l','-c','module list']
```

Output: ```No modules loaded```

**Comment by vivek-bala** [comment]
Also, for now my solution has been to set mpi=True in all CUDs.

**Comment by marksantcroos** [comment]
Try prepending this to the pre_exec of your cu:
```
source /opt/apps/lmod/lmod/init/sh
```

**Comment by andre-merzky** [comment]
This is assumed to be addressed by the latest env fixes.
