### ISSUE TITLE
"WARNING : skip cb for incomple unit (unit.000018: Scheduling)"

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#986]
What does warning:

WARNING : skip cb for incomple unit (unit.000018: Scheduling)

mean?

**Comment by andre-merzky** [comment]
It means a race condition was detected and averted, but you missed a callback because of this.  Basically, we got a uni state change but  do not know for which unit.  This will be fixed in the refactoring, and is near impossible to fix in the current code.
