### ISSUE TITLE
getting_started_osg.py - Unable to execute past 150 sequential CUs

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#989]
I tried to run getting_start_osg.py with 1 pilot with N sequential CUs, but I have found that I am unable to run more than 150 CUs. When I do, pilot closes with some number of CUs left in the queue.

**Comment by marksantcroos** [comment]
Whats the lifetime of the pilot and the duration of the CUs? In other words, does it goes against what you expect?

**Comment by mingtaiha** [comment]
I extended the wall time of the pilot and it seems to have fixed the problem. I didn't expect the pilot to fail so early as the execution time is less than that of the requested wall time (1hr). Sorry for the false alarm.

**Comment by andre-merzky** [comment]
out of interest: what was the runtime for the individual CUs?

**Comment by mingtaiha** [comment]
About 16-17 seconds per CU.

**Comment by andre-merzky** [comment]
Was there any data staging involved?

**Comment by mingtaiha** [comment]
There was no data staging. The time for each CU includes the overhead for entering and exiting the data staging states.
