### ISSUE TITLE
getting_started_osg.py - BulkWriteError

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#991]
I have been running getting_started_osg.py and have encountered a BulkWriteError at 1 Pilot, 128 CUs. I unfortunately did not record the error message and have been unable to reproduce it. When I encounter the error again, I will attach the error message.

It should be noted that I am using the most up-to-date version of RP.

**Comment by andre-merzky** [comment]
Yes, capturing the error message, and if possible the output when running under `RADICAL_PILOT_VERBOSE=DEBUG`,  would be great.  If you don't mind, we'll leave the ticket idle until we are able to gather more information?

**Comment by andre-merzky** [comment]
This specific error is fixed in the scope of the split branch.
