### ISSUE TITLE
python_dist config entry & Anaconda

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#992]
Hello guys,

do you mind if I made the ```python_dist``` entry in the config files mandatory? 

I would also like to start duplicating the configurations for Anaconda support in the remote target. Do you agree?

Thank you,
Giannis

**Comment by andre-merzky** [comment]
> I would also like to start duplicating the configurations for Anaconda support in the remote target. Do you agree?

I am not sure I understand what you mean by that - would you elaborate, please?

**Comment by iparask** [comment]
The python_dist entry in the config files shows the type of python distribution that the agent will use. If we want to be able to use anaconda in any machine we should duplicate the entry of that machine.

**Comment by andre-merzky** [comment]
Ah, you mean like adding an 'xsede.stampede_anaconda' to the existing 'stampede.xsede'  entry?  Hmm,  does that serve any purpose, beyond 'we can do that'?  An agent would not behave any different, and would not be configured differently either...

**Comment by iparask** [comment]
Based on our discussion, I am renaming this ticket and moving forward for making ```python_dist``` mandatory. Is that okay?

**Comment by andre-merzky** [comment]
Ack. Thanks!

**Comment by andre-merzky** [comment]
Iannis, any update on this ticket?

**Comment by iparask** [comment]
Done. PR #1022
