### ISSUE TITLE
getting_started_osg.py - Hang Up in Execution

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#995]
I am trying to run getting_started_osg.py with 1 pilot and 512 CUs. I have given the task a wall time of 10hrs. With 417 CUs left to run, the execution freezes and does not continue. However, according to the OSG queue, the job is considered to be running.

**Comment by andre-merzky** [comment]
Hmm, running some more tests, I seem to be able to confirm this.  Not sure yet what's up...

**Comment by andre-merzky** [comment]
Is this ticket actually different from #989?

**Comment by andre-merzky** [comment]
This is considered obsolete.
